### ISSUE TITLE
no statistics/graphs

### ISSUE THREAD

**Issue by JayBeRayBearGun** [modoboa/modoboa#1000]
Just noticed I don't seem to have the nice graphs displaying the mail statistics. How can I debug this?

**Comment by JayBeRayBearGun** [comment]
on a side note,... despite following instructions I can't change the default modoboa logo on the sign-in page.

**Comment by tonioo** [comment]
First, make sure you installed the rrdtool binary please. About the logo, I suggest you open a dedicated issue if it still persists.

**Comment by JayBeRayBearGun** [comment]
The rrdtool regular package is installed but not the python-rrdtool package if this should be installed then the automatic installer script must have missed it. Could this be the case?

**Comment by JayBeRayBearGun** [comment]
The logo issue is partly resolved. The filename was different as the one referenced. However correcting this did not fix it yet. I'll investigate further.

**Comment by tonioo** [comment]
Do you receive any traffic on this server. If not, the stats will remain empty.

**Comment by JayBeRayBearGun** [comment]
Oh yes, there is plenty of traffic now (this is not on the test domain anymore). There is not even en empty graph, there is just nothing.

**Comment by csmk** [comment]
Try to run the log parser manually. See if there's some kind of error.

Just my 2 cents. Cheers!

**Comment by JayBeRayBearGun** [comment]
You mean grep /var/log/syslog? PS: /srv/modoboa/rrdfiles is empty

**Comment by csmk** [comment]
No, the one in the cronjob. On my server will be like this:

> sudo -u mdb /srv/modoboa/venv/bin/python /srv/modoboa/mdb/manage.py logparser

**Comment by JayBeRayBearGun** [comment]
Ok got it, but where does the ouput go?

**Comment by JayBeRayBearGun** [comment]
Hey guess what,... all of the sudden I have a graph! Does this mean the cron script never ran i.e. failed?

**Comment by csmk** [comment]
Hmm.. It seems so.

**Comment by JayBeRayBearGun** [comment]
Thanks pal! Much appreciated!

**Comment by JayBeRayBearGun** [comment]
On a side note,... do you know if modoboa (or in fact the postfix as it is installed) checks for  SPF?

**Comment by csmk** [comment]
Did you use modoboa's installer? If yes, then I think Amavis was installed for you, so yeah, SPF will be checked.

**Comment by JayBeRayBearGun** [comment]
@tonioo Looking at crongtab files now,... noticed that the letsencrypt one will not run due to missing EOL at EOF

**Comment by JayBeRayBearGun** [comment]
@csmk yes I did,... i was about to look at  postfix-policyd-spf-python but no need if amavis takes care of it then.

**Comment by JayBeRayBearGun** [comment]
hmm,...don't see anything spf related in my recently received emails though or does amavis not write something to the mailheader?

**Comment by JayBeRayBearGun** [comment]
seems like it is spamassasin not amavis doing the SPF checking

**Comment by Arvedui** [comment]
spamassasin does not enforce spf policies, it takes them into account for the score, but a mail with failed spf may still pass as ham.
If you want to enforce spf something like postfix-policyd-spf-python is the only sensible way to go, because you do not want postfix to accept mail with failed spf checks.

**Comment by tonioo** [comment]
@JayBeRayBearGun Can we close the stats issue?

**Comment by JayBeRayBearGun** [comment]
YES! by they I think I deserve a price opening (and closing) issue #1000  :)

**Comment by tonioo** [comment]
@JayBeRayBearGun ;)

**Comment by JayBeRayBearGun** [comment]
PS: I noticed a massive amount of bounced messages from about 11pm yesterday. 

Jan 11 16:18:03 ns1 postfix/bounce[9813]: 00B287F66C: sender non-delivery notification: 250A37F66D
Jan 11 16:18:03 ns1 postfix/smtp[9812]: 250A37F66D: to=<root@mail.rhebergen.net>, relay=none, delay=0.05, delays=0.03/0.01/0.01/0, dsn=5.4.6, status=bounced (mail for mail.rhebergen.net loops back to myself)

not really a bug,... although it bugs me :)

**Comment by tonioo** [comment]
You can remove mail.rhebergen.net from mydestination (actually you can
empty this setting) and declare this domain into modoboa with and
account or an alias to receive messages sent to root@mail.rhebergen.net.
Look at /etc/postfix/main.cf.

**Comment by JayBeRayBearGun** [comment]
Ah, ok,... I think I grok it,... will look at it asap. On a side note, I understand alias working on the mail reception side, but how to you use it for sending? Or does an alias not work like that and do you have to create an actuall identitiy for that other account/domain?

**Comment by tonioo** [comment]
By default with Modoboa, any alias pointing to a local address can be used as a sender address. If you want to add non local identities to an account, look at the sender address field.

**Comment by JayBeRayBearGun** [comment]
Got it!

**Comment by JayBeRayBearGun** [comment]
Ok, found it but not quite. I filled out the sender field (for the address from the other domain) But how do I actually use it? Does the webmail interface support this? (perhaps I am looking in the wrong place).

**Comment by tonioo** [comment]
The webmail does not support it atm but you can open an issue on the appropriate repository to keep track of it.

**Comment by JayBeRayBearGun** [comment]
OK
