### ISSUE TITLE
Mailbox limit reached when adding account whereas it can not be reached (setted 'unlimited' ie. -1)

### ISSUE THREAD

**Issue by mpirio** [modoboa/modoboa#1004]
I use Modoboa 1.6.2. Default Admin's limits are enable like this:

![adminlimits](https://cloud.githubusercontent.com/assets/16302192/21991031/596dd86c-dc11-11e6-9ae4-f3fe3a65ec5e.png)

I use a DomainAdmin account with its mailboxes and aliases limits set to -1:

![domainadminlimits](https://cloud.githubusercontent.com/assets/16302192/21991147/bfb894a4-dc11-11e6-8e96-d2d5b5e3ff4c.png)

But when I want to add new mailbox, i have this message:

![limitreached](https://cloud.githubusercontent.com/assets/16302192/21992578/460f50d8-dc17-11e6-8e8a-262765a3a25a.png)

Thanks for your help,

**Comment by mpirio** [comment]
I tried to find where the mailboxes limits check was done. I find a class `UserObjectLimit and its method `is_exceeded()` in `modoboa/limits/models.py` but i do not find where 'unlimited' limit (-1) is checked...

I modified the method like this:

```Python
def is_exceeded(self, count=1):
        """Check if limit will be reached if we add count object(s)."""
        return ((self.max_value != -1) and (self.current_value + 1 > self.max_value))
```

That works. But i do not know if it's the best solution...

**Comment by tonioo** [comment]
Looks like the unlimited case is not supported since the last refactoring... Thank you for reporting this!
