### ISSUE TITLE
Possibility to change default password

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa#1007]
When a domain administrator is automatically created by Modoboa for a new domain, the default password is `password`. This value should be customizable.

**Comment by daks** [comment]
In other software (Jenkins if I remember correctly), I saw the following behaviour: a random password is generated and put in a file in the local filesystem. This way is secured and only the administrator doing the installation can get it.
(my 2 cents)

**Comment by tonioo** [comment]
Random passwords is something I plan to add but this is just a quick answer to people who want to change the value used for fresh domain administrators.
