### ISSUE TITLE
Spamfilter improvements

### ISSUE THREAD

**Issue by dragon2611** [modoboa/modoboa#1010]
These are things I'd like to see with the spamfilter if possible in future releases.

1) Notification don't appear to work at the moment, means manually logging in and checking the quarantine, ideally an email sent at a certain time showing an quarantine summery

2) Feedback loop, there doesn't seem to be any obvious way to tell the spam filter it missed something, I don't want all clean emails in the quarantine and I've been led to believe the plugin to support learning from the junk folder in IMAP isn't suitable for production use.

3) Trusted IP's, So if using an external spam filtering service you can turn it off for any email that came through the service, but keep it on for anything else (Might not be possible to firewall SMTP if the modboa server hosts other domains)

**Comment by tonioo** [comment]
@dragon2611 Looks like your requests are related to the amavis plugin. Could you please move your issue to the appropriate repository?

**Comment by dragon2611** [comment]
I will repost there, I wasn't sure if it was all handled by the plugin or if some of it would be part of the core.
