### ISSUE TITLE
Aliases not working at all

### ISSUE THREAD

**Issue by ktechmidas** [modoboa/modoboa#1011]
Hi Modoboa, I'm running Ubuntu 16.04 and I installed using the default installer https://github.com/modoboa/modoboa-installer yesterday. I'm all up and running now with admin@ktechmidas.net receiving email, but I have tried to add a catch-all which doesn't work (@ktechmidas.net alias pointing to admin@ktechmidas.net) then I tried to add a specific email doing the same (sales@ktechmidas.net pointing to admin@ktechmidas.net) and I still get the following:

Final-Recipient: rfc822; sales@ktechmidas.net
Action: failed
Status: 5.1.1
Remote-MTA: dns; mail.ktechmidas.net. (47.91.16.120, the server for the domain ktechmidas.net.)
Diagnostic-Code: smtp; 550 5.1.1 <sales@ktechmidas.net>: Recipient address rejected: undeliverable address: host mail.ktechmidas.net[private/dovecot-lmtp] said: 550 5.1.1 <sales@ktechmidas.net> User doesn't exist: sales@ktechmidas.net (in reply to RCPT TO command)

**Comment by tonioo** [comment]
Hi,
try to delete the file `/var/lib/postfix/verify_cache.db` and to reload postfix, it should work.

**Comment by ktechmidas** [comment]
Hi, that worked! Thanks, you can close this now.

**Comment by tonioo** [comment]
@ktechmidas Sorry I didn't find another to contact you but could you please contact me?
