### ISSUE TITLE
Dovecot Replication

### ISSUE THREAD

**Issue by qskousen** [modoboa/modoboa#1014]
I am trying to set up Dovecot replication so I can run 2 mailservers as primary and backup, so a server hardware failure does not result in loss of email capabilities. Ideally both of them would be running Modoboa and an external IP will float between them as needed if one has downtime. Dovecot replication will work great to sync email both ways, so if one gets an email while the other is down, it will be synced when it comes back up.

However, I am having a hard time getting the replication to work. In particular, the `vmail` user (who owns the mailboxes and thus needs to be the one who replicates) cannot list the users. If I am logged in as `vmail` and try `doveadm user '*'` it returns:
```
Error: User listing returned failure
Fatal: user listing failed
```

I am not sure what the issue is. I can connect to Postgres while logged in as `vmail` using the credentials specified for Modoboa and query the `core_user` table just fine. Can anyone give any direction on this? Is there something else I could/should be using to accomplish this task?

**Comment by tonioo** [comment]
Looks like vmail user can't access the socket used to retrieve user list. Open the `/etc/dovecot/conf.d/10-master.conf` and modify `auth-userdb` as follows:
```
  unix_listener auth-userdb {
    #mode = 0666
    user = vmail
    #group =
  }
```
Then reload dovecot.

**Comment by qskousen** [comment]
Thanks, that worked!

**Comment by adeklanin** [comment]
Hello @qskousen would mind share your configuration on how to do dovecot replication with modoboa? I mean like VPS setup, are you separate the DB? Or is there place where cloud start digging on this topic? For your consideration I'm new on mail server setup. Thanks
