### ISSUE TITLE
Login with email alias fails

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa#1016]
From other mail systems, i.e. ISPConfig, I am used to the notion to be able to login to IMAPS and SMTPS also with alias addresses and/or domains. This is useful for migrations, where mailboxes don't need to swap messages and just append new domains.

This requires some fiddling with the postfix and dovecot SQL queries, I guess.

**Comment by tonioo** [comment]
Are you talking about SMTP/IMAP connections only? Or do you include the access to the web interface?

**Comment by almereyda** [comment]
I was implying, as authentication of it happened via IMAP, no?, access to
the web interface, too. Especially if it uses its own SQL queries, of
course.

**Comment by tonioo** [comment]
Using a regular alias to authenticate requires a more complex query since we need to find the account to access the password but, that's the simplest case. The worst case concerns domain aliases since corresponding mailbox aliases does not exist into the database...

**Comment by kryskool** [comment]
Hi @almereyda 

Alias can be share with more than one real user, how can we find teh real accoutn to use ?

Regards,

**Comment by yannfill** [comment]
I agree, when a domain alias exists, i.e. example.net is an alias for example.com, user should be able to login to Dovecot and Postfix with either user@example.com or user@example.net.

For now, I must maintain a flat file with users@example.net credentials together with modoboa DB in Dovecot authentication process to address this issue.

**Comment by almereyda** [comment]
Indeed, I have never thought of a use case where multiple mailboxes share an alias.
Additionally, I have checked ISPConfig again and the alias login stemmed from my imagination and does not actually work.

Therefore this probably `won't fix` and cannot be a core functionality. Implementations of patches to this circumstance need to be pluggable to core, then.

**Comment by tonioo** [comment]
@almereyda Maybe we could restrict this functionality to domain aliases (https://github.com/modoboa/modoboa/issues/1040)?
