### ISSUE TITLE
Top redirection does not work when a plugin is used

### ISSUE THREAD

**Issue by ronaldotto** [modoboa/modoboa#1019]
The admin can generate a PDF with the user credentials.
The url in that PDF is http(s)://[hostname]/accounts/login/

After login, the user is redirected to a page that does not exist.

using http(s)://[hostname]/ works fine. It redirects the user to http(s)://[hostname]/accounts/login/?next=/ where the user can login and see his mailbox.

**Comment by tonioo** [comment]
This url should work. Do you have more information? How did you install Modoboa?

**Comment by ronaldotto** [comment]
We did a default installation.

After login, i'm redirected to https://[domain]/accounts/login/webmail
That it tries to push me to webmail is correct. That is the setting in the admin.
However, the url does not work.
Error: Sorry  The requested page does not exist.

https://[domain]/webmail/ should be the url i think?

**Comment by tonioo** [comment]
Indeed, there is something broken but this has nothing to do with this
plugin :)

I think the problem is located inside the core module. Can you move your
issue to the main repository please?

**Comment by ronaldotto** [comment]
i think it is already?

**Comment by tonioo** [comment]
Sorry... I thought you opened it inside the pdfcredentials repository :D

**Comment by tonioo** [comment]
@ronaldotto Issue has been fixed but it will be released with modoboa 1.7.0. It also concerns extensions so I must fix them too.
