### ISSUE TITLE
Sorry An internal error occured & no statistics images

### ISSUE THREAD

**Issue by WhereIsPedro** [modoboa/modoboa#1025]
Hello,

I have upgraded two months ago my last modoboa 1.5  to 1.6.0 and today I have decidet to make an update to 1.6.3 but with no success. On main page:
Sorry An internal error occured.
I have found that I should upgrade plugins due to  core.User problem but this didn't solved problem :/

Also I would like to know where can be a problem that I don't have any statisticas (images). I saw that rrd files are with current date in system that means rrd db is up to date but still no images :/

System; Ubuntu 16.04.2 LTS
So, what did I miss or where I should debug ?
Thank you for help

**Comment by tonioo** [comment]
@WhereIsPedro Please set DEBUG to True inside settings.py and reload uwsgi. You should then see a complete trace.
About rrdtool, can you check the rrdtool binary is installed on your system please?

**Comment by WhereIsPedro** [comment]
Dear Tonioo,
Thank you for reply but from couple of days I was busy. Today I have made an upgrade again on development enviroment with success to 1.6.3 with working statistics. I think the problem was with old modules (pip install seciton) that and next: migrate collectstatic & restart

Thank you and you can close this thread
Peter

**Comment by tonioo** [comment]
Great, glad you fixed your issue.
