### ISSUE TITLE
Import domains and accounts

### ISSUE THREAD

**Issue by oconshaw** [modoboa/modoboa#1031]
Password problem on import of user accounts from csv file.
When I import accounts from a csv file there is a problem with authentication to webmail.

I will import a csv file and choose NOT to encrypt the password. The accounts get created OK.  I can login.  However, when I try to connect to webmail the password fails.  I think probably because it is trying to decrypt a password that is not encrypted.

When I got into the admin interface and reset the password (to the same password) and update it fixes the problem.

I suspect this probably breaks the offline-imap extension as well.

# Impacted versions

* Modoboa: 1.6.3
* installer used: Yes
* Webserver: Nginx

**Comment by tonioo** [comment]
@oconshaw How did you create the CSV file?

About the password, is it already encrypted? What is its format in the file?

**Comment by tonioo** [comment]
You need to specify the scheme used to crypt password. In your case, use the following prefix: `{PLAIN}password123`.

**Comment by tonioo** [comment]
@oconshaw Have you tried again?

**Comment by tonioo** [comment]
Closed for inactivity.

**Comment by shwetd19** [comment]
@tonioo can you pls help me with this, I've tried 
for accounts;
account,[test@abc.com](mailto:test@abc.com),password123,,,TRUE,SimpleUsers,[test@abc.com](mailto:test@abc.com),0,abc.com

for domains:
domain,abc.com,0,TRUE

but it's still not working
