### ISSUE TITLE
Import domains and accounts: all disabled

### ISSUE THREAD

**Issue by oconshaw** [modoboa/modoboa#1032]
When I import via csv file domains and accounts -- I have enabled set to true, but on import they are all set to disabled.

# Impacted versions

* Modoboa: 1.6.3
* installer used: Yes
* Webserver: Nginx

**Comment by tonioo** [comment]
Can you provide a sample of your CSV file please?

**Comment by tonioo** [comment]
@oconshaw The only values to tell something is enabled are True, 1, yes, y (case sensitive).

**Comment by oconshaw** [comment]
Here is an example:
account,test@abc.com,password123,,,TRUE,SimpleUsers,test@abc.com,0,abc.com

**Comment by tonioo** [comment]
Ok so replace TRUE by True and it will work.

**Comment by oconshaw** [comment]
OK, I will give it a try.  Thanks!

**Comment by tonioo** [comment]
@oconshaw ping

**Comment by tonioo** [comment]
Fixed by #1087.
