### ISSUE TITLE
webmail: move emails to folder?

### ISSUE THREAD

**Issue by oconshaw** [modoboa/modoboa#1033]
How does one move a message to a mail folder in webmail?  
Also, I can see how to create and delete a new mailbox folder.  But, when I go to the server in /srv/vmail/user account/Maildir I can see that the folder is still there.

Does it eventually get deleted somehow?

Thanks.

# Impacted versions

* Modoboa: 1.6.3
* installer used: Yes
* Webserver: Nginx
# Steps to reproduce

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@oconshaw Could you please move this issue to the appropriate repository? (https://github.com/modoboa/modoboa-webmail)
