### ISSUE TITLE
Changing Encryption Method

### ISSUE THREAD

**Issue by oconshaw** [modoboa/modoboa#1045]
How would you change the encryption used for passwords in Modoboa?  Or for that matter, disable it all together?  I realize disabling it would be considered a bad idea -- this wouldn't be in production.  I am just trying to understand how this works and how to change.  I usually start with no security and then add on from there until it breaks when trying to understand all the pieces. -- Thanks.

**Comment by tonioo** [comment]
There is a dedicated global parameter for that. Look at Modoboa > Parameters > General.

**Comment by tonioo** [comment]
@oconshaw Have you found it?
