### ISSUE TITLE
Domain directory not deleted on filesystem

### ISSUE THREAD

**Issue by pavinjosdev** [modoboa/modoboa#1046]
* Modoboa: 1.6.3
* Installer used: Yes (stock install, no mods)
* Webserver: Nginx
* OS: Debian 8.7

# Steps to reproduce

1. Create domain
2. Create identity/email acc
3. Login to email acc
4. Delete domain

# Current behavior

**Domain/identities are deleted from admin panel, but the domain directory incl. identities are not deleted from the filesystem (even after successful/manual cron run).**

Deleting just the identity/email acc works fine: the identity is deleted from the admin panel and from the filesystem. Also worth noting is that if the email acc is open in any email client/webmail, dovecot locks it and thus Modoboa won't delete the user's directory on filesystem.

# Expected behavior

When deleting domain, the domain directory incl. all identities should be deleted from the filesystem.

**Comment by pavinjosdev** [comment]
@tonioo Modoboa logs showing CRITICAL `error: delete failed (reason: (exceptions.OSError>, OSError(2, No such file or directory), ))`

On deleting domain, the domain's accounts are all deleted but not the domain's empty directory itself.

Dir permissions:
`drwx------  3 vmail vmail 4096 Mar  3 20:36 cheapmailhosting.com`

**Comment by tonioo** [comment]
@pavinjosdev The domain directory is not removed, this is "normal". What about the CRITICAL error? What was the deleted object?

**Comment by pavinjosdev** [comment]
![mod1](https://cloud.githubusercontent.com/assets/11430516/23569810/9a772358-0061-11e7-853c-ce0cdaf21963.PNG)

The issue seems to have corrected itself after I deleted the domain and its directory (domain was present before upgrade) and created same one again.

**Comment by pavinjosdev** [comment]
On a fresh install it seems when deleting the domain it does not delete the accounts.

**Comment by pavinjosdev** [comment]
On a fresh install of 1.7.0 using installer, Modoboa is not deleting the accounts from admin panel. Mailbox dir was successfully deleted from filesystem though.

Circled in red is me removing the User from admin panel manually after deleting the whole domain from admin panel. 

![mod2](https://cloud.githubusercontent.com/assets/11430516/23579795/6f0cc8d2-00f5-11e7-963c-f748ba9e90ef.PNG)
![mod3](https://cloud.githubusercontent.com/assets/11430516/23579796/6f2267dc-00f5-11e7-99e9-90c6f2ab2174.PNG)
