### ISSUE TITLE
dovecot: dict(12777): Error: sql dict: commit failed: Field 'messages' doesn't have a default value

### ISSUE THREAD

**Issue by cerw** [modoboa/modoboa#1048]
# Impacted versions

* Modoboa: 1.6.3
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

Getting this lots in logs? 

```
dovecot: dict(12777): Error: sql dict: commit failed: Field 'messages' doesn't have a default value
```
 Random in mail.log

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
What is your database?

**Comment by tonioo** [comment]
@cerw ping

**Comment by tonioo** [comment]
Closed for inactivity.

**Comment by cerw** [comment]
Sorry for some reason github did not send me email :( 

mysql 5.7.18

**Comment by cerw** [comment]
@tonioo

**Comment by tonioo** [comment]
@cerw That's strange because the corresponding django model defines a default value for this field...
Can you try to run the following SQL statement please:
```sql
ALTER TABLE admin_quota ALTER COLUMN messages SET DEFAULT 0;
```

**Comment by cerw** [comment]
The date got there via postfixadmin migration script? could this cause it? 

I ran the SQL alter command and it seem to lower the rate but still getting some: 

```
May 16 19:50:52 modoboa dovecot: dict(22930): Error: sql dict: commit failed: Field 'bytes' doesn't have a default value
M
```

**Comment by cerw** [comment]
After I set default to `bytes`  its seem to be fixed. Thanks
