### ISSUE TITLE
spam headers / filtering not working out of box

### ISSUE THREAD

**Issue by mlzummo** [modoboa/modoboa#1049]
* Modoboa: master
* installer used: Yes/No ? Yes
* Webserver: Nginx/Apache Nginx

# Steps to reproduce
     Install on clean debian 8.7 system
     install postwhite to get email(s) past postscreen - (postscreen config needs fixing)
     send message from gmail to system 

# Current behavior
     (no X-SPAM headers)

# Expected behavior
     X-SPAM headers for email filtering

**Comment by tonioo** [comment]
I'm not sure to understand your issue, could you please explain it a bit more?

**Comment by mlzummo** [comment]
@tonioo basically the spam filtering doesn't seem to be working ... I would expect X-SPAM-STATUS filters to be placed in the headers and then those are used to mark spam and filter into the spam folder (instead of just instant reject) (and perhaps sent to quarentene which i didnt see happening either) ... also postscreen seems to be set a bit to high and almost no email can come in without a whitelist. (gmail example) ... I can be reached on gchat mzummo@gmail.com to discuss the issue further. I really like your application and this is the only thing stopping me from using it.

Matt Z

**Comment by tonioo** [comment]
The X-SPAM header is not added to every message processed by the filter.
Only messages with a score greater than a first limit will be tagged and
messages with a score even greater will be rejected or quarantined
according to amavis configuration.

About postscreen, gmail and outlook indeed cause troubles these days and
get rejected by postscreen. postwhite looks like a good fix but I'd like
more feedback about its use.

**Comment by mlzummo** [comment]
http://blog.dmitryleskov.com/small-hacks/forcing-spamassassin-to-add-the-x-spam-status-header-to-ham-for-debugging/

$final_spam_destiny = D_PASS;

http://www.dataparadis.net/osp/gnu-linux-server/mail-server/securing-mail-server-with-spamassassin-amavis-postgrey-and-clam-av/

**Comment by mlzummo** [comment]
@tonioo postscreen blocks gmail as well. (i think what im going to do here is do a pull request with some suggested out of box changes and some configs from mailcow

**Comment by tonioo** [comment]
@mlzummo Would be nice but you're not on right repository, please check https://github.com/modoboa/modoboa-installer.
