### ISSUE TITLE
DNSBL Notifications ignore allowed domains for Domain Admins

### ISSUE THREAD

**Issue by janvalo** [modoboa/modoboa#1051]
* Modoboa: 1.6.2
* installer used: Yes
* Webserver: Nginx

Earlier today our Domain Admins reported emails regarding DNSBL:

```
Subject: [modoboa] DNSBL issue(s) for domain domain.name

Modoboa detected that domain domain.name is listed by the following DNSBL providers:
 
: 

The domain's reputation will be affected and there is a chance that emails coming from it are considered as spam. You should contact those providers and ask them to unlist detected IP address(es).
```
After checking the dnsbl-3.uceprotect.net, our IP is not listed (false alarm due to flagged IP range).
I understand that this would be normal behaviour (the notification bit), however every Domain Admin user received these messages for all the domains currently present at our mail server, even the ones that they are not allowed to manage.

Is there any way to restrict these notifications to be sent only to Super Admins?

**Comment by gawel** [comment]
No, but you can send mails to a specified address. I'm using this crontab instead of the default one:

```
@weekly $HOME/vtenv/bin/python $HOME/bearboa/manage.py modo check_mx --skip-admin-emails --email=admin@bearstech.com
```

**Comment by tonioo** [comment]
@janvalo That's strange because, checking the code, notification for 1 domain should be only sent to its administrators... Can you describe your context a bit more please?

**Comment by tonioo** [comment]
@janvalo ping

**Comment by janvalo** [comment]
@tonioo I had a closer look at the emails and noticed that only domains that did not have any domain administrator assigned were being sent to all of our Domain Admin users. The issue was resolved by assigning a general Domain Admin to those accounts. Is there a possibility to assign Domain Administrator privileges to Super Admins, so they would receive notifications for domains that do not have Domain Admins instead of every Domain Admin user by default? 

I tried suggestion by @gawel but it sends only email to Super Admin.
Thanks

**Comment by tonioo** [comment]
@janvalo Have you tried with a newer version of Modoboa?

**Comment by janvalo** [comment]
@tonioo Not yet. I will give it a try tonight.

**Comment by tonioo** [comment]
@janvalo ping

**Comment by janvalo** [comment]
@tonioo apologies for the delay, I managed to upgrade to version 1.7.0 All seems to be working without any problems. Thanks for your help. 

I was wondering if there is a way for the superadmins to send custom messages/notification to users or specified user groups?

**Comment by tonioo** [comment]
@janvalo Great but please use 1.7.2, 1.7.0 contains bugs.

There is no such feature at the moment. Someone already asked for something similar (see #961), does it correspond to your need?

**Comment by janvalo** [comment]
@tonioo Thanks, will update to 1.7.2

Yes, that feature would be in the scope of functionality that I am looking for, maybe with ability to create email templates and simple scheduler for sending these emails would be great. Any plans to add such functionality in the foreseeable future?

**Comment by tonioo** [comment]
@janvalo Nothing defined yet but it could be interesting. Do you plan to use Modoboa for marketing campaigns? :smile:

**Comment by janvalo** [comment]
@tonioo Nope, just for small volume email /internal notifications to our users.

**Comment by tonioo** [comment]
@janvalo Ok. I close this issue since the original problem looks solved.
