### ISSUE TITLE
MailBox Glitch

### ISSUE THREAD

**Issue by mlzummo** [modoboa/modoboa#1052]
![image](https://cloud.githubusercontent.com/assets/1057527/23416668/bba7841c-fdb1-11e6-8515-a0f3141241cd.png)

**Comment by mlzummo** [comment]
not sure why this is happening seems to be getting worse?

**Comment by tonioo** [comment]
@mlzummo sorry but I can't see your image.

**Comment by mlzummo** [comment]
link: https://cloud.githubusercontent.com/assets/1057527/23416668/bba7841c-fdb1-11e6-8515-a0f3141241cd.png

**Comment by tonioo** [comment]
Ok. Can you describe the actions you made to get this result please?
