### ISSUE TITLE
how to check total size of email messages (so as to not run out of space) and quota usage per domain/mailboxa

### ISSUE THREAD

**Issue by mzummo** [modoboa/modoboa#1053]
how to check total size of email messages (so as to not run out of space) and quota usage per domain/mailboxa

**Comment by tonioo** [comment]
@mlzummo Currently, the only way to have a global overview of quota usage per mailbox is through the Identities > List quotas page.

**Comment by tonioo** [comment]
The kind of listing has been added to the Domains section.
