### ISSUE TITLE
Auto Reply Error & bounce email

### ISSUE THREAD

**Issue by mlzummo** [modoboa/modoboa#1074]
Sent: March 13, 2017 4:06 PM
Subject: Undelivered Mail Returned to Sender
This is the mail system at host mx-1.example.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

The mail system

<"it@example.com"@autoreply.example.com> (expanded from
<it@example.com>): Command died with status 2:
"/srv/modoboa/env/bin/python". Command output: usage: manage.py autoreply
[-h] [--version] [-v {0,1,2,3}] [--settings
SETTINGS] [--pythonpath PYTHONPATH]
[--traceback] [--no-color] [--debug] manage.py autoreply: error:
unrecognized arguments: person@example.com it@example.com

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-postfix-autoreply#39
