### ISSUE TITLE
Update to v.1.7.x failed

### ISSUE THREAD

**Issue by mkkeck** [modoboa/modoboa#1075]
## Impacted versions

+ OS: Centos 7.3
+ Modoboa: 1.6.1 / 1.7.x
+ Installer used: 
  - Modoboa v1.6.1 installed via installer (some weeks ago)
  - Attempt to update to v.1.7.x descriped [here](http://modoboa.readthedocs.io/en/latest/upgrade.html#id2)
+ Webserver: Apache (PHP-FPM, mod_uwsgi)

## Steps to reproduce
```shell
> cd /path/to/modoboa/
> sudo -u <modoboa-user> -i

(env)-sh-4.2$ source env/bin/activate
(env)-sh-4.2$ pip install --upgrade django
# ...
# Installing collected packages: django
# Successfully installed django-1.10.6

(env)-sh-4.2$ pip install --upgrade django-versionfield2
# ...
# Requirement already up-to-date: 
# django-versionfield2 in /path/to/modoboa/env/lib/python2.7/site-packages
# Requirement already up-to-date: 
# six>=1.9.0 in /path/to/modoboa/env/lib/python2.7/site-packages (from django-versionfield2)

(env)-sh-4.2$ cd instance/
(env)-sh-4.2$ python manage.py migrate
```

## Current behavior
```shell
Traceback (most recent call last):
  File "manage.py",
    line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/path/to/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py",
    line 367, 
    in execute_from_command_line utility.execute()
  File "/path/to/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py",
    line 341,
    in execute django.setup()
  File "/path/to/modoboa/env/lib/python2.7/site-packages/django/__init__.py",
    line 27,
    in setup apps.populate(settings.INSTALLED_APPS)
  File "/path/to/admin/modoboa/env/lib/python2.7/site-packages/django/apps/registry.py",
    line 85,
    in populate app_config = AppConfig.create(entry)
  File "/path/to/modoboa/env/lib/python2.7/site-packages/django/apps/config.py",
    line 123,
    in create import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py",
    line 37,
    in import_module __import__(name)

ImportError: No module named parameters
```

**Comment by tonioo** [comment]
Actually, you forgot to upgrade modoboa itself... Have you tried to run this:
```shell
$ pip install modoboa==1.7.1
```
Instead of trying to upgrade each dependency manually?

**Comment by mkkeck** [comment]
I've not tried:
`$ pip install modoboa==1.7.1`

Does this not replace all my postfix and/or other mail server related configs?

**Comment by tonioo** [comment]
No, it only upgrades python packages.

**Comment by mkkeck** [comment]
Ok ... then I will try
... and post results or close this issue
Perhabs ... the documentation may be not clear enough?

**Comment by mkkeck** [comment]
**Step 1** 
```shell
> cd /path/to/modoboa/
> sudo -u <modoboa-user> -i

sh-4.2$ source env/bin/activate
sh-4.2$ pip install modoboa==1.7.1
```

**Step 2** 
Follow the [upgrade guide for 1.7.x](http://modoboa.readthedocs.io/en/1.7.1/upgrade.html#id2)

**Step 3** 
Follow the [upgrade extensions guide](http://modoboa.readthedocs.io/en/1.7.1/upgrade.html#extensions)

**Step 4** 
+ `> python manage.py generate_postfix_maps --destdir <path> --force-overwrite`
+ restart postfix service

**Many thanks** to Modoboa and Tonioo for his help
