### ISSUE TITLE
Bad request (HTTP 400)

### ISSUE THREAD

**Issue by PeterBocan** [modoboa/modoboa#1080]
# Impacted versions 
Latest (using Installer)

* Modoboa: latest
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Installed Modoboa using installer. I ran ```./run.py mail.pbocan.net``` which was bad (it has prepended the mail part again) so I had to fix some duplicates in NGINX configuration (already had SSL set up) after that, I had to fix the names of the subdomain and so on. 

I know a thing that may be breaking the code: /tmp is not mounted (at all) with /noexec flag. (I am running on VPS) 

# Current behavior
Reaching the frontend of the mail administration responds with HTTP 400 (Bad request) 

# Expected behavior
Display the login screen

# Video/Screenshot link (optional)
<img width="318" alt="screenshot 2017-03-17 14 10 34" src="https://cloud.githubusercontent.com/assets/2006860/24044429/8bc71808-0b1b-11e7-8811-79d400b75ebc.png">

**Comment by PeterBocan** [comment]
Can I/Should I rerun the installer?

**Comment by tonioo** [comment]
@PeterBocan When did you run the installer?

**Comment by PeterBocan** [comment]
today.

**Comment by tonioo** [comment]
Ok, so now the right way to run the installer is:
```shell
sudo ./run.py pbocan.net
```
Please try to run the installer once again.

**Comment by tonioo** [comment]
yes, add default values are 'password'.

**Comment by PeterBocan** [comment]
Okay, now I get Internal Server Error. Do I need to create mysql user manually? And/or what should I check?

**Comment by tonioo** [comment]
No, it should be created by the installer. Can you set DEBUG to True inside /srv/modoboa/instance/instance/settings.py, reload uwsgi and retry please?

**Comment by PeterBocan** [comment]
now I can't even load webpage. ERR_CONNECTION_RESET or ERR_CONNECTION_CLOSED. Dammit.

**Comment by tonioo** [comment]
@PeterBocan Is your problem fixed now?

**Comment by PeterBocan** [comment]
No, I haven't solved it yet. I may install the certificate as a root at first time and then I hope it will renew the certificate by itself.

**Comment by Xervia** [comment]
I have the same problem, I did no changes to the installer settings and I just ran `./run.py mysite.com`, I get a ERR_CONNECTION_CLOSED

**Comment by PeterBocan** [comment]
You most likely don't have SSL certs.

**Comment by Xervia** [comment]
@PeterBocan No the certs are there and ok

**Comment by Xervia** [comment]
Fixed by me, I had wrong permissions on the uwsgi socket and forgot to add the reverse entry in the /etc/hosts `121.21.xx.xx   mail.pbocan.net`

**Comment by stalks** [comment]
FYI this also occurs if you mispell the hostname during "deploy" command

**Comment by PeterBocan** [comment]
Havent had time to look at that yet.

**Comment by mylastore** [comment]
I had the same problem Bad request (HTTP 400) wen't to sleep and the next day everything was install correctly seems the it takes time for the domain propagation to take place. I could not fine any documentation on how to set your domain DNS settings or there is no need to have any custom DNS records.

**Comment by PeterBocan** [comment]
@mylastore I went for AWS WebMail and they said on their site, that it will take 3 days to propagate  change DNS globally, which turned up to be true actually.
