### ISSUE TITLE
Some things wrong after update to 1.7.2

### ISSUE THREAD

**Issue by mkkeck** [modoboa/modoboa#1081]
# Impacted versions

* Modoboa: 1.7.2
* installer used: Yes
* Webserver: Apache (PHP-FPM, mod_wsgi, mod_security)
* OS: Centos 7.3

# Steps to reproduce
Update from version 1.7.1 to 1.7.2 (see [docs](http://modoboa.readthedocs.io/en/1.7.2/upgrade.html))

# Current behavior
* After login dashboard throws error
* Loading any page is some times very slow (timeout)
* Uploading images via CKEditor does not work (can't select uploaded image)
  - how should this configured?
* Spellchecker is not available
  - how should this configured?
* I've attached my debugging log: [modoboa-debug.md.txt](https://github.com/modoboa/modoboa/files/852345/modoboa-debug.md.txt)

**Comment by tonioo** [comment]
@mkkeck About the trace you sent, can you check which version of ``requests`` is installed on your virtualenv please?

**Comment by mkkeck** [comment]
I've typed in my shell:
```bash
[user@host ~] sudo -u modoboa -i
-bash-4.2$ source env/bin/activate
(env)-bash-4.2$ python
```
> Python 2.7.5 (default, Nov  6 2016, 00:28:07)
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
```python
import requests
requests.__version__
```
> **'2.12.4'**
>>>

**Comment by mkkeck** [comment]
Now it works:

```shell
(env)-bash-4.2$ pip install --upgrade requests
```
> ```
> Collecting requests
>   Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
> Installing collected packages: requests
>   Found existing installation: requests 2.12.4
>     Uninstalling requests-2.12.4:
>       Successfully uninstalled requests-2.12.4
> Successfully installed requests-2.13.0
> ```

```shell
systemctl restart httpd.service
```

Login ...
... and the Dashboard is available
Upload to the server works via CKEditor too. But how can I configure the spellchecker?

**Comment by tonioo** [comment]
Two possibilities:
* Enable CKeditor [SCAYT](http://ckeditor.com/addon/scayt) plugin: add `'Scayt'` to `CKEDITOR_CONFIGS` inside settings.py (just after `SpellChecking`)
* Enable browser native support: add `'disableNativeSpellChecker': False` to `CKEDITOR_CONFIGS` inside settings.py

**Comment by mkkeck** [comment]
**@tonioo:**

Many thanks :+1:  it works! (I prefer the `native spell checker` instead of `Scayt`)
So I close this Issue ...
