### ISSUE TITLE
API DELETE method fails on domains and accounts

### ISSUE THREAD

**Issue by figassis** [modoboa/modoboa#1082]
# Impacted versions

* Modoboa: 1.7.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
1. Generate API Token form modoboa user settings
2. Configure Postman with "Authorization: Token <token>" header
3. Send DELETE request to {domain}/api/v1/accounts/{id} or {domain}/api/v1/domains/{id}

# Current behavior
A 200 response code is returned along with full json of object to DELETE
A GET request still returns the same object with a 200 response

# Expected behavior
A 200 response code is returned along with full json of object to DELETE
A GET request should return a 404 response code, with a { "detail": "Not found." } response.

**Comment by tonioo** [comment]
A DELETE request should return a 204 code on success, not 200... Have you checked the response payload?

**Comment by figassis** [comment]
Yes, it's a the full json object of the resource I attempted to DELETE

Assis Ngolo
CEO, Nellcorp

**Comment by tonioo** [comment]
Have you tried with something else than postman?

**Comment by figassis** [comment]
Sorry for the late reply. No, I haven't tried with anything else.

**Comment by tonioo** [comment]
@figassis Could you please try with something else (curl or similar)?

**Comment by figassis** [comment]
Hi, I tried with curl (using php) and was able to delete accounts. So it might be a postman issue.

**Comment by tonioo** [comment]
Ok, so I close the issue.
