### ISSUE TITLE
Is it possible to set this up with a DDNS from No-IP? If so How?

### ISSUE THREAD

**Issue by Vlku272** [modoboa/modoboa#1083]
* Modoboa: Dunno, Latest. Installed 26/03/17
* installer used: Yes
* Webserver: Apache

# Steps to reproduce
Install Modoboa with a server using Dynamic DNS

# Current behavior
Can't access site as mail.domain was attached to an address that just redirects to constantly changing IP.

# Expected behavior
Sorta hoped it would add itself like domain/mail and have it redirect to another port to the apache website.

**Comment by tonioo** [comment]
You could look at no-ip documentation: http://www.noip.com/support/knowledgebase/can-i-run-an-email-server-using-a-free-no-ip-hostname/ ?
