### ISSUE TITLE
Upgrading from 1.6.0 to 1.7.2

### ISSUE THREAD

**Issue by abmiller99** [modoboa/modoboa#1091]
I have a stable Modoboa install v 1.6.0 (on Debian 8/Jessie)

Question about upgrading: Is it proper to upgrade directly to 1.7.2 (from 1.6.0) or to incrementally upgrade? i.e. first upgrade to 1.6.1, then 1.7.0, etc... Could not find answer to this by searching.

I have attempted to upgrade both ways, unfortunately I keep having to restore to 1.6.0 because my upgraded Modoboa runs but with critical bugs (internal error)

Thanks

**Comment by gawel** [comment]
Hi,

It's probable safer to follow versions with specific migration steps listed here http://modoboa.readthedocs.io/en/latest/upgrade.html

**Comment by almereyda** [comment]
I am usually jumping from the last installed version to the current version and make sure migrations are applied. An incremental log of such a procedure for a deployment environment can be found in https://github.com/modoboa/modoboa-installer/issues/39

`settings.py` is then also up to date, as it is being removed and recreated by the installer.

**Comment by tonioo** [comment]
@abmiller99 Any news about this?

**Comment by abmiller99** [comment]
Well - I upgraded Modoboa core and extensions incrementally w/ virtualenv, using the specific upgrade instructions for each (if applicable), and always ran 
```
python manage.py migrate
python manage.py collectstatic
```
after each..

My install is up-to-date. 

While the core functions do seem intact, I do however experience some buggy behaviour:
- critical errors when replying with webmail (HTML editor only)
- saving option settings on some pages produces a blank page with 'parameters saved' writen in plain text at the top
- when viewing an email received in webmail inbox inline images are broken

I would love to know if there is any method to create a fresh Modoboa install and then apply a backup from a previous (broken) install.

Lots of off-topic stuff there.. sorry! As you can probably tell I'm not a Python or Linux genius.

**Comment by tonioo** [comment]
@abmiller99 Actually, the webmail is a bit buggy and I'm working on it. A new version should be released soon. Anyway, I suggest you clear the cache of your browser and retry the other points.

**Comment by tonioo** [comment]
@abmiller99 I guess you solved your issue so I close this issue. Open a new one if needed.
