### ISSUE TITLE
Docs : Ways of contribution

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa#1094]
The [How to contribute](https://modoboa.readthedocs.io/en/latest/contributing.html) page in the documentation is very rough and currently focusses on developers. Hence there are other forms of contributors, as bug reporters, translators, users or providers, they could be directed more appropriately to

* https://www.transifex.com/tonio/modoboa/ (found via https://github.com/modoboa/modoboa-installer/issues/73#issuecomment-262453542)
* https://github.com/modoboa/modoboa-installer/issues
* https://modoboa.org/sponsor/
* ...

**Comment by tonioo** [comment]
@almereyda As suggested by @gawel, I fixed the CONTRIBUTING.rst template.
About your request, all the information you're talking about is already available on the official website: https://modoboa.org/en/.
Are you suggesting this site is not clear enough or is not the right way to communicate?

**Comment by almereyda** [comment]
Yes, the contribute page has a link to the translation.

I *believe* I was thinking about ways for the public to contribute that does not involve development or coding, but the Transifex link is now there.

Everything else, like an end user documentation, is maybe another project, thus closing.
