### ISSUE TITLE
Prevent special chars in user’s name

### ISSUE THREAD

**Issue by schneidermayer** [modoboa/modoboa#1096]
When giving a user an full name that contains  a char like `!` the email will get blocked by gmail and other hosts because of duplicate adress entries that aren’t matching.

**Suggestion:** Only allow [a-zA-Z0-9 ] for the first name and last name fields. Maybe some names contain utf chars like `è`. In that case you could just block the special chars.

**Comment by tonioo** [comment]
@schneidermayer Can you describe gmail behaviour a bit more please?

**Comment by schneidermayer** [comment]
Return sender should match the sender's adress. It's a generel violation, but gmail rejects all emails doing it. Other hosts may work fine, but it's always bad practice to have different names. The exclamation mark is causing this. That's all I know.

**Comment by tonioo** [comment]
Do you use the internal webmail?

**Comment by schneidermayer** [comment]
Yes, I created a User with first name `Hello,` and last name `Word!` and tried sending an email to a gmail account.

**Comment by tonioo** [comment]
I just tried to reproduce your issue and I fail... Can you provide more technical detail? (NDR message from Google, source of the original message, etc.)

**Comment by schneidermayer** [comment]
Dovecot/Postfix Log:
https://pastebin.com/vBSP1mFa

Mail creation:
http://pasteboard.co/8AGVT6PoC.png

Mail Header:
https://pastebin.com/WyDmaDSi

Mail Daemon:
https://pastebin.com/H08D7rt4

**Comment by tonioo** [comment]
@schneidermayer Actually, the problem comes from the coma. It is used as a separator when you send a message to multiple recipients and modoboa does not escape it (it is a mistake).

**Comment by tonioo** [comment]
@schneidermayer I was talking about the sender, sorry.
