### ISSUE TITLE
security issue: domain administrators permissions

### ISSUE THREAD

**Issue by msenebald** [modoboa/modoboa#1100]
# Impacted versions

* Modoboa:  1.7.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Account with domainadmin rights
accountname: domainadmin@example.com
permissions for domain: subdomain.example.com
resource: mailbox aliases >0

# Current behavior
Domainadmin@example.com
- can edit his own identiy like an admin
- can add aliases for any domain (even when not listed, but available on the server)
- can add sender addresses for any domain

# Expected behavior
Should not be able to edit is own identity at all. 
Should only be able to edit all identies under the domain where permission is granted

# open
not checked if it is possible to add identities outside his domains

**Comment by tonioo** [comment]
@msenebald I've fixed alias and sender address issues, thank you for reporting.

Where is the problem in allowing the domain admin to edit its own information?

**Comment by tonioo** [comment]
@msenebald I close this issue. Feel free to open a new one about the self-edition issue.

**Comment by msenebald** [comment]
Nice! Thanks for the fix. I'll check the self edit options in more detail with this patch to verify if worth another ticket. From code it seems already fine.
