### ISSUE TITLE
Migration to Modoboa

### ISSUE THREAD

**Issue by jaketame** [modoboa/modoboa#1112]
I'm currently using Mailcow (non docker) however its not being supported anymore. I would like to know what options there are available for a migration  to Modoboa?

Thanks

**Comment by tonioo** [comment]
@jaketame There is no migration tool for now so the only available way is to use the CSV import feature. (available from the command line)
Otherwise, a migration tool like https://github.com/modoboa/modoboa-pfxadmin-migrate could be useful. Do you have any python skills?

**Comment by jaketame** [comment]
Not well even for postfix migrations :) 
is the csv import documented anywhere? I can't see it on the documentation.

Cheers,

**Comment by tonioo** [comment]
@jaketame No, only in the interface. But you have a command line tool available:
$ python manage.py modo import <your file>
You can find some documentation [here](https://github.com/modoboa/modoboa/blob/master/modoboa/admin/templates/admin/import_domains_form.html) and [there](https://github.com/modoboa/modoboa/blob/master/modoboa/admin/templates/admin/import_identities_form.html)

**Comment by tonioo** [comment]
@jaketame I've added some documention about CSV import: http://modoboa.readthedocs.io/en/latest/moving.html.
Can I close the issue?

**Comment by jaketame** [comment]
Nice one thanks!
