### ISSUE TITLE
stats page is empty

### ISSUE THREAD

**Issue by euri10** [modoboa/modoboa#1113]
# Impacted versions

* Modoboa: 1.7.4
* installer used: Yes/No ? YES
* Webserver: Nginx/Apache nginx

# Steps to reproduce
my first install, please bear with me, it's inside a lxc container but I don't think it's relevant,

I have some 404 on some sitestatic paths that maybe explain I don't see anything on the stats page, rest of the site seems to work fine.
The links are:
https://mail.mydomain.fr/sitestatic/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0
https://mail.mydomain.fr/sitestatic/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2

both links above are reachable with the .woff extension instead of .woff2

I tried to
```
(env) modoboa@modoboa:~$ python instance/manage.py collectstatic

You have requested to collect static files at the destination
location as specified in your settings:

    /srv/modoboa/instance/sitestatic

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes

0 static files copied to '/srv/modoboa/instance/sitestatic', 2195 unmodified.
(env) modoboa@modoboa:~$
```

to no avail,

**Comment by euri10** [comment]
mmm I found why, not linked at all to that 404
in fact the cron jobs are all failing in my install as the env variables $PYTHON and $INSTANCE stayed like that in /etc/cron.d/modoboa
I dunno if it's a bug in the installer then
changing $PYTHON to /srv/modoboa/env/bin/python and $INSTANCE to /srv/modoboa/instance solved the issue

**Comment by tonioo** [comment]
@euri10 Indeed, that's strange. I'll look into it asap.

**Comment by tonioo** [comment]
@euri10 Actually, what you see in you log file is normal. Variables are not replaced but it should work. Looks like you cron daemon was not running...

**Comment by euri10** [comment]
@tonioo sincere apologies for the false report, actually cron was ok, dunno what happened, it works with the default cron.d/modoboa once I re-enabled the iptable rules to my container.
