### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by physiii** [modoboa/modoboa#1125]
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily

Using Apache

# Steps to reproduce
git clone https://github.com/modoboa/modoboa-installer && cd modoboa* && sudo ./run.py domain.org:8080
...
Congratulations! You can enjoy Modoboa at https://mail.domain.org:8080 (admin:password)

# Current behavior
nothing at https://mail.domain.org:8080

# Expected behavior
Thinking admin site should load

Tried doing the manual install.  Ended up with a mess on my system and had to rebuild OS.

**Comment by tonioo** [comment]
Why do you include a port number? Just use a simple domain name, the syntax you're trying to use is not supported by the installer.

**Comment by physiii** [comment]
I tried without the port and get the same result. I am running apache2 on 8080 and a different webserver on 80 so that's why I tried the the 8080 port.

Please let me know what I should do from here.

**Comment by tonioo** [comment]
Please run the installer once again using the --debug option, you should
have more information.

**Comment by physiii** [comment]
Okay looks like a problem with dovecot, "Address family not supported by protocol"

> ● dovecot.service - Dovecot IMAP/POP3 email server
>    Loaded: loaded (/lib/systemd/system/dovecot.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Tue 2017-05-16 09:06:52 MST; 2min 53s ago
>  Main PID: 5241 (code=exited, status=89)
> 
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: master: Error: service(managesieve-login): listen(::, 4190) failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: master: Error: socket() failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: master: Error: service(imap-login): listen(::, 143) failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: master: Error: socket() failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: Error: service(managesieve-login): listen(::, 4190) failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: Error: socket() failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: Error: service(imap-login): listen(::, 143) failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: Error: socket() failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: Error: service(imap-login): listen(::, 993) failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: Fatal: Failed to start listeners
> Synchronizing state of dovecot.service with SysV init with /lib/systemd/systemd-sysv-install...

**Comment by physiii** [comment]
Removed references to IPv6 in nginx and dovecot and now all services appear to be running. Still no access from https://mail.mydomain.org

Here is my nginx config:

```
$ cat /etc/nginx/sites-enabled/mail.mydomain.org.conf
# This file was automatically installed on 2017-05-17T07:01:19.308859
upstream modoboa {
    server unix:/run/uwsgi/app/modoboa_instance/socket fail_timeout=0;
}

server {
    listen 8080;
    server_name mail.mydomain.org;
    rewrite ^ https://$server_name$request_uri? permanent;
}

server {
    listen 443 ssl;
    server_name mail.mydomain.org;
    root /srv/modoboa/instance;

    ssl_certificate /etc/ssl/certs/mail.mydomain.org.cert;
    ssl_certificate_key /etc/ssl/private/mail.mydomain.org.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_verify_depth 3;
    ssl_dhparam /etc/nginx/dhparam.pem;

    client_max_body_size 10M;

    access_log /var/log/nginx/mail.mydomain.org-access.log;
    error_log /var/log/nginx/mail.mydomain.org-error.log;

    location /sitestatic/ {
        try_files $uri $uri/ =404;
    }

    location /media/ {
        try_files $uri $uri/ =404;
    }

    location / {
        include uwsgi_params;
        uwsgi_param UWSGI_SCRIPT instance.wsgi:application;
        uwsgi_pass modoboa;
    }
}

```

**Comment by tonioo** [comment]
@physiii What do you get when you try to access the web interface?

**Comment by physiii** [comment]
I don't even get an error returned, just sits there connecting. I can access my test page from 8080 but if I got to https://mail.mydomain.org, it just sits there trying to connect, not even an error is returned. I have no problems running other ssl applications on my webserver.

**Comment by tonioo** [comment]
Firewall issue? Is your DNS correctly configured?

**Comment by physiii** [comment]
I can run my applications on any port without issue.

**Comment by almereyda** [comment]
Should this issue maybe moved to the modoboa-installer issue tracker?

**Comment by tonioo** [comment]
@almereyda yes

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-installer#128
