### ISSUE TITLE
Disabling modoboa.relaydomains causes an error in the domains tab

### ISSUE THREAD

**Issue by tuxis-ie** [modoboa/modoboa#1127]
If you disable ```modoboa.relaydomains```, the 'Domains'-tab shows an 'Internal error'. I don't want people to be able to create relaydomains, that's why I want this app to be disabled.

**Comment by tonioo** [comment]
Actually, this is a required application. It is not intended to be disabled...

**Comment by tuxis-ie** [comment]
It shouldn't be :)

**Comment by tonioo** [comment]
I think a flag to globally disable the feature would be better... Are you giving superadmin rights to your customers?

**Comment by kryskool** [comment]
ping @tuxis-ie
