### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by atikulhaider** [modoboa/modoboa#1128]
I followed your documentation here as recommended:
[http://modoboa.readthedocs.io/en/latest/installation.html#recommended-way](http://modoboa.readthedocs.io/en/latest/installation.html#recommended-way)
I tried to install Modoboa from scratch on a fresh CentOS 6.9 (Final) server.
And got this error:

`Traceback (most recent call last):
  File "./run.py", line 11, in <module>
    from modoboa_installer import scripts
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 3, in <module>
    import importlib
ImportError: No module named importlib`

Any solution please?

**Comment by tonioo** [comment]
The installer is not supposed to work with your CentOS version. I suggest you try with version 7.

**Comment by tonioo** [comment]
@atikulhaider I close this issue. Feel free to open a new one but in the appropriate repository this time: https://github.com/modoboa/modoboa-installer.
