### ISSUE TITLE
Quarantine list empty after deletion of multiple messages

### ISSUE THREAD

**Issue by TacoScheltema** [modoboa/modoboa#1129]
# Impacted versions

* Modoboa: 1.7.4
* Amavis Frontend: 1.1.2
* installer used: Yes
* Webserver: Nginx
* Browser used: Chrome on OSX 58.0.3029.110 (Official Build) (64-bit)

# Steps to reproduce
when there are multiple messages in quarantine (in my case there were over 60), then using the selector at the top of the page to select all messages with bad headers (which in my case selects all but 2 messages) and click the Delete button.

# Current behavior
Quarantine page does not list any remaining messages. when navigating to the quarantine page again it does show the 2 remaining messages

# Expected behavior
Quarantine page should show the messages that are left in quarantine after removing the selected message, in this case 2 spam messages.
This is not a major issue and may not happen in every browser (haven't been able to test other browsers yet, I'll do some more testing once I have messages in quarantine again)

**Comment by TacoScheltema** [comment]
I just tested this with the same versions as mentioned above with 2 messages in quarantine. I deleted one message, the second messages stays on the page as expected. Will test some more this weekend.

**Comment by TacoScheltema** [comment]
Tested again today, this time with safari Version 10.1 (12603.1.30.0.34) on OSX. About 100-120 messages in quarantine. selected 25 messages and deleted those. the  remaining messages stay visible as expected. then repeated the same action on chrome on OSX; the quarantine page is empty. a reload of the quarantine page will show the remaining messages again.
I've also done the same test on chrome 58.0.3029.110 (64-bit) on Windows 10, after deleting the page shows up empty too.
On windows 10 using Internet Explorer 11 it works as expected so this seems to be an issue with Chrome only.

**Comment by tonioo** [comment]
Thank you for reporting, I'll look into it asap.

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-amavis#56
