### ISSUE TITLE
Use as relay without Dovecot

### ISSUE THREAD

**Issue by ursweiss** [modoboa/modoboa#1131]
We want to use Modoboa as a gateway only without any local mailboxes, and therefore i didn't install dovecot (Installer cfg: enabled = false). But now i get the following message:

> `to=<me@example.com>, relay=none, ... dsn=4.4.1, status=deferred (connect to modoboa.server.com[private/dovecot-lmtp]: No such file or directory)`

Do we need to have Dovecot installed, even we don't use it? The type of the domain is set to "Relay domain" and "Relay settings >> Service" to relay.

Installed extensions: modoboa-amavis modoboa-stats modoboa-dmarc

Thank you,
Urs

**Comment by tonioo** [comment]
I guess you installed Modoboa with the installer? 

Anyway, you just have to disable the postfix config related to dovecot and it should be enough.

**Comment by ursweiss** [comment]
Yes, i used the installer.

The dovecot part was already disabled by the installer:
```
## SASL authentication through Dovecot
#
#smtpd_sasl_type = dovecot
#smtpd_sasl_path = private/auth
#smtpd_sasl_auth_enable = yes
#broken_sasl_auth_clients = yes
#smtpd_sasl_security_options = noanonymous
```
That's why i'm a bit confused.

My full postfix config: https://pastebin.com/2ee0TR7U

**Comment by tonioo** [comment]
Can you try to comment the `reject_unverified_recipient` line and reload postfix?

**Comment by ursweiss** [comment]
That's one thing i tried yesterday already. The only thing that changes is that the email is accepted, but kept in the local queue instead of the senders queue with the same error.


```
### reject_unverified_recipient set ###

Jun  1 11:46:56 icrvsgw003-wina postfix/smtpd[14628]: connect from unknown[1.2.3.4]
Jun  1 11:46:57 icrvsgw003-wina postfix/smtpd[14628]: Anonymous TLS connection established from unknown[1.2.3.4]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Jun  1 11:46:57 icrvsgw003-wina postfix/smtpd[14628]: NOQUEUE: reject: RCPT from unknown[1.2.3.4]: 450 4.1.1 <recipient@otherdomain.com>: Recipient address rejected: unverified address: connect to modoboa.server.com[private/dovecot-lmtp]: No such file or directory; from=<sender@domain.com> to=<recipient@otherdomain.com> proto=ESMTP helo=<smtp10.domain.com>
Jun  1 11:46:57 icrvsgw003-wina postfix/smtpd[14628]: disconnect from unknown[1.2.3.4]
Jun  1 11:46:57 icrvsgw003-wina postfix/postscreen[49954]: CONNECT from [2001:1:2:3::61]:40396 to [2001:1:2:3::71]:25
Jun  1 11:46:57 icrvsgw003-wina postfix/cleanup[14641]: 1B76710152E: message-id=<20170601094657.1B76710152E@modoboa.server.com>
Jun  1 11:46:57 icrvsgw003-wina postfix/qmgr[49838]: 1B76710152E: from=<double-bounce@modoboa.server.com>, size=245, nrcpt=1 (queue active)
Jun  1 11:46:57 icrvsgw003-wina postfix/lmtp[14643]: 1B76710152E: to=<recipient@otherdomain.com>, relay=none, delay=0.07, delays=0.05/0.02/0/0, dsn=4.4.1, status=undeliverable (connect to modoboa.server.com[private/dovecot-lmtp]: No such file or directory)
Jun  1 11:46:57 icrvsgw003-wina postfix/qmgr[49838]: 1B76710152E: removed
Jun  1 11:46:57 icrvsgw003-wina postfix/postscreen[49954]: PASS OLD [2001:1:2:3::61]:40396
Jun  1 11:46:57 icrvsgw003-wina postfix/smtpd[14628]: connect from unknown[2001:1:2:3::61]
Jun  1 11:46:57 icrvsgw003-wina postfix/smtpd[14628]: Anonymous TLS connection established from unknown[2001:1:2:3::61]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Jun  1 11:46:57 icrvsgw003-wina postfix/smtpd[14628]: NOQUEUE: reject: RCPT from unknown[2001:1:2:3::61]: 450 4.1.1 <recipient@otherdomain.com>: Recipient address rejected: unverified address: connect to modoboa.server.com[private/dovecot-lmtp]: No such file or directory; from=<sender@domain.com> to=<recipient@otherdomain.com> proto=ESMTP helo=<smtp10.domain.com>
Jun  1 11:46:57 icrvsgw003-wina postfix/smtpd[14628]: disconnect from unknown[2001:1:2:3::61]

## Remote (sender) queue ##
9DD5E1505      1069 Thu Jun  1 11:46:56  sender@domain.com
(host modoboa.server.com[2001:1:2:3::71] said: 450 4.1.1 <recipient@otherdomain.com>: Recipient address rejected: unverified address: connect to modoboa.server.com[private/dovecot-lmtp]: No such file or directory (in reply to RCPT TO command))
                                         recipient@otherdomain.com


### reject_unverified_recipient NOT set ###
Jun  1 11:51:59 icrvsgw003-wina postfix/postscreen[14936]: CONNECT from [2001:1:2:3::62]:39924 to [2001:1:2:3::71]:25
Jun  1 11:51:59 icrvsgw003-wina postfix/postscreen[14936]: PASS OLD [2001:1:2:3::62]:39924
Jun  1 11:51:59 icrvsgw003-wina postfix/smtpd[15231]: connect from unknown[2001:1:2:3::62]
Jun  1 11:51:59 icrvsgw003-wina postfix/smtpd[15231]: Anonymous TLS connection established from unknown[2001:1:2:3::62]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Jun  1 11:51:59 icrvsgw003-wina postfix/smtpd[15231]: NOQUEUE: client=unknown[2001:1:2:3::62]
Jun  1 11:52:00 icrvsgw003-wina postfix/smtpd[14996]: 1C23210237E: client=localhost[127.0.0.1], orig_client=unknown[2001:1:2:3::62]
Jun  1 11:52:00 icrvsgw003-wina postfix/cleanup[15244]: 1C23210237E: message-id=<592FE3BD.8060003@domain.com>
Jun  1 11:52:00 icrvsgw003-wina postfix/qmgr[14921]: 1C23210237E: from=<sender@domain.com>, size=1814, nrcpt=1 (queue active)
Jun  1 11:52:00 icrvsgw003-wina postfix/smtpd[14996]: disconnect from localhost[127.0.0.1]
Jun  1 11:52:00 icrvsgw003-wina amavis[35493]: (35493-03) Passed CLEAN {RelayedInbound}, [2001:1:2:3::62]:39924 [2001:1:2:3::62] <sender@domain.com> -> <recipient@otherdomain.com>, Message-ID: <592FE3BD.8060003@domain.com>, mail_id: YBdzyv0P_yPz, Hits: 1.274, size: 1371, queued_as: 1C23210237E, 615 ms
Jun  1 11:52:00 icrvsgw003-wina postfix/smtpd[15231]: proxy-accept: END-OF-MESSAGE: 250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 1C23210237E; from=<sender@domain.com> to=<recipient@otherdomain.com> proto=ESMTP helo=<smtp10.domain.com>
Jun  1 11:52:00 icrvsgw003-wina postfix/smtpd[15231]: disconnect from unknown[2001:1:2:3::62]
Jun  1 11:52:00 icrvsgw003-wina postfix/lmtp[15245]: 1C23210237E: to=<recipient@otherdomain.com>, relay=none, delay=0.06, delays=0.03/0.03/0/0, dsn=4.4.1, status=deferred (connect to modoboa.server.com[private/dovecot-lmtp]: No such file or directory)
Jun  1 11:52:12 icrvsgw003-wina postfix/postscreen[14936]: CONNECT from [172.31.120.2]:44676 to [172.31.0.71]:25

## Local (modoboa server) queue ##
-Queue ID- --Size-- ----Arrival Time---- -Sender/Recipient-------
1C23210237E     1814 Thu Jun  1 09:52:00  sender@domain.com
(connect to modoboa.server.com[private/dovecot-lmtp]: No such file or directory)
                                         recipient@otherdomain.com
```
My config of the domain:
![screenshot at 2017-06-01 12-05-35](https://cloud.githubusercontent.com/assets/1810116/26675051/b95c0624-46c2-11e7-9a70-79e4eb91afd8.png)
![screenshot at 2017-06-01 12-05-50](https://cloud.githubusercontent.com/assets/1810116/26675052/b95fbbde-46c2-11e7-81a5-bf32dbf1a62c.png)

**Comment by tonioo** [comment]
How did you create your relay domain in modoboa?

**Comment by ursweiss** [comment]
Hmmm... After reading your answer i thought "let me try to recreate the relay domain". And bam, it works...
I will try to reproduce it now.

**Comment by ursweiss** [comment]
OK, i got it.

If i create the relay domain AND also create a "domain administrator" during the "New domain" wizard, which has the same name as the recipient i try to send mails to later (recipient@otherdomain.com in my example above), it fails with the error.

But:
If i create the domain without a domain administrator, it works. It still works if i create the domain and afterwards create an domain administrator identity with the same name as before during the wizard (recipient@...). Permissions for the domain assigned too of course.

**Comment by tonioo** [comment]
Actually, Modoboa allows the creation of local mailboxes for a relay domain. This can be useful when you want to migrate a domain to another server. So, if you create a user with a mailbox for your domain, it means it won't be routed. You can still create a domain administrator, just let the mail part empty.

**Comment by ursweiss** [comment]
OK, could make sense is some special cases. But in most cases, if you create a relay domain, you want it to relay mails (obviously). I cannot give a tool with such a default behavior to a customer/reseller, because we will get flooded with support requests because of that.

Within the domain wizard there is no option to not create a mailbox. If you select the checkbox to create a domain admin, it also creates an eMail address/mailbox. If you create the identity manually, you can select if you want to add an eMail address/mailbox.

Next, if i enable "Verify recipients" during the wizard, but don't add an domain admin/mailbox, it fails with the same error message. I think on a relay it should try to verify the eMail address by SMTP and not locally.

Finally, is there a way to send you a donation? I like the product and want to support it with some $$, or maybe an Amazon wishlist?

Thanks for your great and fast support. I appreciate that a lot!

**Comment by tonioo** [comment]
@ursweiss I guess we could add an option to allow the creation of local mailboxes for a relay domain.
The domain wizard is just a shortcut to get a prefilled domain, I could add a flag to create a mailbox or not but I don't want to introduce too much complexity on this part.

About the verify recipients option, I think your issues might be related to postfix verify cache (http://www.postfix.org/ADDRESS_VERIFICATION_README.html). What you can try is to remove this file and let postfix recreate it. Then, try your tests again.

About donation, there is a system available on the official website where you can finance features (https://modoboa.org/en/sponsor/). You can also use paypal to send me a donation directly.
As you prefer ;)

**Comment by tonioo** [comment]
@ursweiss Could you please explain me the "verify recipient" issue a bit more?

**Comment by tonioo** [comment]
@ursweiss ping

**Comment by ursweiss** [comment]
Sorry, was quite busy the last few weeks. Tried it again today and i cannot reproduce it at the moment. No idea what i did back then.

**Comment by tonioo** [comment]
Ok, so I think it was related to the verify cache. Thanks for your
donation btw ;-)
