### ISSUE TITLE
How to set up DKIM for domain name?

### ISSUE THREAD

**Issue by brylie** [modoboa/modoboa#1137]
How do users generate DKIM keys for Modoboa hosted mail domains?

# Impacted versions
Modoboa latest

# Steps to reproduce
1. add a new domain to Modoboa

# Expected behavior
It might be important for authenticity purposes to generate DKIM signatures for domain names.

https://www.emailonacid.com/blog/article/email-development/what_is_dkim_everything_you_need_to_know_about_digital_signatures

**Comment by tonioo** [comment]
There are two options to manage DKIM keys: use amavis (see https://github.com/modoboa/modoboa-amavis/issues/8) or use opendkim.

**Comment by brylie** [comment]
Thanks for the quick follow-up :-)

**Comment by jaketame** [comment]
Another one too look at is https://github.com/mailcow/mailcow

https://github.com/mailcow/mailcow/blob/master/opendkim/conf/opendkim.conf
https://github.com/mailcow/mailcow/blob/master/misc/mailcow-dkim-tool

**Comment by jaketame** [comment]
Could do something similar here, would be able to adapt for SPF too.
https://github.com/tknarr/opendkim-genkeys

**Comment by tonioo** [comment]
See #1325
