### ISSUE TITLE
Add a link to a demo installation to readme 

### ISSUE THREAD

**Issue by frlan** [modoboa/modoboa#1141]
I think subject says everything: It would be cool to find some kind of a demo project where to look around with some near-reality settings.

**Comment by tonioo** [comment]
@frlan Have you tried the official demo? https://demo.modoboa.org

**Comment by frlan** [comment]
No, because i didn't found it :/

**Comment by tonioo** [comment]
This is where you go when you click on "Try Modoboa" on the official website (https://modoboa.org/en/)

**Comment by frlan** [comment]
I did not find that. However, see my PR. This would solve the issue for me ;)
