### ISSUE TITLE
wildcard aliases

### ISSUE THREAD

**Issue by PalinuroSec** [modoboa/modoboa#1147]
Hi, is there any way to create wildcards from the modoboa interface?

for wildcard i mean something like myuser-*@domain.tld pointing to myuser@domain.ltd

 in the postfix configuration (main,cf) i have seen that the aliases are stored inside the postgresql database

`virtual_alias_maps =
        proxy:pgsql:/etc/postfix/sql-aliases.cf`

is there any way to pipeline it with the regexp: instruction? (http://www.postfix.org/regexp_table.5.html)

is it safe to create a new rule with an independent file-based alias map just for the users who need this kind of aliasing rules?

**Comment by tonioo** [comment]
@PalinuroSec Yes, you can add as many map as you need.

**Comment by tonioo** [comment]
@PalinuroSec And no, there is currently no way to create such aliases using Modoboa.

**Comment by PalinuroSec** [comment]
ok thank you
