### ISSUE TITLE
CentOS 7 install using apache requires modifications to wsgi.py

### ISSUE THREAD

**Issue by helgew** [modoboa/modoboa#1149]
# Impacted versions

* Modoboa: 1.7.4
* installer used: Yes
* Webserver: Apache

# Steps to reproduce

run the installer and [configure apache](http://modoboa.readthedocs.io/en/latest/manual_installation/webserver.html)

# Current behavior

In order to get the django application to work, I had to insert the following code into `wsgi.py` (right after `import os`):
```python
import sys
sys.path.append("/srv/modoboa/instance")

VIRTUAL_ENV = '/srv/modoboa/env'
# activate virtualenv
_activate = "%s/%s/activate_this.py" % (
    VIRTUAL_ENV,
    'Scripts' if sys.platform == 'win32' else 'bin'
)
if sys.version_info >= (3, 0):
    exec(compile(open(_activate, 'rb').read(), _activate, 'exec'))
else:
    execfile(_activate, dict(__file__=_activate))
```

# Expected behavior

"things just work" (not serious... this is either an improvement request or a cry for help, since I have not worked with django/modoboa before)

**Comment by tonioo** [comment]
The installer does not install apache, it is designed to install nginx. Are you asking for an apache support? BTW, can you move your issue to the installer repository please?

**Comment by helgew** [comment]
Moved [here](https://github.com/modoboa/modoboa-installer/issues/137). I am not asking for apache support, I am pointing out that following the documentation didn't work for me.
