### ISSUE TITLE
incompatibility between MariaDB 10.2.x MySQL-python/perl-DBD-MySQL

### ISSUE THREAD

**Issue by helgew** [modoboa/modoboa#1150]
This is just an FYI/documentation improvement suggestion about a [known issue](https://jira.mariadb.org/browse/MDEV-12950) with the latest stable MariaDB releases.

# Impacted versions

* Modoboa: any
* installer used: Yes
* Webserver: Nginx or Apache

# Steps to reproduce

run installer with mysql as DB engine and MariaDB 10.2.x installed

# Current behavior

MySQL-python installation fails

# Expected behavior

MySQL-python is installed

**Comment by tonioo** [comment]
Thank you for reporting this but the best place would be the installer repository (https://github.com/modoboa/modoboa-installer). Can you move this issue please?

**Comment by helgew** [comment]
Moved [here](https://github.com/modoboa/modoboa-installer/issues/136)
