### ISSUE TITLE
mail return issue

### ISSUE THREAD

**Issue by mzummo** [modoboa/modoboa#1159]
This is the mail system at host jjl-mx-1.xxxxxx.com. I'm sorry to have to inform you that your message could not be delivered to one or more recipients. It's attached below. For further assistance, please send mail to postmaster. If you do so, please include this problem report. You can delete your own text from the attached returned message. The mail system <"ghoffman@xxxxxx..com"@autoreply.xxxxxx.com> (expanded from <ghoffman@xxxxxx.com>): Command died with status 1: "/srv/modoboa/env/bin/python". Command output: Traceback (most recent call last): File "/srv/modoboa/instance/manage.py", line 22, in <module> execute_from_command_line(sys.argv) File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line utility.execute() File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute self.fetch_command(subcommand).run_from_argv(self.argv) File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv self.execute(*args, **cmd_options) File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute output = self.handle(*args, **options) File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_postfix_autoreply/management/commands/autoreply.py", line 169, in handle send_autoreply(sender, mbox, armessage, original_msg) File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_postfix_autoreply/management/commands/autoreply.py", line 78, in send_autoreply msg.send() File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/mail/message.py", line 342, in send return self.get_connection(fail_silently).send_messages([self]) File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 107, in send_messages sent = self._send(message) File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 121, in _send message = email_message.message() File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/mail/message.py", line 307, in message msg['Subject'] = self.subject File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/mail/message.py", line 232, in __setitem__ name, val = forbid_multi_line_headers(name, val, self.encoding) File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/mail/message.py", line 92, in forbid_multi_line_headers raise BadHeaderError("Header values can't contain newlines (got %r for header %r)" % (val, name)) django.core.mail.message.BadHeaderError: Header values can't contain newlines (got u'Auto: I am currently out of the office Re: Fwd: RE: Picked Up Issued Garnishment - No JJL Record - JJL to Serve?\n (Georgia)' for header u'Subject')

**Comment by tonioo** [comment]
@mzummo Looks like an autoreply issue. Which version are you running?

**Comment by mzummo** [comment]
@tonioo modoboa 1.7.2 - auto reply version 1.2.1

**Comment by tonioo** [comment]
I think your issue is the same than https://github.com/modoboa/modoboa-postfix-autoreply/issues/45 but with a complete stacktrace in your case.
