### ISSUE TITLE
"Extra adresses" not working as expected with smtpd_sender_login_maps

### ISSUE THREAD

**Issue by mundschenk-at** [modoboa/modoboa#1164]
# Impacted versions

* Modoboa: 1.7.4
* installer used: No
* Webserver: Nginx

# Steps to reproduce
Add the recommended settings to `main.cf`:

```
smtpd_sender_login_maps = mysql:$config_directory/modoboa/sql-sender-login-mailboxes.cf,
        mysql:$config_directory/modoboa/sql-sender-login-aliases.cf,
        mysql:$config_directory/modoboa/sql-sender-login-mailboxes-extra.cf
```

Create two users, add the address of the first user to the second as an "extra address" and try to send mail for it.

# Current behavior
The mail is rejected.

# Expected behavior
The second user can send mail using the first users address as sender.

# Solution
```
smtpd_sender_login_maps = unionmap:{
        mysql:$config_directory/modoboa/sql-sender-login-mailboxes.cf,
        mysql:$config_directory/modoboa/sql-sender-login-aliases.cf,
        mysql:$config_directory/modoboa/sql-sender-login-mailboxes-extra.cf }
```
While this solution needs Postfix 3.x, it provides the expected behavior (otherwise, Postfix stops a the first returned result of a query and `smtpd_sender_login_maps` lookups are resolved using the _sender address_).

**Comment by tonioo** [comment]
@mundschenk-at Sorry about the lack of response.
Indeed, this use case won't be possible without a unionmap. Do you know a solution for postfix < 3 ?

**Comment by mundschenk-at** [comment]
You could merge the three queries into one? But that would probably be messy SQL wise. Mainly I think this is a documentation issue.

**Comment by tonioo** [comment]
Indeed a SQL query using ``UNION`` statements could do the trick.
