### ISSUE TITLE
Unable to view domain created with Quota set to 0

### ISSUE THREAD

**Issue by ogg1980** [modoboa/modoboa#1166]
# Impacted versions

* Modoboa: 1.8.0
* installer used: No
* Webserver: Nginx

# Steps to reproduce

Create a domain, set Quota to 0 as per instructions to disable quota.

# Current behavior

Crashes domain view ( /admin/domains/<id>)

# Expected behavior

Shouldn't crash =D.

# Video/Screenshot link (optional)

Saved output when debug turned on (html file):
https://nextcloud.dalnix.se/index.php/s/AeWcJ0fhSyqTkAN/download

**Comment by ogg1980** [comment]
I get similar behaviour if I change an existing domains quota to 0 after it's been created. But then I get a divizion by zero error instead:

https://nextcloud.dalnix.se/index.php/s/klRwsUvnRqGYk4E/download (html output)

**Comment by pavinjosdev** [comment]
Same issue when creating domain with quota. Once a user is added, domain view doesn't crash though.
