### ISSUE TITLE
Query on certs

### ISSUE THREAD

**Issue by jaketame** [modoboa/modoboa#1170]
Does the LetsEncrypt allow for each domain to be included in the certificate?

I would like to provide customers with there own mail domain that is ssl enabled without having to accept certificates on devices as the name's mismatch. Mailcow can do this with domains.txt file.

Cheers

**Comment by tonioo** [comment]
I think LetsEncrypt allows to create to create one certificate for several domains but currently, the installer does not support it.

**Comment by jaketame** [comment]
Thanks for the response, how about post setup for when new domains are added?
