### ISSUE TITLE
Cookie issue: user redirected to ../accounts/login/None

### ISSUE THREAD

**Issue by pavinjosdev** [modoboa/modoboa#1180]
# Impacted versions

* Modoboa: 1.8.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

1. Login as User1 (SuperAdmin)
2. Logout.
3. Login as User2 (Resellers)

# Current behavior

When logging in as User2, he's redirected to https://modoboa.tld/accounts/login/None

"Sorry
The requested page does not exist."

# Expected behavior

Logging in and out as different users should be possible without clear cookies!

Tested in Chrome and Firefox (clean install) latest versions.

**Comment by Wedmer** [comment]
More info:
If you target to "/", you will be redirected to "/accounts/login/?next=/" and you will be redirected normally after login.
If you target directly to "/accounts/login/", you will be redirected to "/accounts/login/None" after login
