### ISSUE TITLE
[Feature Request] Virtual Domain SSL Cert

### ISSUE THREAD

**Issue by jaketame** [modoboa/modoboa#1181]
# Impacted versions

* Modoboa: All
* installer used: Yes
* Webserver: Nginx

# Current behavior
- Currently only top level domain certificate is generated, will cause issues with domains that want to hide the orginal mail server name, such as mail.primary.uk, mail.client1.uk

# Expected behavior
 - On domain creation within gui, option to enable SSL for the domain, automatic letsencrypt certificate generation (Multi-Domain SAN) and restart of services.

# Potential Implementation 
https://github.com/mail-in-a-box/free_tls_certificates

**Comment by jaketame** [comment]
IDEA:

Possibility to use the free_tls_certificates as a python plugin, store the ssl domains in db table

1) Admin interface to create/update with option to enable SSL for domain such as mail.new.com
2) Update domains sql table
3) Trigger issue.certificate via driver.py plugin, will detect new domain from db table and issue new cert, first domain will be primary domain on cert with others as additional domains (SAN)
4) Restart mail services.

Thoughts?

**Comment by kryskool** [comment]
This issue was moved to modoboa/modoboa-installer#199
