### ISSUE TITLE
Emails not readable anymore after upgrading from 1.1.0 to 1.1.5

### ISSUE THREAD

**Issue by christianwgd** [modoboa/modoboa#1182]
# Impacted versions

* Modoboa: 1.8.0
* installer used: No
* Webserver: Apache

# Steps to reproduce
I could provide the emails, that causes the errors, preferable in PN since the email-sender maybe would not like his emails to be posted here ;-)

# Current behavior
**1. Internal error is shown when trying to open the email:**
UnicodeDecodeError at /webmail/
'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

Request Method: GET
Request URL: https://webmail.ehv-nrw.de/webmail/?action=viewmail&mbox=INBOX&mailid=2430&_=1499706463180
Django Version: 1.10.7
Python Executable: /usr/bin/python
Python Version: 2.7.6
Python Path: ['/var/venvs/mail/lib/python2.7/site-packages', '/var/www/ehvmail/ehvnrw', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/pymodules/python2.7']
Server time: Mo, 10 Jul 2017 19:07:43 +0200
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'reversion',
 'ckeditor',
 'ckeditor_uploader',
 'rest_framework',
 'rest_framework.authtoken',
 'modoboa',
 'modoboa.core',
 'modoboa.lib',
 'modoboa.admin',
 'modoboa.relaydomains',
 'modoboa.limits',
 'modoboa.parameters',
 'modoboa_amavis',
 'modoboa_stats',
 'modoboa_webmail')
Installed Middleware:
('x_forwarded_for.middleware.XForwardedForMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'modoboa.core.middleware.LocalConfigMiddleware',
 'modoboa.lib.middleware.AjaxLoginRedirect',
 'modoboa.lib.middleware.CommonExceptionCatcher',
 'modoboa.lib.middleware.RequestCatcherMiddleware')

Traceback:  

File "/var/venvs/mail/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  42.             response = get_response(request)

File "/var/venvs/mail/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/var/venvs/mail/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/var/venvs/mail/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/venvs/mail/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/var/venvs/mail/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/var/venvs/mail/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa/admin/lib.py" in wrapped_f
  33.                 return f(request, *args, **kwargs)

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/views.py" in index
  621.         response = globals()[action](request)

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/views.py" in viewmail
  555.     email.fetch_headers()

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/imapemail.py" in fetch_headers
  75.             hdrvalue = self.get_header(msg, label, raw=raw_addresses)

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/imapemail.py" in get_header
  98.                 hdrvalue, **kwargs)

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/imapheader.py" in parse_to
  87.     return parse_address_list(value, **kwargs)

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/imapheader.py" in parse_address_list
  76.         result.append(parse_address(addr, **kwargs))

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/imapheader.py" in parse_address
  62.     addr = EmailAddress(value)

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa/lib/email_utils.py" in __init__
  23.         self.fulladdress = u2u_decode.u2u_decode(address).strip("\r\t\n")

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa/lib/u2u_decode.py" in u2u_decode
  50.     s = ''.join(s.splitlines())

Exception Type: UnicodeDecodeError at /webmail/
Exception Value: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

**2. Email opens but shows Django Debug Screen:**
ParseError at /webmail/getmailcontent
End of buffer reached while looking for a BODY/BODYSTRUCTURE end
Request Method:	GET
Request URL:	https://webmail.ehv-nrw.de/webmail/getmailcontent?mbox=INBOX&mailid=2356&links=0
Django Version:	1.10.7
Exception Type:	ParseError
Exception Value:	
End of buffer reached while looking for a BODY/BODYSTRUCTURE end
Exception Location:	/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/fetch_parser.py in parse_bodystructure, line 119
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/var/venvs/mail/lib/python2.7/site-packages',
 '/var/www/ehvmail/ehvnrw',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/pymodules/python2.7']
Server time:	Mo, 10 Jul 2017 19:19:05 +0200
Traceback Switch to copy-and-paste view

/var/venvs/mail/lib/python2.7/site-packages/django/core/handlers/exception.py in inner
            response = get_response(request) ...
▶ Local vars
/var/venvs/mail/lib/python2.7/site-packages/django/core/handlers/base.py in _legacy_get_response
            response = self._get_response(request) ...
▶ Local vars
/var/venvs/mail/lib/python2.7/site-packages/django/core/handlers/base.py in _get_response
                response = self.process_exception_by_middleware(e, request) ...
▶ Local vars
/var/venvs/mail/lib/python2.7/site-packages/django/core/handlers/base.py in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/var/venvs/mail/lib/python2.7/site-packages/django/utils/decorators.py in inner
                    return func(*args, **kwargs) ...
▶ Local vars
/var/venvs/mail/lib/python2.7/site-packages/django/utils/decorators.py in inner
                    return func(*args, **kwargs) ...
▶ Local vars
/var/venvs/mail/lib/python2.7/site-packages/django/contrib/auth/decorators.py in _wrapped_view
                return view_func(request, *args, **kwargs) ...
▶ Local vars
/var/venvs/mail/lib/python2.7/site-packages/modoboa/admin/lib.py in wrapped_f
                return f(request, *args, **kwargs) ...
▶ Local vars
/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/views.py in getmailcontent
        "mailbody": email.body if email.body else "" ...
▶ Local vars
/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/imapemail.py in body
            self.fetch_body_structure() ...
▶ Local vars
/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/imapemail.py in fetch_body_structure
                self.mbox, self.mailid, readonly=False ...
▶ Local vars
/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/imaputils.py in fetchmail
        data = self._cmd("FETCH", mailid, to_fetch) ...
▶ Local vars
/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/imaputils.py in _cmd
                return parse_fetch_response(data) ...
▶ Local vars
/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/fetch_parser.py in parse_fetch_response
            key, value = parse_response_chunk(content) ...
▶ Local vars
/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/fetch_parser.py in parse_response_chunk
            result[cmdname] = func(result[cmdname])[0] ...
▶ Local vars
/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/fetch_parser.py in parse_bodystructure
        "End of buffer reached while looking for a BODY/BODYSTRUCTURE end") ...
▶ Local vars

# Expected behavior

Normal viewing of all emails, like it was in 1.1.0

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
Unfortunately, this is a side effect of the python3 compatibility work. I'm working on the webmail compat., I hope it will be ready this week. (https://github.com/modoboa/modoboa-webmail/issues/85)

**Comment by tonioo** [comment]
@christianwgd It should be fixed by the new 1.2.0 release of the webmail.

**Comment by christianwgd** [comment]
Thanks for your work, but i'm afraid this didn't work. Upgraded to webmail 1.2.0 (which upgraded also modoboa to 1.8.2). The two mails are still unreadable with the same error from above.

Now there is another error in my javascript console: Error: Bootstrap's JavaScript requires jQuery
Globaler Code — bootstrap.min.js:6:89

Maybe i missed something in the update process, but there were no instructions till now, so i supposed there is nothing more to do like running the update and restart the server?

**Comment by tonioo** [comment]
@christianwgd I think your issue is different. It would be really useful if you could get the real issue because what you give does not help. Have you set DEBUG to True inside settings.py?

**Comment by christianwgd** [comment]
I had debug to True when i created these exception logs above and i did again to test now with the new version. The same two mails are failing and the first is leading to the same exception like the first one above. 

I can try again and post the new exception logs.

**Comment by christianwgd** [comment]
**1. email**
UnicodeDecodeError at /webmail/
'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

Request Method: GET
Request URL: https://webmail.ehv-nrw.de/webmail/?action=viewmail&mbox=INBOX&mailid=2430&_=1501263892341
Django Version: 1.10.7
Python Executable: /usr/bin/python
Python Version: 2.7.6
Python Path: ['/var/venvs/mail/lib/python2.7/site-packages', '/var/www/ehvmail/ehvnrw', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/pymodules/python2.7']
Server time: Fr, 28 Jul 2017 19:44:53 +0200
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'reversion',
 'ckeditor',
 'ckeditor_uploader',
 'rest_framework',
 'rest_framework.authtoken',
 'modoboa',
 'modoboa.core',
 'modoboa.lib',
 'modoboa.admin',
 'modoboa.relaydomains',
 'modoboa.limits',
 'modoboa.parameters',
 'modoboa_amavis',
 'modoboa_stats',
 'modoboa_webmail')
Installed Middleware:
('x_forwarded_for.middleware.XForwardedForMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'modoboa.core.middleware.LocalConfigMiddleware',
 'modoboa.lib.middleware.AjaxLoginRedirect',
 'modoboa.lib.middleware.CommonExceptionCatcher',
 'modoboa.lib.middleware.RequestCatcherMiddleware')


Traceback:  

File "/var/venvs/mail/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  42.             response = get_response(request)

File "/var/venvs/mail/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/var/venvs/mail/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/var/venvs/mail/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/venvs/mail/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/var/venvs/mail/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/var/venvs/mail/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa/admin/lib.py" in wrapped_f
  33.                 return f(request, *args, **kwargs)

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/views.py" in index
  622.         response = globals()[action](request)

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/views.py" in viewmail
  556.     email.fetch_headers()

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/imapemail.py" in fetch_headers
  76.             hdrvalue = self.get_header(msg, label, raw=raw_addresses)

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/imapemail.py" in get_header
  99.                 hdrvalue, **kwargs)

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/imapheader.py" in parse_to
  93.     return parse_address_list(value, **kwargs)

File "/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/imapheader.py" in parse_address_list
  79.     lst = values.split(",")

Exception Type: UnicodeDecodeError at /webmail/
Exception Value: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

**2. email:**

Request Method: | GET
-- | --
https://webmail.ehv-nrw.de/webmail/getmailcontent?mbox=INBOX&mailid=2356&links=0
1.10.7
ParseError
End of buffer reached while looking for a BODY/BODYSTRUCTURE end
/var/venvs/mail/lib/python2.7/site-packages/modoboa_webmail/lib/fetch_parser.py in parse_bodystructure, line 124
/usr/bin/python
2.7.6
['/var/venvs/mail/lib/python2.7/site-packages',  '/var/www/ehvmail/ehvnrw',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/usr/lib/pymodules/python2.7']
Fr, 28 Jul 2017 19:46:35 +0200

**Comment by christianwgd** [comment]
Ok, i tried to track this down to the content of those mails after viewing them in a different mail client: The first wasn't delivered to all recipients because the sender had put in one address with "Umlaut ü". After forwarding it to myself it was readable in modoboa webmail without problems (maybe this would only mean to show a proper error message although other mail clients have no Problem to show the mail addresses).

The second one had two attachments, one PDF and one image (jpg). After forwarding this one, the jpg was gone and the mail is also readable. 

I would suggest to leave this issue closed. I will monitor this and if i see something like that, i will analyze it and come back with more information... Thanks for your commitment to this.

Maybe you can give me a hint concerning the bootstraps complaining about missing jquery, because i've seen it now in other places (can't export identities because of this).
