### ISSUE TITLE
Internal Server Error on Webmail

### ISSUE THREAD

**Issue by danny-idingo** [modoboa/modoboa#1189]
Everything else works but when I log into an account and go to webmail I get an Internal Server Error or Internal Error. 

* Modoboa: 1.8.1
* installer used: Yes (modoboa installer)
* Webserver: Apache
* Ubuntu 16.04

**Comment by krekoten** [comment]
This is a duplicate of #1183 and I'm pretty sure of #1182 too. So I hope it will be fixed soon.

**Comment by tonioo** [comment]
@krekoten you're right.
