### ISSUE TITLE
Redirected to None page after each login

### ISSUE THREAD

**Issue by danielsatanik** [modoboa/modoboa#1191]
# Impacted versions

* Modoboa: X.X.x
* installer used: Yes/No ?
* Webserver: Nginx/Apache

# Steps to reproduce
Login

# Current behavior
After the login I am redirected to accounts/login/None, chopping off the path I am still logged in and can work normally.

# Expected behavior
After login I should be redirected to the dashboard or similar.

# Video/Screenshot link (optional)
<img width="1680" alt="screen shot 2017-07-23 at 02 20 10" src="https://user-images.githubusercontent.com/2507586/28495460-7be5abe8-6f4d-11e7-89f9-dd78f5689d91.png">

**Comment by csmk** [comment]
It's a duplicate: https://github.com/modoboa/modoboa/issues/1180

**Comment by danielsatanik** [comment]
thx for the redirection I guess its closed now, but how do I actually incorporate that? I changed the code in `/srv/modoboa/env/lib/python2.7/site-packages/modoboa` accordingly and built the python scripts with `python -m compileall` but unfortunately it is not having any effect

**Comment by tonioo** [comment]
@danielsatanik you must reload uwsgi.
