### ISSUE TITLE
ERROR: SQL: No module named psycopg2

### ISSUE THREAD

**Issue by acidsploit** [modoboa/modoboa#1193]
# Impacted versions
* Modoboa: 1.8.1
* Installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Test automx with automx-test script
See following error in /var/log/uwsgi/app/automx_instance.log:
ERROR: SQL: No module named psycopg2

# Current behavior
Generates: ERROR: SQL: No module named psycopg2

# Expected behavior
Generates no error

# Temp Fix
sudo su - automx 
source env/bin/activate
pip install psycopg2

# Fix
Fix installer?

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-installer#147
