### ISSUE TITLE
Mail for non-existing users is not rejected during SMTP dialog

### ISSUE THREAD

**Issue by helgew** [modoboa/modoboa#1197]
# Impacted versions

* Modoboa: 1.7.4
* installer used: Yes
* Webserver: Apache

# Current behavior

After removing a user who received a lot of spam, messages for the now deleted user are still processed for spam and quarantined.

# Expected behavior

Mail for non-existing users should be rejected outright.

**Comment by tonioo** [comment]
@helgew Actually, it is a normal behaviour if you installed Modoboa using the installer. Spam detection comes after postscreen and before postfix verifies if recipient exists. (see http://www.postfix.org/SMTPD_PROXY_README.html)

**Comment by helgew** [comment]
I see. Would you have any advice on how to configure [`smtpd_reject_unlisted_recipient`](http://www.postfix.org/postconf.5.html#smtpd_reject_unlisted_recipient) so that it would work with the virtual recipients configured via modoboa? My understanding is that `smtpd_reject_unlisted_recipient` kicks in during the SMTP dialogue.

**Comment by tonioo** [comment]
I think it'd work, but after postscreen and amavis checks (which is not a bad thing, think about a ddos using fake addresses). Have you tried to activate this setting?

**Comment by tonioo** [comment]
Inactive thread => close.
