### ISSUE TITLE
Getmailcontent yields error on first try

### ISSUE THREAD

**Issue by danielsatanik** [modoboa/modoboa#1203]
# Impacted versions

* Modoboa: 1.8.2
* installer used: Yes (configured cfg, no amavis)
* Webserver: Nginx

# Steps to reproduce
On may installation it happens every time an unread message is opened.
When the message is read it works fine. So reloading works.
Setting the message back to unread, yields the same problem.

# Current behavior
A red banner is displayed, informing about an internal error.

# Expected behavior
Mail content should be displayed.

# Video/Screenshot link (optional)

<img width="608" alt="screen shot 2017-07-29 at 05 27 50" src="https://user-images.githubusercontent.com/2507586/28741801-13c72948-741f-11e7-853f-610c13a8d3ee.png">

**Comment by tonioo** [comment]
This error concerns the webmail so the right repository to report it is https://github.com/modoboa/modoboa-webmail.

**Comment by danielsatanik** [comment]
Ok I'll report it there…
