### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'DjangoFilterBackend' on upgrade 1.8.1 -> 1.8.2

### ISSUE THREAD

**Issue by acidsploit** [modoboa/modoboa#1205]
# Impacted versions

* Modoboa: 1.8.1 / 1.8.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Upgrade modoboa from 1.8.1 to 1.8.2
Run the migrate command: python manage.py migrate

# Current behavior
    thomas@mail~$ sudo su - modoboa                                                                             
    [sudo] password for thomas:                                                                                            
    modoboa@mail:~$ source env/bin/activate                                                                                
    (env) modoboa@mail:~$ pip install modoboa==1.8.2                                                                       
    Collecting modoboa==1.8.2                                                                                              
    Downloading modoboa-1.8.2.tar.gz (3.9MB)                                                                             
        100% |████████████████████████████████| 3.9MB 344kB/s                                                              
    Requirement already satisfied: django<=1.10.99,>=1.10 in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)       
    Requirement already satisfied: django-ckeditor==5.2.1 in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)       
    Requirement already satisfied: django-reversion==1.10.2 in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)     
    Requirement already satisfied: django-subcommand2==0.1.1 in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)    
    Requirement already satisfied: django-versionfield2>=0.5.0 in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)  
    Requirement already satisfied: django-xforwardedfor-middleware in ./env/lib/python2.7/site-packages (from modoboa==1.8.
    2)                                                                                                                     
    Requirement already satisfied: dj-database-url in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)              
    Collecting coreapi==2.3.1 (from modoboa==1.8.2)                                                                        
    Downloading coreapi-2.3.1-py2.py3-none-any.whl (110kB)                                                               
        100% |████████████████████████████████| 112kB 4.4MB/s                                                              
    Requirement already satisfied: coreapi-cli==1.0.6 in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)           
    Collecting djangorestframework==3.6.3 (from modoboa==1.8.2)                                                            
    Downloading djangorestframework-3.6.3-py2.py3-none-any.whl (1.3MB)                                                   
        100% |████████████████████████████████| 1.3MB 819kB/s                                                              
    Requirement already satisfied: argparse in /usr/lib/python2.7 (from modoboa==1.8.2)                                    
    Collecting bcrypt==3.1.3 (from modoboa==1.8.2)                                                                         
    Downloading bcrypt-3.1.3-cp27-cp27mu-manylinux1_x86_64.whl (57kB)                                                    
        100% |████████████████████████████████| 61kB 5.5MB/s                                                               
    Requirement already satisfied: dnspython==1.15.0 in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)            
    Requirement already satisfied: feedparser==5.2.1 in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)            
    Requirement already satisfied: gevent==1.2.1 in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)                
    Requirement already satisfied: ipaddress in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)                    
    Requirement already satisfied: jsonfield==1.0.3 in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)             
    Collecting passlib==1.7.1 (from modoboa==1.8.2)                                                                        
    Downloading passlib-1.7.1-py2.py3-none-any.whl (498kB)                                                               
        100% |████████████████████████████████| 501kB 2.3MB/s                                                              
    Requirement already satisfied: progressbar33==2.4 in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)           
    Requirement already satisfied: py-dateutil==2.2 in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)             
    Collecting cryptography (from modoboa==1.8.2)                                                                          
    Downloading cryptography-2.0.2-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)                                             
        100% |████████████████████████████████| 2.2MB 684kB/s                                                              
    Requirement already satisfied: pytz in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)                         
    Requirement already satisfied: requests in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)                     
    Requirement already satisfied: rfc6266 in ./env/lib/python2.7/site-packages (from modoboa==1.8.2)                      
    Requirement already satisfied: six>=1.9.0 in ./env/lib/python2.7/site-packages (from django-versionfield2>=0.5.0->modo$
    oa==1.8.2)                                                 
    Requirement already satisfied: coreschema in ./env/lib/python2.7/site-packages (from coreapi==2.3.1->modoboa==1.8.2)   
    Requirement already satisfied: itypes in ./env/lib/python2.7/site-packages (from coreapi==2.3.1->modoboa==1.8.2)
    Requirement already satisfied: uritemplate in ./env/lib/python2.7/site-packages (from coreapi==2.3.1->modoboa==1.8.2)  
    Requirement already satisfied: click>=6.0 in ./env/lib/python2.7/site-packages (from coreapi-cli==1.0.6->modoboa==1.8.$
    )                                                                                                                      
    Requirement already satisfied: cffi>=1.1 in ./env/lib/python2.7/site-packages (from bcrypt==3.1.3->modoboa==1.8.2)
    Requirement already satisfied: greenlet>=0.4.10 in ./env/lib/python2.7/site-packages (from gevent==1.2.1->modoboa==1.8$2)                           
    Requirement already satisfied: idna>=2.1 in ./env/lib/python2.7/site-packages (from cryptography->modoboa==1.8.2)      
    Collecting asn1crypto>=0.21.0 (from cryptography->modoboa==1.8.2)                                                      
    Downloading asn1crypto-0.22.0-py2.py3-none-any.whl (97kB)
        100% |████████████████████████████████| 102kB 5.6MB/s          
    Collecting enum34 (from cryptography->modoboa==1.8.2)      
    Downloading enum34-1.1.6-py2-none-any.whl
    Requirement already satisfied: urllib3<1.22,>=1.21.1 in ./env/lib/python2.7/site-packages (from requests->modoboa==1.8.
    2)
    Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./env/lib/python2.7/site-packages (from requests->modoboa==1.8.
    2)
    Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python2.7/site-packages (from requests->modoboa==1.8.2)
    Requirement already satisfied: LEPL in ./env/lib/python2.7/site-packages (from rfc6266->modoboa==1.8.2)
    Requirement already satisfied: jinja2 in ./env/lib/python2.7/site-packages (from coreschema->coreapi==2.3.1->modoboa==1
    .8.2)
    Requirement already satisfied: pycparser in ./env/lib/python2.7/site-packages (from cffi>=1.1->bcrypt==3.1.3->modoboa==
    1.8.2)
    Requirement already satisfied: MarkupSafe>=0.23 in ./env/lib/python2.7/site-packages (from jinja2->coreschema->coreapi=
    =2.3.1->modoboa==1.8.2)
    Building wheels for collected packages: modoboa
    Running setup.py bdist_wheel for modoboa ... done
    Stored in directory: /srv/modoboa/.cache/pip/wheels/3c/27/49/57ad18835ab0253dd3bf4b20e9b1abaa3cb85d692f655aea59
    Successfully built modoboa
    Installing collected packages: coreapi, djangorestframework, bcrypt, passlib, asn1crypto, enum34, cryptography, modoboa
    Found existing installation: coreapi 2.3.0
        Uninstalling coreapi-2.3.0:
        Successfully uninstalled coreapi-2.3.0
    Found existing installation: djangorestframework 3.6.2
        Uninstalling djangorestframework-3.6.2:
        Successfully uninstalled djangorestframework-3.6.2
    Found existing installation: bcrypt 2.0.0
        Uninstalling bcrypt-2.0.0:
        Successfully uninstalled bcrypt-2.0.0
    Found existing installation: passlib 1.6.5
        Uninstalling passlib-1.6.5:
        Successfully uninstalled passlib-1.6.5
    Found existing installation: modoboa 1.8.1
        Uninstalling modoboa-1.8.1:
        Successfully uninstalled modoboa-1.8.1
    Successfully installed asn1crypto-0.22.0 bcrypt-3.1.3 coreapi-2.3.1 cryptography-2.0.2 djangorestframework-3.6.3 enum34
    -1.1.6 modoboa-1.8.2 passlib-1.7.1
    (env) modoboa@mail:~$ ls
    env  instance  pdfcredentials  rrdfiles
    (env) modoboa@mail:~$ cd instance/
    (env) modoboa@mail:~/instance$ ls
    instance  manage.py  media  sitestatic

    (env) modoboa@mail:~/instance$ python manage.py migrate
    Traceback (most recent call last):
    File "manage.py", line 22, in <module>
        execute_from_command_line(sys.argv)
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_fr
    om_command_line
        utility.execute()
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
        self.execute(*args, **cmd_options)
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 342, in execute
        self.check()
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
        include_deployment_checks=include_deployment_checks,
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in _ru
    n_checks
        issues.extend(super(Command, self)._run_checks(**kwargs))
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
        return checks.run_checks(**kwargs)
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
        new_errors = check(app_configs=app_configs)
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
        return check_resolver(resolver)
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
        for pattern in resolver.url_patterns:
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
        patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
        return import_module(self.urlconf_name)
    File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    File "/srv/modoboa/instance/instance/urls.py", line 4, in <module>
        url(r'', include('modoboa.urls')),
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
        urlconf_module = import_module(urlconf_module)
    File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/urls.py", line 57, in <module>
        url("^api/v1/", include("modoboa.urls_api", namespace="api")),
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
        urlconf_module = import_module(urlconf_module)
    File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/urls_api.py", line 14, in <module>
        urlpatterns += exts_pool.get_urls(category="api")
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/extensions.py", line 118, in get_urls
        url(root, include(pattern.format(ext_name), **options))
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
        urlconf_module = import_module(urlconf_module)
    File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_contacts/urls_api.py", line 5, in <module>
        from . import viewsets
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_contacts/viewsets.py", line 3, in <module>
        import django_filters.rest_framework
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django_filters/rest_framework/__init__.py", line 3, in <module>
        from .backends import DjangoFilterBackend
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/django_filters/rest_framework/backends.py", line 7, in <module>
        from rest_framework.filters import BaseFilterBackend
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/rest_framework/filters.py", line 54, in <module>
        DFBase = django_filters.rest_framework.DjangoFilterBackend
    AttributeError: 'NoneType' object has no attribute 'DjangoFilterBackend'

# Expected behavior
Clean migration

**Comment by tonioo** [comment]
Duplicates #1202. Please update contacts plugin to 0.4.0.
