### ISSUE TITLE
centos 7.3 on digitalocean

### ISSUE THREAD

**Issue by iahim** [modoboa/modoboa#1214]
# Impacted versions
I am using CentOS Linux release 7.3.1611 (Core)
latest one from git as of ... today :) 

* Modoboa: X.X.x
* installer used: Yes ?
* Webserver: Nginx

# Steps to reproduce
just run the installer and:

Welcome to Modoboa installer!
Configuration file installer.cfg not found, creating new one.
Your mail server will be installed with the following components:
modoboa automx amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) Y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Generating new self-signed certificate
Installing amavis
Installing spamassassin
Installing razor
Installing clamav
Installing modoboa
Installing automx
Installing uwsgi
Installing nginx
Traceback (most recent call last):
  File "./run.py", line 91, in <module>
    main()
  File "./run.py", line 81, in main
    scripts.install("nginx", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 22, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 147, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/nginx.py", line 64, in post_run
    self._setup_config("automx", hostname)
  File "/root/modoboa-installer/modoboa_installer/scripts/nginx.py", line 53, in _setup_config
    utils.copy_from_template(src, dst, context)
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 135, in copy_from_template
    with open(dest, "w") as fp:
IOError: [Errno 2] No such file or directory: '/etc/nginx/conf.d/autoconfig.mail01.brad24.ro.conf

**Comment by iahim** [comment]
i tried the same thing on an Ubuntu 16.04 and the installer just stopped ... with no message after installing modoboa package.

**Comment by iahim** [comment]
it worked on ubuntu 14.04

**Comment by tonioo** [comment]
I just tried on a fresh CentOS 7.3 and I can't reproduce your issue. Have you made all your tests on digital ocean box? If so, how much RAM do you have?

**Comment by mylastore** [comment]
@tonioo what programs are you using for templates and can they be modify?

**Comment by tonioo** [comment]
@mylastore What do you mean by templates?

**Comment by mylastore** [comment]
@tonioo views

**Comment by mylastore** [comment]
@tonioo can the views be modify?

**Comment by tonioo** [comment]
@mylastore if you're talking about the web interface, you're not at the right place. You should ask your question in the https://github.com/modoboa/modoboa repository.

**Comment by gawel** [comment]
So it's the right place :D (it was the wrong place to talk about the installer)

**Comment by tonioo** [comment]
@gawel T_T
@mylastore it's indeed the right repository but not the right issue

**Comment by tonioo** [comment]
@iahim ping

**Comment by iahim** [comment]
@tonioo  Sorry - i stopped testing. I ended up using mailinabox (although they support only ubuntu 14.04). 
I will run another test today on centos.

**Comment by iahim** [comment]
So i just testeg again on centos 7.
Installer worked. Before i think it was my error - i didn't chose probably 1GB of ram. 
I see that in idle state the vm consumes around 720MB ram.

Welcome to Modoboa installer!
Configuration file installer.cfg not found, creating new one.
Your mail server will be installed with the following components:
modoboa automx amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) Y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Generating new self-signed certificate
Installing amavis
Installing spamassassin
Installing razor
Installing clamav
Installing modoboa
Installing automx
Installing uwsgi
Installing nginx
Installing postfix
Installing dovecot
Congratulations!

**Comment by iahim** [comment]
So the linux version is CentOS Linux release 7.4.1708 (Core)
But i get  a lof of
Sorry
An internal error occured.

I am sorry i do not have time to test some more.
