### ISSUE TITLE
Cannot attach file to email

### ISSUE THREAD

**Issue by svandecappelle** [modoboa/modoboa#1220]
# Impacted versions

* Modoboa: 1.8.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Send a mail and add an attachement file. (tested file is 400 octets sized)

# Current behavior
It generate an error 'file too big' (max size is 2048).

# Expected behavior
File added and uploaded on email.

# Video/Screenshot link (optional)
http://imgur.com/a/A5pxq

**Comment by tonioo** [comment]
You can change the max. size allowed for uploaded files. Go to Modoboa > Parameters > Webmail.

**Comment by svandecappelle** [comment]
But in this case the file I tried to upload was lower than the parameter.

**Comment by tonioo** [comment]
@svandecappelle Have you tried to change the max value?

**Comment by VladimirKiev** [comment]
> @svandecappelle Have you tried to change the max value?

Hi. I have the same problem. Changed the value to a larger one (20480) - writes the same error but with the new value (Attachment is too big (limit: 20480).
Please tell me where you can change this value to fix the error ...

**Comment by tonioo** [comment]
@VladimirKiev Try with something like this: 20M

**Comment by VladimirKiev** [comment]
> @VladimirKiev Try with something like this: 20M

New error: Failed to save attachment: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail/tmp05zWR1'

**Comment by VladimirKiev** [comment]
> @VladimirKiev Try with something like this: 20M

I also checked the web_utils.py file as an example here https://github.com/modoboa/modoboa/blob/9f2ea29a9fe0cf78db2cf340e286601dc799756a/modoboa/lib/web_utils.py#L117
changed the values of client_max_body_size on nginx.conf. nothing helped. Your help is very necessary ...

**Comment by tonioo** [comment]
@VladimirKiev Have you checked if the `/srv/modoboa/instance/media/webmail/`folder exists?

**Comment by VladimirKiev** [comment]
> @VladimirKiev Have you checked if the `/srv/modoboa/instance/media/webmail/`folder exists?

There is        /srv/modoboa/instance/media/modoboa_webmail        folder...

![image](https://user-images.githubusercontent.com/53512202/74412578-707ae180-4e46-11ea-9d47-9eb5e81ff009.png)
