### ISSUE TITLE
Non-ASCII chars in password 

### ISSUE THREAD

**Issue by GreenItSolutions** [modoboa/modoboa#1221]
# Impacted versions

* Modoboa: 1.8.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

Create a user with 'é' in the password
Can't login because encoding character is not correct.

exemple:
Eé111111 ->  E\xe9111111

seems to be similar to #1218 issue

can you help us ?
Is it possible to have correction in 1.8.3?
release date of 1.8.3 ?
Thanks in advance 

# VALUE ERROR :

Variable | Value
-- | --
username | u'bertrand@domain.tld'
csrfmiddlewaretoken | u'MtmKVOKzVa94btEUBPDPEQf2Ae19KKnoP80PNnK1z52VQRTOdT5yz5JE84z8V6St'
password | u'E\\\xe9111111'
next | u''

`
Exception Type:	ValueError

Exception Value:	
The length of the provided data is not a multiple of the block length.

Exception Location:	/srv/modoboa/env/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py in finalize, line 172

Python Version:	2.7.13

Python Path:  ['.',  '',  '/srv/modoboa/env/lib/python2.7', 
 '/srv/modoboa/env/lib/python2.7/plat-x86_64-linux-gnu',  
'/srv/modoboa/env/lib/python2.7/lib-tk', 
 '/srv/modoboa/env/lib/python2.7/lib-old', 
 '/srv/modoboa/env/lib/python2.7/lib-dynload', 
 '/usr/lib/python2.7',  
'/usr/lib/python2.7/plat-x86_64-linux-gnu',  
'/usr/lib/python2.7/lib-tk',  '/srv/modoboa/env/local/lib/python2.7/site-packages',  '/srv/modoboa/env/lib/python2.7/site-packages']

`

**Comment by HuTaeh** [comment]
Hi,
We make modoboa update in 1.8.3 and 1.9.0 but we get similar issue.

```
Request Method: | GET
-- | --
1.10.7
UnicodeEncodeError
'ascii' codec can't encode character u'\xe9' in position 58: ordinal not in range(128)
/usr/lib/python2.7/socket.py in meth, line 228
/usr/bin/uwsgi-core
2.7.13
['.',  '',  '/srv/modoboa/env/lib/python2.7',  '/srv/modoboa/env/lib/python2.7/plat-x86_64-linux-gnu',  '/srv/modoboa/env/lib/python2.7/lib-tk',  '/srv/modoboa/env/lib/python2.7/lib-old',  '/srv/modoboa/env/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/srv/modoboa/env/local/lib/python2.7/site-packages',  '/srv/modoboa/env/lib/python2.7/site-packages']
mer, 13 Sep 2017 10:25:06 +0200
```
We used this passphrase to generate this error `Des encyclopédistes emmènent les univers.`

Can you help us ?
 Thanks in advance
