### ISSUE TITLE
Webmail PDF Credential

### ISSUE THREAD

**Issue by WASDIT** [modoboa/modoboa#1224]
Hello If i try at some users to print the credentials i recived an error see attachment.
[AlreadyFinalized at _modoboa_pdfcredentials_credentials_25_.pdf](https://github.com/modoboa/modoboa/files/1274599/AlreadyFinalized.at._modoboa_pdfcredentials_credentials_25_.pdf)

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-pdfcredentials#14
