### ISSUE TITLE
What happened to the AccountCreated event?

### ISSUE THREAD

**Issue by djcf** [modoboa/modoboa#1229]
[This version](https://modoboa.readthedocs.io/en/1.5.3/extending/events.html) of Modoboa's documentation lists an `AccountCreated` event which plugins could potentially subscribe to. However I understand that in the current version (1.9.x) of Modoboa, events were replaced with signals. [I cannot find](https://pastebin.com/Y6ii5a4D) an equivalent signal in the codebase.

**Comment by tonioo** [comment]
@djcf events have been replaced by regular django signals. Instead, you can use the ``post_save`` signal (https://docs.djangoproject.com/fr/1.10/ref/signals/#post-save) on the ``core.models.User`` model. (example: https://github.com/modoboa/modoboa/blob/master/modoboa/limits/handlers.py#L48)
