### ISSUE TITLE
No error displayed when user password does not respect validation rules

### ISSUE THREAD

**Issue by buttch** [modoboa/modoboa#1231]
# Impacted versions

* Modoboa: 1.9.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

After fresh installation I'm not able to create a new user. The only response I get from /admin/accounts/new/ endpoint is following with status 400 
[response.txt](https://github.com/modoboa/modoboa/files/1300836/response.txt)

It occurs after hit Next in new user wizard window, so it's not even a Submit.
It's with Debug=True and I cannot find any reason for this issue in any log file I'm aware of.

I've tried to switch off the pdfcredentials as I'd seen [this issue](https://github.com/modoboa/modoboa/issues/1228) but with no success. 

Regards

**Comment by buttch** [comment]
Ok I found the reason and it was a weak password for new user but there is no information about that failing validation. Can I find this information in any logs ?

**Comment by tonioo** [comment]
Looks like a bug because an error message should be displayed. I'll look into it.
