### ISSUE TITLE
fetch users' emails through api

### ISSUE THREAD

**Issue by alexandrapersea** [modoboa/modoboa#1233]
Is there a way to fetch a user's emails through the modoboa api?

**Comment by tonioo** [comment]
@alexandrapersea you can use the ``accounts`` service. For example:
```
GET /api/v1/accounts/{id}
```
The answer must contain the email.

**Comment by alexandrapersea** [comment]
@tonioo sorry for not being specific enough, what i meant is getting the user's email messages

**Comment by tonioo** [comment]
No, there is no such feature provided by the API. The only solution you have (for now) is to use IMAP.

**Comment by Ramsteven** [comment]
Hello, do currently exist the way they get the email of a specific account? I want to avoid using other libraries.
