### ISSUE TITLE
Contacts do not work in Debug mode

### ISSUE THREAD

**Issue by buttch** [modoboa/modoboa#1235]
# Impacted versions

* Modoboa: 1.9.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Set Debug=True in settings.py and then try to open Contacts tab in Webmail.

# Current behavior
Error visible. IOException - no file.

# Expected behavior
See contacts.

In Debug mode it looking for webpack-stats.json file in place which does not exist.

**Comment by tonioo** [comment]
@buttch This issue concerns the contacts plugin so this is not the right repository. Anyway, make sure you read https://github.com/modoboa/modoboa-contacts#for-developpers. When you set DEBUG to True, Modoboa considers you're in development mode so you need to run the ``npm run dev`` command.
