### ISSUE TITLE
postfix's main.cf should have an entry for $mydestination

### ISSUE THREAD

**Issue by TonyBostonTB** [modoboa/modoboa#1238]
# Impacted versions

* Modoboa: 1.9.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

- Install everything via installer. 
- $EDITOR /etc/aliases | change root mail
- $ newaliases

# Current behavior
- postfix doesn't use /etc/aliases.db

# Expected behavior
- postfix now uses the just set root mail

One has to change /etc/postfix/main.cf to have the following
$mydestination = $myhostname

**Comment by tonioo** [comment]
This is intentional. Instead, I'd like to setup a default domain in Modoboa corresponding to the hostname with an administrator and a catchall alias to receive all emails sent by daemon programs. What do you think?

**Comment by paulchabotca** [comment]
This is great, but currently as it stands, message ids look like this.
Message-ID: <20171002090039.1244.83116@localhost.localdomain>

**Comment by tuxis-ie** [comment]
I think on a Linux machine, people are used to redirect root to a specific address. Having to install the localdomain into modoboa and create a forward there seems inefficient.

**Comment by tonioo** [comment]
Changed (https://github.com/modoboa/modoboa-installer/commit/111cb83b07270032a928425009522d94b0c82b88).
