### ISSUE TITLE
Superadmin Username must be valid Mailaddress else webmail authentication fails

### ISSUE THREAD

**Issue by jakicoll** [modoboa/modoboa#1240]
I'm impressed by the great functionality and how easy modoboa is. Thank you very much! :)
However poking around a litte I guess I found a bug:

# Impacted versions

* Modoboa: 1.9.0.
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
* Login as superadmin and go to Identities
* Create a new superadmin accout with user name "foo" and some password
* Click on "Next" and then enter foo@mydomain.de as E-mail Address. Submit.
* Logout
* Login as foo
* Click on Webmail

# Current behavior

Webmail tries to login as ```user=<foo>```:
> Sep 20 20:29:27 vs****** dovecot[449]: imap-login: Disconnected (auth failed, 1 attempts in 2 secs): user=<foo>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, secured, session=<LXLt1KRZvAB/AAAB>

Browser displays:
> Error: ['[AUTHENTICATIONFAILED] Authentication failed.']

# Expected behavior
Browser displays mailbox. :)

# Note
If you change the username from foo to foo@mydomain.de, everything works as expected.
I guess, instead of the username, the webmail should pass the E-mail Adress associated with the username to Dovecot...

**Comment by tonioo** [comment]
I guess the simplest way to fix this issue would be to enforce same values for username and email address once the email address is defined. What do you think?

**Comment by jakicoll** [comment]
Good idea, that should do the trick. :)
The error message displayed to the user should explain it a little, e.g.:

"If you define or change the mail address for this account, you need to
change it's username to the same value."

**Comment by makakken** [comment]
Just a hint would be nice. I was running into same issue after fresh modoboa install. luckily i found this thread. I really think it's a reason to change to other software if webmail (which you run to test after first time installs) is not working! 👍
