### ISSUE TITLE
cronjob fails $PYTHON $INSTANCE/manage.py communicate_with_public_api

### ISSUE THREAD

**Issue by TonyBostonTB** [modoboa/modoboa#1245]
# Impacted versions

* Modoboa: 1.9.0
* installer used: Yes
* Webserver: Nginx
* OS: Centos 7
* DB: Postgresql

# Traceback

```
CommandError: Failed to retrieve versions from the API.
```

**Comment by tonioo** [comment]
Have you tried to run the command manually? Do you always have the same result?

**Comment by danielsatanik** [comment]
happens again
