### ISSUE TITLE
Multiple general questions

### ISSUE THREAD

**Issue by Extarys** [modoboa/modoboa#1246]
Hey, this seems like awesome project!

- I wanted to make sure, even though there is still pull requests, that this isn't abandoned or is not planned ot be.
- That is production ready for a small group of people
- That there is a strong spam and virus protection
- Planning or support for multiple servers? :)

- Could I help update the GUI to Bootstrap 4? Modernize it a little?
- Suggest features when they pops in - I got a strong imagination

Thanks!

EDIT: I don't understand regex (I know, I know), but it would be awesome if someone could create a fail2ban jail for all aspect of modoboa :) I love security and brute force is a bit**

**Comment by tonioo** [comment]
Hi,
to answer your questions:
* The project is active and we don't plan to stop working on it
* It is production ready
* There is a strong spam and virus protection
* There is no special plan to support multiple servers setup if this is what you mean
* You could indeed help to mordernize the web ui
* Your ideas are welcome as long as they can be useful to Modoboa ;-)

**Comment by Extarys** [comment]
Thanks buddy :)
