### ISSUE TITLE
password scheme  {MD5-CRYPT}

### ISSUE THREAD

**Issue by moumour** [modoboa/modoboa#1253]
# Impacted versions

* Modoboa: 1.9.
* installer used: Yes
* Webserver: Nginx

The scheme {MD5-CRYPT} produce a hash with $1 at the first character
usually in the password /etc/shadow first character $1 mean: $1 = MD5 hashing algorithm, but after the first $1 has one more $ with the salt, after the salt has one more $ with the md5 hash of password.
Your {MD5-CRYPT} scheme has only $1 without salt. 
{MD5-CRYPT} scheme is the same as MD5 with additional $1? or the {MD5-CRYPT} scheme support salt?

**Comment by tonioo** [comment]
Modoboa relies on ``passlib`` to hash passwords. Looks like MD5Crypt supports salt (http://passlib.readthedocs.io/en/stable/lib/passlib.hash.md5_crypt.html).
