### ISSUE TITLE
Need to re-create modoboa's database

### ISSUE THREAD

**Issue by sorcer1122** [modoboa/modoboa#1255]
Hello,

I was trying to install afterlogic webmail frontend but it messed up my MariaDB and I ended up loosing modoboa's database before I made a backup. So, I would appreciate if anyone could help me to recreate the database again. I have created a user already, created a DB, granted this user rights over the DB and now I am getting the following in postfix log:

warning: mysql query failed: Table 'modoboa.admin_domain' doesn't exist

When I try to create this table, it asks me about columns and I have no idea how many columns I need.

Thanks in advance!

**Comment by tonioo** [comment]
@sorcer1122 How did you install modoboa?

**Comment by sorcer1122** [comment]
@tonioo I installed it via the script run.py, so automated installation.

**Comment by tonioo** [comment]
Ok, so the easiest way to recreate your database is to run the following commands:
```bash
> su - modoboa
> bash
> source env/bin/activate
> cd instance
> python manage.py migrate
> python manage.py load_initial_data
> python manage.py set_default_site <your hostname here>
```
If it doesn't, drop the modoboa database, recreate it, check permissions and try again.

**Comment by sorcer1122** [comment]
@tonioo Thanks!

**python manage.py migrate** gives me
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, core, lib, limits, modoboa_amavis, modoboa_contacts, modoboa_postfix_autoreply, relaydomains, reversion, sessions, sites
Running migrations:
  No migrations to apply.

**python manage.py load_initial_data** gives no output

**python manage.py set_default_site mydomain.com** gives no output

However, it did not help. So, I dropped DB, recreated it and gave permissions:

+------------------------------------------------------------------------+
| Grants for modoboa@%                                                   |
+------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'modoboa'@'%'                                    |
| GRANT ALL PRIVILEGES ON `modoboa`.* TO 'modoboa'@'%' WITH GRANT OPTION |
+------------------------------------------------------------------------+

However, it still does not work, here is what I see in DB:

MariaDB [modoboa]> show tables;
Empty set (0.00 sec)

Any ideas?

**Comment by tonioo** [comment]
Check the instance/settings.py file to see if you've configured the same database...

**Comment by sorcer1122** [comment]
@tonioo I checked settings.py and I can see that the DB is the same. I have also tried to re-create a user again and granted it all rights over the database, I have ended up with the following (I only need local connection):

+----------------------------------------------------------------------------------------------------------------+
| Grants for modoboa@localhost                                                                                   |
+----------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'modoboa'@'localhost' IDENTIFIED BY PASSWORD '*HASH_PASS' |
| GRANT ALL PRIVILEGES ON `modoboa`.* TO 'modoboa'@'localhost'                                                   |
+----------------------------------------------------------------------------------------------------------------+

I am still getting:

MariaDB [modoboa]> show tables;
Empty set (0.00 sec)

**Comment by tonioo** [comment]
@sorcer1122 and what happens if you run the migrate command once again ?

**Comment by sorcer1122** [comment]
@tonioo All the time same output:

Apply all migrations: admin, auth, authtoken, contenttypes, core, lib, limits, modoboa_amavis, modoboa_contacts, modoboa_postfix_autoreply, relaydomains, reversion, sessions, sites
Running migrations:
  No migrations to apply.

**Comment by sorcer1122** [comment]
Not sure whether it is helpful but...

I am also not able to update any extensions. After I do pip install modoboa-.....==1.2.0, extensions is being downloaded but after I do python manage.py migrate, I get 'no migrations to apply'. After python manage.py collectstatic I get '0 static files copied to '/srv/modoboa/instance/sitestatic', 2204 unmodified' and the extension is still there, outdated.

Funnily enough, everything seems to work smoothly: I can add domains, aliases, email users. I am not confused dot com.

**Comment by tonioo** [comment]
@sorcer1122 So you're saying everything works as expected now?

**Comment by sorcer1122** [comment]
@tonioo it looks like yes, everything is working. I do not see any errors in logs. However, I am not able to update any extensions (as I explained above).

**Comment by tonioo** [comment]
Have you reloaded uwsgi?

**Comment by sorcer1122** [comment]
Thanks, I can now see the updated extension!!! Completely forgot about uwsgi...

I am a little bit confused about the DB though. Not sure where modoboa keeps its data...do you think it will work smoothly without a single record in the DB?

**Comment by sorcer1122** [comment]
Thanks, I can now see the updated extension!!! Completely forgot about uwsgi...Perhaps you should amend the manual - https://modoboa.readthedocs.io/en/latest/upgrade.html ...after phrase 'Finally, restart your web server' you can add something like 'and uwsgi'.

I am a little bit confused about the DB though. Not sure where modoboa keeps its data...do you think it will work smoothly without a single record in the DB?

**Comment by sorcer1122** [comment]
Not sure whether this is related but I am now unable to send mail via webmail. Gives me error 500 with the following in the console:

POST https://mydomain.com/webmail/?action=compose 500 ()
(anonymous) @ VM492:1
send @ jquery.min.js:5
ajax @ jquery.min.js:5
sendmail @ webmail.js:1044
i @ jquery.min.js:3
dispatch @ jquery.min.js:3
v.handle @ jquery.min.js:3

in /var/log/mail.log I can see:

connection established from...
lost connection after AUTH from...
disconnect...

:(

**Comment by tonioo** [comment]
You should not have to deal with that. Are you using a mysql cluster or similar?

**Comment by sorcer1122** [comment]
I am using MariaDB

**Comment by sorcer1122** [comment]
I am using MariaDB. It was a default installation and I don't think clustering is enabled

**Comment by sorcer1122** [comment]
Still cannot send any emails via webmail, error 500 all the time and nothing specific in logs.

**Comment by sorcer1122** [comment]
Resolved, many thanks for the interest!
