### ISSUE TITLE
LDAP using TLS not possible with current control panel settings

### ISSUE THREAD

**Issue by psycotic2017** [modoboa/modoboa#1259]
# Impacted versions

* Modoboa: 1.9.0
* installer used: No
* Webserver: Apache

# Current behavior
Even though the control panel suggests otherwise there is no option to use LDAP with TLS. Selecting 'Yes' on the 'Use a secured connection' setting only seems to create a LDAP URL for SSL (ldaps://) even if the port number is 389.

Selecting 'No' on the 'Use a secured connection' setting and putting 'AUTH_LDAP_START_TLS = True' in settings.py enables communication with LDAP over TLS

# Expected behavior
Selecting 'Yes' on the 'Use a secured connection' setting and leaving the port number at 389 suggests to me that TLS would be used

**Comment by tonioo** [comment]
@psycotic2017 And what happens if you change the port?

**Comment by psycotic2017** [comment]
@tonioo Changing the port number makes no difference, as far as I can tell.

Looking at the code in modoboa/core/app_settings.py (and I'm no python expert at all) at line 421:
`ldap_uri = "ldaps://" if values["ldap_secured"] else "ldap://"`

This piece of code seems to set the ldap uri independent of the port number.

Personally I think the ldap secured setting should have 3 values and not 2 as it has at present.
Rather than off or on it should be off, ssl or tls.
The ssl setting would set the `ldaps://` uri as it does already, the tls setting would keep the `ldap://` uri but set `AUTH_LDAP_START_TLS = True`
