### ISSUE TITLE
Modoboa Upgrade

### ISSUE THREAD

**Issue by WASDIT** [modoboa/modoboa#1266]
Hello,
i upgraded modoboa and all modules like here: 
http://modoboa.readthedocs.io/en/latest/upgrade.html#id1

But in the webinterface it means that is still the old version.
![image](https://user-images.githubusercontent.com/31078768/31318376-76a299b6-ac51-11e7-998f-7450658cfe54.png)

Whats wrong?

**Comment by tonioo** [comment]
Have you reloaded uwsgi?

**Comment by WASDIT** [comment]
yes also rebooted the server

**Comment by tonioo** [comment]
So this is a virtualenv issue. Have you loaded the virtualenv before upgrading?

**Comment by WASDIT** [comment]
How exaclty i installed modoboa with the root user and the installer

so what is the modoboa-user and what is the virtuenv_path?

Sorry but this is very new to me ;)

**Comment by WASDIT** [comment]
ok i found the solution, it only worked when i only use this command:
source <virtuenv_path>/bin/activate

**Comment by CooperBarrett** [comment]
Hi, 
I'm sorry to bother you, but I see you had the same problem as me.
Will you be able to tell me by what you replaced <virtuenv_path>? Where did you find the information?
Thank you in advance for your help

**Comment by WASDIT** [comment]
source /srv/modoboa/env/bin/activate

**Comment by CooperBarrett** [comment]
thank you very much
