### ISSUE TITLE
error when updating email info

### ISSUE THREAD

**Issue by oconshaw** [modoboa/modoboa#1267]
# Impacted versions

* Modoboa: 1.8.2
* installer used: Yes/No Yes
* Webserver: Nginx

# Steps to reproduce
As admin user, edit user.

# Current behavior
When clicking on "update", on the mail tab I see the following error message, "
Failed to retrieve mailbox location (sudo: no tty present and no askpass program specified )"

Other accounts i get the following message, "Email domain does not exist"

And still other accounts -- no issue at all. Seems to work fine.

**Comment by oconshaw** [comment]
In another thread, I saw the following "fix" for 1.8.1
https://github.com/modoboa/modoboa/issues/1090

Need to add the following -- 
Also needed to add to /etc/sudoers.d/modoboa:

uwsgi ALL=(vmail) NOPASSWD: /usr/bin/doveadm

I tried that and now I get the following error:

Failed to retrieve mailbox location (doveconf: Warning: NOTE: You can get a new clean config file with: doveconf -n > dovecot-new.conf doveconf: Warning: Obsolete setting in /etc/dovecot/dovecot.conf:22: 'imaps' protocol is no longer necessary, remove it doveconf: Warning: Obsolete setting in /etc/dovecot/dovecot.conf:22: 'pop3s' protocol is no longer necessary, remove it userdb lookup: user joblow@acme.com doesn't exist )

**Comment by oconshaw** [comment]
So I think I understand at least part of one of the issues --
When I run userdb lookup from the command line (which I believe is essentially what modoboa is doing) I am able to reproduce the error:
[root@mail sudoers.d]# doveadm user joeblow@acme.com
field   valueuserdb lookup: user joeblow@acme.com doesn't exist

When I run userdb for a domain that doesn't have the error I get:
[root@mail sudoers.d]# doveadm user sarablow@domain1.com
field   value
uid     1002
gid     1002
home    /srv/vmail/domain1.com/sarablow
mail    maildir:~/Maildir
quota_rule      *:bytes=0M

So the issue is that userdb is looking for that directory structure in /srv/vmail that matches the username and domain name.  In the case where I get the error that directory structure does not exist.

So the real issue, in this case, is why does modoboa (or dovecot) care at this point?  I am just configuring accounts and domains -- not ready to receive emails just yet.  I thought the domain structure gets automatically created when postfix/dovecot gets its first email destined for that domain.  Maybe not?  How should this get set?

**Comment by tonioo** [comment]
Looks like an issue with the userdb query... Have you disabled the faulty domain?

**Comment by oconshaw** [comment]
I wouldn’t call the domain “faulty” – it is not in use yet.  But, yes, in Modoboa I have the domain checked as disabled.  I tried it both ways – disabled and enabled.  Doesn’t work either way and same error messages.

 

It seems like the query is correct, but modoboa or dovecot seems to be expecting a condition that is not true  -- it seems like Modoboa and/or dovecot should accept configuration changes without requiring that the domain structure exist in the file system.  OR, maybe what should happen is when one creates a domain and/or account in Modoboa that the expected directories get written on update.  How is it supposed to work?

**Comment by tonioo** [comment]
Modoboa indeed uses doveadm to find mailbox homedir but it should not fail like this. Can you please the userdb query located in /etc/dovecot/dovecot-sql.conf and check the /var/log/mail.log file to see if there is more information?

**Comment by oconshaw** [comment]
I see a file in that directory called, “dovecot-sql.conf.ext”, but not “dovecot-sql.conf”.  I don’t see a userdb query per se, but I do see a postgres database query (maybe they are the same thing?) as follows:
#user_query = \

#  SELECT home, uid, gid \

#  FROM users WHERE username = '%n' AND domain = '%d'

user_query = SELECT '/srv/vmail/%d/%n' AS home, 1002 as uid, 1002 as gid, '*:bytes=' || mb.quota || 'M' AS quota_rule FROM admin_mailbox mb INNER JOIN admin_domain dom ON mb.domain_id=dom.id WHERE mb.address='%n' AND dom.name='%d'

 

is this what you are looking for?

**Comment by tonioo** [comment]
Yes it is. The domain/account account state is not checked so it should work... What is the difference between the domain which works and the one which doesn't?

**Comment by oconshaw** [comment]
The only difference that I am aware of is the ones that work are actually receiving emails and the ones that don’t work are just setup in Modoboa, but have never received any emails (and don’t have that directory structure present in /srv/vmail).  Why are you building up the path in the query?  It seems like you would be doing this for a reason – to check if it exists.  It doesn’t so modoboa or dovecot returns the error.  No?

 

Also, is this a query that gets sent to postgres?  It seems like in the where clause you are looking for any address that ends with an “n” and any name that ends in a “d”.  There must be some variable substitution going on I don’t understand.

 

user_query = SELECT '/srv/vmail/%d/%n' AS home, 1002 as uid, 1002 as gid, '*:bytes=' || mb.quota || 'M' AS quota_rule FROM admin_mailbox mb INNER JOIN admin_domain dom ON mb.domain_id=dom.id WHERE mb.address='%n' AND dom.name='%d'

 

Thanks for your help with this.

**Comment by tonioo** [comment]
@oconshaw Sorry for the delay. I still can't reproduce this issue, I thought it was similar to #1190 but it is not.
To answer your questions:
* %d and %n are special dovecot variables replaced by the domain and the local part of the address being checked
* The full path is required to be in the query because a userdb lookup maps username with a path in the filesystem for the delivery
Do you still encounter this issue?

**Comment by fyfe** [comment]
This is caused by the doveadm parameters being in the wrong order, see #1350
