### ISSUE TITLE
Question: Wrong Mail Date in Apple Mail Client

### ISSUE THREAD

**Issue by WASDIT** [modoboa/modoboa#1271]
Hey,
we changed by a customer to your software, then we migrate (copy) the Mails from the old to the new modoboa.

We have the Problem only in the Apple Mail Client it shows on some mails the wrong date, there is the date from the migration.

Everywhere in the Webmail, Server (creation and manipulation date) the Date is the right one.

Only on the Apple Mail Client it is the wrong date at some mails from the migration day.
We also removed the completly mail cache from the Macbook. And create the mail account new.
Still the same :(

Do you have a idea from where the Apple Mail Client get the wrong date?  Is there any other file on the Modoboa Mail server from where it got these date?

Thanks and BR

**Comment by tonioo** [comment]
Your mail client uses IMAP to retrieve emails and this part is managed by dovecot. Modoboa is not responsible for this. Have you tried with a different mail client?

**Comment by WASDIT** [comment]
Hey thanks for your reply, yes on every Client it worked only on the Apple Mail Clients we have this problem.

**Comment by tonioo** [comment]
So this is definitely a problem with this mail client... I don't have much experience with it so I can't help you, sorry.

**Comment by WASDIT** [comment]
Ok thanks ;)
