### ISSUE TITLE
Webmail authentication failed by LDAP user

### ISSUE THREAD

**Issue by yiminfantw** [modoboa/modoboa#1273]
# Impacted versions

* Modoboa: 1.9.0
* installer used: Yes
* Webserver: Nginx
* Ubuntu 16.04 (Xenial)

# Steps to reproduce
Fresh installation, following http://modoboa.readthedocs.io/en/latest/configuration.html to enable LDAP authentication, filling out LDAP settings and rebooting server, logging in by LDAP user and switching to webmail page.

# Current behavior
Getting "Error: ['[AUTHENTICATIONFAILED] Authentication failed.']" when switching to webmail page.

# Expected behavior
Normal webmail page as non-LDAP user has.

# More info
Through admin account I can see the LDAP user mailbox has been created in Identities page. The user role is "Simple user", quota is disabled by "Use domain default value" checkbox ticked. User name and email are [name]@[domain].

**Comment by tonioo** [comment]
Have you configured dovecot too? (https://wiki.dovecot.org/HowTo/DovecotOpenLdap)

**Comment by yiminfantw** [comment]
Hi @tonioo, I haven't configured dovecot yet, will get on that. Thx for pointing this out.

**Comment by yiminfantw** [comment]
Hi @tonioo,

I managed to configure dovecot-ldap.conf.ext and now the authentication seems passing through, but I got the following error:
`Error: ['[SERVERBUG] Internal error occurred. Refer to server log for more information. [2017-10-13 07:20:04] (0.000 + 0.000 secs).']`

By checking dovecot status, I got the following info(cuz I set debug_level = -1):
`
3 07:20:04 localhost dovecot[8929]: imap(ldapservice@yiminfan.tech): Error: net_connect_unix(/var/run/dovecot/dict) failed: Permission denied (euid=5006(<unknown>) egid=5006(<unknown>) ...0:0 mode=0755)
Oct 13 07:20:04 localhost dovecot[8929]: imap(ldapservice@yiminfan.tech): Error: Failed to autocreate mailbox Drafts: Permission denied
Oct 13 07:20:04 localhost dovecot[8929]: imap(ldapservice@yiminfan.tech): Error: Failed to autocreate mailbox Junk: Permission denied
Oct 13 07:20:04 localhost dovecot[8929]: imap(ldapservice@yiminfan.tech): Error: Failed to autocreate mailbox Trash: Permission denied
Oct 13 07:20:04 localhost dovecot[8929]: imap(ldapservice@yiminfan.tech): Error: Failed to autocreate mailbox Sent: Permission denied
Oct 13 07:20:04 localhost dovecot[8929]: imap(ldapservice@yiminfan.tech): Error: mkdir(/home/ldapservice/Maildir/cur) failed: Permission denied (euid=5006(<unknown>) egid=5006(<unknown>) mis...0:0 mode=0755)
Oct 13 07:20:04 localhost dovecot[8929]: imap(ldapservice@yiminfan.tech): Error: mkdir(/home/ldapservice/Maildir/cur) failed: Permission denied (euid=5006(<unknown>) egid=5006(<unknown>) mis...0:0 mode=0755)
`

Looks like it's permission issue on modoboa user side. Any suggestion?

Cheers,
YiMin

**Comment by ProCreator** [comment]
@tonioo,

I am having the same problem. So if I understand correctly what is being said is that the Modoboa ldap authentication only work for the Modoboa administration and now webmail? I am running my Modoboa config on Ubuntu and am having a real difficult time following the complexities of of the dovecot wiki for setting up the authentication even though I have successfully setup the Modoboa authentication. Is there any way you could assist by simplifying the implementation?

**Comment by yiminfantw** [comment]
Ya, the Modoboa ldap only works for Modoboa administration and has nothing to do with webmail (because dovecot takes different ldap config). 

Here is how I set it up, too me a while though:
- Editing /etc/dovecot/conf.d/10-auth.conf
```
#!include auth-sql.conf.ext
!include auth-ldap.conf.ext 
```

- Editing /etc/dovecot/dovecot-ldap.conf.ext
```
hosts = ldap.jumpcloud.com
dn = uid=samplebinduser,ou=Users,o=sampleorganizationid,dc=jumpcloud,dc=com
dnpass = samplebinduser
tls = yes
debug_level = -1
auth_bind = yes
ldap_version = 3
base = o=sampleorganizationid,dc=jumpcloud,dc=com
deref = never
scope = subtree
user_attrs = homeDirectory=home,uidNumber=uid,gidNumber=gid
user_filter = (&(objectClass=posixAccount)(uid=%n))
pass_attrs = mail=user,userPassword=password
pass_filter = (&(objectClass=posixAccount)(uid=%n))
default_pass_scheme = BLF-CRYPT
```

Btw, I just figured that the internal error is due the fact that I commented `!include auth-sql.conf.ext` in 10-auth.conf. After uncommenting it, my ldap user can open webmail page and send/receive emails. I thought sql and ldap are different authentication mechanism and shouldn't affect each other. Do you have any idea why commenting `!include auth-sql.conf.ext` makes IMAP try to create user folder in /home?

Anyway, it's all working now. Thx for your help. :)

**Comment by tonioo** [comment]
I think your LDAP config file does not declare any userdb lookup. So, if you deactivate the sql default one, there is no userdb at all. In this case, and because the authentication works, dovecot tries to initiate a mailbox in the user home directory (default behaviour).

**Comment by tonioo** [comment]
And regarding your errors, I don't know. I think you should ask on dovecot mailing list, you'll certainly have a better answer there.
