### ISSUE TITLE
internal server error for new admin users

### ISSUE THREAD

**Issue by hadifarnoud** [modoboa/modoboa#1275]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
I'm not 100 sure but: create new users on 1.9.0 and try to login or go to /webmail after login. it gives 500 error for login and sometimes give 500 error for webmail too.

# Current behavior
new admin users can't login

# Expected behavior
should be able to login

# Video/Screenshot link (optional)
https://sentry.io/kamva-c0/kamva-mail/issues/350444456/

I was usually able to get around 500 errors by rebooting the server. it doesn't work anymore. I updated to latest version and the issue is still there.

the issue seems to happen for new admin users (domain admins) only. old admin users can login just fine. this error is present on /webmail as well. not sure how to reproduce that one

**Comment by tonioo** [comment]
@hadifarnoud Looking at you sentry trace, the issue is due to a problem with the amavis quarantine plugin. There is some strange content into the quarantine, I think that's the same issue than the one described here: https://github.com/modoboa/modoboa-amavis/issues/35

**Comment by hadifarnoud** [comment]
is there any temp fix? if not, would a patch be long to make/test?

**Comment by tonioo** [comment]
There is no temp fix right now (unless you empty your quarantine). A fix should not be too long to realize but I don't have enough time at the moment...

**Comment by hadifarnoud** [comment]
I empty quarantine but problem still exist. I thought you should know this. issue may be somewhere else too?

**Comment by tonioo** [comment]
That's a complicated one to fix... @hadifarnoud Could you try the fix proposed in the ticket I mentionned? ie. replace all occurences of UTF8 to LATIN1 in the sql_connector.py file?

**Comment by hadifarnoud** [comment]
safe to try? we have so many accounts on this server

**Comment by tonioo** [comment]
I think it can't be worse than UTF8... What you can do is try the modification, see if it fixes the issue and rollback to the old code if it doesn't. What do you think?

**Comment by hadifarnoud** [comment]
here is what I did:

I logged in as modoboa user and edited this file: `./env/lib/python2.7/site-packages/modoboa_amavis/sql_connector.py`

I replaced all `UTF8` with `LATIN1` and saved the file. I didn't restart the server or anything else.

It didn't fix the issue. if I missed anything, please let me know

**Comment by hadifarnoud** [comment]
I just noticed I can't empty quarantine. messages come back!

**Comment by tonioo** [comment]
@hadifarnoud you must reload uwsgi

**Comment by hadifarnoud** [comment]
issue is fixed :)

**Comment by tonioo** [comment]
So it is working better using LATIN1 ?

**Comment by hadifarnoud** [comment]
yeah, users can login. I report back if I see any 500 error
