### ISSUE TITLE
Feature Request: one LDAP connection per domain

### ISSUE THREAD

**Issue by jpellissari** [modoboa/modoboa#1278]
Hello all,

The company I work for would like to use modoboa as our unique email server. We manage multiple email servers and we're really looking forward to migrate to modoboa. This would allow us to manage only one email server with multiple domains. The only thing that we need to make this migration is the ability to authenticate in one LDAP per domain. I saw [this post on google groups](https://groups.google.com/forum/#!topic/modoboa-users/r1pArdwbNps) of 2011 and that's what we need! Do you think that's possible? Maybe we could help implementing this feature!

**Comment by tonioo** [comment]
@jpellissari To make sure I understand you well, you'd like to have a per-domain LDAP configuration in addition to the global one? For example: domain A would use LDAP directory X and domain B would use LDAP directory Y, right?

**Comment by jpellissari** [comment]
Yes! Exactly!!!

**Comment by hadifarnoud** [comment]
that would be nice but I think you need to sponsor this feature. not many need it

**Comment by tonioo** [comment]
@jpellissari Indeed this is an interesting feature but really adapted to a professional context. Do you think your company could sponsor (even partially) this feature?

**Comment by tonioo** [comment]
@jpellissari ping

**Comment by hadifarnoud** [comment]
I don't think this bug is useful.
