### ISSUE TITLE
Howto reinstall modoboa completely without data lose?

### ISSUE THREAD

**Issue by Hackbard** [modoboa/modoboa#1279]
Hi,
the heading contains the question ;)

Best Regard

**Comment by tonioo** [comment]
Do you want to upgrade to a new version a to run the installer one more time on an existing server?

**Comment by Hackbard** [comment]
yes that would be great.

**Comment by tonioo** [comment]
Important data are emails (stored by default in /srv/vmail) and the database. Backup them before doing anything else.
