### ISSUE TITLE
Catch all alias not working

### ISSUE THREAD

**Issue by telskamp** [modoboa/modoboa#1288]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes?
* Webserver: Nginx
*linux: Ubuntu 16.04 updated

# Steps to reproduce
create  a *.domain.tld alias pointing to blabla@domain.tld

# Current behavior
Recipient address rejected: undeliverable address: host xx.xxxxx.xx[private/dovecot-lmtp] said: 550 5.1.1 <test@domain.tld> User doesn't exist
# Expected behavior
email delivered to blabla@domain.tld

I did try to recreate the catch-al and I tried pointing it to another inbox.
I also tried removing /var/lib/postfix/verify_cache.db and restarting postfix, but it did not make a difference.

**Comment by tonioo** [comment]
@telskamp What syntax did you use?

**Comment by telskamp** [comment]
I am not sure what you mean by syntax in this matter,

**Comment by tonioo** [comment]
@telskamp How did you create your alias? What value did you use? Can you take a screenshot?

**Comment by telskamp** [comment]
![image](https://user-images.githubusercontent.com/25670464/32288905-9fa4ab14-bf35-11e7-8652-c79c1cb86137.png)

**Comment by telskamp** [comment]
![image](https://user-images.githubusercontent.com/25670464/32289435-009b0192-bf37-11e7-83ac-6ea72f3c20da.png)

**Comment by tonioo** [comment]
Remove the '*' and it will work.

**Comment by telskamp** [comment]
@tonioo  thank you,  obviously user error from my side
