### ISSUE TITLE
1.9.1 a lot of unresponsive features

### ISSUE THREAD

**Issue by rami-dabain** [modoboa/modoboa#1291]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes ?
* Webserver: Nginx

# Steps to reproduce
git clone, 
./run.py [domain[

# Current behavior
1- after login, go to profile, try change password.. doesn't work
2- adding domains with domain admins not working (one worked. other didn't ... domain is dash-poker.com)
3- adding simple users for the new domain doesn't work
the ajax requests for those feature return HTTP err 500

# Expected behavior
- password changed
- domain added
- user added

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@rami-dabain Could you give more detail please? Try to set DEBUG to True inside settings.py, reload uwsgi, and open your browser debugger to check the response please.

**Comment by tonioo** [comment]
@rami-dabain ping
