### ISSUE TITLE
Disable the call to api.modoboa.org

### ISSUE THREAD

**Issue by rmontagud** [modoboa/modoboa#1292]
# Impacted versions

* Modoboa: 1.5.3
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
api.modoboa.org is down (just like anything connected to OVH, including my personal box)

# Current behavior
Modoboa admin times out and nginx gives a 504 error

# Expected behavior
Either disable new version notifications or skip version check for X minutes if api.modoboa.org doesn't respond

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@rmontagud This behaviour has been fixed with newer versions. Could you try to update?

**Comment by rmontagud** [comment]
That's up to the server owner but will try, thanks
