### ISSUE TITLE
Webmail contents not showing when using NGINX as Reverse Proxy

### ISSUE THREAD

**Issue by jasonaleski** [modoboa/modoboa#1296]
This really isn't an issue (anymore), but thought I'd share a solution to a problem I have been having.  Modoboa was installed with the installer, but NGINX was reconfigured to be used as a Reverse Proxy; mainly for SSL offloading.  I've had this issue with prior version of Modoboa installer, but never took the time to truly troubleshoot it...until now.  For the most part, Modoboa back-end would work, except when displaying email content.  It would display the headers, but not the actual content.  The fix, at least for me, is below.

# Impacted versions
* Modoboa: 1.9.1
* installer used: Yes/No ?
* Webserver: Nginx

# Steps to reproduce/Current Problem
Webmail content unable to display while running behind Nginx (acting as a Reverse Proxy).

# Expected behavior
Show email contents via webmail.

# Proposed solutions that did not work:
In the /srv/modoboa/instance/instance/settings.py, the following X_FRAME_OPTIONS did NOT work (different instances of the configuration):
```
X_FRAME_OPTIONS = "SAMEORIGIN"
X_FRAME_OPTIONS = "DENY"
```

# Solution that worked
In the /srv/modoboa/instance/instance/settings.py, set the following:
`X_FRAME_OPTIONS = "ALLOW-FROM https://mailserver.yourdomain.com"`

I originally thought the configuration error was in Nginx, but then realized that the UWSGI server was confused due to the nature of the Reverse Proxy request.

Hopefully this will help someone in the future.

**Comment by jasonaleski** [comment]
Just passing information to be documented.

**Comment by guillim** [comment]
Had the same issue. your trick solved it. tks

**Comment by alexander255** [comment]
Thank you, this helped me figure out why viewing messages did not work on my instance.
