### ISSUE TITLE
Remote SQL authentication

### ISSUE THREAD

**Issue by arduino43** [modoboa/modoboa#1297]
# Impacted versions

* Modoboa: Latest
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Run installer with 'installer.cfg' the following options set:

engine = mysql
host = 1.1.1.1

# Current behavior

When using a remote SQL server Modoboa fails. Some tables are not created for each database - spamassassin, amavis and modoboa. It appears that at some point during the installation script modoboa sets the SQL account to use 'modoboa@localhost', causing the remote SQL server to reject authentication attempts.

Does Modoboa support remote SQL server authentication?

**Comment by kryskool** [comment]
ping @arduino43

**Comment by arduino43** [comment]
The installer may be creating the account, but is Modoboa using that account? I haven't checked in quite some time, but I vaguely remember that it did create the account, it just didn't use it after installation.

**Comment by tonioo** [comment]
Yes it is. And tables were missing in every database? That's very strange because I don't see why some tables would created... If it's an authentication issue, nothing should be created.
