### ISSUE TITLE
Multi-domain / single user quarantine

### ISSUE THREAD

**Issue by arduino43** [modoboa/modoboa#1298]
# Impacted versions

* Modoboa: X.X.x
* installer used: Yes
* Webserver: Nginx

Currently hosting 3 mail domains where a user has an account for each domain e.g user1@domain1.com, user1@domain2.com, user1@domain3.com.

Modoboa is a gateway to Microsoft Exchange, where each user account mailbox is stored. When logging into the web interface (LDAP auth to active directory) I am unable to view quarantine mail for anything but non-primary email account. If I login as user1@domain1.com I cannot see quarantine mail for user1@domain2.com. 

Ldap is setup to use the filter:
(objectclass=person)(proxyAddresses=smtp:%s)

Does modoboa support multi-domain quarantines for single use logins?

**Comment by tonioo** [comment]
@arduino43 Have you tried with aliases instead? eg. define one primary account and aliases for the other ones.

**Comment by tonioo** [comment]
@arduino43 ping

**Comment by arduino43** [comment]
Perfect, that worked!

Sorry for the late response, I havent had time to test this until now.
