### ISSUE TITLE
Document what DNS records need to be set up

### ISSUE THREAD

**Issue by cweagans** [modoboa/modoboa#1299]
This might just be something that the installer needs to output at the end or something, but some direction for how to configure my DNS would be awesome.

**Comment by fasihrana** [comment]
I installed modoboa last night and I was also confused by this. The only thing that works right now is outgoing email but i'm unable to receive any emails.

**Comment by tonioo** [comment]
See https://github.com/modoboa/modoboa-installer/issues/168.

**Comment by cweagans** [comment]
Yeah, I saw that. That doesn't really help for even a relatively technical person that knows next to nothing about how to host email. Note that even in that issue, you said:

> I guess a piece of documentation could be added at the end of the process... What do you think?

I think that the documentation for how to set things up belongs in the documentation.

**Comment by tonioo** [comment]
The message I added is just a reminder about minimum DNS requirements. I agree the documentation could cover a more complete DNS setup but that's also something the community could do with a contribution.
