### ISSUE TITLE
Migrate 

### ISSUE THREAD

**Issue by ndecaris** [modoboa/modoboa#1300]
# Impacted versions

* Modoboa: 1.7.4
* installer used: Yes/No ? i think yes
* Webserver: Nginx

# Steps to reproduce
upgrade process describe in the official documentation

# Current behavior
error when use the command : "python manage.py migrate" => ImportError: No module named modoboa_amavis

# Expected behavior
go further .....

thank a lot for your help
Nicolas

**Comment by tonioo** [comment]
@ndecaris Did you install Modoboa using the installer (https://github.com/modoboa/modoboa-installer) or following the documentation? (http://modoboa.readthedocs.io/en/latest/installation.html#manual-installation)

**Comment by ndecaris** [comment]
@tonioo i used the installer ...

**Comment by tonioo** [comment]
@ndecaris when did you run this install? Modoboa 1.7.4 is pretty old. Could you try with the latest version of the installer?

**Comment by ndecaris** [comment]
@tonioo you mean update the installer ? how can i do it : i will see in the doc !

**Comment by tonioo** [comment]
```bash
> cd modoboa-installer
> git pull origin master
```

**Comment by ndecaris** [comment]
@tonioo idem : 
> ImportError: No module named modoboa_amavis

**Comment by tonioo** [comment]
@ndecaris Can you restart from scratch?

**Comment by ndecaris** [comment]
you mean reinstall everything ? heu, how does it work for postfix dovecot, ... configuration : the installation keep the configuration files ?

**Comment by tonioo** [comment]
@ndecaris did you modify the config manually?

**Comment by ndecaris** [comment]
@tonioo yes i did. and i think many people does : listen on another port for webadmin (nginx config), disable a dns postscreen service, modify postscreen_access.cidr, use letsencrypt certificate, add POP3s for dovecot, ... !
Do you mean : i have to restart from scratch, even for services ?
how can i backup everything  : even messages in mailbox ?

**Comment by ndecaris** [comment]
@tonioo i try to backup configurations, but i can't connect to postgresql : where are the credentials ?
thanks

**Comment by tonioo** [comment]
The credentials are stored in the settings.py file.

**Comment by tonioo** [comment]
@ndecaris any news?

**Comment by ndecaris** [comment]
@tonioo backup is ok now. but i can't use a new version of the installer : i don't want to crash my production service. is there a way to check what is done by the installer : i mean just to understand how files are written or not if configuration exists ?

**Comment by tonioo** [comment]
@ndecaris There is easy way for that. Either look at the code or run the installer on a VM with the --debug option

**Comment by tonioo** [comment]
@ndecaris Can I close this issue?
