### ISSUE TITLE
Generic transport feature

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa#1301]
Allow administrators to declare transport entries for domains. Instead of the current 'relay domains' functionality, allow a per-domain transport definition. Depending on the selected transport (ie. the master.cf service entry), a custom form will be displayed to specify the required parameters.

**Comment by fbartels** [comment]
Hi @tonioo ,

since this feels related I wanted to add something to this ticket. One thing I'm currently missing in modoboa is the possibility to define a per user transport. Say for example just one of the user of a specific domain is located on a different server.

**Comment by tonioo** [comment]
@fbartels That's something I'll certainly add after. Actually, I might propose it through the crowd funding system soon.
