### ISSUE TITLE
Sender addresses not working

### ISSUE THREAD

**Issue by lmfrazao** [modoboa/modoboa#1302]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes ?
* Webserver: Nginx / centos 7 

# Steps to reproduce

# Current behavior
When a user has sender addresses configured are they supposed to work only on modoboa webmail ?

# Expected behavior

Is there a way to configure this as sender-login-maps ? I had to put the old file to be able to use send connectors on microsoft exchange.

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@lmfrazao yes, if you send your emails through the submission port (587)
Are you using it?

**Comment by lmfrazao** [comment]
I am using por 587, yes, it's only working if I use sender_login_maps on postfix.
Somehow it's not reading the list of users that should be sending email with that address.
For example, I have an exchange server using account user@domain.com as send connector for user1@domain.com, user2@domain.com, all of them are modoboa's existing users. When I add the users on sender address for user@domain.com it's always 5.7.1 errors (not owned by), if the user doesn't exists, for example usernonexistand@domain.com it works as intended.

**Comment by lmfrazao** [comment]
through the installer

**Comment by tonioo** [comment]
Have you checked #1164 ?

**Comment by lmfrazao** [comment]
Will try, I guess it might be the postfix 2 on centos...

Will give feedback later

Thanx!

On Nov 23, 2017 19:41, Antoine Nguyen <notifications@github.com> wrote:

Have you checked #1164<https://github.com/modoboa/modoboa/issues/1164> ?

**Comment by lmfrazao** [comment]
working fine with postfix 3

Thank you!
