### ISSUE TITLE
Amamis issue, clamd.ctl: Connection refused

### ISSUE THREAD

**Issue by blackyzero** [modoboa/modoboa#1308]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Mail unable to deliver

# Current behavior
Nov 22 16:09:14 siren amavis[21023]: (21023-10) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl: Connection refused
# Expected behavior

# Video/Screenshot link (optional)

I have to restart /etc/init.d/clamav-daemon to make it works back.
Please advise how to fix this issue.

Thank you.

**Comment by tonioo** [comment]
I clamav stops randomly, it might mean you don't have enough RAM on your server. How much to you have?

**Comment by tonioo** [comment]
@blackyzero ping
