### ISSUE TITLE
Error 500 Import CSV

### ISSUE THREAD

**Issue by carbans** [modoboa/modoboa#1312]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes/No ?
Yes
* Webserver: Nginx/Apache
Nginx

# Steps to reproduce
Identities / Import

# Current behavior
I can't import csv with users, Javascript browser console throws 500 Error(see Screenshot) when it's try to access to https://server.com/admin/identities/import/

# Video/Screenshot link (optional)
https://imgur.com/a/CnU7g

**Comment by tonioo** [comment]
Could you retry with DEBUG set to True inside settings.py? Otherwise you can also test the command line version (http://modoboa.readthedocs.io/en/latest/moving.html#using-csv-files)

**Comment by tonioo** [comment]
@carbans ping

**Comment by carbans** [comment]
Sorry for the delay, I tried with the settings Debug to True, but this has not worked, I was doing tests and detected that the error is because I enter names with accents or special characters such as º, ª

I think that you process the file before uploading it, Is it done using javascript?

It would be great if we could add accents and special characters

**Comment by tonioo** [comment]
In which column(s) did you put special characters?

**Comment by fyfe** [comment]
@carbans  Are you using Python 2.7?

https://github.com/modoboa/modoboa/blob/168743f74b4107f055844e2979025a4d03faa198/modoboa/admin/views/import_.py#L43-L52

I haven't tested it yet but I think this should be:
```python
infile = codecs.open(request.FILES["sourcefile"].file, mode="r", encoding="utf8")
reader = reader = csv.reader(
                infile,
                delimiter=smart_str(form.cleaned_data["sepchar"])
            )
```

**Comment by fyfe** [comment]
Found a simpler solution, use the back ported csv module it supports Python 3.

See #1342
