### ISSUE TITLE
Domain does not exist

### ISSUE THREAD

**Issue by Chris87871** [modoboa/modoboa#1313]
When I add a new user I get Domain does not exist yet I created a domain.
![image](https://user-images.githubusercontent.com/34148567/33465934-eced3326-d607-11e7-9155-1cc2b5942e27.png)
Also what does my dns server records  need to be set for a new domain to receive emails. There is no clear documentation whats so ever.

**Comment by Chris87871** [comment]
Ok I reinstalled modoboa and created user accounts and auto created an admin account for the  domain now it seems to work,but I login as a user and mail wont send. Hit send it pauses then clears the from and to fields and nothing.

**Comment by Chris87871** [comment]
Ok reinstalled the same way for a third time. Emails work. What is going on? I am running ubuntu 16.04 and used the installer. Also I was wondering how to send email voicemail attachments from free pbx to an email account in modoba? Free pbx is configured relayhost ip of modoba server and user accounts list with names and passwords. Is that enough? They are all in an internal network.

**Comment by tonioo** [comment]
If your servers share the same network then you just need to adjust the internal_networks postfix setting and you're done.
And I don't know why you encountered this behavior with the installer, maybe a network issue or something. Anyway, your server is installed, that's the most important.
