### ISSUE TITLE
Cannot save parameters at all

### ISSUE THREAD

**Issue by herrbischoff** [modoboa/modoboa#1316]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

Trying to save parameters.

# Current behavior

Does not save parameters.

# Expected behavior

Saves parameters.

# Video/Screenshot link (optional)

![screen shot 2017-12-05 at 17 34 59](https://user-images.githubusercontent.com/8957346/33618401-bfd809fe-d9e2-11e7-8a8b-d048c3ec2f9b.png)

This is a brand new installation. Of note is that there isn't even a request being made to `https://mail.domain.com/core/parameters/` which should happen.

**Comment by pruje** [comment]
Hi @herrbischoff 
I'm not part of the modoboa team, but I had the same issue.
The problem is that you have to set the field "Default password" that is not "password", but a complex password with 8 characters minimum, at least one digit and one uppercase character.

BTW, @tonioo it would be nice to have explanation messages when failing to submit that form.
Thanks and keep the good work!

**Comment by herrbischoff** [comment]
@pruje: The password is set to something else than the default (which initially appeared to work) and there is no notice about it whatsoever:

![modoboa](https://user-images.githubusercontent.com/8957346/33665924-af2c8916-da98-11e7-87d5-c06d222ba5d0.png)

**Comment by herrbischoff** [comment]
In the developer tools I can see a JavaScript event attached to the form to send an Ajax request but somehow this is never fired. I have another install on a different server that works without a hitch. If there's no obvious solution to this, I'm just going to wipe the server and reinstall everything as it's not in active use for now.

**Comment by tonioo** [comment]
@herrbischoff Can you try again after a full refresh the page (ctrl+F5) and also check all tabs to see if you haven't forgotten something.

**Comment by herrbischoff** [comment]
@tonioo: I tried both several times and finally just gave up and ran the Modoboa installer again. Afterwards all data was still there and it worked.

Coming to think about it, the difference is that there is now no Radicale plugin. It may have had something to do with this.

**Comment by tonioo** [comment]
@herrbischoff Yes, I think it is related to the radicale plugin which has an empty setting by default.

Rewriting the user interface using vue.js is something I plan to do (I already did the contacts plugin like this and I'm working on a new radicale plugin) but, as you said, it is a longer-term project. Anyway, I'd **really** need help about this. Would you be ready to work on this with me?

**Comment by herrbischoff** [comment]
@tonioo: Sure, I'm up for it. I recently finished several Vue.js-based client projects so I'm quite up-to-speed working with the framework. From what I've seen, Modoboa does all of its interaction with the API though REST calls. This should make it manageable to transition to Vue. I can involve myself for some time every week but obviously I cannot guarantee availability with needing to earn money and that. That being said, I really like Modoboa's approach and will gladly help out to make it even better.

Maybe somewhere along the way we can tackle a FreeBSD installer as well. ;)

**Comment by tonioo** [comment]
@herrbischoff I understand the need for money, I've got the same problem ;-) (who doesn't?)

As you mentioned it, Modoboa provides a REST api which could be used as a starting point but it needs some improvements. I'd also like to update the way menu items are organized.

How could we start this?

**Comment by herrbischoff** [comment]
I'm closing this as the original issue is resolved. It was apparently caused by an unconfigured Radicale plugin.
