### ISSUE TITLE
Uninstallation Instructions in Documentation

### ISSUE THREAD

**Issue by ziyaddin** [modoboa/modoboa#1317]
Hello, it would be great if we have "uninstallation instructions" page in documentation. I want to uninstall modoboa completely from the machine but due to different installed components in separate directories I do not know how to do that.

**Comment by tonioo** [comment]
@ziyaddin I suggest you take a look at the "Manual setup" section available in the documentation, you'll know what components are installed.

**Comment by ziyaddin** [comment]
Thanks @tonioo
