### ISSUE TITLE
Admin panel access after default installation

### ISSUE THREAD

**Issue by ziyaddin** [modoboa/modoboa#1321]
How can I access modoboa admin panel right after the installation?

**Comment by tonioo** [comment]
The installer displays a message at the end of the process. Did you see it?

**Comment by ziyaddin** [comment]
The message is:
`Congratulations! You can enjoy Modoboa at https://mail.localhost (admin:password)`

The problem is I do not have any admin panel on this page:

![image](https://user-images.githubusercontent.com/1016523/33793606-7d38b26c-dcd3-11e7-9335-14192baddf27.png)

**Comment by ziyaddin** [comment]
The issue is solved! I used the wrong URL (`mail.localhost` instead of `https://mail.localhost`).

Thank you!
