### ISSUE TITLE
CommandError: Failed to retrieve versions from the API. 

### ISSUE THREAD

**Issue by danielsatanik** [modoboa/modoboa#1343]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes
* Webserver: Nginx

# Current behavior
I know there are some already resolved issues regarding this, but unfortunately they didn't help so the reason why it happens must be something else.

I get an email hourly because inside the `/etc/cron.d/modoboa` file there is the following line

```
# Public API communication
0       *       *       *       *       root    $PYTHON $INSTANCE/manage.py communicate_with_public_api
```

but unfortunately for some reason cron cannot execute this line. I get the following error message every hour sent as an email.

```
CommandError: Failed to retrieve versions from the API. 
```

I tried executing this line manually and it didn't throw any error or exception.

**Comment by tonioo** [comment]
@danielsatanik It was a SSL certificate issue on the API, sorry for that.

**Comment by danielsatanik** [comment]
happens again

**Comment by WLR86** [comment]
Yup - same here

**Comment by tonioo** [comment]
Fixed, once again... Certificate issue, nginx is not reloaded after the update.

**Comment by danielsatanik** [comment]
@tonioo I actually don't really care if this happens apart from the fact that my mail inbox gets flooded with the same email every hour…is it possible to turn off the email notifications?

and is this an issue that will come back every now and then?
