### ISSUE TITLE
Cron issue - Refer to closed #983

### ISSUE THREAD

**Issue by hrx777** [modoboa/modoboa#1345]
See https://github.com/modoboa/modoboa/issues/983

**Comment by tonioo** [comment]
That's really strange... Can you check that your file ends with a newline? What happens if you reintroduce variables?

**Comment by kryskool** [comment]
ping @hrx777

**Comment by makakken** [comment]
i think the problem still exists:
```
Jul 10 22:23:01 mail cron[893]: (*system*letsencrypt) ERROR (Missing newline before EOF, this crontab file will be ignored)
Jul 10 22:25:01 mail cron[893]: Error: bad username; while reading /etc/cron.d/modoboa
Jul 10 22:25:01 mail cron[893]: (*system*modoboa) ERROR (Syntax error, this crontab file will be ignored)
```

fresh install using the installer on debian 9.4
is there any solution for that?

**Comment by tonioo** [comment]
@makakken Thank you for the logs. There is indeed a missing newline in the letsencrypt crontab, I'll fix it. About the modoboa crontab, can you paste the content somewhere? The "bad username" error is explicit but I'd like to know which one...

**Comment by makakken** [comment]
@tonioo sorry, deleted the test cloud-node ;) currently try to install on ubuntu 18.04. node. if the error still persists, i'll post the content of /etc/cron.d/modoboa

**Comment by makakken** [comment]
```
Jul 11 11:06:01 mail cron[1021]: Error: bad username; while reading /etc/cron.d/modoboa
Jul 11 11:06:01 mail cron[1021]: (*system*modoboa) ERROR (Syntax error, this crontab file will be ignored)
```

how nice, error still exists with ubuntu 18.04 fresh install on cloud-node.
content of cron.d/modoboa

```
# This file was automatically installed on 2018-07-11T11:05:13.976819
#
# Modoboa specific cron jobs
#
PYTHON=/srv/modoboa/env/bin/python
INSTANCE=/srv/modoboa/instance

# Operations on mailboxes
*       *       *       *       *       vmail   $PYTHON $INSTANCE/manage.py handle_mailbox_operations

# Sessions table cleanup
0       0       *       *       *       root    $PYTHON $INSTANCE/manage.py clearsessions

# Logs table cleanup
0       0       *       *       *       root    $PYTHON $INSTANCE/manage.py cleanlogs

# Quarantine cleanup
0       0       *       *       *       root    $PYTHON $INSTANCE/manage.py qcleanup

# Notifications about pending release requests
0       12      *       *       *       root    $PYTHON $INSTANCE/manage.py amnotify

# Logs parsing
*/5     *       *       *       *       root    $PYTHON $INSTANCE/manage.py logparser &> /dev/null
0       *       *       *       *       root    $PYTHON $INSTANCE/manage.py update_statistics

# Radicale rights file
*/2    *       *       *       *        root    $PYTHON $INSTANCE/manage.py generate_rights

# DNSBL checks
*/30    *       *       *       *       root    $PYTHON $INSTANCE/manage.py modo check_mx

# Public API communication
0       *       *       *       *       root    $PYTHON $INSTANCE/manage.py communicate_with_public_api

# Generate DKIM keys (they will belong to the user running this job)
*       *       *       *       *       opendkim    $PYTHON $INSTANCE/manage.py modo manage_dkim_keys
```

**Comment by makakken** [comment]
i checked all the usernames, they exist in the passwd file: root, vmail, opendkim

**Comment by makakken** [comment]
@tonioo i cannot see any errors, do you?

**Comment by makakken** [comment]
@tonioo no strange characters i think

**Comment by tonioo** [comment]
No indeed... And reloading the daemon? I wonder if there could be an issue if opendkim and vmail users are added after the cron daemon has been started...

**Comment by makakken** [comment]
i think you're right, after restarting the daemon, no errors:

`Jul 11 11:31:33 mail cron[6264]: (CRON) INFO (pidfile fd = 3)
Jul 11 11:31:33 mail cron[6264]: (CRON) INFO (Skipping @reboot jobs -- not system startup)`

**Comment by tonioo** [comment]
Great! I'll fix it in the installer.

**Comment by makakken** [comment]
all processes seem to work now.

**Comment by tonioo** [comment]
Fixed by https://github.com/modoboa/modoboa-installer/commit/9eed99d88430918e0ff5c336b36655c5297c4e47 and https://github.com/modoboa/modoboa-installer/commit/d845ce78d0d4849234e2929d23f91fa47da0f003.
