### ISSUE TITLE
modoboa 1.9.1 SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by khalidzouagui** [modoboa/modoboa#1346]
Hi,

I have installed modoboa 1.9.1, but when i try to add a new account i coud not and in the console i receive this error :
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data : jquery.min.js:3:4315

Thank you for your time and your help.

# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes/No ?
* Webserver: Apache

# Steps to reproduce

# Current behavior
error :
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data : jquery.min.js:3:4315

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
Enable debug mode (set DEBUG to True inside settings.py and reload uwsgi) and check the response content with your JS debugger, you should have more information.

**Comment by khalidzouagui** [comment]
Thanks for your response.
I set DEBUG = True in settings.py and i when i want to reload uwsgi with :(env) $ service uwsgi reload
i get : uwsgi.service is not active, cannot reload.

**Comment by tonioo** [comment]
How did you install modoboa?

**Comment by khalidzouagui** [comment]
With the manual installation: 
    Modoboa
    Apache as web server
    Dovecot
    Postfix

**Comment by tonioo** [comment]
Ok so reload apache.

**Comment by khalidzouagui** [comment]
I reloaded apache, when i hit submit to add a new account i could not and in the console i receive this error :
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data : jquery.min.js:3:4315

**Comment by tonioo** [comment]
You're not looking at the right tab. Inspect the response content. And also make sure you settings are correct (PDF files storage directory for example, see Modoboa > Parameters > PDF)

**Comment by khalidzouagui** [comment]
i have an issue about PDF but i resolved it, Please how do i inspect the response content?

**Comment by tonioo** [comment]
Look at the network tab for example and search the failing request.

**Comment by khalidzouagui** [comment]
It was about PDF authorization, i resolved it by : # chmod ugo+rwx -R /var/lib/modoboa/pdf_credentials/
but i have other problems when i want to access Contacts and Webmail. but i think it is another issue.
Thank you Mr Antoine.
