### ISSUE TITLE
Trace login attempts / brute-force protection

### ISSUE THREAD

**Issue by pruje** [modoboa/modoboa#1359]
Is there any way to see the login attempts (to access the web interface) in logs?
It would be nice to have it at least for monitoring and most preferably to configure a brute-force protection system.

Thanks!

# Impacted versions
* Modoboa: 1.9.1
* installer used: Yes
* Webserver: Nginx

**Comment by tonioo** [comment]
@pruje Modoboa already logs login attempts (https://github.com/modoboa/modoboa/blob/master/modoboa/core/views/auth.py#L54) so you can use something like fail2ban.

**Comment by pruje** [comment]
Thanks @tonioo, but where can I found this log? I didn't found such line in `/var/log/uwsgi/app/modoboa_instance.log` neither in syslog

**Comment by pruje** [comment]
Sorry @tonioo, but the file `auth.log` exists and is working (entries are added when an user log in), but there is no modoboa entries in it.

I'm using Ubuntu 16.04 with syslog-ng 3.5.6

**Comment by fyfe** [comment]
According to [python documentation](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.SysLogHandler) it sends syslog messages to localhost:514

In `settings.py` find LOGGING and add `'address': '/dev/log',` to the syslog-auth handler:
```python
        'syslog-auth': {
            'class': 'logging.handlers.SysLogHandler',
            'facility': SysLogHandler.LOG_AUTH,
            'address': '/dev/log',
            'formatter': 'syslog'
        },
```

The documentation needs updated to highlight that this may need configured depending on the servers configuration.

**Comment by pruje** [comment]
@fyfe Thank you! It works!
@tonioo, I can make a PR to update documentation, if you want. I was thinking to put that in the Configuration page. Tell me if OK for you.

**Comment by tonioo** [comment]
@pruje Yes, that's a good idea. Thank you.
