### ISSUE TITLE
Attachment disappear by forwarding an e-mail

### ISSUE THREAD

**Issue by whiteSpaceX** [modoboa/modoboa#1362]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes
* Webserver: Nginx/Apache

Forwarding the e-mail to another e-mail address should automatically include the attachment in the forwarded e-mail. In Modoboa the attachment disappear by forwarding an e-mail?

**Comment by tonioo** [comment]
Duplicate of https://github.com/modoboa/modoboa-webmail/issues/110.
