### ISSUE TITLE
Change default   Mail.domain.com

### ISSUE THREAD

**Issue by nizammufid** [modoboa/modoboa#1365]
is there any chance that i can change the mail.domain.com to another subdomain like mx01.domain.com??

**Comment by tonioo** [comment]
Run the installer a first time like this:
```bash
$ ./run.py --stop-after-configfile-check <your domain>
```
and then change the hostname variable in the installer.cfg file.

**Comment by nizammufid** [comment]
how to continue installtion?

**Comment by tonioo** [comment]
Just run the installer once again without the --stop-after-configfile-check option.
