### ISSUE TITLE
'Contacts' page cannot be translated by other languages. 

### ISSUE THREAD

**Issue by jing95** [modoboa/modoboa#1368]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes
* Webserver: Nginx

# Current behavior
   As the title says,the page only shown as English.
# Expected behavior
  I hope the page can be displayed in other languages
  Thank you in advance
# Video/Screenshot link (optional)
![translate](https://user-images.githubusercontent.com/34827497/35469943-cc49d750-037a-11e8-88df-81f54f25fd33.png)

**Comment by tonioo** [comment]
@stellaxie Which language are you trying to use?

**Comment by stellaxie** [comment]
I;m trying to use Chinese.And in fact, no other language can translate it.

**Comment by tonioo** [comment]
The contacts plugin is not translated into Chinese yet. You can help (https://www.transifex.com/tonio/modoboa/dashboard/) if you have time.

**Comment by stellaxie** [comment]
@tonioo OK，I have translated it.
