### ISSUE TITLE
Not able to save Parameters

### ISSUE THREAD

**Issue by fresH229a** [modoboa/modoboa#1371]
# Impacted versions

* Modoboa: 1.10.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
New setup, after login and password change, I am not able to save parameter settings. Nothing happend on pressing SAVE button

**Comment by JeroenvO** [comment]
Same problem here. Console output after click on 'save' is:
 An invalid form control with name='modoboa_amavis-recipient_delimiter' is not focusable.

Using modoboa 1.10.1 with amavis, dmarc, statistics, webmail and radicale (all latest version), nginx.

**Comment by fyfe** [comment]
duplicate of #1370
