### ISSUE TITLE
Upgrade Error

### ISSUE THREAD

**Issue by WASDIT** [modoboa/modoboa#1372]
i have upgraded to the last Version:

Name | Installed version | Last version | Description
Modoboa | 1.10.1 | 1.10.1 | The core part of Modoboa
Amavis frontend | 1.2.1 | 1.2.1 | Simple amavis management frontend
Contacts | 0.5.0 | 0.5.0 | Address book
PDF credentials | 1.3.1 | 1.3.1 | Generate PDF documents containing users' credentials
Postfix autoreply | 1.4.0 | 1.4.0 | Auto-reply (vacation) functionality using Postfix
Sieve filters | 1.4.0 | 1.4.0 | Plugin to easily create server-side filters
Statistics | 1.4.0 | 1.4.0 | Graphical statistics about emails traffic using RRDtool
Webmail | 1.4.1 | 1.4.1 | Simple IMAP webmail

but i got an error:
(env) root@mail:/srv/modoboa/instance# python manage.py migrate
SystemCheckError: System check identified some issues:

ERRORS:
admin.Domain.transport: (fields.E300) Field defines a relation with model 'transport.Transport', which is either not installed, or is abstract.
admin.Domain.transport: (fields.E307) The field admin.Domain.transport was declared with a lazy reference to 'transport.transport', but app 'transport' isn't installed.
(env) root@mail:/srv/modoboa/instance# admin.Domain.transport: (fields.E300) Field defines a relation with model 'transport.Transport', which is either not installed, or is abstract.
-bash: Syntaxfehler beim unerwarteten Wort `fields.E300'
(env) root@mail:/srv/modoboa/instance#

**Comment by fyfe** [comment]
Did you follow the [upgrade insructions](https://modoboa.readthedocs.io/en/latest/upgrade.html#id2)? Looks like you're missing `modoboa.transport` in `MODOBOA_APPS`
