### ISSUE TITLE
PDF Problem after Upgrade to 1.10.1

### ISSUE THREAD

**Issue by WASDIT** [modoboa/modoboa#1373]
Now i have the problem when i try to download a PDF with the user credentials, the pdf viewer tell that the file is corrupt.

**Comment by tonioo** [comment]
Are you talking about existing documents?

**Comment by WASDIT** [comment]
yes if i change the password of an existing user it worked, but not on existing.

**Comment by tonioo** [comment]
Unfortunately, this is "normal" since we change the way documents are encrypted on the file system...

**Comment by fyfe** [comment]
PDF documents created before 1.10.0 won't work because of the changes to SECRET_KEY.

On January 29, 2018 8:59:10 AM UTC, "WASD-IT.com e.U." <notifications@github.com> wrote:
>yes if i change the password of an existing user it worked, but not on
>existing.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/modoboa/modoboa/issues/1373#issuecomment-361179712

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by WASDIT** [comment]
Ok, thanks for the info.
