### ISSUE TITLE
Postfix Problem after Upgrade to 1.10.1

### ISSUE THREAD

**Issue by WASDIT** [modoboa/modoboa#1374]
After upgrade i got in the Postfix Error Log:
Jan 28 21:23:19 mail postfix/submission/smtpd[3675]: fatal: proxymap service is not configured for table "pgsql:/etc/postfix/sql-sender-login-map.cf"

**Comment by WASDIT** [comment]
Jan 28 21:27:07 mail postfix/trivial-rewrite[4282]: fatal: proxymap service is not configured for table "pgsql:/etc/postfix/sql-transport.cf"
Jan 28 21:27:07 mail postfix/submission/smtpd[4283]: fatal: proxymap service is not configured for table "pgsql:/etc/postfix/sql-sender-login-map.cf"
Jan 28 21:27:11 mail postfix/smtpd[4284]: fatal: proxymap service is not configured for table "pgsql:/etc/postfix/sql-sender-login-map.cf"

**Comment by WASDIT** [comment]
root@mail:/srv/modoboa/instance# rm -f /etc/postfix/modoboa-postfix-maps.chk
root@mail:/srv/modoboa/instance# python manage.py generate_postfix_maps --force --destdir /etc/postfix/
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/modoboa/instance/instance/settings.py", line 13, in <module>
    modoboa_amavis_settings.apply(globals())
AttributeError: 'module' object has no attribute 'apply'
root@mail:/srv/modoboa/instance#

**Comment by olkitu** [comment]
Put this to proxy_read_maps section on Postfix main.cf file:

`proxy:pgsql:/etc/postfix/sql-sender-login-map.cf`

And reload config

**Comment by WASDIT** [comment]
Jan 29 00:16:04 mail postfix/trivial-rewrite[25690]: fatal: proxymap service is not configured for table "pgsql:/etc/postfix/sql-transport.cf"

**Comment by WASDIT** [comment]
my config lines:
proxy_read_maps =
        proxy:pgsql:/etc/postfix/sql-sender-login-map.cf
        proxy:unix:passwd.byname
        proxy:pgsql:/etc/postfix/sql-domains.cf
        proxy:pgsql:/etc/postfix/sql-domain-aliases.cf
        proxy:pgsql:/etc/postfix/sql-aliases.cf
        proxy:pgsql:/etc/postfix/sql-relaydomains.cf
        proxy:pgsql:/etc/postfix/sql-relaydomains-transport.cf
        proxy:pgsql:/etc/postfix/sql-relaydomain-aliases-transport.cf
        proxy:pgsql:/etc/postfix/sql-autoreplies-transport.cf
        proxy:pgsql:/etc/postfix/sql-maintain.cf
        proxy:pgsql:/etc/postfix/sql-relay-recipient-verification.cf
        proxy:pgsql:/etc/postfix/sql-sender-login-mailboxes.cf
        proxy:pgsql:/etc/postfix/sql-sender-login-aliases.cf
        proxy:pgsql:/etc/postfix/sql-sender-login-mailboxes-extra.cf
        proxy:pgsql:/etc/postfix/sql-spliteddomains-transport.cf


should i remove anything?

**Comment by olkitu** [comment]
There is my config's and no errors

```
proxy_read_maps =
        proxy:unix:passwd.byname
        proxy:pgsql:/etc/postfix/sql-domains.cf
        proxy:pgsql:/etc/postfix/sql-domain-aliases.cf
        proxy:pgsql:/etc/postfix/sql-aliases.cf
        proxy:pgsql:/etc/postfix/sql-relaydomains.cf
        proxy:pgsql:/etc/postfix/sql-relaydomains-transport.cf
        proxy:pgsql:/etc/postfix/sql-relaydomain-aliases-transport.cf
        proxy:pgsql:/etc/postfix/sql-autoreplies-transport.cf
        proxy:pgsql:/etc/postfix/sql-maintain.cf
        proxy:pgsql:/etc/postfix/sql-relay-recipient-verification.cf
        proxy:pgsql:/etc/postfix/sql-sender-login-map.cf
        proxy:pgsql:/etc/postfix/sql-sender-login-mailboxes.cf
        proxy:pgsql:/etc/postfix/sql-sender-login-aliases.cf
        proxy:pgsql:/etc/postfix/sql-sender-login-mailboxes-extra.cf
        proxy:pgsql:/etc/postfix/sql-spliteddomains-transport.cf
```

```
smtpd_sender_login_maps =
        proxy:pgsql:/etc/postfix/sql-sender-login-map.cf
#        proxy:pgsql:/etc/postfix/sql-sender-login-mailboxes.cf
#        proxy:pgsql:/etc/postfix/sql-sender-login-aliases.cf
#        proxy:pgsql:/etc/postfix/sql-sender-login-mailboxes-extra.cf
```

**Comment by tonioo** [comment]
Looks like you forgot the upgrade instructions: http://modoboa.readthedocs.io/en/latest/upgrade.html#id2

**Comment by tonioo** [comment]
@WASDIT have you fixed your issue?

**Comment by WASDIT** [comment]
I did what olkitu do and it worked my me.

**Comment by WASDIT** [comment]
Can anyone send me a complete postfix main.cf

**Comment by WASDIT** [comment]
@tonioo can you send me a complete working postfix main.cf for the modoboa 1.10.0?

**Comment by tonioo** [comment]
@WASDIT just follow the upgrade procedure or use this template https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/scripts/files/postfix/main.cf.tpl.

**Comment by WASDIT** [comment]
Thanks 👍
