### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by jing95** [modoboa/modoboa#1375]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes
* Webserver: Nginx

# Current behavior
I created an ordinary user,and when I wanted to use it to check webmail,it said socket errors
# Expected behavior
I can check webmail
# Video/Screenshot link (optional)
![image](https://user-images.githubusercontent.com/34827497/35498019-9399fc1c-0507-11e8-8b26-aa81a0893976.png)

**Comment by tonioo** [comment]
@stellaxie We need more information: please check log file (mail.log) and your Modoboa configuration too (Modoboa > Parameters > Webmail)

**Comment by tonioo** [comment]
@jing95 Do yo still have this issue?
