### ISSUE TITLE
Cron & python error

### ISSUE THREAD

**Issue by CooperBarrett** [modoboa/modoboa#1376]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Cron

 ---

Hello, 
I receive a cron error by email:

**Subject:** 
`Cron <root@monserve> $PYTHON $INSTANCE/manage. py communicate_with_public_api`

**Content:** 
`CommandError: Failed to update instance.`

If I try to run the command `manage. py` manually, here is the returned error: 

```
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage. py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```

Django seems to be well installed but I don't know how to check if it is activated or not.

Thank you in advance for your help. I used a translator, I hope the translation is clear!

**Comment by tonioo** [comment]
@CooperBarrett could it be related too https://github.com/modoboa/modoboa/issues/1345?

**Comment by CooperBarrett** [comment]
yes it looks like it except that it's for `communicate_with_public_api`.

If I do 
```/srv/modoboa/env/env/bin/python/python /srv/modoboa/instance/manage. py communicate_with_public_api```
I have no error.

However, I didn't really understand how to solve the problem.
The variables PYTHON and INSTANCE are well informed.

**Comment by danielsatanik** [comment]
Same problem here and this is probably already the 3rd or 4th time it happened, last time @tonioo you said it was a SSL issue, is this regularly reappearing?
For a little more info last time it kind of happened every full hour now it is like every few hours.
Here is the issue I posted before #1343

**Comment by tonioo** [comment]
@danielsatanik It is not the same issue. I made some changes to the public API today, let's see if it solves something.

**Comment by danielsatanik** [comment]
@tonioo I haven't received the error in hours, so I guess it is fine again. I also believe you that it was a different bug but it caused the same error to be sent via email, just not as regularly.

**Comment by CooperBarrett** [comment]
I close this ticket, I don't have the error since my update to modoboa 1.10
