### ISSUE TITLE
About reinstall

### ISSUE THREAD

**Issue by jing95** [modoboa/modoboa#1379]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
1. I removed /srv/modoboa and /opt/modoboa-installer
2. Reinstalled modoboa use the following commands
> git clone https://github.com/modoboa/modoboa-installer
> cd modoboa-installer
> sudo ./run.py <your domain>
 
   3.Please see Screenshot
# Current behavior
 Reinstall modoboa  
# Expected behavior
 Successful reinstall and needn't to keep previous configuration,I just want to make it look like a new one, never used.
# Video/Screenshot link (optional)
![reinstall](https://user-images.githubusercontent.com/34827497/35613030-bb429914-06a5-11e8-8c36-772fde35b889.png)

**Comment by jing95** [comment]
Is there something I forget to delete?

**Comment by tonioo** [comment]
@jing95 You removed the home directory of the modoboa user, which is a really bad idea... Try something like this before running the installer again:
```shell
> userdel modoboa
```

**Comment by fyfe** [comment]
You need to delete the database users as well
*PostgreSQL*
```shell
psql -U postgres "DROP USER IF EXISTS modoboa, amavis"
```
*MySQL*
```shell
mysql -u root "DROP USER IF EXISTS modoboa, amavis"
```

**Comment by jing95** [comment]
@tonioo I ran the command ,it shows that group modoboa not removed because it has other members .So I stop here , and then I’ve restored the srv/modoboa , it looks just like it used to be ,now can you tell me how to reinstall it correctly?
Thanks.

**Comment by jing95** [comment]
According to this instruction, I backup Settings file, and then removed all modoboa file (but I doubt if I completely removed it),next when I have to reinstall, then appeared the problem mentioned above.
![reinstall2](https://user-images.githubusercontent.com/34827497/35657957-14210824-073a-11e8-8ea6-791117c51e56.png)

**Comment by tonioo** [comment]
@jing95 Just run the installer, it will ask you if you want to overwrite the existing files.

**Comment by jing95** [comment]
@tonioo thank you for your reply.
I run the installer , but as shown in the figure.
![ae](https://user-images.githubusercontent.com/34827497/35716073-4ea9b64e-0811-11e8-9ef2-e970b15fb3a0.png)

The folder was deleted , but no new one was created , and didn't do anything else next.
What should I do ?
Thank you in advance .

**Comment by tonioo** [comment]
Can you run the installer using the --debug option please?

**Comment by jing95** [comment]
@tonioo I've tried , but it also failed . As is shown in figure.it removed /srv/modoboa/instance , but did not create a new one.
![ae](https://user-images.githubusercontent.com/34827497/35728971-3a577000-0848-11e8-83f5-67f394119b44.png)
Now, I'm trying to uninstall first , then install again.  So could you tell me how to uninstall modoboa completely?
I'm sorry to trouble you , but It's really annoying...

**Comment by tonioo** [comment]
Do you have more information when you run the installer with the --debug option?

**Comment by jing95** [comment]
@tonioo No other information

**Comment by jing95** [comment]
So it looks like I have to uninstall it first , and then maybe the installation will work.

**Comment by tonioo** [comment]
Try to remove user and group before running the installer once again.

**Comment by jing95** [comment]
Ok,I will try

**Comment by jing95** [comment]
@tonioo But if it doesn't work, how can I uninstall it?

**Comment by kryskool** [comment]
This issue was moved to modoboa/modoboa-installer#190
