### ISSUE TITLE
Update moduboa-postfix-maps.chk

### ISSUE THREAD

**Issue by plvsouza** [modoboa/modoboa#1382]
I get this error when trying to update moduboa-postfix-maps.chk after update to 1.10.1

> python manage.py generate_postfix_maps --force --destdir /etc/postfix/
> Traceback (most recent call last):
>   File "manage.py", line 22, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 341, in execute
>     django.setup()
>   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
>     app_config = AppConfig.create(entry)
>   File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 123, in create
>     import_module(entry)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
> ImportError: No module named transport

**Comment by plvsouza** [comment]
I follow this steps exactly

**Comment by fyfe** [comment]
Are you sure you've added `modoboa.transport` to `MODOBOA_APPS` in `settings.py`?

**Comment by tonioo** [comment]
@plvsouza Looks like you're not using the right python binary so the virtualenv is not loaded. If you run the command as root, make sure to use the absolute path of the binary (like ``/srv/modoboa/env/bin/python``)

**Comment by plvsouza** [comment]
Now I'm having this problem when starts postfix

> fatal: proxymap service is not configured for table "pgsql:/etc/postfix/sql-transport.cf"

**Comment by tonioo** [comment]
Looks at the upgrade instructions:
http://modoboa.readthedocs.io/en/latest/upgrade.html#id2

**Comment by tonioo** [comment]
And also update proxy_read_maps.

**Comment by plvsouza** [comment]
And also update proxy_read_maps?

Where?

**Comment by tonioo** [comment]
Should be in the same file, main.cf. Have you used the installer?

**Comment by plvsouza** [comment]
It works now
