### ISSUE TITLE
Webmail broken after upgrade

### ISSUE THREAD

**Issue by WLR86** [modoboa/modoboa#1383]
# Impacted versions

* Modoboa: 1.10.1 (upgraded from previous stable version, all extensions up to date)
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Click on 'Webmail' in the main menu bar
# Current behavior
a error is displayed, saying "Sorry An internal error occured."
# Expected behavior
Webmail interface should appear

**Comment by tonioo** [comment]
@WLR86 Please try to logout/login before accessing the webmail.

**Comment by WLR86** [comment]
Oh yeah : ) Works fine now  - Sorry I didn't think about doing that !
Thank you !
