### ISSUE TITLE
Distribution Lists

### ISSUE THREAD

**Issue by DarrenCarterSA** [modoboa/modoboa#1385]
# Impacted versions

* Modoboa: 1.10.1
* installer used: Yes
* Webserver: Nginx

I believe the functionality to set up distribution lists should be available under Identities on the admin panel. However, I can't find anything of the sort. I have searched for answers and could not find anything. Am I missing something?

**Comment by tonioo** [comment]
@DarrenCarterSA Modoboa does not support distribution lists atm.

**Comment by tonioo** [comment]
I mean if you're talking about something similar to mailman for example.

**Comment by DarrenCarterSA** [comment]
@tonioo Thanks for your response. I was referring more to a setup whereby sending an email to one address (e.g. allstaff@example.com) would relay the email to a specified list of emails on the same domain.

However, after pondering on this for a while, I realised that one could set up a new mailbox (e.g. allstaff@example.com) and simply specify all the emails in the forwarders section. Should achieve the same result.
