### ISSUE TITLE
Mail Error (autoreply)

### ISSUE THREAD

**Issue by WASDIT** [modoboa/modoboa#1389]
This is the mail system at host mail.xxx.xx.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

The mail system

<"eb@xxx.xx"@autoreply.xxx.xx> (expanded from <eb@xxx.xx>): Command died
with status 1: "/srv/modoboa/env/bin/python". Command output: Traceback
(most recent call last): File "/srv/modoboa/instance/manage.py", line 22,
in <module> execute_from_command_line(sys.argv) File
"/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py",
line 364, in execute_from_command_line utility.execute() File
"/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py",
line 356, in execute
self.fetch_command(subcommand).run_from_argv(self.argv) File
"/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py",
line 283, in run_from_argv self.execute(*args, **cmd_options) File
"/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py",
line 330, in execute output = self.handle(*args, **options) File
"/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_postfix_autoreply/management/commands/autoreply.py",
line 163, in handle sender_localpart = split_mailbox(sender.lower())[0]
File
"/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/email_utils.py",
line 316, in split_mailbox local_part, domain = split_address(mailbox)
File
"/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/email_utils.py",
line 269, in split_address "address should be of type %s" %
six.text_type.__name__ AssertionError: address should be of type unicode
Reporting-MTA: dns; mail.xxx.xx
X-Postfix-Queue-ID: 3A5B0604F0
X-Postfix-Sender: rfc822; cj@xxx.xx
Arrival-Date: Sun, 4 Feb 2018 11:22:26 +0100 (CET)

Final-Recipient: rfc822; "eb@xxx.xx"@autoreply.xxx.xx
Original-Recipient: rfc822;eb@xxx.xx
Action: failed
Status: 5.3.0
Diagnostic-Code: x-unix; Traceback (most recent call last): File
"/srv/modoboa/instance/manage.py", line 22, in <module>
execute_from_command_line(sys.argv) File
"/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py",
line 364, in execute_from_command_line utility.execute() File
"/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py",
line 356, in execute
self.fetch_command(subcommand).run_from_argv(self.argv) File
"/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py",
line 283, in run_from_argv self.execute(*args, **cmd_options) File
"/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py",
line 330, in execute output = self.handle(*args, **options) File
"/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_postfix_autoreply/management/commands/autoreply.py",
line 163, in handle sender_localpart = split_mailbox(sender.lower())[0]
File
"/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/email_utils.py",
line 316, in split_mailbox local_part, domain = split_address(mailbox)
File
"/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/email_utils.py",
line 269, in split_address "address should be of type %s" %
six.text_type.__name__ AssertionError: address should be of type unicode
Return-Path: <cj@xxx.xx>
Received: from localhost (localhost [127.0.0.1])
by mail.xxx.xx (Postfix) with ESMTP id 3A5B0604F0;
Sun, 4 Feb 2018 11:22:26 +0100 (CET)
X-Virus-Scanned: Debian amavisd-new at mail.xxx.xx
Received: from mail.xxx.xx ([127.0.0.1])
by localhost (mail.xxx.xx [127.0.0.1]) (amavisd-new, port 10026)
with ESMTP id MvMT_RNoLBA5; Sun, 4 Feb 2018 11:22:24 +0100 (CET)
Received: from [192.168.xx.xx] (xxxxxxx.cable.dynamic.surfer.at [xx.xx.xx.xx])
(using TLSv1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits))
(No client certificate requested)
by mail.xxx.xx (Postfix) with ESMTPSA;
Sun, 4 Feb 2018 11:22:24 +0100 (CET)
From: Christian XXXXX <cj@xxx.xx>
Content-Type: multipart/alternative; boundary="Apple-Mail=_B601DBD9-AD08-4D79-A7B8-4AA0FCEB5931"
Subject: Klausur Protokoll
Message-Id: <BFA86287-534C-4587-9188-41ADA0D50A1C@xxx.xx>
Date: Sun, 4 Feb 2018 11:22:24 +0100
To: Edgar xxx <edk@g.xxx.xx>,
=?utf-8?Q?M=C3=B6rz_Katharina?= <km@xxx.xx>,
"mes (Melanie xxx)" <mes@xxx.xx>,
Senad xxx <sh@xxx.xx>,
"eb (Evamaria xxx)" <eb@xxx.xx>
Mime-Version: 1.0 (Mac OS X Mail 9.3 \(3124\))
X-Mailer: Apple Mail (2.3124)

**Comment by WASDIT** [comment]
Hey fyfe,
can i do here a workaround? anything change in the code?

BR

**Comment by fyfe** [comment]
Yes, see modoboa/modoboa-postfix-autoreply#55

**Comment by WASDIT** [comment]
Where i can find this file? How is the path?

**Comment by WASDIT** [comment]
fyfe where i can find this file? How is the path?

**Comment by WASDIT** [comment]
@tonioo yes but how i can do this? where i find the file to change them?

**Comment by WASDIT** [comment]
Where is modoboa_postfix_autoreply/management/commands/autoreply.py?

**Comment by tonioo** [comment]
If you used the installer with default config, you should find it here:
``/srv/modoboa/env/lib/python2.7/site-package/modoboa_postfix_autoreply/management/commands/autoreply.py``
Otherwise, ``locate`` is your friend.

**Comment by WASDIT** [comment]
Thanks

**Comment by WASDIT** [comment]
@tonioo 
<"eb@xxx.xx"@autoreply.xxx.xx> (expanded from <eb@xxx.xx>): Command died
    with status 1: "/srv/modoboa/env/bin/python". Command output: Traceback
    (most recent call last):   File "/srv/modoboa/instance/manage.py", line 22,
    in <module>     execute_from_command_line(sys.argv)   File
    "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py",
    line 364, in execute_from_command_line     utility.execute()   File
    "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py",
    line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)   File
    "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py",
    line 206, in fetch_command     klass = load_command_class(app_name,
    subcommand)   File
    "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py",
    line 40, in load_command_class     module =
    import_module('%s.management.commands.%s' % (app_name, name))   File
    "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)   File
    "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_postfix_autoreply/management/commands/autoreply.py",
    line 204     address, domain = split_mailbox(fulladdress)           ^
    IndentationError: expected an indented block

**Comment by tonioo** [comment]
Looks like you introduced a syntax error when you modified your file. The indentation is important when you write python code. Make sure your local file is exactly the same as the one present on Github.

**Comment by WASDIT** [comment]
i copied it and now it worked ;)
