### ISSUE TITLE
Upgrade help 

### ISSUE THREAD

**Issue by CooperBarrett** [modoboa/modoboa#1390]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes
* Webserver: Nginx

Hi. Hi,
I would like to upgrade modoboa but, let's be clear, I don't understand anything! As much as the installation script is simple, the update procedure is really difficult...

If I try to do it:
`python manage. py generate_postfix_maps --force --destdir /etc/postfix/`
This is my mistake:
```
Traceback (most recent call last):
  File "manage. py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```
I'm probably supposed to do these orders:
```
source <virtuenv_path>/bin/activate
```
But what to replace  **<virtuenv_path>**? I used the installer, I have no idea what to do!
I replaced **<modoboa_user>** by **modoboa** because I have a modoboa user, I guess it's him...

Thank you in advance for your help.

**Comment by CooperBarrett** [comment]
I think I've found the way...
`/srv/modoboa/env`
But if I make `source /srv/modoboa/env/bin/activate` with the modoboa user (`sudo -u modoboa -i`), I have the error: `source: not found`
If I make `source /srv/modoboa/env/env/bin/activate` with my user, it works BUT when I make `python manage. py generate_postfix_maps --force --destdir /etc/postfix/`, here is a new error:
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named transport
```

I'm starting to despair!

**Comment by gawel** [comment]
If source don't work, you can try with a dot:
```
. /srv/modoboa/env/bin/activate
```

Some shells don't implement source. the dot trick do the same.

**Comment by CooperBarrett** [comment]
Thank you,
I managed to activate virtualenv.
But I still have a mistake when I want to make `python manage. py generate_postfix_maps --force --destdir /etc/postfix/` : 

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named transport
```
I really don't see what more I can do...

**Comment by CooperBarrett** [comment]
Finally!!!
I finally managed to update Modoboa to 1.10.0.
Honestly, I find the doc is not super clear, especially for a beginner like me.
I'll try to give my steps to get there.

**Information** :
I'm on Debian Stretch
I used the modoboa installer
I left from modoboa 1.9.1
I am a beginner, do not necessarily take these instructions literally, I put it only to give indications to those who like me had difficulty finding my way in the doc.

**Steps**

We use the modoboa user : 
```
sudo -u modoboa -i
bash
source env/bin/activate
```
Normally you should see **(env)** appear in front of it.
Then we update the extensions:
```
pip install modoboa-amavis==1.2.0
pip install modoboa-contacts==0.5.0
pip install modoboa-dmarc==1.1.0
pip install modoboa--imap-migration==1.2.0
pip install modoboa-pdfcredentials==1.3.0
pip install modoboa-postfix-autoreply==1.4.0
pip install modoboa-radicale==1.2.0
pip install modoboa-sievefilters==1.4.0
pip install modoboa-stats==1.4.0
pip install modoboa-webmail==1.4.0
```
We will now follow the instructions of the doc: http://modoboa.readthedocs.io/en/latest/upgrade.html#specific-upgrade-instructions
`nano instance/instance/settings.py`
Add `'modoboa.transport'` to `MODOBOA_APPS`:
```
MODOBOA_APPS = (
   'modoboa',
   'modoboa.core',
   'modoboa.lib',
   'modoboa.admin',
   'modoboa.transport',
   'modoboa.relaydomains',
   'modoboa.limits',
   'modoboa.parameters',
)
```
Replace the following line:

`MIDDLEWARE_CLASSES = (`

by:

`MIDDLEWARE = (`

Exit the user **modoboa**.
```
exit
exit
```
Double exit because we used `bash`.
```
cd /srv/modoboa/instance/

sudo rm -f /etc/postfix/modoboa-postfix-maps.chk
sudo /srv/modoboa/env/bin/python manage.py generate_postfix_maps --force --destdir /etc/postfix/
```
We modify the configuration of postfix :
`sudo nano /etc/postfix/main.cf`
```
smtpd_sender_login_maps =
  proxy:pgsql:/etc/postfix/sql-sender-login-map.cf

transport_maps =
  proxy:pgsql:/etc/postfix/sql-transport.cf
  proxy:pgsql:/etc/postfix/sql-spliteddomains-transport.cf
```
If `transport_maps` contains `sql-relaydomains-transport.cf`, remove it.

We're restarting postfix:
`sudo service postfix restart`

Modify the modoboa crontab : 
`sudo nano /etc/cron.d/modoboa`
Add the following cron job at the end : 
```
# Generate DKIM keys (they will belong to the user running this job)
*       *       *       *       *       root    $PYTHON $INSTANCE/manage.py modo manage_dkim_keys
```
**Update Modoboa**
We're going back to modoboa user :
```
sudo -u modoboa -i
bash
source env/bin/activate
```
And we do the update plus the migration of modoboa : 
```
cd
pip install modoboa==1.10.0
cd instance
python manage.py migrate
python manage.py collectstatic
python manage.py check --deploy
```
And we restart the server. Normally, everything should be okay.

**Comment by jing95** [comment]
Hi,@CooperBarrett . What is the 'nano'

**Comment by CooperBarrett** [comment]
hi,
Sorry about the response time.
**nano** is a different text editor from **vi**.
If you prefer **vi**, you can replace **nano** with **vi**.

Don't hesitate if you have any more questions.

**Comment by jing95** [comment]
I get it , thank you for your answer.

**Comment by jing95** [comment]
There is another question , I want to update Modoboa to 1.10.1 , do you think I need to do http://modoboa.readthedocs.io/en/latest/upgrade.html#specific-instructions ?
Thank you in advance !

**Comment by jing95** [comment]
Do you have this question?
(modoboa-amavis.W001) AMAVIS_DEFAULT_DATABASE_ENCODING does not match the character encoding used by the Amavis database.

**Comment by jing95** [comment]
@CooperBarrett hello

**Comment by CooperBarrett** [comment]
Sorry for the response time...
Yes, I got this warning, but it doesn't prevent modoboa from working.

**Comment by Cr4shOv3rrid3** [comment]
> Do you have this question? (modoboa-amavis.W001) AMAVIS_DEFAULT_DATABASE_ENCODING does not match the character encoding used by the Amavis database.

to fix this issue pretending you did follow everything through with the modoboa user and activated virtual environment

in modoboa folder you will find a hidden folder named ".local" (without quotes)

this is due to using virtual environment on top of modoboa user

it makes sure everything that runs is installed there in your appropriate python3.x/site-packages folder inside and through that hidden location.

now switch inside that folder to modoboa-amavis folder 
inside you will find settings.py file

now inside that file you will find following entry

settings["AMAVIS_DEFAULT_DATABASE_ENCODING"] = "UTF8"

i just already changed it into UTF8 from something like LATIN1 make sure you did the same and you will no longer get those annoying encoding warnings.
