### ISSUE TITLE
New install working, but cannot save any settings in the web interface (http 400)

### ISSUE THREAD

**Issue by laapsaap** [modoboa/modoboa#1393]
# Impacted versions

* Modoboa: 1.10.2
* installer used: Yes/
* Webserver: Nginx

# Steps to reproduce
run installer, go to webui, go to modoboa and press save after changing settings

I tried figuring this out, but basically a clean centos 7 kickstart and then I run the installer. I can go to the web interface and see everything.

But when I try to edit modoboa -> parameters and press save. I get a http 400.
```
"POST /core/parameters/ HTTP/1.1" 400 132 
```

Then when I do a browser reload, the setting is not saved and goes back to the installer defaults. 

# Possible reason
the WebUI is not showing "form_errors". 

```
{"prefix": "core", "form_errors": {"default_password": ["This password is too common.", "Password must contain at least 1 digit."]}}
```

And then some other form error
```
{"prefix": "modoboa_amavis", "form_errors": {"recipient_delimiter": ["This field is required."]}}
```

Because the UI doesnt show form_errors, I had no idea why it was giving a HTTP 400 and not saving my settings.

**Comment by laapsaap** [comment]
Sorry was latest version 1.10.2 not 1.8.x

**Comment by wroersma** [comment]
I have the same issue but I'm not sure if it's because I didn't RTFM well enough

**Comment by laapsaap** [comment]
Well if you did what I did, then there's not much to read about. This happens immediately after running the installer. And when press save, the post command sends data that it is not recognized by nginx. Not sure if its nginx or other parts of modoboa.

**Comment by laapsaap** [comment]
Okay I did some debugging. The POST sent to /core/parameters are empty.


2018-02-13 14:31:21	10.1.9.12	10.1.10.108	>	POST	mail.int.xxx.com:443	/core/parameters/	HTTP/1.1	-	-
2018-02-13 14:31:21	10.1.10.108	10.1.9.12	<	-	-	-	HTTP/1.1	400	Bad Request

**Comment by wroersma** [comment]
thanks I will any chance I can get an example of the config you used?

**Comment by laapsaap** [comment]
You dont need my config. Just for now change default_password to some random string with numbers in it and Amavis->recipient_delimiter use a + sign. Press save and you should get Parameters saved popup.

Yeah its a bit shitty, default_password shouldnt be required.

**Comment by tonioo** [comment]
A new version of the amavis plugin has been released and should fix this issue.
