### ISSUE TITLE
{"prefix": "modoboa_amavis", "form_errors": {"recipient_delimiter": ["This field is required."]}}

### ISSUE THREAD

**Issue by laapsaap** [modoboa/modoboa#1395]
# Impacted versions

* Modoboa: latest
* installer used: Yes
* Webserver: Nginx

When trying to save settings, I get an error:
{"prefix": "modoboa_amavis", "form_errors": {"recipient_delimiter": ["This field is required."]}}

But $recipient_delimiter in amavisd.conf is commented out/disabled, so shouldnt this field not be required in the settings?

**Comment by fyfe** [comment]
@tonioo we need a new modoboa-amavis release  this has [been fixed since 1.2.1](https://github.com/modoboa/modoboa-amavis/compare/1.2.1...master)

**Comment by tonioo** [comment]
the 1.2.2 release of the amavis plugin has been released and should fix this issue.
