### ISSUE TITLE
Users added with createsuperuser have "isolated" identity list

### ISSUE THREAD

**Issue by jakicoll** [modoboa/modoboa#1397]
# Impacted versions

* Modoboa: 1.9.0
* installer used: Yes
* Webserver: Apache

# Steps to reproduce
Enter the virtual enviroment and
```
./instance/manage.py createsuperuser
Username: some-createdsu
Email: 
Password: 
Password (again): 
Superuser created successfully.
```

# Current behavior
As I login with this user, dashboard shows 1 domain and 12 identities (which is correct).
However, when I go to "List identities", only the user modboa is shown (which was created by `createsuperuser` or the installer - I don't exactly remember that).

By creating another superuser now via the webinterface "Add identity" and logging in with that new user, I can see all identities, except the two created with the `createsuperuser`-function.

This is an excerpt of my sql table core_user. Note the "is_staff" and "master_user" property. I could not find any other obvious differences in the database. I did not look very intensitive though.
```
+----+--------------+-------------------------------+----------+-----------+-------------+
| id | is_superuser | username                      | is_staff | is_active | master_user |
+----+--------------+-------------------------------+----------+-----------+-------------+
|  1 |            1 | superadmin@mydomain.de        |        0 |         1 |           1 |
|  6 |            1 | super2                        |        0 |         1 |           1 |
|  9 |            1 | modoboa                       |        1 |         1 |           0 |
| 11 |            1 | some-createdsu                |        1 |         1 |           0 |
+----+--------------+-------------------------------+----------+-----------+-------------+
```
Changing is_staff and master_user does not seem to fix this behaviour, though.

**Comment by tonioo** [comment]
You should not create a user like this because it won't update internal permissions. Can you try to run the following command:
```shell
> python manage.py modo repair
```

**Comment by jakicoll** [comment]
Yep, fixed that. Sorry for poking around too much.
Would you accept a PR that adds a warning to the output of manage.py createsuperuser?

**Comment by tonioo** [comment]
Sure.
