### ISSUE TITLE
Problem with proper encoding / quarantine view WebGUI

### ISSUE THREAD

**Issue by WhereIsPedro** [modoboa/modoboa#1398]
# Impacted versions

* Modoboa: 1.10.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Upgrade from 1.9.0 to 1.10.0

# Current behavior
Not proper encoding in amavis quarantine (screen below)

Aditional info:
mysql latin1_swedish_ci db

# Expected behavior
UTF8 encoding with letters like ćżńółęś on web interface.

# Video/Screenshot link (optional)

**Quarantine view:**
![2018-02-16 20_19_30-quarantine management](https://user-images.githubusercontent.com/8850576/36325407-0627f230-1358-11e8-98fd-c77784e70528.png)

![IMG](https://user-images.githubusercontent.com/8850576/36354876-db78b266-14da-11e8-9882-8f41cf85b027.png)

**MUA**
![IMG](https://user-images.githubusercontent.com/8850576/36325776-375b96e4-1359-11e8-87dd-08e65baa2215.png)

**1.10.2 with amavis 1.2.2**
* edits works, but encoding is still not proper.

![2018-02-18 18_50_27-quarantine management](https://user-images.githubusercontent.com/8850576/36355009-bfbccbaa-14dc-11e8-84db-cf48f5c0a806.png)

**Comment by tonioo** [comment]
Have you tried to play with the AMAVIS_DEFAULT_DATABASE_ENCODING setting? default value is LATIN1, can you try using UTF8?

**Comment by WhereIsPedro** [comment]
Hi,
Sorry for delay. I changed DB structure to UTF8_unicode, but this didn't solve problem.
Also adding "AMAVIS_DEFAULT_DATABASE_ENCODING = utf8 - didn't solve  the problem.
Also test has been made with latin1 encoding and AMAVIS_DEFAULT_DATABASE_ENCODING. The same :(

Anyway, intresting is that when i can view an email, email's subject on the top is decoded as should be. Rest of mail is not decoded as should. Also grid.
So, any ideas where I should debug ?

**Comment by fyfe** [comment]
`AMAVIS_DEFAULT_DATABASE_ENCODING` is only used to for the `from_addr` and `subject` fields in the `msgs` table, it's not used to read the message body.

To fix the error you need to upgrade Modoboa to 1.10.2, the `append_to_error` parameter doesn't exist in 1.10.0

**Comment by fyfe** [comment]
I missed the bottom of your original message, you've already upgraded to 1.10.2.

How did you convert the database from latin1 to utf8? Did you convert it to utf8 or utf8mb4?

**Comment by WhereIsPedro** [comment]
Hi,

That explains why I have subject like it should be, with right encoding.

- fresh tables with type: utf8_unicode
- new records for tablez from amavis
Shoud I change this to utf8mb4 ( bin / unicode_ci ) ?
Like this:

![image](https://user-images.githubusercontent.com/8850576/36929819-7d72d712-1e96-11e8-8dba-2c3f4835fc38.png)

**Comment by tonioo** [comment]
@WhereIsPedro Have you tried the switch to utf8mb4?

**Comment by WhereIsPedro** [comment]
Hi,

After months, I would like to refresh this problem with observations about Polish letters like "ŻŹĆŃÓŁŚĄĘ żźćńółśóę ..." 

As you asked, yes, db has been set as UTF8MB4

![image](https://user-images.githubusercontent.com/8850576/55280143-b0fe6900-5321-11e9-807a-f76476cb2635.png)

![image](https://user-images.githubusercontent.com/8850576/55280148-bb206780-5321-11e9-86f7-01b69dcaeb15.png)

As result:
![image](https://user-images.githubusercontent.com/8850576/55280199-6cbf9880-5322-11e9-8355-3e63553e9b33.png)

same text has been pasted to Subject and body:
![image](https://user-images.githubusercontent.com/8850576/55280213-92e53880-5322-11e9-8038-8145b02a8650.png)


Anyway, next instalation based on fresh installation Debian 9.8, 
`4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux`

installed trough modoboa-installer with config:

```
[mysql]
user = root
password = *************
charset = utf8
collation = utf8_unicode_ci

[modoboa]
user = modoboa
home_dir = /srv/modoboa
venv_path = %(home_dir)s/env
instance_path = %(home_dir)s/instance
timezone = Europe/Warsaw
dbname = modoboa
dbuser = modoboa
dbpassword = ************
extensions = modoboa-amavis modoboa-pdfcredentials modoboa-postfix-autoreply modoboa-sievefilters modoboa-stats modoboa-webmail modoboa-contacts modoboa-radicale modoboa-dmarc
devmode = false
```

```
**SQL:**
Server type: MariaDB
Server version: 10.1.37-MariaDB-0+deb9u1 - Debian 9.6
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)
```



```
Modoboa | 1.13.1 | 1.13.1 | The core part of Modoboa
Amavis frontend | 1.2.3 | 1.2.3 | Simple amavis management frontend
Contacts | 0.7.3 | 0.7.3 | Address book
DMARC tools | 1.1.0 | 1.1.0 | A set of tools to ease DMARC integration
PDF credentials | 1.3.2 | 1.3.2 | Generate PDF documents containing users' credentials
Postfix autoreply | 1.5.1 | 1.5.1 | Auto-reply (vacation) functionality using Postfix
Radicale management | 1.3.6 | 1.3.6 | Management frontend for Radicale, a simple calendar and contact server.
Sieve filters | 1.4.2 | 1.4.2 | Plugin to easily create server-side filters
Statistics | 1.4.1 | 1.4.1 | Graphical statistics about emails traffic using RRDtool
Webmail | 1.5.0 | 1.5.0 | Simple IMAP webmail
```


![image](https://user-images.githubusercontent.com/8850576/55280313-3daa2680-5324-11e9-9840-c5c991c01501.png)

![image](https://user-images.githubusercontent.com/8850576/55280315-4a2e7f00-5324-11e9-8f87-4c9ef28cb8e2.png)

with result:
![image](https://user-images.githubusercontent.com/8850576/55280333-9679bf00-5324-11e9-9f95-696cb26ca035.png)

![image](https://user-images.githubusercontent.com/8850576/55280344-d345b600-5324-11e9-88bf-f68fdb85bac1.png)

The same on next fresh installation based on Ubuntu 18 LTS ...
