### ISSUE TITLE
issue with "Parameter secret_key not defined for app core" in 1.10.1 & 1.10.2

### ISSUE THREAD

**Issue by WhereIsPedro** [modoboa/modoboa#1399]
# Impacted versions

* Modoboa: 1.10.1, 1.10.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Upgrade from 1.10.0 to .1 or .2

# Current behavior
Cant change password
- Secret key option in Modoboa > Parameters > General  is not available
- Can't change users passsword with error "Parameter secret_key not defined for app core"

# Expected behavior
- change pasword option

# Video/Screenshot link (optional)

**Password change 1.10.1 & 1.10.2**
![2018-02-16 19_16_56-identities](https://user-images.githubusercontent.com/8850576/36322781-e8910c06-134e-11e8-8672-013527b8a023.png)

**Settings in 1.10.1 & in 1.10.2:**
![2018-02-16 20_14_43-modoboa settings](https://user-images.githubusercontent.com/8850576/36324903-47d54eb4-1356-11e8-81d3-240eddc58d4e.png)

**Settings in 1.10.0**
![2018-02-16 19_19_53-modoboa settings](https://user-images.githubusercontent.com/8850576/36324941-5dc3a19e-1356-11e8-8cd0-7aa0ee2a88e5.png)

**Solution:**
Downgrade to 1.10.0

**Comment by tonioo** [comment]
Have you updated all your extensions? (especially the pdf credentials one)

**Comment by tonioo** [comment]
@WhereIsPedro ping

**Comment by WhereIsPedro** [comment]
Hi Tonioo

Sorry for delay. Anyway, couple of minutes ago update has been made to:
modoboa-pdfcredentials==1.3.1,
modoboa-amavis==1.2.2, 
modoboa==1.10.3 

It's working.
Thank you
