### ISSUE TITLE
Can't Save Parameters

### ISSUE THREAD

**Issue by DarrenCarterSA** [modoboa/modoboa#1400]
# Impacted versions

* Modoboa: 1.10.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

* Login -> Modoboa -> Paramaters
* Try to update parameters

# Current behavior

The screen refreshes and no parameters are saved, no error or success message displayed on UI. 400 Bad Request on POST https://xxx.example.com/core/parameters/
If you return to the parameters page, all settings are as they were before.

# Expected behavior

Display success or failure message on save, changes to reflect when revisiting the parameters page.

# Video/Screenshot link (optional)

![image](https://user-images.githubusercontent.com/1651380/36359611-b4c0403a-1525-11e8-8477-1395aecca38b.png)

**Comment by w00kie** [comment]
I had the same issue. I looked at the 400 error response and it said the **modoboa_amavis** **recipient_delimiter** was a required field. Mine was empty.

What I did is add the following to my `/etc/amavis/conf.d/50-user` file:

```
$recipient_delimiter = '+';
```

And then set the field to `+` in the parameters on the web app. Then I could save.

**Comment by tonioo** [comment]
@DarrenCarterSA Make sure you're using the latest version of the amavis plugin (1.2.2 now), this issue has been fixed.

**Comment by DarrenCarterSA** [comment]
I have tried the suggestion above and it is still giving me the same issue. I am running the latest version as well.

**Comment by tonioo** [comment]
Have you tried a hard refresh of your browser cache?

**Comment by DarrenCarterSA** [comment]
I have indeed, even tried a web browser I have never used before for the domain.

**Comment by tonioo** [comment]
A 400 error means there is a validation issue in one or more tab (ie. a missing value for a required setting). Have you checked all tabs? (amavis or PDF credentials)

**Comment by DarrenCarterSA** [comment]
I have checked and filled each and every field on each and every tab. Yet still getting the same error.
Is there any way to get better logs? Apart from my browsers debugger, I can't find any other logs on the server regarding the parameter saving issue.

**Comment by tonioo** [comment]
Open your javascript debugger and go to the network tab, then check responses sent by the server.

**Comment by DarrenCarterSA** [comment]
@tonioo That did the trick! My problem was with the default password. I left it as per the default "password" and this is where the form validation was failing. Might be useful to add the password requirements to the "?" tooltip in future.

Thanks everyone for your help on the matter.
