### ISSUE TITLE
ConnectionDoesNotExist at /dashboard/

### ISSUE THREAD

**Issue by notoriousbsd** [modoboa/modoboa#1409]
# Impacted versions
```
Name: modoboa
Version: 1.10.2
Summary: Mail hosting made simple
Home-page: http://modoboa.org/
Author: Antoine Nguyen
Author-email: tonio@ngyn.org
License: ISC
Location: /home/modoboa/modoboa/lib/python2.7/site-packages
Requires: rfc6266, backports.csv, cryptography, django, django-ckeditor, django-xforwardedfor-middleware, chardet, argparse, django-subcommand2, dj-database-url, jsonfield, feedparser, django-reversion, requests, py-dateutil, lxml, bcrypt, passlib, progressbar33, django-braces, coreapi-cli, dnspython, gevent, djangorestframework, pytz, coreapi, ipaddress
```

* installer used: Yes/No ? No, it is a custom build so we're setting up everything by hand :( 
* Webserver: Nginx/Apache Nginx

# Steps to reproduce

Install utilizing the manual method outlined by the docuemntation

# Current behavior
```

Request Method: | GET
-- | --
https://mail.emailflo.io/dashboard/
1.11.10
ConnectionDoesNotExist
The connection amavis doesn't exist
/home/modoboa/modoboa/lib/python2.7/site-packages/django/db/utils.py in ensure_defaults, line 178
/usr/sbin/uwsgi
2.7.5
['.',  '',  '/home/modoboa/modoboa/lib64/python27.zip',  '/home/modoboa/modoboa/lib64/python2.7',  '/home/modoboa/modoboa/lib64/python2.7/plat-linux2',  '/home/modoboa/modoboa/lib64/python2.7/lib-tk',  '/home/modoboa/modoboa/lib64/python2.7/lib-old',  '/home/modoboa/modoboa/lib64/python2.7/lib-dynload',  '/usr/lib64/python2.7',  '/usr/lib/python2.7',  '/home/modoboa/modoboa/lib/python2.7/site-packages']
Tue, 27 Feb 2018 21:58:10 +0000
```

# Expected behavior
Dashboard.

**Comment by fyfe** [comment]
You're missing the configuration for the amavis database in settings.py, see [Connect Modoboa and Amavis](https://modoboa-amavis.readthedocs.io/en/latest/setup.html#connect-modoboa-and-amavis)

**Comment by notoriousbsd** [comment]
I have added the configuration settings to the suggested file, however it does not indicate a method of having this change picked up. 

I also see in the documentation it says 'Then, you must tell amavis to use this database for lookups and quarantined messages storing. ' prior to where to make the suggested edit for settings.py, however it does not mention where it is to be added relative to the custom installation. 

Can a documentation update be made to specify where this edit should go? Or if you know where it is that would be helpful too :)

**Comment by notoriousbsd** [comment]
```
Request Method: | GET
-- | --
https://mail.emailflo.io/dashboard/
1.11.10
ProgrammingError
(1146, "Table 'modoboa.msgrcpt' doesn't exist")
/srv/modoboa/modoboa/lib/python2.7/site-packages/django/db/models/sql/compiler.py in execute_sql, line 899
/usr/sbin/uwsgi
2.7.5
['.',  '',  '/srv/modoboa/modoboa/lib64/python27.zip',  '/srv/modoboa/modoboa/lib64/python2.7',  '/srv/modoboa/modoboa/lib64/python2.7/plat-linux2',  '/srv/modoboa/modoboa/lib64/python2.7/lib-tk',  '/srv/modoboa/modoboa/lib64/python2.7/lib-old',  '/srv/modoboa/modoboa/lib64/python2.7/lib-dynload',  '/usr/lib64/python2.7',  '/usr/lib/python2.7',  '/srv/modoboa/modoboa/lib/python2.7/site-packages']
```

Can you specify what process creates this table? Do I need to re-run something since I've modified my amavis values? The path seems to indicate django, but I assume that's just the framework.

**Comment by notoriousbsd** [comment]
The solution here was to run this file against my modoboa database, and my amavis database: 
`/scripts/files/amavis/amavis_mysql_2.11.0.sql`
