### ISSUE TITLE
Rainloop for Modoboa

### ISSUE THREAD

**Issue by saurabh-panjwani** [modoboa/modoboa#1410]
How do I use rainloop as a webmail for modoboa?

**Comment by Toniob** [comment]
Hi,
I think your bug doesn't belong here. What you're asking is how to install a webmail which is not related to Modoboa. Maybe you'll find useful informations on the Rainloop website ?
Why don't you use the webmail extension ? If there are features in Rainloop missing in modoboa-webmail, then you can open requests for enhancements. It will be a good idea.
