### ISSUE TITLE
cant enable dkim on domain

### ISSUE THREAD

**Issue by jookk** [modoboa/modoboa#1411]
# Impacted versions

* Modoboa: latest
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
save dkim dir path on modoboa config page
create new domain, select Enable DKIM signing and save. 
Red text: "DKIM keys storage directory not configured"
# Current behavior
cant save enabled dkim signing on domain
# Expected behavior
enabled and saved dkim signing
# Video/Screenshot link (optional)

**Comment by fyfe** [comment]
If you go back into the settings page does the `DKIM keys storage directory` field contain the path you set?

**Comment by jookk** [comment]
No. Tried many times.
Parameters are not saved

Dňa 1. marca 2018 14:22:21 používateľ Andrew Fyfe 
<notifications@github.com> napísal:>

**Comment by fyfe** [comment]
Can you open the javascript console on your browser (F12 for most browsers) and see if any errors come up when you save the parameters.

**Comment by jookk** [comment]
Yes, there is, see pict
https://nc.orencak.eu/s/6EjBWi9HGFrjEmP
screenshot is after pressing save buttons on modoboa parameters page.

**Comment by tonioo** [comment]
@jookk You can upgrade modoboa to 1.10.3 which fixes the parameters issue.

**Comment by jookk** [comment]
I have problem to launch upgrade :/

Dňa 2. marca 2018 15:49:31 používateľ Antoine Nguyen 
<notifications@github.com> napísal:>

**Comment by kisst** [comment]
Still exist on latest version, with fresh ( beta ) install.

**Comment by bernd-wechner** [comment]
I get this too. Further, when I look at the Preferences as suggested I see no joy:

![image](https://user-images.githubusercontent.com/7296506/206969071-a174b1ba-bc45-4d13-b573-ae1be39b4f6e.png)

Messages on the browser console are not informative, clearing the reloading the page shows:

```
16:43:15.310 This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. user
16:43:15.399 Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.js:3429:51
16:43:16.340 The Components object is deprecated. It will soon be removed. user
16:43:16.400 Object { xmlType: false }
content.js:10924:25
```

**Comment by bernd-wechner** [comment]
> I get this too. Further, when I look at the Preferences as suggested I see no joy:

All sorted. I had confused Parameters with Preferences and vice versa. Under Parameters at:

https://mymail.domain/core/#parameters/

All was visible, I added the DKIM keys storage directory and all is good (well not quite all, but this issue no longer exists for me).
