### ISSUE TITLE
Feature request: add Content-Security-Policy headers

### ISSUE THREAD

**Issue by basbebe** [modoboa/modoboa#1414]
Modoboa should be able to send it's own `Content-Security-Policy` HTTP headers.
It script-src only allowed specific, dynamically created nonces, security could be enhanced for supporting browsers.

**Comment by kryskool** [comment]
Hi @bax- 

CSP can be configure in Nginx or Apache to inject the proper header, 

I prefer this solution, because you can modify template, and use Google analytic or new theme and font, that required to adjust the CSP HTPP header.

Regards,
