### ISSUE TITLE
Sieve Filter: `Parse error????`

### ISSUE THREAD

**Issue by bax-** [modoboa/modoboa#1415]
# Impacted versions

* Modoboa: 1.10.2
* installer used: No
* Webserver: h2o
# Steps to reproduce

I have a sieve rule "default" set up on my web server which is:

```
require "fileinto";
require "imap4flags";

if header :is "X-Spam" "Yes" {
    setflag "\\Seen";
    addflag "Junk";
    fileinto "Junk";
    stop;
}
```
When I log in into modoboa as a user and try to view the rule "default", I only get a flag on the site showing that the rule couldn't be loaded.

The log shows:
```
==> /var/log/uwsgi-modoboa.log <==
Parse error????
```

I don't have another error.
The sieve settings are correct.

**Comment by fyfe** [comment]
Go into user settings > Preferences > Message filters and set `Editor mode` to `raw`.

`simplified` mode expects the sieve file to be in a format generated by modoboa.

**Comment by bax-** [comment]
thank you.
Didn't get that, sorry.
