### ISSUE TITLE
Reject unknown recipient addresses

### ISSUE THREAD

**Issue by skandragon** [modoboa/modoboa#1416]
# Impacted versions

* Modoboa: 1.10.3
* installer used: Yes (then upgraded recently)
* Webserver: Nginx

For some reason, my quarantine list is littered with email destinations that do not exist, and have never existed in this modoboa setup.

How do I have addresses that will never work rejected at the SMTP layer, so they just bounce back, rather than end up in my quarantine list?  Ideally, this should be possible to do through the UI; I know I can just manually configure postfix, but it should do this out of the box.

**Comment by fyfe** [comment]
It's part of the [Postfix configuration](http://modoboa.readthedocs.io/en/latest/manual_installation/postfix.html#configuration).
```
smtpd_recipient_restrictions =
      # ...
      check_recipient_access
          <driver>:/etc/postfix/sql-maintain.cf
          <driver>:/etc/postfix/sql-relay-recipient-verification.cf
      permit_mynetworks
      reject_unauth_destination
      reject_unverified_recipient
      # ...
```
The important two being [reject_unauth_destination](http://www.postfix.org/postconf.5.html#reject_unauth_destination) and [reject_unverified_recipient](http://www.postfix.org/postconf.5.html#reject_unverified_recipient), check this is set in `main.cf`.

If you've used the installer this should be set for you, have you made any changes to `main.cf`? If you're still having issues post a copy of `main.cf`.

**Comment by skandragon** [comment]
No, but I think I realized I left the domain set up to relay unknown users to a second host, and that relay is what is currently causing the spam filtering to kick in before sending it along.  I think once I remove that, it should work as expected.

**Comment by skandragon** [comment]
I was in transition, where I was moving accounts from the old server to the new one bit by bit.  However, they are all moved, and I changed the domain `flame.org` from a relay domain to a plain old domain.  I expected this to start causing unknown addresses to be rejected, however, I see one in the quarantine that is not a valid address.

**Comment by skandragon** [comment]
More info, here are the logs dealing with this specific spam.

**Comment by tonioo** [comment]
@skandragon Amavis is configured to quarantine SPAM by default so I don't see any bug here.
What do you want to do?

**Comment by skandragon** [comment]
I feel it should not quarantine spam for addresses which do not exist, it should just outright discard them.  That's the problem -- the address "magic@flame.org" is not a valid recipient, and it just clutters the quarantine having it there, as it will never be accepted.

**Comment by fyfe** [comment]
This isn't an amavis problem it's an issue with postfix, if the address doesn't exist it should be rejected before it gets passed to amavis.

Can you post the output of `postconf -nf`.

**Comment by skandragon** [comment]
[postconf.txt](https://github.com/modoboa/modoboa/files/1798154/postconf.txt)

**Comment by fyfe** [comment]
The only possible cause I can see is this:
```
virtual_alias_maps = pcre:/etc/postfix/virtual_aliases.pcre
    proxy:pgsql:/etc/postfix/sql-aliases.cf
```
What's in `/etc/postfix/virtual_aliases.pcre`?

----

Do you have catch all alias? (an alias with the email set to `@flame.org`)

**Comment by skandragon** [comment]
There are three aliases, one which will redirect root@ for several hosts to my personal email address, and two that re-map emails in the older qmail-format `user-extra@flame.org` to `user+extra@flame.org` syntax.  There's no catch-all, in that every address in that file has an explicit user@host pattern.

**Comment by tonioo** [comment]
@skandragon It might be a before-queue filtering issue... (that's how the installer deploys amavis by default) See http://www.postfix.org/SMTPD_PROXY_README.html.

**Comment by skandragon** [comment]
What is the recommended configuration, and which installer set this up as a before-queue filter?

**Comment by tonioo** [comment]
@skandragon Are you still encountering this issue?

When the content filter is configured to work in "before queue" mode, it will deal with messages before any address resolution is made by postfix. If you want to avoid it, change postfix's config to run amavis in "after queue" mode.

**Comment by vtoc** [comment]
@tonioo the better solution is to check before queue, you only need to add

```
virtual_mailbox_maps = pgsql:/etc/postfix/sql/sql-mailboxes.cf
```

```user = postfix
password = donttell
dbname = modoboa
hosts = localhost
query = SELECT 'OK' FROM admin_mailbox LEFT JOIN admin_domain ON admin_mailbox.domain_id = admin_domain.id WHERE admin_mailbox.address='%u' AND admin_domain.name='%d' LIMIT 1;
```
This will check the user before accepting the mail and reject if otherwhise and only after it will pass the mail to amavis, which still can reject before queue and thus won't bounce spam

**Comment by skandragon** [comment]
Will this also handle user+foo@ and user-foo@ if postfix is set up to handle this elsewhere?
