### ISSUE TITLE
Webmail (mobile view): Buttons are laying about each other 

### ISSUE THREAD

**Issue by Gravity-87** [modoboa/modoboa#1427]
FIRST OF ALL: 
Dear Modoboa-Specialists: Thx for this great project!! I installed Modoboa last weekend with the installer and now have a fully functional e-mail-server. It's a really big thing! :-)
**********************************************************************************************************
My issue...

# Impacted versions
* Modoboa: 1.10.3
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
In the mobile view of the webmail interface on my smartphone (5,5"), there is the following problem:
- in the right mobile menu I click on "webmail" and get my inbox list (overview)
- on top of the list, you can see a search-field, a delete-button (red), a junk-button (orange) and a multi-choice-button for some more e-mail-actions.
- when I now use the left mobile menu to get the "New mail" button (green), this button lays BEHIND the search field, the delete- and the junk-button and is not really selectable
- It's reproducable on Android-Smartphone, with Opera- and Firefox-Browser.

# Current behavior
As described

# Expected behavior
It would be nice to have a really usable "New mail" button (green) in mobile view of the webmail interface.

# Video/Screenshot link (optional)
![screenshot_20180306-130515](https://user-images.githubusercontent.com/37107634/37031593-b0b21a06-213f-11e8-9320-2714c85ce140.jpg)

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-webmail#155
