### ISSUE TITLE
Upgrade Modoboa Problems Transport

### ISSUE THREAD

**Issue by carbans** [modoboa/modoboa#1429]
# Impacted versions

* Modoboa: 1.10.3
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce
Hi, I try to upgrade modoboa from 1.9.1 to 1.10.3 and I upgrade modoboa, modoboa_amavis, modoboa_sievefilters, modoboa_webmail. 
It's upgrade without problem, but when I try to launch I see in the terminal this:

admin.Domain.transport: (fields.E300) Field defines a relation with model 'transport.Transport', which is either not installed, or is abstract.
admin.Domain.transport: (fields.E307) The field admin.Domain.transport was declared with a lazy reference to 'transport.transport', but app 'transport' isn't installed.

How can I fix it?

**Comment by tonioo** [comment]
Looks like you did not follow the upgrade procedure: http://modoboa.readthedocs.io/en/latest/upgrade.html#id2.

**Comment by carbans** [comment]
Okey! Thanks The problem was I didn't see the specific steps by version. Sorry!
Everything is alright
