### ISSUE TITLE
[enhancement] password complexity customisation

### ISSUE THREAD

**Issue by cptMikky** [modoboa/modoboa#1434]
# Impacted versions

* Modoboa: 1.10.3

I coulnd't find any password complexity settings except through editing settings.py. It would be nice to have an admin GUI for that.

**Comment by kryskool** [comment]
Hi @cptMikky 

May be related with your question #1422 

Regards,

**Comment by cptMikky** [comment]
I don't think so, @kryskool. My question is about password complexity enforcement, 1422 is about password encryption and storage. 

And it's not really a question, it's more like a feature request ;)
