### ISSUE TITLE
Adding new domains with type relay domain dows not work

### ISSUE THREAD

**Issue by y0va** [modoboa/modoboa#1444]
# Impacted versions

* Modoboa: 1.10.3
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Domains -> Edit Domain -> Alias

When trying to add it as an alias domain to an existing relay domain by typing it in the *Alias(es)* box and pressing enter, it is shown in the interface. Unfortunately pressing Update does not work and the browser console yields an error:

```
jquery.min.js:5 POST https://email.ecobytes.net/admin/domains/122/edit/ 500 (Internal Server Error)
send @ jquery.min.js:5
ajax @ jquery.min.js:5
simple_ajax_form_post @ global.js:171
(anonymous) @ admin.js:314
i @ jquery.min.js:3
i @ jquery.min.js:4
dispatch @ jquery.min.js:3
v.handle @ jquery.min.js:3
VM235:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.parseJSON (jquery.min.js:3)
    at Object.<anonymous> (global.js:195)
    at c (jquery.min.js:3)
    at Object.fireWith [as rejectWith] (jquery.min.js:3)
    at k (jquery.min.js:5)
    at XMLHttpRequest.r (jquery.min.js:5)
```

which is due to the thrown 500 HTML error page, instead of the expected JSON.
The UWSGI log in `/var/log/uwsgi/app/modoboa_instance.log` only reads

    email.ecobytes.net [pid: 30615|app: 1|req: 997/9890] 91.65.240.8 () {58 vars in 1219 bytes} [Thu Mar 22 13:08:02 2018] POST /admin/domains/122/edit/ => generated 870 bytes in 157 msecs (HTTP/1.1 500) 5 headers in 181 bytes (1 switches on core 0)

Adding new domains with type "relay domain" doesn't work neither.

**Comment by tonioo** [comment]
@y0va Can you set DEBUG to True inside settings.py, reload your wsgi server and check response body using a javascript debugger?

**Comment by y0va** [comment]
Strangely I had two entries for policies of this domain. After deleting them and reconfiguring the domain it worked again.
