### ISSUE TITLE
webmail error  occurs when the folder is not empty

### ISSUE THREAD

**Issue by foxinstone** [modoboa/modoboa#1449]
# Impacted versions

* Modoboa: 1.10.3
* installer used: Yes
* Webserver: Nginx
* OS: Ubuntu 16.04

# Steps to reproduce
according the document

# Current behavior
Everything else looks good, except for  webmail show “internal error!”,when the folder isn't empty.
But, it is important that i can use remote app in my celphone to send/reveive mail, everything's okay。

Just only when you use a Webmail fails , and just an error occurs only when the folder is not empty!

# Expected behavior
Help me to fix it, Please!

# Video/Screenshot link (optional)
![image](https://user-images.githubusercontent.com/35874666/38188210-79281fbe-368d-11e8-9be3-dbb309ebb948.png)

**Comment by tonioo** [comment]
@foxinstone Please set DEBUG to True inside settings.py and reload your WSGI server, you should get more information about the issue.

**Comment by niko-lay** [comment]
Same issue
Where I can find a debug log?
```
[root@mail] instance#  pwd
/srv/modoboa/instance/instance
[root@mail] instance# cat settings.py | grep DEBUG
#DEBUG = False
DEBUG = True
# A list of all the people who get code error notifications. When DEBUG=False
```
Now in log file I see only this strings
```
[root@mail] instance# tail /var/log/uwsgi/app/modoboa_instance.log
mail.xxx.com [pid: 37724|app: 1|req: 42/67] 1.2.3.4 () {56 vars in 1213 bytes} [Mon Apr  2 17:59:28 2018] POST /webmail/?action=compose => generated 906 bytes in 903 msecs (HTTP/2.0 200) 6 headers in 229 bytes (1 switches on core 0)
mail.xxx.com [pid: 37723|app: 1|req: 26/68] 1.2.3.4 () {48 vars in 1004 bytes} [Mon Apr  2 17:59:29 2018] GET /webmail/?action=listmailbox&mbox=INBOX&_=1522684734929 => generated 19833 bytes in 611 msecs (HTTP/2.0 500) 5 headers in 169 bytes (1 switches on core 0)
mail.xxx.com [pid: 37724|app: 1|req: 43/69] 1.2.3.4 () {48 vars in 1036 bytes} [Mon Apr  2 17:59:32 2018] GET /webmail/?action=listmailbox&mbox=INBOX&reset_page=true&_=1522684734930 => generated 19902 bytes in 185 msecs (HTTP/2.0 500) 5 headers in 169 bytes (1 switches on core 0)
mail.xxx.com [pid: 37723|app: 1|req: 27/70] 1.2.3.4 () {48 vars in 955 bytes} [Mon Apr  2 17:59:56 2018] GET /core/top_notifications/check/ => generated 2 bytes in 51 msecs (HTTP/2.0 200) 5 headers in 152 bytes (1 switches on core 0)

```

**Comment by foxinstone** [comment]
I already set DEBUG = True, but what has changed, nothing happened.
however, when i click 'Contacts',something wrong,  i will attach a  trace back file to you.

By the way, i guess that's what about language features, because i found that too few lists the available language of choice ，i also send the screen shot to you.

![image](https://user-images.githubusercontent.com/35874666/38204024-cad39500-36d3-11e8-9d5f-88e0e0a227ac.png)

[traceback.txt](https://github.com/modoboa/modoboa/files/1868556/traceback.txt)

**Comment by tonioo** [comment]
@foxinstone @niko-lay I've just released a new version of the webmail plugin (1.4.2), could you please try it?

**Comment by kryskool** [comment]
This issue was moved to modoboa/modoboa-webmail#159

**Comment by foxinstone** [comment]
Ofcause I will try it, thanks for your work.
But how can I update? Please help me!

Antoine Nguyen <notifications@github.com> 于 2018年4月6日周五 16:50写道：

**Comment by carbans** [comment]
You can update if you follow the next instructions: http://modoboa.readthedocs.io/en/latest/upgrade.html
