### ISSUE TITLE
Feature Request for Modoboa - 2 factor authentication

### ISSUE THREAD

**Issue by kryskool** [modoboa/modoboa#1455]
_From @CyberfoxDK on December 7, 2017 19:42_

Many solutions today offer inhanced logon security with 2 factor authentication.
I would love if modoboa offered 2-factor for webmail access.

_Copied from original issue: modoboa/modoboa-installer#172_

**Comment by inas3** [comment]
Yes i second this.  But in addition to 2FA on webmail access, it should also be included into the main control panel logon access for the admin user or any other additional user created (just like mailcow has when logging on their control panel)

This is a very important feature to have on a mail hosting server

**Comment by CyberfoxDK** [comment]
Agree with inas3.
One thing to take into consideration, is of cause that imap or pop3 connections should not prompt for 2fa.
Only the webmail / admin site

**Comment by tonioo** [comment]
FYI, you can sponsor this feature: https://modoboa.org/en/projects/10/.
