### ISSUE TITLE
Can't access Identities Listing -> error 500

### ISSUE THREAD

**Issue by jaysee** [modoboa/modoboa#1457]
# Impacted versions

* Modoboa: 1.10.4
* installer used: Yes
* Webserver: Nginx

# Current behavior

Just going to the indentities tab and I've an `internal error` message, request `GET https://mailserver/admin/identities/list/?_=xxxx` returns `500 Internal Server Error`

I think this is somehow related to my content/configuration, but I can't have anything to lead me to the problem, can someone explain how to get some debugging  informations?
The only log i found is `/var/log/uwsgi/app/modoboa_instance.log` and it tolds me not so much :

```mailserver [pid: 2115|app: 1|req: 24/33] IP.IP.IP.IP () {50 vars in 1158 bytes} [Mon Apr  9 14:54:18 2018] GET /admin/identities/list/?_=1523278455956 => generated 870 bytes in 139 msecs (HTTP/1.1 500) 5 headers in 181 bytes (1 switches on core 0)```

thanks!

**Comment by tonioo** [comment]
Set DEBUG to True inside settings.py, reload your WSGI server and open a javascript debugger to inspect the server's response body.

**Comment by jaysee** [comment]
Ok, the problem was

`ProgrammingError at /admin/identities/list/
(1146, "Table 'modoboa.modoboa_imap_migration_migration' doesn't exist")`

So i tried reinstalling the plugin but this does not resolves the issue, I disabled since I don't neet it for the moment

**Comment by tonioo** [comment]
@jaysee Did you run the following command:
```shell
python manage.py migrate modoboa_imap_migration
```
(as indicated in the [README](https://github.com/modoboa/modoboa-imap-migration))

**Comment by jaysee** [comment]
Can't remember exactly, I usually follow the readmes.

For sur, ater installing the plugin i did a `python manage.py migrate`

I tried it now, but I get some errors `django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0007_auto_20161104_1915 is applied before its dependency relaydomains.0005_auto_20161105_1426 on database 'default'.` ;(

**Comment by tonioo** [comment]
@jaysee Have you applied the 1.10.0 upgrade procedure? (http://modoboa.readthedocs.io/en/latest/upgrade.html#id2)

**Comment by jaysee** [comment]
I did, and if a try again, still the same `django.db.migrations.exceptions.InconsistentMigrationHistory` error message ;(

**Comment by jaysee** [comment]
`modoboa.transport` is in my `MODOBOA_APPS` but since `INSTALLED_APPS += MODOBOA_APPS` I guess this made it ?

**Comment by jaysee** [comment]
this :
```
admin
 [X] 0001_initial
 [X] 0002_migrate_from_modoboa_admin
 [X] 0003_auto_20151118_1215
 [X] 0004_auto_20160914_0907
 [X] 0005_auto_20161026_1003
 [X] 0006_auto_20161104_1900
 [X] 0007_auto_20161104_1915
 [X] 0008_domain_enable_dns_checks
 [X] 0009_auto_20170215_0948
 [X] 0010_auto_20170215_1328
 [X] 0011_domain_transport
 [X] 0012_auto_20180112_1658
 [X] 0013_auto_20180124_2311
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
authtoken
 [X] 0001_initial
 [X] 0002_auto_20160226_1747
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
core
 [X] 0001_initial
 [X] 0002_delete_extension
 [X] 0003_user_master_user
 [X] 0004_auto_20150728_1228
 [X] 0005_user_language
 [X] 0006_auto_20151114_1518
 [X] 0007_auto_20151116_1349
 [X] 0008_localconfig
 [X] 0009_auto_20161026_1003
 [X] 0010_auto_20161026_1011
 [X] 0011_auto_20161104_2217
 [X] 0012_auto_20170215_1034
 [X] 0013_auto_20170707_1058
 [X] 0014_auto_20171010_1746
 [X] 0015_auto_20180112_1642
lib
 [X] 0001_initial
 [X] 0002_rename_parameters
 [X] 0003_rename_parameters
 [X] 0004_auto_20151114_1409
 [X] 0005_auto_20160416_1449
 [X] 0006_auto_20161104_2206
limits
 [X] 0001_initial
 [X] 0002_auto_20151114_1518
 [X] 0003_auto_20160413_1046
 [X] 0004_auto_20160413_1312
 [X] 0005_auto_20160415_1654
 [X] 0006_auto_20170216_1112
modoboa_dmarc
 [X] 0001_initial
 [X] 0002_auto_20180124_2311
relaydomains
 [ ] 0001_initial
 [ ] 0002_migrate_from_modoboa_admin_relaydomains
 [ ] 0003_auto_20170116_1508
 [ ] 0004_auto_20161105_1424
 [ ] 0005_auto_20161105_1426
 [ ] 0006_auto_20170215_0948
 [ ] 0007_recipientaccess
 [ ] 0008_auto_20171123_1653
 [ ] 0009_auto_20171124_1508
reversion
 [X] 0001_squashed_0004_auto_20160611_1202 (4 squashed migrations)
sessions
 [X] 0001_initial
sites
 [X] 0001_initial
 [X] 0002_alter_domain_unique
transport
 [X] 0001_initial
```

**Comment by tonioo** [comment]
That's really strange... Did you add the relaydomains app to your setup recently?

**Comment by jaysee** [comment]
Nop, i think I installed by default it at the very begining of my installation, as i've no usage of such functionnality yet.

**Comment by tonioo** [comment]
Then I don't understand why migrations have not been applied. If you look at the database, do you see any table beginning with relaydomains?

**Comment by jaysee** [comment]
Yes `relaydomains_recipientaccess`

**Comment by jaysee** [comment]
sorry, clicked on the wrong button :)

**Comment by tonioo** [comment]
@jaysee Have you fixed your database?

**Comment by jaysee** [comment]
sorry, wasn't available last time.

No, i don't know how to fix it ?... is there a way to apply one by on the patches ?

**Comment by tonioo** [comment]
@jaysee I think you should order a support ticket from Modoboa's website (https://modoboa.org/fr/professional-services/)
