### ISSUE TITLE
Matrix integration

### ISSUE THREAD

**Issue by sim6** [modoboa/modoboa#1459]
Firstly, thanks for your work.

Please, could you add an integration for matrix server (i.e. synapse) with a web client (i.e riot) to modoboa.

Thanks again.

**Comment by Toniob** [comment]
Hi,
What do you mean exactly by that ? Matrix is a lot of things. What features do you want exactly ?
Thanks

**Comment by almereyda** [comment]
Indeed, this is not immediately understandeably and probably out of scope for an email distribution.

Are you asking for a Matrix - Email integration instead? Then have a look at https://github.com/kamax-io/matrix-appservice-email

**Comment by sim6** [comment]
I'm sorry for the delay.
I'm thinking in an intergration like the radicale one.
Thanks anyway.
