### ISSUE TITLE
Feature: Change the time of MX Checks

### ISSUE THREAD

**Issue by haeihaeihaei** [modoboa/modoboa#1460]
Hi, would it be possible to add a choice to how often the MX Checks run? Just a box or something where you can write a number in minutes or hours.

Thanks

**Comment by kryskool** [comment]
Hi @haeihaeihaei 

The MX check is defined on a crontab  [documentation](http://modoboa.readthedocs.io/en/latest/manual_installation/modoboa.html?highlight=cron#cron-jobs), you can adjust it

It's global for the instance, 

regards,

**Comment by haeihaeihaei** [comment]
@kryskool thanks buddy, then you can resolve this :)
