### ISSUE TITLE
[dkim] Check if the key is still in the storage directory

### ISSUE THREAD

**Issue by Toniob** [modoboa/modoboa#1474]
# Steps to reproduce
Delete one .pem key file in the directory where are stored the dkim keys.

# Current behavior
Key is not saved again. You have to update the database manually to put an empty string in the dkim_private_key_path field.

# Expected behavior
The job maange_dkim_keys should check if the key is still in the directory and recreate it if needed. I have not tested, but I think it is the same behavior if you just change the directory. Current keys are not recreated in the new one.

**Comment by tonioo** [comment]
Finally, I added a button to let users regenerate their DKIM keys.
