### ISSUE TITLE
SQLite syntax error with sql-sender-login map

### ISSUE THREAD

**Issue by evaryont** [modoboa/modoboa#1476]
# Impacted versions

* Modoboa: 1.10.4
* installer used: No, wrapping around calling modoboa-admin.py with Ansible
* Webserver: Nginx

Stock generated maps ran `manage.py generate_postfix_maps` results in this error when someone attempts to log in:

    Apr 24 04:31:35 postman.aether.earth postfix/proxymap[9896]: fatal: dict_sqlite_lookup: /etc/postfix/maps/sql-sender-login-map.cf: SQL prepare failed: near "(": syntax error?

Contents of file:

```
# This file was generated on April 23, 2018, 5:26 a.m. by running:
# manage.py generate_postfix_maps --destdir /etc/postfix/maps --force-overwrite
# DO NOT EDIT!
dbpath = /var/local/modoboa/db.sqlite
query = (SELECT email FROM core_user WHERE email='%s' AND is_active=1) UNION (SELECT mb.address || '@' || dom.name FROM admin_mailbox mb INNER JOIN admin_senderaddress sad ON sad.mailbox_id=mb.id INNER JOIN admin_domain dom ON dom.id=mb.domain_id WHERE sad.address='%s') UNION (SELECT mb.address || '@' || dom.name FROM admin_mailbox mb INNER JOIN modoboa_admin_aliasrecipient alr ON alr.r_mailbox_id=mb.id INNER JOIN admin_domain dom ON dom.id=mb.domain_id INNER JOIN admin_alias al ON alr.alias_id=al.id WHERE al.enabled=1 AND al.address='%s')
```

**Comment by tonioo** [comment]
@evaryont Looks like SQLite does not like parenthesis. Can you try to remove them from the query?
