### ISSUE TITLE
Installation Failure (Installer and manual)

### ISSUE THREAD

**Issue by striderr** [modoboa/modoboa#1485]
# Impacted versions
* Modoboa: 1.10
* installer used: Yes/No Both

# Steps to reproduce
Deployed Deb 9, Ubuntu 18 (LXC containers)
Used git installer on both server instances.
Installer had problems but completed
Used debug switch, saw a few issues.
1. Postgres had the wrong password and didn't start
2. opendkim failed to start
3. Said django-filter 1.0.4 was going to be used but some module needed 1.1.10.  1.1.10 was available in pip and thus a compatibility issue.

Installer finished, website didn't work.  Error log for the site threw an error "backports cvs not found", this isn't the exact wordage.  I manually installed backports.cvs from pip which didn't fix the issue.

I tried the manual installation, documentation needs work, feels partly completed.  Installation didn't work and here are the last few lines of the error message.

  File "/usr/local/lib/python2.7/dist-packages/modoboa/urls.py", line 31, in <module>
    url("admin/", include("modoboa.admin.urls", namespace="admin")),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/modoboa/admin/urls.py", line 10, in <module>
    from .views import (
  File "/usr/local/lib/python2.7/dist-packages/modoboa/admin/views/export.py", line 22, in <module>
    from backports import csv
ImportError: No module named backports

['/usr/bin/python', u'manage.py', u'set_default_site', 'mail'] failed, check your configuration

# Current behavior
Doesn't install, installer has errors.
# Expected behavior
Installs with no errors and works out of the box.

# Video/Screenshot link (optional)

**Comment by powerfischi** [comment]
I'm having the exact same issue. Error message is basically identical. I'm using python virtualenv. Installed packages are as follows:

Package | Version
------- | -------
asn1crypto | 0.24.0
bcrypt | 3.1.4
certifi | 2018.4.16
cffi | 1.11.5
chardet | 3.0.4
click | 6.7
coreapi | 2.3.3
coreapi-cli | 1.0.6
coreschema | 0.0.4
cryptography | 2.2.2
dj-database-url | 0.5.0
Django | 1.11.13
django-braces | 1.11.0
django-ckeditor | 5.2.2
django-reversion | 2.0.12
django-subcommand2 | 0.1.1
django-xforwardedfor-middleware | 2.0
djangorestframework | 3.7.3
dnspython | 1.15.0
enum34 | 1.1.6
feedparser | 5.2.1
futures | 3.2.0
gevent | 1.2.2
greenlet | 0.4.13
idna | 2.6
ipaddress | 1.0.22
itypes | 1.1.0
Jinja2 | 2.10
jsonfield | 2.0.2
LEPL | 5.1.3
lxml | 4.2.1
MarkupSafe | 1.0
modoboa | 1.10.4
modoboa-admin | 1.1.2
modoboa-admin-limits | 1.0.2
modoboa-admin-relaydomains | 1.1.0
modoboa-dmarc | 1.1.0
modoboa-postfix-autoreply | 1.4.1
modoboa-stats | 1.4.0
mysqlclient | 1.3.12
passlib | 1.7.1
pip | 10.0.1
pkg-resources | 0.0.0
progressbar | 2.3
progressbar33 | 2.4
py-dateutil | 2.2
pycparser | 2.18
pytz | 2018.4
requests | 2.18.4
requests-file | 1.4.3
rfc6266 | 0.0.4
rrdtool | 0.1.14
setuptools | 39.1.0
six | 1.11.0
tldextract | 2.2.0
uritemplate | 3.0.0
urllib3 | 1.22
wheel | 0.31.0

**Comment by powerfischi** [comment]
Forgot to mention my OS.

$ lsb_release -d
Description:    Debian GNU/Linux 9.4 (stretch)

**Comment by striderr** [comment]
Took a break and tried the installer on Ubuntu 18.04

Ran the installer with debug several times and worked my way through some of the issues.

1. Ensure your hostname = a FQDN otherwise the installer has errors
2. I installed amavis before running the installer but this might not be required
3. Deleted postgresql database before re-installation by using this command "sudo -u postgres psql" and "DROP DATABASE <database_name>;
4. I needed to install the following before installation
`apt-get install libdbd-pg-perl`

I forgot how many times I ran the installer but I made a little programs each time.

Eventually the installer finished and looked good.

I ran into the following to fix errors from uwsgi.

`/srv/modoboa/env/bin/activate`
`pip install django-filter==1.1.0`
`pip install backports.csv`

Turned debug=true in settings.py

Got this error

ProgrammingError at /dashboard/

relation "core_localconfig" does not exist
LINE 1: ..."site_id", "core_localconfig"."api_versions" FROM "core_loca...


So I ran this as per solution I found https://groups.google.com/forum/#!msg/modoboa-users/0lsGvjYwlxA/p6MWbI5kBgAJ

> source bin/env/activate
> cd instance
> python manage.py migrate
> python manage.py collectstatic

Website now loads and I got a login prompt.

I put in admin:password as this is the default and the error I get is the username/password doesn't match.

I search how to reset the admin manually and came across this link https://github.com/modoboa/modoboa/issues/905

The python code doesn't work, well I get a response that PK=1 doesn't exist.

I'm still questioning why there isn't a backup solution that allows me to reset the admin password easily in case I break the system.

This is the point I'm at, I can't log into the system as I don't have a username that works and I don't know how to reset it.  I don't know if the username/password are actually good but there is another issue preventing auth.  Or if the username and password even exists as I don't know if this is stored in the database, under what table or what.

**Comment by striderr** [comment]
As a follow up.

I've deployed Centos 7 using LXC containers.

After deployment, I configured the hostname, installed git and nano.

Downloaded the installer into the /opt/ directory.

Ran the installer with debug switch.

Installer completed with more information compared to the deb experience.

Website works and was able to login using admin:password.

It appears there is something broken with deb and ubuntu installation wizard that needs to be addressed.  If anyone is dealing with this problem, I recommend using centos 7 as for me, the installer works out of the box.

**Comment by powerfischi** [comment]
When I install the following packages as stated above manual installation works if the --extensions switch is not specified:
`pip install django-filter==1.1.0`
`pip install backports.csv`

However, when using the --extensions switch or when trying to install extensions afterwards I get several errors depending on the extension that should be loaded.

e.g. for modoboa_admin:

```
Traceback (most recent call last):
  File "/srv/webapps/modoboa-prod/prod/prod/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/srv/webapps/modoboa-prod/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/srv/webapps/modoboa-prod/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/webapps/modoboa-prod/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/srv/webapps/modoboa-prod/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/webapps/modoboa-prod/lib/python2.7/site-packages/modoboa_admin/models/__init__.py", line 1, in <module>
    from .base import AdminObject
  File "/srv/webapps/modoboa-prod/lib/python2.7/site-packages/modoboa_admin/models/base.py", line 3, in <module>
    from modoboa.lib import events
ImportError: cannot import name events
```

or for modoboa_admin_relaydomains:

```
Traceback (most recent call last):
  File "/srv/webapps/modoboa-prod/prod/prod/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/srv/webapps/modoboa-prod/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/srv/webapps/modoboa-prod/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/webapps/modoboa-prod/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/srv/webapps/modoboa-prod/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/webapps/modoboa-prod/lib/python2.7/site-packages/modoboa_admin_relaydomains/models.py", line 9, in <module>
    from modoboa.lib import parameters
ImportError: cannot import name parameters
```

```
# ls /srv/webapps/modoboa-prod/lib/python2.7/site-packages/modoboa/lib/
api_client.py     cryptutils.pyc   fields.py       __init__.pyc    migrations       singleton.py   test_utils.pyc
api_client.pyc    db_utils.py      fields.pyc      ldap_utils.py   paginator.py     singleton.pyc  u2u_decode.py
authbackends.py   db_utils.pyc     form_utils.py   ldap_utils.pyc  paginator.pyc    sysutils.py    u2u_decode.pyc
authbackends.pyc  email_utils.py   form_utils.pyc  listing.py      permissions.py   sysutils.pyc   validators.py
connections.py    email_utils.pyc  imap_utf7.py    listing.pyc     permissions.pyc  templatetags   validators.pyc
connections.pyc   exceptions.py    imap_utf7.pyc   middleware.py   signals.py       tests          web_utils.py
cryptutils.py     exceptions.pyc   __init__.py     middleware.pyc  signals.pyc      test_utils.py  web_utils.pyc
```

No `events` and no `parameters`

**Comment by striderr** [comment]
I did some testing and ran into a few more issues.

admin login worked, created a domain and added a simple user.

Logged into the user account, all tabs except webmail worked.

First error after clicking webmail was IMAP connection error.  I don't think dovecot was starting.

Second error was something about the IMAP reaching the EOF.  I think this was related to uwsgi having a problem finding a socket that wasn't being created.

I wasn't able to logout, the server timed out.  I wasn't able to login again.

Ran the installer over top.

This seemed to fixed things and now my test user can use webmail, things seem to be working and I can logout without causing a timeout.

Current error I'm getting in the admin panel is the DKIM path is highlighted red with an error message that openssl wasn't found, please make sure it's installed.  It is installed on the base system, unsure if openssl needs to be installed in the virtualenv.

I haven't tried to send email yet, sync with imap or anything else.

**Comment by tonioo** [comment]
Guys, this issue is a mess. You're talking about different errors.
@powerfischi Are you trying to upgrade an existing modoboa installation?
@striderr Was it a fresh install?

**Comment by striderr** [comment]
Fresh installs.

I only used LXC containers using the ubuntu 18, debian 9 or centos 7 images.


On May 9, 2018, at 4:43 AM, Antoine Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


Guys, this issue is a mess. You're talking about different errors.
@powerfischi<https://github.com/powerfischi> Are you trying to upgrade an existing modoboa installation?
@striderr<https://github.com/striderr> Was it a fresh install?

**Comment by tonioo** [comment]
@striderr With an up-to-date installer copy?

**Comment by xGruntx** [comment]
@tonioo If git clone https://github.com/modoboa/modoboa-installer is up-to-date then yes .

`from backports import csv
ImportError: No module named backports` same on fresh 9.4 Debian ( VPS from DigitalO )

**Comment by striderr** [comment]
Yes I used the updated installer.


On May 9, 2018, at 10:14 AM, xGruntx <notifications@github.com<mailto:notifications@github.com>> wrote:


@tonioo<https://github.com/tonioo> If git clone https://github.com/modoboa/modoboa-installer is up-to-date then yes .

from backports import csv ImportError: No module named backports same on fresh 9.4 Debian ( VPS from DigitalO )

**Comment by tonioo** [comment]
@xGruntx This issue [has been fixed](https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/scripts/modoboa.py#L88) with latest versions of the installer but requires to remove any previously downloaded binary package from pypi. To do that on a regular install:
```shell
> rm -r /srv/modoboa/env
> rm -r /srv/modoboa/.cache/pip
```

**Comment by powerfischi** [comment]
@tonioo I'm trying a fresh install with a fresh virtualenv.

**Comment by tonioo** [comment]
@powerfischi And your installer copy is up-to-date?

**Comment by powerfischi** [comment]
@tonioo I'm doing a manual installation because all mailserver components are already in place and configured.

**Comment by tonioo** [comment]
@powerfischi Looking at your logs, you're using deprecated modoboa packages (ie. modoboa-admin-* packages). Why did you install them?

**Comment by powerfischi** [comment]
@tonioo Maybe because I did't know better... :) I will uninstall them an try again.

**Comment by tonioo** [comment]
@powerfischi @striderr any news?

**Comment by striderr** [comment]
I’ve stopped pursuing this for the time being.
