### ISSUE TITLE
Adding relay domains silently fails

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa#1489]
# Impacted versions

* Modoboa: 1.10.4
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

Add a new relay domain via the Domains tab.

# Current behavior

After clicking Submit in the modal it remains open, but silently fails.

# Expected behavior

- The UI responds with a visible error.

OR

- The domain is added.

# Links

- [:link: DEBUG log](https://gist.github.com/almereyda/282ffc7d254289d5a0a9f95b3dff5ab9)
- This is a reoccurence of #1450, which also contains a workaround.

**Comment by tonioo** [comment]
@almereyda Unfortunately this is a different issue. As a workaround, you can create a regular domain and then convert it to a relay domain, it should work.

**Comment by almereyda** [comment]
Yes, this is what @y0va suggested in the closed issue #1450. I opened a new one, so the issue becomes visible again.
