### ISSUE TITLE
Split-horizon DNS and MX/DNSBL check invalid

### ISSUE THREAD

**Issue by AmazingBeu** [modoboa/modoboa#1492]
# Issue :

If Modoboa is behind a firewall/router with NAT and have split-horizon DNS, the private IP address is used for checks.

# Solution : 

Possibility to specify a DNS servers for checks or use public API

**Comment by tonioo** [comment]
@AmazingBeu Can't you simply play with your local /etc/resolv.conf file?

**Comment by AmazingBeu** [comment]
@tonioo I can't because i have some other services hosted in the same plateform (monitoring, ldap, backups... ).

**Comment by tonioo** [comment]
@AmazingBeu When you talk about split-horizon DNS, you mean MX records are resolved to private IP addresses in your environment?

**Comment by AmazingBeu** [comment]
Yes, and this IP is used for DNSBL and MX checks

![dnsblcheck](https://user-images.githubusercontent.com/26152831/40175650-1f5c6fc0-59d9-11e8-8b2e-fa8581515fd3.PNG)
