### ISSUE TITLE
Issues with creating a Calendar and Syncing all Modoboa Services to a client mail application 

### ISSUE THREAD

**Issue by Jayne3** [modoboa/modoboa#1493]
Hello,

Is anyone having this same problem? Or is it just a configuration issue.

Thanks

# Impacted versions

* Modoboa: X.X.x
* installer used: Yes/No ?
* Webserver: Nginx/Apache

# Steps to reproduce

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@Jayne3 Can you give more information?

**Comment by Jayne3** [comment]
I installed Modoboa, created a domain in it, and can access all the services from the web portal but when it comes to having all services on a client like my desktop, laptop and mobile, I’ll only receive the mail and notes. The calendar and address book is not available. I am trying to configure all the services using the Apple Mail Suite, Exchange option (mail,calendar, addressbook, notes, etc), then it say your user cannot be verified so I go to the other option which is add a mail account then is connects with mail and notes.

Thanks.

**Comment by tonka-truck** [comment]
Hi Jayne & Antoine,

I'm new to Modoboa and I'm likewise having the same problems.  I've also tried to create a calendar on the online demo and this also fails.

I'm installing 1.10.5 (also tried the patched version of 1.10.4) on Ubuntu 18.04.  On error that I noticed during the install was that an old version of Django was installed and the installer flagged this.  Still haven't tried a fresh install with installing Django before hand.

Ta

**Comment by Jayne3** [comment]
It may have something to do with the Radicale config or rights file, I’m still looking for some information.

**Comment by Jayne3** [comment]
I checked the Ngnix log and found out it was trying to connect then say an Exchange ActivSync Software (EAS) issue, then found Z-Push may fix the issue but not sure.

**Comment by tonioo** [comment]
@Jayne3 any news?

**Comment by Phenex1978** [comment]
@tonioo Hello, same problem here, fresh install with LE, and I am not able to create a calendar on the admin session. I can give you an SSH access to the server if you want to check

**Comment by tonioo** [comment]
@Phenex1978 The admin user is a bit special since it does not have a mailbox by default. Calendars are linked to mailboxes so you need a regular user (ie.  with a mailbox).
