### ISSUE TITLE
GUI Not Working

### ISSUE THREAD

**Issue by macuser913** [modoboa/modoboa#1497]
# Impacted versions

* Modoboa: 1.10.5
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
-Using DigitalOcean clean install (new droplet) of CentOS 7.5 x64
-Install git (sudo yum install git)
-Install modoboa per installation instructions

# Current behavior
See screenshots. Nothing is really working.
Cannot add users or domains. Cannot change admin settings.

![window 2018-05-27 at 21 25 36](https://user-images.githubusercontent.com/16932800/40589370-b05d6146-61f4-11e8-8649-766a24f6ca7d.png)

![window 2018-05-27 at 21 25 52](https://user-images.githubusercontent.com/16932800/40589364-a1f523e6-61f4-11e8-8672-bd7165ebe90e.png)

**Comment by csmk** [comment]
You need to give more information than that. Did you checked Nginx's error/access logs?

**Comment by macuser913** [comment]
No, but in any case everything works well in Ubuntu 14.04 so I'm just going to use that and close this error.
