### ISSUE TITLE
Mail traffic is empty

### ISSUE THREAD

**Issue by niko-lay** [modoboa/modoboa#1498]
# Impacted versions

* Modoboa: 1.10.5
* installer used: Yes
* Webserver: Nginx
* OS:   Ubuntu 16.04.4 LTS x64 4.4.0-124-generic

I have setup modoboa with installer and now I'm using it for small domain. This domain process about 10-15 emails per day, send or recieve. But mail taffic page is empty. At the same time Accounts page show correct graph.
I tried  to run this command from root `/srv/modoboa/env/bin/python /srv/modoboa/manage.py logparser && /srv/modoboa/env/bin/python /srv/modoboa/manage.py update_statistics` but no changes.
Any idea why this happens?

# Video/Screenshot link (optional)
![firefox_2018-06-01_19-56-38](https://user-images.githubusercontent.com/5228230/40853297-3fa177ae-65d6-11e8-94aa-7df38d8d7d61.png)

**Comment by tonioo** [comment]
@niko-lay Do you see any error when you run the logparser command?

**Comment by niko-lay** [comment]
@tonioo 
I see exit code not 0, but no errors in console
```
[root@serv] ~# /srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py logparser ; echo $?
1
[root@serv] ~#
```

**Comment by niko-lay** [comment]
I have found the cause of the error
```
/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py logparser --debug
[Errno 2] No such file or directory: '/var/log/modoboa.log'
```
Look like it was not created by installer.  I created this file, but it remain empty. 
Now I have another question, where should I specify `modoboa.log` as a log file?

**Comment by tonioo** [comment]
@niko-lay The script parses mail logs (generated by postfix). They are generally available in the /var/log/mail.log file (or /var/log/maillog). Check which path is the right one for your system, then make sure the user which runs the script has read permission on this file.

**Comment by niko-lay** [comment]
@tonioo thnaks for information, I just added symlink  modoboa.log -> mail.log and stats appeared in web interface. Possibly, this is an installer bug, I will check on clear vm.

**Comment by tonioo** [comment]
@niko-lay Any news?

**Comment by niko-lay** [comment]
@tonioo checked today with new installer - statistics works fine. But file `/var/log/modoboa.log` not exists. Looks like cronjob using different file, maybe it `/var/log/mail.log`
I guess, in my case errors caused by incorrect update

**Comment by tonioo** [comment]
There is no /var/log/modoboa.log file, all logs are written to /var/log/mail.log file by default. I think you have changed the corresponding setting in the web panel. Look at Modoboa > Parameters > Graphical statistics and fix the value if it's wrong.

**Comment by hugohamelcom** [comment]
I have the same issue.

Modoboa: 2.2.4
Installer used: Yes
Webserver: Nginx
OS: Debian 12

"sudo /var/log/mail" returns:
`sudo: /var/log/mail: command not found`

"/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py logparser --debug" returns: 
`Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 22, in <module>
    main()
  File "/srv/modoboa/instance/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/modoboa/env/lib/python3.11/site-packages/modoboa/maillog/management/commands/logparser.py", line 641, in handle
    if not self.can_start():
           ^^^^^^^^^^^^^^^^
  File "/srv/modoboa/env/lib/python3.11/site-packages/modoboa/maillog/management/commands/logparser.py", line 636, in can_start
    with open(pidfile, "w") as fp:
         ^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/var/run/modoboa_logparser.pid'`

**Comment by tonioo** [comment]
@hugohamelcom you have on permission issue. Make sure it is run by root user.
And /var/log/mail.log is a file so you can't execute it, you need to use cat or similar to check its content

**Comment by hugohamelcom** [comment]
Good catch! There's actually no mail.log:
`sudo ls /var/log/
alternatives.log  btmp    dpkg.log  fail2ban.log  fontconfig.log  lastlog      nginx    razor   redis  supervisor  wtmp
apt               clamav  exim4     faillog       journal         letsencrypt  private  README  runit  uwsgi`

Also, "sudo /srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py logparser --debug" returns: 
`/srv/modoboa/env/lib/python3.11/site-packages/modoboa/maillog/management/commands/logparser.py:97: FutureWarning: Possible nested set at position 29
  self._regex = {k: re.compile(v) for k, v in self._regex.items()}
[Errno 2] No such file or directory: '/var/log/mail.log'`

I'm using a root user (not root directly), does it matter? I've used this user to install modoboa with sudo.

**Comment by tonioo** [comment]
Check if rsyslog is installed on your server

**Comment by hugohamelcom** [comment]
It is not:
`dpkg -l | grep rsyslog

systemctl status rsyslog
Unit rsyslog.service could not be found.`

**Comment by tonioo** [comment]
Then install it please

**Comment by hugohamelcom** [comment]
Done! 
`sudo systemctl status rsyslog
● rsyslog.service - System Logging Service
     Loaded: loaded (/lib/systemd/system/rsyslog.service; enabled; preset: enabled)
     Active: active (running) since Wed 2024-06-12 13:25:26 CEST; 5s ago
TriggeredBy: ● syslog.socket`

**Comment by hugohamelcom** [comment]
Installing rsyslog have resolved the issue. Thank you :)
