### ISSUE TITLE
dkim keys not generating

### ISSUE THREAD

**Issue by Rustypredator** [modoboa/modoboa#1500]
# Impacted versions

* Modoboa: 1.10.5
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
install, add domain, enable dkim key generation

# Current behavior
cronjob is executed correctly, but no keys are being generated in the directory. also the output in the webinterface is just an error message

# Expected behavior
to generate a (domain.com).pem file in /var/lib/dkim

# Video/Screenshot link (optional)
[web-output](https://rusty.info/dkim-rinfo.png)
[cron](https://rusty.info/Screenshot_20180604_182724.png)

**Comment by tonioo** [comment]
@Rustypredator Looks like a permission issue. What are the permissions of the /var/lib/dkim folder? Which user runs the cron command?
