### ISSUE TITLE
504 error time out when exporting more than 30 thousand identities

### ISSUE THREAD

**Issue by augustodv** [modoboa/modoboa#1501]
# Impacted versions

* Modoboa: 1.10.5
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
create more than 30k identities
# Current behavior
at the moment of exporting the accounts already created, 35834, the page generates time out after a short time throwing error 504
# Expected behavior
can exprort all identities 
# Video/Screenshot link (optional)
![image](https://user-images.githubusercontent.com/39961339/40987266-851375c2-68be-11e8-9284-954df66987f1.png)
![image](https://user-images.githubusercontent.com/39961339/40987318-9f73db3c-68be-11e8-8a14-9db6f9cf0fea.png)

**Comment by augustodv** [comment]
sorry for my english. i speak spanish.

**Comment by tonioo** [comment]
Indeed, the web export is not appropriated in your case... What don't you try the command line version?

**Comment by augustodv** [comment]
sorry but can not find, what would the command to export by command line?

**Comment by augustodv** [comment]
excelent!!!   i use this command    /srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py modo export identities >> indentidades.csv

Thanks!!!!
