### ISSUE TITLE
All emails are stored in the inbox when the redirect is activated to another e-mail account

### ISSUE THREAD

**Issue by ktsmokolyuk** [modoboa/modoboa#1502]
# Impacted versions

* Modoboa: 1.10.5
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
All emails are stored in the inbox when the redirect is activated to another e-mail account 

Keep local copies button is empty

# Current behavior
all emails are saved in the local inbox

# Expected behavior

Mail should not be retained when redirecting is active

# Video/Screenshot link (optional)

![image](https://user-images.githubusercontent.com/26760678/41046547-48db541c-69b3-11e8-9950-11134f249baf.png)

**Comment by tonioo** [comment]
Duplicates #1356
