### ISSUE TITLE
API not working - /api/v1 - page does not exist.

### ISSUE THREAD

**Issue by pilotdns** [modoboa/modoboa#1503]
# Impacted versions

* Modoboa: 1.10.5

* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Fresh install of modoboa - when you attempt to go to /docs/api it states Internal error has occured, even on the demo site you have online.  When you try to go to /api/v1 even with it enabled, it states 

Sorry
The requested page does not exist.

# Current behavior
/api/v1 shows:

Sorry
The requested page does not exist.

# Expected behavior
API and /docs should function correctly.

**Comment by pruje** [comment]
/api/v1 path does not exists, you have to reach the /api/v1/accounts/ or /api/v1/domains/ for example.
For docs, go on /docs/api, it should work.

**Comment by tonioo** [comment]
@pilotdns Issue has been fixed and will require to upgrade to modoboa-radicale plugin to 1.3.4. (demo is alreadly up to date and working)
