### ISSUE TITLE
Changing a username makes the account unusable

### ISSUE THREAD

**Issue by figassis** [modoboa/modoboa#1504]
# Impacted versions

* Modoboa: 1.8.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Change a user's name
Try to login as new user

# Current behavior
User is no longer able to login with new or old username

# Expected behavior
User is no longer able to login with new or old username

The cause of the issue is that when changing a username, modoboa does not also change the email field in the core_user table, nor does it change the email directory pointing to the old username. The user has the new username, but their mailbox cannot be found.

**Comment by tonioo** [comment]
@figassis I suggest you to upgrade to the latest modoboa version, this issue should be fixed.
