### ISSUE TITLE
Installer failing after update from idna to 2.7

### ISSUE THREAD

**Issue by Noaphiel** [modoboa/modoboa#1505]
# Impacted versions

Modoboa: recent
installer used: Yes

# Steps to reproduce

running the installer on a clean system

# Current behavior

idna v2.7 got released yesterday. Installer is collecting the new version:
`Collecting idna>=2.1 (from cryptography->modoboa)
  Downloading https://files.pythonhosted.org/packages/65/c4/80f97e9c9628f3cac9b98bfca0402ede54e0563b56482e3e6e45c43c4935/idna-2.7.tar.gz (172kB)`

requests 2.18.4 relies on idna being <2.7 and >=2.5
`requests 2.18.4 has requirement idna<2.7,>=2.5, but you'll have idna 2.7 which is incompatible.`

result of the whole story is that lxml is not installed properly (though i'm not sure, if that is error is occuring because of the idna incompatibility):
`Running setup.py install for lxml ... error`

EDIT: it seems the lxml-error is independent to the idna compatibility issue above. It is most likely caused by insufficient memory of a Raspberry Pi. So I'm not sure anymore if the idna incompatibility with requests is affecting the install at all.

# Expected behavior

no error occurrence at lxml install

**Comment by tonioo** [comment]
@Noaphiel Looks like a temporary issue. Feel free to reopen it if the problem persists.
