### ISSUE TITLE
default nginx page on http, http 400 error when connecting to https

### ISSUE THREAD

**Issue by honorablejudgegman** [modoboa/modoboa#1506]
# Latest

* Modoboa: 1.10.5
* installer used: Yes
* Webserver: Nginx

### I don't even know right now. An Admin panel of some sorts somewhere?

# 
![capture](https://user-images.githubusercontent.com/6770821/41322171-da75da52-6ea7-11e8-89c3-4164a03cc865.PNG)

**Comment by tonioo** [comment]
@honorablejudgegman I see you're trying to access modoboa using an IP address, which won't work. You need to use the address printed by the installer at the end of the process (and make sure DNS is configured properly).

**Comment by tonioo** [comment]
@honorablejudgegman any news?
