### ISSUE TITLE
DKIM keys are not being generated

### ISSUE THREAD

**Issue by telnet23** [modoboa/modoboa#1507]
# Impacted versions
* Modoboa: **1.10.5**
* installer used: **Yes**/No ?
* Webserver: **Nginx**/Apache

# Steps to reproduce
Navigate to the _Domains_ tab
Click the _Add_ button
Enter a domain name
Check _Enable DKIM signing_
Enter key selector: _default_ 
Select key length: _4096_
Click the _Next_ button
Click the _Submit_ button

Navigate to the _Domains_ tab
Click on the newly created domain name

# Current behavior
DKIM key has not been generated
```
$ ls -l /etc/dkimkeys/
total 4
-rw-r--r-- 1 root root 664 Jun 30  2015 README.PrivateKeys
```
# Expected behavior
DKIM key should be generated

# Video/Screenshot link (optional)
![image](https://user-images.githubusercontent.com/3433012/41798247-eda3c6bc-763a-11e8-8a62-9c239908ec98.png)
![image](https://user-images.githubusercontent.com/3433012/41798095-5bed00f8-763a-11e8-9303-8b8c22f0f097.png)

**Comment by tonioo** [comment]
The generation of DKIM keys is not synchronous, it is done by a dedicated cron job so it can take a few minutes before you can see it in the web interface. If you still don't see your key, make sure the folder you configured has good permissions (ie. the user which runs the cron job must has write permission on the folder)

**Comment by makakken** [comment]
maybe it's worth to state out that the dkim-key is not presented on the Modal where you can check the "Enable DKIN signing" - Option. it's shown in the overviewpage of the domain:

![bildschirmfoto 2018-07-11 um 12 15 34](https://user-images.githubusercontent.com/10586572/42565843-eb4962cc-8504-11e8-8c68-7cc11cbf6177.jpg)

**Comment by makakken** [comment]
`sudo service cron restart` can do the job, if you have the newest version of the crontab-file /etc/cron.d/letsencrypt (there has to be a empty line at the end)

**Comment by telnet23** [comment]
Thanks for pointing out that DKIM keys are not generated synchronously, @tonioo. Perhaps the "Not generated" message should be changed to something more specific to alert users that DKIM keys take several minutes to be generated.

**Comment by tonioo** [comment]
@telnet23 Indeed. Does it work now?

**Comment by telnet23** [comment]
Yes, thank you @tonioo.

**Comment by movahhedi** [comment]
After 12 hours it didn't generate automatically. So I ran this (with SUDO) and it worked:
```
sudo /srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py modo manage_dkim_keys
```
Got it from [the cronjobs` docs](https://modoboa.readthedocs.io/en/latest/manual_installation/modoboa.html#cron-jobs)
