### ISSUE TITLE
Creating a calendar leads to HTTP 500 in API call

### ISSUE THREAD

**Issue by sr-it1** [modoboa/modoboa#1511]
# Impacted versions

* Modoboa: 1.10.5
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
After clicking on "Calendar" and then on "+ New calendar" nothing happens. The nginx access logfile only shows
[...] "POST /api/v1/user-calendars/ HTTP/1.1" 500 [...]
There is nothing in the error.log

A HTTPS request to /radicale/.web shows "Radicale works!"

Any hints on this?

What I didn't find was the URL to access the calendar and contacts from an external client, such as an iphone (CalDAV / CardDAV) directly.

# Current behavior
Calendar is not created.

# Expected behavior
Calendar is created

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
Which user did you use?

**Comment by sr-it1** [comment]
I checked both: a SuperAdmin and a SimpleUser - it is the same API call and an HTTP 500 as well

**Comment by tonioo** [comment]
Actually it won't work with the default admin user because it has no mailbox, need to add something about this.
It should work with a simple user, unless you choose the "self signed certificate" option at installation time. You need a valid certificate.

**Comment by sr-it1** [comment]
It was the default admin created at installation time. The SimpleUser was created afterwards.

I chose the "self signed certifiate", but I just switched to a "normal" valid SSL certificate. I already updated the postfix, dovecot, nginx references. I did not find any cert ref in /etc/radicale/config, these were commented out, neither in /etc/supervisor/conf.d/radicale.conf.

Did I miss a location?

**Comment by sr-it1** [comment]
It was the default admin created at installation time. The SimpleUser was created afterwards.

I chose the "self signed certifiate", but I just switched to a "normal" valid SSL certificate. I already updated the postfix, dovecot, nginx references. I did not find any cert ref in /etc/radicale/config, these were commented out, neither in /etc/supervisor/conf.d/radicale.conf.

Did I miss a location?

**Comment by sr-it1** [comment]
I just did a complete reinstall of the server. I used the self signed cert again, but updated the cert and key files to the offical cert/key.

It is not possible to create a calendar - neither as superadmin nor as simpleuser.

**Comment by tonioo** [comment]
@sr-it1 Do you have any trace? Would be easier to debug...

**Comment by Salamek** [comment]
@tonioo I have same problem this i found in uwsgi log

```
Thu Jul 26 04:41:55 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /api/v1/user-calendars/ (ip 188.175.***.***) !!!
Thu Jul 26 04:41:55 2018 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 296] during POST /api/v1/user-calendars/ (188.175.***.***)
IOError: write error
```
nginx.log
```
m, client: 188.175.128.247, server: mail.nemec.eu, request: "POST /api/v1/user-calendars/ HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket", host: "mail.nemec.eu", referrer: "https://mail.nemec.eu/calendars/"
2018/07/26 04:48:44 [crit] 24688#24688: *788 SSL_do_handshake() failed (SSL: error:1417D18C:SSL routines:tls_process_client_hello:version too low) while SSL handshaking, client: 208.93.153.179, server: 0.0.0.0:443
```

**Comment by Salamek** [comment]
@tonioo solved for me... i had bad IP in `/etc/hosts` for mail DNS...

**Comment by sr-it1** [comment]
After a second complete reinstall, it works now, even for the admin user!

It is an self signed certificate during installation and is switched to a "normal valid SSL certificate" afterwards. The admin user is updated to have a normal mailbox as well and can also have a calender.

It seems that this issue is connected to a browser cache issue. Using another browser and/or clearing FireFox cache worked. Maybe this caused the primary issue, that a radicale calendar could not be created.

Is there an plan to save the contact to radicale also, that these could be used in cardav sync as well as the calendar?

**Comment by tonioo** [comment]
@sr-it1 Enabling carddav for contacts is something planed but I wonder if it could be sponsored.
