### ISSUE TITLE
RoundCube password plugin for Modoboa

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#1513]
Hello!

I created a Modoboa driver for RoundCube Password plugin. The driver use the Modoboa API and token to communicate.

Tested with RoundCube 1.3.x.

If you like or find a problem, let me know.

I will publish it later in roundcube git repository.

Code is located in PR directory: #1512

**Comment by stefaweb** [comment]
Plugin accepted and migrated to Roundcube Master.
https://github.com/roundcube/roundcubemail/pull/6361#event-1823280335

**Comment by tonioo** [comment]
@stefaweb great :)
So, can I close this issue and the related PR?

**Comment by stefaweb** [comment]
Yes, I could.

**Comment by lmfrazao** [comment]
Is this plugin for roundcube workin on latest modoboa version and roundcube ?

thank you.
