### ISSUE TITLE
Repeatedly shows the same active user in "Active users" page

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#1516]
# Impacted versions

* Modoboa: 1.10.5
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

Log using admin account and click on Modoboa Menu. 

# Current behavior

Repeatedly shows the same active user in list.

# Expected behavior

Only one entry.

![sc](https://user-images.githubusercontent.com/12907102/42261013-e78fc926-7f66-11e8-8339-d5b652dd5d7b.png)

**Comment by tonioo** [comment]
What is strange is that every session has the same opening date... Are you using more than one browser?

**Comment by stefaweb** [comment]
Hi!

I tried again. Only one browser/session opened. Same result.

![sc](https://user-images.githubusercontent.com/12907102/42586809-35574f12-8539-11e8-99cc-99f5c2f7fed9.png)

**Comment by tonioo** [comment]
@stefaweb Do you manually disconnect from Modoboa? This view actually scans opened sessions to find active users... Maybe I could display only one line per user.

**Comment by stefaweb** [comment]
Hi!

I tried.

login with admin -> disconnect -> login again -> modoboa -> Information

Same result.
