### ISSUE TITLE
Can't send mail with an attachment containing non-ascii characters in the file name

### ISSUE THREAD

**Issue by lefta** [modoboa/modoboa#1518]
# Impacted versions

* Modoboa: 1.10.5
* Installer used: No
* Python version: 3.5
* Webserver: Nginx

# Steps to reproduce

Send a mail with an attachment containing non-ascii characters in the filename from the webmail. There is no problem with filenames containing only ascii characters and other mail clients (tested with GMail Android).

# Current behavior

Mail sending fails with error code 500 and contents : 

```
"'bytes' object has no attribute 'encode'"
```

# Expected behavior

Mail sent successfully :smile: 

# Additional details

I **really** need it to be working, but this is not a problem to fix it myself. How can I install a local (not pip) version, if possible not having to build a full mail stack so I can start to hack the code ? Would `git clone` be enough ? How would I install plugins in this case ? (I'm especially thinking about the webmail plugin, as it seems to be the cause of the breakage)

**Comment by tonioo** [comment]
@lefta Please provide a full stack trace.

**Comment by lefta** [comment]
I would like to, but I could not get one. I tried to activate debug mode and check the answer body, but still no backtrace. How may I get one ? I'm using uwsgi if this is relevant. (sorry, I'm new to Modoboa and python servers)

**Comment by tonioo** [comment]
Have you reloaded uwsgi?

**Comment by lefta** [comment]
Yes I did

**Comment by tonioo** [comment]
@lefta yes please.

**Comment by lefta** [comment]
Done: modoboa/modoboa-webmail#165
