### ISSUE TITLE
It's can't use letsencrypt if web server change port.

### ISSUE THREAD

**Issue by akong77** [modoboa/modoboa#1519]
# Impacted versions

* Modoboa: 1.10.5
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce
I change installer.cfg to letsencrypt.I also change modoboa.conf.tpl with 80 port to 82 port and 443 port to 8443 port.Then I run "./run.py mydomain".It's can run to finish.But nginx can't start.If I change installer.cfg to self-signed and use 82 port and 8443 port.The nginx will running.Could letsencrypt not support change web server port?

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
The LE script is running using the standalone mode, ie. it does not use nginx so it should work, unless the 80/443 ports are already used. Can you provide the output of the installer using the --debug option?

**Comment by akong77** [comment]
I know what's problem.Because letsencrypt need upload file to web server.And letsencrypt only upload to 80 port web server.So it's will direct auth http://mail.domain.tld/.well-known/acme-challenge/<random code>.But the path it's not my modoboa server.This is my another web server.How to fix it?

**Comment by tonioo** [comment]
That's not a modoboa issue. I suggest you add a redirect rule to the web server running on port 80 so requests sent to http://mail.domain.tld/.well-known/acme-challenge/random_code are redirected to the right server.
