### ISSUE TITLE
Could change default web panel url?

### ISSUE THREAD

**Issue by akong77** [modoboa/modoboa#1520]
# Impacted versions

* Modoboa: 1.10.5
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce
When I install modoboa.It's will use mail.domain.tld to web panel url.Could I change this url name?If I want use panel.domain.tld.Thanks a lot.

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
Look at the README file: https://github.com/modoboa/modoboa-installer/#change-the-generated-hostname.
