### ISSUE TITLE
It's can't remove messages when I release quarantine message.

### ISSUE THREAD

**Issue by akong77** [modoboa/modoboa#1521]
# Impacted versions

* Modoboa: 1.10.5
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce
I have set "Remove released messages" to yes and apply.But when I use admin account to release quarantine message.The messages always in quarantine.How to fix it? 

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
The removal is not instantaneous. A cron job is executed every night to actually remove messages. You can try to run it manually to check if it works (look at the /etc/cron.d/modoboa file)
