### ISSUE TITLE
Problems Delete Accounts

### ISSUE THREAD

**Issue by carbans** [modoboa/modoboa#1522]
# Impacted versions

* Modoboa: 1.10.5
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce
I deleted a domain, and then I couldn't delete the accounts. The panel returns Internal Error. I check modoboa log but It doesn't put anything about this, all seems okey.
Anyone can help me ?

**Comment by tonioo** [comment]
@carbans Set DEBUG to True inside settings.py, reload uwsgi and open a javascript debugger to inspect the server response, you should get more information.
