### ISSUE TITLE
Wish: Could direct release message when I mark non-spam?

### ISSUE THREAD

**Issue by akong77** [modoboa/modoboa#1523]
# Impacted versions

* Modoboa: 1.10.5
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce
Could direct release message when I mark non-spam?Thanks a lot.

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
Could you please move this request to the right repo? (https://github.com/modoboa/modoboa-amavis)
