### ISSUE TITLE
How to mark spam mail if modoboa is set relay domain?

### ISSUE THREAD

**Issue by akong77** [modoboa/modoboa#1525]
# Impacted versions

* Modoboa: 1.10.5
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce
I set modoboa relay my domain to my mail server.I recevied spam mail from my mail server and want mark spam to modoboa.How to do it? 

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
You can use dovecot [antispam plugin](https://wiki2.dovecot.org/Plugins/Antispam) to do that (with spamassassin spamc client).

**Comment by akong77** [comment]
I mean if user use mail client like microsoft outlook and use pop3 get mail.If user get spam mail.How to mark spam?

**Comment by akong77** [comment]
Could let user send spam mail to specific account.modoboa can cron to learn it account all mail.I know spamassassin can to do it.

**Comment by tonioo** [comment]
Indeed, that's a possible workaround. I guess that's something you can setup on your own?

**Comment by akong77** [comment]
I can create spam account on my mail server.All user can send spam mail to this account.The modoboa can get all spam mail to learn.Could possible to do it?

**Comment by tonioo** [comment]
Using dovecot antispam plugin, you could automate the learning.

**Comment by akong77** [comment]
So,Could I let modoboa learn spam mail?

**Comment by tonioo** [comment]
Yes you could.

**Comment by akong77** [comment]
dovecot antispam plugin install to modoboa?

**Comment by tonioo** [comment]
No, you need to install it manually.
