### ISSUE TITLE
ex post random password generator

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa#1532]
# Impacted versions

* Modoboa: 1.10.4
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

1. Create an identity and fill a manual password. Don't check the random password generator. No PDF donwload button will be shown.
2. Edit the identity and check the random password generator to overwrite the password anew.

# Current behavior

- No PDF download button for retrieving the new random password is being shown, not even after reloading the whole view.

# Expected behavior

- A PDF download button appears next to the edit one and it is possible to retrieve a newly generated ex post random password.

**Comment by tonioo** [comment]
@almereyda You have a setting to control that. Check the Modoboa > Parameters > PDF tab.

**Comment by almereyda** [comment]
I need to check this. For the moment the settings pane does not seem to help to display the download button for accounts that didn't have a random password upon creation.

**Comment by tonioo** [comment]
The setting you're looking for is "Generate documents only at account creation". Set it to "No".

**Comment by tonioo** [comment]
@almereyda Any news here? Can I close the issue?

**Comment by almereyda** [comment]
I've found the setting, please excuse the delay.
