### ISSUE TITLE
What's upgrade modoboa step?

### ISSUE THREAD

**Issue by akong77** [modoboa/modoboa#1533]
# Impacted versions

* Modoboa: 1.10.5
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce
I follow this url to upgrade modoboa.
http://modoboa.readthedocs.io/en/latest/upgrade.html

> source /srv/modoboa/env/bin/activate
pip install modoboa==1.10.6
cd /srv/modoboa/instance
python manage.py migrate
python manage.py collectstatic
python manage.py check --deploy

I found modoboa always is 1.10.5.
I reinstall modoboa-installer.It's will change to 1.10.6.
Could I miss any step?

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
You forgot to reload uwsgi.
