### ISSUE TITLE
Wish: modoboa installable as a snap

### ISSUE THREAD

**Issue by esbeeb** [modoboa/modoboa#1534]
# Impacted versions

* Modoboa: 1.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
See end of https://github.com/modoboa/modoboa/issues/1486
That issue should not be marked as "closed", IMHO.

# Expected behavior
A straightforward install, where I can reach the web management interfce, after successful exiting from command line installer.

# Current behavior
This "502 Bad Gateway" problem (after a fresh install) is still looming. Since modoboa depends on a sophisticated set of cutting-edge python libraries (and stogy, conservative, slow-moving distros like Debian will take years to nicely package up these libraries) please package all these meticulous, easily-broken dependancies in a "snap", along with all the many moving parts which make up modoboa.  

Debian, like many other distros, has snapd as a standard package (the current Debian 9 has snapd version 2.21-2+b1, please make a modoboa snap compatible with this version).

Huge compatibility across many Linux distros will be gained in this way.

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
Providing a snap can be done by the community but we don't have the time or the resource to do it, sorry.
