### ISSUE TITLE
LookupError: unknown encoding: cp-850

### ISSUE THREAD

**Issue by Viperoo** [modoboa/modoboa#1535]
# Impacted versions

* Modoboa: 1.10.6
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

1. Get some spam mail with encoding cp-850.
2. Go to quarantine
3. Click preview on e-mail
4. error

# Current behavior

>Sorry
An internal error occured.

# Expected behavior

Preview of the email with headers.

# Video/Screenshot link (optional)

[Sentry trace](https://sentry.azmi.pl/share/issue/9a980a520e82406c9073a6bfd64ae29b/)

**Comment by ericlingit** [comment]
`'cp-850'` was passed to `decode(encoding)` as an argument, but the function expects `'cp850'` (without the hyphen).

Interestingly, python accepts `'utf-8'` (with a hyphen) as a valid alias for `'utf_8'`, but somehow `'cp-850'` isn't a supported alias for `cp850`. [Source](https://docs.python.org/3/library/codecs.html#standard-encodings).
