### ISSUE TITLE
Bad smtp connection time

### ISSUE THREAD

**Issue by makakken** [modoboa/modoboa#1539]
# Impacted versions

* Modoboa: 1.10.6
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Install Modoboa on a cloud node and setup MX records in DNS, go to mxtoolbox.com and SMTP:xxx.xxx.xxx.190 test your mailservers ip
# Current behavior

  | SMTP Connection Time | 6.950 seconds - Warning on Connection time | More Info
-- | -- | -- | --
  | SMTP Transaction Time | 9.188 seconds - Not good! on Transaction Time

# Expected behavior
 No Warnings. A hint in Documentation for Installation Requirements would be nice too.
( 1cpu? 2gb ram? is that enough? i've doubled, but still have same problem)

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@makakken I'm not sure to understand what the problem is. Are you complaining about the connection time being too long?

**Comment by Toniob** [comment]
Hi,
The modoboa installer enables postscreen by default : http://www.postfix.org/POSTSCREEN_README.html .
It activates several features against bots, but with a cost of a small delay during the connection (which is not a problem, email being asynchronous).

If you want to get rid of the warning, just disable postscreen. But then, be prepared for dumb bots to spam your server. It's your choice.

**Comment by makakken** [comment]
@tonioo yes ;) i had some problems connecting from apple mail via smtp.
@Toniob Thanks for pointing that out. Maybe we could add this to documentation?

So, it's not a bug, it's a feature. good to know.
