### ISSUE TITLE
force DNS check?

### ISSUE THREAD

**Issue by JayBeRayBearGun** [modoboa/modoboa#1548]
Hi there,

In my domain list it say 'awaiting checks' under DNS status. How can I force a check? 

Cheers,
JBR

**Comment by JayBeRayBearGun** [comment]
Lemme answer my own question.

It is handled by a cron script. So running this script will force it at your behest :)

**Comment by tonioo** [comment]
@dougmey Have you checked /etc/cron.d/modoboa?
