### ISSUE TITLE
Webmail - add feature to display full headers of an email

### ISSUE THREAD

**Issue by InToSSH** [modoboa/modoboa#1552]
# Impacted versions

* Modoboa: 1.10.6
* Webmail: 1.4.4
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Open any mail in the Webmail app
# Current behavior
No button to display full headers of the mail.
# Expected behavior
It would be nice to add the possibility to display full headers of an email, same as in Quarantine tab.
Sometimes for debugging I would like to see full headers of an email in the Webmail. For example to debug the spam score. Thanks

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-webmail#173
