### ISSUE TITLE
Problems Delete Accounts

### ISSUE THREAD

**Issue by carbans** [modoboa/modoboa#1554]
# Impacted versions

* Modoboa: 1.10.6
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce
I created a domain, then we deleted the domain, but we forgot to delete the accounts, later we try to delete the accounts and we couldn't. We need to create the same accounts because when we sing in with this accounts appears a message that says "There aren't mailbox for this account"

 Looking the console of JavaScript we can see there are a call that returns 500 error and show this: 
```
Exception Type: AttributeError at /admin/accounts/568/delete/
Exception Value: 'NoneType' object has no attribute 'is_superuser'
```

# Expected behavior
We would like to delete the accounts and create the new ones

Can anybody help us?

**Comment by tonioo** [comment]
@carbans Can you describe the exact way to reproduce this bug please?

**Comment by carbans** [comment]
@tonioo I need to delete some accounts because we deleted the domain before, so when I try to delete the account this is what happens: 

`178.     if owner.is_superuser or owner.role != "Resellers":

Exception Type: AttributeError at /admin/accounts/564/delete/
Exception Value: 'NoneType' object has no attribute 'is_superuser'
Request information:
USER: admin
GET: No GET data
POST: No POST data
FILES: No FILES data
`

**Comment by tonioo** [comment]
@carbans Looks like you also deleted the super administrator who created the domain. Can you run the following command and try again:
```shell
python manage.py modo repair
```

**Comment by carbans** [comment]
Ooh good! It's works! Thanks a lot for your work!
