### ISSUE TITLE
upgrade advice

### ISSUE THREAD

**Issue by oconshaw** [modoboa/modoboa#1557]
# Impacted versions

* Modoboa: 1.8.2
* installer used: Yes/No ? YES
* Webserver: Nginx

I am on Modoboa 1.8.2.  I want to upgrade to the latest version (1.10.6), but honestly I am scared to death to take the plunge.  You have done a lot of work since 1.8.  What is the best/recommended upgrade path?  Any special gotchas or caveats?

Also running:

- Amavis: 1.1.3
- Contacts: 0.4.0
- DMARC tools: 1.0.0
- PDF credentials: 1.1.1
- Postfix autoreply: 1.2.1
- Radicale management: 1.1.0
- Sieve filters: 1.1.1
- Statistics: 1.2.1
- Webmail: 1.2.0

Thank you.

**Comment by branditodesign** [comment]
At least you're not on 1.5.3 like me :(

**Comment by tonioo** [comment]
The safest way to upgrade from an old version is to install every intermediate version and to follow the dedicated procedures available in the [documentation](https://modoboa.readthedocs.io/en/latest/upgrade.html#specific-instructions). BTW, I suggest you upgrade more often if you want to avoid such situations in the future.
You can also order an upgrade service from the (official website)[https://modoboa.org/en/professional-services/]
