### ISSUE TITLE
Wishlist: delete all account/alias from domain

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#1561]
Hello!

Sorry if this exist but I've not found.

Can we have a feature to delete all accounts and aliases from a domain in one step?

![capture d ecran 2018-08-31 a 09 59 07](https://user-images.githubusercontent.com/12907102/44900476-f4014b00-ad04-11e8-809d-dec6e11c3684.png)

**Comment by tonioo** [comment]
@stefaweb Go Modoboa > Parameters > Administration and set the "Automatic account removal" setting to yes.

**Comment by stefaweb** [comment]
Very sorry. Thanks.

**Comment by stefaweb** [comment]
Hi!

I'm back on this.

Seems messages do not correspond to the "action". But all accounts and aliases are well removed when we delete the domain.

I can open a issue for that if needed.

![capture d ecran 2018-09-03 a 16 55 45](https://user-images.githubusercontent.com/12907102/44993560-4e1b3e00-af9b-11e8-82e6-a700a19cbb81.png)

When `Yes` is selected, we still got the same message.

![capture d ecran 2018-09-03 a 16 56 09](https://user-images.githubusercontent.com/12907102/44993562-4e1b3e00-af9b-11e8-99fb-cb9f226b6715.png)
