### ISSUE TITLE
DKIM key file world readable

### ISSUE THREAD

**Issue by inpos** [modoboa/modoboa#1563]
# Impacted versions

* Modoboa: 1.10.6
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Create new domain with DKIM signing option checked
# Current behavior
When try to send message all fields reset. The following entries appear in the log:
```
Sep  2 09:56:10 mail opendkim[1806]: 2: key data is not secure: /var/lib/dkim/somedomain.com.pem can be read or written by other users
Sep  2 09:56:10 mail opendkim[1806]: 4E8422055A: error loading key '2'
```
# Expected behavior
Message go out.

**Comment by inpos** [comment]
Workaround is manual change file permissions:
```
chmod 640 /var/lib/dkim/somedomain.com.pem
```

**Comment by tonioo** [comment]
See also https://github.com/modoboa/modoboa-installer/issues/214.
