### ISSUE TITLE
[MD5-CRYPT] imported password do not work.

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#1564]
# Impacted versions

* Modoboa: 1.10.6
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

Imported accounts with [MD5-CRYPT] don't work. The account is well created but login failed.

/var/log/mail.log:

`Sep  3 18:51:37 modoboa dovecot: auth-worker(25093): Error: sql(man@domain.tld,xx.xx.xx.xx,<ptTDWvp0eJ0+0qZC>): Invalid password in passdb: Not a valid MD5-CRYPT or PLAIN-MD5 password`

From imported cvs:

`account;man@domain.tldr;[MD5-CRYPT]c3af58603be288769bb31d980bb74abc;;;True;SimpleUsers;man@domain.tld;102
`

Am I wrong somewhere?

**Comment by stefaweb** [comment]
Found. Can't work when we use `[]` instead of `{}`

I close.

**Comment by stefaweb** [comment]
Hello!

I reopen this issue.

I corrected my export code to use brackets instead of quote but the problem is still here.

`account;man@domain.tldr;{MD5-CRYPT}c3af58603be288769bb31d980bb74abc;;;True;SimpleUsers;man@domain.tld;102`

The password was generated with the php md5() command.

**Comment by tonioo** [comment]
The format was indeed wrong. And you still have an issue since you selected the wrong scheme. If passwords were generated using the md5 php function then you should select MD5. FYI, this is a weak encryption mechanism and you should move to MD5-CRYPT which is far more secure.

**Comment by stefaweb** [comment]
Sorry but I don't understand, do you mean `{MD5}` ?

**Comment by tonioo** [comment]
And make sure the "Crypt passwords" checkbox is not checked.

**Comment by stefaweb** [comment]
"Crypt passwords" is not checked in import page.

**Comment by tonioo** [comment]
I remember MD5 passwords must be base64 encoded (dovecot requirement). Is it the case?

**Comment by stefaweb** [comment]
No, basic md5() without salt or base64 encoding.

**Comment by stefaweb** [comment]
I'll try later to base64 encode the md5 password. I'll you know.

**Comment by stefaweb** [comment]
I encoded the md5 password with base64. Still do not work.

**Comment by stefaweb** [comment]
Found.

I made an error when trying the connexion. I navigator autocomplete was not entering the right password.

It work with {MD5} and regular MD5 scheme. No need to base64 encode (does't work).

I close this time. Thanks.

ps: vacation api for modoboa. Any new?
