### ISSUE TITLE
error after first login 

### ISSUE THREAD

**Issue by CHazz** [modoboa/modoboa#1566]
hi  i have problem after install :

Request Method: | POST
-- | --
https://xxxxxxxxx/accounts/login/
1.11.15
AttributeError
'NoneType' object has no attribute 'parameters'
/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/parameters/tools.py in get_global_parameter, line 186
/usr/bin/uwsgi-core
2.7.12
['.',  '',  '/srv/modoboa/env/lib/python2.7',  '/srv/modoboa/env/lib/python2.7/plat-x86_64-linux-gnu',  '/srv/modoboa/env/lib/python2.7/lib-tk',  '/srv/modoboa/env/lib/python2.7/lib-old',  '/srv/modoboa/env/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/srv/modoboa/env/local/lib/python2.7/site-packages']
so, 8 Zář 2018 14:24:32 +0200

Environment:

Request Method: POST
Request URL: https://mail.xxxxxxx/accounts/login/

Django Version: 1.11.15
Python Version: 2.7.12
Installed Applications:
(u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.sessions',
 u'django.contrib.messages',
 u'django.contrib.sites',
 u'django.contrib.staticfiles',
 u'reversion',
 u'ckeditor',
 u'ckeditor_uploader',
 u'rest_framework',
 u'rest_framework.authtoken',
 u'modoboa',
 u'modoboa.core',
 u'modoboa.lib',
 u'modoboa.admin',
 u'modoboa.transport',
 u'modoboa.relaydomains',
 u'modoboa.limits',
 u'modoboa.parameters',
 u'modoboa_amavis',
 u'modoboa_pdfcredentials',
 u'modoboa_postfix_autoreply',
 u'modoboa_sievefilters',
 u'modoboa_stats',
 u'modoboa_webmail',
 u'modoboa_contacts',
 u'modoboa_radicale',
 'webpack_loader')
Installed Middleware:
(u'x_forwarded_for.middleware.XForwardedForMiddleware',
 u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'django.middleware.locale.LocaleMiddleware',
 u'django.middleware.clickjacking.XFrameOptionsMiddleware',
 u'modoboa.core.middleware.LocalConfigMiddleware',
 u'modoboa.lib.middleware.AjaxLoginRedirect',
 u'modoboa.lib.middleware.CommonExceptionCatcher',
 u'modoboa.lib.middleware.RequestCatcherMiddleware')

Traceback:

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/views/auth.py" in dologin
  34.                                 password=form.cleaned_data["password"])

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py" in authenticate
  70.             user = _authenticate_with_backend(backend, backend_path, request, credentials)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py" in _authenticate_with_backend
  116.     return backend.authenticate(*args, **credentials)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/contrib/auth/backends.py" in authenticate
  22.             UserModel().set_password(password)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/models.py" in set_password
  123.             self.password = self._crypt_password(raw_value)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/models.py" in _crypt_password
  103.             "password_scheme", raise_exception=False)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/parameters/tools.py" in get_global_parameter
  186.     return get_localconfig().parameters.get_value(name, app=app, **kwargs)

Exception Type: AttributeError at /accounts/login/
Exception Value: 'NoneType' object has no attribute 'parameters'

thanks for help

**Comment by CHazz** [comment]
after full reinstall same error

**Comment by tonioo** [comment]
@CHazz How did you install modoboa?

**Comment by CHazz** [comment]
with the installer does not report any error even in debug mode

**Comment by tonioo** [comment]
On which linux distribution?

**Comment by tonioo** [comment]
With default user or new one?

**Comment by CHazz** [comment]
new sudoer

**Comment by tonioo** [comment]
I'm talking about the modoboa user. I've tried a fresh install on a Ubuntu 16.04 VM and it works fine... I don't understand what's happening.

**Comment by CHazz** [comment]
hi, thank you very much, but I will not try again .. I reinstalled completely the server in the meantime and this is how it is solved .. now it is finally functional :) obviously it was some older configuration what the installer did not overwrite
