### ISSUE TITLE
IMAP Does not Work for just one user.

### ISSUE THREAD

**Issue by blackmlm** [modoboa/modoboa#1568]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
trying to login via modoboa web and using  Rainloop wit this one user and it fails

# Current behavior
IMAP not working for just one user, but POP is Working Fine.  And this issue is on only one DomainAdmin user.

Modoboa web returns 
Error: Connection to IMAP server failed: [Errno 113] No route to host

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@blackmlm I suggest you upgrade your installation, your issue might be fixed already.
