### ISSUE TITLE
Can't Create Calendar

### ISSUE THREAD

**Issue by pholphoj** [modoboa/modoboa#1569]
# Impacted versions
* Modoboa: 1.10.6
* installer used: Yes
* Webserver: Nginx

i install Modoboa on ubuntu 16.04LTS . from https://modoboa.readthedocs.io/en/latest/installation.html

mail is work!. but i can't create calendar. how i can do it?

i check  radicale from https://mail.mydoamin.com/radicale/.web     is work 
Radicale works!

![radicale_work](https://user-images.githubusercontent.com/19725469/45950692-1304ab80-c02b-11e8-9dbd-e28383b8f00c.JPG)

Thank you

**Comment by tonioo** [comment]
@pholphoj Could it be the same issue than https://github.com/modoboa/modoboa-radicale/issues/38?
