### ISSUE TITLE
No mail since upgrade

### ISSUE THREAD

**Issue by julienCozo** [modoboa/modoboa#1575]
# Impacted versions
1.10.7 with auto reply 1.5.0

* installer used: Yes ?
* Webserver: Nginx

# Steps to reproduce
Do the last upgrade

# Current behavior
faild to send and receive mail
# Expected behavior

# Video/Screenshot link (optional)

Oct  3 14:12:43  postfix/proxymap[8295]: warning: mysql query failed: Table 'modoboa.postfix_autoreply_transport' doesn't exist
Oct  3 14:12:43  postfix/trivial-rewrite[8296]: warning: proxy:mysql:/etc/postfix/sql-autoreplies-transport.cf lookup error for "*"
Oct  3 14:12:43  postfix/trivial-rewrite[8296]: warning: proxy:mysql:/etc/postfix/sql-autoreplies-transport.cf lookup error for "*"

...

NOQUEUE: reject: RCPT from localhost[127.0.0.1]: 451 4.3.0 <julien@xxxxx.xxxt>: Temporary lookup failure

**Comment by tonioo** [comment]
Please consult the online documentation: https://modoboa.readthedocs.io/en/latest/upgrade.html#modoboa-postfix-autoreply-1-5-0.

**Comment by julienCozo** [comment]
Arf how could i miss it !

Sorry for the noise Antoine, and thank you
