### ISSUE TITLE
New installation, admin password not working

### ISSUE THREAD

**Issue by fresH229a** [modoboa/modoboa#1581]
# Impacted versions

* Modoboa: latest version
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
After the final installation and inital login with admin:password (which worked good).
If I change the admin password afterwards, I am no longer able to login to the admin panel.

Error: Password or Username incorrect.

Is this known ?

**Comment by tonioo** [comment]
@fresH229a No it is not... Did you use any special char in the new password?

**Comment by fresH229a** [comment]
you mean only !,# etc?

**Comment by fresH229a** [comment]
Okay I found the issue.
The password with ! and # is working good, the problem was that I did not recognize that in the Username, the uppercases I had was automaticly lowerd.

it was not sys_Admin, it was sys_admin.... :(

**Comment by tonioo** [comment]
Indeed, modoboa forces lower case usernames.
