### ISSUE TITLE
Not able to send email to external addresses

### ISSUE THREAD

**Issue by jwhitewick** [modoboa/modoboa#1583]
# Impacted versions

* Modoboa: 1.10.7
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Send email to my external email such as a corporate, hotmail or gmail
# Current behavior
not able to send email to external account
# Expected behavior
not able to send email to external account
# Video/Screenshot link (optional)
1 06:13:56 whmtlmail01 postfix/qmgr[824]: F37E02226F1: from=<admin@mydomain.com>, size=1072, nrcpt=1 (queue active)
Oct 11 06:14:27 whmtlmail01 postfix/smtp[14127]: connect to mydomain-com.mail.protection.outlook.com[23.103.157.42]:25: Connection timed out
Oct 11 06:14:27 whmtlmail01 postfix/smtp[14127]: F37E02226F1: to=<jwhitewick@whitewickgroup.com>, relay=none, delay=490, delays=460/0.08/30/0, dsn=4.4.1, status=deferred (connect to mydomain-com.mail.protection.outlook.com[23.103.157.4$
Oct 11 06:15:48 whmtlmail01 dovecot: imap-login: Login: user=<noreply@mydomain.com>, method=PLAIN, rip=192.168.3.3, lip=172.16.1.8, mpid=14282, TLS, session=<Whnd5u1336bAqAMD>
Oct 11 06:18:15 whmtlmail01 postfix/pickup[823]: E0EEE2226FC: uid=111 from=<amavis>
Oct 11 06:18:15 whmtlmail01 postfix/cleanup[14553]: E0EEE2226FC: message-id=<20181011061814.E0EEE2226FC@mail.mydomain.com>
Oct 11 06:18:15 whmtlmail01 opendkim[5186]: E0EEE2226FC: no signing table match for 'root@mail.app.allunac.com'
Oct 11 06:18:15 whmtlmail01 opendkim[5186]: E0EEE2226FC: no signature data
Oct 11 06:18:15 whmtlmail01 postfix/qmgr[824]: E0EEE2226FC: from=<amavis@mydomain.com>, size=760, nrcpt=1 (queue active)
Oct 11 06:18:15 whmtlmail01 postfix/local[14561]: E0EEE2226FC: to=<amavis@mail.mydomain.com, orig_to=<amavis>, relay=local, delay=0.54, delays=0.41/0.06/0/0.07, dsn=2.0.0, status=sent (delivered to mailbox)
Oct 11 06:18:15 whmtlmail01 postfix/qmgr[824]: E0EEE2226FC: removed
Oct 11 06:18:56 whmtlmail01 postfix/qmgr[824]: 2D2642226B1: from=<jwhitewick@mydomain.com>, size=1367, nrcpt=1 (queue active)
Oct 11 06:19:06 whmtlmail01 dovecot: imap(noreply@mydomain.com): Disconnected for inactivity in=111 out=794
Oct 11 06:19:26 whmtlmail01 postfix/smtp[14592]: connect to mydomain-com.mail.protection.outlook.com[23.103.157.10]:25: Connection timed out
Oct 11 06:19:26 whmtlmail01 postfix/smtp[14592]: 2D2642226B1: to=<other@otheremail.com>, relay=none, delay=2360, delays=2329/0.05/31/0, dsn=4.4.1, status=deferred (connect to mydomain-com.mail.protection.outlook.com[23.103.157$
Oct 11 06:23:56 whmtlmail01 postfix/qmgr[824]: F37E02226F1: from=<admin@mydomain.com>, size=1072, nrcpt=1 (queue active)
Oct 11 06:23:56 whmtlmail01 postfix/qmgr[824]: CC2E62226E7: from=<noreply@mydomain.com>, size=3327, nrcpt=1 (queue active)
Oct 11 06:24:26 whmtlmail01 postfix/smtp[15241]: connect to msn-com.olc.protection.outlook.com[104.47.37.33]:25: Connection timed out

**Comment by Toniob** [comment]
Hi,
As you can see in your logs
```
Oct 11 06:14:27 whmtlmail01 postfix/smtp[14127]: connect to mydomain-com.mail.protection.outlook.com[23.103.157.42]:25: Connection timed out
Oct 11 06:19:26 whmtlmail01 postfix/smtp[14592]: connect to mydomain-com.mail.protection.outlook.com[23.103.157.10]:25: Connection timed out
```
your server can't contact the remote one. It's either a routing problem or a firewall issue in my opinion. So nothing related to modoboa.

**Comment by Toniob** [comment]
You don't have to open specific ports for modoboa. Of course you have to open postfix and dovecot ports.
The problem here is you can't connect to a remote server. It may be an issue with your firewall filtering outgoing packets, not incoming ones. Did you try to ping the remote addresses ?

**Comment by stefaweb** [comment]
Hi @jwhitewick 

Try:

```
ping mydomain-com.mail.protection.outlook.com
traceroute mydomain-com.mail.protection.outlook.com
telnet mydomain-com.mail.protection.outlook.com 25
```

A mail server generally need ports:  25, 587, 995 and 993.
