### ISSUE TITLE
unable to login when I change the default password scheme

### ISSUE THREAD

**Issue by jodumont** [modoboa/modoboa#1584]
Hi;

1st: thanks for your marvelous project; it's fit so much my expectation _(no docker, postgres, ...)_
2nd: it's more a curiously thing than an angry issue but...

I change the default password scheme right after the installation, before creating any domain, user, ...
then I made the domain and user

the user is/was able to connect to the modoboa interface but
the webmail was "broken" and it was impossible to connect via IMAP & SMTP
so to fix it I put back the SHA512 and reset the password than everything works fine.
so I presume the password scheme don't interact with dovecot and postfix.

# Impacted versions

* Modoboa: 1.10.7
* installer used: Yes
* Webserver: Nginx
* Fresh Debian9 from a netinstall with only ssh (nothing else (no basic tools, ...))

# Steps to reproduce
1. goto : https://mail.yourdomain.tld/core/#parameters/
2. change the **Default password scheme** for `bcrypt`
3. define a user
4. login as this user
5. try webmail

# Current behavior
I survive by putting back `SHA512`

# Expected behavior
being able to use **bcrypt** because it is offered and also because [this article](https://rietta.com/blog/2016/02/05/bcrypt-not-sha-for-passwords/)

**Comment by tonioo** [comment]
Looks like dovecot (< 2.3) relies on local libc to provide BCRYPT (see https://wiki.dovecot.org/Authentication/PasswordSchemes). Unfortunately, BCRYPT is not available on Debian 9 and it provides dovecot 2.2... (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=149452).
I think the only fix we can propose is to hide schemes that are not available on the local server. Then, we will propose new schemes.

**Comment by jodumont** [comment]
@Toniob yes yes I put it back to SHA512-CRYPT, the one by default
not SHA512 which -CRYPT was lost in the translation

@tonioo don't worry about it; as I said; I was more curious about it than anything else.
