### ISSUE TITLE
MX Records

### ISSUE THREAD

**Issue by RobbieBott** [modoboa/modoboa#1588]
# Impacted versions

* Modoboa: - 1.11.1
* installer used: Yes/No ? - Yes on fresh Ubuntu 18.04 droplet from DigitalOcean.
* Webserver: Nginx/Apache - Whatever Installer uses.

I received and email telling me my MX records aren't right. However I can send and receive emails. They go to spam a lot, however. How do I correct this spam issue and my MX and DKIM stuff? The DKIM that the system generates has quotes and spaces in it do all those going the DNS txt record?

The domain always says "awaiting checks".  How do I correct this?

<img width="828" alt="screen shot 2018-10-14 at 1 21 56 pm" src="https://user-images.githubusercontent.com/10303297/46920532-316c2000-cfb5-11e8-8da6-2310046050b5.png">

<img width="1055" alt="screen shot 2018-10-14 at 1 25 19 pm" src="https://user-images.githubusercontent.com/10303297/46920534-36c96a80-cfb5-11e8-9db2-ae6a0dfb8955.png">

<img width="1020" alt="screen shot 2018-10-14 at 1 30 47 pm" src="https://user-images.githubusercontent.com/10303297/46920544-64161880-cfb5-11e8-9ead-c62e028c446b.png">

**Comment by tonioo** [comment]
@RobbieBott ott I think you local name resolution is not well configured, your MX server should not resolve to 127.0.1.1.
