### ISSUE TITLE
Installer Variables

### ISSUE THREAD

**Issue by RobbieBott** [modoboa/modoboa#1589]
Where can I find a list of variables the installer uses? For example to upgrade an extension you need the Modoboa user.... which is what how are we to know the installer does that.. You also need to know the virtual path which is what? The installer set that, so how are we to know, by default the installer has to use defaults so what are they?

Also I have yet to find in the documentation that for automx to work you need to put an autodiscover record in your DNS. Also auto mx has a test tool which when run returns an automx not installed run apt install automx. Once installed you can then run the test with the command 
`automx-test user@example.com` 
You can see this document for more information about the autodiscover DNS records.
[https://github.com/sys4/automx/blob/master/INSTALL](url)

Note... I still have yet to get auto discover to function properly.. Can anyone offer any help with this?

Also on Digital Ocean droplets by default point the localhost IP to the hostname so for my fresh install server I had to manually change the localhost ip (127.0.1.1) to my external IP for the DNS checks to function properly. I use Webmin for this so I cannot tell you how to do it from command. Maybe someone can elaborate on how to do this.

**Comment by tonioo** [comment]
@RobbieBott Can you please avoid to open an issue talking about different subjects?
About variables, you can find them in the installer.cfg file that was generated during the first run.

**Comment by Toniob** [comment]
Hi @RobbieBott 
As you probably know, Modoboa is a free, open source, software. People are working on it on their spare time. They try to do their best for it to be a great mail manager (and even more). Your message seems really agressive. It's a good thing to say hi, or hello, and to ask something politely.
I really hope that next time, you'll think about this.
Thanks
