### ISSUE TITLE
Upgrade to 1.11.1 can't recivied mail.

### ISSUE THREAD

**Issue by akong77** [modoboa/modoboa#1591]
# Impacted versions

* Modoboa: 1.11.1
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce
I upgrade to 1.11.1 is show follow error

> Oct 16 14:10:08 mail postfix/proxymap[2193]: warning: pgsql query failed: fatal error from host 127.0.0.1: ERROR:  relation "postfix_autoreply_transport" does not exist?LINE 1: SELECT method FROM postfix_autoreply_transport WHERE domain=...?                           ^?
Oct 16 14:10:08 mail postfix/trivial-rewrite[2201]: warning: proxy:pgsql:/etc/postfix/sql-autoreplies-transport.cf lookup error for "*"
Oct 16 14:10:08 mail postfix/trivial-rewrite[2201]: warning: proxy:pgsql:/etc/postfix/sql-autoreplies-transport.cf lookup error for "*"
Oct 16 14:10:08 mail postfix/trivial-rewrite[2201]: warning: proxy:pgsql:/etc/postfix/sql-autoreplies-transport.cf lookup error for

What's this problem?

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
I guess you also updated the autoreply plugin but didn't consult the documentation: https://modoboa.readthedocs.io/en/latest/upgrade.html#modoboa-postfix-autoreply-1-5-0.

**Comment by akong77** [comment]
Yes,So I can't one time direct upgrade all package?

**Comment by tonioo** [comment]
No you can't. I you need something better, you can help and sponsor this feature: https://modoboa.org/en/projects/8/.
