### ISSUE TITLE
New warning message during modoboa upgrade

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#1592]
Hello!

During the upgrade to modoboa 1.11.1, contacts 0.7.2 and webmail 1.5.0, I got a new warning message.

```
(env) modoboa@mailhub:~/instance$ python manage.py check --deploy
System check identified some issues:

WARNINGS:
?: (security.W001) You do not have 'django.middleware.security.SecurityMiddleware' in your MIDDLEWARE so the SECURE_HSTS_SECONDS, SECURE_CONTENT_TYPE_NOSNIFF, SECURE_BROWSER_XSS_FILTER, and SECURE_SSL_REDIRECT settings will have no effect.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W016) You have 'django.middleware.csrf.CsrfViewMiddleware' in your MIDDLEWARE, but you have not set CSRF_COOKIE_SECURE to True. Using a secure-only CSRF cookie makes it more difficult for network traffic sniffers to steal the CSRF token.

System check identified 3 issues (1 silenced).
```

Previous upgrade was not printing these messages.

**Comment by Tibase** [comment]
Hello,

I have the same warnings messages after update from 1.10.6

**Comment by Schokobecher** [comment]
same here - 1.10. to 1.12.2

`(env) modoboa@mail:~/instance$ python2 manage.py check --deploy
System check identified some issues:

WARNINGS:
?: (modoboa-amavis.W001) AMAVIS_DEFAULT_DATABASE_ENCODING does not match the character encoding used by the Amavis database.
        HINT: Check your database character encoding and set/update AMAVIS_DEFAULT_DATABASE_ENCODING.
?: (security.W001) You do not have 'django.middleware.security.SecurityMiddleware' in your MIDDLEWARE so the SECURE_HSTS_SECONDS, SECURE_CONTENT_TYPE_NOSNIFF, SECURE_BROWSER_XSS_FILTER, and SECURE_SSL_REDIRECT settings will have no effect.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W016) You have 'django.middleware.csrf.CsrfViewMiddleware' in your MIDDLEWARE, but you have not set CSRF_COOKIE_SECURE to True. Using a secure-only CSRF cookie makes it more difficult for network traffic sniffers to steal the CSRF token.`

**Comment by tonioo** [comment]
I've just pushed a fix for security.W012 and security.W016.
More information about security.W001 can be found here: https://docs.djangoproject.com/en/1.11/ref/middleware/#module-django.middleware.security.
@Schokobecher About modoboa-amavis.W001, you must adjust your configuration.
