### ISSUE TITLE
use multiple domains for emails

### ISSUE THREAD

**Issue by lukasbasedow** [modoboa/modoboa#1593]
# Impacted versions

* Modoboa: 1.11.1
* installer used: Yes
* Webserver: Nginx

Hello, i setup the first domain, all nice and good. I added a second domain, and im stuck at
Awaiting checks. I cant check the domain with check_mx and also cant create email acounds with this domain. What i am during wrong?

**Comment by tonioo** [comment]
@lukasbasedow Have you tried to delete/recreate the domain?

**Comment by lukasbasedow** [comment]
yes, i think my problem is the dns config of the second domain, how have to look the second one, i dont find something in the docs :/

**Comment by tonioo** [comment]
#1621 should help you. It will be released soon.
