### ISSUE TITLE
Modoboa web server with subdirectory instead of subdomain.

### ISSUE THREAD

**Issue by koper89** [modoboa/modoboa#1602]
# Impacted versions

* Modoboa: 1.12.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
I cannot make web server to work as location instead of subdomain. Is there anyway to setup nginx to work with domain like:
https://example.com/mail instead of https://mail.example.com

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@koper89 Have you tried something like this: https://davidjb.com/blog/2013/04/serving-uwsgi-apps-on-a-sub-directory-with-nginx/ ?
