### ISSUE TITLE
OpenDKIM fails to start after server shutdown/reboot

### ISSUE THREAD

**Issue by qriouslad** [modoboa/modoboa#1609]
# Impacted versions
* Modoboa: 1.12.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
1. Shutdown and start, or restart VPS (KVM, Ubuntu 18.04). 
2. Check status of OpenDKIM with "service opendkim status"

# Current behavior
Shows the following status:

● opendkim.service - OpenDKIM DomainKeys Identified Mail (DKIM) Milter
   Loaded: loaded (/lib/systemd/system/opendkim.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-11-02 06:34:21 WIB; 2min 56s ago
     Docs: man:opendkim(8)
           man:opendkim.conf(5)
           man:opendkim-genkey(8)
           man:opendkim-genzone(8)
           man:opendkim-testadsp(8)
           man:opendkim-testkey
           http://www.opendkim.org/docs.html
  Process: 695 ExecStart=/usr/sbin/opendkim -x /etc/opendkim.conf (code=exited, status=78)

Nov 02 06:34:21 server.host.name systemd[1]: opendkim.service: Control process exited, code=exited status=78
Nov 02 06:34:21 server.host.name systemd[1]: opendkim.service: Failed with result 'exit-code'.
Nov 02 06:34:21 server.host.name systemd[1]: Failed to start OpenDKIM DomainKeys Identified Mail (DKIM) Milter.
Nov 02 06:34:21 server.host.name systemd[1]: opendkim.service: Service hold-off time over, scheduling restart.
Nov 02 06:34:21 server.host.name systemd[1]: opendkim.service: Scheduled restart job, restart counter is at 5.
Nov 02 06:34:21 server.host.name systemd[1]: Stopped OpenDKIM DomainKeys Identified Mail (DKIM) Milter.
Nov 02 06:34:21 server.host.name systemd[1]: opendkim.service: Start request repeated too quickly.
Nov 02 06:34:21 server.host.name systemd[1]: opendkim.service: Failed with result 'exit-code'.
Nov 02 06:34:21 server.host.name systemd[1]: Failed to start OpenDKIM DomainKeys Identified Mail (DKIM) Milter.

# After "service opendkim restart", service status is as follows

● opendkim.service - OpenDKIM DomainKeys Identified Mail (DKIM) Milter
   Loaded: loaded (/lib/systemd/system/opendkim.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-11-02 06:38:12 WIB; 6s ago
     Docs: man:opendkim(8)
           man:opendkim.conf(5)
           man:opendkim-genkey(8)
           man:opendkim-genzone(8)
           man:opendkim-testadsp(8)
           man:opendkim-testkey
           http://www.opendkim.org/docs.html
  Process: 2519 ExecStart=/usr/sbin/opendkim -x /etc/opendkim.conf (code=exited, status=0/SUCCESS)
 Main PID: 2524 (opendkim)
    Tasks: 6 (limit: 4915)
   CGroup: /system.slice/opendkim.service
           └─2524 /usr/sbin/opendkim -x /etc/opendkim.conf

Nov 02 06:38:11 server.host.name systemd[1]: Starting OpenDKIM DomainKeys Identified Mail (DKIM) Milter...
Nov 02 06:38:12 server.host.name systemd[1]: opendkim.service: Can't open PID file /var/run/opendkim/opendkim.pid (yet?) after start: No such file or directory
Nov 02 06:38:12 server.host.name opendkim[2524]: OpenDKIM Filter v2.11.0 starting (args: -x /etc/opendkim.conf)
Nov 02 06:38:12 server.host.name systemd[1]: Started OpenDKIM DomainKeys Identified Mail (DKIM) Milter.

# Expected behavior
Should start automagically, but I need to use "service opendkim restart". I've tried "sudo systemctl enable opendkim" to autostart the service to no avail.

# Outbound message not properly signed with DKIM
With OpenDKIM service not starting, outgoing mails are not getting proper DKIM signature. It's not detected by gmail or mail-tester.com, albeit showing up in https://mxtoolbox.com/dkim.aspx

**Comment by tonioo** [comment]
@qriouslad Do you have more logs to provide?

**Comment by qriouslad** [comment]
@tonioo Where should I look for more logs?

**Comment by tonioo** [comment]
/var/log/mail.log?
/var/log/messages?
/var/log/syslog?
Look for anything related to opendkim...

**Comment by demanl** [comment]
`Jan  1 20:06:35 mail2 systemd[1]: Reached target Login Prompts.
Jan  1 20:06:35 mail2 systemd[1]: opendkim.service: Service hold-off time over, scheduling restart.
Jan  1 20:06:35 mail2 systemd[1]: opendkim.service: Scheduled restart job, restart counter is at 5.
Jan  1 20:06:35 mail2 systemd[1]: Stopped OpenDKIM DomainKeys Identified Mail (DKIM) Milter.
Jan  1 20:06:35 mail2 systemd[1]: opendkim.service: Start request repeated too quickly.
Jan  1 20:06:35 mail2 systemd[1]: opendkim.service: Failed with result 'exit-code'.
Jan  1 20:06:35 mail2 systemd[1]: Failed to start OpenDKIM DomainKeys Identified Mail (DKIM) Milter.
Jan  1 20:06:35 mail2 systemd[1]: Started OpenBSD Secure Shell server.
`
Problem still occurring :(

**Comment by demanl** [comment]
More info...ubuntu 18.04 server....using mysql database engine...:)
`Jan  1 20:06:35 mail2 opendkim[815]: opendkim: /etc/opendkim.conf: dsn:mysql://opendkim:sV0NFTYx7medWk9M@127.0.0.1/modoboa/table=dkim?keycol=domain_name?datacol=id: dkimf_db_open(): Can't connect to MySQL server on '127.0.0.1' (111)
Jan  1 20:06:35 mail2 systemd[1]: opendkim.service: Control process exited, code=exited status=78
Jan  1 20:06:35 mail2 systemd[1]: opendkim.service: Failed with result 'exit-code'.
Jan  1 20:06:35 mail2 systemd[1]: opendkim.service: Service hold-off time over, scheduling restart.
Jan  1 20:06:35 mail2 systemd[1]: opendkim.service: Scheduled restart job, restart counter is at 5.
Jan  1 20:06:35 mail2 systemd[1]: opendkim.service: Start request repeated too quickly.
Jan  1 20:06:35 mail2 systemd[1]: opendkim.service: Failed with result 'exit-code'.
`
opendkim is trying to start before the mysql db is up and running :)

**Comment by tonioo** [comment]
@demanl Same problem exists with postgres: https://github.com/modoboa/modoboa-installer/pull/217. I'll look into it soon.

**Comment by slowaways** [comment]
I have this problem in CentOS 7

**Comment by lmfrazao** [comment]
same problem in CentoOS 7, after reboot needs to restart manually

**Comment by lmfrazao** [comment]
fix for CentOS7: 

/usr/lib/systemd/system/opendkim.service

change:
After=network.target nss-lookup.target syslog.target 
to:
After=network.target nss-lookup.target syslog.target mariadb.service
