### ISSUE TITLE
E-mail Storage Location

### ISSUE THREAD

**Issue by pappastech** [modoboa/modoboa#1610]
# Impacted versions

* Modoboa: 1.12.2
* installer used: Yes
* Webserver: Nginx

Could someone point me to the storage directory for e-mail with this setup? I'm testing and will need to migrate ~50 e-mail accounts from an existing e-mail server and need to figure out the best way to move the old e-mail over.

Thanks.

**Comment by pappastech** [comment]
Fair enough for the migration. However, in this case, I also want to store the e-mail on an NFS and mount it from the e-mail server; so I still need the mail storage location. Is it /srv/vmail?

**Comment by tonioo** [comment]
@pappastech Yes it is.

**Comment by marcoraven** [comment]
Could perhaps someone tell me HOW to synchronise with doveadm sync if we're talking about a modboa setup? 
Suppose I want to migrate only one mailbox - should I use -u or -m?
