### ISSUE TITLE
Webmail and port 25 problem

### ISSUE THREAD

**Issue by rj2010ism** [modoboa/modoboa#1611]
Having problem after installation 2-3 days after. all worked and all a sudden webmail not sending mail even giving errors and working after restart for a while. but still not sending messages just freeze. on client: outlook port 25 give error messages ill attach screenshots it was working before. the OS/Server wasn't touched just sitting till the error came..

![1](https://user-images.githubusercontent.com/44802856/48304698-68871000-e526-11e8-8a62-e179aedfed51.png)
![2](https://user-images.githubusercontent.com/44802856/48304699-68871000-e526-11e8-9a4a-e7577c182e44.png)
![3](https://user-images.githubusercontent.com/44802856/48304700-691fa680-e526-11e8-8a91-97657971e3f3.png)

**Comment by tonioo** [comment]
@rj2010ism Don't use port 25 for Outlook but port 587 and enable authentication. Check mail logs to find what's going wrong with the webmail.

**Comment by rj2010ism** [comment]
I also tried port 587 same message.
I checked port online if its open from outside my network its fine. Port is open but errors. But when i use my internal network 192.168.100.** it works fine with outlook port 25,587 works but it i use my static isp ip or my domain name its giving me errors.
On Nov 11, 2018, at 11:56 AM, Antoine Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:

@rj2010ism<https://github.com/rj2010ism> Don't use port 25 for Outlook but port 587 and enable authentication. Check mail logs to find what's going wrong with the webmail.

**Comment by tonioo** [comment]
Did you activate authentication in your email client?

**Comment by rj2010ism** [comment]
yes
________________________________

**Comment by tonioo** [comment]
@rj2010ism Can you check if Outlook is using "plain" authentication mechanism?

**Comment by rj2010ism** [comment]
Why is it so hard to get this to work? No proper steps online or guide. you solve one problem and another comes up. I was going to test this for a month to see how it works if its simple to use and maybe use it for a personal mail server. but i cant seem to get this to be stable. the port issue is solved. i replace my router and changed a few settings. now for some reason im getting a message after i login:

Sorry
An internal error occured.

Imagine that this is commercial and errors like this happens?

I'm running this from a virtual machine vmware 15. iv even tried reinstall but whats the point of trying to get something to work that doesn't want to work? at the moment i have the ( internal error occured. ) message. this thing isn't stable all i was looking for is a stable user friendly interface mail server that can use alias

**Comment by tonioo** [comment]
You said it, it's not a commercial product. We do our best to create an open source product simple to use (at least that's the goal we're trying to reach), with no commercial restrictions, on our free time. And it's the same about user support. Modoboa is used by a lot of people every day and it seems to work for them... We do our best to help but if it's not enough for you, you can try something else.
