### ISSUE TITLE
Nginx multiple domains

### ISSUE THREAD

**Issue by pappastech** [modoboa/modoboa#1613]
# Impacted versions

Modoboa: 1.12.2
installer used: Yes
Webserver: Nginx

# Steps to reproduce
N/A

# Current behavior
Admin panel is only available at the base domain. If I install modoboa using domain1.com, I can't simply redirect domain2.com to the same IP and have it bring up the admin interface because Nginx throws an error.

# Expected behavior
Can Nginx be configured to respond to domain1.com, domain2.com, domainn.com etc?

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
You also need to complete the ALLOWED_HOSTS variable inside settings.py to allow every hostname you want to support.

**Comment by pappastech** [comment]
This doesn't answer the original question, but I do appreciate the insight. If this isn't the correct forum, I'm happy to take the question elsewhere; I figured however, that someone else running modoboa might know or want to know the answer to this.

Thanks.

**Comment by tonioo** [comment]
@pappastech you just need to add aliases to nginx configuration or copy vhost configuration to create a new one, in addition to what I said earlier.
