### ISSUE TITLE
OpenDKIM question

### ISSUE THREAD

**Issue by bizit524** [modoboa/modoboa#1615]
I merely had a question
In the settings of the individual Domains it has an option of "Enable DKIM signing" 
I would like to enable this but I dont know what "Key Selector" is in reference to. There is no explanation on the page and of the documentation found here: https://modoboa.readthedocs.io/en/latest/manual_installation/opendkim.html?highlight=selector

I cant find anything. What do I actually input there. Do I need need to install OpenDKIM? by the documentation it appears it would be installed I just need to configure it to sign/check messages

* Modoboa: Latest as of yesterday 13/11/18
* installer used: Yes ?
* Webserver: Nginx

**Comment by tonioo** [comment]
@bizit524 The selector is just a way to identify the key (since a same domain can have multiple keys). Leave the default value or set something like 'default' or 'modoboa', as you like.

**Comment by bizit524** [comment]
Ah ok Thanks :)
