### ISSUE TITLE
How to clean verify_cache.db?

### ISSUE THREAD

**Issue by akong77** [modoboa/modoboa#1623]
# Impacted versions

* Modoboa: 1.12.2
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce
How to clean verify_cache.db?

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@akong77 If you are in a hurry, just remove the file, postfix will recreate it. Otherwise, the documentation will help you: http://www.postfix.org/ADDRESS_VERIFICATION_README.html#dirty_secret.
