### ISSUE TITLE
Admin Login in Webinterface Gateway Timeout

### ISSUE THREAD

**Issue by Dogy007** [modoboa/modoboa#1624]
* Modoboa: Version not sure (1 Month old installation)
* installer used: Yes
* Webserver: Nginx

# Current behavior
Login in Webinterface works with all users

Login in Webinterface doesn't work with admin. Modoboa responds with Gateway Timeout 

In /var/log/nginx mail.domain.ch-error.log

2018/11/24 00:14:40 [error] 508#508: *698 upstream timed out (110: Connection timed out) while reading response header from upstream, client: <192.X.X.X>, server: mail.Domain.ch, request: "GET /dashboard/ HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket", host: "mail.Domain.ch", referrer: "https://mail.Domain.ch/accounts/login/?next=/"

If the password is wrong we get a "Username and Password do not match"
(Keep in mind, it works with users...)

It did work for a Month, and suddenly stopped working without configuration changes

Mails do get delivered still and can be accessed with a mail client

**Comment by Dogy007** [comment]
I have found the Problem

To get a Succesfull admin login  Modoboa needs to have a connection to 94.23.45.181 on Port 443

Otherwise the interface times out.

Im wondering if it is ineed intended?

**Comment by Dogy007** [comment]
Check your mail please

**Comment by Dogy007** [comment]
The soultion was allow modoboa connection to it's api. Otherwise logins in the admin user portal wasn't possible

**Comment by johnmays4545** [comment]
How do we allow modoboa connection to it's api? What config file do I need to modify

**Comment by johnmays4545** [comment]
Solution for this issue on my server was to disable Firewall blocking countries outside the USA
