### ISSUE TITLE
502 Bad Gateway after update

### ISSUE THREAD

**Issue by CooperBarrett** [modoboa/modoboa#1625]
# Impacted versions

* Modoboa: 1.12.1
* installer used: Yes ?
* Webserver: Nginx

# Steps to reproduce
Problem after the update to modoboa 1.12.1 and some plugins
# Current behavior
*Sorry, I use an automatic translation*

502 Bad Gateway when I want to access mail.xxxx.fr
Logs Nginx : 
```
2018/11/26 21:52:41 [error] 1725#1725: *9 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /dashboard/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr", referrer: "https://mail.XXXXX.fr/core/"
2018/11/26 22:02:46 [error] 1728#1728: *242 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /dashboard/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr", referrer: "https://mail.XXXXX.fr/dashboard/"
2018/11/26 22:12:48 [error] 1728#1728: *279 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /dashboard/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr", referrer: "https://mail.XXXXX.fr/dashboard/"
2018/11/26 22:22:50 [error] 1727#1727: *331 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /dashboard/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr", referrer: "https://mail.XXXXX.fr/dashboard/"
2018/11/26 22:33:15 [error] 1703#1703: *49 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /dashboard/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr", referrer: "https://mail.XXXXX.fr/dashboard/"
2018/11/26 22:42:08 [error] 9559#9559: *19 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /dashboard/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr"
2018/11/26 22:42:09 [error] 9559#9559: *19 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /favicon.ico HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr"
2018/11/26 22:42:16 [error] 9559#9559: *19 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET / HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr"
2018/11/26 22:42:17 [error] 9559#9559: *19 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /favicon.ico HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr"
2018/11/26 22:43:17 [error] 9559#9559: *33 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /dashboard/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr", referrer: "https://mail.XXXXX.fr/dashboard/"
2018/11/26 22:53:18 [error] 9557#9557: *103 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /dashboard/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr", referrer: "https://mail.XXXXX.fr/dashboard/"
2018/11/26 23:02:46 [error] 13697#13697: *31 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET / HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr"
2018/11/26 23:02:47 [error] 13697#13697: *31 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /favicon.ico HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr"
2018/11/26 23:03:20 [error] 13697#13697: *34 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /dashboard/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr", referrer: "https://mail.XXXXX.fr/dashboard/"
2018/11/26 23:11:35 [error] 1592#1592: *4 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET / HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr"
2018/11/26 23:11:36 [error] 1592#1592: *4 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /favicon.ico HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr"
2018/11/26 23:13:22 [error] 1592#1592: *8 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /dashboard/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr", referrer: "https://mail.XXXXX.fr/dashboard/"
2018/11/26 23:23:23 [error] 1592#1592: *15 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /dashboard/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr", referrer: "https://mail.XXXXX.fr/dashboard/"
2018/11/26 23:29:11 [error] 1592#1592: *21 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET / HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr"
2018/11/26 23:29:12 [error] 1592#1592: *21 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /favicon.ico HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr"
2018/11/26 23:31:05 [error] 1592#1592: *21 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /accounts/login/?next=/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr"
2018/11/26 23:31:06 [error] 1592#1592: *21 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /favicon.ico HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr"
2018/11/26 23:31:09 [error] 1592#1592: *21 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /accounts/login/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr"
2018/11/26 23:31:11 [error] 1592#1592: *21 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /favicon.ico HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr"
2018/11/26 23:33:25 [error] 1592#1592: *30 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /dashboard/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr", referrer: "https://mail.XXXXX.fr/dashboard/"
2018/11/26 23:43:27 [error] 1592#1592: *37 upstream prematurely closed connection while reading response header from upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /dashboard/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr", referrer: "https://mail.XXXXX.fr/dashboard/"
```
the problem seems to be coming from uwsgi.
the "issue" #1607  to the same problem but I didn't succeed in doing the same thing. I simply installed uwsgi with `pip install`.
# Expected behavior
Have access to my mailbox and send/receive mails

**Comment by tonioo** [comment]
@CooperBarrett I don't think it is the same issue. There was a segmentation fault in #1607, it is not the case here... Can you try with an older uwsgi version, not the latest one?

**Comment by CooperBarrett** [comment]
Sorry for the delay in responding

I have version `2.0.14-debian`, the latest version being `2.0.17.1`. 
Do I need to test an older version at `2.0.14-debian` ?

How to uninstall the installed version with the script ?
I tried `pip uninstall uwsgi` but I have the answer:
```
Cannot uninstall requirement uwsgi, not installed
```
Thank you for your help.

**Comment by tonioo** [comment]
@CooperBarrett Maybe you can try to install the latest uwsgi from sources? (as to guy in the other issue did) https://uwsgi-docs.readthedocs.io/en/latest/Install.html#installing-from-source

**Comment by CooperBarrett** [comment]
Thank you, 
however I don't understand, I uninstall `uwsgi` with 
```
sudo apt uwsgi remove
```
Everything's okay, but if I do 
```
uwsgi --version
```
I still have an answer `2.0.14-debian`, the message persists despite a `purge`.
How to completely uninstall `uwsgi`? 

thank you

P.S : Yes, I am a noob...

**Comment by tonioo** [comment]
Those commands should uninstall uwsgi debian package... Have you tried to install it using another way?

**Comment by CooperBarrett** [comment]
J'ai finalement réussi à désinstaller mon ancienne version de uwsgi.
J'ai installer ma nouvelle version via 
```
pip install https://projects.unbit.it/downloads/uwsgi-lts.tar.gz
```
`uwsgi --version`me donne bien `2.0.17.1`

Mais cette fois ci, j'ai ceci dans les logs (/var/log/nginx/mail.XXXXX.fr-error.log): 
```
2018/12/07 07:23:09 [crit] 1359#1359: *35081 connect() to unix:/run/uwsgi/app/modoboa_instance/socket failed (2: No such file or directory) while connecting to upstream, client: XX.XXX.XXX.XX, server: mail.XXXXX.fr, request: "GET /dashboard/ HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.XXXXX.fr", referrer: "https://mail.XXXXX.fr/dashboard/"
```
Il ne me trouve pas `uwsgi`...

**Comment by tonioo** [comment]
Does this path exist:
/run/uwsgi/app/modoboa_instance/sock
And can you check if you still have configuration files in /etc/uwsgi?

**Comment by CooperBarrett** [comment]
I only have 2 folders in `/run/uwsgi`.
`apps-available` and `apps-enabled`.

**Comment by tonioo** [comment]
Those are files or folders ?

**Comment by CooperBarrett** [comment]
Sorry, I was wrong. These folders are in `/etc/uwsgi`
I don't have an `uwsgi` folder in `/run/`

**Comment by tonioo** [comment]
@CooperBarrett Sorry for the late reply. Maybe you could try the solution mentionned in #1650 ?

**Comment by CooperBarrett** [comment]
No...
I'm desperate, nothing works

**Comment by tonioo** [comment]
@CooperBarrett I really don't know what's wrong... Maybe you could order a support ticket from the website so I can check your installation?

**Comment by CooperBarrett** [comment]
> Maybe you could order a support ticket from the website

it would have been a pleasure, but 100€ per ticket is really out of price for me !

**Comment by jforce** [comment]
I have the same issue

**Comment by jforce** [comment]
cat /var/log/uwsgi/app/modoboa_instance.log
Sun Apr  7 03:15:33 2019 - WSGI app 1 (mountpoint='mail.domain|') ready in 2 seconds on interpreter 0x55a096eb0590 pid: 9941
Sun Apr  7 03:15:33 2019 - !!! uWSGI process 9941 got Segmentation Fault !!!
Sun Apr  7 03:15:33 2019 - *** backtrace of 9941 ***
/usr/bin/uwsgi(uwsgi_backtrace+0x2a) [0x55a095ef798a]
/usr/bin/uwsgi(uwsgi_segfault+0x23) [0x55a095ef7d73]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f4268f6af20]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/./libssl-c0c2ede4.so.1.0.2q(ssl3_cleanup_key_block+0xb) [0x7f42619bfcab]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/./libssl-c0c2ede4.so.1.0.2q(ssl3_clear+0x16) [0x7f42619bd5a6]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/./libssl-c0c2ede4.so.1.0.2q(tls1_clear+0x9) [0x7f42619c9219]
/usr/lib/x86_64-linux-gnu/libssl.so.1.1(SSL_new+0x3f2) [0x7f4269be4d32]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/libpq-bd31fe2b.so.5.11(+0x23969) [0x7f4261c54969]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/libpq-bd31fe2b.so.5.11(+0x24fc5) [0x7f4261c55fc5]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/libpq-bd31fe2b.so.5.11(PQconnectPoll+0xb78) [0x7f4261c3fba8]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/libpq-bd31fe2b.so.5.11(+0xfa28) [0x7f4261c40a28]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/libpq-bd31fe2b.so.5.11(PQconnectdb+0x1f) [0x7f4261c4341f]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/_psycopg.so(+0x129c1) [0x7f4261e949c1]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/_psycopg.so(+0x1374f) [0x7f4261e9574f]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x13c8da) [0x7f42659558da]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(_PyObject_CallFunction_SizeT+0xa1) [0x7f42659918b1]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/_psycopg.so(+0xc268) [0x7f4261e8e268]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x64d7) [0x7f42658c6697]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1646dd) [0x7f426597d6dd]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5314) [0x7f42658c54d4]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b5b) [0x7f42658c8d1b]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b5b) [0x7f42658c8d1b]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b5b) [0x7f42658c8d1b]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5bf6) [0x7f42658c5db6]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b5b) [0x7f42658c8d1b]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5bf6) [0x7f42658c5db6]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x196dd3) [0x7f42659afdd3]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x188443) [0x7f42659a1443]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1886d8) [0x7f42659a16d8]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x13c8da) [0x7f42659558da]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x41e1) [0x7f42658c43a1]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b5b) [0x7f42658c8d1b]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1645f9) [0x7f426597d5f9]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1abd1c) [0x7f42659c4d1c]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x12b880) [0x7f4265944880]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_GetIter+0x1f) [0x7f426598f48f]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1883f8) [0x7f42659a13f8]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1886d8) [0x7f42659a16d8]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x13c8da) [0x7f42659558da]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x41e1) [0x7f42658c43a1]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1646dd) [0x7f426597d6dd]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5314) [0x7f42658c54d4]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5bf6) [0x7f42658c5db6]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5bf6) [0x7f42658c5db6]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1645f9) [0x7f426597d5f9]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1abd1c) [0x7f42659c4d1c]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x12c0ca) [0x7f42659450ca]
*** end of backtrace ***
Sun Apr  7 03:15:34 2019 - DAMN ! worker 1 (pid: 9941) died :( trying respawn ...
Sun Apr  7 03:15:34 2019 - Respawned uWSGI worker 1 (new pid: 10456)
Sun Apr  7 03:15:35 2019 - WSGI app 1 (mountpoint='mail.domain|') ready in 1 seconds on interpreter 0x55a096eb0590 pid: 9906
Sun Apr  7 03:15:35 2019 - !!! uWSGI process 9906 got Segmentation Fault !!!
Sun Apr  7 03:15:35 2019 - *** backtrace of 9906 ***
/usr/bin/uwsgi(uwsgi_backtrace+0x2a) [0x55a095ef798a]
/usr/bin/uwsgi(uwsgi_segfault+0x23) [0x55a095ef7d73]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f4268f6af20]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/./libssl-c0c2ede4.so.1.0.2q(ssl3_cleanup_key_block+0xb) [0x7f42619bfcab]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/./libssl-c0c2ede4.so.1.0.2q(ssl3_clear+0x16) [0x7f42619bd5a6]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/./libssl-c0c2ede4.so.1.0.2q(tls1_clear+0x9) [0x7f42619c9219]
/usr/lib/x86_64-linux-gnu/libssl.so.1.1(SSL_new+0x3f2) [0x7f4269be4d32]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/libpq-bd31fe2b.so.5.11(+0x23969) [0x7f4261c54969]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/libpq-bd31fe2b.so.5.11(+0x24fc5) [0x7f4261c55fc5]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/libpq-bd31fe2b.so.5.11(PQconnectPoll+0xb78) [0x7f4261c3fba8]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/libpq-bd31fe2b.so.5.11(+0xfa28) [0x7f4261c40a28]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/.libs/libpq-bd31fe2b.so.5.11(PQconnectdb+0x1f) [0x7f4261c4341f]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/_psycopg.so(+0x129c1) [0x7f4261e949c1]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/_psycopg.so(+0x1374f) [0x7f4261e9574f]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x13c8da) [0x7f42659558da]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(_PyObject_CallFunction_SizeT+0xa1) [0x7f42659918b1]
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/_psycopg.so(+0xc268) [0x7f4261e8e268]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x64d7) [0x7f42658c6697]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1646dd) [0x7f426597d6dd]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5314) [0x7f42658c54d4]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b5b) [0x7f42658c8d1b]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b5b) [0x7f42658c8d1b]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b5b) [0x7f42658c8d1b]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5bf6) [0x7f42658c5db6]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b5b) [0x7f42658c8d1b]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5bf6) [0x7f42658c5db6]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x196dd3) [0x7f42659afdd3]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x188443) [0x7f42659a1443]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1886d8) [0x7f42659a16d8]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x13c8da) [0x7f42659558da]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x41e1) [0x7f42658c43a1]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b5b) [0x7f42658c8d1b]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1645f9) [0x7f426597d5f9]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1abd1c) [0x7f42659c4d1c]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x12b880) [0x7f4265944880]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_GetIter+0x1f) [0x7f426598f48f]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1883f8) [0x7f42659a13f8]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1886d8) [0x7f42659a16d8]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x13c8da) [0x7f42659558da]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x41e1) [0x7f42658c43a1]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1646dd) [0x7f426597d6dd]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5314) [0x7f42658c54d4]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5bf6) [0x7f42658c5db6]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5bf6) [0x7f42658c5db6]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f42659f8278]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1645f9) [0x7f426597d5f9]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1abd1c) [0x7f42659c4d1c]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f426586d333]
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x12c0ca) [0x7f42659450ca]
*** end of backtrace ***
Sun Apr  7 03:15:36 2019 - DAMN ! worker 2 (pid: 9906) died :( trying respawn ...
Sun Apr  7 03:15:36 2019 - Respawned uWSGI worker 2 (new pid: 10490)

**Comment by tonioo** [comment]
@jforce Your issue looks different, have you updated the psycopg2 package recently?

**Comment by fabionader** [comment]
that help me with this issue:

https://stackoverflow.com/a/53944279

**Comment by RT4U** [comment]
This fixed the issue for me.
https://stackoverflow.com/a/54253374/2748913

> This error occurs when uwsgi and psycopg are compiled against two different openssl versions. You have two solution.
> 
> disable ssl of django database configuration (the other answer's solution)
> Install psyocpg2 from source instead of wheel
> to install psyocpg2 from source you have to uninstall previous one and try this
> 
> pip uninstall psycopg2
> pip install --no-binary :all: psycopg2
