### ISSUE TITLE
table dkim empty?

### ISSUE THREAD

**Issue by lendriu7** [modoboa/modoboa#1627]
# Impacted versions

* Modoboa: last
* installer used: Yes?
* Webserver: Nginx

# Steps to reproduce
install modoboa from installer

# Current behavior
opendkim not be able to sign mail (opendkim[1756]: E849E40330: no signing table match for ...) 

# Expected behavior
opendkim be able to signe email
# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@lendriu7 Have you enabled DKIM signing for your domain(s) from the modoboa admin page? If not, keys won't be generated on OpenDKIM won't sign anythinh.

**Comment by lendriu7** [comment]
Thz Antoine for the reply.
You can close the ticket: it was a permission problem on /usr/lib/dkim.
Cheers

Il giorno lun 3 dic 2018 alle ore 09:33 Antoine Nguyen <
notifications@github.com> ha scritto:
