### ISSUE TITLE
Questions about Radicale

### ISSUE THREAD

**Issue by inas3** [modoboa/modoboa#1630]
1. Does Radicale front-end on Modoboa allow you to actually control your Radicale instance by adding/changing Contacts/Calenders, etc ?  If yes, then where exactly do you control it since I only see 2 paths you set on radicale tab in Modoboa?

2. Does Radicale have to be installed separately so that it can work on Modoboa?

3. Can you have Radicale installed on a completely separate domain and still control it via Modoboa?

It would be great to know all this, since i do not see any of this information being clear in the documentation.
Sorry if this is a noob question.

**Comment by tonioo** [comment]
@inas3 If you install Modoboa using the installer then Radicale will be installed too. To create calendars and contacts, you need a user with a mailbox (a simple user). The default administrator (admin) has no mailbox so you won't see anything.
What do you mean by completely separate domain?

**Comment by inas3** [comment]
@tonioo i see. ok.
So for Q3. i meant when you add more domains to Modoboa like different email domains such as email1@domain1.com and email1@domain2.com
I take it Radicale then is also able to separate these since the users will be different?

Also, if you don't want to enable Radicale on Modoboa, what do you do? just simply not configure Radicale settings?
