### ISSUE TITLE
Question about TSL Encryption and Windows Mail/Outlook

### ISSUE THREAD

**Issue by horvan** [modoboa/modoboa#1632]
# Impacted versions

* Modoboa: 1.12.2

* installer used: Yes
* Webserver: Nginx

# Install Modoba with Let's encrypt
![modoba error](https://user-images.githubusercontent.com/5676367/49736547-c5432b00-fc8a-11e8-825a-64cb1a0678cc.PNG)

![cert](https://user-images.githubusercontent.com/5676367/49736838-7c3fa680-fc8b-11e8-9c6d-dca541202cff.png)

# Windows Mail and Outlook say the certifictae is untrsted and it may be it has the wron domain. Not sure why this is.

# Connecting Mail Clients like a charm without any errors by useing tsl encryption

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
The LE certificate generated by the installer is valid only for the server hostname (ie. mail.domain.tld by default). I guess with could add autodiscover.domain.tld to the list...
