### ISSUE TITLE
Opening quarantine as super user displays Internal Error

### ISSUE THREAD

**Issue by ndoody** [modoboa/modoboa#1633]
# Impacted versions

* Modoboa: 1.12.2
* installer used: Yes
* Webserver: Apache

# Steps to reproduce
Open Quarantine as Admin

# Current behavior
Getting internal server error when opening Quarantine as super user with no results, worked fine before upgrading.  Quarantine will display some results as admin if I search for search strings, and the quarantine opens fine logging in as individual user accounts showing personal quarantines.

# Expected behavior
That the Quarantine opens and displays all quarantined emails for all users.

# Video/Screenshot link (optional)

**Comment by ndoody** [comment]
I would like to get a pointer on how I can get some more verbose error that just "Internal Error" so I can debug it myself, where is the detail of the error that causes this stored?

**Comment by tonioo** [comment]
@ndoody Set DEBUG to True in /srv/modoboa/instance/instance/settings.py and reload apache, you should get more info

**Comment by ndoody** [comment]
Thanks, I did that as I found it on another thread.  I'm not seeting any more info in the actual box, but I read your reply about using a Java Debugger and I'm working out how to do that now.

I'm running the amavis pluging 1.4.0 by the way.

**Comment by ndoody** [comment]
/tools/managemail/quarantine/listing/?sort_order=-date&reset_page=true&_=1544550558808:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

is what I get

**Comment by tonioo** [comment]
You should find more information in the network tab. Click on the request which returns a 500 error, and look at the response content.

**Comment by ndoody** [comment]
I don't see anything extra.

HTTP/1.1 500 Internal Server Error
Date: Tue, 11 Dec 2018 17:57:37 GMT
Server: Apache/2.4.9 (Unix) PHP/5.6.4 mod_wsgi/4.2.1 Python/2.7.15
Content-Length: 18963
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
Content-Language: en
Vary: Accept-Language,Cookie
X-Frame-Options: DENY
Connection: close
Content-Type: text/plain

**Comment by ndoody** [comment]
Ahh, I see I'm being a bit thick...the response in full :-

UnicodeDecodeError at /quarantine/listing/
'utf8' codec can't decode byte 0xd2 in position 4: invalid continuation byte

Request Method: GET
Request URL: http://svr1.16o.com/tools/managemail/quarantine/listing/?sort_order=-date&reset_page=true&_=1544551389590
Django Version: 1.11.17
Python Executable: /usr/local/bin/python
Python Version: 2.7.15
Python Path: ['/usr/local/lib/python2.7/site-packages/py_mysql2pgsql-0.1.6-py2.7.egg', '/usr/local/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7-freebsd-9.2-RELEASE-p7-i386.egg', '/usr/local/lib/python2.7/site-packages/django_xslt-0.4.5-py2.7.egg', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-freebsd11', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/usr/home/16o/svr1/modoboa/managemail']
Server time: Tue, 11 Dec 2018 18:03:17 +0000
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'reversion',
 'ckeditor',
 'ckeditor_uploader',
 'rest_framework',
 'rest_framework.authtoken',
 'modoboa',
 'modoboa.core',
 'modoboa.lib',
 'modoboa.admin',
 'modoboa.transport',
 'modoboa.relaydomains',
 'modoboa.limits',
 'modoboa.parameters',
 'modoboa_amavis',
 'modoboa_contacts',
 'modoboa_dmarc',
 'modoboa_imap_migration',
 'modoboa_pdfcredentials',
 'modoboa_postfix_autoreply',
 'modoboa_radicale',
 'modoboa_sievefilters',
 'modoboa_stats',
 'modoboa_webmail')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'modoboa.core.middleware.LocalConfigMiddleware',
 'modoboa.lib.middleware.AjaxLoginRedirect',
 'modoboa.lib.middleware.CommonExceptionCatcher',
 'modoboa.lib.middleware.RequestCatcherMiddleware',
 'django.middleware.security.SecurityMiddleware')


Traceback:  

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/modoboa_amavis/views.py" in _listing
  105.     context = get_listing_pages(request, connector)

File "/usr/local/lib/python2.7/site-packages/modoboa_amavis/views.py" in get_listing_pages
  66.         email_list += connector.fetch(page.id_start, page.id_stop)

File "/usr/local/lib/python2.7/site-packages/modoboa_amavis/sql_connector.py" in fetch
  175.                 "from": fix_utf8_encoding(qm["mail__from_addr"]),

File "/usr/local/lib/python2.7/site-packages/modoboa_amavis/utils.py" in fix_utf8_encoding
  61.     return value.encode("raw_unicode_escape").decode("utf-8")

File "/usr/local/lib/python2.7/encodings/utf_8.py" in decode
  16.     return codecs.utf_8_decode(input, errors, True)

Exception Type: UnicodeDecodeError at /quarantine/listing/
Exception Value: 'utf8' codec can't decode byte 0xd2 in position 4: invalid continuation byte
Request information:
USER: admin

GET:
sort_order = u'-date'
_ = u'1544551389590'
reset_page = u'true'

POST: No POST data

FILES: No FILES data

COOKIES:
csrftoken = 'LBHZUQixZmX0JwFvGtRVYFd2AurnsFj4rEnSCglH64NZjIAQIJpPiNa7M3nnmI5s'
sessionid = 'j6k4poi3m1gz6u731x6wn38h8s305r8s'

META:
CONTEXT_DOCUMENT_ROOT = '/home/16o/svr1/public_html'
CONTEXT_PREFIX = ''
CSRF_COOKIE = 'LBHZUQixZmX0JwFvGtRVYFd2AurnsFj4rEnSCglH64NZjIAQIJpPiNa7M3nnmI5s'
DOCUMENT_ROOT = '/home/16o/svr1/public_html'
GATEWAY_INTERFACE = 'CGI/1.1'
HTTP_ACCEPT = 'application/json, text/javascript, */*; q=0.01'
HTTP_ACCEPT_ENCODING = 'gzip, deflate'
HTTP_ACCEPT_LANGUAGE = 'en-GB,en-US;q=0.9,en;q=0.8'
HTTP_CONNECTION = 'keep-alive'
HTTP_COOKIE = 'csrftoken=LBHZUQixZmX0JwFvGtRVYFd2AurnsFj4rEnSCglH64NZjIAQIJpPiNa7M3nnmI5s; sessionid=j6k4poi3m1gz6u731x6wn38h8s305r8s'
HTTP_HOST = 'svr1.16o.com'
HTTP_REFERER = 'http://svr1.16o.com/tools/managemail/quarantine/'
HTTP_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36'
HTTP_X_REQUESTED_WITH = 'XMLHttpRequest'
LD_LIBRARY_PATH = '/usr/local/apache/lib:'
PATH_INFO = u'/quarantine/listing/'
PATH_TRANSLATED = '/home/16o/svr1/public_html/quarantine/listing/'
QUERY_STRING = 'sort_order=-date&reset_page=true&_=1544551389590'
REMOTE_ADDR = '211.25.100.65'
REMOTE_PORT = '58732'
REQUEST_METHOD = 'GET'
REQUEST_SCHEME = 'http'
REQUEST_URI = '/tools/managemail/quarantine/listing/?sort_order=-date&reset_page=true&_=1544551389590'
SCRIPT_FILENAME = '/usr/home/16o/svr1/modoboa/managemail/managemail/wsgi.py'
SCRIPT_NAME = u'/tools/managemail'
SERVER_ADDR = '78.129.175.64'
SERVER_ADMIN = 'root@svr1.16o.com'
SERVER_NAME = 'svr1.16o.com'
SERVER_PORT = '80'
SERVER_PROTOCOL = 'HTTP/1.1'
SERVER_SIGNATURE = ''
SERVER_SOFTWARE = 'Apache/2.4.9 (Unix) PHP/5.6.4 mod_wsgi/4.2.1 Python/2.7.15'
apache.version = u'(2, 4, 9)'
mod_wsgi.application_group = 'svr1.16o.com|/tools/managemail'
mod_wsgi.callable_object = 'application'
mod_wsgi.enable_sendfile = '0'
mod_wsgi.handler_script = ''
mod_wsgi.input_chunked = '0'
mod_wsgi.listener_host = ''
mod_wsgi.listener_port = '80'
mod_wsgi.process_group = ''
mod_wsgi.request_handler = 'wsgi-script'
mod_wsgi.request_start = '1544551395400628'
mod_wsgi.script_reloading = '1'
mod_wsgi.script_start = '1544551395401290'
mod_wsgi.version = u'(4, 2, 1)'
wsgi.errors = <mod_wsgi.Log object at 0x2dc7cd40>
wsgi.file_wrapper = ''
wsgi.input = <mod_wsgi.Input object at 0x2d042368>
wsgi.multiprocess = True
wsgi.multithread = True
wsgi.run_once = False
wsgi.url_scheme = 'http'
wsgi.version = u'(1, 0)'

Settings:
Using settings module managemail.settings
ABSOLUTE_URL_OVERRIDES = {}
ADMINS = []
ALLOWED_HOSTS = ['svr1.16o.com']
AMAVIS_DEFAULT_DATABASE_ENCODING = u'LATIN1'
APPEND_SLASH = True
AUTHENTICATION_BACKENDS = u"('django.contrib.auth.backends.ModelBackend',)"
AUTH_PASSWORD_VALIDATORS = u'********************'
AUTH_USER_MODEL = 'core.User'
BASE_DIR = '/usr/home/16o/svr1/modoboa/managemail'
CACHES = {u'default': {u'BACKEND': u'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS = u'default'
CACHE_MIDDLEWARE_KEY_PREFIX = u'********************'
CACHE_MIDDLEWARE_SECONDS = 600
CKEDITOR_ALLOW_NONIMAGE_FILES = False
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_CONFIGS = {'default': {'toolbar_Modoboa': [['Bold', 'Italic', 'Underline'], ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'], ['BidiLtr', 'BidiRtl', 'Language'], ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'], ['Undo', 'Redo'], ['Link', 'Unlink', 'Anchor', '-', 'Smiley'], ['TextColor', 'BGColor', '-', 'Source'], ['Font', 'FontSize'], ['Image'], ['SpellChecker']], 'allowedContent': True, 'toolbar': 'Modoboa', 'width': None}}
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_UPLOAD_PATH = 'uploads/'
CSRF_COOKIE_AGE = 31449600
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_NAME = u'csrftoken'
CSRF_COOKIE_PATH = u'/'
CSRF_COOKIE_SECURE = False
CSRF_FAILURE_VIEW = u'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME = u'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS = []
CSRF_USE_SESSIONS = False
DATABASES = {'default': {'ENGINE': 'django.db.backends.mysql', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': True, 'NAME': 'mail', 'CONN_MAX_AGE': 0, 'TIME_ZONE': None, 'PORT': '3306', 'HOST': 'localhost', 'USER': 'mail', 'TEST': {'COLLATION': None, 'CHARSET': None, 'NAME': None, 'MIRROR': None}, 'PASSWORD': u'********************', 'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"}}, 'amavis': {'ENGINE': 'django.db.backends.mysql', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': True, 'NAME': 'mail_amavisd', 'CONN_MAX_AGE': 0, 'TIME_ZONE': None, 'PORT': '3306', 'HOST': 'localhost', 'USER': 'mail', 'TEST': {'COLLATION': None, 'CHARSET': None, 'NAME': None, 'MIRROR': None}, 'PASSWORD': u'********************', 'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"}}}
DATABASE_ROUTERS = [u'modoboa_amavis.dbrouter.AmavisRouter']
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000
DATETIME_FORMAT = u'N j, Y, P'
DATETIME_INPUT_FORMATS = [u'%Y-%m-%d %H:%M:%S', u'%Y-%m-%d %H:%M:%S.%f', u'%Y-%m-%d %H:%M', u'%Y-%m-%d', u'%m/%d/%Y %H:%M:%S', u'%m/%d/%Y %H:%M:%S.%f', u'%m/%d/%Y %H:%M', u'%m/%d/%Y', u'%m/%d/%y %H:%M:%S', u'%m/%d/%y %H:%M:%S.%f', u'%m/%d/%y %H:%M', u'%m/%d/%y']
DATE_FORMAT = u'N j, Y'
DATE_INPUT_FORMATS = [u'%Y-%m-%d', u'%m/%d/%Y', u'%m/%d/%y', u'%b %d %Y', u'%b %d, %Y', u'%d %b %Y', u'%d %b, %Y', u'%B %d %Y', u'%B %d, %Y', u'%d %B %Y', u'%d %B, %Y']
DEBUG = True
DEBUG_PROPAGATE_EXCEPTIONS = False
DECIMAL_SEPARATOR = u'.'
DEFAULT_CHARSET = u'utf-8'
DEFAULT_CONTENT_TYPE = u'text/html'
DEFAULT_EXCEPTION_REPORTER_FILTER = u'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE = u'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL = u'webmaster@localhost'
DEFAULT_INDEX_TABLESPACE = u''
DEFAULT_TABLESPACE = u''
DISALLOWED_USER_AGENTS = []
EMAIL_BACKEND = u'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = u'localhost'
EMAIL_HOST_PASSWORD = u'********************'
EMAIL_HOST_USER = u''
EMAIL_PORT = 25
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = u'********************'
EMAIL_SUBJECT_PREFIX = u'[Django] '
EMAIL_TIMEOUT = None
EMAIL_USE_LOCALTIME = False
EMAIL_USE_SSL = False
EMAIL_USE_TLS = False
FILE_CHARSET = u'utf-8'
FILE_UPLOAD_DIRECTORY_PERMISSIONS = None
FILE_UPLOAD_HANDLERS = [u'django.core.files.uploadhandler.MemoryFileUploadHandler', u'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440
FILE_UPLOAD_PERMISSIONS = None
FILE_UPLOAD_TEMP_DIR = None
FIRST_DAY_OF_WEEK = 0
FIXTURE_DIRS = []
FORCE_SCRIPT_NAME = None
FORMAT_MODULE_PATH = None
FORM_RENDERER = u'django.forms.renderers.DjangoTemplates'
IGNORABLE_404_URLS = []
INSTALLED_APPS = u"('django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.sites', 'django.contrib.staticfiles', 'reversion', 'ckeditor', 'ckeditor_uploader', 'rest_framework', 'rest_framework.authtoken', 'modoboa', 'modoboa.core', 'modoboa.lib', 'modoboa.admin', 'modoboa.transport', 'modoboa.relaydomains', 'modoboa.limits', 'modoboa.parameters', 'modoboa_amavis', 'modoboa_contacts', 'modoboa_dmarc', 'modoboa_imap_migration', 'modoboa_pdfcredentials', 'modoboa_postfix_autoreply', 'modoboa_radicale', 'modoboa_sievefilters', 'modoboa_stats', 'modoboa_webmail')"
INTERNAL_IPS = []
LANGUAGES = [(u'af', u'Afrikaans'), (u'ar', u'Arabic'), (u'ast', u'Asturian'), (u'az', u'Azerbaijani'), (u'bg', u'Bulgarian'), (u'be', u'Belarusian'), (u'bn', u'Bengali'), (u'br', u'Breton'), (u'bs', u'Bosnian'), (u'ca', u'Catalan'), (u'cs', u'Czech'), (u'cy', u'Welsh'), (u'da', u'Danish'), (u'de', u'German'), (u'dsb', u'Lower Sorbian'), (u'el', u'Greek'), (u'en', u'English'), (u'en-au', u'Australian English'), (u'en-gb', u'British English'), (u'eo', u'Esperanto'), (u'es', u'Spanish'), (u'es-ar', u'Argentinian Spanish'), (u'es-co', u'Colombian Spanish'), (u'es-mx', u'Mexican Spanish'), (u'es-ni', u'Nicaraguan Spanish'), (u'es-ve', u'Venezuelan Spanish'), (u'et', u'Estonian'), (u'eu', u'Basque'), (u'fa', u'Persian'), (u'fi', u'Finnish'), (u'fr', u'French'), (u'fy', u'Frisian'), (u'ga', u'Irish'), (u'gd', u'Scottish Gaelic'), (u'gl', u'Galician'), (u'he', u'Hebrew'), (u'hi', u'Hindi'), (u'hr', u'Croatian'), (u'hsb', u'Upper Sorbian'), (u'hu', u'Hungarian'), (u'ia', u'Interlingua'), (u'id', u'Indonesian'), (u'io', u'Ido'), (u'is', u'Icelandic'), (u'it', u'Italian'), (u'ja', u'Japanese'), (u'ka', u'Georgian'), (u'kk', u'Kazakh'), (u'km', u'Khmer'), (u'kn', u'Kannada'), (u'ko', u'Korean'), (u'lb', u'Luxembourgish'), (u'lt', u'Lithuanian'), (u'lv', u'Latvian'), (u'mk', u'Macedonian'), (u'ml', u'Malayalam'), (u'mn', u'Mongolian'), (u'mr', u'Marathi'), (u'my', u'Burmese'), (u'nb', u'Norwegian Bokm\xe5l'), (u'ne', u'Nepali'), (u'nl', u'Dutch'), (u'nn', u'Norwegian Nynorsk'), (u'os', u'Ossetic'), (u'pa', u'Punjabi'), (u'pl', u'Polish'), (u'pt', u'Portuguese'), (u'pt-br', u'Brazilian Portuguese'), (u'ro', u'Romanian'), (u'ru', u'Russian'), (u'sk', u'Slovak'), (u'sl', u'Slovenian'), (u'sq', u'Albanian'), (u'sr', u'Serbian'), (u'sr-latn', u'Serbian Latin'), (u'sv', u'Swedish'), (u'sw', u'Swahili'), (u'ta', u'Tamil'), (u'te', u'Telugu'), (u'th', u'Thai'), (u'tr', u'Turkish'), (u'tt', u'Tatar'), (u'udm', u'Udmurt'), (u'uk', u'Ukrainian'), (u'ur', u'Urdu'), (u'vi', u'Vietnamese'), (u'zh-hans', u'Simplified Chinese'), (u'zh-hant', u'Traditional Chinese')]
LANGUAGES_BIDI = [u'he', u'ar', u'fa', u'ur']
LANGUAGE_CODE = 'en-us'
LANGUAGE_COOKIE_AGE = None
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_NAME = u'django_language'
LANGUAGE_COOKIE_PATH = u'/'
LOCALE_PATHS = []
LOGGING = {'loggers': {'modoboa.auth': {'handlers': ['syslog-auth', 'modoboa'], 'propagate': False, 'level': 'INFO'}, 'modoboa.admin': {'handlers': ['modoboa'], 'propagate': False, 'level': 'INFO'}}, 'version': 1, 'formatters': {'syslog': {'format': '%(name)s: %(levelname)s %(message)s'}}, 'handlers': {'syslog-auth': {'formatter': 'syslog', 'class': 'logging.handlers.SysLogHandler', 'facility': 4}, 'modoboa': {'class': 'modoboa.core.loggers.SQLHandler'}}}
LOGGING_CONFIG = u'logging.config.dictConfig'
LOGIN_REDIRECT_URL = u'/accounts/profile/'
LOGIN_URL = '/tools/managemail/accounts/login/'
LOGOUT_REDIRECT_URL = None
MANAGERS = []
MEDIA_ROOT = '/usr/home/16o/svr1/modoboa/managemail/media'
MEDIA_URL = '/tools/managemail/media/'
MESSAGE_STORAGE = u'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE = u"('django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.locale.LocaleMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'modoboa.core.middleware.LocalConfigMiddleware', 'modoboa.lib.middleware.AjaxLoginRedirect', 'modoboa.lib.middleware.CommonExceptionCatcher', 'modoboa.lib.middleware.RequestCatcherMiddleware', 'django.middleware.security.SecurityMiddleware')"
MIDDLEWARE_CLASSES = [u'django.middleware.common.CommonMiddleware', u'django.middleware.csrf.CsrfViewMiddleware']
MIGRATION_MODULES = {}
MODOBOA_API_URL = u'********************'
MODOBOA_APPS = u"('modoboa', 'modoboa.core', 'modoboa.lib', 'modoboa.admin', 'modoboa.transport', 'modoboa.relaydomains', 'modoboa.limits', 'modoboa.parameters', 'modoboa_amavis', 'modoboa_contacts', 'modoboa_dmarc', 'modoboa_imap_migration', 'modoboa_pdfcredentials', 'modoboa_postfix_autoreply', 'modoboa_radicale', 'modoboa_sievefilters', 'modoboa_stats', 'modoboa_webmail')"
MONTH_DAY_FORMAT = u'F j'
NUMBER_GROUPING = 0
PASSWORD_HASHERS = u'********************'
PASSWORD_RESET_TIMEOUT_DAYS = u'********************'
PREPEND_WWW = False
REST_FRAMEWORK = {'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.TokenAuthentication', 'rest_framework.authentication.SessionAuthentication')}
ROOT_URLCONF = 'managemail.urls'
SECRET_KEY = u'********************'
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_HSTS_SECONDS = 0
SECURE_PROXY_SSL_HEADER = None
SECURE_REDIRECT_EXEMPT = []
SECURE_SSL_HOST = None
SECURE_SSL_REDIRECT = False
SERVER_EMAIL = u'root@localhost'
SESSION_CACHE_ALIAS = u'default'
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = u'sessionid'
SESSION_COOKIE_PATH = u'/'
SESSION_COOKIE_SECURE = False
SESSION_ENGINE = u'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_FILE_PATH = None
SESSION_SAVE_EVERY_REQUEST = False
SESSION_SERIALIZER = u'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE = 'managemail.settings'
SHORT_DATETIME_FORMAT = u'm/d/Y P'
SHORT_DATE_FORMAT = u'm/d/Y'
SIGNING_BACKEND = u'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS = [u'fields.W342']
SITE_ID = 1
STATICFILES_DIRS = u"('/usr/local/lib/python2.7/site-packages/modoboa/bower_components',)"
STATICFILES_FINDERS = [u'django.contrib.staticfiles.finders.FileSystemFinder', u'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATICFILES_STORAGE = u'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_ROOT = '/usr/home/16o/svr1/modoboa/managemail/sitestatic'
STATIC_URL = '/tools/managemail/sitestatic/'
TEMPLATES = [{'DIRS': [], 'APP_DIRS': True, 'OPTIONS': {'debug': True, 'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.template.context_processors.i18n', 'django.template.context_processors.media', 'django.template.context_processors.static', 'django.template.context_processors.tz', 'django.contrib.messages.context_processors.messages', 'modoboa.core.context_processors.top_notifications']}, 'BACKEND': 'django.template.backends.django.DjangoTemplates'}]
TEST_NON_SERIALIZED_APPS = []
TEST_RUNNER = u'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR = u','
TIME_FORMAT = u'P'
TIME_INPUT_FORMATS = [u'%H:%M:%S', u'%H:%M:%S.%f', u'%H:%M']
TIME_ZONE = 'UTC'
USE_ETAGS = False
USE_I18N = True
USE_L10N = False
USE_THOUSAND_SEPARATOR = False
USE_TZ = True
USE_X_FORWARDED_HOST = False
USE_X_FORWARDED_PORT = False
WSGI_APPLICATION = 'managemail.wsgi.application'
X_FRAME_OPTIONS = 'DENY'
YEAR_MONTH_FORMAT = u'F Y'


You're seeing this error because you have DEBUG = True in your
Django settings file. Change that to False, and Django will
display a standard page generated by the handler for this status code.

**Comment by tonioo** [comment]
@ndoody Any news?
