### ISSUE TITLE
CommandError: Failed to retrieve versions from the API.

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#1638]
# Impacted versions

* Modoboa: 1.12.2

From time to time, I receive this type of error as mail admin.

Any idea how to debug this?

```
Subject: Cron <root@mail>    $PYTHON $INSTANCE/manage.py communicate_with_public_api
CommandError: Failed to retrieve versions from the API.
```

**Comment by tonioo** [comment]
@stefaweb I also see such errors sometimes, I guess it can be caused by a server overload on the API side but I need to check...

**Comment by ddiguru** [comment]
I had this problem today and took a quick PCAP to see what's going on, and it appears the certificate is expired.

**Comment by Philambdo** [comment]
The certificate expired on February 11, 2019, 11:00:15 PM GMT+1. The current time is February 12, 2019, 8:03 AM.

Same problem here since yesterday - i guess someone missed the reissue cron job? ;)

**Comment by WLR86** [comment]
Same here. Given that certbot may be used, it's no surprise : I was using that too until I realized it was failing every time the certs needs to be updated and I ended renewing manually - I switched to acmetool and never had a problem since. I don't want to hear about certbot anymore, it's a waste of time.

**Comment by vac** [comment]
api.modoboa.org certificate looks fine today but I'm still receiving `CommandError: Failed to retrieve versions from the API.` :(

**Comment by stefaweb** [comment]
Same here. I have the error message many times per day.

**Comment by mundschenk-at** [comment]
It's happening for me right now (didn't see the messages two weeks ago).

**Comment by ddiguru** [comment]
> It's happening for me right now (didn't see the messages two weeks ago). Looks like the certificate expired again this morning.

Same here for the last two (2) days

**Comment by stefaweb** [comment]
Many every days.

And now every hour.

![sc](https://user-images.githubusercontent.com/12907102/57184387-25956c00-6ebb-11e9-91b0-00edd8e3e15c.png)

**Comment by PatTheMav** [comment]
@stefaweb Certificate seems to be expired again. As the cron runs once per hour, we'll be getting those errors until the certificate is renewed (and hopefully `acme.sh` instead of `certbot` is properly configured on that host 😬).

**Comment by PatTheMav** [comment]
@tonioo FYI - certificate has expired again. 🙃

**Comment by jquiros2** [comment]
Today is:  7/25/2019.
current cert on api info... 
Issued On	Wednesday, April 24, 2019 at 3:00:22 PM
Expires On	Tuesday, July 23, 2019 at 3:00:22 PM

That said-  @tonioo... thanks for this project!

**Comment by christoph-mueller-crixp** [comment]
looks like the cert of api.modobia.org has expired again:

> Validity Period
> Issued On	Sunday, July 14, 2019 at 11:00:23 PM
> Expires On	Saturday, October 12, 2019 at 11:00:23 PM

**Comment by BugHunter2k** [comment]
Still not solved
![image](https://user-images.githubusercontent.com/5654631/68578529-7beaf500-0472-11ea-9446-fe1bbcd19aa4.png)

**Comment by monasax** [comment]
https://api.modoboa.org/1/ - Not Found. The requested URL /1/ was not found on this server.

**Comment by studioluminous** [comment]
Still not solved, I have the same issue.

CommandError: Failed to retrieve versions from the API.

I'm getting the error about 10 times a day for the last week an a half at least.

**Comment by jaggeddragon** [comment]
I continue to get the same error on a brand new installation. It seems to be intermittent, so I assume it is related to load on the API end. Have you considered cloudlflare for this resource endpoint? Is it possible for server admins to make our own api backend, and point the DNS for api.modoboa.org there to prevent this annoyance?

**Comment by michael-v-bloom** [comment]
Same issue here > #2422 

Receiving same Error message twice and/or thrice a day.
