### ISSUE TITLE
automx_wsgi.py: No module named html

### ISSUE THREAD

**Issue by Meistercoach83** [modoboa/modoboa#1639]
Hey! I don´t know if it´s a bug or my config is not working, but I see the following error in automx_instance.log:

> Fri Dec 21 11:25:28 2018 - Python version: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)  [GCC 7.3.0]
Fri Dec 21 11:25:28 2018 - Set PythonHome to /srv/automx/env
Fri Dec 21 11:25:28 2018 - *** Python threads support is disabled. You can enable it with --enable-threads ***
Fri Dec 21 11:25:28 2018 - Python main interpreter initialized at 0x55ddfd72d2b0
Fri Dec 21 11:25:28 2018 - dropping root privileges after plugin initialization
Fri Dec 21 11:25:28 2018 - your server socket listen backlog is limited to 100 connections
Fri Dec 21 11:25:28 2018 - your mercy for graceful operations on workers is 60 seconds
Fri Dec 21 11:25:28 2018 - mapped 218304 bytes (213 KB) for 2 cores
Fri Dec 21 11:25:28 2018 - *** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./automx_wsgi.py", line 29, in <module>
    from html import escape
ImportError: No module named html

What does that error mean / how can I solve the problem?

When I do an pip install html I get the following log:
Requirement already satisfied: html in /srv/modoboa/instance/env/lib/python2.7/site-packages (1.16)

Question: Is that the right directory? shouldn´t it be somewhere like /srv/automx/?

**Comment by tonioo** [comment]
@Meistercoach83 How did you install modoboa?

**Comment by Meistercoach83** [comment]
I installed it manually
