### ISSUE TITLE
[support request] how to set up dkim keys the right way

### ISSUE THREAD

**Issue by horvan** [modoboa/modoboa#1641]
# Impacted versions

* Modoboa: X.X.x
* installer used: Yes/No ?
* Webserver: Nginx/Apache

I tried to set up dkim with my hoster in dns editor by useing this tutorial

https://contabo.com/?show=tutorials&tutorial=domainkeys-dkim

I cant get the dkim to work Is there a tutorial how to reform the key to get it in to a dns record?

**Comment by tonioo** [comment]
@horvan There is no specific tutorial about DKIM setup but I suggest you try with the latest version, additional instructions were added.
