### ISSUE TITLE
how/where to change dkim selector?

### ISSUE THREAD

**Issue by JayBeRayBearGun** [modoboa/modoboa#1643]
# Impacted versions

* Modoboa: 1.10.6
* installer used: Yes
* Webserver: Nginx

I'd like to change my dkim selector string. Where or how can I do this? 

By the way when I click to generate a new it it responds with "not generated" although in fact there seems to be a new key available anyway

**Comment by tonioo** [comment]
@JayBeRayBearGun The selector (for a given domain) can be changed in the edit form and if DKIM is enabled. There is also a global parameter you can find in Modoboa > Parameters > Admin.

**Comment by JayBeRayBearGun** [comment]
Thanks,... found it!  PS: happy new year!
