### ISSUE TITLE
dkim check fails

### ISSUE THREAD

**Issue by Greybane** [modoboa/modoboa#1647]
# Impacted versions

* Modoboa: 1.13.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Add domain to modoboa.
Configure DKIM in the web ui.
Make sure the record passes tests on sites like dmarcanalyzer.com & dkimcore.org

# Current behavior
The DNS check is red and says "No record found."

# Expected behavior
DNS check should turn green and say "A DNS record has been found and is valid."

**Comment by tonioo** [comment]
@Greybane Can you check if #1648 fixes your problem?

**Comment by ObiOnyemaobi** [comment]
Same issue here. Two different environments/installations

**Comment by lsh-0** [comment]
I've just upgraded to 1.13.1, the information pane in the Modoboa admin interface confirms this however my DKIM label is still red with the label `no record found`. https://www.dmarcanalyzer.com gives me all green and I can't see a fault in my configuration.

Can anybody else confirm the 1.13.1 release fixes this bug?

**Comment by ObiOnyemaobi** [comment]
+1.

Fault is still apparent at 1.13.1.

**Comment by tonioo** [comment]
@lsh-0 @ObiOnyemaobi Can you provide examples? (DNS records)

**Comment by ObiOnyemaobi** [comment]
As with everything, issues take time to figure possibly figure themselves out. 
The fault is now resolved on my end. Seems as if the DNS was taking it's time.
