### ISSUE TITLE
Contacts name with special characters don't work

### ISSUE THREAD

**Issue by npfe** [modoboa/modoboa#1652]
# Impacted versions

* Modoboa: Latest - 1.13.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Create a new contact using the web interface and put this character somewhere in the name "é" , when the page with pull data from the rest API using `https://<server_address>/api/v1/address-books/sync_from_cdav/` it will reply with `500 server error`.

I enabled debug, browsed to `sync_from_cdav` and this is what I could see: [pastebin](https://pastebin.com/XQZwdNCg )

### However !
It seems like radicale is doing just fine, I can sync the contact with the special character to my phone and to my other webmail. 

Let me know if you need additional info ! 

Thanks!

**Comment by tonioo** [comment]
@npfe I think there is enough information, thank you. Could you just move this issue to the right repository: https://github.com/modoboa/modoboa-contacts/?

**Comment by npfe** [comment]
@tonioo I created an issue there [#24](https://github.com/modoboa/modoboa-contacts/issues/24#issue-397566772) - Thanks !
