### ISSUE TITLE
Simple User cannot login

### ISSUE THREAD

**Issue by aurora** [modoboa/modoboa#1660]
# Impacted versions

* Modoboa: 1.13.0
* installer used: Yes
* Webserver: Nginx

# Current behavior

I have the problem, that users with the role "Simple User" are unable to log-in. The message they get is just:

Sorry
An internal error occured

If i change the role to "Domain Administrator", the user can log-in. So this issue apparently only effects users with the role "Simple User" applied. I have no idea, how i can debug this further - if i enable "Debug = True" in the settings, it does not give me any additional information.

**Comment by aurora** [comment]
Apparently this has something to do with the setting the admin user can do in "Modoboa -> Parameters -> General -> Miscellaneous": "Default top redirection" - if set to something a simple-user has no access to, the internal error occurs. 

In my opinion modoboa should:

* fallback to a page that a simple user is allowed to access
* or provide a functionality to define the redirection per role

**Comment by tonioo** [comment]
@aurora When DEBUG is enabled, you need to check server responses content using a javascript debugger (F12 key).

**Comment by tonioo** [comment]
@aurora Any news?

**Comment by aurora** [comment]
@tonioo sorry, i've been busy with other things lately, but i will try the coming weekend.

**Comment by tonioo** [comment]
@aurora Any news?
