### ISSUE TITLE
Search button

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#1662]
# Impacted versions

* Modoboa: 1.13.0
* Safari 10.0.2 or Chrome OSX 71.

If we type something in the search entry field and click on the search icon, the entry field is cleared.

Is this normal behavior?

![capture d ecran 2019-01-25 a 17 37 00](https://user-images.githubusercontent.com/12907102/51759357-526e0200-20c8-11e9-83fa-dffcefa30e26.png)

**Comment by tonioo** [comment]
@stefaweb I don't reproduce this behaviour. What is your browser?

**Comment by stefaweb** [comment]
Hi @tonioo!

The problem is gone. I tried again with Safari and Chrome OSX. Now when I click on the search button, nothing append. The only way to search is not enter something in the search field and click on return.

**Comment by tonioo** [comment]
I close this issue. Feel free to open a new one if you want to suggest an improvement.
