### ISSUE TITLE
I can send emails

### ISSUE THREAD

**Issue by RemisSeguro** [modoboa/modoboa#1663]
# Impacted versions

* Modoboa: 1.13.0
* installer used: Yes
* Webserver: Nginx/Apache

# Steps to reproduce

# Current behavior

hello, i install in digitalocean modoboa, the installation was perfect, I can receive emails but I can not send, maybe the error is because of the SMTP configuration, I made the steps with letsencrypt for SSL, I need this urgent, I hope you can help me

# Expected behavior

be able to send messages without problems

# Video/Screenshot link (optional)

**Comment by RemisSeguro** [comment]
news? Help me please

**Comment by RemisSeguro** [comment]
hello thank you for answering. How would I get an error log? I tried to open port 25, but I have the firewall disabled, something you need to help me? regards

**Comment by tonioo** [comment]
Logs should be available in /var/log/mail.log file.

**Comment by RemisSeguro** [comment]
si, aparentemente tengo problemas para conectacrme al puerto 25 de gmail

**Comment by RemisSeguro** [comment]
Yes, apparently I have problems to connect to port 25 of gmail,now I attach a log

**Comment by RemisSeguro** [comment]
After this operation, 73.7 kB of additional disk space will be used.
Get:1 http://mirrors.digitalocean.com/ubuntu xenial/universe amd64 xsel amd64 1.2.0-2 [20.6 kB]
Fetched 20.6 kB in 0s (1,173 kB/s)
Selecting previously unselected package xsel.
(Reading database ... 68441 files and directories currently installed.)
Preparing to unpack .../xsel_1.2.0-2_amd64.deb ...
Unpacking xsel (1.2.0-2) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up xsel (1.2.0-2) ...
root@mail:~# xsel --clipboard < /var/log/mail.log
xsel: Can't open display: (null)
: Connection refused
root@mail:~# nano /var/log/mail.log
root@mail:~#
root@mail:~# nano /var/log/mail.log
Use "fg" to return to nano.

[1]+  Stopped                 nano /var/log/mail.log
root@mail:~# nano /var/log/mail.log
root@mail:~#
root@mail:~# nano /var/log/mail.log
root@mail:~# clear
root@mail:~# nano /var/log/mail.log
  GNU nano 2.5.3           File: /var/log/mail.log

Jan 27 07:02:53 mail postfix/qmgr[2676]: 22357BEF6B: from=<info@remisseguro.com$
Jan 27 07:02:53 mail postfix/qmgr[2676]: B8E5BBEF60: from=<info@remisseguro.com$
Jan 27 07:03:23 mail postfix/smtp[2638]: connect to gmail-smtp-in.l.google.com[$
Jan 27 07:03:23 mail postfix/smtp[2639]: connect to gmail-smtp-in.l.google.com[$
Jan 27 07:03:53 mail postfix/smtp[2638]: connect to alt1.gmail-smtp-in.l.google$
Jan 27 07:03:53 mail postfix/smtp[2639]: connect to alt1.gmail-smtp-in.l.google$
Jan 27 07:04:23 mail postfix/smtp[2638]: connect to alt2.gmail-smtp-in.l.google$
Jan 27 07:04:23 mail postfix/smtp[2639]: connect to alt2.gmail-smtp-in.l.google$
Jan 27 07:04:53 mail postfix/smtp[2638]: connect to alt3.gmail-smtp-in.l.google$
Jan 27 07:04:53 mail postfix/smtp[2639]: connect to alt3.gmail-smtp-in.l.google$
Jan 27 07:05:23 mail postfix/smtp[2638]: connect to alt4.gmail-smtp-in.l.google$
Jan 27 07:05:23 mail postfix/smtp[2639]: connect to alt4.gmail-smtp-in.l.google$
Jan 27 07:05:23 mail postfix/smtp[2638]: 22357BEF6B: to=<sartin.consultas@gmail$
Jan 27 07:05:23 mail postfix/smtp[2639]: B8E5BBEF60: to=<sartin.consultas@gmail$
Jan 27 07:12:44 mail postfix/submission/smtpd[3869]: connect from unknown[125.6$
Jan 27 07:12:44 mail postfix/submission/smtpd[3869]: warning: connect to Milter$
Jan 27 07:12:45 mail postfix/submission/smtpd[3869]: lost connection after EHLO$
Jan 27 07:12:45 mail postfix/submission/smtpd[3869]: disconnect from unknown[12$
Jan 27 07:15:16 mail postfix/postscreen[4223]: CONNECT from [2.201.42.156]:3933$
                               [ Read 855 lines ]
^G Get Help  ^O Write Out ^W Where Is  ^K Cut Text  ^J Justify   ^C Cur Pos
^X Exit      ^R Read File ^\ Replace   ^U Uncut Text^T To Spell  ^_ Go To Line

**Comment by tonioo** [comment]
@RemisSeguro Looks like there is a firewall somewhere...

**Comment by RemisSeguro** [comment]
nice, the firewall is generating conflicts? How do I deactivate it? or do I access port 25? I tried to do it several times already but I have not managed to fix it

**Comment by RemisSeguro** [comment]
I found the problem, after investigating, I discovered that digitalocean blocks port 25 until 60 days have passed since I was using the service, and I sent a message to support to ask if they could enable it. thanks guys, any update I will comment
