### ISSUE TITLE
Bug with cancel button for imap migration

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#1665]
# Impacted versions

* Modoboa: 1.13.1
* Safari OSX

If we have an account with active imap migration.
If we click on the button, and if we click on "cancel", the imap migration is stopped anyway (and the blue button disappears anyway).

![sc](https://user-images.githubusercontent.com/12907102/52261255-17ba6400-2929-11e9-89b1-019ecc1de551.png)

Another bug: the button show "Annuler" (cancel) unless we are using English language.

**Comment by tonioo** [comment]
@stefaweb Hi, could you please move this issue to the right repository? (https://github.com/modoboa/modoboa-imap-migration)

**Comment by stefaweb** [comment]
Moved to https://github.com/modoboa/modoboa-imap-migration/issues/38
