### ISSUE TITLE
Lots of Spam

### ISSUE THREAD

**Issue by blackmlm** [modoboa/modoboa#1666]
# Impacted versions

* Modoboa: 1.13.0
* installer used: No 
* Webserver: Nginx/Apache

We been getting lots of spam mail and it passing.... I dont know what to do.  I been thinking on getting a third party software to filter the spam, but I would like your opinion first..  here its a copy of the header of the emails we are getting.

[Pastebin]https://pastebin.com/CkHh40Yj
thanks in advance for your advice.

**Comment by tonioo** [comment]
@blackmlm I see you installed modoboa manually. Have you also installed a spam filter like spamassassin or rspamd?

**Comment by blackmlm** [comment]
Well,  I used the installer the first time I created the box with 1.9.0, but then I upgraded to 1.13.0. manually. I would assume I think it should be there. 

how can I check if it is installed and working properly?

any suggestions?

**Comment by blackmlm** [comment]
well, the 
systemctl enable spamassassin
systemctl start spamassassin

didn't help.  We are still receiving lots of spam. I don't know if this is normal or I have something wrong.  one of my customers decided to use a comodo antispam gatway to filter the emails, and they are ok now, but I really don't think I should be doing this for every installation of modoboa.  I think I am doing something wrong and I really want to know what it is.

JG

**Comment by tonioo** [comment]
@blackmlm Check if amavis is running (this is the process which calls spamassassin) and if there are errors in the /var/log/mail.log file.
