### ISSUE TITLE
APACHE integation on Autoinstaller?

### ISSUE THREAD

**Issue by TheChaosToast** [modoboa/modoboa#1670]
Hello everybody,

is there a possibility to integrate the APACHE server in the Autoinstaller script?

The problem is that I have broken my configuration because NGNIX is being installed. Since both wanted to listen on port 80 that was not as I would like, because my websites were no longer available. Thank God I had previously made a complete backup.

Thank you very much for an answer

Sorry for my bad English

**Comment by tonioo** [comment]
@TheChaosToast It is possible but it requires some work. Please see https://github.com/modoboa/modoboa-installer/issues/178.
