### ISSUE TITLE
argon2 support

### ISSUE THREAD

**Issue by Arvedui** [modoboa/modoboa#1673]
[From the django docs:](https://docs.djangoproject.com/en/1.11/topics/auth/passwords/#using-argon2-with-django)
> Argon2 is the winner of the 2015 Password Hashing Competition, a community organized open competition to select a next generation hashing algorithm. It’s designed not to be easier to compute on custom hardware than it is to compute on an ordinary CPU.

As indicated django supports argon2 and [dovecot](https://wiki.dovecot.org/Authentication/PasswordSchemes) does as well.
Unfortunately passlib only supports argon2i, not argon2id. The later seems to be the better one for general use. And since passlib upstream seems to have died in 2017 I would not bet on them implementing it anytime soon. There is even a working patch which was completely ignored.
However argon2-cffi, which is the preferred argon2 backend of passlib, does support argon2id and defaults to it. It is quite high level as well so it would be pretty easy to implement.

I could do it myself if there is no objection against using argon2-cffi.

**Comment by tonioo** [comment]
@Arvedui That's a good idea and there is no objection against using argon2-cffi ;)

**Comment by Arvedui** [comment]
Great!

One thing though: 
argon has 3 parameters 
- number of iterations
- size of memory used 
- number of threads

The libraries defaults are sensible as far as I can tell, but they should be tweak able.
Would it be acceptable if that could only be done in settings.py?

**Comment by tonioo** [comment]
@Arvedui I think so, we just need to provide acceptable default values.
