### ISSUE TITLE
Certificate for api.modoboa.org expired

### ISSUE THREAD

**Issue by tschuettler** [modoboa/modoboa#1674]
# Steps to reproduce
cron job `manage.py communicate_with_public_api` fails with `CommandError: Failed to retrieve versions from the API.`

# Current behavior
```
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=api.modoboa.org
*  start date: Nov 13 22:00:15 2018 GMT
*  expire date: Feb 11 22:00:15 2019 GMT
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify result: certificate has expired (10), continuing anyway.
```
# Expected behavior
valid certificate

**Comment by WLR86** [comment]
This is what happens when relying on certbot... Been there, done that. Certbot doesn't automatically renew certs, it just FAILS to do so, and at the end of the day, you have to troubleshoot the issue, fix it, and renew your certs MANUALLY.

Or use acmetool, and forget about it, it just does the job.
(Sorry for this rant, but I wasted so much time using certbot I can't take it anymore)

**Comment by tonioo** [comment]
Actually, the certificate renew worked but nginx reloading failed... Need to figure out why.

**Comment by WLR86** [comment]
Once again... Is there any known workaround ?

**Comment by WLR86** [comment]
Ok I thought I could redirect the error to /dev/null :

```
/etc/cron.d/modoboa
[...]
# Public API communication
0       *       *       *       *       root    $PYTHON $INSTANCE/manage.py communicate_with_public_api 2>/dev/null
[...]
```
So far so good. Obviously the api call still fails, but at east I don't get spammed when it does.

**Comment by Arvedui** [comment]
Here is you quarterly reminder that the certificate auto renewal setup for api.modoboa.org is broken.

**Comment by tonioo** [comment]
@Arvedui it's fixed and I hope it's the last time you report this ;)
