### ISSUE TITLE
Problem with DKIM signature for BIND

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#1675]
# Impacted versions

* Modoboa: 1.30.1

The key printed in GUI do not have "space" between "v=DKIM1;k=rsa;p=". Should be "v=DKIM1; k=rsa; p=xxxx".

![capture d ecran 2019-02-14 a 10 13 31](https://user-images.githubusercontent.com/12907102/52776418-d1a88300-3041-11e9-94df-4cfcf5b03540.png)

**Comment by tonioo** [comment]
@stefaweb Are you sure spaces are required?

**Comment by stefaweb** [comment]
Hi @tonioo!
The RFC alway show parameters with space between.
https://tools.ietf.org/html/rfc6376

**Comment by tonioo** [comment]
According to https://tools.ietf.org/html/rfc6376#section-3.2, spaces are optional... Have you encountered any error using the printed record?

**Comment by stefaweb** [comment]
It works without the spaces.
But with space, it will be better to read it.
As you want if you have some time. It's more cosmetic than technical.
