### ISSUE TITLE
Domains List: Internal Error

### ISSUE THREAD

**Issue by elryion** [modoboa/modoboa#1678]
# Impacted versions

* Modoboa: 1.13.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Login with Super-Admin or Domain-Admin and click on Domains. The quarantine works correctly.

# Current behavior
I have this problem with the upgrade on 1.13.0.
A update of 1.13.1 have not fixed this Problem.

# Expected behavior
The list with my domains.

# Video/Screenshot link (optional)

![internalerror_domains](https://user-images.githubusercontent.com/47864242/53189051-ef0fbb00-3606-11e9-9d79-1e354a9f11c1.PNG)

**Comment by senner** [comment]
Something to do with the checks templates . turn off in Administration settings the following and the error went away for me.


Enable SPF checks ?
Yes  No
Enable DKIM checks ?
Yes  No
Enable DMARC checks ?
Yes  No
Enable autoconfig checks ?
Yes  No
Enable DNSBL checks ?
Yes  No

**Comment by elryion** [comment]
Yes it works only if I disable all checks. 
![disableallchecks](https://user-images.githubusercontent.com/47864242/53249609-cba54880-36b8-11e9-825c-452c185de74c.PNG)

If I then click on the "i" in DNS then the error comes too.
![internalerror_dns](https://user-images.githubusercontent.com/47864242/53249526-91d44200-36b8-11e9-8d00-ca3d90df2b22.PNG)

**Comment by senner** [comment]
Related to https://github.com/modoboa/modoboa/issues/1649

Missing 1.13.0 specific instructions..

**Comment by elryion** [comment]
Thanks for your help. I haven't seen the editing of the "settings.py." Now it works fine!
