### ISSUE TITLE
Unable to login with admin user when IMAP is forwarded from WAN

### ISSUE THREAD

**Issue by Razorblade12** [modoboa/modoboa#1680]
# Impacted versions

* Modoboa: 1.12.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Enable Port Forwarding for IMAP(s) to local mail server on firewall. Login with user that has any administrative role

# Current behavior
Unable to login, error message 504 Gateway Time-Out

# Expected behavior
Administrative user is able to login

# Additional information
As soon as the Port forwarding rule is disabled on the firewall login is possible. 
Login with any user that does not have an administrative role is always possible. 

You can even try a simple user with the firewall rule active.  That user is able to login. When the user's role is then changed to Domain Administrator or Super Administrator the login is not possible.

**Comment by tonioo** [comment]
@Razorblade12 Strange... Are you talking about authentication to the web frontend? What is the first url the user is redirected to after authentication?

**Comment by Razorblade12** [comment]
@tonioo Yes, the authentication to the web frontend. 
After entering credentials and pressing enter the message "504 Gateway Time-Out" appears with the "/dashboard" URL after several seconds.

**Comment by johnmays4545** [comment]
Was this issue ever resolved, I am currently experiencing the same error?

**Comment by Razorblade12** [comment]
@johnmays4545
No, unfortunately not. I did not hear anything since my last post. 
I think this might be a nginx configuration issue as I recently had the same issue with a different nginx site. So there must be something specific with the webserver.
