### ISSUE TITLE
Error updating to 1.13.1

### ISSUE THREAD

**Issue by animalillo** [modoboa/modoboa#1681]
# Impacted versions

* Modoboa: 1.13.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Install 1.13.0 and update following the steps specified at https://modoboa.readthedocs.io/en/latest/upgrade.html to 1.13.1

# Current behavior
Errors appear:

> (env) modoboa@mail:~/instance$ python manage.py check --deploy
System check identified some issues:
> WARNINGS:
> ?: (modoboa-amavis.W001) AMAVIS_DEFAULT_DATABASE_ENCODING does not match the character encoding used by the Amavis database.
>        HINT: Check your database character encoding and set/update AMAVIS_DEFAULT_DATABASE_ENCODING.
> ?: (security.W001) You do not have 'django.middleware.security.SecurityMiddleware' in your MIDDLEWARE so the SECURE_HSTS_SECONDS, SECURE_CONTENT_TYPE_NOSNIFF, SECURE_BROWSER_XSS_FILTER, and SECURE_SSL_REDIRECT settings will have no effect.
>
> System check identified 2 issues (3 silenced).
> (env) modoboa@mail:~/instance$ 

# Expected behavior
No errors shown. Update finishes correctly and is reflected on the web UI

**Comment by tonioo** [comment]
@animalillo Those are just warnings, it does not mean your upgrade has failed. Why do you think it has fail?

**Comment by animalillo** [comment]
Because it was still displaying the same version on the web UI and the update warning...
I guess i had to open a new session or something was cached out preventing that to update but now it seems to display the proper version number!

Thank you for checking, seems to be workinng and updated.
