### ISSUE TITLE
Whishlist: have a refresh on /stats/#graphs/?gset=mailtraffic

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#1683]
It will be nice to have an auto refresh on the statistics page.

`/stats/#graphs/?gset=mailtraffic`

A 60 seconds refresh time will be fine.

Optionally, a global variable to change the refresh time.

Cheers,

**Comment by tonioo** [comment]
@stefaweb Can you please move this issue to the right repository?

**Comment by stefaweb** [comment]
Moved to https://github.com/modoboa/modoboa-stats/issues/54
