### ISSUE TITLE
OpenDKIM no such file or directory; no permission

### ISSUE THREAD

**Issue by danielsatanik** [modoboa/modoboa#1687]
# Impacted versions

* Modoboa: 1.13.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

Enable DKIM Signing

# Current behavior

after just enabling

```
can't load key from /var/lib/dkim/domain.tld.pem: No such file or directory
94B51C0819: error loading key '1'
```

when I create a pem file with openssl genrsa etc. the following errors are shown

```
KeyTable entry for '1' corrupt
can't load key from /var/lib/dkim/domain.tld.pem: Permission denied
```

also this is what is written inside the public key in postgres

```
140332928537024:error:0200100D:system library:fopen:Permission denied:../crypto/bio/bss_file.c:74:fopen('/var/lib/dkim/domain.tld.pem','r')140332928537024:error:2006D002:BIO routines:BIO_new_file:system lib:../crypto/bio/bss_file.c:83:unable to load Private Key
```
# Expected behavior

creating a valid private and public key and signing mails

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@danielsatanik Can you check permissions of the /var/lib/dkim folder? Which user runs the cron job in charge of generating DKIM keys? What is you OS?

**Comment by danielsatanik** [comment]
@tonioo the folder is owned by root:root, that was also suggested, the OS I'm running this on is Ubuntu 18.04LTS, the opendkim user runs the cronjob.

Do you need more detailed information?
