### ISSUE TITLE
'Reseller'-User cannot see all Account-Aliases for his Domain.

### ISSUE THREAD

**Issue by cremesk** [modoboa/modoboa#1692]
# Impacted versions

* Modoboa: 1.3.1
* installer used: Yes
* Webserver: Nginx

My 'Domainadmins'-User cannot see all Accounts (Users and Aliases) for his Domain.
He Cannot see the Domain-Reseller Account.

**Comment by tonioo** [comment]
@cremesk It's normal. A Reseller account has more permissions than a Domain admin one. Is it the only content you don't see as domain administrator?

**Comment by cremesk** [comment]
Okay i Understand this.
Currently I see all Accounts from the Domainadmin but I think i see not alle Account Aliases every time.

**Comment by cremesk** [comment]
Is currently no longer available.

**Comment by cremesk** [comment]
The Reseller-Account cannot see all Aliases.
For the Domain-Admin is this not a problem. He see all Accounts and Aliases.
Is this okay? 

Thanks

**Comment by cremesk** [comment]
@tonio The Reseller- and the Domainadmins- Account cannot see all Aliases.
The i change downgrade the Domainadmins to an Simple User and than renew the Permission to Domainadmins for the Domain is the Problem fixed.

**Comment by tonio** [comment]
`s/@tonio/@tonioo` (-;

**Comment by cremesk** [comment]
fixed after: https://github.com/modoboa/modoboa/issues/1703#issuecomment-523405652
