### ISSUE TITLE
new install getting 404 on static content

### ISSUE THREAD

**Issue by tonyguadagno** [modoboa/modoboa#1693]
hi, i just installed a brand new modoboa on a fully patched centos 7 server.  i used the automatic install which completed without error.  I am trying to get into the admin gui but the css and images are not painting....they are throwing 404's.....

I would appreciate any help in figuring out how to get this working....

thanks in advance!

**Comment by tonyguadagno** [comment]
ok, so i found the nginx logs and see this....why is there a permission issue?

`2019/03/07 10:15:25 [crit] 16967#0: *13 stat() "/srv/modoboa/instance/sitestatic/css/modoboa.png" failed (13: Permission denied), client: 192.168.168.205, server: mail.ffusa.com, request: "GET /sitestatic/css/modoboa.png HTTP/1.1", host: "mail.ffusa.com", referrer: "https://mail.ffusa.com/accounts/login/?next=/"
`

**Comment by tonyguadagno** [comment]
ok, so more poking around shows me that this is an selinux issue.....and i think this is caused by the fact that modoboa chose to put its web home directory in a non standard path (/srv/modoboa/instance).  i was able to find these commands and it seems to have fixed the issue...it seems these should be included in the installer?

```
sudo semanage fcontext -a -t httpd_sys_rw_content_t "/srv/modoboa/instance(/.*)?"
sudo restorecon -Rv /srv/modoboa/instance
```

**Comment by tonyguadagno** [comment]
update:  as it turns out, there are MANY other SELinux violations that get in the way of this working right....regrettable, i had to disable selinux.  I don't like doing this, but i don't have enough knowledge to fix all of it....
If anyone knows all the SELinux changes that need to happen, I would appreciate it, it would be nice if the install script could take care of this.

thanks

**Comment by cremesk** [comment]
you can check this: [Issue 198](https://github.com/modoboa/modoboa-installer/issues/198)

**Comment by tonyguadagno** [comment]
cremesk...GREAT, THANKS, I will try this!
