### ISSUE TITLE
451 4.3.0 Error: queue file write error

### ISSUE THREAD

**Issue by tonyguadagno** [modoboa/modoboa#1694]
hi, i have a new install of modoboa on centos7.  i used the auto install and that went without issue.  I am trying to send a test message out and all messages produce the following error in the /var/log/maillog file:

`Mar  7 15:16:11 ffcplmail postfix/smtpd[6406]: proxy-reject: END-OF-MESSAGE: 451 4.3.0 Error: queue file write error`

can anyone point me in the right direction...it seems like a permissions issue, but I am not sure what folders should be owned and by whom.
thanks

**Comment by cremesk** [comment]
I think the problem was caused by the SELinux issue. Or was the error after Issue [1694](https://github.com/modoboa/modoboa/issues/1694) created?

**Comment by tonyguadagno** [comment]
hi, this is after 1693....i don't think it is related to selinux, i do not see anything in the /var/log/audit/audit.log

**Comment by tonioo** [comment]
@tonyguadagno don't you have more information to provide?

**Comment by tonyguadagno** [comment]
tonioo, I would be happy to provide whatever you think would be helpful, I am not sure what that is....What would be helpful?

thanks again!

**Comment by tonyguadagno** [comment]
this is the complete log if that helps

```
Mar  7 15:16:11 ffcplmail postfix/postscreen[6405]: CONNECT from [127.0.0.1]:56170 to [127.0.0.1]:25
Mar  7 15:16:11 ffcplmail postfix/postscreen[6405]: WHITELISTED [127.0.0.1]:56170
Mar  7 15:16:11 ffcplmail postfix/smtpd[6406]: connect from unknown[127.0.0.1]
Mar  7 15:16:11 ffcplmail postfix/smtpd[6406]: warning: connect to Milter service inet:127.0.0.1:12345: Connection refused
Mar  7 15:16:11 ffcplmail postfix/smtpd[6406]: NOQUEUE: client=unknown[127.0.0.1]
Mar  7 15:16:11 ffcplmail postfix/smtpd[6406]: warning: connect to proxy filter inet:[127.0.0.1]:10024: Connection refused
Mar  7 15:16:11 ffcplmail postfix/smtpd[6406]: proxy-reject: END-OF-MESSAGE: 451 4.3.0 Error: queue file write error; from=<info@dternity.net> to=<tguadagno@fujifilm.com> proto=ESMTP helo=<ffcplmail.ffusa.com>
Mar  7 15:16:11 ffcplmail postfix/cleanup[6415]: 7F3F561432EC: message-id=<20190307201611.7F3F561432EC@mail.ffusa.com>
Mar  7 15:16:11 ffcplmail postfix/smtpd[6406]: disconnect from unknown[127.0.0.1]
Mar  7 15:16:11 ffcplmail postfix/qmgr[5491]: 7F3F561432EC: from=<double-bounce@mail.ffusa.com>, size=1073, nrcpt=1 (queue active)
Mar  7 15:16:11 ffcplmail postfix/local[6416]: 7F3F561432EC: to=<root@mail.ffusa.com>, orig_to=<postmaster>, relay=local, delay=0.06, delays=0.03/0.02/0/0.01, dsn=2.0.0, status=sent (delivered to mailbox)
Mar  7 15:16:11 ffcplmail postfix/qmgr[5491]: 7F3F561432EC: removed

```

**Comment by tonyguadagno** [comment]
If anyone is interested, I figured out the issue.  upon further inspection i noticed that amavisd was not starting as the ports 10024 were not open.  I saw this in the message logs:
```
Mar  8 13:44:07 ffcplmail systemd: Starting Amavisd-new is an interface between MTA and content checkers....
Mar  8 13:44:08 ffcplmail amavisd: The value of variable $myhostname is "ffcplmail", but should have been
Mar  8 13:44:08 ffcplmail amavisd: a fully qualified domain name; perhaps uname(3) did not provide such.
Mar  8 13:44:08 ffcplmail amavisd: You must explicitly assign a FQDN of this host to variable $myhostname
Mar  8 13:44:08 ffcplmail amavisd: in amavisd.conf, or fix what uname(3) provides as a host's network name!
Mar  8 13:44:08 ffcplmail systemd: amavisd.service: control process exited, code=exited status=255

```
It is complaining about the name not being fqdn, so i looked an in fact, it was not set properly.  i used the command
`sudo nmtui`
to set the host name properly and restarted amavisd.  it now starts and as a result, i no longer get this messsage, mail is flowing...
`Mar 7 15:16:11 ffcplmail postfix/smtpd[6406]: proxy-reject: END-OF-MESSAGE: 451 4.3.0 Error: queue file write error`

**Comment by devslayertech** [comment]
How to fix this? 
root@mail:~# sudo nmtui
sudo: nmtui: command not found

**Comment by tonyguadagno** [comment]
@devslayertech ...the point here is to set your server's fqdn properly.  nmtui is the utility on CentOS7.  if you are using another flavor of Linux, then the utility is different.  Not sure what you are using but google how to set your fqdn in that Linux variant.
good luck
