### ISSUE TITLE
Question: Amavis User/Group Not Defined. Defaulting to EUID/EGID

### ISSUE THREAD

**Issue by cremesk** [modoboa/modoboa#1695]
# Impacted versions

* Modoboa: 1.3.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
after reboot:

`tail -f /var/log/mail.info -n 100`

```
Mar  8 13:09:03 sn-mail1 amavis[218]: starting. /usr/sbin/amavisd-new at mail.secnux.net amavisd-new-2.10.1 (20141025), Unicode aware, LC_ALL="C", LANG="en_US.UTF-8"                                                                         
Mar  8 13:09:04 sn-mail1 amavis[889]: Net::Server: Group Not Defined.  Defaulting to EGID '111 111'   
Mar  8 13:09:04 sn-mail1 amavis[889]: Net::Server: User Not Defined.  Defaulting to EUID '108'                          
Mar  8 13:09:04 sn-mail1 amavis[889]: Module Amavis::Conf        2.404
...
```

All works fine!
Can I ignore this or everyone has a "fix"?

Thanks

**Comment by tonioo** [comment]
@cremesk That's pretty strange. Which distribution do you run?

**Comment by cremesk** [comment]
@tonioo I also find it a little strange.
My Modoboa runs on a Debian 9 (buster) with package: amavisd-new
Version: 1: 2.10.1-4

**Comment by tonioo** [comment]
@cremesk I don't see where it can be defined in amavis config. Since I think it's just a warning, can we close this issue?

**Comment by cremesk** [comment]
I also think. we close it.
