### ISSUE TITLE
import existing dkim certs

### ISSUE THREAD

**Issue by tonyguadagno** [modoboa/modoboa#1696]
hi, i am interested in moving an existing mail system to modoboa.  in the existing system, i have many domains with dkim already set up.  i do not want to go through the hassle of changing all the dns txt records so i would like to configure modoboa to use the existing dkim certs...

how can this be done?
thanks

**Comment by tonioo** [comment]
@tonyguadagno There is no easy way to do this right now. What you can do is create a dkim key for your domain in modoboa, replace the generated key by yours on the filesystem and empty the public key stored in database.

**Comment by tonyguadagno** [comment]
yes, i suspected i would need to edit the database.  i am familiar with mysql but not postgresql, how do i login in to postgresql and what table needs to be changed?

thanks

**Comment by tonioo** [comment]
I guess you should find a lot of articles explaining how to connect to a postgres database on the web. The table you need to modify is admin_domain.

**Comment by tonyguadagno** [comment]
sorry, i guess i should have been more specific...where do i find the postgres user password? so i can login?

thanks

**Comment by cremesk** [comment]
@tonyguadagno in the '/<path to modoboa>/instance/instance/settings.py' after line ~160 you can find the database informations.

**Comment by tonyguadagno** [comment]
yes, that's it! thanks
