### ISSUE TITLE
add ssl/tls certs to modoboa

### ISSUE THREAD

**Issue by tonyguadagno** [modoboa/modoboa#1697]
hi, i would like to add my signed cert to modoboa to be used for the web server gui as well as smtp/imap tls.  is there any docs on how this can be done?  i have looked and i don't see anything in the docs.

thanks

**Comment by tonioo** [comment]
@tonyguadagno there is no documentation about this at the moment. How did you install modoboa? What's your distrib?

**Comment by tonyguadagno** [comment]
i used the auto installer, i installed last week. i don't know how to tell the version.

thanks

**Comment by tonioo** [comment]
@tonyguadagno what your linux distribution?

**Comment by tonyguadagno** [comment]
sorry, centos 7, fully patched
btw, how do i tell the modoboa version?

**Comment by tonyguadagno** [comment]
hi, i found the information page, i am using modoboa 1.13.1

**Comment by tonioo** [comment]
For the web part, you'll find the configuration in /etc/nginx/conf.d/.
For the smtp part, it will be in /etc/postfix/main.cf
For the imap part, it will be in /etc/dovecot/conf.d/10-ssl.conf

**Comment by tonyguadagno** [comment]
thanks, this helped!

**Comment by Catospye** [comment]
I have the same question how do I add my own cert? I'm running **Ubuntu 18.04** and **modoboa 1.17.0**

**Comment by qupfer** [comment]
just for googlers like me:

put the certificate in `/etc/ssl/certs/DOMAIN.cert` and the key in `/etc/ssl/private/DOMAIN.key`
