### ISSUE TITLE
Quota never update 

### ISSUE THREAD

**Issue by augustodv** [modoboa/modoboa#1698]
# Impacted versions

* Modoboa: 1.12.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
define a quota of 10 mb and fill the mail and then delete them.
# Current behavior
list quota is never updated. The emails were cleaned within the accounts that were reaching the limit but still show the same capacity always after restarting.
# Expected behavior
Once the account has been emptied or its size reduced, it shows the correct size.

**Comment by augustodv** [comment]
I made the update to the latest version of all the components and the core and the problem persisted.

**Comment by tonioo** [comment]
@augustodv Which database engine to you use?

**Comment by kryskool** [comment]
>  Which database engine to you use?

Ping @augustodv
