### ISSUE TITLE
forward a email-address to a other server?

### ISSUE THREAD

**Issue by cremesk** [modoboa/modoboa#1704]
# Impacted versions

* Modoboa: 1.3.1
* installer used: Yes
* Webserver: Nginx

Hello,
Question.. how can i forward a email-address to a other server?
news@domain.com (mailman email on modoboa) -> to mailman-server ?

/etc/postfix/main.cf
```
mynetworks = 127.0.0.0/8 remote.postfix.ip.address
transport_maps = hash:/etc/postfix/transport
```
/etc/postfix/transport
```
news@domain.com smtp:[remote.postfix.ip.address]
```

**and**

```
postmap /etc/postfix/transport
service postfix restart
```
is that all i need?

Thank You so much

**Comment by tonioo** [comment]
@cremesk Yes, it is a good way to route an email address to another server.

**Comment by cremesk** [comment]
Thank you. I have test it this weekend. Works fine!

**Comment by cremesk** [comment]
hey @tonioo ,
I have a question about the forward. Everything works great so far!
Is there still a possibility to check the mail on spam before this forward?

`news@domain.com smtp:[remote.postfix.ip.address]`

thanks! =)

**Comment by cremesk** [comment]
Could it be that simply adding 'FILTER' is enough?

`news@domain.com FILTER smtp:[remote.postfix.ip.address]`
