### ISSUE TITLE
how do i configure relay settings?

### ISSUE THREAD

**Issue by tonyguadagno** [modoboa/modoboa#1705]
Hi, I am running Modoboa 1.31 using the installer on centos7 an nginx.

I need to allow devices on the local network to relay through the server without authenticating.  where is this configured?  is it really just a postfix config?  is this exposed in the gui?

thanks

**Comment by cremesk** [comment]
@tonyguadagno you need to add our 'remote-ip' to mynetworks in:

/etc/postfix/main.cf
`mynetworks = 127.0.0.0/8 remote-ip`

and
`systemctl reload postfix`

**Comment by tonyguadagno** [comment]
thanks for the info, that worked!
