### ISSUE TITLE
can webmail be the default after login

### ISSUE THREAD

**Issue by tonyguadagno** [modoboa/modoboa#1707]
hi, i am using modoboa 1.13.1 installed with the autoinstaller on centos7/nginx.

I have noticed that when users login, they land on the profile settings.  I would like them to land in webmail, is there a way to do this?

thanks

**Comment by tonioo** [comment]
@tonyguadagno yes, check online parameters, you find one name "Default top redirection".

**Comment by tonyguadagno** [comment]
great, thanks!
