### ISSUE TITLE
User unknown if from additional domain

### ISSUE THREAD

**Issue by hihachi123** [modoboa/modoboa#1708]
# Impacted versions

* Modoboa: 1.13.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Installed on a new server with the latest version pulled via git.
run.py run with first domain
added second domain
created user with email-address:

username@seconddomian.tld

and created user with 
username@firstdomain.tld

sent email to both email-adresses.

# Current behavior

User with domain which the installed run with (=firstdomain) recieves mail.
User with second domain does not:

username@seconddomain.tld:
SMTP error from remote server for RCPT TO command, host: mail.secondomain.tld (ip) reason: 550 5.1.1 <username@seconddomain.tld>: Recipient address rejected: undeliverab
le address: host mail.firstdomain.tld[private/dovecot-lmtp] said: 
550 5.1.1 <username@seconddomain.tld> User doesn't exist: username@seconddomain.tld (in reply to RCPT TO command)
# Expected behavior

User within additional domain should also receive emails and be known by the system.

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@hihachi123 Might a verify cache issue. Looks like you tried to send a message to this account before it was created. Postfix will then keep a cache entry for a given amount of time... You can wait for cache expiration or remove the cache file. See http://www.postfix.org/verify.8.html for more info.

**Comment by hihachi123** [comment]
Hi there,

that did the trick!

Thanks!

Greetings

Marcel 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 25.03.19, 16:08, Antoine Nguyen <notifications@github.com> schrieb:
@hihachi123 Might a verify cache issue. Looks like you tried to send a message to this account before it was created. Postfix will then keep a cache entry for a given amount of time... You can wait for cache expiration or remove the cache file. See http://www.postfix.org/verify.8.html for more info.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/modoboa/modoboa","title":"modoboa/modoboa","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/modoboa/modoboa"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tonioo in #1708: @hihachi123 Might a verify cache issue. Looks like you tried to send a message to this account before it was created. Postfix will then keep a cache entry for a given amount of time... You can wait for cache expiration or remove the cache file. See http://www.postfix.org/verify.8.html for more info."}],"action":{"name":"View Issue","url":"https://github.com/modoboa/modoboa/issues/1708#issuecomment-476238985"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/modoboa/modoboa/issues/1708#issuecomment-476238985",
"url": "https://github.com/modoboa/modoboa/issues/1708#issuecomment-476238985",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
