### ISSUE TITLE
old version postfix, anyone using postfix 3?

### ISSUE THREAD

**Issue by tonyguadagno** [modoboa/modoboa#1709]
hi, i set up a modoboa 1.13.1 server using the autoinstall script on centos 7.  i noticed that the postfix version provided by centos7 is really old, (2.10).  I am interested in getting postfix 3.x on my server, does anyone know of any issue with postfix 3 and modoboa?  do i need to worry about compatibility?

thanks

**Comment by tonioo** [comment]
@tonyguadagno Modoboa works fine with postfix 3+.

**Comment by tonyguadagno** [comment]
thanks for the info
