### ISSUE TITLE
Change the Favicon of Modoboa

### ISSUE THREAD

**Issue by JustSquiddy** [modoboa/modoboa#1711]
Hi,
is ist possible to change the favicon of the mail server?
Thanks!

**Comment by tonioo** [comment]
@JustSquiddy There is no builtin way to change the favicon. I guess you can replace it using a apache/nginx rewrite rule.

**Comment by Anky-DH** [comment]
> Hi, is ist possible to change the favicon of the mail server? Thanks!

Hi
did you find the way to change favicon ? 
while sharing url in whatsapp, favicon looking bad, i want to change it.
