### ISSUE TITLE
Postfix and dovecot sub addressing

### ISSUE THREAD

**Issue by willfurnell** [modoboa/modoboa#1713]
Hi,
I've been looking into sub addressing with Modoboa and Postfix. I can see that the 'recipient_delimiter = +' parameter is there, and recieveing emails works fine to addresses like mail+test@example.com. 

However, I'd like the message sent to this address go to a folder called test (either inside or outside the INBOX folder). Looking at this stackoverflow post, adding the -m argument to dovecot would put it in a folder. https://serverfault.com/questions/748182/dovecot-plus-sign-in-mailbox-name

Is there any reason why I couldn't replace the maildrop line with a dovecot one, or is that used with spam filtering etc. If I can't change maildrop to dovecot, do you know how I could achieve this functionality?

Thank you very much!

**Comment by tonioo** [comment]
@willfurnell Have you tried with a sieve filter?

**Comment by willfurnell** [comment]
I've had a look at the sieve filters interface, but I can't see how to match on +<variable> and then put it in the folder <variable> - as you can't get the <variable> part out?

**Comment by willfurnell** [comment]
Is there some way to enter plain raw text in the interface? In that case I could probably write a filter for it. :)

**Comment by tonioo** [comment]
@willfurnell Yes. Go to user preferences, sieve tab and select raw format for editor.
