### ISSUE TITLE
Domain Admin cannot add users: Quota Limit Reached

### ISSUE THREAD

**Issue by JPerryJr** [modoboa/modoboa#1717]
# Impacted versions

* Modoboa: 1.13.1
* installer used: Yes
* Webserver: Nginx
* Database: Postgresql w/additional steps followed (Default, Trigger, etc)

# Steps to reproduce
Create a domain (e.g. na.example.com)
Create multiple domain admins (e.g. bill@na.example.com, joe@na.example.com)
Log in as Bill@na.example.com and attempt to create a new regular user/mailbox.  Mailboxes: limit reached

# Current behavior
Error message "Mailboxes: limit reached" occurs when you hit submit.

# Expected behavior
Add new regular user/mailbox.

# Video/Screenshot link (optional)
![image](https://user-images.githubusercontent.com/32584892/56011369-eeadab00-5cac-11e9-9a88-e71ea5a82240.png)

![image](https://user-images.githubusercontent.com/32584892/56011409-1997ff00-5cad-11e9-8ab0-e0cda08f56c8.png)

![image](https://user-images.githubusercontent.com/32584892/56011544-ba86ba00-5cad-11e9-953d-85cbf55e1056.png)

**Comment by tonioo** [comment]
@JPerryJr Can you check the limits defined for the user you're using?

**Comment by JPerryJr** [comment]
I'm logged in as admin (superadmin) when I get the error.  Is there another way to do this?

**Comment by JPerryJr** [comment]
I figured it out.  I went back and removed all quotas at the domain level.

Thx

**Comment by jawwadnaeem** [comment]
@JPerryJr Can you share screenshot of your settings that worked as i am facing the same issue

**Comment by tcjn** [comment]
<img width="820" height="816" alt="Image" src="https://github.com/user-attachments/assets/34192072-59a2-4e68-8bfe-2609ab157a60" />

<img width="1310" height="262" alt="Image" src="https://github.com/user-attachments/assets/9ab26d39-b0b7-4b11-8275-0b28cc631049" />

Seems like issue still exist - as domain administrator I cannot create new account due to above error. I was trying to set -1, 999 and result is the same.

**Comment by tonioo** [comment]
@tcjn And if you turn off the switch?

**Comment by tcjn** [comment]
> [@tcjn](https://github.com/tcjn) And if you turn off the switch?

Then it works,  I am going to use unlimited approach. Just saying it's not resolved imho.

**Comment by tonioo** [comment]
@tcjn Ok, I'll take a look at this but at least you're not stuck.

**Comment by tcjn** [comment]
> [@tcjn](https://github.com/tcjn) Ok, I'll take a look at this but at least you're not stuck.

Thanks a lot ;)

**Comment by tonioo** [comment]
@tcjn Have you actually checked what are the limits defined AT the admin level directly? Because those global limits are only applied at account creation time

**Comment by tcjn** [comment]
> [@tcjn](https://github.com/tcjn) Have you actually checked what are the limits defined AT the admin level directly? Because those global limits are only applied at account creation time

I would say yes. IMHO by default it does not work as it should. I do not use them anyway so for me its not an issue ;-)
