### ISSUE TITLE
Internal Error when trying to open mail with attached files with accent mark on filenames

### ISSUE THREAD

**Issue by sibuxiang** [modoboa/modoboa#1719]
# Impacted versions

* Modoboa: 1.31.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Send a pdf file with a name including an accent mark on vowel (Ex. canción)

The email receiver(modoboa user) can't open the mail getting a little box saying "internal error"

This is a problem when spanish speaking clients are using the mail client, sending and receiving files with accent marks is frequent.

# Current behavior

# Expected behavior

It should open the mail normally

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@sibuxiang Can you please move this issue to the right repository please? (https://github.com/modoboa/modoboa-webmail)

**Comment by sibuxiang** [comment]
Wrong repo. Sorry
