### ISSUE TITLE
Remove bad.psky.me from DNSBL providers

### ISSUE THREAD

**Issue by yannfill** [modoboa/modoboa#1721]
You should remove bad.psky.me from DNSBL providers list. It was [fishy at first](https://www.spamhaus.org/organization/statement/015/fraudulent-dnsbl-uncovered-protected-sky-bad.psky.me) and now the domain seems to have been drop catched, with website displaying a parking page. It then results in false alert in Modoboa RBL check.

**Comment by Lucidi0us** [comment]
Today I had about 13 emails from Modoboa about bad.psky.me DNSBL check.  I agree with @yannfill that this one needs to go.  It was considered fraudulent for a while (see: https://www.spamhaus.org/organization/statement/015/fraudulent-dnsbl-uncovered-protected-sky-bad.psky.me ).

**Comment by ewenjo** [comment]
I agree with this. Got tons of emails yesterday that my private IPs were listed by them, which are false positives.

**Comment by dugite-code** [comment]
For thoes waiting you can manually disable a DNSBL in the `settings.py by adding the following snipit:

```python
# fix broken DNSBLs
from modoboa.admin.constants import DNSBL_PROVIDERS
DNSBL_PROVIDERS.remove("bad.psky.me")
```
From: https://github.com/modoboa/modoboa/issues/1496#issue-326768587

**Comment by dym-sh** [comment]
/rel https://hetrixtools.com/forum#/discussion/91/bad-psky-me-inactive-removed

**Comment by almereyda** [comment]
Is the solution via `settings.py` to be preferred over the solution presented in the PRs #1722 #1723 #1724?

**Comment by dugite-code** [comment]
@almereyda the `settings.py` solution is just while you wait to update to the next version of modoboa. It's just how you can customize you DSNBL for you individual system.

**Comment by almereyda** [comment]
#1722 has been merged. Can this be closed?

**Comment by warsix4** [comment]
Supposedly this is fixed, however I am getting notified about this every few hours still with a fresh installation. Any reason it's persisted still?

**Comment by tonioo** [comment]
@warsix4 Because it has not been released yet.
