### ISSUE TITLE
Can't edit domain

### ISSUE THREAD

**Issue by lmfrazao** [modoboa/modoboa#1728]
# Impacted versions

* Modoboa: 1.13.1
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce
edit domain, change anything and press update

# Current behavior
nothing happens, and doesn't save changed items or values, and window continues open

# Expected behavior
close window and save domain definitions

How can I debug this ?

thanx.

**Comment by borisdigital** [comment]
Hm, sounds like my problem here.
There is exactly one domain (my first/main) which can't be updated/edited.

I tried the following from this comment in another thread, which didn't do the trick for me.
https://github.com/modoboa/modoboa/issues/1289#issuecomment-343240019

I'm also looking for an easy way to get some debug info or helping logs.

**Comment by tonioo** [comment]
@lmfrazao @borisdigital You can set DEBUG to True inside the settings.py file, reload uwsgi and then open the debugger of your browser and look at the network tab. Look for requests returning a 500 code and check the response content please.

**Comment by borisdigital** [comment]
Hey @tonioo, thanks for your help in advance. This is what i'm getting in the debug/network tab.

DoesNotExist at /admin/domains/1/edit/
Users matching query does not exist.
...
(check attachment for full message)

[modoboa.log](https://github.com/modoboa/modoboa/files/3194044/modoboa.log)

**Comment by lmfrazao** [comment]
on my side this is what's happening:
DoesNotExist at /admin/domains/115/edit/
Users matching query does not exist.

**Comment by lmfrazao** [comment]
**update:**
what I was trying to do was activating the DKIM for a domain, on new domains is ok, on older isn't.
but, if I open the domain, press update, 
and then when I activate DKIM, it worked.

from what it seems, on second time you press update it starts working.

Before this was working I did the steps here: [https://github.com/modoboa/modoboa/issues/1289#issuecomment-343240019](url)
