### ISSUE TITLE
DNSBL bad.psky.me

### ISSUE THREAD

**Issue by DPR1604** [modoboa/modoboa#1735]
# Impacted versions

* Modoboa: 1.13.1
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce
Run DNSBL check

# Current behavior
Showing listed in bad.psky.me
# Expected behavior
Not showing to be listed as with everywhere else 
# Video/Screenshot link (optional)

To add to this you may want to remove the Database from your checks as it was found to be Fraudulent by spamhaus https://www.spamhaus.org/organization/statement/015/fraudulent-dnsbl-uncovered-protected-sky-bad.psky.me their site is also down.

**Comment by dugite-code** [comment]
Duplicate https://github.com/modoboa/modoboa/issues/1721
