### ISSUE TITLE
Cron error manage.py modo check_mx error since 1.13.1

### ISSUE THREAD

**Issue by koper89** [modoboa/modoboa#1736]
# Impacted versions

* Modoboa: 1.13.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Upgraded from 1.12.0 to 1.13.1

# Current behavior
Got cron error every 30 minutes:

> Traceback (most recent call last):
>   File "/srv/modoboa/instance/manage.py", line 22, in <module>
>     execute_from_command_line(sys.argv)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
>     utility.execute()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/subcommand/base.py", line 53, in run_from_argv
>     return super(SubcommandCommand, self).run_from_argv(argv)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
>     output = self.handle(*args, **options)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/subcommand/base.py", line 84, in handle
>     return command.run_from_argv(argv)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
>     output = self.handle(*args, **options)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 264, in handle
>     self.check_domain(domain, **options)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 199, in check_domain
>     domain, "spf", ttl)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/dnstools/models.py", line 26, in get_or_create_for_domain
>     domain=domain, type=rtype, updated__gt=now).first()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 567, in first
>     objects = list((self if self.ordered else self.order_by('pk'))[:1])
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
>     self._fetch_all()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
>     self._result_cache = list(self._iterable_class(self))
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
>     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
>     raise original_exception
> django.db.utils.ProgrammingError: (1146, "Table 'modoboa.dnstools_dnsrecord' doesn't exist")

# Expected behavior
No error

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@koper89 Please run upgrade instructions:
https://modoboa.readthedocs.io/en/latest/upgrade.html#modoboa
