### ISSUE TITLE
Bad Request (HTTP 400)

### ISSUE THREAD

**Issue by DamonOnYT** [modoboa/modoboa#1740]
# Impacted versions

* Modoboa: latest
* installer used: Yes
* Webserver: Apache

# Steps to reproduce
go to the web link
# Current behavior
error message
# Expected behavior
login screen

I would like to note i changed the port to 44

**Comment by tonioo** [comment]
@DamonOnYT Can you check that the value listed in the ALLOWED_HOSTS variable (/srv/modoboa/instance/instance/settings.py) is the same than the address you use to access the web interface?

**Comment by DamonOnYT** [comment]
@tonioo I just checked and it was incorrect. I changed it but I'm still experiencing the issue.

**Comment by DamonOnYT** [comment]
I just rebooted my vm and it worked. Is there a default set of credentials?

**Comment by DamonOnYT** [comment]
Now im getting a different error.
![Screenshot](https://user-images.githubusercontent.com/20586245/58940883-00e42b00-87be-11e9-8396-35ae41dc24c6.png)

**Comment by tonioo** [comment]
@DamonOnYT Refresh the login page, it happens sometimes...

**Comment by DamonOnYT** [comment]
@tonioo i have refreshed it multiple times and it keeps showing

**Comment by DamonOnYT** [comment]
Got it to work, I had to use https. Also im making another issue since its not related to this.
