### ISSUE TITLE
Catch all sender address not working

### ISSUE THREAD

**Issue by y0va** [modoboa/modoboa#1742]
# Impacted versions

* Modoboa: 1.13.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Create a account `notifications@domain.tld` with a sender adress catchall like `@domain.tld`.

Try to send a mail using `user@domain.tld` with smtp eg with nullmailer.

# Current behavior
The message is rejected:

    Jun  5 23:45:19 strix nullmailer[8356]: smtp: Failed: 553 5.7.1 <user@domain.tld>: Sender address rejected: not owned by user notifications@domain.tld

# Expected behavior
The message is accepted

Maybe a continuation of #1580.

**Comment by tonioo** [comment]
@y0va Indeed, the SQL query used to find valid sender addresses does not support catchall syntax.
