### ISSUE TITLE
4.3.0 Error: queue file write error.

### ISSUE THREAD

**Issue by DamonOnYT** [modoboa/modoboa#1745]
# Impacted versions

* Modoboa: latest
* installer used: Yes
* Webserver: Apache

# Steps to reproduce
Try to send an email using any email client
Webmail just dosent do anything when i press send
# Current behavior
Gives error
# Expected behavior
Sends email
# Video/Screenshot link (optional)
![Screen Shot 2019-06-10 at 7 57 12 pm](https://user-images.githubusercontent.com/20586245/59187979-fe1c7800-8bb9-11e9-8840-47de048bd6a0.png)

**Comment by tonioo** [comment]
@DamonOnYT Please check mail logs, you should find more explicit errors.

**Comment by tonioo** [comment]
@DamonOnYT Any news?

**Comment by DamonOnYT** [comment]
Sorry, havent checked my github recently. How do I find my mail logs?

**Comment by fpiccinali** [comment]
@DamonOnYT 

Have a look at /var/log/mail.log or /var/log/mail.err 

Does you disk have enough space ? 

Try `df -h` to see available space

If it is ok for you, can you close this issue ?
