### ISSUE TITLE
MSRBL returns false positives and is unresponsive

### ISSUE THREAD

**Issue by y0va** [modoboa/modoboa#1746]
Users report false positives from MSRBL: https://lab.allmende.io/ecobytes/lab/mx/issues/72 and it's currently not possible to edit their db: http://www.msrbl.com/check-db

Why I disabled it according to https://github.com/modoboa/modoboa/issues/1496#issue-326768587

**Comment by niko-lay** [comment]
looks like they already updated domain

**Comment by tonioo** [comment]
Check : https://github.com/modoboa/modoboa/pull/1748
