### ISSUE TITLE
UnicodeEncodeError at /webmail/

### ISSUE THREAD

**Issue by Artur236** [modoboa/modoboa#1747]
* Modoboa: 1.13.1
* installer used: Yes
* Webserver: Nginx

1. When trying to add signature with default HTML editor (with default TEXT editor all is ok) in Russian or Ukrainian languages, I've got next error
```
Exception Value: 'ascii' codec can't encode character u'\u0421' in position 25: ordinal not in range(128)
Exception Location: /srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/lib/signature.py in _format_sig_html, line 26
```

2. If I insert an attachment to email and the name of it contains Russian or Ukrainian symbols, I've got next issue
```
Exception Value: 'ascii' codec can't encode characters in position 7-17: ordinal not in range(128)
Exception Location: /usr/lib/python2.7/urllib.py in urlencode, line 1342
```

**Comment by VPuks** [comment]
Hi,
Is any progress?

I got the same issue:

Modoboa version: 1.14.0
Modoboa webmail version: 1.5.0

Also when You try open message with attachment who contains utf-8 symbols Youe get "Internal error" on screen. 

Admin get mail with following error message: 

UnicodeEncodeError at /webmail/
'ascii' codec can't encode character u'\u0113' in position 17: ordinal not in range(128)

Request Method: | GET
Request URL:  ---- hidden ---- 
Django Version: 1.11.23
Exception Type: UnicodeEncodeError
Exception Value: 'ascii' codec can't encode character u'\u0113' in position 17: ordinal not in range(128)
Exception Location: /usr/lib64/python2.7/urllib.py in urlencode, line 1326
Python Executable: /usr/sbin/uwsgi
Python Version: 2.7.5
Python Path: ['.',  '',  '/srv/modoboa/env/lib64/python27.zip',  '/srv/modoboa/env/lib64/python2.7',  '/srv/modoboa/env/lib64/python2.7/plat-linux2',  '/srv/modoboa/env/lib64/python2.7/lib-tk',  '/srv/modoboa/env/lib64/python2.7/lib-old',  '/srv/modoboa/env/lib64/python2.7/lib-dynload',  '/usr/lib64/python2.7',  '/usr/lib/python2.7',  '/srv/modoboa/env/lib/python2.7/site-packages']
Server time: 

-----
Regards.

**Comment by tonioo** [comment]
https://github.com/modoboa/modoboa-webmail/issues/189
