### ISSUE TITLE
can't receive emails

### ISSUE THREAD

**Issue by fusenn** [modoboa/modoboa#1750]
# Impacted versions

* Modoboa: 1.13.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Used installer and set up as usual. I'm at a loss. All steps taken.

# Current behavior

can send emails no problem, just can't receive them and the strange thing is there is no reject messages in the logs. I have checked all dns settings and everything is correct.

# Expected behavior

sending emails from modoboa install

I really am at a loss to this and it is probably something simple. I've done this before and never had this issue. All solutions i've found so far have not worked. All ports are 100% open.

**Comment by tonioo** [comment]
@fusenn Have you checked your DNS setup is complete?

**Comment by fusenn** [comment]
Yes dns is set up as mentioned above. The only thing i can think of is port 25 being blocked by isp

**Comment by tonioo** [comment]
@fusenn Indeed, it's a possibility.

**Comment by aaronesteban1** [comment]
Was this issue ever resolved? After installing Mautic over Modoboa, my Modoboa no longer receives email. It's still able to send, but not receive. I know that my DNS records are properly configured. I've tried to restart postfix, amavis, clam, SpamAssassin, and others, but it still won't receive messages. Any idea what could be causing this?
