### ISSUE TITLE
E-mail does not arrive at Freenet

### ISSUE THREAD

**Issue by codiergott** [modoboa/modoboa#1753]
# Impacted versions

* Modoboa: 1.13.1
* installer used: Yes
* Webserver: Nginx

I have a coming phenomenon. I can send and receive emails. But if I send an e-mail to freenet, it does not arrive. It is neither in the Spam-order, nor comes a response from Freenet.

**Comment by tonioo** [comment]
@codiergott Have you checked if your server IP is not blacklisted somewhere?

**Comment by NineSeven8** [comment]
Test your domain on MXTOOLBOX and see if you are blacklisted
Also if you are using some sort of dynamic A records, list will black list you just for the fact that your address is constantly changing ip address.

**Comment by codiergott** [comment]
Hello, Thanks for the feedback. The server has a fixed IP and is not blacklisted.

**Comment by tonioo** [comment]
@codiergott Don't you have any information from Freenet about this kind of issue?

**Comment by Clevero** [comment]
@codiergott 

Did you create a PTR/rDNS record?
Please check against "FCrDNS" at http://multirbl.valli.org/

You can also check your setup with https://www.mail-tester.com/

**Comment by codiergott** [comment]
I have an answer from Freenet now.

Answer: 550 inconsistent / missing DNS PTR record (RFC 1912 2.1)

I have an understanding question. For example, if the mail server address is xxx@server1.com. Under Modoboa I deposited a domain server2.de. And I send now for example an email from mail@server1.de over the account mail@server2.de.

Do you get this error?

**Comment by tonioo** [comment]
@codiergott no because the two domains are hosted on the same system.
