### ISSUE TITLE
Alias to external address without local delivery?

### ISSUE THREAD

**Issue by mixabo** [modoboa/modoboa#1755]
Hello,

My question in short:

Is it possible to set up an alias to forward emails to an external address without local delivery?

In more detail:

Suppose I manage the domain _example.com_ with Modoboa. I have a simple account _user@example.com_ and an alias _alias@example.com_ forwarding emails to _someuser@some-other-domain.com_.

I want to set up the alias to forward emails to the external address and skip local delivery to the account user@example.com.

Is this possible?

I want to set up other accounts and aliases for the same domain with local delivery.

I'm using:
* Modoboa: 1.13.1

I seem to remember this could be achieved in some earlier Modoboa versions. It might have been before the merger of _forward_ and _alias_?

Thank you,

Miklos

**Comment by tonioo** [comment]
There is a bug opened about this: https://github.com/modoboa/modoboa/issues/1356.

**Comment by npsimons** [comment]
I am interested in this feature as well, as I administer a couple of domains where all they do for email is forward to real email addresses.

**Comment by kryskool** [comment]
Hi @mixabo 

The bug is fixed, can you test and confirm ?

Regards,

**Comment by tonioo** [comment]
I confirm, this problem should be fixed now.
