### ISSUE TITLE
Add support for 2FA

### ISSUE THREAD

**Issue by JackApple1337** [modoboa/modoboa#1760]
# Impacted versions

* Modoboa: Latest
* installer used: Yes
* Webserver: Nginx/Apache

# Current behavior
Not integrated

# Expected behavior
Integrated and usable

# Notes
First of all, I love the Moboda appliance but due to some security concerns of my Users and me, I wanted to ask, if there are some plans to integrate 2F/A for the Webmail like via Google Authenticator or some other Apps.
Or is there already a possibility to integrate it?

Best Regards
Jack

**Comment by CyberfoxDK** [comment]
I have suggested this earlier, I think it is an essential security feature.
For other interested, remember to sponsor this feature.

https://modoboa.org/en/projects/10/
