### ISSUE TITLE
admin page not accessible after install

### ISSUE THREAD

**Issue by alexglvr** [modoboa/modoboa#1769]
# Impacted versions

* installer used: Yes
* Webserver: Apache

# Steps to reproduce installation tutorial : https://www.linuxbabe.com/mail-server/email-server-ubuntu-18-04-modoboa

# Current behavior : https://mail.mydomain.com : CONNECTION REFUSED

# Expected behavior

# Video/Screenshot link (optional)

Hello,

After the installation (https://www.linuxbabe.com/mail-server/email-server-ubuntu-18-04-modoboa), I get the phrase : Congratulations! You can enjoy Modoboa at https://mail.mydomain.com (admin:password)
But the url returns ERR_CONNECTION_REFUSED

what did i miss?

Thank you for your help

**Comment by blackhold** [comment]
see logs at /var/log/uwsgi/

**Comment by alexglvr** [comment]
here are the logs I have in /var/log/uwsgi/app :
[automx_instance.log](https://github.com/modoboa/modoboa/files/3489786/automx_instance.log)
[modoboa_instance.log](https://github.com/modoboa/modoboa/files/3489787/modoboa_instance.log)

**Comment by alexglvr** [comment]
apparently I have a problem with Apache / Nginx conflict.
What are the configurations to do to make it work with apache?

**Comment by blackhold** [comment]
use different ports for each web-server
