### ISSUE TITLE
Mailbox aliases: limit reached, even though limits are -1 or 99999

### ISSUE THREAD

**Issue by erenfro** [modoboa/modoboa#1770]
# Impacted versions

* Modoboa: 1.14.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
As Modoboa Global Admin:
Modoboa->Parameters->Limits:
  Enable per-admin limits: Yes
  Mailboxes: -1
  Mailbox aliases: -1
  Enable per-domain limits: Yes
  Mailboxes: -1
  Mailbox aliases: -1
Domains-><domain>->Edit->Resources:
  Mailboxes: -1
  Mailbox aliases: -1

As DomainAdmins user:
  Identities-><user>->Mail:
    Try to add a 4th alias to the account. It will return: Mailbox aliases: limit reached with Update.

As Modoboa Global Admin (again):
Modoboa->Parameters->Limits:
  Enable per-admin limits: Yes
  Mailboxes: -1
  Mailbox aliases: 99999
  Enable per-domain limits: Yes
  Mailboxes: -1
  Mailbox aliases: 99999
Domains-><domain>->Edit->Resources:
  Mailboxes: -1
  Mailbox aliases: 99999

As DomainAdmins user:
  Identities-><user>->Mail:
    Try to add a 4th alias to the account. It will return: Mailbox aliases: limit reached with Update.

# Current behavior
Mailbox aliases: limit reached, on Update adding a 4th alias to a single mailbox account.

# Expected behavior
Mailbox alias is added per actual limits settings, or unlimited setting.

# Video/Screenshot link (optional)
Global Admin:
* http://i.imgur.com/9MHrOyL.png
* http://i.imgur.com/4BEZjYB.png

DomainAdmins:
* http://i.imgur.com/D84Vefa.png

**Comment by tonioo** [comment]
@erenfro Just one thing : changing default values won't affect existing domains or accounts. Have you checked the values actually defined for you domain admin before you make your tests?
