### ISSUE TITLE
Adding a user gets a "500 Internal server error"

### ISSUE THREAD

**Issue by twagener** [modoboa/modoboa#1771]
# Impacted versions

* Modoboa: 1.14.0
* installer used: Yes/No ?
* Webserver: Nginx/Apache

# Steps to reproduce
Every python package up to date

# Current behavior
Ajax call gets server response 500

# Solution
change line 886 in /srv/modoboa/env/local/lib/python2.7/site-packages/reportlab/lib/utils.py
FROM:
if Image.VERSION.startswith('1.1.7'): im.load()
TO:
if Image.`__version__`.startswith('1.1.7'): im.load()

Because the new module has no attribute VERSION. The correct usage is `__version__`

Hope this helps anyone

**Comment by tonioo** [comment]
Can you provide a trace or something useful to understand the issue?

**Comment by tonioo** [comment]
Looks like it has been fixed on reportlab's side.
