### ISSUE TITLE
DKIM signature missing from outgoing emails [ was working fine earlier]

### ISSUE THREAD

**Issue by AisselTechnologiesPvtLtd** [modoboa/modoboa#1773]
# Impacted versions

* Modoboa: 1.13.1
* installer used: Yes 
* Webserver: Nginx

# Steps to reproduce
Send an email from the webmail or email client, the DKIM signature will be missing.

# Current behavior
Starting today, the DKIM signature is missing from all the outbound emails. While in the Domains Tab, the DKIM and all other show green and the DKIM matches with what I have added in the TXT record. I also tried testing with the SPF and DKIM testing websites e.g https://www.appmaildev.com/en/dkim and in those cases also the DKIM signature status is No Signature. “DKIM-Result: none (no signature)”. Till yesterday 8/29 all emails were fine so was the DKIM, not sure what when wrong today. I even restarted the server hoping any blocked processes doing this but no hope.

# Expected behavior
The DKIM signature should be present in the outbound email.

# Video/Screenshot link (optional)
Installed Modules and versions
![image](https://user-images.githubusercontent.com/18698211/64028289-fbe60c00-cb5f-11e9-8549-24390ecfd83c.png)
List Domains page with DNS status
![image](https://user-images.githubusercontent.com/18698211/64028321-115b3600-cb60-11e9-8aa9-24e34739bb39.png)

**Comment by AisselTechnologiesPvtLtd** [comment]
On further research found out the DKIM service had stopped on the server. Not sure why or how. After restarting the service the DKIM signatures are again appearing in the emails.

**Comment by gregorypilar** [comment]
Hi!, how you you started it?

**Comment by AisselTechnologiesPvtLtd** [comment]
Started it using the below command

`sudo service opendkim start`

**Comment by slowaways** [comment]
> Started it using the below command
> 
> `sudo service opendkim start`

I have the same problema but this solution not work for me.
