### ISSUE TITLE
Switching Languages Failure

### ISSUE THREAD

**Issue by ihmc3jn09hk** [modoboa/modoboa#1774]
#Impacted versions

* Modoboa: 1.14.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Profile->Lanuage->Update

# Current behavior
Failure for non-English languages

# Expected behavior
Languages switch

# Video/Screenshot link (optional)

_Switching language in the WebGUI is not working. Turned on DEBUG=True and the following responses are returned._
Moreover, the "Trash" button in the "Trash" folder is not enabled even some items are selected.

`
ValueError at /user/profile/
unexpected end of plural form //or 'list index out of range'

Request Method: POST
Request URL: https://192.168.1.2:4443/user/profile/
Django Version: 1.11.23
Python Executable: /usr/bin/uwsgi-core
Python Version: 2.7.15
Python Path: ['.', '', '/srv/modoboa/env/lib/python2.7', '/srv/modoboa/env/lib/python2.7/plat-x86_64-linux-gnu', '/srv/modoboa/env/lib/python2.7/lib-tk', '/srv/modoboa/env/lib/python2.7/lib-old', '/srv/modoboa/env/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/srv/modoboa/env/local/lib/python2.7/site-packages', '/srv/modoboa/env/lib/python2.7/site-packages']
Server time: Sun, 8 Sep 2019 19:58:32 +0800
Installed Applications:
(u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.sessions',
 u'django.contrib.messages',
 u'django.contrib.sites',
 u'django.contrib.staticfiles',
....
`

**Comment by tonioo** [comment]
Can you please paste the full trace?

**Comment by ihmc3jn09hk** [comment]
> Can you please paste the full trace?

Here you are:
`
ValueError at /user/profile/
unexpected end of plural form

Request Method: POST
Request URL: https://192.168.1.2:4443/user/profile/
Django Version: 1.11.23
Python Executable: /usr/bin/uwsgi-core
Python Version: 2.7.15
Python Path: ['.', '', '/srv/modoboa/env/lib/python2.7', '/srv/modoboa/env/lib/python2.7/plat-x86_64-linux-gnu', '/srv/modoboa/env/lib/python2.7/lib-tk', '/srv/modoboa/env/lib/python2.7/lib-old', '/srv/modoboa/env/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/srv/modoboa/env/local/lib/python2.7/site-packages', '/srv/modoboa/env/lib/python2.7/site-packages']
Server time: Mon, 9 Sep 2019 18:59:03 +0800
Installed Applications:
(u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.sessions',
 u'django.contrib.messages',
 u'django.contrib.sites',
 u'django.contrib.staticfiles',
 u'reversion',
 u'ckeditor',
 u'ckeditor_uploader',
 u'rest_framework',
 u'rest_framework.authtoken',
 u'modoboa',
 u'modoboa.core',
 u'modoboa.lib',
 u'modoboa.admin',
 u'modoboa.transport',
 u'modoboa.relaydomains',
 u'modoboa.limits',
 u'modoboa.parameters',
 u'modoboa.dnstools',
 u'modoboa_amavis',
 u'modoboa_pdfcredentials',
 u'modoboa_postfix_autoreply',
 u'modoboa_sievefilters',
 u'modoboa_stats',
 u'modoboa_webmail',
 u'modoboa_contacts',
 u'modoboa_radicale',
 'webpack_loader')
Installed Middleware:
(u'x_forwarded_for.middleware.XForwardedForMiddleware',
 u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'django.middleware.locale.LocaleMiddleware',
 u'django.middleware.clickjacking.XFrameOptionsMiddleware',
 u'modoboa.core.middleware.LocalConfigMiddleware',
 u'modoboa.lib.middleware.AjaxLoginRedirect',
 u'modoboa.lib.middleware.CommonExceptionCatcher',
 u'modoboa.lib.middleware.RequestCatcherMiddleware')


Traceback:  

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/views/user.py" in profile
  48.             translation.activate(request.user.language)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/translation/__init__.py" in activate
  166.     return _trans.activate(language)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py" in activate
  239.     _active.value = translation(language)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py" in translation
  228.         _translations[language] = DjangoTranslation(language)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py" in __init__
  129.             self._add_installed_apps_translations()

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py" in _add_installed_apps_translations
  177.                 translation = self._new_gnu_trans(localedir)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py" in _new_gnu_trans
  156.             fallback=use_null_fallback)

File "/usr/lib/python2.7/gettext.py" in translation
  569.                 t = _translations.setdefault(key, class_(fp))

File "/usr/lib/python2.7/gettext.py" in __init__
  255.             self._parse(fp)

File "/usr/lib/python2.7/gettext.py" in _parse
  391.                         self.plural = c2py(plural)

File "/usr/lib/python2.7/gettext.py" in c2py
  177.         result, nexttok = _parse(_tokenize(plural))

File "/usr/lib/python2.7/gettext.py" in _parse
  120.         sub, nexttok = _parse(tokens)

File "/usr/lib/python2.7/gettext.py" in _parse
  154.         if_false, nexttok = _parse(tokens)

File "/usr/lib/python2.7/gettext.py" in _parse
  154.         if_false, nexttok = _parse(tokens)

File "/usr/lib/python2.7/gettext.py" in _parse
  154.         if_false, nexttok = _parse(tokens)

File "/usr/lib/python2.7/gettext.py" in _parse
  151.         if_true, nexttok = _parse(tokens, 0)

File "/usr/lib/python2.7/gettext.py" in _parse
  130.             raise _error(nexttok)

Exception Type: ValueError at /user/profile/
Exception Value: unexpected end of plural form
Request information:
USER: xxxxxxxxxxxxxxxxxxxx

GET: No GET data

POST:
phone_number = u''
first_name = u'xxxx'
last_name = u''
language = u'br'
secondary_email = u''
confirmation = u''
newpassword = u''
oldpassword = u''
csrfmiddlewaretoken = u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

FILES: No FILES data

COOKIES:
csrftoken = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
sessionid = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

META:
CONTENT_LENGTH = '193'
CONTENT_TYPE = 'application/x-www-form-urlencoded; charset=UTF-8'
CSRF_COOKIE = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
DOCUMENT_ROOT = '/srv/modoboa/instance'
HTTPS = 'on'
HTTP_ACCEPT = '*/*'
HTTP_ACCEPT_ENCODING = 'gzip, deflate, br'
HTTP_ACCEPT_LANGUAGE = 'en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7,ja;q=0.6'
HTTP_CACHE_CONTROL = 'no-cache'
HTTP_CONNECTION = 'close'
HTTP_CONTENT_LENGTH = '193'
HTTP_CONTENT_TYPE = 'application/x-www-form-urlencoded; charset=UTF-8'
HTTP_COOKIE = 'csrftoken=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; csrftoken=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; sessionid=xxxxxxxxxxxxxxxxxxxxxxxxxxx'
HTTP_HOST = '192.168.1.2:4443'
HTTP_ORIGIN = 'https://dontworryaboutit.domain.com'
HTTP_PRAGMA = 'no-cache'
HTTP_REFERER = 'https://dontworryaboutit.domain.com'
HTTP_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36'
HTTP_X_CSRFTOKEN = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
HTTP_X_REQUESTED_WITH = 'XMLHttpRequest'
PATH_INFO = u'/user/profile/'
QUERY_STRING = ''
REMOTE_ADDR = '10.0.2.2'
REMOTE_PORT = '60654'
REQUEST_METHOD = 'POST'
REQUEST_SCHEME = 'https'
REQUEST_URI = '/user/profile/'
SCRIPT_NAME = u''
SERVER_NAME = 'dontworryaboutit.domain.com'
SERVER_PORT = '4443'
SERVER_PROTOCOL = 'HTTP/1.0'
UWSGI_APPID = '192.168.1.2:4443|'
UWSGI_SCRIPT = 'instance.wsgi:application'
uwsgi.node = 'DontWorryAboutIt'
uwsgi.version = '2.0.15-debian'
wsgi.errors = <open file 'wsgi_errors', mode 'w' at 0x7f39ccecf420>
wsgi.file_wrapper = ''
wsgi.input = <uwsgi._Input object at 0x7f39c5c1cf90>
wsgi.multiprocess = True
wsgi.multithread = False
wsgi.run_once = False
wsgi.url_scheme = 'https'
wsgi.version = u'(1, 0)'

Settings:
Using settings module instance.settings
ABSOLUTE_URL_OVERRIDES = {}
ADMINS = []
ALLOWED_HOSTS = [u'dontworryaboutit.domain.com', u'192.168.1.2']
AMAVIS_DEFAULT_DATABASE_ENCODING = u'LATIN1'
APPEND_SLASH = True
AUTHENTICATION_BACKENDS = u"(u'django.contrib.auth.backends.ModelBackend',)"
AUTH_PASSWORD_VALIDATORS = u'********************'
AUTH_USER_MODEL = u'core.User'
BASE_DIR = '/srv/modoboa/instance'
CACHES = {u'default': {u'BACKEND': u'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS = u'default'
CACHE_MIDDLEWARE_KEY_PREFIX = u'********************'
CACHE_MIDDLEWARE_SECONDS = 600
CKEDITOR_ALLOW_NONIMAGE_FILES = False
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_CONFIGS = {u'default': {u'toolbar_Modoboa': [[u'Bold', u'Italic', u'Underline'], [u'JustifyLeft', u'JustifyCenter', u'JustifyRight', u'JustifyBlock'], [u'BidiLtr', u'BidiRtl', u'Language'], [u'NumberedList', u'BulletedList', u'-', u'Outdent', u'Indent'], [u'Undo', u'Redo'], [u'Link', u'Unlink', u'Anchor', u'-', u'Smiley'], [u'TextColor', u'BGColor', u'-', u'Source'], [u'Font', u'FontSize'], [u'Image'], [u'SpellChecker']], u'allowedContent': True, u'toolbar': u'Modoboa', u'width': None}}
CKEDITOR_IMAGE_BACKEND = u'pillow'
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_UPLOAD_PATH = u'uploads/'
CSRF_COOKIE_AGE = 31449600
CSRF_COOKIE_DOMAIN = u'domain.com'
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_NAME = u'csrftoken'
CSRF_COOKIE_PATH = u'/'
CSRF_COOKIE_SECURE = True
CSRF_FAILURE_VIEW = u'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME = u'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS = [u'dontworryaboutit.com', u'192.168.1.2']
CSRF_USE_SESSIONS = False
DATABASES = {u'default': {u'ENGINE': u'django.db.backends.postgresql_psycopg2', 'AUTOCOMMIT': True, u'ATOMIC_REQUESTS': True, u'NAME': u'modoboa', 'CONN_MAX_AGE': 0, 'TIME_ZONE': None, u'PORT': u'', u'HOST': u'127.0.0.1', u'USER': u'modoboa', 'TEST': {'COLLATION': None, 'CHARSET': None, 'NAME': None, 'MIRROR': None}, u'PASSWORD': u'********************', 'OPTIONS': {}}, u'amavis': {u'ENGINE': u'django.db.backends.postgresql_psycopg2', 'AUTOCOMMIT': True, u'ATOMIC_REQUESTS': True, u'NAME': u'amavis', 'CONN_MAX_AGE': 0, 'TIME_ZONE': None, u'PORT': u'', u'HOST': u'127.0.0.1', u'USER': u'amavis', 'TEST': {'COLLATION': None, 'CHARSET': None, 'NAME': None, 'MIRROR': None}, u'PASSWORD': u'********************', 'OPTIONS': {}}}
DATABASE_ROUTERS = [u'modoboa_amavis.dbrouter.AmavisRouter']
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000
DATETIME_FORMAT = u'N j, Y, P'
DATETIME_INPUT_FORMATS = [u'%Y-%m-%d %H:%M:%S', u'%Y-%m-%d %H:%M:%S.%f', u'%Y-%m-%d %H:%M', u'%Y-%m-%d', u'%m/%d/%Y %H:%M:%S', u'%m/%d/%Y %H:%M:%S.%f', u'%m/%d/%Y %H:%M', u'%m/%d/%Y', u'%m/%d/%y %H:%M:%S', u'%m/%d/%y %H:%M:%S.%f', u'%m/%d/%y %H:%M', u'%m/%d/%y']
DATE_FORMAT = u'N j, Y'
DATE_INPUT_FORMATS = [u'%Y-%m-%d', u'%m/%d/%Y', u'%m/%d/%y', u'%b %d %Y', u'%b %d, %Y', u'%d %b %Y', u'%d %b, %Y', u'%B %d %Y', u'%B %d, %Y', u'%d %B %Y', u'%d %B, %Y']
DEBUG = True
DEBUG_PROPAGATE_EXCEPTIONS = False
DECIMAL_SEPARATOR = u'.'
DEFAULT_CHARSET = u'utf-8'
DEFAULT_CONTENT_TYPE = u'text/html'
DEFAULT_EXCEPTION_REPORTER_FILTER = u'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE = u'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL = u'webmaster@localhost'
DEFAULT_INDEX_TABLESPACE = u''
DEFAULT_TABLESPACE = u''
DISALLOWED_USER_AGENTS = []
EMAIL_BACKEND = u'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = u'localhost'
EMAIL_HOST_PASSWORD = u'********************'
EMAIL_HOST_USER = u''
EMAIL_PORT = 25
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = u'********************'
EMAIL_SUBJECT_PREFIX = u'[Django] '
EMAIL_TIMEOUT = None
EMAIL_USE_LOCALTIME = False
EMAIL_USE_SSL = False
EMAIL_USE_TLS = False
FILE_CHARSET = u'utf-8'
FILE_UPLOAD_DIRECTORY_PERMISSIONS = None
FILE_UPLOAD_HANDLERS = [u'django.core.files.uploadhandler.MemoryFileUploadHandler', u'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440
FILE_UPLOAD_PERMISSIONS = None
FILE_UPLOAD_TEMP_DIR = None
FIRST_DAY_OF_WEEK = 0
FIXTURE_DIRS = []
FORCE_SCRIPT_NAME = None
FORMAT_MODULE_PATH = None
FORM_RENDERER = u'django.forms.renderers.DjangoTemplates'
IGNORABLE_404_URLS = []
INSTALLED_APPS = u"(u'django.contrib.auth', u'django.contrib.contenttypes', u'django.contrib.sessions', u'django.contrib.messages', u'django.contrib.sites', u'django.contrib.staticfiles', u'reversion', u'ckeditor', u'ckeditor_uploader', u'rest_framework', u'rest_framework.authtoken', u'modoboa', u'modoboa.core', u'modoboa.lib', u'modoboa.admin', u'modoboa.transport', u'modoboa.relaydomains', u'modoboa.limits', u'modoboa.parameters', u'modoboa.dnstools', u'modoboa_amavis', u'modoboa_pdfcredentials', u'modoboa_postfix_autoreply', u'modoboa_sievefilters', u'modoboa_stats', u'modoboa_webmail', u'modoboa_contacts', u'modoboa_radicale', 'webpack_loader')"
INTERNAL_IPS = []
LANGUAGES = [(u'af', u'Afrikaans'), (u'ar', u'Arabic'), (u'ast', u'Asturian'), (u'az', u'Azerbaijani'), (u'bg', u'Bulgarian'), (u'be', u'Belarusian'), (u'bn', u'Bengali'), (u'br', u'Breton'), (u'bs', u'Bosnian'), (u'ca', u'Catalan'), (u'cs', u'Czech'), (u'cy', u'Welsh'), (u'da', u'Danish'), (u'de', u'German'), (u'dsb', u'Lower Sorbian'), (u'el', u'Greek'), (u'en', u'English'), (u'en-au', u'Australian English'), (u'en-gb', u'British English'), (u'eo', u'Esperanto'), (u'es', u'Spanish'), (u'es-ar', u'Argentinian Spanish'), (u'es-co', u'Colombian Spanish'), (u'es-mx', u'Mexican Spanish'), (u'es-ni', u'Nicaraguan Spanish'), (u'es-ve', u'Venezuelan Spanish'), (u'et', u'Estonian'), (u'eu', u'Basque'), (u'fa', u'Persian'), (u'fi', u'Finnish'), (u'fr', u'French'), (u'fy', u'Frisian'), (u'ga', u'Irish'), (u'gd', u'Scottish Gaelic'), (u'gl', u'Galician'), (u'he', u'Hebrew'), (u'hi', u'Hindi'), (u'hr', u'Croatian'), (u'hsb', u'Upper Sorbian'), (u'hu', u'Hungarian'), (u'ia', u'Interlingua'), (u'id', u'Indonesian'), (u'io', u'Ido'), (u'is', u'Icelandic'), (u'it', u'Italian'), (u'ja', u'Japanese'), (u'ka', u'Georgian'), (u'kk', u'Kazakh'), (u'km', u'Khmer'), (u'kn', u'Kannada'), (u'ko', u'Korean'), (u'lb', u'Luxembourgish'), (u'lt', u'Lithuanian'), (u'lv', u'Latvian'), (u'mk', u'Macedonian'), (u'ml', u'Malayalam'), (u'mn', u'Mongolian'), (u'mr', u'Marathi'), (u'my', u'Burmese'), (u'nb', u'Norwegian Bokm\xe5l'), (u'ne', u'Nepali'), (u'nl', u'Dutch'), (u'nn', u'Norwegian Nynorsk'), (u'os', u'Ossetic'), (u'pa', u'Punjabi'), (u'pl', u'Polish'), (u'pt', u'Portuguese'), (u'pt-br', u'Brazilian Portuguese'), (u'ro', u'Romanian'), (u'ru', u'Russian'), (u'sk', u'Slovak'), (u'sl', u'Slovenian'), (u'sq', u'Albanian'), (u'sr', u'Serbian'), (u'sr-latn', u'Serbian Latin'), (u'sv', u'Swedish'), (u'sw', u'Swahili'), (u'ta', u'Tamil'), (u'te', u'Telugu'), (u'th', u'Thai'), (u'tr', u'Turkish'), (u'tt', u'Tatar'), (u'udm', u'Udmurt'), (u'uk', u'Ukrainian'), (u'ur', u'Urdu'), (u'vi', u'Vietnamese'), (u'zh-hans', u'Simplified Chinese'), (u'zh-hant', u'Traditional Chinese')]
LANGUAGES_BIDI = [u'he', u'ar', u'fa', u'ur']
LANGUAGE_CODE = u'en-us'
LANGUAGE_COOKIE_AGE = None
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_NAME = u'django_language'
LANGUAGE_COOKIE_PATH = u'/'
LOCALE_PATHS = []
LOGGING = {u'loggers': {u'modoboa.auth': {u'handlers': [u'syslog-auth', u'modoboa'], u'propagate': False, u'level': u'INFO'}, u'django': {u'handlers': [u'mail-admins'], u'propagate': False, u'level': u'ERROR'}, u'modoboa.admin': {u'handlers': [u'modoboa'], u'propagate': False, u'level': u'INFO'}}, u'version': 1, u'formatters': {u'syslog': {u'format': u'%(name)s: %(levelname)s %(message)s'}}, u'handlers': {u'syslog-auth': {u'formatter': u'syslog', u'class': u'logging.handlers.SysLogHandler', u'facility': 4}, u'modoboa': {u'class': u'modoboa.core.loggers.SQLHandler'}, u'mail-admins': {u'include_html': True, u'class': u'django.utils.log.AdminEmailHandler', u'level': u'ERROR'}}}
LOGGING_CONFIG = u'logging.config.dictConfig'
LOGIN_REDIRECT_URL = u'/accounts/profile/'
LOGIN_URL = u'/accounts/login/'
LOGOUT_REDIRECT_URL = None
MANAGERS = []
MEDIA_ROOT = u'/srv/modoboa/instance/media'
MEDIA_URL = u'/media/'
MESSAGE_STORAGE = u'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE = u"(u'x_forwarded_for.middleware.XForwardedForMiddleware', u'django.contrib.sessions.middleware.SessionMiddleware', u'django.middleware.common.CommonMiddleware', u'django.middleware.csrf.CsrfViewMiddleware', u'django.contrib.auth.middleware.AuthenticationMiddleware', u'django.contrib.messages.middleware.MessageMiddleware', u'django.middleware.locale.LocaleMiddleware', u'django.middleware.clickjacking.XFrameOptionsMiddleware', u'modoboa.core.middleware.LocalConfigMiddleware', u'modoboa.lib.middleware.AjaxLoginRedirect', u'modoboa.lib.middleware.CommonExceptionCatcher', u'modoboa.lib.middleware.RequestCatcherMiddleware')"
MIDDLEWARE_CLASSES = [u'django.middleware.common.CommonMiddleware', u'django.middleware.csrf.CsrfViewMiddleware']
MIGRATION_MODULES = {}
MODOBOA_API_URL = u'********************'
MODOBOA_APPS = u"(u'modoboa', u'modoboa.core', u'modoboa.lib', u'modoboa.admin', u'modoboa.transport', u'modoboa.relaydomains', u'modoboa.limits', u'modoboa.parameters', u'modoboa.dnstools', u'modoboa_amavis', u'modoboa_pdfcredentials', u'modoboa_postfix_autoreply', u'modoboa_sievefilters', u'modoboa_stats', u'modoboa_webmail', u'modoboa_contacts', u'modoboa_radicale')"
MONTH_DAY_FORMAT = u'F j'
NUMBER_GROUPING = 0
PASSWORD_HASHERS = u'********************'
PASSWORD_RESET_TIMEOUT_DAYS = u'********************'
PREPEND_WWW = False
REST_FRAMEWORK = {u'DEFAULT_AUTHENTICATION_CLASSES': (u'rest_framework.authentication.TokenAuthentication', u'rest_framework.authentication.SessionAuthentication')}
ROOT_URLCONF = u'instance.urls'
SECRET_KEY = u'********************'
SECURE_BROWSER_XSS_FILTER = False
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_HSTS_SECONDS = 0
SECURE_PROXY_SSL_HEADER = None
SECURE_REDIRECT_EXEMPT = []
SECURE_SSL_HOST = None
SECURE_SSL_REDIRECT = False
SERVER_EMAIL = u'root@localhost'
SESSION_CACHE_ALIAS = u'default'
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = u'sessionid'
SESSION_COOKIE_PATH = u'/'
SESSION_COOKIE_SECURE = True
SESSION_ENGINE = u'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_FILE_PATH = None
SESSION_SAVE_EVERY_REQUEST = False
SESSION_SERIALIZER = u'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE = 'instance.settings'
SHORT_DATETIME_FORMAT = u'm/d/Y P'
SHORT_DATE_FORMAT = u'm/d/Y'
SIGNING_BACKEND = u'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS = [u'security.W019', u'fields.W342']
SITE_ID = 1
STATICFILES_DIRS = u"(u'/srv/modoboa/env/lib/python2.7/site-packages/modoboa/bower_components',)"
STATICFILES_FINDERS = [u'django.contrib.staticfiles.finders.FileSystemFinder', u'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATICFILES_STORAGE = u'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_ROOT = u'/srv/modoboa/instance/sitestatic'
STATIC_URL = u'/sitestatic/'
TEMPLATES = [{u'DIRS': [], u'APP_DIRS': True, u'OPTIONS': {u'debug': False, u'context_processors': [u'django.template.context_processors.debug', u'django.template.context_processors.request', u'django.contrib.auth.context_processors.auth', u'django.template.context_processors.i18n', u'django.template.context_processors.media', u'django.template.context_processors.static', u'django.template.context_processors.tz', u'django.contrib.messages.context_processors.messages', u'modoboa.core.context_processors.top_notifications']}, u'BACKEND': u'django.template.backends.django.DjangoTemplates'}]
TEST_NON_SERIALIZED_APPS = []
TEST_RUNNER = u'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR = u','
TIME_FORMAT = u'P'
TIME_INPUT_FORMATS = [u'%H:%M:%S', u'%H:%M:%S.%f', u'%H:%M']
TIME_ZONE = u'Solar/Mars'
USE_ETAGS = False
USE_I18N = True
USE_L10N = True
USE_THOUSAND_SEPARATOR = False
USE_TZ = True
USE_X_FORWARDED_HOST = False
USE_X_FORWARDED_PORT = False
WEBPACK_LOADER = {'CALENDAR': {'IGNORE': ['.+\\.hot-update.js', '.+\\.map'], 'BUNDLE_DIR_NAME': 'modoboa_radicale/', 'CACHE': False, 'STATS_FILE': '/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_radicale/../frontend/webpack-stats.json'}, 'CONTACTS': {'IGNORE': ['.+\\.hot-update.js', '.+\\.map'], 'BUNDLE_DIR_NAME': 'modoboa_radicale/', 'CACHE': False, 'STATS_FILE': '/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_contacts/../frontend/webpack-stats.json'}}
WSGI_APPLICATION = u'instance.wsgi.application'
X_FRAME_OPTIONS = u'SAMEORIGIN'
YEAR_MONTH_FORMAT = u'F Y'


You're seeing this error because you have DEBUG = True in your
Django settings file. Change that to False, and Django will
display a standard page generated by the handler for this status code.
`

**Comment by ihmc3jn09hk** [comment]
More information. Some of the languages have this error.
`
Traceback:  

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/views/user.py" in profile
  48.             translation.activate(request.user.language)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/translation/__init__.py" in activate
  166.     return _trans.activate(language)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py" in activate
  239.     _active.value = translation(language)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py" in translation
  228.         _translations[language] = DjangoTranslation(language)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py" in __init__
  129.             self._add_installed_apps_translations()

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py" in _add_installed_apps_translations
  177.                 translation = self._new_gnu_trans(localedir)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py" in _new_gnu_trans
  156.             fallback=use_null_fallback)

File "/usr/lib/python2.7/gettext.py" in translation
  569.                 t = _translations.setdefault(key, class_(fp))

File "/usr/lib/python2.7/gettext.py" in __init__
  255.             self._parse(fp)

File "/usr/lib/python2.7/gettext.py" in _parse
  390.                         plural = v[1].split('plural=')[1]
`

**Comment by ihmc3jn09hk** [comment]
For cestina

`
File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py" in _new_gnu_trans
  156.             fallback=use_null_fallback)

File "/usr/lib/python2.7/gettext.py" in translation
  573.                 t = _translations.setdefault(key, class_(fp))

File "/usr/lib/python2.7/gettext.py" in __init__
  255.             self._parse(fp)

File "/usr/lib/python2.7/gettext.py" in _parse
  417.                     tmsg = unicode(tmsg, self._charset)

File "/srv/modoboa/env/lib/python2.7/encodings/utf_8.py" in decode
  16.     return codecs.utf_8_decode(input, errors, True)

Exception Type: UnicodeDecodeError at /user/profile/
Exception Value: 'utf8' codec can't decode byte 0xc5 in position 274: unexpected end of data
`

**Comment by ihmc3jn09hk** [comment]
Injected some code for the 日本の

`
...
the same shit
...

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py" in _new_gnu_trans
  156.             fallback=use_null_fallback)

File "/usr/lib/python2.7/gettext.py" in translation
  573.                 t = _translations.setdefault(key, class_(fp))

File "/usr/lib/python2.7/gettext.py" in __init__
  255.             self._parse(fp)

File "/usr/lib/python2.7/gettext.py" in _parse
  392.                             raise ValueError('GG : %s' % ', '.join(str(e) for e in v))

Exception Type: ValueError at /user/profile/
Exception Value: GG : nplurals=1,  p
`

**Comment by tonioo** [comment]
Does anyone know if it happens with python3?

**Comment by slowaways** [comment]
I can't switch to PT-BR in the new version too.
Please, help me!
