### ISSUE TITLE
Modoboa not accessible via web

### ISSUE THREAD

**Issue by cekpek** [modoboa/modoboa#1781]
# Impacted versions

* Modoboa: 1.7.2
* installer used: Yes
* Webserver: Nginx

I am not sure how to reproduce this issue, however after using modoboa for a year, suddenly the it can not be accessed via web (i'm still able to access the email from email client like emClient). Found out that nginx is not running, something wrong with its configuration,

> root@e-mail:/# nginx -t
nginx: [crit] pread() "/etc/nginx/sites-enabled/env" failed (21: Is a directory)
nginx: configuration file /etc/nginx/nginx.conf test failed

Not so sure what it is, but is it something related to the virtual env?

**Comment by tonioo** [comment]
@cekpek Looks like there is a mistake somewhere in your configuration. Did you modify anything manually?

**Comment by cekpek** [comment]
@tonioo i dis not alter the configuration, in fact i never touch the backend after the installation and first configuration, everything i do is through the frontend. Checked the server, and did not find any intruder.

**Comment by tonioo** [comment]
this path is wrong: ``/etc/nginx/sites-enabled/env``. If you used the installer with default configuration, it should not be there. Can you grep this pattern against nginx configuration files to see where it happens?
