### ISSUE TITLE
Error 500 on user creation

### ISSUE THREAD

**Issue by benjaminbellamy** [modoboa/modoboa#1782]
I don’t know if this is a bug or a hidden feature, but you cannot add new accounts after updating `/srv/modoboa/instance/sitestatic/css/modoboa.png`

# Impacted versions

* Modoboa: 1.14.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
  * Install Modoboa
  * Design a nice logo with Gimp (or MS Paint if you live in 1984 or Photoshop if you love DRMs)
  * Replace `/srv/modoboa/instance/sitestatic/css/modoboa.png` with your logo.
  * Add a new identity/mailbox and…
  * **Patatra !**

# Current behavior
**Error 500**

```
IOError at /admin/accounts/new/
cannot identify image file <open file u'/srv/modoboa/instance/sitestatic/css/modoboa.png', mode 'rb' at 0x7f4171dc9390>
fileName=u'/srv/modoboa/instance/sitestatic/css/modoboa.png' identity=[ImageReader@0x7f4171e5acd0 filename=u'/srv/modoboa/instance/sitestatic/css/modoboa.png']

Request Method: POST
Request URL: https://xxx/admin/accounts/new/
Django Version: 1.11.24
Python Executable: /usr/bin/uwsgi-core
Python Version: 2.7.15
Python Path: ['.', '', '/srv/modoboa/env/lib/python2.7', '/srv/modoboa/env/lib/python2.7/plat-x86_64-linux-gnu', '/srv/modoboa/env/lib/python2.7/lib-tk', '/srv/modoboa/env/lib/python2.7/lib-old', '/srv/modoboa/env/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/srv/modoboa/env/local/lib/python2.7/site-packages', '/srv/modoboa/env/lib/python2.7/site-packages']
Server time: Sat, 5 Oct 2019 15:54:30 +0200
```

# Expected behavior
Create new account with no Error 500?

**Comment by tonioo** [comment]
@benjaminbellamy Are you sure your image is not corrupted? Is it a real PNG file?

**Comment by benjaminbellamy** [comment]
Yes, the PNG is perfectly displayed, everything works fine. I just can’t create new mailboxes.
And when I put the original PNG file back I can create accounts again.

**Comment by tonioo** [comment]
@benjaminbellamy The error is pretty clear: ``cannot identify image file <open file u'/srv/modoboa/instance/sitestatic/css/modoboa.png``. Your PNG file must be special in some way...

**Comment by benjaminbellamy** [comment]
I don’t see anything special about this file. It is displayed fine by Nginx/browser.
I even tried with a blank png file, same size, same error.
Weird.
Why is this happening on user creation? How is user creation related to a PNG file?

**Comment by benjaminbellamy** [comment]
OK, I found it: **PNG file must have NO metadata at all.**
I removed them, now it works.

For instance when exporting to PNG using Gimp, you must uncheck all checkboxes (uncheck `"Save Exif data"`…).
Comments for PIL/Image.py open() function says `"This is a lazy operation;"`… Well it kinda is lazy…
(I had checked my PNG file header with Hex editor and they were clean.)
