### ISSUE TITLE
can't create new user

### ISSUE THREAD

**Issue by cenix102** [modoboa/modoboa#1783]
Modoboa version 1.14.

Distribution: Ubuntu
Codename: Bionic Beaver
Arch: 364 Bits
Database: MySQL

# Steps to reproduce
When I'm trying to add a new user under: **Identities > Add** 
![Screenshot 2019-10-12 at 10 17 53](https://user-images.githubusercontent.com/46600012/66697863-aca40700-ecd9-11e9-9a5a-6a391fccb42d.png)

Then **next** and then **submit**
# Current behavior
![image](https://user-images.githubusercontent.com/46600012/66697896-dfe69600-ecd9-11e9-9b9e-1f91f781450f.png)

# Expected behavior
"to creat a new user successfully

I never had this problem before, the last that i changed was the variable `MODOBOA_CUSTOM_LOGO` in `settings.py` 

Can anyone help me?

**Comment by tonioo** [comment]
@cenix102 Maybe an issue with PDF document creation. Can you enable debug mode?

**Comment by cenix102** [comment]
@tonioo Sorry for the late response. 
I enabled the debug mode. 

[modoboa_debug.txt](https://github.com/modoboa/modoboa/files/3725682/modoboa_debug.txt)

**Comment by tonioo** [comment]
@cenix102 the problem comes from your custom logo. How did you create it?

**Comment by cenix102** [comment]
The logo is a normal png file. I created the PNG GIMP2.0.

**Comment by tonioo** [comment]
@cenix102 Look at this please: https://github.com/modoboa/modoboa/issues/1782#issuecomment-542230399

**Comment by XiaotianZha** [comment]
@cenix102 Can you tell how how to get debug log, I have some erro but I don't know how to find the log file

**Comment by cenix102** [comment]
@XiaotianZha First you need to set the DEBUG parameter in settings.py to TRUE. Then you will find the logs in 
for nginx: /var/log/nginx/error.log 
for apache: /var/log/apache2/error.log
