### ISSUE TITLE
[Feature-Request] anonymize-headers

### ISSUE THREAD

**Issue by cremesk** [modoboa/modoboa#1784]
In Postfix, we can manage to hide the sender originating IP (plus some other stuff), in order to reduce the presence of user information on the server, and this can be achieved using Postfix's cleanup_service_name directive.

https://github.com/d3cod3/EndtoEndEncryptedMailServer#anonymize-headers

**Comment by tonioo** [comment]
@cremesk Interesting idea. Could you please move this issue to the installer repository?
