### ISSUE TITLE
Cannot receive email from external accounts

### ISSUE THREAD

**Issue by boydspace** [modoboa/modoboa#1786]
# Impacted versions

* Modoboa: 1.14.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Happens no matter how I try. I am on my own local network. All ports are opened, port 25 works, SMTP works, but IMAP to receive mail is not working. Unless I am misunderstanding something. I can receive email internally, ie from local accounts to other local accounts, but if I try an email server from outside the network, ie google, microsoft, yahoo, etc. the connection is not accepted. **[mail.encountermercy.com. 24.154.55.119: timed out]** this is what Google returns. I cannot understand what I am doing wrong.

# Current behavior
Unable to receive email. No problem with sending. I can send out, and port 25 is not blocked by ISP.

# Expected behavior
Accounts should be able to receive email. All ports are opened between modem and server

**Comment by tonioo** [comment]
There must be something that block the traffic between ISPs and your server... Have you tried to open a connection to port 25 on your server from the outside? (using telnet)

**Comment by Fr3shlama** [comment]
I have the same problem.

I did try that, no ports are blocked

**Comment by tonioo** [comment]
@Fr3shlama It might be a verify cache issue in your case. You can try to remove the verify cache (http://www.postfix.org/ADDRESS_VERIFICATION_README.html#caching) and reload postfix.

**Comment by ScrumpyJack** [comment]
> I have the same problemexcept i cannot send emails internally
> 
> I did try that, no ports are blocked
> 
> my mail.log throws the following errors:
> 
> `Jan 6 20:41:52 fr3shlamamail postfix/smtpd[19509]: NOQUEUE: reject: RCPT from mail-il1-f170.google.com[x.x.x.x]: 550 5.1.1 <fr3shlama@fqdn.com>: Recipient address rejected: undeliverable address: unknown user: "fr3shlama"; from=<externemail@gmail.com> to=<fr3shlama@fqdn.com> proto=ESMTP helo=<mail-il1-f170.google.com>`
> 
> and
> 
> `Jan 6 20:41:52 fr3shlamamail postfix/smtpd[19509]: disconnect from mail-il1-f170.google.com[x.x.x.x] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 quit=1 commands=5/7`
> 
> Details are changed

Same issue for me on a fresh install

 Recipient address rejected: undeliverable address: unknown user

**Comment by tonioo** [comment]
@ScrumpyJack Have you tried to delete the verify cache?
