### ISSUE TITLE
Cron job "manage.py communicate_with_public_api" fails.

### ISSUE THREAD

**Issue by francescop75** [modoboa/modoboa#1787]
# Impacted versions

* Modoboa: 1.14.0
* installer used: Yes (about a year ago, upgraded since)
* Webserver: Nginx

# Steps to reproduce

Enable public API comminication in Modoboa parameters.

# Current behavior

Cron job fails with "CommandError: Failed to retrieve versions from the API."

# Expected behavior

Success to retrieve versions from the API.

# Note

If manually launched from shell:

```
PYTHON=/srv/modoboa/env/bin/python
INSTANCE=/srv/modoboa/instance
$PYTHON $INSTANCE/manage.py communicate_with_public_api --verbosity 3

```

No errors are reported.

https://api.modoboa.org SSL certificate seems to be ok.

# Attachments

[modoboa.crontab.txt](https://github.com/modoboa/modoboa/files/3788727/modoboa.crontab.txt)

**Comment by tsabi** [comment]
It happened to me too, i guessed every server sends the log at the same time, and the remote server is DDOSed, so i modified the sending time to another minute in the hour, and it works.

**Comment by francescop75** [comment]
> It happened to me too, i guessed every server sends the log at the same time, and the remote server is DDOSed, so i modified the sending time to another minute in the hour, and it works.

I'll try to do that way, thanks!

**Comment by tonioo** [comment]
There was indeed or configuration issue on the public API server. It is now fixed.
