### ISSUE TITLE
how to modify default configurations 

### ISSUE THREAD

**Issue by XiaotianZha** [modoboa/modoboa#1791]
# Impacted versions

Latest Modoboa installer on Centos 7.
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Install Modoboa on Centos 7 following install directions.

git clone https://github.com/modoboa/modoboa-installer
cd modoboa-installer/
./run.py mytestdomain.xyz
# Current behavior
After installing there is a tips :
Congratulations! You can enjoy Modoboa at https://xxxx (admin:password)
And Modoboa  is running now. but the configurations of Modoboa  are using default . 
I have noticed that there is a file named settings.py, but I'm new to python ,I don't know to make modification  be effective.(Restart the server or something like?)

**Comment by tonioo** [comment]
@XiaotianZha You must reload uwsgi every time you update the settings.py file.

**Comment by XiaotianZha** [comment]
> @XiaotianZha You must reload uwsgi every time you update the settings.py file.

I modified the condfiguration of db to a mysql server , after reload uwsgi , there is a Internal Server Error  when I access the webmail.

**Comment by XiaotianZha** [comment]
> > @XiaotianZha You must reload uwsgi every time you update the settings.py file.
> 
> I modified the condfiguration of db to a mysql server , after reload uwsgi , there is a Internal Server Error when I access the webmail.
> And there is an error log in var/spool/mail/root
> 
> ```
> "django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named MySQLdb.
> Did you install mysqlclient or MySQL-python?"
> ```
> 
> I have already use the pip install mysqlclient MySQL-python, but it seems not in install into the write path

I have solved this problem after learning the python virtualenv , now it seems I need to re-built table in the new db
