### ISSUE TITLE
Getting unauthorized acces (401) while fetching the modoboa API's. 

### ISSUE THREAD

**Issue by akshaykashid13** [modoboa/modoboa#1792]
# Impacted versions

* Modoboa: X.X.x
* installer used: Yes/No ?
* Webserver: Nginx/Apache

# Steps to reproduce

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@akshaykashid13 Make sure your requests include a valid API token.
