### ISSUE TITLE
An Error occurred in create new account

### ISSUE THREAD

**Issue by XiaotianZha** [modoboa/modoboa#1793]
# Impacted versions

* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Create new account  in web
# Current behavior

Failed to create the directory that will contain PDF documents ([Errno 2] No such file or directory: '/var/lib/modoboa/pdf_credentials')

And there is another failed in /var/spool/mail/root
IOError: [Errno 2] No such file or directory: '/etc/modoboa_radicale/rights'

**Comment by XiaotianZha** [comment]
I solved this problem by disable  pdf_credentials, and create a new user. But when I open the web-mail there is an error
`Error: ['[AUTHENTICATIONFAILED] Authentication failed.']`

**Comment by tonioo** [comment]
@XiaotianZha Is this issue still happening?

**Comment by maximerenou** [comment]
> @XiaotianZha Is this issue still happening?

Yes. I had to disable pdfcredentials to create a new account.

**Comment by XiaotianZha** [comment]
> @XiaotianZha Is this issue still happening?

I don't know, I have chosen Apache James instead

**Comment by NiccyB** [comment]
This problem still occurs with a brand new installation on Debian using the provided script.

Typing:
```
mkdir -p /var/lib/modoboa/pdf_credentials
chown -R modoboa.modoboa /var/lib/modoboa
chmod -R 700 /var/lib/modoboa
```
appears to solve the issue.

**Comment by Spitfireap** [comment]
> This problem still occurs with a brand new installation on Debian using the provided script.
> 
> Typing:
> 
> ```
> mkdir -p /var/lib/modoboa/pdf_credentials
> chown -R modoboa.modoboa /var/lib/modoboa
> chmod -R 700 /var/lib/modoboa
> ```
> 
> appears to solve the issue.

[A fix is on the way](https://github.com/modoboa/modoboa-installer/pull/497) ;)
