### ISSUE TITLE
LDAP Authentication - Webmail / Dovecot

### ISSUE THREAD

**Issue by abonanni** [modoboa/modoboa#1800]
# Impacted versions

* Modoboa: 1.14.0
* Webserver: Nginx

# Steps to reproduce

If LDAP authentication is configured, webmail not working : authentication error

The problem is that dovecot uses databases to check authentication. It would be nice if LDAP is configured that the configuration install dovecot-ldap module and generate the configuration file.

I manually update dovecot configuration and everything is working.

**Comment by Kobberholm** [comment]
@abonanni do you have the required steps for enabling LDAP with Dovecot?

Did you do Password lookups or Authentication binds?
Which LDAP server are you using?

I am planning on setting this up on my own server eventually, so did a bit of searching on the web, but would be nice to see a known good configuration.

Found the following documentation:

- https://doc.dovecot.org/configuration_manual/authentication/ldap/
- https://help.ubuntu.com/community/DovecotLDAP
