### ISSUE TITLE
DKIM Won't register

### ISSUE THREAD

**Issue by Zodsmar** [modoboa/modoboa#1802]
# Impacted versions

* Modoboa: Recent
* installer used: Yes
* Webserver: Nginx/Apache (Ubuntu 18 LTS)

Everything is working except for DKIM.

![Capture](https://user-images.githubusercontent.com/5366500/70379696-cc346600-18fd-11ea-84bd-ffa6e56f24d6.PNG)

![Capture1](https://user-images.githubusercontent.com/5366500/70379699-d2c2dd80-18fd-11ea-8db4-4e2a96190f27.PNG)

**This is my DNS record with the selector set when setting up the account (The selector above is the same as below)**

![Capture2](https://user-images.githubusercontent.com/5366500/70379710-ecfcbb80-18fd-11ea-9293-71a2228ec74e.PNG)

![Capture3](https://user-images.githubusercontent.com/5366500/70379713-fc7c0480-18fd-11ea-976a-5fe2748fcf6f.PNG)
![Capture4](https://user-images.githubusercontent.com/5366500/70379715-030a7c00-18fe-11ea-95be-3f92fc2ad37d.PNG)

**Here I tried both lines the one uncommented and also the one with the arrow and commented out the bottom line. Neither seemed to fix it.**

![Capture5](https://user-images.githubusercontent.com/5366500/70379717-056cd600-18fe-11ea-8bde-01b20eaf701c.PNG)
![Capture6](https://user-images.githubusercontent.com/5366500/70379718-069e0300-18fe-11ea-9caf-95140d6bccee.PNG)
![Capture7](https://user-images.githubusercontent.com/5366500/70379719-0867c680-18fe-11ea-9897-ac36e02b17d8.PNG)

**Not sure if its important but the .pem files do not have the selector prefixed to them it is simply the URL.ca.pem**

![Capture8](https://user-images.githubusercontent.com/5366500/70379720-0a318a00-18fe-11ea-89d0-64b63367f789.PNG)
![Capture9](https://user-images.githubusercontent.com/5366500/70379722-0b62b700-18fe-11ea-8030-0c7b5b62b445.PNG)
![Capture10](https://user-images.githubusercontent.com/5366500/70379723-0d2c7a80-18fe-11ea-9c71-6e1ea1955cd1.PNG)

Overall I have attached all of the config files I can think of. I have spent hours googling trying so many things to get the DKIM to register but no matter what I try it seems that the DNS record cannot find the private keys and does not sign the email.

I setup modoboa using the installer, and changed the install.cfg to have custom db passwords. Other than that, it installed totally fine and everything is working beautifully except for the DKIM.

If anyone knows why this is not working I tried to attach as much information as possible. I don't think that I am doing anything wrong regarding the DNS its "selector._domainkey as TXT "v=DKIM1;k=rsa;p=PUBLIC KEY WITH NO SPACES OR DOUBLE QUOTES" 

Hopefully someone has an answer to this sooner rather than later. I can provide more information if need be or if I missed a config file that would be helpful to see! 

Also I have looked through other threads and have done a lot of what was suggested and still nothing. I even have done chmod g+w /var/lib/dkim to make sure its accessible.

Thanks!

**Comment by tonioo** [comment]
@Zodsmar Simple question, have you created the appropriate record in your DNS zone?

**Comment by Zodsmar** [comment]
Yes

**Comment by tonioo** [comment]
Might be fixed by https://github.com/modoboa/modoboa/pull/1823.
