### ISSUE TITLE
Mail Server is Slow on sending/receiving mails

### ISSUE THREAD

**Issue by DamonNomadJr** [modoboa/modoboa#1803]
# Impacted versions

* Modoboa: 1.19.1
* installer used: Yes
* Webserver: Nginx/Apache

Going to mail, composing and sending an email. This process takes way too long. I sometimes leave for 2-3 min and came back to see it sent.

On phone as well using GMail client I and waiting for 5 min for the server to send my emails.

**Comment by tonioo** [comment]
Look at you server logs, you might have a timeout issue somewhere.
