### ISSUE TITLE
Using API to update password fails 

### ISSUE THREAD

**Issue by dkashikar** [modoboa/modoboa#1816]
# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes
* Webserver: Nginx

I used the put request to update the password for an account 
curl --location --request PUT 'https://myinstance/api/v1/accounts/28/password' \
--header 'Content-Type: application/json' \
--header 'Authorization: Token xxxxxxxxxxxxxxxxxxxxxxxxx' \
--data-raw '{
	"password" : "asfasdf",
	"new_password" : "asfasdf"
}'

and I get the response

{"new_password":["This field is required."],"password":["This field is required."]}

whereas it should have updated the password. The documentation for the api says I need to pass the whole user object. however the error message seems to say that only two fields are required and they are password and new_password. Is there anything I am doing wrong here?

**Comment by tonioo** [comment]
@dkashikar Have you tried with an up-to-date version of Modoboa?
