### ISSUE TITLE
less notifications about MX/DNSBL issues

### ISSUE THREAD

**Issue by tg-x** [modoboa/modoboa#1820]
# Impacted versions

* Modoboa: 1.13.1

# Steps to reproduce

get listed at a DNSBL or have some DNS issues 

# Current behavior

modoboa sends email notifications about the issue every couple of hours while the problem persists filling the mailbox of admins with useless messages of already acknowledged issues

# Expected behavior

send only one notification when the problem starts and another one when the problem is resolved

**Comment by tonioo** [comment]
@tg-x What kind of message do you receive exactly? About MX issues, DNSBL issues, both?

**Comment by tg-x** [comment]
this happened for both
