### ISSUE TITLE
Feature Request UI/UX

### ISSUE THREAD

**Issue by DamonNomadJr** [modoboa/modoboa#1825]
This is not related to any bugs or error, but a feature request. 

The create mail page is good as it is, but it would be better if users could have a WYSIWYG editor so that they can attach images inline with their email. And the layout may be improved further.

Overall, loving the project sofar.

**Comment by tonioo** [comment]
@DamonNomadJr There is an option in your personal settings to enable an HTML editor when you compose messages.

**Comment by DamonNomadJr** [comment]
@tonioo I saw the feature about 3 days after the original post. My mistake, However, may I suggest to have it so that you could turn it on across all users automatically?

If it is not a good idea please let me know why you choose this approach.
