### ISSUE TITLE
crontab error -- no cron jobs ran on clean install when not using dovecot

### ISSUE THREAD

**Issue by stalks** [modoboa/modoboa#1826]
### Impacted versions

* Modoboa: 1.14.0
* installer used: **Yes**
* Webserver: Nginx

### Steps to reproduce
Install modoboa using installer with MDA disabled (dovecot disabled, no local mail).

### Current behavior
crontab is created however the "vmail" user doesn't exist, so crontab ignores the file

### Expected behavior
crontab to have the vmail entry commented out if MDA doesn't exist

### Error message
By enabling /var/log/cron.log we can see the following message:
```
Error: bad username; while reading /etc/cron.d/modoboa
(*system*modoboa) ERROR (Syntax error, this crontab file will be ignored)
```

### Steps to fix post-install
Comment out the following entry from /etc/cron.d/modoboa
`*       *       *       *       *       vmail   $PYTHON $INSTANCE/manage.py handle_mailbox_operations`

**Comment by tonioo** [comment]
@stalks Thanks for reporting this. Could you please move this issue to the modoboa-installer repository?

**Comment by tonioo** [comment]
Fixed by https://github.com/modoboa/modoboa-installer/commit/b5aa1bc7e7b4537f3275e6812ea7bb5a8f146cd3.
