### ISSUE TITLE
521 Error when I use Cloudflare free SSL certificate

### ISSUE THREAD

**Issue by Super-Gil** [modoboa/modoboa#1828]
# Impacted versions
Not sure...
* Modoboa: Latest
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
1. Setup my website in Cloudflare and require a SSL certificate
2. Build my website with Wordpress
3. Setup Modoboa on the same server
4. Then 521 error occur

# Current behavior
521 Error
# Expected behavior
Request 200
# Video/Screenshot link (optional)
https://mail.anckak.tech/

**Comment by tonioo** [comment]
@Super-Gil The installer was designed to be run on a fresh system, with no existing web server. If you want to share a server then go with a manual installation.
