### ISSUE TITLE
I cant receive external emails, but send to them.

### ISSUE THREAD

**Issue by Bastianvgt** [modoboa/modoboa#1833]
# Impacted versions

* Modoboa: 1.14.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
I really dont know. Everything was working fine, but then suddenly it didnt. 
# Current behavior
I am not able to receive external Mails. I can receive internal mails (sent from the modoboa website of my server, not working when using an app on my mobile) and send to external adresses (again, just from the website)
# Expected behavior
I can send and receive everything from both, mobile and website

# Video/Screenshot link (optional)
LISTENING Ports on my VPS
![Screenshot_1](https://user-images.githubusercontent.com/51333265/73614747-2bfb7480-4602-11ea-94ce-35233494f0e2.png)

Webmail Settings in Modoboa (German)
![Screenshot_2](https://user-images.githubusercontent.com/51333265/73614754-3f0e4480-4602-11ea-8e94-4075a4e3794f.png)

**Comment by Bastianvgt** [comment]
Ok, I now got dovecot running too, but still not receiving emails...
![Screenshot_3](https://user-images.githubusercontent.com/51333265/73616663-7edf2700-4616-11ea-8978-6dc25a2dabcd.png)

**Comment by tonioo** [comment]
@Bastianvgt If you don't see anything in your logs, it means the problem is not on the server. Have you checked your firewall / DNS configuration / ISP blocking rules / etc ?

**Comment by Bastianvgt** [comment]
Yes, I did. Anyways, I tried to reinstall but it didnt work. And I cant install it again, so I will reinstall my VPS sometime... Thank you for your reply and this Thread can be closed.




Dienstag, 4. Februar 2020, 08:50 +0100 von notifications@github.com  <notifications@github.com>:

**Comment by Bastianvgt** [comment]
Hey! I just reinstalled my VPS and modoboa.

I now tested with GMail and this error occures: 

Recipient address rejected: undeliverable address: mail for bot-dev.de loops back to myself

AND now I get errors on my VPS. 

`Feb  4 17:57:38 vmd43772 postfix/smtpd[3020]: connect from mail-io1-f41.google.com[209.85.166.41]
Feb  4 17:57:38 vmd43772 postfix/smtpd[3020]: warning: connect to Milter service inet:127.0.0.1:12345: Connection refused
Feb  4 17:57:39 vmd43772 postfix/smtpd[3020]: Anonymous TLS connection established from mail-io1-f41.google.com[209.85.166.41]: TLSv1.3 with cipher TLS_AES_128_GCM_SHA256 (128/128 bits)
Feb  4 17:57:39 vmd43772 postfix/smtpd[3020]: NOQUEUE: reject: RCPT from mail-io1-f41.google.com[209.85.166.41]: 550 5.1.1 <basti@bot-dev.de>: Recipient address rejected: undeliverable address: mail for bot-dev.de loops back to myself; from=<myemail@gmail.com> to=<basti@bot-dev.de> proto=ESMTP helo=<mail-io1-f41.google.com>
Feb  4 17:57:39 vmd43772 postfix/smtpd[3020]: disconnect from mail-io1-f41.google.com[209.85.166.41] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 quit=1 commands=5/7
`

I hope thats not too less information

**Comment by Bastianvgt** [comment]
@tonioo I hope you see this cause its closed

**Comment by tonioo** [comment]
@Bastianvgt Can you check the value of mydestination setting in the /etc/main.cf file? It should be empty...

**Comment by Bastianvgt** [comment]
If you mean /etc/postfix/main.cf, it´s set to mail.bot-dev.de ( $myhostname ), I dont have a /etc/main.cf file

**Comment by Bastianvgt** [comment]
@tonioo Any idea?

**Comment by Bastianvgt** [comment]
@tonioo Could you please reopen the thread?

**Comment by Bastianvgt** [comment]
Okay... new update:

I dont know what it was, but suddenly I recieved an email and it seems to be working for now... 
No need to be reopened
