### ISSUE TITLE
Quarantine / Release Button / HTTP/1.1 500

### ISSUE THREAD

**Issue by r0nster** [modoboa/modoboa#1834]
# Impacted versions

* Modoboa: 1.14.0
* installer used: Yes
* Webserver: Nginx 1.14.0-0ubuntu1.7
* Ubuntu 18.04.4 LTS
* uwsgi 2.0.15-10.2ubuntu2.1

# Steps to reproduce
- Mail in Quarantine
- Select Mail
- Use Button "Release" an no action with mail (see log)
# Current behavior
/var/log/uwsgi/app/modoboa_instance.log
() {60 vars in 1310 bytes} [Thu Feb  6 15:06:45 2020] POST /quarantine/process/ => generated 18624 bytes in 267 msecs (HTTP/1.1 500) 5 headers in 169 bytes (1 switches on core 0)

ngnix log:
xxx.xxx.xxx.xxx - - [06/Feb/2020:15:06:45 +0100] "POST /quarantine/process/ HTTP/1.1" 500 870 "https://DOMAIN/quarantine/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
# Expected behavior

# Video/Screenshot link (optional)

What exactly is the problem?

**Comment by rvicentiu** [comment]
Looks like you are using a newer version of Python.

First a simple fix for the missing atoi function in lib.py .

The second issue is the SQLConnector is now returning binary strings and passing them to the amavis request which ends up failing:
mail amavis[107508]: (!!)policy_server FAILED: Invalid mail_id 'b'CsYzT_eYhU7v'' at (eval 95) line 281, <GEN91> line 6.

The attached diffs (use patch utility)
[views.py.txt](https://github.com/modoboa/modoboa/files/4275028/views.py.txt)
[lib.py.txt](https://github.com/modoboa/modoboa/files/4275029/lib.py.txt)

 fixed the issue for me but there may be a need for additional fixes.

**Comment by tonioo** [comment]
@rvicentiu Thanks for the help. I close this issue since it's a duplicated of https://github.com/modoboa/modoboa-amavis/issues/119.
