### ISSUE TITLE
I cannot send emails through my Modoboa email server, although I can recieve.

### ISSUE THREAD

**Issue by brandonhndrxn** [modoboa/modoboa#1846]
# Impacted versions

* Modoboa: X.X.x
* installer used: Yes/No ?
* Webserver: Nginx/Apache

# Steps to reproduce

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@brandonhndrxn can't help you without proper logs from your system.
