### ISSUE TITLE
ssl certificate of https://modoboa.org/fr/ expired

### ISSUE THREAD

**Issue by fpiccinali** [modoboa/modoboa#1853]
# Impacted versions

* Modoboa: X.X.x
* installer used: Yes/No ?
* Webserver: Nginx/Apache

# Steps to reproduce

Open https://modoboa.org/fr/

# Current behavior

Les sites web justifient leur identité par des certificats qui ont une période de validité définie. Le certificat de modoboa.org a expiré le 06/03/2020.
 
Code d’erreur : SEC_ERROR_EXPIRED_CERTIFICATE

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@fpiccinali Fixed, thank you.
