### ISSUE TITLE
No sent mail in sentbox(smtp)

### ISSUE THREAD

**Issue by cybmp3** [modoboa/modoboa#1856]
# Impacted versions

* Modoboa: 1.14
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
use smtp to sent 
# Current behavior
Sending mail using smtp protocol but there is no sent mail in the sentbox.
# Expected behavior
The server can automatically save the emails that have been sent using the smtp protocol so that they we can be easily queried in webmail.
# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@cybmp3 Can you please provide more info? (logs, screenshots, ...)

**Comment by Toniob** [comment]
@cybmp3 From your message, I understand that you're not using a mail client to send your emails. Maybe I'm wrong, tell me. If those are emails sent using a script or something automated, it can't be done. SMTP is a protocol made to send email, that's all. It doesn't store them. For that, you need IMAP (let's forget about POP).

**Comment by cybmp3** [comment]
> 
> 
> @cybmp3 Can you please provide more info? (logs, screenshots, ...)

Such as wordpress send email via smtp.

**Comment by Toniob** [comment]
So that's something to see with wordpress, for them to support IMAP storage when emails are sent. Not an issue with Modoboa.

**Comment by cybmp3** [comment]
> 
> 
> @cybmp3 From your message, I understand that you're not using a mail client to send your emails. Maybe I'm wrong, tell me. If those are emails sent using a script or something automated, it can't be done. SMTP is a protocol made to send email, that's all. It doesn't store them. For that, you need IMAP (let's forget about POP).

correct.
But if wordpress uses gmail's smtp protocol to send mail, you can find the sent mail in the sentbox of gmail.

**Comment by Toniob** [comment]
Gmail is everything but standard SMTP et IMAP.
We shouldn't store email sent via SMTP. If we do this, when you'll send emails with your mail client, you'll have duplicates in your sendbox : one mail stored via your mail client, another one with a trick on SMTP.

**Comment by cybmp3** [comment]
> 
> 
> Gmail is everything but standard SMTP et IMAP.
> We shouldn't store email sent via SMTP. If we do this, when you'll send emails with your mail client, you'll have duplicates in your sendbox : one mail stored via your mail client, another one with a trick on SMTP.

Thank you.
