### ISSUE TITLE
MX is not recognise and I am not receiving email 

### ISSUE THREAD

**Issue by mesoshqip** [modoboa/modoboa#1860]
# Impacted versions

* Modoboa: 1.14.0
* installer used: Yes
* Webserver: Nginx
* Ubuntu 18.04

# Steps to reproduce
I have installed and configure the DNS, MX, TX everything
Modoboa don't recognize the  MX record
No MX record found for this domain.
and also DMARC 

I had tested the mail through mail-tester.com and is everything ok.

But the problem is this; I can send email but from yesterday I don't receive the email through imap.

Thank you

**Comment by tonioo** [comment]
@mesoshqip Please check the server DNS configuration and I think next release should fix this issue if it's not a local configuration issue.

**Comment by mesoshqip** [comment]
Thank you @tonioo .. i solved it.. every thing is green and I can send and receive emails from the iPhone client mail, but I can't send email from Webmail!!.

Also, I did a check through mxtoolbox.com tool and I have these warnings:

smtp | mail.mesoshqip.net | Reverse DNS does not contain the hostname 
smtp | mail.mesoshqip.net | 6.375 seconds - Warning on Connection time
smtp | mail.mesoshqip.net | 8.531 seconds - Not good! on Transaction Time

Can you help me?

**Comment by tonioo** [comment]
@mesoshqip Can I close this issue?
