### ISSUE TITLE
debian bullseye(11) has changed default python version to 3.8 broken everything.

### ISSUE THREAD

**Issue by cybmp3** [modoboa/modoboa#1864]
# Impacted versions

* Modoboa: 1.14.0
* installer used: Yes
* system: Debian bullseye
* Webserver: Nginx

# Steps to reproduce
march 2020 debian bullseye  has changed /usr/bin/python to 3.8.and change /usr/bin/pip to version 3.if you want use python2.7 you need use command python2.
# Current behavior
modoboa web page can't check dns status.
# Expected behavior
Have no idea.
# Video/Screenshot link (optional)
![20200402093216](https://user-images.githubusercontent.com/14276116/78201785-089b5b80-74c5-11ea-86b4-bd7aeaa0d461.jpg)
![20200402093304](https://user-images.githubusercontent.com/14276116/78201786-0a651f00-74c5-11ea-89ba-1fc4616f28ab.jpg)
pip install mysql-python is ok.

**Comment by tonioo** [comment]
Your screenshots say you're using a python2 based virtualenv, which is not a good idea. I suggest you create a new python3 based virtualenv. Check this page to know more: https://modoboa.readthedocs.io/en/latest/upgrade.html#rebuild-virtual-environment.
