### ISSUE TITLE
Albanian translation

### ISSUE THREAD

**Issue by mesoshqip** [modoboa/modoboa#1867]
Hi Tonio
I am working on translation of Modoboa in the Albanian language. But, I need to test it locally. Can you explain how to enable the Albanian files and where to put these files?
BR

**Comment by tonioo** [comment]
@mesoshqip You can use the transifex client or take a look at how .po files are stored in the modoboa repository. Once files are installed, check the `modoboa/core/constants.py` file, you'll find a  ̀LANGUAGES` variable you can modify to declare the language you're adding. Don't forget to reload uwsgi

**Comment by tonioo** [comment]
@mesoshqip Any news?
