### ISSUE TITLE
Error While Sending Email Using Python

### ISSUE THREAD

**Issue by saileshkush95** [modoboa/modoboa#1868]
# Impacted versions

* Modoboa: Latest
* installer used: Yes?
* Webserver: Nginx

# Steps to reproduce
I'm trying to send email using python.
Some thing like describe here [https://automatetheboringstuff.com/chapter16/](url)
# Current behavior
![Screenshot_20200403_124306](https://user-images.githubusercontent.com/28560875/78333017-cc412b80-75a8-11ea-856d-b4f205708ccb.png)

# Expected behavior
I can able to successfully send email
# Video/Screenshot link (optional)
Here is my webmail configurations, by the way. I'm using digitalocean  to host modoboa, and working, i'm new to modoboa and email-server hosting. 
![Screenshot_20200403_124615](https://user-images.githubusercontent.com/28560875/78333245-30fc8600-75a9-11ea-9380-64dce18b376f.png)

**Comment by tonioo** [comment]
@saileshkush95 Can you describe what does not work in Modoboa? If you're looking for a way to send email from a Python script, it is not the right place.

**Comment by saileshkush95** [comment]
I'm using this script to send email. 
```
import smtplib, ssl
smtp_server = "mail.domainname.com"
port = 587
sender_email = "someemail@domainname.com"
password = input("Type your password and press enter: ")
receiver_email = "someemail@gmail.com"
message = """\
Subject: Hi there
This message is sent from Python."""
# Send email here
# Create a secure SSL context
context = ssl.create_default_context()
server = smtplib.SMTP(smtp_server,port)
# Try to log in to server and send email
try:
    server.ehlo() # Can be omitted
    server.starttls(context=context) # Secure the connection
    server.ehlo() # Can be omitted
    server.login(sender_email, password)
    server.sendmail(sender_email, receiver_email, message)
    print('message sed successfully')
except Exception as e:
    # Print any error messages to stdout
    print(e)
finally:
    server.quit()
````

Above script run successfully, but i didn't receive any email
