### ISSUE TITLE
Autodiscover/AutoConfig/AutoMX

### ISSUE THREAD

**Issue by DaveDischord** [modoboa/modoboa#1869]
# Impacted versions

* Modoboa: 1.14
* installer used: Yes/No ? Yes
* Webserver: Nginx

OK, so first question so I can wrap my head around it:  How does AutoMX, autodiscover, and autoconfig interact, if they even do?

Also, and mainly, is that everything is functioning pretty good.  I run Outlook and autodiscover seems to be working, except for one small bit that I have to go in and set manually, and that is the **Secure Password Authentication** checkbox that needs checked on the IMAP side.  In my generated autodiscover.xml, the tag <SPA> is between the <LoginName> tag and the <Encryption> tag.  Currently it is **off**.  How can I set it to **on** so that I won't have to manually change it for the next account setup?

On the topic of automating Ouitlook account setup, is there, or has anyone figured out, a way to totally automate it, so that a user doesn't need to do anything after opening Outlook, like no password input, etc?

**Comment by tonioo** [comment]
@DaveDischord automx is a tool which provides autoconfig (mozilla) / autodiscover (microsoft) implementations. Modoboa installer does install an automx instance but using an old version, there a rewrite (automx2) available but that's something that should be done.
