### ISSUE TITLE
[Suggestion] Add max_mail_size to Settings Panel

### ISSUE THREAD

**Issue by makakken** [modoboa/modoboa#1871]
Is there a way to set postfix max_mail_size parameter through modoboas-settings panel? Is there a possiblity to set that per Domain?

**Comment by tonioo** [comment]
@makakken Modoboa does not modify postfix configuration file currently.

**Comment by neonknight** [comment]
I'd appreciate a few postfix configuration settings to be changed via UI, although it's probably not easy to do (need to edit files owned by root, as a first obstacle).

The following options would be great to set in UI:
- max message size
- smarthost (incl auth)
- enable/disable postscreen checks completely
