### ISSUE TITLE
Doesn't work with django allauth

### ISSUE THREAD

**Issue by saileshkush95** [modoboa/modoboa#1873]
i'm using django allauth in my project. Every things works fine in modoboa. But it is not working with django allauth. I'm facing error like this.
![Screenshot_20200408_121053](https://user-images.githubusercontent.com/28560875/78752159-48fe4c00-7993-11ea-9d96-d119610d87f3.png)

**Comment by tonioo** [comment]
@saileshkush95 Are you trying to integrate allauth in a Modoboa installation? Or are you using Modoboa as an SMTP server for an application you develop?

**Comment by saileshkush95** [comment]
> @saileshkush95 Are you trying to integrate allauth in a Modoboa installation? Or are you using Modoboa as an SMTP server for an application you develop?

I'm using modoboa as a SMTP server. Any way issue is solved
