### ISSUE TITLE
UI is not mobile friendly

### ISSUE THREAD

**Issue by saileshkush95** [modoboa/modoboa#1874]
# Impacted versions

* Modoboa: Latest
* installer used: Yes
* Webserver: Nginx

UI is not mobile friendly

# Video/Screenshot link (optional)
![Screenshot_2020-04-11-08-44-45-316_com brave browser](https://user-images.githubusercontent.com/28560875/79033830-1e99d200-7bd1-11ea-9915-4ec9b44658ca.jpg)

**Comment by tonioo** [comment]
See https://github.com/modoboa/modoboa-webmail/issues/155.
