### ISSUE TITLE
IMAP server issues

### ISSUE THREAD

**Issue by anthrophitech** [modoboa/modoboa#1879]
# Impacted versions

* Modoboa: 1.5.3
* installer used: Not sure
* Webserver: NA

# Steps to reproduce
It's intermittent.
Accessing IMAP via an email client and/or Modoboa's webmail interface.

# Current behavior
Without any particular pattern, we receive IMAP server errors from both email clients , Mail, Outlook and Modoboa's own webmail client.
We get: Socket error: EOF from the webmail interface.
Email clients report generic server errors with IMAP.
After waiting minutes, it usually comes back by itself, but then goes "offline" again.

**Comment by tonioo** [comment]
@anthrophitech Please check server logs, you'll have more information about the issue.

**Comment by anthrophitech** [comment]
Thanks Antoine, but when viewing Logs in web interface, there is nothing of help.

Are there logs I can view via SSH that can shed some light on the problem? Where do I look?

Thank-you for your help.

**Comment by anthrophitech** [comment]
I have found the following:

 

Apr 28 02:13:16 ip-172-31-37-255 dovecot: imap(): Fatal: pool_system_realloc(2097152): Out of memory

Apr 28 02:13:16 ip-172-31-37-255 dovecot: imap(): Fatal: master: service(imap): child 9974 returned error 83 (Out of memory (service imap { vsz_limit=256 MB }, you may need to increase it) - set DEBUG_OUTOFMEM=1 environment to get core dump)

Apr 28 02:13:17 ip-172-31-37-255 dovecot: imap(): Fatal: pool_system_realloc(2097152): Out of memory

Apr 28 02:13:17 ip-172-31-37-255 dovecot: imap(): Fatal: master: service(imap): child 9989 returned error 83 (Out of memory (service imap { vsz_limit=256 MB }, you may need to increase it) - set DEBUG_OUTOFMEM=1 environment to get core dump)

Apr 28 02:13:20 ip-172-31-37-255 dovecot: imap(): Fatal: pool_system_realloc(2097152): Out of memory

Apr 28 02:13:20 ip-172-31-37-255 dovecot: imap(): Fatal: master: service(imap): child 10011 returned error 83 (Out of memory (service imap { vsz_limit=256 MB }, you may need to increase it) - set DEBUG_OUTOFMEM=1 environment to get core dump)

 

 

The machine itself has not run out of memory at any point according to monitoring though.

**Comment by MrGeneration** [comment]
You can adjust your dovecot configuration to have a higher vsz_limit as stated by your error message:

`Out of memory (service imap { vsz_limit=256 MB }, you may need to increase it`

I've done the same within my installation. Personally I don't see this as a modoboa bug directly, as this setting highly depends on your needs and 256MB might be perfectly fine for other users.

**Comment by tonioo** [comment]
I do agree with @MrGeneration. Thanks for your reply anyway. I close this issue.
