### ISSUE TITLE
Are all the strict requirements necessary?

### ISSUE THREAD

**Issue by ntninja** [modoboa/modoboa#1970]
# Impacted versions

* Modoboa: 1.15.*
* installer used: No
* Webserver: Nginx

# Steps to reproduce

Currently Modoboa comes with a rather long list of strict requirements. In particular these include:

  * `dnspython==1.16.0`
  * `gevent==1.4.0` 
  * `dateutil==2.2`
  * `passlib==1.7.2`
  * `feedparser==5.2.1`

Does it really, really, really only work with these particular versions or can these be replaced by minimum compatible version requirements (such as `gevent~=1.4`, `feedparser~=5.2,>=5.2.1`, etc)?

In particular `gevent` is super slow to build and I'd really like to replace it with the [native version provided by Alpine](https://pkgs.alpinelinux.org/package/v3.11/community/x86_64/py3-gevent) in my Docker image, but I can't because of the strict version requirement.

**Comment by tonioo** [comment]
@ntninja Maybe not, but changing them requires to make some compatibility tests and I my time is limited...

**Comment by ntninja** [comment]
Which tests would that be exactly? Can you provide some details on this?

Also, assuming that dependencies adhere to semver, changing say `gevent==1.4.0` to `gevent~=1.4` (i.e. `gevent>=1.4.0,<2`) should be pretty unproblematic, I think?

**Comment by ksaadDE** [comment]
@tonioo  closed? I mean that's not really an issue, I would also not categorize it as enhancement

**Comment by tonioo** [comment]
I guess we can close it since requirements are updated more frequently with depandabot;
