### ISSUE TITLE
Migration between servers, different versions

### ISSUE THREAD

**Issue by othaner** [modoboa/modoboa#1972]
# Impacted versions

* Modoboa: 1.13.1 & 1.15
* installer used: Yes (Both)
* Webserver: Nginx

# Steps to reproduce

# Current behavior
I have two servers with Modoboa installed. I need to migrate from an old one (v1.13.1) to a new one (v1.15). I would like to do a seamless migration without bother my clients with nothing more than change imap server address.

I was thinking on copy /srv/vmail/ folder, but then I realized the user auth problem. Also, I found `modoboa-imap-migration` tool, but I could not even install it on first shot.

Old one has 4-5 domains, with 3-5 identities. How can I do this? Can someone point me in the right direction?

Thank you.

# Expected behavior

# Video/Screenshot link (optional)

**Comment by Pleskan** [comment]
Hi @othaner !
IMO you have to use[ imapsync ](https://imapsync.lamiral.info/).
imap-migration core project is already dead FYI.

**Comment by othaner** [comment]
@Pleskan  Thank you! I will look into it.

**Comment by othaner** [comment]
@Pleskan I wonder, could it be possible with export domains/identities tool in Modoboa? and the scp'd the `vmail` folder.

**Comment by tonioo** [comment]
@othaner Just use rsync to copy /srv/vmail to the new server, and dump/restore the database on the new server.

**Comment by othaner** [comment]
> @othaner Just use rsync to copy /srv/vmail to the new server, and dump/restore the database on the new server.

Yup, in the end I did something alike:
- Export import csvs.
- Rsync vmail folder

Thank you!
