### ISSUE TITLE
Missing option to disable Redirect to Admin Panel

### ISSUE THREAD

**Issue by Gill-Bates** [modoboa/modoboa#1980]
Hey there,

when I enter mail.mydomain.com - nginx will redirect me to https://mail.mydomain.com **/accounts/login/** - this is pretty annoying.

I would love to see the nginx Welcome-Page. Missing painfully a button inside the Admin Options to turning on/off this redirection.

**Comment by tonioo** [comment]
@Gill-Bates It is not possible unless you configure Modoboa to be served on a sub path (something like https://mail.mydomain.com/modoboa/).
