### ISSUE TITLE
FeatureRequest: Empty Trash (Webmail)

### ISSUE THREAD

**Issue by Gill-Bates** [modoboa/modoboa#1981]
Hey there,

missing painfully to move E-Mails in bulk to the Trash, After picking every single mail to move them to Trash, I have to repeat the same steps, to delete them from the Trash Folder. Why is there no Button "Empty Trash" or a bulk function for mass-deletion?

**Comment by tonioo** [comment]
@Gill-Bates You can select more than on email (using the checkboxes) and then move your selection to the trash folder (drag&drop feature). Just click on the icon at the left of a checkbox to that.
Once your emails are in the trash, select this folder and click on the "Actions" dropdown menu. You will find a "Empty folder" menu item you can click on to flush your trash.
