### ISSUE TITLE
uwsgi wont start after update.

### ISSUE THREAD

**Issue by ravarage** [modoboa/modoboa#1991]
# Impacted versions

* Modoboa: 1.15.0
* installer used: Yes
* Webserver: Nginx
* Debian 10 x64

# Steps to reproduce
I  had installed 1.14.0,it worked fine, I installed the new version the same way install 1.14.0, I get error 502, then I find it uwsgi process wont start, I installed 1.14.0 everything start working again  
# Current behavior
error 502
# Expected behavior
uwsgi should start
# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@ravarage What python version do you use?

**Comment by ravarage** [comment]
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux

**Comment by tonioo** [comment]
@ravarage Can you check if the python3 uwsgi package is installed on your system?

**Comment by ravarage** [comment]
@tonioo  it wasnt, that maybe the issue, I figured it out it was uwsgi, but never checked it its install on python 3.7.3,thank you,  I will check it in few days, I am very busy at the moment.

**Comment by tonioo** [comment]
@ravarage Can I close this issue?

**Comment by ravarage** [comment]
> @ravarage Can I close this issue?

sure, sorry I forgot abou this
