### ISSUE TITLE
Error when ldap auth is config

### ISSUE THREAD

**Issue by ASLLR** [modoboa/modoboa#1992]
# Impacted versions

* Modoboa: 1.15
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
sudo -i -u modoboa
bash
virtualenv env
source env/bin/activate
pip install django-auth-ldap

=> modify setting.py 
 AUTHENTICATION_BACKENDS = (
    'modoboa.lib.authbackends.LDAPBackend',
    'modoboa.lib.authbackends.LDAPSecondaryBackend',
    'django.contrib.auth.backends.ModelBackend',
  )
 => configure on web interface my ldap. 
# Current behavior
=> when i want to connect with admin local or LDAP account

ImportError at /accounts/login/
Module "modoboa.lib.authbackends" does not define a "LDAPBackend" attribute/class

Request Method:  POST
Django Version: 2.2.14
Exception Type: ImportError
Exception Value: Module "modoboa.lib.authbackends" does not define a "LDAPBackend" attribute/class
Exception Location: /srv/modoboa/env/lib/python3.7/site-packages/django/utils/module_loading.py in import_string, line 24
Python Executable: /usr/bin/uwsgi-core
Python Version: 3.7.3
Python Path:  ['.',  '',  '/usr/lib/python37.zip',  '/usr/lib/python3.7',  '/usr/lib/python3.7/lib-dynload',  '/srv/modoboa/env/lib/python3.7/site-packages']

# Expected behavior
Can connect to web interface

Thank you

**Comment by ClemRiviere** [comment]
The following line is installing the python2 _django-auth-ldap_ package.
`pip install django-auth-ldap`

As shown in the logs, modoboa is using python3.7

This issue can be solved by installing the python3 _django-auth-ldap_ and _python-ldap_ packages :
```
su - modoboa
bash
source env/bin/activate
python3 -m pip install --upgrade pip
pip3 install python-ldap django-auth-ldap
```
@tonioo can you confirm that this is the better way to solve this ?

**Comment by tonioo** [comment]
@ClemRiviere No it's the right way to install required packages.
@ASLLR Can you check both packages are installed? Have you reloaded uwsgi after you installed the packages?

**Comment by ASLLR** [comment]
Hi,

by default modoboa seem to be use python 2.7. When i try the solution of @ClemRiviere it's works.

Thank you

**Comment by ASLLR** [comment]
I think this issue isn't closed, an update of the documentation is necessary. Or correct the install script to force modoboa to use only python 3

**Comment by MrGeneration** [comment]
I partly agree.
This seems to only happen if you do have python2 installed:
https://github.com/modoboa/modoboa-installer/blob/c3b6ce9b8ec167a6a3c8b1939e6dcf83d97e168f/modoboa_installer/python.py#L52

When I installed modoboa I installed python3 right away and had no version 2 on the host.
If you have this condition, you'd be fine.

So, as it's described on https://modoboa.readthedocs.io/en/latest/manual_installation/modoboa.html it should also have a hint on the requirenments part of the docs: https://modoboa.readthedocs.io/en/latest/installation.html#requirements
