### ISSUE TITLE
please help me upgrade, on 1.14 want to be on 1.16

### ISSUE THREAD

**Issue by tonyguadagno** [modoboa/modoboa#2007]
# Impacted versions

* Modoboa: 1.14
* installer used: Yes
* Webserver: Nginx

i have followed the steps in https://github.com/modoboa/modoboa/issues/1964  but i get an error about not having a config file.  can anyone help me upgrade from 1.14 to 1.16?

**Comment by tonioo** [comment]
1.16 is not available yet. Can you paste your error somewhere?

**Comment by tonyguadagno** [comment]
tonioo, i am confused, this page says 1.16 is available

https://modoboa.readthedocs.io/en/latest/upgrade.html#specific-upgrade-instructions

also, the error is the exact same error as on this issue

https://github.com/modoboa/modoboa/issues/1964
```
Could not find a version that satisfies the requirement modoboa==1.15.0 (from versions: 0.7.0, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.11.0, 1.11.1, 1.12.0, 1.12.1, 1.12.2, 1.13.0, 1.13.1, 1.14.0)
No matching distribution found for modoboa==1.15.0
```

**Comment by tonioo** [comment]
The ``latest`` documentation corresponds to the ``master`` branch, so it might talk about things to come sometimes.

**Comment by tonioo** [comment]
@tonyguadagno 1.16 is now available, you can upgrade if you want to.
