### ISSUE TITLE
Enabling POP3 on a running Modoboa Server

### ISSUE THREAD

**Issue by sergioeix** [modoboa/modoboa#2008]
# Impacted versions

* Modoboa: 1.13.0
* installer used: Yes ?
* Webserver: Nginx

# Steps to reproduce

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

Hello I want to enable POP3 on a running server but i dont know the best way to do that.
May be ...

sudo apt-get install dovecot-imapd dovecot-pop3d
add to dovecot.conf
protocols = imap lmtp sieve pop3 pop3s

anyone can give me an advice or point me to the rigth way.

B/R

**Comment by tonioo** [comment]
@sergioeix That's the way to go if you're on a debian like system. Otherwise you could have let the installer do it for you using the ``extra_protocols`` setting located inside the ``installer.cfg`` file.

**Comment by sergioeix** [comment]
I known it could been done with modoboa on the install stage but now server is running well and i have to enable pop3. Thats why i am asking, i want to know if i am missing something or with these two comands its enougth.
B/R
