### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Salamon75** [modoboa/modoboa#2023]
# Impacted latest

* Modoboa: X.X.x
* installer used: Yes/No ?
* Webserver: mail.salamon.tf
# Steps to reproduce

I am probably very stupid I just installed the program as instructed and I just can't get to the website to log in.
Here is the installation screenshot
https://pasteboard.co/JtYl9gk.jpg

and if you go to the website it's just gives me the basic apache website.
Can you help me where did I go wrong?
Kind Regards,

**Comment by tonioo** [comment]
@Salamon75 Why are you talking about Apache? The installer deploys nginx, not Apache. If you try to install Modoboa like this, on a server which already runs Apache, it won't work.
