### ISSUE TITLE
DKIM signature for domain aliases

### ISSUE THREAD

**Issue by dirtyhillbilly** [modoboa/modoboa#2027]
# Impacted versions

* Modoboa: 1.15.0
* installer used: Yes

# Steps to reproduce

Create a domain and an alias of it.
Send a mail using that aliased domain -> opendkim can't find the key

I had to change the dkim view to achieve this :

```
CREATE OR REPLACE VIEW dkim AS (
SELECT id, name as domain_name, dkim_private_key_path AS private_key_path, dkim_key_selector AS selector
FROM admin_domain WHERE enable_dkim
UNION
SELECT admin_domainalias.id, admin_domainalias.name as domain_name, admin_domain.dkim_private_key_path AS private_key_path, admin_domain.dkim_key_selector AS selector from admin_domainalias 
JOIN admin_domain ON admin_domainalias.target_id=admin_domain.id);
```

**Comment by tonioo** [comment]
@dirtyhillbilly Thank you for this contribution but I see 2 problems with your query:

1. You're using ``admin_domainalias.id`` which is a different sequence than ``domain.id``, so it will create duplicates in the view (I don't know if it's a problem or not)
2. You're including every domain alias in the result without checking if DKIM signing is enabled or not for the related domain

**Comment by dirtyhillbilly** [comment]
I think 1. is a problem, collisions will happen.

This one works better, then. I'm quite new to SQL, as you can see ;) :

```
SELECT id, name as domain_name, dkim_private_key_path AS private_key_path, dkim_key_selector AS selector
FROM admin_domain WHERE enable_dkim
UNION
SELECT -admin_domainalias.id, admin_domainalias.name as domain_name, admin_domain.dkim_private_key_path AS private_key_path, admin_domain.dkim_key_selector AS selector from admin_domainalias 
JOIN admin_domain ON admin_domainalias.target_id=admin_domain.id where enable_dkim;
```

**Comment by dirtyhillbilly** [comment]
clone of #1882

**Comment by dirtyhillbilly** [comment]
Some years and upgrades later, i still use :
`CREATE OR REPLACE VIEW dkim AS  (
   SELECT ROW_NUMBER() OVER(order by domain_name, selector) as id, domain_name, private_key_path, selector FROM
    (SELECT admin_domainalias.name as domain_name, admin_domain.dkim_private_key_path AS private_key_path, admin_domain.dkim_key_selector AS selector from admin_domainalias 
JOIN admin_domain ON admin_domainalias.target_id=admin_domain.id where enable_dkim 
UNION SELECT name as domain_name, dkim_private_key_path AS private_key_path, dkim_key_selector AS selector
FROM admin_domain WHERE enable_dkim) as aliases
);`
