### ISSUE TITLE
Replace 127.0.0.1 by localhost by default for policyd

### ISSUE THREAD

**Issue by AmazingBeu** [modoboa/modoboa#2028]
By default, the policyd daemon listen on the 127.0.0.1 . Use "--host localhost" make the daemon listen on "127.0.0.1" and "::1".

It's not important, but can generate bugs in specific cases.

**Comment by tonioo** [comment]
@AmazingBeu Do you suggest I modify the default host to localhost?

**Comment by AmazingBeu** [comment]
@tonioo Yes, in policyd and postfix.
But I thought of something else but it's more complicated. Maybe it could be nice to use unix sockets instead of the default tcp/ip sockets in Modoboa, for policyd and all other modules. All the software used seems to support this feature, but I'm not sure Modoboa allows you to define a unix socket for Webmail configuration for example.

**Comment by tonioo** [comment]
@AmazingBeu The webmail communicates using SMTP and IMAP protocols. I'm not sure postfix or dovecot support this...
About the policy daemon, it could be possible I guess but it's another story :)

**Comment by AmazingBeu** [comment]
@tonioo from what i found: postfix, dovecot, amavis, opendkim, opendmarc and redis support unix socket.

**Comment by tonioo** [comment]
@AmazingBeu Can you please add a link for dovecot?

**Comment by AmazingBeu** [comment]
@tonioo According to the doc, you have to replace the "inet_listener" by "unix_listener" with the right options :
https://doc.dovecot.org/configuration_manual/service_configuration/?highlight=unix_listeners

**Comment by tonioo** [comment]
@AmazingBeu I'll close this issue since I modified the default values for policyd. I suggest you open a new issue about unix sockets.
