### ISSUE TITLE
Paste Image from Clipboard gives Error 404

### ISSUE THREAD

**Issue by liszca** [modoboa/modoboa#2029]
# Impacted versions

* Modoboa: 1.16.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Make a screenshot, and try to paste it, example in the Video/Screenshot section

# Current behavior
First I get a message about successfull upload immediatly followed by error 404.

# Expected behavior
After pasting the image I expect to be able to resize the image.

# Video/Screenshot link (optional)
[2020-10-06 11-10-33.mkv.zip](https://github.com/modoboa/modoboa/files/5332613/2020-10-06.11-10-33.mkv.zip)

**Comment by liszca** [comment]
Where are pasted images saved? In the `/tmp` folder? Which rights for the folder(s) are needed?

**Comment by tonioo** [comment]
@liszca Actually I don't think it is currently configured. I didn't know it was possible to do this with CKeditor!

**Comment by liszca** [comment]
You are right in the current version it isn't available anymore. If it is CKeditor, well I had trouble with that editor when ever I tried to use it.

I close the Issue, but can you get that feature back in long term?
