### ISSUE TITLE
Redis server  python manage.py policy_daemon not starting

### ISSUE THREAD

**Issue by lmfrazao** [modoboa/modoboa#2032]
# Impacted versions

* Modoboa: 1.16.1
* installer used: No 
* Webserver: Nginx

# Steps to reproduce

on settings.py I've added:

REDIS_HOST = '127.0.0.1'
REDIS_PORT = 6379
REDIS_QUOTA_DB = 0
REDIS_URL = 'redis://127.0.0.1:6379/0'

# Current behavior

redis is running, but  python manage.py policy_daemon just hangs, nothing on redis logs.

what is wrong ?

# Expected behavior

# Video/Screenshot link (optional)

**Comment by harryfoster** [comment]
I thought the same thing, but it's just that the process isn't forked into the background (not sure if it's supposed to), it is writing the quotas to the redis hash at least, and listening on the socket. Follow the [docs](https://modoboa.readthedocs.io/en/latest/manual_installation/modoboa.html#policy-daemon) to make it run as a systemd unit or a supervisor service.

For example, I created the following unit:
```
[Unit]
Description=Modoboa Postfix Policy Daemon"
After=network.target nss-lookup.target syslog.target redis.service

[Service]
User=modoboa
Group=modoboa
WorkingDirectory=/srv/modoboa/
ExecStart=/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py policy_daemon
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

Restarting systemctl daemon, enabling and starting the service all worked fine and I was able to get the postfix daemon to throw me an error when I exceeding sending limits. 

Don't forget to update the webmail settings in the admin control panel to use authentication if you want the policy daemon to count those too. By default, it doesn't send authentication which is what the policy daemon is checking for (sasl_username) and is just relying on localhost.

**Comment by lmfrazao** [comment]
that was it, got it working now!

on roundcube isn't working, since I'm using it for webmail.

any idea on how to use it with roundcube ?

thank you!

**Comment by harryfoster** [comment]
Not really, I'd imagine it's the same as any other backend that Roundcube uses. I'm just using the Modoboa webmail.

**Comment by tonioo** [comment]
@lmfrazao Same solution, use port 587 with authentication for Roundcube.

**Comment by lmfrazao** [comment]
Just updated to 1.17.0 and now it doesn't start:

Nov 07 13:05:23 prod-smtp-01.loc python[4429]: output = self.handle(*args, **options)
Nov 07 13:05:23 prod-smtp-01.loc python[4429]: File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/policyd/management/commands/policy_daemon.py", line 39, in handle
Nov 07 13:05:23 prod-smtp-01.loc python[4429]: server = loop.run_until_complete(coro)
Nov 07 13:05:23 prod-smtp-01.loc python[4429]: File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
Nov 07 13:05:23 prod-smtp-01.loc python[4429]: return future.result()
Nov 07 13:05:23 prod-smtp-01.loc python[4429]: File "/usr/lib64/python3.6/asyncio/streams.py", line 119, in start_server
Nov 07 13:05:23 prod-smtp-01.loc python[4429]: return (yield from loop.create_server(factory, host, port, **kwds))
Nov 07 13:05:23 prod-smtp-01.loc python[4429]: File "/usr/lib64/python3.6/asyncio/base_events.py", line 1066, in create_server
Nov 07 13:05:23 prod-smtp-01.loc python[4429]: % (sa, err.strerror.lower()))
Nov 07 13:05:23 prod-smtp-01.loc python[4429]: OSError: [Errno 99] error while attempting to bind on address ('::1', 9999, 0, 0): cannot assign requested address

any help ?

**Comment by tonioo** [comment]
@lmfrazao Try using ipv4.

**Comment by lmfrazao** [comment]
Yes, I have it disabled on the os, how is it trying to bind to it? Same script that is starting it.

Luís Frazão | Bild Corp
+351 914120170
www.bild.pt
________________________________

**Comment by lmfrazao** [comment]
fixed, had localhost defined as ::1 also in /etc/hosts

thanx!
