### ISSUE TITLE
Upgrade to 1.16.1 doesn't work

### ISSUE THREAD

**Issue by ivdok** [modoboa/modoboa#2033]
# Impacted versions

* Modoboa: 1.15.0
* installer used: ?
* Webserver: Nginx

# Steps to reproduce

> sudo -u modoboa bash
> cd ~
> source env/bin/activate
> pip install modoboa==1.16.1
> cd instance
> python manage.py migrate
> python manage.py collectstatic
> python manage.py check --deploy
> ^D
> systemctl restart nginx
# Current behavior
`One or more updates are available!` in Web UI, still showing 1.15.0
# Expected behavior
Updated environment

**Comment by MrGeneration** [comment]
Modoboa is based von Django and in order for modoboa to reload, restarting your webserver is not enough.
Restart `uwsgi` which is responsible for the modoboa part - after that you should be fine.
