### ISSUE TITLE
How to send and receive emails using the REST API of Modoboa

### ISSUE THREAD

**Issue by SellamiRami** [modoboa/modoboa#2069]
Hello all, 
I want to integrate Modoboa in a private project in which we developed a client web interface that is connected to the Modoboa server (i.e. Backend).
Via this client web interface, I want to exchange emails with attachement. However, I do not find any operations in the REST API of Modoboa (i.e. https://modoboa.readthedocs.io/en/latest/rest_api.html) enabling sending and receiving emails with attachement.
Could you please tell me how we can ensure these features using the REST API of Modoboa?
Thank you in advance for your response.
Best regards, 
Rami.

**Comment by tonioo** [comment]
@SellamiRami You can't do this using the REST API. I suggest you use IMAP/SMTP protocols instead.

**Comment by SellamiRami** [comment]
Thank you @tonioo for your quick reply. Could you please give more details about this (e.g. a documentation)?
Thanks in advance for your help !
Rami.

**Comment by tonioo** [comment]
@SellamiRami IMAP and SMTP are old and standard protocols. You can find a lot of documentation on the Internet about them and most programming language provide ready-to-use client modules.
