### ISSUE TITLE
Question: Update from 1.10.3

### ISSUE THREAD

**Issue by k-hristov** [modoboa/modoboa#2073]
Hey,
Modoboa rulz!

I have a simple question:
I am running modoboa version 1.10.3. Will it be safe to upgrade to the latest version by following the steps in the documentation? Also what are the key features to be backed up ? Email folders, database (postgre) and probably something else ?

https://prnt.sc/v8w07s

Also on the version i am running i have manually configured openDKIM. Will this somehow break up the upgrade process. I have 3 domains only.

**Comment by tonioo** [comment]
@k-hristov upgrade should be fine if you follow the instructions. Don't forget to upgrade all extensions too.
 You can backup the database, email folders and maybe configuration file in /etc but if you upgrade manually, you should not have problems.
And your OpenDKIM won't be modified if you don't use the installer.
