### ISSUE TITLE
Domain Quota Not Functioning

### ISSUE THREAD

**Issue by mattg66** [modoboa/modoboa#2078]
# Impacted versions

OS Type: Debian
OS Version: 10
Modoboa: 1.15.0
Installer used: Yes ?
Webserver: Nginx

# Steps to reproduce
Domain Quota doesn't show usage when set. Bar is empty.
# Current behavior
Domain quota bar shows when a mailbox has a quota set on it
# Expected behavior
Domain quota bar should show usage of all mailboxes associated with the domain

**Comment by tonioo** [comment]
@mattg66 Have you defined a quota for your domain?

**Comment by mattg66** [comment]
![image](https://user-images.githubusercontent.com/56981878/98245195-7aaab600-1f68-11eb-9df7-859082321756.png)

**Comment by tonioo** [comment]
Default mailbox quota is set to 0, which means no quota. Did you define quota manually on the mailboxes you created for this domain?

**Comment by mattg66** [comment]
No, I did not set the quota for individual accounts, I thought the idea of a domain quota was an overall restriction on the amount of space the domain as a whole can use?

**Comment by tonioo** [comment]
@mattg66 It is not the way it works. The domain quota is a pool you can allocate from for mailboxes. The rule is simple: the sum of all mailboxes quota must not exceed the domain quota.
