### ISSUE TITLE
Can't login after installing

### ISSUE THREAD

**Issue by davekimble2** [modoboa/modoboa#2083]
# Impacted versions

* OS Type: Debian/Ubuntu, Centos/Redhat, Arch, Gentoo, Slack, ...Ubuntu
* OS Version: Number or Name 20.04
* Database Type: PostgreSQL/MySQL postgresql
* Database version: X.y 12+214ubuntu0.1
* Modoboa: X.X.x 1.17.0
* installer used: Yes/No ? Yes
* Webserver: Nginx/Apache Nginx

# Steps to reproduce
Install with modoboa-installer, goto https://mail.mydomain.com, login screen asks for username and password, but what default username and password?
# Current behavior
I haven't specified any username and password yet !  Tried user = postmaster, default, blank, admin.  Tried password = blank, 1234, ****.  All failed.  "Forgot password" doesn't send anything to me.
# Expected behavior

# Video/Screenshot link (optional)

**Comment by maxcco** [comment]
If I'm correct default should be 
admin / password
