### ISSUE TITLE
"domain does not exist" error when creating user

### ISSUE THREAD

**Issue by devhammed** [modoboa/modoboa#2086]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 20.04.1
* Database Type: PostgreSQL
* Database version: psql (PostgreSQL) 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1)
* Modoboa: 1.17.0
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce

Try to create a new user.

# Current behavior

Getting "domain does not exist" error

# Expected behavior

To create a new user.

# Video/Screenshot link (optional)

![Screenshot from 2020-11-23 16-41-43](https://user-images.githubusercontent.com/22827908/99982402-cce23880-2daa-11eb-86c7-411e8bee602f.png)

**Comment by tonioo** [comment]
@devhammed Have you created the corresponding domain first?

**Comment by devhammed** [comment]
> @devhammed Have you created the corresponding domain first?

I just did and it is working correctly!
