### ISSUE TITLE
Incoming message bounces for one mail account

### ISSUE THREAD

**Issue by adrian-abit** [modoboa/modoboa#2097]
# Impacted versions

* OS Type: Debian
* OS Version: 10.4
* Database Type: MySQL
* Database version: 15.1
* Modoboa: 1.17.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Install Modoboa, add an account and try to send an email to the account
# Current behavior
Mail bounces when sent to admin@abit.dev with the message: `550 5.1.1 <admin@abit.dev>: Recipient address rejected: undeliverable address: mail for abit.dev loops back to myself`

Mails sent from admin@abit.dev get delivered correctly.

Mails to postmaster@adrianbit.tech, test@abit.dev etc. go through. Only this account bounces. 
# Expected behavior
Mail should go through.
# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@adrian-abit Looks like your @abit.dev domain is listed more than once in postfix configuration... What are your values for myhostname and mydestination in main.cf file?
