### ISSUE TITLE
How to renew letsencrypt SSL cert?

### ISSUE THREAD

**Issue by Computroniks** [modoboa/modoboa#2108]
# Impacted versions

* OS Type: Ubuntu 18.04.4 LTS
* Database Type: PostgreSQL
* Database version: 10.15
* Modoboa: 1.17.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Standard install using installer but changing SSL cert from self signed to letsencrypt.

I have tried a manually running the command in /etc/cron.d/letsencrypt but recived the following error

```
Attempting to renew cert (mail.example.com) from /etc/letsencrypt/renewal/mail.examlpe.com.conf produced an unexpected error: Failed authorization procedure. mail.example.com (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from https://mail.example.com/.well-known/acme-challenge/j2JLqbhZ0r-rLL6cjf36gDFnkQz0qcNRsIQ6Fnb0nzs [79.66.236.109]: "<!DOCTYPE html>\n\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title></title>\n    <link rel=\"icon\" type=\"image/png". Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/mail.example.com/fullchain.pem (failure)
```

Most of the slightly older issues to do with updating the SSL cert such as #1546 and [#116 on modoboa-installer](https://github.com/modoboa/modoboa-installer/issues/116) suggest using:
```
/opt/certbot-auto -q renew --pre-hook 'nginx -t && service stop nginx stop' --post-hook 'nginx -t && service nginx start && service postfix reload && service dovecot reload'
```
or 
```
/opt/certbot-auto renew --no-self-upgrade --force-renewal
```
but it seems that /opt/certbot-auto doesn't exist. Presumably because it has been depreciated by letsencrypt. There also doesn't seem to be anything in the docs about renewing the certificate.

**Comment by MrGeneration** [comment]
According to this class it should be installed automatically:
https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/ssl.py#L63-L110

In my humble opinion generation of the initial certificate should have failed if that was not the case. Possibly it was removed too.
It's hard to tell without knowing which command you're running.

A quick and dirty try may be to manually install certbot ( https://certbot.eff.org/instructions ) and try again.

**Comment by gawel** [comment]
You're trying to renew a certificat for a domain that you don't own (mail.example.com)
I guess you leaved defaults values somewhere in the config file

**Comment by Computroniks** [comment]
> You're trying to renew a certificat for a domain that you don't own (mail.example.com)
> I guess you leaved defaults values somewhere in the config file

No that is just me not wanting to share my domain name
