### ISSUE TITLE
Disabled account can still receive email

### ISSUE THREAD

**Issue by jeromelebleu** [modoboa/modoboa#2120]
# Impacted versions

* OS Type: Debian
* OS Version: Buster
* Database Type: PostgreSQL
* Database version: 11
* Modoboa: 1.17.0

# Steps to reproduce

1. Create an account with _Simple user_ role and disable it - either at the creation or after
2. Send an email to this account

# Current behavior

Even if the account is disabled, the recipient is still allowed by Postfix and the email is delivered.

# Expected behavior

If I understand the meaning of a disabled account, emails to this address should be rejected.

# Debugging

While trying to find in Postfix when this recipient is accepted, I found that it was by looking up in `sql-aliases.cf` table. Even if there is a condition on `enabled` in the `admin_alias` table, the object is still returned. And indeed, even if the `core_user` is disabled, the corresponding `admin_alias` is not.

**Comment by cyberal77** [comment]
Hi,

I Cant reproduce. 

When i send mail to desactivated user, it's reject.

Regard

**Comment by jeromelebleu** [comment]
Thanks @cyberal77 to give it a try! Are you also using the last Modoba's version? I encounter that on manual installations too, but my Postfix configuration is almost the same as the automatic installer's one. Anyway, from what I understood, I don't think this is related.

Could you also check that the corresponding `admin_alias`'s object is also disabled please? For example, here is what I have in a shell:
```python
>>> from modoboa.core.models import User
>>> from modoboa.admin.models import Alias

>>> u = User.objects.get(email='user2@example.org')
>>> u.enabled
False
>>> a = Alias.objects.get(address=u.email)
>>> a.enabled
True
>>> a.internal
True
```

**Comment by kryskool** [comment]
Hi @jeromelebleu 

It seem that @tonioo fix the problem in this [commit](https://github.com/modoboa/modoboa/commit/1aed875f6865046a0d538a1a0772e50962987789) can you retry ?

Regards,

**Comment by jeromelebleu** [comment]
Hi @kryskool, no it does not fix this problem and this is why I commented this commit. It only disables aliases which have been added *manually* from the interface (`internal=False`) and not automatically like here (`internal=True`).

**Comment by Toniob** [comment]
Hi,

I’m running 1.17.0 and I added the patch manually. But the mail are still received. I think that’s because that’s dovecot-lmtp which is responsible for accepting or not the mail. And in the user_query in dovecot, we never check for the is_active attribute.
