### ISSUE TITLE
False positive DNSBL reports because of spamcop.net

### ISSUE THREAD

**Issue by phpony** [modoboa/modoboa#2148]
# Impacted versions

All.

# Steps to reproduce

Just have any domain in modoboa.

# Current behavior

Getting a lot of service emails:

```
Modoboa detected that domain example.com is listed by the following DNSBL providers:


  bl.spamcop.net: example2.com (1.1.1.1) for example.com 


The domain's reputation will be affected and there is a chance that emails coming from it are considered as spam. You should contact those providers and ask them to unlist detected IP address(es).
```

# Expected behavior

spamcop.net domain is expired, this service is not working anymore and so those reports should be considered as false-positive.

**Comment by mackcoding** [comment]
Hi, I'm still using and actively reporting mail to Spamcop. The domain is not expired and is renewed until 1/30/2022. What makes you think the service isn't working anymore?

```
:~$ whois spamcop.net
   Domain Name: SPAMCOP.NET
   Registry Domain ID: 3340109_DOMAIN_NET-VRSN
   Registrar WHOIS Server: whois.enom.com
   Registrar URL: http://www.enom.com
   Updated Date: 2021-01-31T16:04:06Z
   Creation Date: 1999-01-30T05:00:00Z
   Registry Expiry Date: 2022-01-30T05:00:00Z
```

**Comment by JeroenvO** [comment]
Seems no longer an issue, just got a few modoboa mails with errors but can't find it back in the interface. spamcop doesn't list me either.

**Comment by tonioo** [comment]
https://www.theregister.com/2021/02/01/in_brief_security/
Looks like this was just a temporary issue.
