### ISSUE TITLE
Error 500 when accessing the browser for the first time.

### ISSUE THREAD

**Issue by MiteNy** [modoboa/modoboa#2152]
# Impacted versions

* OS Type:Ubuntu
* OS Version:20.04
* Database Type: MySQL
* installer used: Yes
* Webserver: Nginx

# Current behavior

Good afternoon, first I apologize for my English. Today I installed Modoboa and right from the start it presented an error in the browser.
https://prnt.sc/yfo3qh
https://prnt.sc/yfo6i4

**Comment by tonioo** [comment]
@MiteNy Can you set DEBUG to True inside settings.py, reload uwsgi and try again? You should get more information.
