### ISSUE TITLE
Installer should check if 'host' is installed

### ISSUE THREAD

**Issue by cyrilst** [modoboa/modoboa#2154]
# Impacted versions

* OS Type: Debian (but should apply to all OS)
* OS Version: 10.7
* Modoboa: 1.17.0
* installer used: Yes

# Steps to reproduce
Use the installer on a system without the binary `host`. It happened to me with a VPS from OVH, installed with a "stock" Debian 10.

# Current behavior
There are no error during install.
`/usr/local/bin/spf-tools/despf.sh` fails silently. So `postwhite` fails silently, and `/etc/postfix/postscreen_spf_whitelist.cidr` is empty.

# Expected behavior
If `host` doesn't exist, it should be installed by the installer. In Debian, it's included in the `bind9-host` package.

**Comment by Spitfireap** [comment]
Installer is now installing `bind9-host` for Debian based disto.
