### ISSUE TITLE
The List for "standard password scheme" is empty

### ISSUE THREAD

**Issue by Sysadminfromhell** [modoboa/modoboa#2164]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 20.10
* Database Type: I actually dont know, i used the Installer
* Database version: see above
* Modoboa: 1.17.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
I go to the Website -> Modoboa -> Parameters, the List for "standard password scheme" is empty

# Current behavior

The list is empty after a reboot of the Server.

Is theyre an issue with a mysql instance byside this?

# Expected behavior
In the List should be CRYPT.

# Tried fixes:
I tried to fix the issue by editing the dovecot config and change MD5 to CRYPT
I tried to fix the issue by adding vmail to dovecot group
I tried to fix the issue by editing the dovecot-sql.conf.ext and dovecpt-sql-master.conf.ext and change the default_pass_scheme to CRYPT
I tried to fix the issue by changing my dovecot Certificate to my wildcard for my domain

**Comment by tonioo** [comment]
Have you checked this discussion: https://github.com/modoboa/modoboa/discussions/1731?

**Comment by Sysadminfromhell** [comment]
Yes right now i tried to add modoboa to Dovecot group but no change. Error Logs are Empty aswell so far and the command doveadm pw -l tells me just:
`doveconf: Fatal: Error in configuration file /etc/dovecot/conf.d/10-ssl.conf line 13: ssl_cert: Can't open file /etc/letsencrypt/live/sysadminfromhell.dev/fullchain.pem: Permission denied`
but when i check the permissions from the old certificate and my "new" certificate its the same:

`/etc/letsencrypt/archive/mail.sysadminfromhell.dev# ls -l
total 16
-rw-r--r-- 1 root root 1870 Feb  5 14:09 cert1.pem
-rw-r--r-- 1 root root 1586 Feb  5 14:09 chain1.pem
-rw-r--r-- 1 root root 3456 Feb  5 14:09 fullchain1.pem
-rw------- 1 root root 1708 Feb  5 14:09 privkey1.pem

/etc/letsencrypt/archive/sysadminfromhell.dev# ls -l
total 16
-rw-r--r-- 1 root root 1862 Feb  6 14:11 cert1.pem
-rw-r--r-- 1 root root 1586 Feb  6 14:11 chain1.pem
-rw-r--r-- 1 root root 3448 Feb  6 14:11 fullchain1.pem
-rw------- 1 root root 1704 Feb  6 14:11 privkey1.pem`

Is there something with the permissions what I don't see?

**Comment by Sysadminfromhell** [comment]
Update: I tried what was suggested in Post [https://github.com/postfixadmin/postfixadmin/issues/398#issuecomment-737301398](url) and reboot the Server but still no change.

**Comment by Sysadminfromhell** [comment]
I could fix the access denied problem for the modoboa User with chmod 755 live/ and the same for archive/ but the list in parameters remains empty.
