### ISSUE TITLE
401 Authorization Required

### ISSUE THREAD

**Issue by Sequential-circuits** [modoboa/modoboa#2195]
Installed it TWICE using the installed on a Ubuntu 20.04.2 LTS running nginx/1.18.0 using python both 3.6.13 and 3.8.5 and when I go to the login page I get a 401 Authorization Required

The autoconfig is
This file was automatically installed on 2021-03-08T09:04:56.008421

upstream automx {
server unix:/run/uwsgi/app/automx_instance/socket fail_timeout=0;
}

server {
listen 80;
listen [::]:80;
server_name autoconfig.alcosta.eu;
root /srv/automx/instance;

access_log /var/log/nginx/autoconfig.alcosta.eu-access.log;
error_log /var/log/nginx/autoconfig.alcosta.eu-error.log;

location /mail/config-v1.1.xml {
    include uwsgi_params;
    uwsgi_pass automx;
}

}
And the mail.alcosta.eu.conf is
This file was automatically installed on 2021-03-08T09:04:56.066012

upstream modoboa {
server unix:/run/uwsgi/app/modoboa_instance/socket fail_timeout=0;
}

server {
listen 80;
listen [::]:80;
server_name mail.alcosta.eu;
rewrite ^ https://$server_name$request_uri? permanent;
}

server {
listen 443 ssl;
listen [::]:443 ssl;
server_name mail.alcosta.eu;
root /srv/modoboa/instance;

ssl_certificate /etc/ssl/certs/mail.alcosta.eu.cert;
ssl_certificate_key /etc/ssl/private/mail.alcosta.eu.key;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
ssl_prefer_server_ciphers on;
ssl_session_cache shared:SSL:10m;
ssl_verify_depth 3;
ssl_dhparam /etc/nginx/dhparam.pem;

client_max_body_size 10M;

access_log /var/log/nginx/mail.alcosta.eu-access.log;
error_log /var/log/nginx/mail.alcosta.eu-error.log;

location /sitestatic/ {
    try_files $uri $uri/ =404;
}

location /media/ {
    try_files $uri $uri/ =404;
}

location / {
    include uwsgi_params;
    uwsgi_param UWSGI_SCRIPT instance.wsgi:application;
    uwsgi_pass modoboa;
}

location ~* ^/autodiscover/autodiscover.xml {
    include uwsgi_params;
    uwsgi_pass automx;
}
location /mobileconfig {
    include uwsgi_params;
    uwsgi_pass automx;
}

location /radicale/ {
    proxy_pass http://localhost:5232/; # The / is important!
    proxy_set_header X-Script-Name /radicale;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass_header Authorization;
}

**Comment by tonioo** [comment]
@Sequential-circuits Are you talking about modoboa or automx? If I go to mail.alcosta.eu, I can see a running Modoboa instance.

**Comment by tonioo** [comment]
@Sequential-circuits Any news?
