### ISSUE TITLE
error 451 4.3.5

### ISSUE THREAD

**Issue by CHazz** [modoboa/modoboa#2200]
hi, i have new error without any reasson .. maybe restart or update any package .. but now have this :/

debian 10, maria 10.5 , nginx mainline, -- 

Mar 18 16:56:16 mail postfix/postscreen[20786]: CONNECT from [127.0.0.1]:57479 to [127.0.0.1]:25
Mar 18 16:56:16 mail postfix/postscreen[20786]: WHITELISTED [127.0.0.1]:57479
Mar 18 16:56:16 mail postfix/smtpd[20787]: connect from localhost[127.0.0.1]
Mar 18 16:56:17 mail postfix/smtpd[20787]: warning: problem talking to server 127.0.0.1:9999: Success
Mar 18 16:56:17 mail postfix/smtpd[20787]: NOQUEUE: reject: RCPT from localhost[127.0.0.1]: 451 4.3.5 <user@domain2.eu>: Recipient address rejected: Server configuration problem; from=<user@domain1.net> to=<user@domain2.eu> proto=ESMTP helo=<email.domain1.net>
Mar 18 16:56:17 mail postfix/smtpd[20787]: disconnect from localhost[127.0.0.1] ehlo=1 auth=1 mail=1 rcpt=0/1 rset=1 quit=1 commands=5/6

thanks a lot  !

**Comment by CHazz** [comment]
i disable modoboa policy .. all working now .. but not known where is bug ...
`# Recipient restriction rules
smtpd_recipient_restrictions =
#modoboa bug #  check_policy_service inet:127.0.0.1:9999
      permit_mynetworks
      permit_sasl_authenticated
      check_recipient_access
          proxy:mysql:/etc/postfix/sql-maintain.cf
          proxy:mysql:/etc/postfix/sql-relay-recipient-verification.cf
      reject_unverified_recipient
      reject_unauth_destination
      reject_non_fqdn_sender
      reject_non_fqdn_recipient
      reject_non_fqdn_helo_hostname

## Postcreen settings
`
port is working for python .. 

`hidden@mail:/etc/postfix# sudo netstat -tnlp | grep :9999
tcp        0      0 127.0.0.1:9999          0.0.0.0:*               LISTEN      25510/python
tcp6       0      0 ::1:9999                :::*                    LISTEN      25510/python
`

**Comment by tonioo** [comment]
@CHazz The policy daemon is using ipv6 but your postfix configuration tries to use ipv4. You can force the use of ipv4 by using the --host option available with the policy_daemon startup script.

**Comment by CHazz** [comment]
thanks for reply .. i try set force ipv4 in /etc/supervisor/conf.d/policyd.conf
command=/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py policy_daemon --host 127.0.0.1

deamon listening now only on ipv4

root@mail:/var/log# sudo netstat -tnlp | grep :9999
tcp        0      0 127.0.0.1:9999          0.0.0.0:*               LISTEN      5149/python

but have same error :( 

Mar 20 20:02:02 mail postfix/postscreen[11084]: CONNECT from [127.0.0.1]:7297 to [127.0.0.1]:25
Mar 20 20:02:02 mail postfix/postscreen[11084]: WHITELISTED [127.0.0.1]:7297
Mar 20 20:02:02 mail postfix/smtpd[11085]: connect from localhost[127.0.0.1]
Mar 20 20:02:03 mail postfix/smtpd[11085]: warning: problem talking to server 127.0.0.1:9999: Success
Mar 20 20:02:03 mail postfix/smtpd[11085]: NOQUEUE: reject: RCPT from localhost[127.0.0.1]: 451 4.3.5 <martin@tuxlinux.eu>: Recipient address rejected: Server configuration problem; from=<martin@netpixeldesign.net> to=<martin@tuxlinux.eu> proto=ESMTP helo=<email.netpixeldesign.net>
Mar 20 20:02:03 mail postfix/smtpd[11085]: disconnect from localhost[127.0.0.1] ehlo=1 auth=1 mail=1 rcpt=0/1 rset=1 quit=1 commands=5/6

something wrong from my side ? thanks

**Comment by tonioo** [comment]
Have you checked supervisor logs for the policyd component?

**Comment by CHazz** [comment]
ah here is problem ... but not know where 

`2021-03-20 21:35:47,694 INFO spawned: 'policyd' with pid 18503
2021-03-20 21:35:47,698 INFO spawned: 'radicale' with pid 18504
2021-03-20 21:35:47,934 INFO exited: radicale (exit status 1; not expected)
2021-03-20 21:35:48,935 INFO success: policyd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-03-20 21:35:48,936 INFO spawned: 'radicale' with pid 18539
2021-03-20 21:35:49,156 INFO exited: radicale (exit status 1; not expected)
2021-03-20 21:35:51,168 INFO spawned: 'radicale' with pid 18541
2021-03-20 21:35:51,381 INFO exited: radicale (exit status 1; not expected)
2021-03-20 21:35:54,387 INFO spawned: 'radicale' with pid 18618
2021-03-20 21:35:54,602 INFO exited: radicale (exit status 1; not expected)
2021-03-20 21:35:55,604 INFO gave up: radicale entered FATAL state, too many start retries too quickly
2021-03-20 21:42:16,684 INFO waiting for policyd to die
2021-03-20 21:42:16,700 WARN received SIGTERM indicating exit request
2021-03-20 21:42:16,913 INFO stopped: policyd (exit status 1)
2021-03-20 21:42:17,125 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-03-20 21:42:17,125 INFO Included extra file "/etc/supervisor/conf.d/policyd.conf" during parsing
2021-03-20 21:42:17,125 INFO Included extra file "/etc/supervisor/conf.d/radicale.conf" during parsing
2021-03-20 21:42:17,136 INFO RPC interface 'supervisor' initialized
2021-03-20 21:42:17,136 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2021-03-20 21:42:17,136 INFO supervisord started with pid 22963
2021-03-20 21:42:18,139 INFO spawned: 'policyd' with pid 22971
2021-03-20 21:42:18,143 INFO spawned: 'radicale' with pid 22972
2021-03-20 21:42:18,368 INFO exited: radicale (exit status 1; not expected)
2021-03-20 21:42:19,370 INFO success: policyd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-03-20 21:42:19,373 INFO spawned: 'radicale' with pid 23005
2021-03-20 21:42:19,599 INFO exited: radicale (exit status 1; not expected)
2021-03-20 21:42:21,603 INFO spawned: 'radicale' with pid 23010
2021-03-20 21:42:21,818 INFO exited: radicale (exit status 1; not expected)
2021-03-20 21:42:24,825 INFO spawned: 'radicale' with pid 23022
2021-03-20 21:42:25,042 INFO exited: radicale (exit status 1; not expected)
2021-03-20 21:42:26,043 INFO gave up: radicale entered FATAL state, too many start retries too quickly
`
and 

Task exception was never retrieved
future: <Task finished coro=<run_at() done, defined at /srv/modoboa/env/lib/python3.7/site-packages/modoboa/policyd/core.py:64> exception=OSError("Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379)")>
Traceback (most recent call last):
  File "/srv/modoboa/env/lib/python3.7/site-packages/modoboa/policyd/core.py", line 67, in run_at
    return await coro(*args)
  File "/srv/modoboa/env/lib/python3.7/site-packages/modoboa/policyd/core.py", line 258, in reset_counters
    rclient = await aioredis.create_redis_pool(settings.REDIS_URL)
  File "/srv/modoboa/env/lib/python3.7/site-packages/aioredis/commands/__init__.py", line 198, in create_redis_pool
    loop=loop)
  File "/srv/modoboa/env/lib/python3.7/site-packages/aioredis/pool.py", line 58, in create_pool
    await pool._fill_free(override_min=False)
  File "/srv/modoboa/env/lib/python3.7/site-packages/aioredis/pool.py", line 383, in _fill_free
    conn = await self._create_new_connection(self._address)
  File "/srv/modoboa/env/lib/python3.7/site-packages/aioredis/connection.py", line 113, in create_connection
    timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 388, in wait_for
    return await fut
  File "/srv/modoboa/env/lib/python3.7/site-packages/aioredis/stream.py", line 24, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 968, in create_connection
    ', '.join(str(exc) for exc in exceptions)))
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379)

and radicale 

[7f93f85ed740] ERROR: An exception occurred during server startup: Failed to load storage module 'radicale_storage_by_index': No module named 'radicale.storage.multifilesystem'; 'radicale.storage' is not a package
[7f8075206740] ERROR: An exception occurred during server startup: Failed to load storage module 'radicale_storage_by_index': No module named 'radicale.storage.multifilesystem'; 'radicale.storage' is not a package
[7f2ef090d740] ERROR: An exception occurred during server startup: Failed to load storage module 'radicale_storage_by_index': No module named 'radicale.storage.multifilesystem'; 'radicale.storage' is not a package
[7fda8764b740] ERROR: An exception occurred during server startup: Failed to load storage module 'radicale_storage_by_index': No module named 'radicale.storage.multifilesystem'; 'radicale.storage' is not a package
[7fb88ea61740] ERROR: An exception occurred during server startup: Failed to load storage module 'radicale_storage_by_index': No module named 'radicale.storage.multifilesystem'; 'radicale.storage' is not a package

**Comment by tonioo** [comment]
Have you installed redis and is it running?

For Radicale, can you check what version you're running?

**Comment by CHazz** [comment]
redis is not present on this system..  its not contain in modoboa installer ?

**Comment by jfs** [comment]
Just did a brand new install on Debian 10 using the installer (also my first time using Modoboa) and I think I have the exact same problem. I would say, since this is a brand new install, there is an opportunity to improve the installer.

```
Apr 27 18:52:42 localhost postfix/submission/smtpd[3427]: warning: problem talking to server 127.0.0.1:9999: Success
Apr 27 18:52:42 localhost postfix/submission/smtpd[3427]: NOQUEUE: reject: RCPT from 207-153-27-158.static.fttp.usinternet.com[ 123.45.67.89]: 451 4.3.5 <recepient@target-domain.com>: Recipient address rejected: Server configuration problem; from=<sender@source-domain.com> to=<recepient@target-domain.com> proto=ESMTP helo=<smtpclient.apple>
```

Looks like if I install redis-server this will resolve my issue? Anything special I need to do config wise?

**Comment by jfs** [comment]
Actually I just looked and redis-server is installed. Might be the ipv4 vs ipv6 thing.

**Comment by rheinon** [comment]
To those having install issues on Debian 10, are you using at least 8GB storage during initial install?  I had all kinds of problems when installed below that.

**Comment by jfs** [comment]
I'm on a new VM with 2GB memory and 50GB of disk space. My understanding was that was fine for a small install.

**Comment by jfs** [comment]
Forcing ipv4 worked...

In `/etc/supervisor/conf.d/policyd.conf`
```
command=/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py policy_daemon --host 127.0.0.1
```

**Comment by mcg-simple** [comment]
It didn't work for me. I set "--host 127.0.0.1" and there's still the same error.

**Comment by SofianeLasri** [comment]
I have the same error and I have set "--host 127.0.0.1". Redis is already installed on my server.

**Comment by SofianeLasri** [comment]
Here is the reason of the problem: https://github.com/ray-project/ray/issues/17475
So delete all aioredis packages here : /srv/modoboa/env/lib/python3.7/site-packages`
And install the version 1.3.1 with this command: `pip3 install -Iv aioredis==1.3.1 --target=/srv/modoboa/env/lib/python3.7/site-packages`
Reboot your server and the problem will be solved.

**Comment by pcd1000** [comment]
I have tried the "--host 127.0.0.1" fix, but it didn't work for me. I am not sure if I am confident enough to attempt a downgrad to 1.3.1 , do you have any more detailed instructions on how to do this, more specifically, what files/directories to delete?

**Comment by JettBurns14** [comment]
I tried adding "--host 127.0.0.1" to the `/etc/supervisor/conf.d/policyd.conf` file and rebooting without success in my case.

I followed the advise of @SofianeLasri to revert the AIORedis version and that immediately fixed my issue. I am running **Ubuntu Server 20.04.2, Python 3.8.10, and Modoboa 1.17.0** (latest currently) on a **2 core, 2 GB RAM, 25 GB SSD Proxmox virtual machine**. Working perfectly now, hope this helps someone! :smiley: 

Here are the commands I used and the error logs from previously:
```bash
# python3.8 for me, your version may vary
cd /srv/modoboa/env/lib/python3.8/site-packages/

# Should see at least two related packages
ls | grep 'aioredis'

# Remove broken packages
sudo rm -rf aioredis aioredis-2.0.0.dist-info/

# Should see no output
ls | grep 'aioredis'

# I needed to install pip
sudo apt install python3-pip

# Install older, working packages
sudo pip3 install -Iv aioredis==1.3.1 --target=/srv/modoboa/env/lib/python3.8/site-packages

# Should see the new packages, v1.3.1
ls | grep 'aioredis'

# Reboot
reboot
```

Main error I was getting, logs from `/var/log/mail.log`:
```
Sep  3 23:12:25 srv2 postfix/submission/smtpd[378393]: connect from ***********.com[***.***.***.***]
Sep  3 23:12:25 srv2 postfix/submission/smtpd[378393]: Anonymous TLS connection established from ***********.com[***.***.***.***]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (
256/256 bits) key-exchange ECDHE (P-256) server-signature RSA-PSS (2048 bits)
Sep  3 23:12:26 srv2 postfix/submission/smtpd[378393]: warning: problem talking to server 127.0.0.1:9999: Success
Sep  3 23:12:26 srv2 postfix/submission/smtpd[378393]: NOQUEUE: reject: RCPT from ***********.com[***.***.***.***]: 451 4.3.5 <****@****.com>: Recipient address reject
ed: Server configuration problem; from=<****@****.com> to=<****@****.com> proto=ESMTP helo=<[***.***.***.***]>
Sep  3 23:12:28 srv2 postfix/submission/smtpd[378393]: disconnect from ***********.com[***.***.***.***] ehlo=2 starttls=1 auth=1 mail=1 rcpt=0/1 quit=1 commands=6/7

Sep  3 23:12:39 srv2 postfix/submission/smtpd[378511]: connect from unknown[***.***.***.***]
Sep  3 23:12:39 srv2 postfix/submission/smtpd[378511]: Anonymous TLS connection established from unknown[***.***.***.***]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Sep  3 23:12:41 srv2 postfix/submission/smtpd[378511]: warning: problem talking to server 127.0.0.1:9999: Success
Sep  3 23:12:41 srv2 postfix/submission/smtpd[378511]: NOQUEUE: reject: RCPT from unknown[***.***.***.***]: 451 4.3.5 <****@****.com>: Recipient address rejected: Server configuration
 problem; from=<****@****.com> to=<****@****.com> proto=ESMTP helo=<[***.***.***.***]>
Sep  3 23:12:42 srv2 postfix/submission/smtpd[378511]: disconnect from unknown[***.***.***.***] ehlo=2 starttls=1 auth=1 mail=1 rcpt=0/1 quit=1 commands=6/7
```

Logs now that it works, from `/var/log/mail.log`:
```
Sep  5 21:21:29 srv2 postfix/submission/smtpd[336956]: connect from ***********.com[***.***.***.***]
Sep  5 21:21:29 srv2 postfix/submission/smtpd[336956]: Anonymous TLS connection established from ***********.com[***.***.***.***]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange ECDHE (P-256) server-signature RSA-PSS (2048 bits) server-digest SHA256
Sep  5 21:21:29 srv2 postfix/submission/smtpd[336956]: NOQUEUE: client=***********.com[***.***.***.***], sasl_method=PLAIN, sasl_username=****@****.com
Sep  5 21:21:33 srv2 dovecot: imap-login: Login: user=<****@****.com>, method=PLAIN, rip=***.***.***.***, lip=***.***.***.***, mpid=336975, TLS, session=<tv/iHUbLthlhT99u>
Sep  5 21:21:33 srv2 dovecot: imap-login: Login: user=<****@****.com>, method=PLAIN, rip=***.***.***.***, lip=***.***.***.***, mpid=336990, TLS, session=<7lDlHUbL2CthT99u>
Sep  5 21:21:34 srv2 postfix/smtpd[337008]: connect from localhost[127.0.0.1]
Sep  5 21:21:34 srv2 postfix/smtpd[337008]: 4C202123C7A: client=localhost[127.0.0.1], orig_client=***********.com[***.***.***.***]
Sep  5 21:21:34 srv2 postfix/cleanup[337009]: 4C202123C7A: message-id=<******@****.com.com>
Sep  5 21:21:34 srv2 opendkim[1339]: 4C202123C7A: DKIM-Signature field added (s=dkim, d=****.com)
Sep  5 21:21:34 srv2 postfix/qmgr[175893]: 4C202123C7A: from=<****@****.com>, size=5022, nrcpt=1 (queue active)
Sep  5 21:21:34 srv2 postfix/smtpd[337008]: disconnect from localhost[127.0.0.1] ehlo=1 xforward=1 mail=1 rcpt=1 data=1 quit=1 commands=6
Sep  5 21:21:34 srv2 amavis[2519]: (02519-04) Passed CLEAN {RelayedOutbound}, ORIGINATING LOCAL [***.***.***.***]:41297 [***.***.***.***] <****@****.com> -> <****@****.com>, Message-ID: <******@****.com.com>, mail_id: P1FYJMUQuepf, Hits: -0.999, size: 4492, queued_as: 4C202123C7A, 4697 ms
Sep  5 21:21:34 srv2 postfix/submission/smtpd[336956]: proxy-accept: END-OF-MESSAGE: 250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 4C202123C7A; from=<****@****.com> to=<****@******.com> proto=ESMTP helo=<[***.***.***.***]> sasl_username=<****@****.com>
Sep  5 21:21:34 srv2 postfix/submission/smtpd[336956]: disconnect from ***********.com[***.***.***.***] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
Sep  5 21:21:34 srv2 dovecot: imap(****@****.com)<336975><tv/iHUbLthlhT99u>: Logged out in=4242 out=707 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Sep  5 21:21:34 srv2 dovecot: imap-login: Login: user=<****@****.com>, method=PLAIN, rip=***.***.***.***, lip=***.***.***.***, mpid=337014, TLS, session=<4qX7HUbLmGFhT99u>
Sep  5 21:21:35 srv2 postfix/smtp[337011]: Trusted TLS connection established to ****.com[***.***.***.***]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
Sep  5 21:21:38 srv2 postfix/smtp[337011]: 4C202123C7A: to=<****@******.com>, relay=****.com[***.***.***.***]:25, delay=4.6, delays=0.07/0.01/1.7/2.9, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 4H2kxH12Wvz9vNPS)
Sep  5 21:21:38 srv2 postfix/qmgr[175893]: 4C202123C7A: removed
```

**Comment by pcd1000** [comment]
Many thanks for your time and effort Jett, that resolved the issue for me!

**Comment by Perlover** [comment]
> This should be fixed asap on the installer!

Today (2021-12-10) I used the [installator (from Github)](https://github.com/modoboa/modoboa-installer) (default type **not** `--beta`) and I had same problems till I read this and applied the fixes from @JettBurns14 

So @florealcab please if you are developer of installation please check up this again (is there fix or not)

Thanks to @JettBurns14 !

**Comment by Perlover** [comment]
I created issue here too:

https://gitlab.com/amavis/amavis/-/issues/81

**Comment by jarforce** [comment]
For those who still got error with V2 :  Failed to connect to 127.0.0.1 port 9999: Connection refused


1. check /etc/supervisor/conf.d/policyd.conf force to use IPv4 by add: --host 127.0.0.1
2.  check https://github.com/modoboa/modoboa/issues/2200#issuecomment-913231983
3. if still failed, run: > "/srv/modoboa/env/bin/python3 /srv/modoboa/instance/manage.py policy_daemon --host 127.0.0.1" to check what's module is missing and install it
4.  > /srv/modoboa/env/bin/python3 /srv/modoboa/env/bin/pip install asgiref
