### ISSUE TITLE
SASL Login not working

### ISSUE THREAD

**Issue by danielsatanik** [modoboa/modoboa#2201]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 18.04.5 LTS
* Database Type: PostgreSQL
* Database version: 9.6
* Modoboa: 1.17.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

I don't know

# Current behavior

One of my users mentioned that they cannot send mails anymore. I confirmed that. When I look into /var/log/mail.log I can see the following errors:

Mar 20 23:41:39 satanik dovecot: postlogin: Error: Password:
Mar 20 23:41:39 satanik dovecot: postlogin: Error: psql: fe_sendauth: no password supplied

I first assumed the issue may be with the file specifying the SQL-statements, but rebuilding them with the manage.py command hasn't worked. Afterwards I tried (for the heck of it) to upgrade modoboa. The previous version was 1.14.0 and I upgraded straight to 1.17.0. I followed alle the upgrade guides and and had to upgrade python from 2 to 3.

The problem persisted and additionally uwsgi fails me now. Which means nginx cannot properly connect to the socket.

Regardless, I afterwards tried to follow the "Reinstall" instructions but that hasn't paid off either.

Weird as it is, I haven't changed anything on my system for a very long time. Periodically a bunch of cronjobs are running, but I don't think they actually did anything that could influence modoboa.

I actually don't even know anymore how to debug the issue. Google wasn't helpful at. all, maybe I was searching with the wrong terms.

# Expected behavior

sending mails and login on the django website should work

# Video/Screenshot link (optional)

**Comment by danielsatanik** [comment]
BTW I wouldn't mind reinstalling everything as long as I don't loose the mails and the users and stuff

**Comment by tonioo** [comment]
@danielsatanik The error message you're showing is related to a postlogin script used by Modoboa. It's related to IMAP/POP connections so it has nothing to do with emails sending since it's using SMTP...
To be sure it's not the cause of your problems, you can comment out the use of this script in the /etc/dovecot/conf.d/10-master.conf file and reload dovecot.

**Comment by danielsatanik** [comment]
Hi, you are right. I saw that the emails are sent. The postlogin script registers the last login time in the database and is from the official installation. But for some reason it does not work anymore. As a workaround I disabled it. But I tried the sql command manually and it worked. So I don't know exactly what fails here.
Unfortunately some of the cron.d/mdoboa commands also fail, which are 

- $PYTHON $INSTANCE/manage.py qcleanup
- $PYTHON $INSTANCE/manage.py update_statistics
- $PYTHON $INSTANCE/manage.py modo check_mx
- $PYTHON $INSTANCE/manage.py communicate_with_public_api

I disabled them as well, because I received many failure mails.

I did upgrade from Modoboa 14 to 17 and Python 2 to 3 and followed all the upgrade instructions, but maybe there were some specifics that did not work as intended.

It also lead to the webinterface not being loaded anymore, I think it may have something to do with uwsgi and the change from Python 2 to 3.

**Comment by tonioo** [comment]
Do you have errors to show?

**Comment by danielsatanik** [comment]
@tonioo I'll run them manually

```shell
$ python manage.py qcleanup
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/__init__.p
y", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/__init__.p
y", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/base.py", 
line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/base.py", 
line 364, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa_amavis/management/command
s/qcleanup.py", line 59, in handle
    Msgs.objects.filter(time_num__lt=limit).delete()
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/db/models/query.py", line 
711, in delete
    deleted, _rows_count = collector.delete()
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/db/models/deletion.py", li
ne 266, in delete
    self.data[model] = sorted(instances, key=attrgetter("pk"))
TypeError: '<' not supported between instances of 'memoryview' and 'memoryview'
```

```shell
$ python manage.py update_statistics
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/maillog/management/commands/update_statistics.py", line 84, in handle
    self.update_account_creation_stats(options["rebuild"])
  File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/maillog/management/commands/update_statistics.py", line 77, in update_account_creation_stats
    db_path, int((start - relativedelta(hours=1)).strftime("%s"))
  File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/maillog/management/commands/update_statistics.py", line 39, in _create_new_accounts_rrd_file
    *params
rrdtool.OperationalError: Cannot create temporary file
```

The other two seemed to work when I ran them manually. For the postlogin script it says

```shell
$ journalctl -xfu dovecot
Dec 29 17:22:11 dovecot[1314]: postlogin: Error: Password:
Dec 29 17:22:11 dovecot[1314]: postlogin: Error: psql: fe_sendauth: no password supplied
```


and for the uwsgi:

```shell
$ tail /var/log/nginx/error.log
2021/03/23 12:14:06 [error] 17581#17581: *3282 connect() to unix:/run/uwsgi/app/modoboa_instance/socket failed (111: Connection refused) while connecting to upstream, client: <IP>, server: <domain.tld>, request: "GET /favicon.ico HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "<domain.tld>", referrer: "https://<domain.tld>/"
```

**Comment by tonioo** [comment]
The qcleanup one is known, there is an opened issue for this and it's actually an issue with psycopg2 (the postgres python connector).
The update_statistics one is strange, have you checked permissions of the folder used to store rrd files?
The postlogin error means there is a configuration in postgresql preventing to execute SQL queries without authentication. which is what the script does...
The error you see in nginx logs means the uwsgi instance is not running.

**Comment by danielsatanik** [comment]
Hi,

I have checked the rrd directory, and even tried to give it unrestricted permissions with `chmod 0777` but that didn't help. I found the settings inside the database somewhere in core_localconfig or smth.

what settings for the postlogin may restrict the access? The psql instance was set up with modoboa and I haven't done any updates lately so there shouldn't have changed anything, but of course there must have. So is it an issue with the hba-file? Would you have the preferred settings available?

as for the uwsgi. The systemd service itself is running so what do you mean is not running? the emperor instance or smth? I'm not very familiar with uwsgi to debug the issue, without extensive research, could you give me a few pointers? As I said it may have to do with changing from Python 2 to 3. What I did was deleting the old venv and just creating a new one with Python3 inside, and then reinstalling all the pip packages needed for modoboa to work. But that certainly had no effects on the uwsgi settings. Do I need to change the emperor-app settings file?

**Comment by tonioo** [comment]
What's the content of you pg_hba.conf file?

About uwsgi, make sure you installed the python3 plugin and that you've updated the modoboa configuration file accordingly. (/etc/uwsgi/)

**Comment by danielsatanik** [comment]
I haven't change a single line in the pg_hba.conf since installing modoboa but this is the content:

```conf
local   all             postgres                                md5

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     md5
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     postgres                                peer
#host    replication     postgres        127.0.0.1/32            md5
#host    replication     postgres        ::1/128                 md5
```

for uwsgi, I could build the python36 plugin, thank you for the tip. I also replaced the plugin in the config accordingly. It still yields 500 Server Error and the resulting log message is the following:

```
Traceback (most recent call last):
  File "./instance/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/srv/modoboa/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/admin/models/__init__.py", line 4, in <module>
    from .alias import Alias, AliasRecipient
  File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/admin/models/alias.py", line 16, in <module>
    from modoboa.lib.email_utils import split_mailbox
  File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/lib/email_utils.py", line 10, in <module>
    import lxml.html
  File "/srv/modoboa/env/lib/python3.6/site-packages/lxml/html/__init__.py", line 53, in <module>
    from .. import etree
ImportError: Interpreter change detected - this module can only be loaded into one interpreter per process.
Wed Mar 24 10:41:46 2021 - unable to load app 1 (mountpoint='<domain.tld>|') (callable not found or import error)
Wed Mar 24 10:41:46 2021 - --- no python application found, check your startup logs for errors ---
<domain.tld> [pid: 11551|app: -1|req: -1/1] 88.117.68.216 () {44 vars in 815 bytes} [Wed Mar 24 10:41:45 2021] GET / => generated 21 bytes in 1195 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
```

When I googled it, some said that could happen when there are multiple instances so I tried setting processes in the config to 1, but that hasn't helped much. Was I missing a step, except for restarting the uwsgi.service?

**Comment by tonioo** [comment]
For uwsgi, add the following to your configuration file:
```
single-interpreter = true
```
And according to the postgres config, I think it should work...

**Comment by danielsatanik** [comment]
@tonioo the single-interpreter option worked thank you.

For the pg_hba.conf. What would be the relevant line.

PS: I would like to suggest putting the tips you gave into the upgrade instructions somewhere. Especially those about what to watch out for when changing from version 1.14.0 to 1.15.0 which enforces using Python3 then.
