### ISSUE TITLE
SSL WRONG_VERSION_NUMBER webmail error

### ISSUE THREAD

**Issue by nickshanks347** [modoboa/modoboa#2213]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 20.04 Server x64
* Database Type: MySQL
* Database version: Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
* Modoboa: 1.17.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

I'm not sure how to reproduce this, but evidently it is a bug.

# Current behavior

When clicking on "Webmail" from the main Modoboa interface, it comes up with `Error: Connection to IMAP server failed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)`.
This is not expected behaviour, it should bring up the Webmail interface. My email client still works, but Webmail doesn't.

# Expected behavior

Webmail should open and this error should not appear.

# Video/Screenshot link (optional)

https://gyazo.com/c48672e07970a51fcad2531f3309d216

**Comment by nickshanks347** [comment]
Does anyone have any ideas?

**Comment by tonioo** [comment]
@nickshanks347 Can you give more information about webmail configuration please?

**Comment by nickshanks347** [comment]
> @nickshanks347 Can you give more information about webmail configuration please?

What would you like to know about the configuration? Like ports for IMAP? Is there a report I can extract for you which'll show you everything you need?

**Comment by tonioo** [comment]
A screenshot of the online configuration page will be fine.

**Comment by nickshanks347** [comment]
> A screenshot of the online configuration page will be fine.

Sorry to be annoying but could you please specify which configuration page? There are 10 different tabs on Modoboa settings, unless you want a screenshot of every single one?

**Comment by tygerxqt** [comment]
I'm also having this error. It seems to be something wrong with the IMAP SSL. If you have "Use a secure connection" enabled in the "Webmail" section of the config, it displays that error. If you disable it, there isn't an error.
