### ISSUE TITLE
Can't send/receive E-Mails internally/externally at all

### ISSUE THREAD

**Issue by itzMiney** [modoboa/modoboa#2229]
# Impacted versions

* OS Type: Debian
* OS Version: 10
* Modoboa: 1.17.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

install dependencies, open ports
freshly install Modoboa with the installer
reboot server
go to mail.example.com
add a domain
make all the dns records
wait for checks (all checks green for me)
make simple user
Compose & Send test E-mail with simple user
# Current behavior
nothing, only clears out "From" and "To" fields (not Subject)

# Expected behavior

green message saying "Message sent!" and redirect to Inbox just like in the online demo

# Video/Screenshot link (optional)

[Edited]
Online Demo after clicking "Send"
![image](https://www.minecrew.net/media/sharefiles/live-demo.png)

My own Webmail after clicking "Send"
![image](https://www.minecrew.net/media/sharefiles/untitled.png)

Browser Console after clicking "Send"
![image](https://user-images.githubusercontent.com/51490217/115975123-55cfec80-a562-11eb-93f9-ee72ebbb585a.png)

**Comment by ItzMineyy** [comment]
Update: Browser Console after clicking "Send"
![image](https://user-images.githubusercontent.com/51490217/115975123-55cfec80-a562-11eb-93f9-ee72ebbb585a.png)

**Comment by kiloDE** [comment]
Hey, 

I'm not of the dev team here, but it looks a bit like you have a bug in your nginx config. Why? you got a 404... not found!
And it's a POST Request to /webmail/?action=compose
I experienced the same when I forget the API Url rewrites in the sites-enabled cfg of your vhost.

Try to setup a mailbox + email acc with Thunderbird and check if stuff gets send out. Then you know it isn't the underlying postfix, only the Webinterface and the Webserver config, since you use nginx. :)

**Comment by antonbowe** [comment]
Hey,

I have the exact same issue with my clean Modoboa installation. I can't even link my mail inbox with Thunderbird and I also cant receive any mails from apart. A few seconds after sending an email to my inbox I get an error on my mobile, that says, that my email has been rejected by the server.

When sending emails, the recipient and the from field clears immediatly and I cant send any emails?
Is there another solution to this issue?

**Comment by tonioo** [comment]
Can one of you enable DEBUG mode in settings.py (reload uwsgi) and check the response content of the request that comes back with a 400 error?

**Comment by ScionOfDesign** [comment]
I can replicate this error when trying to install modoboa into an empty ubuntu container using the installer:
Here is the response:
`{"error": "dest@gmail.com: (451, b'4.3.5 <dest@gmail.com>: Recipient address rejected: Server configuration problem')"`
mail.log has the same error, as expected.

**Comment by ScionOfDesign** [comment]
The issue seems to be in `/etc/postfix/main.cf`
Under `smtpd_recipient_restrictions =` you should remove/comment out `check_policy_service inet:127.0.0.1:9999`, now you should be able to send emails.

**Comment by tonioo** [comment]
@ScionOfDesign It is not a good idea, unless you don't need the policy daemon. Have you checked if it is running on your server?

**Comment by ScionOfDesign** [comment]
> @ScionOfDesign It is not a good idea, unless you don't need the policy daemon. Have you checked if it is running on your server?

It does not seem to be running in an [example container](https://hub.docker.com/r/gzlkhan/modoboa-stable) I was using, as it also had that line removed. I have not verified whether the daemon is installed and just not running or not installed at all.
