### ISSUE TITLE
Failed to retrieve mailbox location [when trying to delete new user/identity & mailbox]

### ISSUE THREAD

**Issue by kiloDE** [modoboa/modoboa#2235]
# Impacted versions

* OS Type: Debian/Ubuntu
* OS Version: x
* Database Type: pSQL
* Database version: x
* Modoboa: latest (German date format: 01.05.2021)
* installer used: Yes
* Webserver: nginx and uwsgi (did work until a few weeks ago)

# Steps to reproduce
after restarting uwsgi problems with API and so on
add Identity + Mailbox in ACP
trying to delete Identity+Mailbox in ACP 

# Current behavior
Can't delete (new) Users any more because it says "Failed to retrieve mailbox location [....]"...  
it needs a sudo terminal (sudo -S "a Terminal is needed to read the password [...] configure a askpass helper [...]" 
Which is already configured

The first error comes from Modoboa Web API, the second one from the underlying System itself. :o (otherwise it wouldn't talk about sudo - since it wants to delete the mailbox directory? )

# Possible workaround
It's possible to **ONLY** delete the user/identity itself, in modoba, by checking "Do not delete mailbox directory"...  but I guess that's not what's intended since it only removes the identity/user from DB.

# Expected behavior
Usually it should just delete the users Mailbox and the Account in the DB

I tried any workarounds I know, I debugged the whole app and so on... nothing works :D 

__

Let me know if I got something wrong, thank you all in advance :)  

Sorry for not enough infos, but I don't have more, since I cant track the bug down to it's origin. I commented somewhere to a User here, if he fixed it. 

Something about the doveadm CMD which got changed in the Python Files (which leads down to this bug and so on)

**Comment by tonioo** [comment]
@kiloDE I think this is related to https://github.com/modoboa/modoboa/issues/2084.
