### ISSUE TITLE
Cannot create identity

### ISSUE THREAD

**Issue by pklav** [modoboa/modoboa#2237]
# Impacted versions

* OS Type: Raspbian GNU/Linux 10 (buster); the Lite release
* OS Version: 10 (buster)
* Database Type: MySQL
* Database version: 15.1
* Modoboa: 1.17.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

1. Do a fresh install using the installer
2. Create a domain without creating a domain administrator.
3. Create a new identity (simple user) for that domain: fill in the user name and password
4. Click [Next] and [Submit]

# Current behavior
After clicking [Submit], nothing happens
Note, when I create a domain _with_ an administrator (step 2 above), the domain is not created.

# Expected behavior
Create a new identity

# Console messages
`17:37:10.588 This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. identities
`
`17:37:10.641 Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead
jquery.js:3429:51
`
`17:41:31.788 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ jquery.min.js:5:17542
`
`17:43:08.661
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    parseJSON jQuery
    post creation_wizard.js:61
    jQuery 5
`
# Tried fixes

- Change the permissions of /srv/modoboa/pdfcredentials, as suggested in the last posts of issue [https://github.com/modoboa/modoboa/issues/1547](url)

**Comment by pklav** [comment]
Default settings, I assume (I did not change anything here...).
The pdfcredentials folder is owned by user modoboa:modoboa with permissions 770.
![Schermafdruk_2021-05-10_13-50-04](https://user-images.githubusercontent.com/83528427/117655023-d31c7380-b196-11eb-8800-3d8c6e7c4c8e.png)

**Comment by tonioo** [comment]
@pklav Sorry for the delay but maybe it could be the same issue than https://github.com/modoboa/modoboa/issues/2286.
