### ISSUE TITLE
MySQL/MariaDB localhost / 127.0.0.1 config change request

### ISSUE THREAD

**Issue by olaf7** [modoboa/modoboa#2259]
Impacted versions: all (?)
OS Type: Debian
OS Version: 10
Database: MariaDB
Manual installation. Over time various upgrades.

https://modoboa.readthedocs.io/en/latest/upgrade.html describes the process to upgrade core and extensions.
It might be that the following is advised/need to run:
`python manage.py generate_postfix_maps --destdir <directory>`
This produces SQL scripts to be used by Postfix. BUT it uses 'localhost' by default as the database-host/server. In a chroot-ed environment such as the default Debian Postfix install this causes problems as now Postfix tries to access MySQL/MariaDB using a socket. The socket file cannot be used. For details also see: https://workaround.org/ispmail/jessie/postfix-mysql
I think a better approach would be to use 127.0.0.1 instead or make this configurable/tweakable.
In the current setup a checksum file is generated and explicitly mentioned is not to edit the SQL script files. I tried to honor this and tried to enforce TCP connections instead of socket by adding transport=TCP to the [client] stanza in the MariaDB config, but this gets ignored. Therefor the only option seemed to edit the SQL files which I did. Drawback is that the checksum file now no longer matches the files.

**Comment by olaf7** [comment]
Things to note:
* https://salsa.debian.org/postfix-team/postfix-dev/-/blob/debian/master/debian/patches/40_chroot_by_default.diff
* https://wiki.debian.org/PostfixAndSASL

Moving/copying either MariaDB/MySQL config into the chroot jail (the reason why my client config using protocol=tcp did not work as it was ignored) or moving the sock file seem nasty solutions to this problem.
The alternative would be to remove the chroot jail of Postfix, which would be a serious adaption of the default configuration of the Debian package, or simply use 127.0.0.1 as a host. Localhost would be a lot cleaner as localhost includes ipv6 support, however it also introduces the socket issue. Personally I think 127.0.0.1 is the cleanest and most upgrade proof solution.

**Comment by tonioo** [comment]
@olaf7 The command which generates those configuration files uses the information available in the settings.py file to connect to the database.
