### ISSUE TITLE
Unable to update domain quota from Web UI or API

### ISSUE THREAD

**Issue by mattg66** [modoboa/modoboa#2263]
1.17.0

OS Type: Debian
OS Version: 10
Database Type: PostgreSQL
installer used: Yes
Webserver: Nginx

Set domain quota upon creation, then attempt to update quota. Quota doesn't update for domain and as a result, no more users can be added to the domain. 
Occurs with both API Patch request and Web UI. When trying to reduce quota from web UI, HTTP 500 is returned

**Comment by H-A-L-I-S** [comment]
Not sure, if it is related, but you can try [this](https://github.com/modoboa/modoboa/issues/2247#issuecomment-857557414) from #2247  :

```
sudo -u modoboa -i
bash
cd /srv/modoboa/
source env/bin/activate
(env)> pip install django-webpack-loader==0.7.0
reboot
```
You can also try [this](https://github.com/modoboa/modoboa/issues/2247#issuecomment-855637118) to get more information:
`You have more information if you enable debug traces: edit /srv/modoboa/instance/instance/settings.py, set DEBUG to True, save and reload uwsgi.
`

**Comment by mas1701** [comment]
Might be related:

I'm experiencing the problem, that I cannot modify Sieve filters once they have been created. I have to delete the rule in question and re-create it. Very annoying. My django-webpack-loader IS 0.7.0.

**Comment by mattg66** [comment]
> Not sure, if it is related, but you can try [this](https://github.com/modoboa/modoboa/issues/2247#issuecomment-857557414) from #2247 :
> 
> ```
> sudo -u modoboa -i
> bash
> cd /srv/modoboa/
> source env/bin/activate
> (env)> pip install django-webpack-loader==0.7.0
> reboot
> ```
> 
> You can also try [this](https://github.com/modoboa/modoboa/issues/2247#issuecomment-855637118) to get more information:
> `You have more information if you enable debug traces: edit /srv/modoboa/instance/instance/settings.py, set DEBUG to True, save and reload uwsgi. `

Thanks for the suggestion, however I am alreadying using django-webpack-loader 0.7.0 apparently:
```Requirement already satisfied: django-webpack-loader==0.7.0 in ./env/lib/python3.7/site-packages (0.7.0)```

**Comment by tonioo** [comment]
@mattg66 Which quota are you talking about?

**Comment by mattg66** [comment]
Domain quota, this is still an issue.

**Comment by mattg66** [comment]
The workaround is to edit the 'quota' column for the domain
