### ISSUE TITLE
Webmail not sending emails despite credentials ok

### ISSUE THREAD

**Issue by Sequential-circuits** [modoboa/modoboa#2265]
We use sendgrid to send emails and we followed the instructions at https://sendgrid.com/docs/for-developers/sending-email/postfix/ for integrating it with modoboa

Still, we cannot send emails from the webmail system as it always says: Diagnostic-Code: smtp; 535 Authentication failed: The provided authorization grant is invalid, expired, or revoked

This started to happen suddenly, and the support at Sendgrid says it's not on their side. In fact, sending emails from other sources using the same username, password, etc works

**Comment by H-A-L-I-S** [comment]
I just checked the [instructions](https://sendgrid.com/docs/for-developers/sending-email/postfix/) that you posted. These are quite a lot of changes and it is more or less expected that something will break:

```
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_sasl_security_options = noanonymous
smtp_sasl_tls_security_options = noanonymous
smtp_tls_security_level = encrypt
header_size_limit = 4096000
relayhost = [smtp.sendgrid.net]:587
```

I do not think this is a problem with modoboa. Maybe you can check the modoboa documentation on how to deal with this. (The manual installation part of the documentation)
