### ISSUE TITLE
DNS status is not updated on IPv4-IPv6 infra

### ISSUE THREAD

**Issue by MarioC-IRL** [modoboa/modoboa#2272]
* OS Type: Ubuntu
* OS Version: Bionic
* Modoboa: 1.17
* installer used: Yes
* Webserver: Nginx

I proceeded to a new installation, everything went well without any error, unfortunately after configuring everything I notice that the check_mx modo does not react, I run it manually and I have no error except that there is a problem, it does not update the DNS Status pending, I find myself without any way to use the service.

The problem is not visible when all the configuration is on IPv4 but in my case I have IPv6, all the redirects are well done in A, AAAA, MX etc.... I'm not sure if this is a problem, but I'd like to know how to solve it. I'm a pain in the ass, but IPv6 is the future, so I don't want to be slowed down by a problem like this.

# Video/Screenshot
![image](https://user-images.githubusercontent.com/55061299/122298414-058b6000-cefd-11eb-865f-7fac341a0a7f.png)

**Comment by tonioo** [comment]
@MarioC-IRL Just to be sure, have you checked if the server where Modoboa is installed is able to resolve your DNS records? Have you tried to run the command manually?

**Comment by MarioC-IRL** [comment]
> @MarioC-IRL Just to be sure, have you checked if the server where Modoboa is installed is able to resolve your DNS records? Have you tried to run the command manually?

I have checked all the DNS, run the command manually and unfortunately nothing goes and I get no error.

**Comment by tonioo** [comment]
Can you also check settings in Modoboa > Parameters > Administration ?

**Comment by MarioC-IRL** [comment]
> Can you also check settings in Modoboa > Parameters > Administration ?

I checked, I didn't see anything wrong

**Comment by MarioC-IRL** [comment]
After 24 hours, errors appear and these are 
![image](https://user-images.githubusercontent.com/55061299/122423868-8ba3b700-cf8e-11eb-9e3c-292fb2272c7d.png)

However everything is correct, the IPv6 is well assigned to the machine, responds well to ping in INPUT/OUTPUT and has its own rDNS, on the v4 side the same thing, why does this error appear now.

> Can you also check settings in Modoboa > Parameters > Administration ?

**Comment by tonioo** [comment]
You must enter ip addresses in the valid MX field, not hostnames.
