### ISSUE TITLE
DKIM test: key syntax error: illegal base64 data at input byte 212

### ISSUE THREAD

**Issue by slowaways** [modoboa/modoboa#2275]
Testing the DKIM key of my Modoboa mail server in [GlockApps](https://glockapps.com/) I found a critical error:
key syntax error: illegal base64 data at input byte 212
I tested using 1024 and 2048 key length.

# Impacted versions

* OS Type: Debian
* OS Version: Debian 10 x64 (buster) 
* Database Type: MySQL
* Database version: ?
* Modoboa: 1.17.0
* Installer used: Yes
* Webserver: Nginx

# Steps to reproduce
1. Create account at [GlockApps App](https://app.glockapps.com/)
2. Go to Diagnostics -> DKIM Validator
3. Enter your domain + DKIM selector

# Current behavior
key syntax error: illegal base64 data at input byte 212

# Expected behavior
The key should be recognized as a base64 key.

# Video/Screenshot link (optional)
![image](https://user-images.githubusercontent.com/9668277/122650327-a863fa00-d108-11eb-9490-d8ace60212d7.png)

**Comment by H-A-L-I-S** [comment]
I think, this is a bug with that website, not with modoboa. You need to report to them, not here

**Comment by slowaways** [comment]
> 
> 
> I think, this is a bug with that website, not with modoboa. You need to report to them, not here

Okay
