### ISSUE TITLE
No action saved

### ISSUE THREAD

**Issue by MarioC-IRL** [modoboa/modoboa#2281]
# Impacted versions

* OS Type: Ubuntu
* OS Version: Bionic
* Database Type: MySQL
* Database version: X.y
* Modoboa: latest
* installer used: Yes
* Webserver: Nginx

Hey I wanted to enable the CardDAV solution on the modoboa panel, but there seems to be a strange problem on the panel. When I make any modification in the /user/#preferences/ nothing manages to be saved but in case I click on saved without having modified it works. I can't find any error in the logs, that's why I came here.

The CardDAV activation bug is visible on all users. I only have problems with this option.

![image](https://user-images.githubusercontent.com/55061299/123353716-6bfa2900-d562-11eb-93c2-b8df0b068fc0.png)

**Comment by tonioo** [comment]
@MarioC-IRL Have you checked all tabs to see if there might be a validation issue?

**Comment by MarioC-IRL** [comment]
> @MarioC-IRL Have you checked all tabs to see if there might be a validation issue?

Yes, I checked all the tabs and only the CardDAV side is affected

**Comment by tonioo** [comment]
@MarioC-IRL Is there any message when you click on save? (a green popup at the top)

Do you see anything in your browser console?
