### ISSUE TITLE
Sorry an internal error occured

### ISSUE THREAD

**Issue by jamielsharief** [modoboa/modoboa#2286]
Ubuntu 20.04

I have just installed the software, and when trying to login for the first time, i get this screen after submitting the username and password.

![image](https://user-images.githubusercontent.com/20553479/123431843-0477c400-d5ca-11eb-996e-98b6ecb3d0ab.png)

**Comment by zQueal** [comment]
Result of a 500 error. Unsure why. Can't seem to get this to work.

**Comment by tonioo** [comment]
Can one of you enable debug traces and try again please? (set DEBUG to True inside settings.py and reload uwsgi)

**Comment by jamielsharief** [comment]
I am guessing the problem is related to this fix #2285 , I am going to try again now. Is the detail of the 500 error logged somewhere?

**Comment by jamielsharief** [comment]
Same problem again, i think some package that it needs is not available since i am installing it inside a lxd container. You should put here instructions how people can debug and restart uwsgi whatever that is.

**Comment by drlight17** [comment]
> Same problem again, i think some package that it needs is not available since i am installing it inside a lxd container. You should put here instructions how people can debug and restart uwsgi whatever that is.

Hi. Just installed modoboa for the first time and faced this error. Temporary fixed this with setting USE_TZ to False in /srv/modoboa/instance/instance/settings.py file and /etc/init.d/uwsgi restart.

**Comment by jamielsharief** [comment]
I just reinstalled and tested and it worked with your fix.

```
 timedatectl | grep "Time zone"
                Time zone: Etc/UTC (UTC, +0000)   
 ```

**Comment by tonioo** [comment]
@drlight17 Could you provide a trace with DEBUG setting set to True?

**Comment by jamielsharief** [comment]
![image](https://user-images.githubusercontent.com/20553479/123660164-b49c3580-d833-11eb-8a87-31607f6dad41.png)

**Comment by tonioo** [comment]
Ok, this is an issue with the postgresql library. I've pushed a fix recently but it has not been released yet (https://github.com/modoboa/modoboa/commit/3835c3e9531247dc1b947ab626e28087b5739b92).
Just ensure the installed psycopg2 library is <2.9.0

**Comment by drlight17** [comment]
> @drlight17 Could you provide a trace with DEBUG setting set to True?

My debug trace is the same as @jamielsharief. I've faced another set of troubles (with jquery and some others) so I decided to use something more heavy like mailcow.

**Comment by solick** [comment]
I can confirm that setting USE_TZ to False works for me too.

**Comment by JettBurns14** [comment]
> Just installed modoboa for the first time and faced this error. Temporary fixed this with setting USE_TZ to False in /srv/modoboa/instance/instance/settings.py file and /etc/init.d/uwsgi restart.

@drlight17 Your fix worked for me as well, thank you! I had just done a fresh install on Ubuntu 20.04.2 with the auto-installer and was disappointed to see it didn't work out of the box. Glad I can use Modoboa now!

**Comment by angeloluidens** [comment]
Hi, after making a snapshot of my Modoboa server, on Debian 10 (buster), I tried to upgrade it from version 1.17.1 to 2.0.1. I too encountered the same issue: Sorry Internal Server Error.
The workaround: USE_TZ = False and restart the UWSGI did not work.

**Comment by angeloluidens** [comment]
> 

Tried the "USE_TZ" fix a second time. It worked!

**Comment by coderexpress** [comment]
Hope this helps anyone else who ran into this issue, the issue is from the script files not being updated.
1) backup up the modoboa-installer folder.
2) delete all the files in the original modoboa-installer and replace them with the latest from https://github.com/modoboa/modoboa-installer
3) My installation was from before fail2ban was installed, I installed fail2ban manually 9 month ago when I first setup the server, so I edit it the fail2ban out from the run.py:

PRIMARY_APPS = [
    "amavis",
    "fail2ban",
    "modoboa",
    "automx",
    "radicale",
    "uwsgi",
    "nginx",
    "opendkim",
    "postfix",
    "dovecot"
]

to this


PRIMARY_APPS = [
    "amavis",
    "modoboa",
    "automx",
    "radicale",
    "uwsgi",
    "nginx",
    "opendkim",
    "postfix",
    "dovecot"
]
4) I restored the file installer.cfg from the backup directory and then ran:
sudo ./run.py --upgrade <your domain>

worked like a charm!!
hope this help other frustrated users as I have been trying to update for a while.

Thank you for the developer!!!! I love Modoboa!!!

**Comment by mtlqc** [comment]
> Hope this helps anyone else who ran into this issue, the issue is from the script files not being updated.
> 
> 1. backup up the modoboa-installer folder.
> 2. delete all the files in the original modoboa-installer and replace them with the latest from https://github.com/modoboa/modoboa-installer
> 3. My installation was from before fail2ban was installed, I installed fail2ban manually 9 month ago when I first setup the server, so I edit it the fail2ban out from the run.py:
> 
> PRIMARY_APPS = [ "amavis", "fail2ban", "modoboa", "automx", "radicale", "uwsgi", "nginx", "opendkim", "postfix", "dovecot" ]
> 
> to this
> 
> PRIMARY_APPS = [ "amavis", "modoboa", "automx", "radicale", "uwsgi", "nginx", "opendkim", "postfix", "dovecot" ] 4) I restored the file installer.cfg from the backup directory and then ran: sudo ./run.py --upgrade
> 
> worked like a charm!! hope this help other frustrated users as I have been trying to update for a while.
> 
> Thank you for the developer!!!! I love Modoboa!!!

Yep!  Worked for me.
Thanks for sharing!

**Comment by Spitfireap** [comment]
Just so you know, the installer has been updated and now includes a configuration update tool. No need for the workaround now, simply `git fetch && git pull` within modoboa-installer then `python run.py ....` ;)

And to disable fail2ban, simply open installer.cfg and set `enabled =` to `false`
