### ISSUE TITLE
500 Internal server error o create user, add domain,..

### ISSUE THREAD

**Issue by optimdevel** [modoboa/modoboa#2304]
LXC Debian GNU/Linux 10 (buster) upgraded from 8, MySql db upgraded using manage migrate from 1.5.3 to 1.17.0 + plugins,  .. using instructions from https://modoboa.readthedocs.io/en/latest/upgrade.html .

After trying to add a new domain or change users password, we get 500 Internal server error.
I have enabled debug = true in settings.py in instance dir and restarted uwsgi. I checked all the log files I can think off, but have no idea where to look to get more detailed error, so I can solve it.

How to get more infor about ther internal error?
![modoboa500](https://user-images.githubusercontent.com/37371940/123953986-25fcf500-d9a8-11eb-9343-a31ac0e0b892.png)

**Comment by tonioo** [comment]
@optimdevel Set DEBUG to True inside settings.py and reload uwsgi.

**Comment by optimdevel** [comment]
I have done that already, however I was not aware there is more info on other tabs in the debug console.
Just fund the error:

(1364, "Field 'manager_slug' doesn't have a default value")

I guess migrations did not completely "upgrade" the database.
Will see how can I fix this.

**Comment by optimdevel** [comment]
Can you please show me your scheba for reversion_revision?
`MariaDB [modoboa]> describe reversion_revision
    -> ;
+--------------+--------------+------+-----+---------+----------------+
| Field        | Type         | Null | Key | Default | Extra          |
+--------------+--------------+------+-----+---------+----------------+
| id           | int(11)      | NO   | PRI | NULL    | auto_increment |
| manager_slug | varchar(191) | NO   | MUL | NULL    |                |
| date_created | datetime     | NO   | MUL | NULL    |                |
| comment      | longtext     | NO   |     | NULL    |                |
| user_id      | int(11)      | YES  | MUL | NULL    |                |
+--------------+--------------+------+-----+---------+----------------+
`

**Comment by tonioo** [comment]
@optimdevel It comes from an external package (django-reversion). Can you check the version installed in your virtualenv and also run the following command:
```
python manage.py showmigrations
```

**Comment by optimdevel** [comment]
Sure.
`env) modoboa@mail3:~/instance$ python manage.py showmigrations
admin
 [X] 0001_initial
 [X] 0002_migrate_from_modoboa_admin
 [X] 0003_auto_20151118_1215
 [X] 0004_auto_20160914_0907
 [X] 0005_auto_20161026_1003
 [X] 0006_auto_20161104_1900
 [X] 0007_auto_20161104_1915
 [X] 0008_domain_enable_dns_checks
 [X] 0009_auto_20170215_0948
 [X] 0010_auto_20170215_1328
 [X] 0011_domain_transport
 [X] 0012_auto_20180112_1658
 [X] 0013_auto_20180124_2311
 [X] 0014_auto_20181017_1628
 [X] 0015_rename_view_permissions
 [X] 0016_auto_20200602_1201
 [X] 0017_alarm
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
 [X] 0010_alter_group_name_max_length
 [X] 0011_update_proxy_permissions
authtoken
 [X] 0001_initial
 [X] 0002_auto_20160226_1747
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
core
 [X] 0001_initial
 [X] 0002_delete_extension
 [X] 0003_user_master_user
 [X] 0004_auto_20150728_1228
 [X] 0005_user_language
 [X] 0006_auto_20151114_1518
 [X] 0007_auto_20151116_1349
 [X] 0008_localconfig
 [X] 0009_auto_20161026_1003
 [X] 0010_auto_20161026_1011
 [X] 0011_auto_20161104_2217
 [X] 0012_auto_20170215_1034
 [X] 0013_auto_20170707_1058
 [X] 0014_auto_20171010_1746
 [X] 0015_auto_20180112_1642
 [X] 0016_auto_20180713_1014
 [X] 0017_auto_20190705_1045
 [X] 0018_auto_20200104_1714
 [X] 0019_auto_20200121_1659
 [X] 0020_auto_20200421_0851
 [X] 0021_localconfig_need_dovecot_update
 [X] 0022_user_tfa_enabled
dnstools
 [X] 0001_initial
lib
 [X] 0001_initial
 [X] 0002_rename_parameters
 [X] 0003_rename_parameters
 [X] 0004_auto_20151114_1409
 [X] 0005_auto_20160416_1449
 [X] 0006_auto_20161104_2206
limits
 [X] 0001_squashed_0004_auto_20160413_1312 (4 squashed migrations)
 [X] 0005_auto_20160415_1654
 [X] 0006_auto_20170216_1112
maillog
 [X] 0001_initial
 [X] 0002_auto_20200916_1346
modoboa_amavis
 [X] 0001_initial
modoboa_contacts
 [X] 0001_initial
 [X] 0002_auto_20180124_2311
 [X] 0003_auto_20181005_1415
 [X] 0004_auto_20181005_1415
 [X] 0005_auto_20181005_1445
modoboa_postfix_autoreply
 [X] 0001_initial
 [X] 0002_auto_20150728_1236
 [X] 0003_move_aliases
 [X] 0004_delete_alias
 [X] 0005_auto_20151202_1623
 [X] 0006_auto_20160329_1501
 [X] 0007_auto_20180928_1423
 [X] 0008_delete_transport
modoboa_radicale
 [X] 0001_initial
 [X] 0002_auto_20170831_1721
 [X] 0003_auto_20180324_1834
 [X] 0004_auto_20200220_1816
 [X] 0005_auto_20200220_1819
otp_static
 [X] 0001_initial
 [X] 0002_throttling
otp_totp
 [X] 0001_initial
 [X] 0002_auto_20190420_0723
relaydomains
 [X] 0001_initial
 [X] 0002_migrate_from_modoboa_admin_relaydomains
 [X] 0003_auto_20170116_1508
 [X] 0004_auto_20161105_1424
 [X] 0005_auto_20161105_1426
 [X] 0006_auto_20170215_0948
 [X] 0007_recipientaccess
 [X] 0008_auto_20171123_1653
 [X] 0009_auto_20171124_1508
reversion
 [X] 0001_squashed_0004_auto_20160611_1202
sessions
 [X] 0001_initial
sites
 [X] 0001_initial
 [X] 0002_alter_domain_unique
transport
 [X] 0001_initial
 [X] 0002_auto_20180928_1520
(env) modoboa@mail3:~/instance$ 
`

**Comment by optimdevel** [comment]
Better formatting:

admin
 [X] 0001_initial
 [X] 0002_migrate_from_modoboa_admin
 [X] 0003_auto_20151118_1215
 [X] 0004_auto_20160914_0907
 [X] 0005_auto_20161026_1003
 [X] 0006_auto_20161104_1900
 [X] 0007_auto_20161104_1915
 [X] 0008_domain_enable_dns_checks
 [X] 0009_auto_20170215_0948
 [X] 0010_auto_20170215_1328
 [X] 0011_domain_transport
 [X] 0012_auto_20180112_1658
 [X] 0013_auto_20180124_2311
 [X] 0014_auto_20181017_1628
 [X] 0015_rename_view_permissions
 [X] 0016_auto_20200602_1201
 [X] 0017_alarm
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
 [X] 0010_alter_group_name_max_length
 [X] 0011_update_proxy_permissions
authtoken
 [X] 0001_initial
 [X] 0002_auto_20160226_1747
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
core
 [X] 0001_initial
 [X] 0002_delete_extension
 [X] 0003_user_master_user
 [X] 0004_auto_20150728_1228
 [X] 0005_user_language
 [X] 0006_auto_20151114_1518
 [X] 0007_auto_20151116_1349
 [X] 0008_localconfig
 [X] 0009_auto_20161026_1003
 [X] 0010_auto_20161026_1011
 [X] 0011_auto_20161104_2217
 [X] 0012_auto_20170215_1034
 [X] 0013_auto_20170707_1058
 [X] 0014_auto_20171010_1746
 [X] 0015_auto_20180112_1642
 [X] 0016_auto_20180713_1014
 [X] 0017_auto_20190705_1045
 [X] 0018_auto_20200104_1714
 [X] 0019_auto_20200121_1659
 [X] 0020_auto_20200421_0851
 [X] 0021_localconfig_need_dovecot_update
 [X] 0022_user_tfa_enabled
dnstools
 [X] 0001_initial
lib
 [X] 0001_initial
 [X] 0002_rename_parameters
 [X] 0003_rename_parameters
 [X] 0004_auto_20151114_1409
 [X] 0005_auto_20160416_1449
 [X] 0006_auto_20161104_2206
limits
 [X] 0001_squashed_0004_auto_20160413_1312 (4 squashed migrations)
 [X] 0005_auto_20160415_1654
 [X] 0006_auto_20170216_1112
maillog
 [X] 0001_initial
 [X] 0002_auto_20200916_1346
modoboa_amavis
 [X] 0001_initial
modoboa_contacts
 [X] 0001_initial
 [X] 0002_auto_20180124_2311
 [X] 0003_auto_20181005_1415
 [X] 0004_auto_20181005_1415
 [X] 0005_auto_20181005_1445
modoboa_postfix_autoreply
 [X] 0001_initial
 [X] 0002_auto_20150728_1236
 [X] 0003_move_aliases
 [X] 0004_delete_alias
 [X] 0005_auto_20151202_1623
 [X] 0006_auto_20160329_1501
 [X] 0007_auto_20180928_1423
 [X] 0008_delete_transport
modoboa_radicale
 [X] 0001_initial
 [X] 0002_auto_20170831_1721
 [X] 0003_auto_20180324_1834
 [X] 0004_auto_20200220_1816
 [X] 0005_auto_20200220_1819
otp_static
 [X] 0001_initial
 [X] 0002_throttling
otp_totp
 [X] 0001_initial
 [X] 0002_auto_20190420_0723
relaydomains
 [X] 0001_initial
 [X] 0002_migrate_from_modoboa_admin_relaydomains
 [X] 0003_auto_20170116_1508
 [X] 0004_auto_20161105_1424
 [X] 0005_auto_20161105_1426
 [X] 0006_auto_20170215_0948
 [X] 0007_recipientaccess
 [X] 0008_auto_20171123_1653
 [X] 0009_auto_20171124_1508
reversion
 [X] 0001_squashed_0004_auto_20160611_1202
sessions
 [X] 0001_initial
sites
 [X] 0001_initial
 [X] 0002_alter_domain_unique
transport
 [X] 0001_initial
 [X] 0002_auto_20180928_1520
(env) modoboa@mail3:~/instance$

**Comment by tonioo** [comment]
@optimdevel Looks like migrations for reversion have been squashed... I'm afraid you need to apply missing changes manually.

**Comment by tonioo** [comment]
@optimdevel Can you make sure than version 3.0.5 is installed?

**Comment by optimdevel** [comment]
Thank you for your help. I really appreciate it.

It is in env and by default on the system:
(env) modoboa@mail3:/instance$ python --version
Python 3.7.3
(env) modoboa@mail3:/instance$ exit
exit
$ exit
root@mail3:/etc# python --version
Python 3.7.3

However i do think that squashing migrations actually still applies all migrations, they are just condensed a. k. a. squashed.

To be noted, is that there was an error with one of the migrations:

django.db.utils.OperationalError: (1060, "Duplicate column name '_parameters'")
->nano -w /srv/modoboa/env/lib/python3.7/site-packages/modoboa/core/migrations/

so I faked it: python manage.py migrate --fake core 0010_auto_20161026_1011

as it seemed like it already has had this column and migration was already applied.


Maybe I should just start over, as this is a copy of production virtual instance where I test the upgrade procedure, and open a new issue when I reach failed migration.


Also on a related note, because i have to remove modoboa and do a install with latest installer again (upgrade fails with python dependencies hell) I have two questions:

Will modoboa (installer) regenerate all daemon (amavis, postfix, dovecot,..) files again if I purge remove them beforehand?
Will modoboa create missing databases and users (as defined in installer.cfg) for plugins that were non existent in the previsously installed version?

**Comment by tonioo** [comment]
I was talking about the django-reversion installed version.

The issues your are facing are pretty strange? Are you trying to upgrade from a pretty old version?

**Comment by optimdevel** [comment]
I got 1.5.3 on Debian 8 to upgrade to recent version and it has proved not to be so easy.

Maybe I should just empty revisions table and make django regenerate it? I think I this can be done.

**Comment by tonioo** [comment]
If you want to do that, you can remove all reversion tables and also delete corresponding rows in the migrations table, otherwise tables won't be recreated. 
And of course, you'll loose your audit trail history

**Comment by tonioo** [comment]
I suggest you drop tables and corresponding rows in the migration table directly from mariadb if you know a bit of SQL

**Comment by optimdevel** [comment]
Yeah, I could do that and I might have to.
In the mean time, please read you email. :-)

**Comment by ilovefreesw** [comment]
Got the same error....

![image](https://user-images.githubusercontent.com/77317006/136018126-807db075-60f6-44a5-bc7c-584e95b1d8ec.png)

**Comment by marutichintan** [comment]
i am getting the same 500 error. i have enable the debug and show me full error. error is "Error 111 connecting to localhost:6379. Connection refused."

modoboa is not able to connect redis.

my redis service is down.

service redis start 

it working now.

**Comment by sacb2** [comment]
Hi (i know is a bit late for this ...sorry, but if someone arrive here on the future i want to share this) , i install this in a clean debian 11 and found two problems maybe can help you ... first of all i have the same problem as you when i use the mysql database i reintall using the postgress and all works well... but on the installation i found this 

First ... the nginx fails because the creation of certs fail ... so i run this:
certbot certonly --standalone -d mail.example.com

and then i found the permission are not right on this socket so run this:

sudo chown www-data:www-data /run/uwsgi/app/modoboa_instance/socket
chmod 770 /run/uwsgi/app/modoboa_instance/socket

and finally i firts try to install this on a mysql database but i encounter a problem on the rout that create the users bur i reinstall it using the postgres database and the userrs run well :)
