### ISSUE TITLE
SMTP error 554 5.7.1 "Client host rejected: Access denied

### ISSUE THREAD

**Issue by 7838099724** [modoboa/modoboa#2311]
Hello I've Installed modoboa via installer everything is working fine but when I need to configure smtp pop 3 to configure emails in outlook and thunderbird. To enable smtp I followed this tutorial https://www.linuxbabe.com/mail-server/enable-smtps-port-465-postfix. after doing everything Mails are not going by thunderbird and not able to configure in outlook

**Comment by 7838099724** [comment]
Mails are receiving in  thurnderbird but when I am trying to send then
I’m getting this error in log file

Jul 4 10:18:29 mail postfix/submission/smtpd[2960795]: connect from unknown[47.15.240.42]
Jul 4 10:18:29 mail postfix/submission/smtpd[2960795]: warning: connect to Milter service inet:127.0.0.1:12345: Connection refused
Jul 4 10:18:31 mail postfix/submission/smtpd[2960795]: Anonymous TLS connection established from unknown[47.15.240.42]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange ECDHE (P-256) server-signature RSA-PSS (2048 bits) server-digest SHA256
Jul 4 10:18:32 mail postfix/submission/smtpd[2960795]: NOQUEUE: reject: RCPT from unknown[47.15.240.42]: 554 5.7.1 <unknown[47.15.240.42]>: Client host rejected: Access denied; from=<> to=<> proto=ESMTP helo=<[192.168.43.87]>

**Comment by tonioo** [comment]
Looks like opendkim is not started, can you check that?

**Comment by NESC1US** [comment]
I am having the same issue and after few years trying to use modoboa, i'd suggest to try mailinthebox.. sorry
