### ISSUE TITLE
Feature Request: WebAuthn

### ISSUE THREAD

**Issue by 10Meisterbaelle** [modoboa/modoboa#2331]
WebAuthn support for hardware-based authentication

**Comment by meramsey** [comment]
Something like this added would be awesome
https://github.com/mkalioby/django-mfa2

**Comment by meramsey** [comment]
still no interest in this?

**Comment by bcsanford** [comment]
not sure how it was done but Mesh Central Supports this works great with my Yubikey, would love to have it with Modoboa

**Comment by Spitfireap** [comment]
I'm working on it, see #2585 to see advancement :)

**Comment by rivarob04** [comment]
I am highly intrested in this. How do I get more people on board?
