### ISSUE TITLE
Message Log not loading additional messages on high resolutions

### ISSUE THREAD

**Issue by PatTheMav** [modoboa/modoboa#2339]
# Impacted versions

* OS Type: Debian
* OS Version: 10
* Database Type: PostgreSQL
* Database version: 11.12
* Modoboa: 1.17.0
* installer used: No ?
* Webserver: Nginx

# Steps to reproduce

* Open Modoboa's web interface on a high resolution screen (e.g. 4k or 5k)
* Open Message Log
* See Message log displaying a first set of messages, but not loading additional ones

# Current behavior

I originally reported that the message log is not populated, but that turned out to not be correct. Instead it seems that if the browser window is big enough to display the initial set of logged messages in the Message Log, no scroll event can happen and no additional messages are loaded.

Thus it appears as if only the first few events since an upgrade to 1.16 are contained in the log. But when resizing the browser window to require scrolling to get to the bottom of the list, additional messages are loaded.

(Do note that this is quite probably a bug in the web interface and should thus be moved into that repo).

# Expected behavior

Additional messages are loaded even on screen resolutions where the initial page does not require scrolling.

**Comment by tonioo** [comment]
@PatTheMav This is a general bug we have with the "infinite scroll" feature which behaves badly on high resolutions. I don't think I'll fix it because we won't use such mode in the new interface.

**Comment by ksaadDE** [comment]
> @PatTheMav  I don't think I'll fix it because we won't use such mode in the new interface.

#closed?
