### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ukrolelo** [modoboa/modoboa#2358]
# Impacted versions

* OS Type: Debian
* OS Version: 10
* Database Type: PostgreSQL
* Database version: X.y
* Modoboa: latest
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

# Current behavior

Can't install

# Expected behavior

Install
# Video/Screenshot link (optional)

----------SHELL----------- (LONG CONFEFE)
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Overwrite the existing SSL certificate? (y/N)
Installing amavis
Installing spamassassin
Installing razor
Installing clamav
Installing modoboa
_

```` TOP````
7247 modoboa   20   0  116020 103540  10332 R 100.0   2.6 606:30.25 pip
606 minutes and 100% CPU the whole night !!!!?!?!?!
-
7247 modoboa   20   0  112284  99712  10332 R 100.0   2.5 775:42.84 pip
775 minutes 100%cpu

**Comment by tonioo** [comment]
See https://github.com/modoboa/modoboa-installer/issues/388
