### ISSUE TITLE
LDAP: Error in creating/updating userPassword

### ISSUE THREAD

**Issue by alexcustos** [modoboa/modoboa#2372]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 20.04
* Database Type: PostgreSQL
* Database version: 12
* Modoboa: 1.17.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

```
# https://github.com/modoboa/modoboa/blob/master/modoboa/ldapsync/lib.py
if user.password:
        password = get_user_password(user, not user.is_active)
        ldif.append((ldap.MOD_REPLACE, "userPassword", password))
```
# Current behavior

This is not how the password is supposed to be created/updated in LDAP. This code extracts the SHA512-CRYPT string and sends it to LDAP. I debugged it for a while, and `force_bytes("plain_text_password")` instead of the `password` variable does the job.

# Expected behavior

I expect a proper password to be sent to LDAP to allow other clients to use it as well.

**Comment by tonioo** [comment]
Plain text password is not available in the database and OpenLDAP (at least) is supposed to understand the way password are stored in modoboa because we use the same format...

**Comment by alexcustos** [comment]
> Plain text password is not available in the database

Not far from the LDAP sync handler, there's a `raw_value` variable  (`core/models.py`). It looks like a raw password that can be passed down to the handler. I guess it's how it's supposed to work. Otherwise, LDAP synchronization doesn't make any sense. Modoboa can authenticate against Plain and SSHA hashed passwords in LDAP but saves back gibberish.

**Comment by tonioo** [comment]
The raw value you're talking about is only available when you set a new password. When do you any other kind of modification, then we don't have it. Could it be possible that your LDAP tries to hash the password sent by modoboa once again?
