### ISSUE TITLE
Amavis stops working after finishing max_requests

### ISSUE THREAD

**Issue by PatTheMav** [modoboa/modoboa#2374]
# Impacted versions

* OS Type: Debian
* OS Version: 11
* Database Type: PostgreSQL
* Database version: 13.4
* Modoboa: 1.17.0
* installer used: No
* Webserver: Nginx

# Steps to reproduce

* Have postfix+amavis setup running as intended by the installer
* Have `$max_servers = 1;` in `/etc/amavis/conf.d/50-user`
* See amavis closing the process after processing 20 requests (default setting)
* Notice amavis stopping

# Current behavior

With the setup as configured by `modoboa-installer` amavis will run with a single master process. Amavis will kill its process after a configured number of processed messages (this number is 20 by default), after which `Net::Server` should start a new process.

After I upgraded to Debian 11 this behaviour seems broken - the limit is reached, the current process is terminated, but no new process is spawned:

```
Oct 11 12:51:39 mailserver amavisd-new[4150261]: Oct 11 12:51:39.429 mailserver /usr/sbin/amavisd-new[4150261]: (4150261-20) Requesting process rundown after 20 tasks (and 20 sessions)
```

Once amavis has cleaned up after receiving `SIGTERM` the whole unit comes to a stop:

```
Oct 11 12:51:40 mailserver systemd[1]: amavis.service: Succeeded.
Oct 11 12:51:40 mailserver systemd[1]: amavis.service: Consumed 14.497s CPU time.
```

As amavis is correctly configured as a proxy_filter in postfix, this results in all incoming mails bouncing.

# Expected behavior

The Amavis unit stays alive after planned process rundown.

# Possible fix

I still have to run some tests, but I increased the `$max_proesses` to any number bigger than `1` which results in amavis spawning _actual_ child processes which can then be terminated and restarted without issue (I checked this by limiting `$max_requests` to `1` forcing amavis to restart a child after processing a single mail).

_Theoretically_ `smtpd` processes will wait for amavis processes to become available, allowing mail clients to terminate a submission if it takes too long (as the `smtpd` process waits for amavis to finish) so increasing `max_servers` should be fine.

But I haven't been able to figure out why amavis doesn't spawn a single child process (which it can then restart) and instead uses the master process which (in essence) terminates itself after 20 tasks have been completed.

**Comment by PatTheMav** [comment]
@tonioo Alas I haven't, but I checked out some debug logs and also the source code.

`max_servers` seems to implicitly expect `2` as it's lower boundary, and with a value >1, it uses the `Net::Server::PreForkSimple` variant:
```
Net::Server: 2021/12/15-15:56:24 Amavis (type Net::Server::PreForkSimple)
```

With the value set to `1` however it runs as a non-forking server:
```
Net::Server: 2021/12/15-15:53:59 Amavis (type Net::Server)
```

This is due to this switch in amavis' source code:

```
  @ISA = !$daemonize && $max_servers==1 ? 'Net::Server' # facilitates debugging
                 : defined $min_servers ? 'Net::Server::PreFork'
                                        : 'Net::Server::PreForkSimple';
```

When using `systemd` (as I do) to run amavis, the default unit file shipped by Debian runs it in foreground, which sets `daemonize` to `0`, thus the "facilitates debugging" branch is taken.

It seems the observed behaviour is "intended" when given the environment used by `systemd`.

**Comment by whirm** [comment]
@PatTheMav  Thanks for sharing your debug work, you saved me a lot of time!
