### ISSUE TITLE
Missing deps

### ISSUE THREAD

**Issue by fpoulain** [modoboa/modoboa#2398]
Hi,

Following the `getting_started.rst` to get an instance for development for testing purpose,  it appeared that there are some missing dependencies :

- factory-boy
- testfixtures

What about adding them into `dev-requirements.txt`?

Also, FYI, I needed `python3-rrdtool` under Debian during the setup step. It seems to be an `easy_install` lack (building headers missed).

Also, FYI, `python3 -m venv` require installing `python3-venv` under Debian. Personally I used `virtualenv --system-site-packages --python=python3` at this step (which require `python3-virtualenv`).

I don't know if you want to introduce a « packages » section in the getting started section of the docs.

**Comment by tonioo** [comment]
The requirements you mention are located in the ``test-requirements.txt`` file so I guess we should include them in the documentation and yes, a packages section could be useful.
