### ISSUE TITLE
Didnt see real mail quota after user recreation

### ISSUE THREAD

**Issue by Quiver92** [modoboa/modoboa#2409]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 20.04.1 LTS
* Database Type: PostgreSQL
* Database version: 12
* Modoboa: 1.15.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
1. backup user folder with all data
2. remove user profile from modoboa GUI
3. copy user directory to domain folder
4. create new user with old username
5. mailbox quota = 0 and in database I see 0 messages counter with 0 bytes

# Current behavior
Currently after mailbox recreation I have 0 bytes mailbox instead of real amount of messages and bytes

# Expected behavior
After user recreation mailbox must have previous size 

# Video/Screenshot link (optional)
Here I have mailbox with 207MB size but in gui or database I didn't see real size. I see only new messages size(I send one test message)
![obraz](https://user-images.githubusercontent.com/13777007/142996568-888de69f-fca5-4aac-8d06-00a667eec805.png)
screenshot from SQL database
![obraz](https://user-images.githubusercontent.com/13777007/142996625-cf03d28f-fcf5-46f4-8bd4-9826324009ef.png)

**Comment by tonioo** [comment]
@Quiver92 Have you tried to run ``doveadm quota recalc`` ?
