### ISSUE TITLE
Cron <root@mail> $PYTHON $INSTANCE/manage.py communicate_with_public_api

### ISSUE THREAD

**Issue by michael-v-bloom** [modoboa/modoboa#2422]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 20.04 (LTS) x64
* Database Type: MySQL
* Database version: 15.1
* Modoboa: 1.17.0
* installer used: Yes
* Webserver: Nginx

# Current behavior

**Notification email from:** Cron Daemon <root@mail.domain.com>
**Email Subject:** Cron <root@mail> $PYTHON $INSTANCE/manage.py communicate_with_public_api 
**Email Message:** CommandError: Failed to retrieve versions from the API. 

This is the 3rd time I receive this error notification from the mail server.
On the other hand, everything works well in terms of receiving and sending. No other errors or issues.

I've been looking for a solution here, but I found that this issue was supposed to be already fixed for this version of Modoboa.

Any ideas? Thanks!

Best regards,
Michael

**Comment by jaggeddragon** [comment]
The best solution I've heard is to update the cronjob to yearly, or delete it entirely

As far as I am aware, this API call is solely to 'call-home' and report usage statistics to the developer. The error indicates nothing about your installation, just that the api endpoint is overloaded, expired, outdated, unsupported, and likely forgotten about.

This issue has been raised several times, and closed with no changes/justification. I may or may not be bitter about that.
