### ISSUE TITLE
Creating a disabled account imply an active (internal) alias

### ISSUE THREAD

**Issue by fpoulain** [modoboa/modoboa#2429]
Testing against behavior similarly to #2120 it appears that creating a disabled account imply creation of an active (internal) alias.

# Impacted versions

* OS Type: Debian
* OS Version: Buster
* Database Type: PostgreSQL
* Database version: 11
* Modoboa: 1.17.3 (also on master branch)

# Steps to reproduce

* Create an account with Simple user role and disable it at the creation
* Send an email to this account

Here is a (failling) test case: https://github.com/fpoulain/modoboa/commit/05dda3cdcd27f6b4d651cf9622fa62ba03244a74

# Current behavior

```ipython
In [1]: from modoboa.core.models import User
In [2]: from modoboa.admin.models import Alias
In [3]: u = User.objects.get(email='tester@test.com')
In [4]: u.enabled
Out[4]: False
In [5]: a = Alias.objects.get(address=u.email)
In [6]: a.enabled
Out[6]: True
In [7]: a.internal
Out[7]: True
```

# Expected behavior

```ipython
In [1]: from modoboa.core.models import User
In [2]: from modoboa.admin.models import Alias
In [3]: u = User.objects.get(email='tester@test.com')
In [4]: u.enabled
Out[4]: False
In [5]: a = Alias.objects.get(address=u.email)
In [6]: a.enabled
Out[6]: False
In [7]: a.internal
Out[7]: True
```

**Comment by fpoulain** [comment]
I may provide a PR if you confirm that the current behavior is a bug.

**Comment by tonioo** [comment]
@fpoulain Does it mean you can send an email to this account anyway? What is the underlying issue here?

**Comment by fpoulain** [comment]
> Does it mean you can send an email to this account anyway?

Yes.

**Comment by tonioo** [comment]
Then indeed, it's a bug.The internal alias state should be synchronized with the account one.

**Comment by fpoulain** [comment]
Ok, will try to fix it and opening a PR.
