### ISSUE TITLE
imap4_utf_7 encoding/decoding fails in Python 3.9 

### ISSUE THREAD

**Issue by cbuh4** [modoboa/modoboa#2432]
# Impacted versions

* OS Type: Debian
* OS Version: 11
* Database Type:  MySQL
* Database version: *
* Modoboa: 2.0.0b3
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

When installing beta to be able to work with 3.9.2 which is default in debian 11 the /webmail/ route throws an error on initial load.
With debug = True it shows a problem with the imap4-utf-7 encoding/decoding (after fiddling with unitialized data var in getquota function of imaputils.py first ;) )

# Current behavior

Call of route /webmail/ fails

# Expected behavior

With Python 3.9 the naming convention was changed back to standard.
In imap_utf7.py the hyphens in corresponding functions should be replaced with underscores.

see also: https://twistedmatrix.com/trac/ticket/9832 and https://bugs.python.org/issue37751
Naming convention should be adopted to PY3.9 naming convention.

**Comment by psztoch** [comment]
Try this: https://github.com/modoboa/modoboa-webmail/issues/227

**Comment by avsdev-cw** [comment]
I've also run into this over the last few days and can confirm that the linked issue does fix this problem.

**Comment by tonioo** [comment]
Duplicate.
