### ISSUE TITLE
CardDAV does not hold to the yes state.

### ISSUE THREAD

**Issue by KrystianPlichta** [modoboa/modoboa#2440]
# Impacted versions

* OS Type: Debian
* OS Version: 10
* Database Type:  MySQL
* Database version: 10.3.31-MariaDB
* Modoboa: 1.17.0
* installer used: Yes
* Webserver: Nginx
* Radicale management | 1.5.1
* Contacts | 0.8.2

# Steps to reproduce
Go to SETTINGS >> PREFERENCES >> CONTACTS >> Synchonize address book using CardDAV > turn from No to Yes.
# Current behavior

radiobutton after switching to the Yes state and clicking Save and after refreshing the page it returns to the No state.

# Expected behavior
radiobutton switches to the yes state and after clicking save the address book synchronization works.

# Video/Screenshot link 
This is what i see in console:

![Inkederrors carddav](https://user-images.githubusercontent.com/45468944/149904490-270abcd4-90c7-4798-8d9a-1c6a20098adb.jpg)

UWSGI LOG:
 POST /user/preferences/ => generated 870 bytes in 146 msecs (HTTP/1.1 500) 8 headers in 314 bytes (1 switches on core 0)

**Comment by tonioo** [comment]
@KrystianPlichta Can you set DEBUG to True inside settings.py file, reload uwsgi and try again? You should get more information.

**Comment by KrystianPlichta** [comment]
I set debug to true and reset uwsgi but nothing changed.

**Comment by tonioo** [comment]
You need to look at the network tab when you javascript debug console is opened, check the response of the request which returns with a 500 error code

**Comment by KrystianPlichta** [comment]
Here is what I found in the debug console:

https://pastebin.com/ceDnqpVv

**Comment by tonioo** [comment]
@KrystianPlichta thanks. Did you install the contacts plugin separately or was it installed by the installer?

**Comment by KrystianPlichta** [comment]
Installed by installer

**Comment by KrystianPlichta** [comment]
I run carddav synchronization option by changing from false to true in database, after entering contacts and clicking synchronize I see the following error.

https://pastebin.com/ZPHUfYDY

I also tried reinstalling modoboa-contacts and radicale but nothing changed

**Comment by amaciej** [comment]
I have a similar problem. Does anyone know the solution ?
