### ISSUE TITLE
Feature request: Custom theme creation

### ISSUE THREAD

**Issue by TukanDev** [modoboa/modoboa#2448]
Allowing more experienced users to create custom themes for admin dashboard and webmail.
Possibly making 2 categories of themes: admin dashboard theme and webmail theme setting
Could be implemented at later releases of 2.0 (end of beta...)

**Comment by mohamed-ghayyad** [comment]
https://i.imgur.com/LkJJv7Y.png

compatible themes https://bootswatch.com/3/
cd /srv/modoboa/instance/sitestatic/bootstrap/dist/css
mv bootstrap.min.css bootstrap.min.css.backup
then wget https://bootswatch.com/3/<themename>/bootstrap.min.css
