### ISSUE TITLE
ProgrammingError at / relation "core_localconfig" does not exist

### ISSUE THREAD

**Issue by forexstudies** [modoboa/modoboa#2449]
# Impacted versions

* OS Type: Ubuntu ...
* OS Version: 21.10
* Database Type: PostgreSQL 14
* Database version: 14
* Modoboa:  (latest version at git clone https://github.com/modoboa/modoboa-installer)
* installer used: No ?
* Webserver: Nginx/Apache

# Steps to reproduce
Run installer

# Current behavior
<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">ProgrammingError at /</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">relation "core_localconfig" does not exist
LINE 1: ...s", "core_localconfig"."need_dovecot_update" FROM "core_loca...
                                                             ^
</pre>

Request Method: | GET
-- | --
https://my-email-server-domain/
2.2.26
ProgrammingError
relation "core_localconfig" does not exist LINE 1: ...s", "core_localconfig"."need_dovecot_update" FROM "core_loca...                                                              ^
/srv/modoboa/env/lib/python3.9/site-packages/django/db/backends/utils.py in _execute, line 84
/usr/bin/uwsgi-core
3.9.7
['.',  '',  '/usr/lib/python39.zip',  '/usr/lib/python3.9',  '/usr/lib/python3.9/lib-dynload',  '/srv/modoboa/env/lib/python3.9/site-packages']
Sun, 30 Jan 2022 08:18:09 +0100

</body>
</html>

# Expected behavior
Expected to open the Web interface. I was disappointed that after installing on a brand new server, my first attempt to open the web interface ws met with an obvious error in feedparser.py base64.decodestring i had to update this file to make it work. I thought this would have been fixed by now. The next issue is this...looks like no databases were created

# Video/Screenshot link (optional)

**Comment by forexstudies** [comment]
oh i just checked the databases were actually created, now begs the question why is this error happening
                                 List of databases
     Name     |    Owner     | Encoding | Collate |  Ctype  |   Access privileges
--------------+--------------+----------+---------+---------+-----------------------
 amavis       | amavis       | UTF8     | C.UTF-8 | C.UTF-8 | =Tc/amavis           +
              |              |          |         |         | amavis=CTc/amavis    +
              |              |          |         |         | modoboa=CTc/amavis
 modoboa      | modoboa      | UTF8     | C.UTF-8 | C.UTF-8 |
 postgres     | postgres     | UTF8     | C.UTF-8 | C.UTF-8 |
 spamassassin | spamassassin | UTF8     | C.UTF-8 | C.UTF-8 |

**Comment by forexstudies** [comment]
No tables created in modoboa database, i am pretty sure there must be some tables here. I do not know where the sql scripts are

**Comment by mohamed-ghayyad** [comment]
Try installation with --beta flag on a fresh Debian 11

`python3 run.py --beta domain.ltd`

and if you want to change hostname from mail.domain.ltd use

`python3 run.py --beta --stop-after-configfile-check domain.ltd`

and change it in the generated cfg

Lastly, KernelPanic Implemented a bash script to install z-push for Microsoft ActiveSync 

`https://github.com/dborg89/modoboa-z-push`

**Comment by forexstudies** [comment]
no changing to debian now is no longer an option
rather try a different server like iRedMail
