### ISSUE TITLE
Feature Request: Blackhole email address creation

### ISSUE THREAD

**Issue by TukanDev** [modoboa/modoboa#2450]
Option when creating simple user type accounts to make the account blackhole meaning it will be only allowed to send emails and not receive any doesn't have an inbox etc...

**Comment by tonioo** [comment]
@TukanDev Any idea about how to do that with postfix/dovecot?

**Comment by TukanDev** [comment]
@tonioo I'm, not that experienced with postfix and dovecot myself but I found a few guides that could help you get it working with modoboa.
https://unix.stackexchange.com/questions/338084/correct-way-to-create-a-blackhole-account-in-postfix#369300
https://forum.iredmail.org/topic2736-iredmail-support-create-blackhole-mail-address-eg-noreplyexamplecom.html
https://www.lanxic.my.id/blackhole-email-address/ 

Can't confirm if any of these setups they show in these guides will work for modoboa but its worth a shot.

**Comment by jhjacobs81** [comment]
whats the idea behind this?

**Comment by TukanDev** [comment]
> whats the idea behind this?
@jhjacobs81 
The idea behind this is allowing users to create noreply email addresses without the messages their noreply email receives filling space etc... instead it just destroys all incoming emails making that account only allowing to send emails programmatic way for example notifications, newsletters...
Generally you can make simple user account for this and it would work fine but that account will be able to receive emails unless you do some manual configuration yourself, so having that option for account type would be cool.

**Comment by damko** [comment]
I'd like to upvote this feature request. I'm impressed by Modoboa (first time user but running mailservers since a while) but I was surprise that I could not find a "noreply" option
