### ISSUE TITLE
Server only for sending mails

### ISSUE THREAD

**Issue by blu-IT** [modoboa/modoboa#2521]
Hello,

I have a modoboa mailserver successfully running for one domain, let's say domain1.com. On this domain1 mails are sent and receieved.

Now I want to configure a second domain, let's say domain2.com on this server, **but only for sending** mails via this server. The mailbox of that domain itself should stay at the webhoster system as it already is. **So mails for domian2 should not be receieved and stored on this host.**

I am not sure how to achieve this. Do I have to "fully" configure the new domain2.com in modoboa and only change SPF-records in the DNS system of the webhoster to allow sending from this host? Or do I have to configure a "relay-domain"?

Thanks!

Regards

**Comment by tonioo** [comment]
@blu-IT I think this is pretty similar to #2450 ?

**Comment by blu-IT** [comment]
@tonioo Yes, it is a little bit similar, but I want that people are able to respond. Mails still have to be accepted by the "old" existing mx-server for the domain.
So the already implemented "relay-domain" does not solve this? It only accepts mails and forwards to the destination server (here it would be my "old" already existing my-server) or can a relay-domain server also be used as a pure smtp-server for sending mails?

**Comment by blu-IT** [comment]
I think something like this will be a solution: https://www.linuxbabe.com/mail-server/postfix-send-only-multiple-domains-ubuntu

DKIM is important, so I will have to handle with "relay-domain" setup on modoboa I think...

**Comment by ksaadDE** [comment]
> I think something like this will be a solution: https://www.linuxbabe.com/mail-server/postfix-send-only-multiple-domains-ubuntu
> 
> DKIM is important, so I will have to handle with "relay-domain" setup on modoboa I think...

Is your issue solved? ^^

**Comment by ksaadDE** [comment]
@tonioo 28 days no reaction, I think we can close this.

**Comment by blu-IT** [comment]
Sorry for the delay! I found another workaround for the moment. Only a temporary solution.

But I am still not sure what configuring a "relay-domain" in modoboa means? Does ist mean, that modoboa accepts mails for the relay domain and forwards the mail to the destination where the domain / mailboxes _are really hosted_ or is a relay domain on modoba a sending gateway for the "real" mailserver somewhere else?

**Comment by ksaadDE** [comment]
> Sorry for the delay! I found another workaround for the moment. Only a temporary solution.
> 
> But I am still not sure what configuring a "relay-domain" in modoboa means? Does ist mean, that modoboa accepts mails for the relay domain and forwards the mail to the destination where the domain / mailboxes _are really hosted_ or is a relay domain on modoba a sending gateway for the "real" mailserver somewhere else?

hey, lets talk on the discord about the other issues.
