### ISSUE TITLE
postfix gives Untrusted TLS connection established in mail.log

### ISSUE THREAD

**Issue by blackhold** [modoboa/modoboa#2537]
# Impacted versions

* OS Type: Debian
* OS Version: 11.3
* Database Type: PostgreSQL
* Database version: 13.7
* Modoboa: last
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
In clean install it gives this messages in mail.log when sending mails, for example to gmail. I'm using letsencrypt as certificate generator.

```
root@mail-2022:/var/log# grep Untrusted mail.log
Jun 10 15:13:37 mail-2022 postfix/smtp[113807]: Untrusted TLS connection established to gmail-smtp-in.l.google.com[66.102.1.27]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256) server-digest SHA256
```

# Current behavior
Gives errors, don't affect on send e-mails, but is ugly :P

# Expected behavior
Do not give this errors

# Solution
Check ca-certificates is installed (it was installed), and add the last line (with [+]) to /etc/postfix/main.cf

```
root@mail-2022:/etc/postfix# dpkg -l |grep ca-certificates
ii  ca-certificates                    20210119                                         all          Common CA certificates
```

```
# Use TLS if this is supported by the remote SMTP server, otherwise use plaintext.
smtp_tls_CApath = /etc/ssl/certs
smtp_tls_security_level = may
smtp_tls_loglevel = 1
smtp_tls_exclude_ciphers = EXPORT, LOW
[+]smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
```

**Comment by MrGeneration** [comment]
Sorry but am I missing the error message?
I guess your point is "no SSL" - but I have to tell you, this string tells you the connection is using SSL: ` TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256) server-digest SHA256`

The line you've provided is a mere default information line about a connection from a google mail server.

**Comment by blackhold** [comment]
I used default installation and gives this errors. I think that could be interesting to add the line I have told to configuration file during the installation.

**Comment by MrGeneration** [comment]
Can you please tell me WHERE in the log message you provided you see an issue / error?

**Comment by blackhold** [comment]
Is an issue. Well I leave it here for who have the same ISSUE.

**Comment by MrGeneration** [comment]
You're not getting it.
"Untrusted connection" means that an server not belonging to your trusted base is connecting.

This is pretty much the norm for ALL external servers connecting.
Would you give google the key to your house? Thus trust google that much to enter it without you being present?
That's basically the same thing.

**Comment by ksaadDE** [comment]
> You're not getting it. "Untrusted connection" means that an server not belonging to your trusted base is connecting.
> This is pretty much the norm for ALL external servers connecting. 

Also it looks more like a postfix error, not modoboa #closed ?

**Comment by tonioo** [comment]
Indeed
