### ISSUE TITLE
API docs missing

### ISSUE THREAD

**Issue by faphdev** [modoboa/modoboa#2548]
Following the documentation to look at the API you get an error.
I was not able to see API documentation of the API anywhere else other than the demo server which again is not there.

Thanks for fixing this!

**Comment by ksaadDE** [comment]
Hello, thanks for your report.


Please look at the edits in the following PR:
https://github.com/modoboa/modoboa/pull/2538


The API was moved to another route in v2. But was not added to docs. 
The demo server has not enabled that API. Regular installations have. 

#Closed @tonioo

**Comment by faphdev** [comment]
Hmm, I would like to see the API documentation before installing. Forgive me if that is not a reasonable expectation.

**Comment by Esuk** [comment]
https://demo.modoboa.org/api/schema-v2/swagger/

**Comment by ksaadDE** [comment]
https://github.com/modoboa/modoboa/pull/2538

**Comment by ksaadDE** [comment]
@tonioo  regarding your comment about the /v2 route.
