### ISSUE TITLE
Calendar throws an internal error 

### ISSUE THREAD

**Issue by arbales** [modoboa/modoboa#2552]
I receive a KeyError when getting or posting to routes with any parameters attached. My formatting for the requests matches those I use for other endpoints, and I can query (GET) without parameters correctly. This happens on both the v1 and v2 endpoints.

I'm using an API token for authentication and it also works properly elsewhere. So, Im not sure why it would be looking for the `password` key. 

```KeyError at /api/v1/user-calendars/1/events/
'password'
Request Method:	POST
Request URL:	https://……/v2/user-calendars/1/events/
Django Version:	3.2.13
Exception Type:	KeyError
Exception Value:	
'password'
Exception Location:	/srv/modoboa/env/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py, line 65, in __getitem__
Python Executable:	/usr/bin/uwsgi-core
Python Version:	3.9.2
Python Path:	
['.',
 '',
 '/usr/lib/python39.zip',
 '/usr/lib/python3.9',
 '/usr/lib/python3.9/lib-dynload',
 '/srv/modoboa/env/lib/python3.9/site-packages']
Server time:	Sat, 25 Jun 2022 23:04:57 +0200```

**Comment by tonioo** [comment]
@arbales Could you provide a complete trace please?
