### ISSUE TITLE
INFO exited: policyd (exit status 1; not expected) after having modoboa installed on Ubuntu

### ISSUE THREAD

**Issue by TubaApollo** [modoboa/modoboa#2562]
# Impacted versions

* OS Type: Ubuntu
* OS Version: Ubuntu 22.04
* Database Type: PostgreSQL
* Database version: 14
* Modoboa: 2.0.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Installing modoboa via. Installer on Ubuntu
Trying to send Mail
Check supervisord.log
# Current behavior
After installing modoboa via the installer i get following error (bootloop), it repeats every second, in "supervisord.log":
`2022-07-11 14:11:52,665 INFO success: policyd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-07-11 14:11:53,009 INFO exited: policyd (exit status 1; not expected)
2022-07-11 14:11:54,012 INFO spawned: 'policyd' with pid 5410
2022-07-11 14:11:55,216 INFO success: policyd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-07-11 14:11:55,217 INFO exited: policyd (exit status 1; not expected)`

Also in my mail.log i get following error:
`Jul 11 14:09:44 tubaapollo postfix/smtpd[4613]: NOQUEUE: reject: RCPT from localhost[127.0.0.1]: 451 4.3.5 <name@example.com>: Recipient address rejected: Server configuration problem; from=<admin@example.com> to=<name@example.com> proto=ESMTP helo=<host>
Jul 11 14:09:44 tubaapollo postfix/smtpd[4613]: using backwards-compatible default setting smtpd_relay_before_recipient_restrictions=no to reject recipient "name@example.com" from client "localhost[127.0.0.1]"
Jul 11 14:09:44 tubaapollo postfix/smtpd[4613]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=0/1 rset=1 quit=1 commands=4/5`
I already tried different solutions from this issue: https://github.com/modoboa/modoboa/issues/2200, but they sadly havent helped

# Expected behavior
No errors/bootloop in logs
Sending from mails should work

**Comment by Spitfireap** [comment]
Same issue here, seems to be same issue as #2561
