### ISSUE TITLE
hard coded path won't work if you use a path prefix

### ISSUE THREAD

**Issue by gawel** [modoboa/modoboa#2567]
# Impacted versions

* OS Type: Debian
* OS Version: Bullseye
* Database Type: MySQL
* Database version: X.y
* Modoboa: 2.0.1
* installer used: No
* Webserver: Apache

# Steps to reproduce

Create a urls.py file and use it in your settings:

```
from django.conf.urls import include, url

urlpatterns = [
    url(r'^manager/', include('modoboa.urls')),
]
```

# Current behavior

There is some hard coded links in the js files. At least for the 2FA auth: https://github.com/modoboa/modoboa/blob/fda59b51e1ef7f57f3601015dcdc2693f7f7efe8/modoboa/static/js/twocols_nav.js#L180

But the real url is `/manager/api/...` so the ajax request fail with a 404

Same problem with the new vuejs UI. Everything is expected to be at `/new-admin/` but we need `/manager/new-admin`. I guess this one can be fixed with sed

# Expected behavior

Api calls should work even if we use a prefix

A solution is to define a js variable with the correct prefix. Something like:

```
window.API_ROOT = "{% url api_root %}"
```

And use this var in the js files.

**Comment by ksaadDE** [comment]
Could you create a patch + PR for this? 

To my understanding of reading it for a few seconds, it might be a variable change in the files, since it is hardcoded right?

**Comment by gawel** [comment]
PR done for the tfa stuff. Looks likes a postgres test is failing because of... mysql. Not sure how to fix that

**Comment by ksaadDE** [comment]
> PR done for the tfa stuff. Looks likes a postgres test is failing because of... mysql. Not sure how to fix that

@tonioo

**Comment by tonioo** [comment]
For the record, it's not possible to conditionally start services with GHA (see https://github.com/actions/runner/issues/822)
