### ISSUE TITLE
Ubuntu 22.04 remove identity with mailbox/doveadm issue

### ISSUE THREAD

**Issue by gsloop** [modoboa/modoboa#2570]
# Impacted versions

* Ubuntu 22.04 (But is really likely to be an issue for any distro with Dovecot versions > 2.3.11.3)
* Modoboa: 2.0.1
* installer used: Yes
* Webserver: Nginx

Deleting a user where you also delete the mailbox causes the issue. (Occurs with both the UI and API calls)

You get this message
Failed to retrieve mailbox location (b"doveconf: Fatal: Error in configuration file /etc/dovecot/conf.d/10-ssl.conf line 14: ssl_key: Can't open file /etc/ssl/private/mail.mydomain.com.key: Permission denied\n")

This is because the API calls doveadm to return the directory that holds the users mailbox. But doveadm won't run because of the change in the way doveadm handles the cert/key.

See: 
https://dovecot.org/pipermail/dovecot/2020-August/119644.html

(Essentially user vmail doesn't have rights to the SSL key and so doveadm fails to run.)

The "new" behavior of dovecot is to put the references to the cert/key into a file that's only readable by root.
Then replace the references to the cert/key with something like
!include_try /etc/dovecot/file-thats-only-root-readable-that-you-created-above

The result is that doveadm, when run by vmail will fail to read the cert/key, but instead of failing and aborting the doveadm invocation, it will still run and return the directory for the referenced user.

I also wrote this up as a bug-fix/work-around on the wiki here:
https://modoboa-wiki.herokuapp.com/en/known-issues-with-Ubuntu-22 

As noted above, this will likely occur on all distros that use dovecot versions > 2.3.11.3.

**Comment by ksaadDE** [comment]
Thanks for adding the write up to fix this! I can remember it took you a bunch of work to find the information in the documentation of Dovecot. I'm very thankful for your work and the write up in the modoba wiki!

Manually set ssl_cert and ssl_key in `/etc/dovecot/conf.d/10-ssl.conf`
```
touch /etc/dovecot/conf.d/10-ssl-keys.try
chmod root:root /etc/dovecot/conf.d/10-ssl-keys.try
chmod 0600 /etc/dovecot/conf.d/10-ssl-keys.try
echo "!include_try /etc/dovecot/conf.d/10-ssl-keys.try" >> /etc/dovecot/conf.d/10-ssl.conf
```
source:  https://modoboa-wiki.herokuapp.com/en/known-issues-with-Ubuntu-22 

I think we can add it to the installer. @tonioo  what do you think about this?

**Comment by gsloop** [comment]
Oh, that touch command needs to be first.
So use this. 
(Probably it would work fine without it, since the >> of the grep should create the file if it doesn't exist, IIRC)
#Create the "try" file.
touch /etc/dovecot/conf.d/10-ssl-keys.try

#Move the cert/key directives to the "try" file and comment them out in the regular conf.
grep "^ssl_cert =" /etc/dovecot/conf.d/10-ssl.conf >> /etc/dovecot/conf.d/10-ssl.try
sed -i 's/ssl_cert =/#ssl_cert =/' /etc/dovecot/conf.d/10-ssl.conf
grep "^ssl_key =" /etc/dovecot/conf.d/10-ssl.conf >> /etc/dovecot/conf.d/10-ssl.try
sed -i 's/ssl_key =/#ssl_key =/' /etc/dovecot/conf.d/10-ssl.conf

#Set the permissions on the "try" file so only root can read it.
chown root:root /etc/dovecot/conf.d/10-ssl-keys.try
chmod 0600 /etc/dovecot/conf.d/10-ssl-keys.try

#Add the !try directive to the main dovecot ssl conf file.
echo "!include_try /etc/dovecot/conf.d/10-ssl-keys.try" >> /etc/dovecot/conf.d/10-ssl.conf

**Comment by ksaadDE** [comment]
> Oh, that touch command needs to be first. So use this. (Probably it would work fine without it, since the >> of the grep should create the file if it doesn't exist, IIRC)
> 
> #Create the "try" file. touch /etc/dovecot/conf.d/10-ssl-keys.try
> 
> #Move the cert/key directives to the "try" file and comment them out in the regular conf. grep "^ssl_cert =" /etc/dovecot/conf.d/10-ssl.conf >> /etc/dovecot/conf.d/10-ssl.try sed -i 's/ssl_cert =/#ssl_cert =/' /etc/dovecot/conf.d/10-ssl.conf grep "^ssl_key =" /etc/dovecot/conf.d/10-ssl.conf >> /etc/dovecot/conf.d/10-ssl.try sed -i 's/ssl_key =/#ssl_key =/' /etc/dovecot/conf.d/10-ssl.conf
> 
> #Set the permissions on the "try" file so only root can read it. chown root:root /etc/dovecot/conf.d/10-ssl-keys.try chmod 0600 /etc/dovecot/conf.d/10-ssl-keys.try
> 
> #Add the !try directive to the main dovecot ssl conf file. echo "!include_try /etc/dovecot/conf.d/10-ssl-keys.try" >> /etc/dovecot/conf.d/10-ssl.conf

You can remove the touch and instead place only a single > at the first grep. So the file gets created.

**Comment by felixlberg** [comment]
This Workaround doesn't work on my fresh installed Ubuntu 22.04.1 with dovecot 2.3.16, please reopen this issue.

I am able to see the default password shemes like "sha512crypt" but I am unable to connect with via smtp with port 993 now:

mail.log give me the follwing error:

mail dovecot: imap-login: Error: Failed to initialize SSL server context: Can't load SSL certificate (ssl_cert setting): The certificate is empty: user=<>, rip=xxx, lip=xxx, session=<XXXXXX>

When i set:
```
#ssl_cert = </etc/letsencrypt/live/mail.thurm.de/fullchain.pem
#ssl_key = </etc/letsencrypt/live/mail.thurm.de/privkey.pem
```

directly in `/etc/dovecot/conf.d/10-ssl.conf` then I can setup mails with imap on port 993 without problems but I have theese bugs described above.

So for me this is not a solution when I cannot use imap with ssl anymore. I will try to fix this problem in a better way with the dovecot documentation now.

**Comment by Spitfireap** [comment]
Hi,

I have been running this setup (so as multiple other user) without any issue. When did you install modoboa, and how did you install it ? :)

**Comment by felixlberg** [comment]
I installed modoboa yesterday with `sudo ./run.py <your domain>` on a new ubuntu 22.04.1 machine.

**Comment by Spitfireap** [comment]
Okay, so you didn't edit any dovecot related file, and just switched to sha512crypt, and now you can't log in ?

**Comment by felixlberg** [comment]
I think there is a misunderstanding, i will reproduce this error on a new instance and describe it further...

**Comment by Spitfireap** [comment]
> I think there is a misunderstanding, i will reproduce this error on a new instance and describe it further...

Thanks. I'm just wondering what step lead to the issue : after installing, did you modify any file or not (the workaround of this issue has already been applied to the installer)?

**Comment by felixlberg** [comment]
yes I didn't modified any files the workaround produces this error:
```
mail dovecot: imap-login: Error: Failed to initialize SSL server context: Can't load SSL certificate (ssl_cert setting): The certificate is empty: user=<>, rip=xxx, lip=xxx, session=<XXXXXX>
```
So you can not use imap or pop3 with ssl with the line `!include_try = /etc/dovecot/conf.d/10-ssl-keys.try` in `/etc/dovecot/conf.d/10-ssl.conf` you must revert it and add:
```
ssl_cert = </etc/letsencrypt/live/mail.thurm.de/fullchain.pem
ssl_key = </etc/letsencrypt/live/mail.thurm.de/privkey.pem
```
to `/etc/dovecot/conf.d/10-ssl.conf` to be able to login with ssl.

i see no reason why this problem should be specific to my machine. I will now test it on another instance of ubuntu 22.04 to fully confirm that this is reproducable.

**Comment by Spitfireap** [comment]
Could you post your `10-ssl.conf` and `10-ssl-keys.try` please ? (hide your personal info :p)

**Comment by felixlberg** [comment]
-rw-r--r-- 1 root root 2154 Nov 10 13:28 /etc/dovecot/conf.d/10-ssl.conf

```
# This file was automatically installed on 2022-11-09T12:13:42.570690
##
## SSL settings
##

# SSL/TLS support: yes, no, required. <doc/wiki/SSL.txt>
#ssl = yes

# Workarround https://github.com/modoboa/modoboa/issues/2570 
# We try to load the key and pass if it fails
# Keys require root permissions, standard commands would be blocked
# because dovecot can't load these cert
#!include_try = /etc/dovecot/conf.d/10-ssl-keys.try
ssl_cert = </etc/letsencrypt/live/mail.thurm.de/fullchain.pem
ssl_key = </etc/letsencrypt/live/mail.thurm.de/privkey.pem

#ssl_dh = </usr/share/dovecot/dh.pem

# If key file is password protected, give the password here. Alternatively
# give it when starting dovecot with -p parameter. Since this file is often
# world-readable, you may want to place this setting instead to a different
# root owned 0600 file by using ssl_key_password = <path.
#ssl_key_password =

# PEM encoded trusted certificate authority. Set this only if you intend to use
# ssl_verify_client_cert=yes. The file should contain the CA certificate(s)
# followed by the matching CRL(s). (e.g. ssl_ca = </etc/ssl/certs/ca.pem)
#ssl_ca = 

# Require that CRL check succeeds for client certificates.
#ssl_require_crl = yes

# Request client to send a certificate. If you also want to require it, set
# auth_ssl_require_client_cert=yes in auth section.
#ssl_verify_client_cert = no

# Which field from certificate to use for username. commonName and
# x500UniqueIdentifier are the usual choices. You'll also need to set
# auth_ssl_username_from_cert=yes.
#ssl_cert_username_field = commonName

# How often to regenerate the SSL parameters file. Generation is quite CPU
# intensive operation. The value is in hours, 0 disables regeneration
# entirely.
#ssl_parameters_regenerate = 168

# SSL protocols to use
ssl_min_protocol = TLSv1


# SSL ciphers to use
ssl_cipher_list = EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+RC4:EECDH:EDH+aRSA:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4

# SSL crypto device to use, for valid values run "openssl engine"
#ssl_crypto_device =
```
-rw------- 1 root root 492 Nov  9 12:13 /etc/dovecot/conf.d/10-ssl-keys.try
```
# This file was automatically installed on 2022-11-09T12:13:42.572538
# PEM encoded X.509 SSL/TLS certificate and private key. They're opened before
# dropping root privileges, so keep the key file unreadable by anyone but
# root. Included doc/mkcert.sh can be used to easily generate self-signed
# certificate, just make sure to update the domains in dovecot-openssl.cnf
ssl_cert = </etc/letsencrypt/live/mail.thurm.de/fullchain.pem
ssl_key = </etc/letsencrypt/live/mail.thurm.de/privkey.pem
```

**Comment by Spitfireap** [comment]
okay, could you try reverting to as it was during install and add read perm to `10-ssl-keys.try` perhaps ?

**Comment by felixlberg** [comment]
ok done...

-rw-r--r-- 1 root root 2154 Nov 10 13:28 /etc/dovecot/conf.d/10-ssl.conf
```
!include_try = /etc/dovecot/conf.d/10-ssl-keys.try
#ssl_cert = </etc/letsencrypt/live/mail.thurm.de/fullchain.pem
#ssl_key = </etc/letsencrypt/live/mail.thurm.de/privkey.pem
```
-rw-r----- 1 root root 492 Nov  9 12:13 /etc/dovecot/conf.d/10-ssl-keys.try

`sudo service dovecot restart`

Same error:
```
Nov 10 13:40:24 mail dovecot: imap-login: Error: Failed to initialize SSL server context: Can't load SSL certificate (ssl_cert setting): The certificate is empty: user=<>, rip=85.57.72.163, lip=178.63.61.109, session=<2SlJ6h3t9lRVOUij>
```

**Comment by felixlberg** [comment]
ok done...

-rw-r--r-- 1 root root 2154 Nov 10 13:28 /etc/dovecot/conf.d/10-ssl.conf
```
!include_try = /etc/dovecot/conf.d/10-ssl-keys.try
#ssl_cert = </etc/letsencrypt/live/mail.thurm.de/fullchain.pem
#ssl_key = </etc/letsencrypt/live/mail.thurm.de/privkey.pem
```
-rw-r----- 1 root root 492 Nov  9 12:13 /etc/dovecot/conf.d/10-ssl-keys.try

`sudo service dovecot restart`

Same error:
```
Nov 10 13:40:24 mail dovecot: imap-login: Error: Failed to initialize SSL server context: Can't load SSL certificate (ssl_cert setting): The certificate is empty: user=<>, rip=xxx, lip=xxx, session=<asadad>
```

**Comment by Spitfireap** [comment]
Okay, thanks. Could you apply the workaround manually then (delete your current `10-ssl-keys.try`)

**Comment by Spitfireap** [comment]
nevermind, there is now `=` in include_try. Will push a fix

**Comment by felixlberg** [comment]
How you mean to apply it manually?

I have now setup an new instance and this bug is definitely reproducible...

**Comment by felixlberg** [comment]
Ahh ok so without the = sign?

**Comment by Spitfireap** [comment]
yes :)

**Comment by Spitfireap** [comment]
A fix has been added to modoboa-installer.

**Comment by samuraikid0** [comment]
> Today I installed modoboa on a Debian 11.6.0 with the modoboa-installer and cannot delete any email accounts. I get the following error: Error in configuration file /etc/dovecot/conf.d/10-ssl-keys.try line 6: ssl_cert: Can't open file /etc/letsencrypt/live/MYDOMAIN.COM/fullchain.pem: Permission denied\n. Do i need to do some extra steps or it should normal work with the newest installer?
> 
> Edit: after i set it manually it works now -> chown root:root /etc/dovecot/conf.d/10-ssl-keys.try chmod 0600 /etc/dovecot/conf.d/10-ssl-keys.try
> 
> sudo service dovecot restart

Your solution fixed my problem

Cheers

**Comment by softwarecreations** [comment]
> Today I installed modoboa on a Debian 11.6.0 with the modoboa-installer and cannot delete any email accounts. I get the following error: Error in configuration file /etc/dovecot/conf.d/10-ssl-keys.try line 6: ssl_cert: Can't open file /etc/letsencrypt/live/MYDOMAIN.COM/fullchain.pem: Permission denied\n. Do i need to do some extra steps or it should normal work with the newest installer?
> 
> Edit: after i set it manually it works now -> chown root:root /etc/dovecot/conf.d/10-ssl-keys.try chmod 0600 /etc/dovecot/conf.d/10-ssl-keys.try

I also encountered this issue, debugged it etc and came to the same solution, though restarting dovecot is unnecessary.
I'll PR a fix to the installer.

**Comment by softwarecreations** [comment]
@Assambra @samuraikid0 I made a PR https://github.com/modoboa/modoboa-installer/pull/489
