### ISSUE TITLE
Calendar issues

### ISSUE THREAD

**Issue by gsloop** [modoboa/modoboa#2571]
# Impacted versions

* Ubuntu 20.04 and 22.04
* Database Type: PostgreSQL
* Database version: X.y
* Modoboa: 2.0.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Regular script install using defaults.
Create a new domain, and a simple user in that domain.

Login as that "simple user" into the UI.
Via the UI, nav to the Calendar.
(I think it's "normal" for there to be no default calendar, but perhaps not. But that is the state a simple user sees when first logging in and viewing "Calendars"

Since there's no default calendar, you have to create a "+New Calendar"
Creating a new Calendar appears to work ok. You can name it and set its color.

However if you try to add an entry to the calendar, you can enter the entry details and then click "Save" and nothing occurs.
No UI response, no entry is created.

Nginx sees this;
"POST /api/v1/user-calendars/1/events/ HTTP/1.1" 500 870 "https://server-fqdn-or-ip/calendars/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"

So, it looks like UWSGI / Nginx are responding with a 500 return code, but nothing occurs.

This also appears to occur if you attempt to "edit" the calendar itself, to change its name or color.
When you attempt to save the change, the UI does nothing.

Tested initially under Ubuntu 22.04, then wondering if it were some other strange bug that only occurs in 22.04, installed a test setup under 20.04 and the behavior is the same.

**Comment by tonioo** [comment]
@gsloop Can you set the DEBUG variable to True inside settings.py, reload uwsgi and check your browser console to catch the response of the request which comes back with a 500 code ?

**Comment by gsloop** [comment]
If it would be really helpful, I could provide you access to a VPS with an install you could tinker with. (If you have a VM, though, that's probably better, snapshots etc.) 
I'd just like to make it as straight-forward to figure out as possible, since I'm pretty lost in where to start to resolve this problem.

**Comment by gsloop** [comment]
Some additional details and a possible solution in one case:
1) On Ubuntu 22.04, an issue with supervisord/policyd causes suervisord not to start. A very tentative fix (see: https://github.com/modoboa/modoboa/issues/2561) appears to resolve this. (As noted in the comments, I'm not at all sure the "fix" is a good idea. But I did test it and it *appears* to work. Confirmation from Tonio or someone very familiar with the code would be a very good next step.) After the fix, supervisord starts, and the calendar issues vanish - on 22.04 ONLY!

2) On 20.04 the supervisord problem doesn't exist, but the same kinds of nginx 500 responses occur. (Same symptoms, perhaps different causes.) I don't know if it matters, but the test Ubuntu 20.04 setup I did is on a VM, and I'm accessing the Web UI via an IP address, not a FQDN. (I mod the nginix available sites and uwsgi configuration so it allows this.) It would be super helpful if someone knowledgeable could weigh in on whether this could cause the same symptoms.

**Comment by gsloop** [comment]
This probably needs to get split into two issues.

I did a bunch of testing on Ubuntu 22.04.4 and I can't get calendaring to work in ANY situation. I get 500 responses in the logs from uwsgi and nginx, but setting [debug = true] in doesn't result in any debug output in the web UI. Checks of all the other logs (sysog/supervisord/nginx/uwsgi/etc) don't show anything that looks interesting (other than the 500 http responses.)

In my test setup, I also configured things so I could simply use mail.somedomain.com - rather than an IP or hacking the 3rd level domain.

I still have these VM's with some snapshots - so I can go back and test some things, if someone can come up with some suggestions.

My biggest question is: Has anyone gotten calendars to work on 20.04

**Comment by Spitfireap** [comment]
Hey, so I managed to find time to test it, I do have the same issue if I run it with a self-signed certificate.

Here is the error 
```
SSLError at /api/v1/user-calendars/

HTTPSConnectionPool(host='mail.test.domain.tld', port=443): Max retries exceeded with url: /radicale/test%40test.domain.tld/drkshbg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))
```

Are you using let's encrypt or not ?

**Comment by gsloop** [comment]
Update.
I finally had time to go re-produce a clean install environment and test the proposed fix by @Spitfireap.
It works. (And I haven't seen any undue side-effects.)

Until a patch gets merged into the base setup, this should "fix" it on **Ubuntu 22.04 ONLY**
[All other distros and versions are untested. You should verify all details before proceeding, and use at your own risk.]

cp /srv/modoboa/env/lib/python3.10/site-packages/modoboa_radicale/backends/caldav_.py /srv/modoboa/env/lib/python3.10/site-packages/modoboa_radicale/backends/caldav_.py.bak

sed -i 's/username=username, password=password)/username=username, password=password, ssl_verify_cert=False)/' /srv/modoboa/env/lib/python3.10/site-packages/modoboa_radicale/backends/caldav_.py

**Comment by Spitfireap** [comment]
I have tested it on Ubuntu (20.04) and Debian, but this is not distro dependent, it rather depends on how you generate your self-signed cert. 
Installer method should not be used for prod environment as it is not a full chain certificate ! so you could say that the fix on this side is not really necessary.
On the other hand, if you install through the installer, or even follow closely the tutorial on the documentation, your system's hostname will be set to ``mail.example.com``. This means that a dig will answer ``127.0.1.1``, meaning it is safe to not verify the cert in any condition (if it's server calling itself - present case -). 
Even if we take into account *special* install where people mess with some stuff (like dns), your machine hostname MUST (in a RFC meaning) have its hostname set to the right hostname, so I'm in favor for simply applying this patch globally.

**Comment by gsloop** [comment]
@Spitfireap
I agree the principle of the fix applies to any distro. However the exact fix I gave above relies on a specific python version etc - and I've only tested on Ubuntu 22.04. (All the controlled/careful testing I've done is on 22.04)

**Comment by gsloop** [comment]
I've done a bunch of additional testing, and while I don't know exactly what's going on, I still have a case where, EVEN AFTER APPLYING THE "ssl_verify_cert=False" mod above, I still can't EDIT a calendar name.

I can create an initial calendar, but can't edit the name/color after creating it.
I quite sure there's some "interesting" interaction with DNS.

For example. 
In a production setup that I'm getting ready for - I can do the modoboa setup using mail.a.com.
But I intend the server to handle mail.b.com (once we go live)
I have real DNS records for mail.a.com but not the mail.b.com (mail.b.com conflicts with the current server).

So, if I run the modoboa setup for mail.a.com (and use the https://mail.a.com URL) it works. (I can create and then rename calendars.)
However, if I modify nginx and django to allow me to use mail.b.com or the IP address of the server and use those URL's, it fails.

So, somewhere in the code there's some references that depend on live DNS lookups, I think..
