### ISSUE TITLE
opendkim not work

### ISSUE THREAD

**Issue by tate11** [modoboa/modoboa#2602]
# Impacted versions

* OS Type: Ubuntu 20.04
* OS Version: Number or Name
* Database Type: PostgreSQL
* Database version: X.y
* Modoboa: 2.0.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
systemctl status opendkim
● opendkim.service - OpenDKIM DomainKeys Identified Mail (DKIM) Milter
     Loaded: loaded (/lib/systemd/system/opendkim.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2022-09-18 19:11:42 CEST; 9s ago
       Docs: man:opendkim(8)
             man:opendkim.conf(5)
             man:opendkim-genkey(8)
             man:opendkim-genzone(8)
             man:opendkim-testadsp(8)
             man:opendkim-testkey
             http://www.opendkim.org/docs.html
    Process: 2123 ExecStart=/usr/sbin/opendkim -x /etc/opendkim.conf (code=exited, status=78)

# Current behavior
Sep 18 19:11:41 mail opendkim[2120]: opendkim: /etc/opendkim.conf: dsn:pgsql://opendkim:AUgSEhrWj0FyTMCc@127.0.0.1:5432/modoboa/table=dkim?keycol=domain_name?datacol=id: dkimf_db_open(): Invalid argument
Sep 18 19:11:41 mail systemd[1]: opendkim.service: Control process exited, code=exited, status=78/CONFIG
Sep 18 19:11:41 mail systemd[1]: opendkim.service: Failed with result 'exit-code'.
Sep 18 19:11:41 mail systemd[1]: Failed to start OpenDKIM DomainKeys Identified Mail (DKIM) Milter.
Sep 18 19:11:42 mail systemd[1]: opendkim.service: Scheduled restart job, restart counter is at 3.
Sep 18 19:11:42 mail systemd[1]: Stopped OpenDKIM DomainKeys Identified Mail (DKIM) Milter.
Sep 18 19:11:42 mail systemd[1]: Starting OpenDKIM DomainKeys Identified Mail (DKIM) Milter...

# Expected behavior

# Video/Screenshot link (optional)

**Comment by Spitfireap** [comment]
What is the output of `sudo netstat -tlnup | grep 5432` plz? And have you try a reboot after install 😁?

**Comment by tate11** [comment]
> What is the output of `sudo netstat -tlnup | grep 5432` plz? And have you tried a reboot after install 😁?

root@mail:~# sudo netstat -tlnup | grep 5432
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      477/postgres
And have you tried a reboot after install  Yes

**Comment by tonioo** [comment]
@tate11 Can you try to remove the ":5432" part from the postgres connection string in opendkim configuration file and try again please?

**Comment by tate11** [comment]
> @tate11 Can you try to remove the ":5432" part from the postgres connection string in opendkim configuration file and try again please?

opendkim.conf
KeyTable		dsn:pgsql://opendkim:AUgSEhrWj0FyTMCc@127.0.0.1/modoboa/table=dkim?keycol=id?datacol=domain_name,selector,private_key_path
SigningTable		dsn:pgsql://opendkim:AUgSEhrWj0FyTMCc@127.0.0.1/modoboa/table=dkim?keycol=domain_name?datacol=id

service opendkim status
● opendkim.service - OpenDKIM DomainKeys Identified Mail (DKIM) Milter
     Loaded: loaded (/lib/systemd/system/opendkim.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-09-19 10:14:01 CEST; 5s ago
       Docs: man:opendkim(8)
             man:opendkim.conf(5)
             man:opendkim-genkey(8)
             man:opendkim-genzone(8)
             man:opendkim-testadsp(8)
             man:opendkim-testkey
             http://www.opendkim.org/docs.html
    Process: 3123 ExecStart=/usr/sbin/opendkim -x /etc/opendkim.conf (code=exited, status=0/SUCCESS)
   Main PID: 3134 (opendkim)
      Tasks: 6 (limit: 9479)
     Memory: 2.9M
     CGroup: /system.slice/opendkim.service
             └─3134 /usr/sbin/opendkim -x /etc/opendkim.conf

Sep 19 10:14:01 mail.uzmantem.com systemd[1]: Starting OpenDKIM DomainKeys Identified Mail (DKIM) Milter...
Sep 19 10:14:01 mail.uzmantem.com systemd[1]: Started OpenDKIM DomainKeys Identified Mail (DKIM) Milter.
Sep 19 10:14:01 mail.uzmantem.com opendkim[3134]: OpenDKIM Filter v2.11.0 starting (args: -x /etc/opendkim.conf)

Yes it finally worked
Thank you for your support

**Comment by stefaweb** [comment]
Hi!

I seem to have the same type of problem with a fresh 2.0.1 install.

I removed port ":5432" in /etc/opendkim.conf file and everything is ok now.

Regards,

**Comment by tonioo** [comment]
I fixed the DSN syntax:
https://github.com/modoboa/modoboa-installer/commit/47a5d29043019fac5264a17f0350e53a7638414c
