### ISSUE TITLE
"Default password scheme" missing after fresh install

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#2603]
# Impacted versions

* OS Type: Debian
* OS Version: bullseye
* Database Type: PostgreSQL
* Database version: 13.8-0+deb11u1
* Modoboa:2.0.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

# Current behavior

Hello,

I installed the latest version of Modoboa on a Debian bullseye server with the modoboa-installer script.

At the exit of the installation, the encryption methods are missing in the administration interface v1 for "Default password scheme". In the v2 interface, the methods are all present but the modification of the default method is not saved when it is changed.

# Video/Screenshot link (optional)

![sc](https://user-images.githubusercontent.com/12907102/191456225-88941bc3-5812-4b49-8ea4-d3a58cbed689.png)

![sc1](https://user-images.githubusercontent.com/12907102/191456264-f06af4f5-a34d-4346-9722-6b150143439e.png)

**Comment by Spitfireap** [comment]
Hi, 

Could you check this : `sudo -u modoboa doveadm pw -l` if it returns anything?

You might need to use `sudo usermod -a -G dovecot modoboa` (see #1731).

**Comment by stefaweb** [comment]
Hi!

sudo -u modoboa doveadm pw -l
doveconf: Fatal: Error in configuration file /etc/dovecot/conf.d/10-ssl.conf line 15: ssl_cert: Can't open file /etc/letsencrypt/live/mail.aweb.fr/fullchain.pem: Permission denied

lrwxrwxrwx 1 root root 41 Sep 20 12:42 /etc/letsencrypt/live/mail.aweb.fr/fullchain.pem -> ../../archive/mail.aweb.fr/fullchain1.pem

-rw-r--r-- 1 root root 5583 Sep 20 12:42 fullchain1.pem

/etc/letsencrypt/ and etc/letsencrypt/archives/ are 755.

drwxr-xr-x 9 root     root      4096 Sep 21 10:14 letsencrypt
drwxr-xr-x 3 root     root      4096 Sep 20 12:42 archive

doveadm pw -l
SHA1 SSHA512 SCRAM-SHA-256 BLF-CRYPT PLAIN HMAC-MD5 OTP SHA512 SHA DES-CRYPT CRYPT SSHA MD5-CRYPT PLAIN-MD4 PLAIN-MD5 SCRAM-SHA-1 SHA512-CRYPT CLEAR CLEARTEXT ARGON2I ARGON2ID SSHA256 MD5 PBKDF2 SHA256 CRAM-MD5 PLAIN-TRUNC SHA256-CRYPT SMD5 DIGEST-MD5 LDAP-MD5


"usermod -a -G dovecot modoboa"do not change error message or the problem in GUI.

**Comment by Spitfireap** [comment]
ok, so for your first error, can you check this : #2570 ? There are the commands needed to fix it. Then reboot, then retry the `sudo -u modoboa doveadm pw -l` and check the GUI if it works :)

**Comment by stefaweb** [comment]
Thanks a lot.

All is fine now. Values are back on the GUI and doveadm now work with modoboa user.

In v2 admin GUI, save still do not work for "Default password scheme". Mods are still not saved.

Regards,

**Comment by Spitfireap** [comment]
Thanks for the feedback. There are some fixes regarding settings save for V2 that are not yet published. Would you mind opening the dev console of the browser and check the response code when you save settings in v2 ? :)

**Comment by stefaweb** [comment]
I got this when I click on the Save button.

```
Failed to load resource: the server responded with a status of 400 (Bad Request)
https://mail.aweb.fr/api/v2/parameters/core/
```

**Comment by Spitfireap** [comment]
Thanks, so it should be fixed with next release
