### ISSUE TITLE
Opendkim A DNS record has been found but its syntax is not valid: Public key mismatchs

### ISSUE THREAD

**Issue by tate11** [modoboa/modoboa#2610]
# Impacted versions

* OS Type: Ubuntu
* OS Version:  20.04
* Database Type: PostgreSQL
* Database version: 12
* Modoboa: 2.0.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by stefaweb** [comment]
Hello,

I have the same concern. The public key in modoboa seems to change on its own and no longer corresponds to the one entered in the DNS. No yet found how this is happening.

**Comment by stefaweb** [comment]
I found the problem. I fooled myself with my curiosity to click everywhere. ;)

If you click on the small button, it generates a new key.

![sc](https://user-images.githubusercontent.com/12907102/191930547-ee03a7bc-b9f4-4173-93a5-7277e5a2c740.png)

It would be nice to have a confirmation "Are you sure you want to generate a new key?" when you click on this button.

**Comment by tate11** [comment]
> I found the problem. I fooled myself with my curiosity to click everywhere. ;)
> 
> If you click on the small button, it generates a new key.
> 
> ![sc](https://user-images.githubusercontent.com/12907102/191930547-ee03a7bc-b9f4-4173-93a5-7277e5a2c740.png)
> 
> It would be nice to have a confirmation "Are you sure you want to generate a new key?" when you click on this button.


I think the problem is the new web admin.
I made the old web admin opendkim settings and it worked
