### ISSUE TITLE
Missing sitestatic/bootstrap/dist/css/bootstrap.min.css.map

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#2612]
# Impacted versions

* OS Type: Debian
* OS Version: bullseye
* Database Type: PostgreSQL
* Database version: 13.8-0+deb11u1
* Modoboa:2.0.1
* installer used: Yes
* Webserver: Nginx

# Current behavior

Hello,

When a page loads in the GUI v1, we systematically have this call to a css which is not found.

Failed to load resource: the server responded with a status of 404 (Not Found)
https://mail.xxxx.fr/sitestatic/bootstrap/dist/css/bootstrap.min.css.map

A "locate bootstrap.min.css.map" found nothing.

```
root@mailhub:/srv/modoboa# ll /srv/modoboa/instance/sitestatic/css/
total 52
-rw-r--r-- 1 modoboa modoboa  4370 Sep 20 12:31 custom.css
-rw-r--r-- 1 modoboa modoboa    80 Sep 20 12:31 jquery.sortable.css
-rw-r--r-- 1 modoboa modoboa   226 Sep 20 12:31 login.css
-rw-r--r-- 1 modoboa modoboa   550 Sep 20 12:31 logo-icon.png
-rw-r--r-- 1 modoboa modoboa 13670 Sep 20 12:31 modoboa.png
-rw-r--r-- 1 modoboa modoboa   630 Sep 20 12:31 offline.css
-rw-r--r-- 1 modoboa modoboa   348 Sep 20 12:31 searchbar.css
-rw-r--r-- 1 modoboa modoboa  2545 Sep 20 12:31 spinner.gif
-rw-r--r-- 1 modoboa modoboa  2485 Sep 20 12:31 viewmail.css

```

**Comment by Spitfireap** [comment]
Hi, the file is accessible, no issue. The .map file [is only for debugging purposes](https://stackoverflow.com/questions/21773376/bootstrap-trying-to-load-map-file-how-to-disable-it-do-i-need-to-do-it). 
If you really want to delete this warning, delete the `/*# sourceMappingURL=bootstrap.min.css.map */` at the end of `{modoboa_venv}/lib/python/site-packages/modoboa/bower_components/bootstrap/dist/css/bootstrap.min.css`

**Comment by stefaweb** [comment]
Hello,

If it's normal, we can close the issue then.

Regards,
