### ISSUE TITLE
MX check stale with some domain

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#2614]
# Impacted versions

* OS Type: Debian
* OS Version: bullseye
* Database Type: PostgreSQL
* Database version: 13.8-0+deb11u1
* Modoboa:2.0.1
* installer used: Yes
* Webserver: Nginx

# Current behavior

Hello,

Another problem with 2.0.1.

I configured the MX test to check the IP MX of domains that point to the modoboa server.

I have the first domain that does not want to update.

It remains as in the screenshot.

![sc](https://user-images.githubusercontent.com/12907102/192089993-fff134ac-a355-43d0-a394-298c7d969d6d.jpg)

If I run this command manually, it runs without error message.

```
sudo -u modoboa -i
/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py modo check_mx
```

**Comment by Spitfireap** [comment]
Perhaps your server cached the DNS before it propagated ? What is the output of something like `dig YOURDOMAIN mx` from your server ?

**Comment by stefaweb** [comment]
dig mx is ok. This si staled since yesterday.

I may be able to delete the files to restart from scratch?

**Comment by Spitfireap** [comment]
Honestly, no clue why it doesn't work. Could you try going to this domain administration page so you can get it's ID in the url, then try adding --domain ID to see if it doesn't respond with any error (`/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py modo check_mx --domain ID`)

**Comment by stefaweb** [comment]
NO message when I run the command.

`/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py modo check_mx --domain 8`

No error in the navigator console except the missing bootstrap.min.css.map.

If I remove the IP in the admin MX check window, the is system work.

![sc](https://user-images.githubusercontent.com/12907102/192092587-7684505f-e0e8-4294-98a0-17aeb3e5ca03.jpg)

(the "delete" sentence was for rdd files...)

**Comment by stefaweb** [comment]
Hello,

Still trying to find the problem source.

Do we have a possibility to have verbose log somewhere?

May be, a --debug optional command will be nice to add to the "modo check_mx" command.

```
usage: manage.py modo check_mx [-h] [--no-dnsbl] [--email EMAIL] [--skip-admin-emails] [--domain DOMAIN] [--timeout TIMEOUT] [--ttl TTL]

optional arguments:
  -h, --help           show this help message and exit
  --no-dnsbl           Skip DNSBL queries.
  --email EMAIL        One or more email to notify
  --skip-admin-emails  Skip domain's admins email notification.
  --domain DOMAIN      Domain name or id to update.
  --timeout TIMEOUT    Timeout used for queries.
  --ttl TTL            TTL for dns query.
```

**Comment by Spitfireap** [comment]
> If I remove the IP in the admin MX check window, the is system work.

What do you mean exactly ? You deactivated mx check ?

**Comment by stefaweb** [comment]
Hello,

I will try to explain the problem again.

In the administration interface, I activated the MX control and entered the IP of the Modoboa server which will be the future MX.

![sc5](https://user-images.githubusercontent.com/12907102/192210467-671feb75-5be3-467e-bbbc-700caa1471b2.png)

I have a domain defined in modoboa. Its MX does not yet point to the IP of the Modoboa server (it is still on the old mail server). The DKIM for this net domain also not good.

In the v1 interface, this domain remains in "Awaiting validation".

![sc1](https://user-images.githubusercontent.com/12907102/192209663-472ac5d4-1dee-4fa9-bcaf-f6954786ca6a.png)

![sc2](https://user-images.githubusercontent.com/12907102/192209976-90830eef-26b8-4796-a39c-92f1f664e4ee.png)

In the v2 interface, it is "Pending".

![sc3](https://user-images.githubusercontent.com/12907102/192209999-16e281ca-9f4c-4798-a4bf-b5e1b013dcb8.png)

The status does not change even if we wait for hours. Launching the "modo check_mx" command by hand does not change anything.

In the v2 interface, the MX record and DKIM control are green when it is not good.

![sc4](https://user-images.githubusercontent.com/12907102/192210280-9e07c9ce-a969-4bcd-9a55-ac83a0264a50.png)

If I remove the IP from the MX in the administration, the display changes.

![sc6](https://user-images.githubusercontent.com/12907102/192211669-e9bd95a1-1e81-4917-8208-3662d1dab794.png)

![sc7](https://user-images.githubusercontent.com/12907102/192212974-66d91199-6597-4b61-95a6-dbeda1874b61.png)

![sc8](https://user-images.githubusercontent.com/12907102/192212998-18320136-05d1-4a5d-ade4-2e4f739c85c7.png)

![sc9](https://user-images.githubusercontent.com/12907102/192212720-a42353f6-66f0-4afc-a676-7b969800ef1a.png)

![sc10](https://user-images.githubusercontent.com/12907102/192212738-8bc6620b-9431-4e17-ab19-18173ee68541.png)

I hope that it's clearer.

Regards,

**Comment by Spitfireap** [comment]
Merci !

I'll try to provide a fix :).

**Comment by Spitfireap** [comment]
Ok so after a quick review : it is intended behavior that if your dns has no valid MXs (which is the case when you set the "MX(s) valide(s)", and that the domain was created less than 24H ago you have a grace period to set them. You can wait 24H and check again, you then should have an alarm about wrong MXs.

For the V2 issue, I'm looking at it :D.

**Comment by Spitfireap** [comment]
As for DKIM, just to be clear : You enabled DKIM in the domain's settings ? Have you set the same selector as your current one ? Is it currently set with the wrong key or it has no key at all in your DNS currently ? Thanks !

**Comment by stefaweb** [comment]
DKIM is activated for the domain. The key is generated by moboba and available on the GUI v1 and v2.

The curent DKIM in DNS for the domaine is not the same key (old key from the old server, as mx).

Your welcome.

**Comment by Spitfireap** [comment]
Okay, would you mind removing any IPs from validated MXs, then do the check_mx and check again ?

**Comment by stefaweb** [comment]
IP removed.

check_mx run again

For the "pending" domain now:

MX signal is green (but IP/name not good as well when we click on the green icon). In GUIv2, first icon in domain list is red (Problem). Inside domain window, all is green.

DKIM signal is yellow (Public key mismatchs) in GUIv1. Green in GUIv2.

**Comment by stefaweb** [comment]
> Ok so after a quick review : it is intended behavior that if your dns has no valid MXs (which is the case when you set the "MX(s) valide(s)", and that the domain was created less than 24H ago you have a grace period to set them. You can wait 24H and check again, you then should have an alarm about wrong MXs.

HI!

Its fine this morning.

![sc](https://user-images.githubusercontent.com/12907102/192453857-b700cb53-2025-4947-98bd-04823375df43.png)
