### ISSUE TITLE
Admins input fields empty in GUI v2.

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#2623]
# Impacted versions

* OS Type: Debian
* OS Version: bullseye
* Database Type: PostgreSQL
* Database version: 13.8-0+deb11u1
* Modoboa: 2.0.2
* installer used: Yes
* Webserver: Nginx
* Navigator: Safari OSX, Chrome OSX

# Current behavior

Hello,

In the v2 interface all input fields are empty. They do not take the values from the database as in the v1 interface.

![v1](https://user-images.githubusercontent.com/12907102/193359134-165d3ca9-e965-4014-9d2e-9c9dfa9e4c4e.png)

![v2](https://user-images.githubusercontent.com/12907102/193359138-8e58eda9-a688-484f-9859-d522a81ee0f7.png)

**Comment by tonioo** [comment]
@stefaweb There might be some API calls failing... Could you check your web browser console?

**Comment by stefaweb** [comment]
HI Tony,

I got this in browser console.

Cheers,

![sc](https://user-images.githubusercontent.com/12907102/200288751-ec426c3e-e05a-40ca-8d18-f64813db2ad7.png)

**Comment by stefaweb** [comment]
I switched GUI to English. No change. Fields still empty.

**Comment by tonioo** [comment]
@stefaweb Check the Network tab please

**Comment by tonioo** [comment]
And if you click on the one containing core, what is the payload returned by the API ?

**Comment by stefaweb** [comment]
I got this for "core":

```
Réponse
HTTP/1.1 200 OK
Content-Type: application/json
Content-Language: en
Connection: keep-alive
Date: Mon, 07 Nov 2022 16:45:09 GMT
X-Frame-Options: SAMEORIGIN
Content-Length: 1684
Vary: Accept, Accept-Language, Cookie
Server: nginx/1.18.0
Allow: GET, PUT, HEAD, OPTIONS
```

**Comment by Spitfireap** [comment]
Hi @stefaweb, any news on this issue ? Is it working now ?
