### ISSUE TITLE
New install loses Admin functions - Can't configure Modoboa

### ISSUE THREAD

**Issue by SaintShaggy** [modoboa/modoboa#2627]
Fresh install through Modoboa installer pulled yesterday, on Ubuntu 20.04. Initial setup of a domain is successful. After changing the admin password, and logging back into the web interface, the admin functions for Modoboa are not present, and the button to add a domain is missing.

After one new identity and two alias were created, now receiving the error message of maximum alias  and Mailboxes: limit reached. Since I can't get into the modoboa settings, I can't look for the configuration setttings.

Any direction on how to 'refresh' or re-deploy access to admin@mail.domain.com account to restore?

![ModoboaNDM](https://user-images.githubusercontent.com/57743611/194185303-b65ba287-4381-4205-a776-aa81ef52e037.png)

![NoModoboaAdmin](https://user-images.githubusercontent.com/57743611/194185067-3028b167-61a5-4dec-bc0f-0f79ae391754.png)

**Comment by tonioo** [comment]
@SaintShaggy Looks like you downgraded the default superadmin account to a domain admin one... Are you sure this is the only user you have?

**Comment by SaintShaggy** [comment]
...weirdness, I will take the blame. For some reason I couldn't log in as 'Admin' but only 'admin@mydomain.com' from my laptop. I was able to log in as Admin from my PC, and have the appropriate permissions. I have made an additional SuperAdmin user and am no longer stuck. Thank you,
