### ISSUE TITLE
Change domain name in domain account operation

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#2628]
# Impacted versions

* OS Type: Debian
* OS Version: Bullseye
* Database Type: PostgreSQL
* Database version: 13.8-0+deb11u1
* Modoboa: 2.0.2
* installer used: Yes
* Webserver: Nginx
* Navigator: Safari OSX, Chrome OSX

# Current behavior

Hello,

I noticed that you could change the original domain name to a domain account.

When changing the domain name, the domain directory name in /srv/vmail/ does not change according to the new value.

```
# ll  /srv/vmail/
total 12
drwx------ 3 vmail vmail 4096 Sep 22 09:55 domain.tld
```

Is this normal operation or a bug?

Regards,

![sc](https://user-images.githubusercontent.com/12907102/194354527-8aa39109-4c5c-410d-b0df-377fef6a6c99.png)

![sc2](https://user-images.githubusercontent.com/12907102/194354612-c7e4cac3-71e6-44f9-a0ea-233e7d6bf51c.png)

**Comment by tonioo** [comment]
It should be renamed if the associated cron job is enabled and if dovecot is on the same server than modoboa

**Comment by tonioo** [comment]
@stefaweb up
