### ISSUE TITLE
Bug on new interface DKIM key

### ISSUE THREAD

**Issue by CptGroot** [modoboa/modoboa#2629]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 20.04.5
* Database Type: MySQL
* Database version: Ver 15.1 Distrib 10.3.34-MariaDB
* Modoboa: 2.0.2
* installer used: Yes
* Webserver: Nginx

# Old interface
If you display the DEKIM-Key it shows it in the right way:
![2](https://user-images.githubusercontent.com/115283625/194612245-673867c6-ce98-4a62-876e-bdb18f49e0f4.png)

# New interface
First of all the first part is in one line. And then it should be _domainkey and not _domain_key
![1](https://user-images.githubusercontent.com/115283625/194612665-204049ed-20fe-4277-8791-9ce8c17be015.png)

Thanks for all :D

**Comment by Spitfireap** [comment]
Hi, thanks. Change proposed. As for the line issue, it is already fixed and should be available in next version :)
