### ISSUE TITLE
Internal Server Error after upgrading from Ubuntu 20.04 to 22.04

### ISSUE THREAD

**Issue by luimen6** [modoboa/modoboa#2634]
# Impacted versions

Distribution: Ubuntu
Codename: Jammy after upgrading from Focal
Arch: 64 Bits

# Steps to reproduce
Upgrade from Ubuntu 20.04 to Ubuntu 22.04

# Full trace using --debug option

> Installing clamav
Paketlisten werden gelesen…
Abhängigkeitsbaum wird aufgebaut…
Statusinformationen werden eingelesen…
clamav-daemon ist schon die neueste Version (0.103.6+dfsg-0ubuntu0.22.04.1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Sun Oct 9 18:28:34 2022 -> ClamAV update process started at Sun Oct 9 18:28:34 2022
Sun Oct 9 18:28:34 2022 -> ^Your ClamAV installation is OUTDATED!
Sun Oct 9 18:28:34 2022 -> ^Local version: 0.103.6 Recommended version: 0.103.7
Sun Oct 9 18:28:34 2022 -> DON'T PANIC! Read https://docs.clamav.net/manual/Installing.html
Sun Oct 9 18:28:34 2022 -> daily.cld database is up-to-date (version: 26684, sigs: 2007435, f-level: 90, builder: raynman)
Sun Oct 9 18:28:34 2022 -> main.cvd database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
Sun Oct 9 18:28:34 2022 -> bytecode.cvd database is up-to-date (version: 333, sigs: 92, f-level: 63, builder: awillia2)
Synchronizing state of clamav-daemon.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable clamav-daemon
● clamav-daemon.service - Clam AntiVirus userspace daemon
Loaded: loaded (/lib/systemd/system/clamav-daemon.service; enabled; vendor preset: enabled)
Drop-In: /etc/systemd/system/clamav-daemon.service.d
└─extend.conf
Active: active (running) since Sun 2022-10-09 18:27:52 CEST; 43s ago
Docs: man:clamd(8)
man:clamd.conf(5)
https://docs.clamav.net/
Main PID: 3137 (clamd)
Tasks: 2 (limit: 9406)
Memory: 1.2G
CPU: 12.250s
CGroup: /system.slice/clamav-daemon.service
└─3137 /usr/sbin/clamd --foreground=true
Okt 09 18:28:04 mail clamd[3137]: Sun Oct 9 18:28:04 2022 -> OLE2 support enabled.
Okt 09 18:28:04 mail clamd[3137]: Sun Oct 9 18:28:04 2022 -> PDF support enabled.
Okt 09 18:28:04 mail clamd[3137]: Sun Oct 9 18:28:04 2022 -> SWF support enabled.
Okt 09 18:28:04 mail clamd[3137]: Sun Oct 9 18:28:04 2022 -> HTML support enabled.
Okt 09 18:28:04 mail clamd[3137]: Sun Oct 9 18:28:04 2022 -> XMLDOCS support enabled.
Okt 09 18:28:04 mail clamd[3137]: Sun Oct 9 18:28:04 2022 -> HWP3 support enabled.
Okt 09 18:28:04 mail clamd[3137]: Sun Oct 9 18:28:04 2022 -> Self checking every 3600 seconds.
Okt 09 18:28:35 mail systemd[1]: /lib/systemd/system/clamav-daemon.service:12: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the>
Okt 09 18:28:35 mail systemd[1]: /lib/systemd/system/clamav-daemon.service:12: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the>
Okt 09 18:28:36 mail systemd[1]: /lib/systemd/system/clamav-daemon.service:12: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the>
Traceback (most recent call last):
File "/root/modoboa-installer/./run.py", line 142, in
main(sys.argv[1:])
File "/root/modoboa-installer/./run.py", line 124, in main
scripts.install("amavis", config, args.upgrade)
File "/root/modoboa-installer/modoboa_installer/scripts/init.py", line 22, in install
getattr(script, appname.capitalize())(config, upgrade).run()
File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 156, in run
self.post_run()
File "/root/modoboa-installer/modoboa_installer/scripts/amavis.py", line 97, in post_run
install("clamav", self.config, self.upgrade)
File "/root/modoboa-installer/modoboa_installer/scripts/init.py", line 22, in install
getattr(script, appname.capitalize())(config, upgrade).run()
File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 157, in run
self.restart_daemon()
File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 146, in restart_daemon
system.enable_and_start_service(name)
File "/root/modoboa-installer/modoboa_installer/system.py", line 57, in enable_and_start_service
code, output = utils.exec_cmd("service {} status".format(name))
File "/root/modoboa-installer/modoboa_installer/utils.py", line 72, in exec_cmd
process.wait()
File "/usr/lib/python3.10/subprocess.py", line 1207, in wait
return self._wait(timeout=timeout)
File "/usr/lib/python3.10/subprocess.py", line 1941, in _wait
(pid, sts) = self._try_wait(0)
File "/usr/lib/python3.10/subprocess.py", line 1899, in _try_wait
(pid, sts) = os.waitpid(self.pid, wait_flags)

**Comment by tonioo** [comment]
@luimen6 Is your trace complete?

**Comment by luimen6** [comment]
Yes

**Comment by Spitfireap** [comment]
Hi, 
Just to be sure, what are you trying to do ? Install or upgrade modoboa ? 
Could you do a ``sudo apt reinstall clamav``, then ``sudo systemctl restart clamav-daemon`` and then check with ``sudo systemctl status clamav-daemon`` that the service is running w/o errors. If it works, you can retry to install/upgrade modoboa

**Comment by luimen6** [comment]
@Spitfireap
No I get the following message:

> Okt 13 21:28:30 mail amavis[1109]: Net::Server: Group Not Defined.  Defaulting to EGID '117 117'
Okt 13 21:28:30 mail amavis[1109]: Net::Server: User Not Defined.  Defaulting to EUID '113'
Okt 13 21:28:30 mail amavis[1109]: No $altermime,         not using it
Okt 13 21:28:30 mail amavis[1109]: No ext program for   .zoo, tried: zoo
Okt 13 21:28:30 mail amavis[1109]: No ext program for   .doc, tried: ripole
Okt 13 21:28:30 mail amavis[1109]: No decoder for       .F
Okt 13 21:28:30 mail amavis[1109]: No decoder for       .doc
Okt 13 21:28:30 mail amavis[1109]: No decoder for       .zoo
Okt 13 21:28:30 mail amavis[1109]: Using primary internal av scanner code for ClamAV-clamd
Okt 13 21:28:30 mail amavis[1109]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
Installing modoboa
Paketlisten werden gelesen…
Abhängigkeitsbaum wird aufgebaut…
Statusinformationen werden eingelesen…
build-essential ist schon die neueste Version (12.9ubuntu3).
cron ist schon die neueste Version (3.0pl1-137ubuntu3).
libffi-dev ist schon die neueste Version (3.4.2-4).
libjpeg-dev ist schon die neueste Version (8c-2ubuntu10).
librrd-dev ist schon die neueste Version (1.7.2-3ubuntu6).
rrdtool ist schon die neueste Version (1.7.2-3ubuntu6).
redis-server ist schon die neueste Version (5:6.0.16-1ubuntu1).
supervisor ist schon die neueste Version (4.2.1-1ubuntu1).
libssl-dev ist schon die neueste Version (3.0.2-0ubuntu1.6).
libxml2-dev ist schon die neueste Version (2.9.13+dfsg-1ubuntu0.1).
libxslt1-dev ist schon die neueste Version (1.1.34-4ubuntu0.22.04.1).
python3-dev ist schon die neueste Version (3.10.6-1~22.04).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
User modoboa already exists, skipping creation but please make sure the /srv/modoboa directory exists.
Traceback (most recent call last):
  File "/srv/modoboa/env/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
Traceback (most recent call last):
  File "/srv/modoboa/env/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
Traceback (most recent call last):
  File "/srv/modoboa/env/bin/modoboa-admin.py", line 3, in <module>
    from modoboa.core.commands import handle_command_line
ModuleNotFoundError: No module named 'modoboa'
None

**Comment by Spitfireap** [comment]
Can you explain what are you trying to do ? What I understand is that you had a server running Ubuntu 20.04 and you upgraded to 22.04. Then you tried to install modoboa or upgrade it. Did you have modoboa installed back when you were at version 20.04 ?

**Comment by luimen6** [comment]
After I upgrade from 20.04. on 22.04. I get the message: Internal Server Error

I thought that if I upgrade Modoboa, the bugs will be fixed.

I just played back a Proxmox VM backup with 20.04.

**Comment by Spitfireap** [comment]
Hi, have retried upgrading ?
