### ISSUE TITLE
Small typo in GUI 2.0.2

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#2683]
# Impacted versions

* Modoboa: 2.0.2

# Expected behavior

In the interface, there is an extra dot at the end of "Box alias".

![sc](https://user-images.githubusercontent.com/12907102/200524057-5047a330-bd18-4d42-a391-79a16699320e.jpg)

**Comment by Spitfireap** [comment]
Hi, I've proposed the fix on transifex. 
Feel free to edit the errors you may find directly [here](https://www.transifex.com/tonio/modoboa/). :D
