### ISSUE TITLE
Can't create user via API. Mailboxes: limit reached

### ISSUE THREAD

**Issue by daidaiworm** [modoboa/modoboa#2704]
curl -X POST "https://demo.modoboa.org/api/v2/accounts/" -H  "accept: application/json" -H  "Content-Type: application/json" -H "Authorization: Token 0487bce8b9d1add498fbfbc2127f05703a944bfa" -d "{\"username\":\"y001@demo.local\",\"role\":\"SimpleUsers\"}"

got error: {"mailbox":["Mailboxes: limit reached"]}
Then tried webmail, also enconter this issue.

Searched this project/issues, tried to chang admin@demo.local resources, but it seems not functional.

⚫2022-12-05 15:59 update: 
Microsoft Edge can change resources.
Chore can't.

But still can't add account via API after change resources after using Edge.

**Comment by MrGeneration** [comment]
Seems to be working by now. At least by short test just now worked without issues.

**Comment by tonioo** [comment]
It's very clear but you need to increase allocated resources for your domain and/or account (ie. maximum allowed number of mailboxes that can be created.
