### ISSUE TITLE
Internal error on fresh reinstallation

### ISSUE THREAD

**Issue by yannfill** [modoboa/modoboa#2720]
* OS Type: Arch
* OS Version: Arch
* Database Type: MariaDB
* Database version: 10.9.4
* Modoboa: 2.0.3
* installer used: No
* Webserver: Nginx

Hi,

On a fresh reinstall the the login page is displayed correctly but after logging I get an internal error. With `DEBUG = True` in settings.py, I launch gunicorn with this command:

```
/srv/modoboa/env/bin/gunicorn -c gunicorn.conf.py instance.wsgi:application --log-level debug --access-logfile - --error-logfile -
```

I have no trace on stdout or on the web page, simply internal error on red background.

**Comment by yannfill** [comment]
I'm using python 3.10 in venv.

**Comment by Spitfireap** [comment]
Hi, 
Could you open browser console with `DEBUG = True` and try to log in ? Requests with error should logically have a trace within the response.

**Comment by yannfill** [comment]
All I get is:

```
GET https://modoboa.example.com/dashboard/ [HTTP/2 500 Internal Server Error 2725ms]
Uncaught Error: Bootstrap's JavaScript requires jQuery
Uncaught bootstrap-datetimepicker requires jQuery to be loaded first
```

No usable info in the error 500.

If I try /new-admin everything seems to work fine.

**Comment by Spitfireap** [comment]
Okay, so I guess that if you reload the page without the browser cache, you see a bunch of 404 error (like jquery) ? If so, you might need to re-apply static collection (`python manage.py collectstatic`) and check `STATIC_ROOT` in your `settings.py`.

**Comment by yannfill** [comment]
I always do ctrl-shift-R to flush the browser cache, I see no 404. Error 500 on /dashboard/ and 200 for JS and CSS.

```
$ $ python manage.py collectstatic
0 static files copied to '/srv/modoboa/instance/sitestatic', 2838 unmodified.
```
```
STATIC_ROOT = os.path.join(BASE_DIR, 'sitestatic')
```

**Comment by yannfill** [comment]
Are modoboa.policyd and modoboa.maillog mandatory in MODOBOA_APPS ?

**Comment by Spitfireap** [comment]
policyd is what manage relationship with postfix and maillog is for analyzing logs for the stats. These are not extensions but core feature, so I would leave them there. 

As for the error 500, having `DEBUG = True` should input the trace in the response of the request. Else it might suggest that there is an issue on Nginx side. Have you checked Nginx access logs ?

**Comment by yannfill** [comment]
The error 500 is logged in nginx access log, not error log, so I don't think it's on nginx side. And the internal error seems like a django formatted output.

The thing that I don't understand is, in spite of having `DEBUG = True` in settings.py, `debug = true` and `loglevel = debug` in gunicorn.conf.py, I don't see any error anywhere, not on stdout when using command line or in journald when using systemd unit, or in browser console. If I split gunicorn access and error logs in 2 files, the access log is empty and no error appears in the error log.

Maybe the problem lies between nginx and the gunicorn socket but I don't know how to debug it. It was working a few weeks ago and I don't think anything has changed since then.

**Comment by Spitfireap** [comment]
Yes, If it was on Django side, you would have the traceback. I don't use gunicorn, so I can't really help you on this. Perhaps you could leave the DEBUG to True and restart your server. So you are sure that everything is reloading correctly ? 

> All I get is:
> 
> ```
> GET https://modoboa.example.com/dashboard/ [HTTP/2 500 Internal Server Error 2725ms]
> Uncaught Error: Bootstrap's JavaScript requires jQuery
> Uncaught bootstrap-datetimepicker requires jQuery to be loaded first
> ```
> 
> No usable info in the error 500.

Do you see the POST request directed to /login ?

**Comment by yannfill** [comment]
OK, in fact I was using the wrong settings.py file. I still have error 500 but know I have traces:
```
AttributeError at /dashboard/

module 'collections' has no attribute 'Callable'

    Request Method: GET
       Request URL: https://modoboa.example.com/dashboard/
    Django Version: 3.2.16
    Exception Type: AttributeError
   Exception Value: module 'collections' has no attribute 'Callable'
Exception Location: /srv/modoboa/env/lib/python3.10/site-packages/dateutil/parser.py, line 324, in parse
 Python Executable: /srv/modoboa/env/bin/python
    Python Version: 3.10.9
       Python Path: ['/srv/modoboa/instance',
                     '/srv/modoboa/env/bin',
                     '/usr/lib/python310.zip',
                     '/usr/lib/python3.10',
                     '/usr/lib/python3.10/lib-dynload',
                     '/srv/modoboa/env/lib/python3.10/site-packages']
       Server time: Thu, 29 Dec 2022 16:59:53 +0100
```

**Comment by yannfill** [comment]
Seems related to a change in python 3.10: https://bobbyhadz.com/blog/python-attributeerror-module-collections-has-no-attribute-callable

**Comment by Spitfireap** [comment]
Much better, [so yes](https://github.com/modoboa/modoboa/pull/2677). Simple fix: remove `py-dateutil` from the venv and install `python-dateutil`

**Comment by yannfill** [comment]
Indeed, now everything is working. Than you very much for your help @Spitfireap.
