### ISSUE TITLE
DKIM DNS record suggestion is wrong in 2.0.3

### ISSUE THREAD

**Issue by olaf7** [modoboa/modoboa#2730]
Modoboa 2.0.3
When using the old admin interface the suggested format for a DNS TXT entry  is: modoboa._domainkey
The new admin suggests: domain._domain_key
One of the examples in which the new admin reports things differently, but also troublesome as testing tools expect the standard format as suggested by the old admin interface. The new suggestion seems wrong.
Another example is the fact that new and old admin interfaces report differently on if dmarc, dnsbl, spf, mx, dkim are supported/configured per domain or not (properly).

**Comment by olaf7** [comment]
See your own screenshot at issue #2731 but in my case the domain entry is dkim._domain_key instead of dkim._domainkey which is wrong and troublesome. Please note the default selector is 'modoboa' and not 'dkim' in my instance. Is this globally reconfigurable instead of per domain?

**Comment by Spitfireap** [comment]
Ok, this fix of this has already been merged and should be available in 2.0.4 ;)

**Comment by Spitfireap** [comment]
https://github.com/modoboa/modoboa/commit/de69840507d6e7dadd36f762c8d88bf47872ba11

**Comment by hw-p** [comment]
can someone post right Format for example ? DKIM from modoboa for DNS , how it looks ?

**Comment by olaf7** [comment]
Modoboa provides suggestions in 2 layouts: BIND and clear text. The later is useful when other nameserver software is used or an online DNS provider.

Format v=DKIM1;k=<encryption method>;p=<key>
Example: v=DKIM1;k=rsa;p=MIICWwIBAAKBgQDVTHUiZM8qCVTI12VyfGeK6pYlab55LJV4q0/2kF1D58QW/FOSWdrOIY+Cm1wMMCJeYIoXvjCHubQaJ69lGZq7iGISvl32poIO+9O0RZnkm/RqIWF0y3U3rPt63XxdhcK7bZk6kVUvo77uYeITJ05x0FSods4zT1JNhJI8fJJuVwIDAQABAoGASr1Dvg182cnzP3zaO0eEMJUKj4mCCIuqxGGi306un4CyoStBTWLW3Ku90ZIGqu6i3FcPjEpETwqvJQsK1m4mXTQBV9bLRe5/wbXh3D/DAtL/vr8IyIAZkAiS87XGW5csrXw4uVHaLiWDHvJNdbDEGZowh0afGMbRqOqIIxr5NEECQQDzonbRX+VGfcd/c575pzmv4ZgS92QSGWQnMn5BNxR1JaGZNKkZ4jR1FrB4B2O1m1ipOGysoTMc0wUHBNy5jo1vAkEA4B/W382iJN6Y2NzqbRZyIn27SJyMUmseorEVIK84PJ9eIkUGW1yveCFCFteyoUJBWUvuHur3qK6kb6DAzYkJmQJAcoSaHv5ZUdILdPAO+MBO0EpU5g1c/1jqB7anO9Y9Cnd+xvnGxoDaMXNRzYmDp7h2a0w3YMmAsfrKcSsq6RmFhwJAKubNWd/h9s7JUVHQaftO870/mWGmFqy8m4XsNmp0CF61RTgTRG/UgtlS7k5xuh6VpcM8HJz7tUVg4qFR5sYhmQJAb7C7uJAGycbxmNemTl5VeSafkgerwz84J9/g/y03pGy0zBV1YVZijXN5BVi4dlQVvh/mSJcNC0VUeExjl/Etgg==

**Comment by ZombiePm** [comment]
I do it all on example. whats wrong?

<img width="753" height="384" alt="Image" src="https://github.com/user-attachments/assets/e7ec261a-8475-4cfa-890f-3662a6e11167" />

check it added all tree: 
dig TXT modoboa._domainkey.mydomain.com +short
"v=DKIM1;k=rsa;p=MIGfMA0GCSq.....
dig TXT modoboa._domainkey.mail.mydomain.com +short
"v=DKIM1;k=rsa;p=MIGfMA0GCSq.....
dig TXT modoboa._domainkey.mail.mail.mydomain.com +short
"v=DKIM1;k=rsa;p=MIGfMA0GCSq.....


Why i see DKIM record not found ?
