### ISSUE TITLE
DKIM show key in 2.0.3 does not show the raw key

### ISSUE THREAD

**Issue by olaf7** [modoboa/modoboa#2731]
DKIM key in old admin interface shows both BIND and RAW versions of the DKIM key
The new admin interface only shows the BIND variety, which is not helpful for hosted DNS

**Comment by Spitfireap** [comment]
Hi, 

Could you share a screenshot of this issue ? I do not encounter it : 
![image](https://user-images.githubusercontent.com/45575529/210214662-ad4c925e-f347-46a9-8d10-994f2e7e0078.png)

**Comment by olaf7** [comment]
Weird. Now it does show. But for some reason all on a single line and not as in your example screenshot.
Issue can be closed I guess. Sorry for the fuss.
