### ISSUE TITLE
`modo` management command does not support Django default args (notably --verbosity)

### ISSUE THREAD

**Issue by bernd-wechner** [modoboa/modoboa#2737]
# Impacted versions

* Modoboa: 2.0.3

# Current behavior

try this: 

```$ python manage.py --verbosity 3 modo
Unknown command: '--verbosity'
Type 'manage.py help' for usage.
```
# Expected behavior

Expect all commands and subcommands to honor the tips provided by help:

```
 python manage.py help modo
usage: manage.py modo [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS] [--pythonpath PYTHONPATH] [--traceback] [--no-color] [--force-color] [--skip-checks] {export,import,check_mx,manage_dkim_keys,repair} ...

Modoboa top management command.

options:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  -v {0,1,2,3}, --verbosity {0,1,2,3}
                        Verbosity level; 0=minimal output, 1=normal output, 2=verbose output, 3=very verbose output
  --settings SETTINGS   The Python path to a settings module, e.g. "myproject.settings.main". If this isn't provided, the DJANGO_SETTINGS_MODULE environment variable will be used.
  --pythonpath PYTHONPATH
                        A directory to add to the Python path, e.g. "/home/djangoprojects/myproject".
  --traceback           Raise on CommandError exceptions
  --no-color            Don't colorize the command output.
  --force-color         Force colorization of the command output.
  --skip-checks         Skip system checks.

subcommands:
  {export,import,check_mx,manage_dkim_keys,repair}
    export              Export domains or identities using CSV format
    import              Import identities from a csv file
    check_mx            Check defined domains.
    manage_dkim_keys
    repair              Check and fix known problems.
```

That includes `-v`

I haven't tried others, but expect they too got lost in the process.

**Comment by Spitfireap** [comment]
Hi,
I have just tested it and if I put `--verbosity` **after** the subcommand, it doesn't get recognized, while it does if it is place after the subcommand. This is because `manage_dkim_keys` do not have any arguments... Can you confirm it is the same on your side ?

**Comment by bernd-wechner** [comment]
Can you clarify your meaning, as I think there's a typo, you said it both does work and doesn't work after the subcommand. My results from a try just now are:

- `python manage.py --verbosity 3 modo manage_dkim_keys` returns `Unknown command: '--verbosity'` which it should not (bug)
- `python manage.py modo --verbosity 3 manage_dkim_keys` does work and sets the option `verbosity` to 3 in the handler.
- `python manage.py modo  manage_dkim_keys --verbosity 3` returns `manage.py modo: error: unrecognized arguments: --verbosity 3` which it should not (bug)

Looks like one combo does work, but two do not. I would never have guess that middle one to be hones and command line options shoudl work regardless of placement.

**Comment by Spitfireap** [comment]
Yes, sorry, I corrected it. 


> * `python manage.py --verbosity 3 modo manage_dkim_keys` returns `Unknown command: '--verbosity'` which it should not (bug)

I agree that this one *should* work. 

> * `python manage.py modo  manage_dkim_keys --verbosity 3` returns `manage.py modo: error: unrecognized arguments: --verbosity 3` which it should not (bug)

This one I'm not sure : `/srv/modoboa/env/bin/python ./manage.py modo manage_dkim_keys -h` return basically nothing (because manage_dkim_keys do not support any argument, actually).
