### ISSUE TITLE
new-admin page not found. returns 404

### ISSUE THREAD

**Issue by cdaraujo1** [modoboa/modoboa#2747]
# Impacted versions

* OS Type: Debian/Ubuntu
* OS Version: Number or Name
* Database Type: sqlite
* Database version: X.y
* Modoboa: 2.0.2
* installer used: Docker/Docker-compose
* Webserver: None

# Steps to reproduce
click at localhost:8000/new-admin
# Current behavior

# Expected behavior

Page working

# Video/Screenshot link (optional)

<img width="935" alt="image" src="https://user-images.githubusercontent.com/12837079/212165489-11b95cb1-68e1-4525-8bc5-5bf3e910cd13.png">

**Comment by tonioo** [comment]
I can't work like this in development mode.
