### ISSUE TITLE
Logparser is missing any lock mechanism that prevents multiple instances to be run

### ISSUE THREAD

**Issue by Salamek** [modoboa/modoboa#2754]
# Impacted versions

* OS Type: Debian
* OS Version: 11
* Database Type: PostgreSQL
* Database version: 13.9
* Modoboa: 2.0.*
* installer used: No
* Webserver: Nginx

# Steps to reproduce

When mail.log is huge, processing it may take more then 5 minutes configured in cron... then another instance is started that slows down the system... this goes on and on until all RAM is wasted and OOM killer starts doing it's job...

# Current behavior

Multiple instances of logparser can be run

# Expected behavior

Only one instance of logparser (and maybe other periodic tasks?) should be allowed to run, use pid file lock for this?

# Video/Screenshot link (optional)

Oh now i'm sad i did not take a screenshot of htop with 82 load and like 30 logparsers running lol...

**Comment by MrGeneration** [comment]
If you don't need current stats but are fine with the day before you could also do this once per day at night and use the rotated log file. We're forced to do this as well as our logfile run takes roughly 45min  due to size.

Using `logtail` in this process would solve this issue imho because it continues on the last line you've left with. That might be a good solution as an enhancement.

**Comment by Salamek** [comment]
@MrGeneration yes, i did that as a first thing! :smiling_face_with_tear: But that is not a FIX that is a HACK, these types of background tasks should have locking mechanism that prevents another task to be run while previous is still running. That means CRON task will "wait" for previous task to finish no matter what CRON period is set to and how long given task actually takes while it prevents spawning more then one task at once...

Why is your solution a hack? It does not prevent the issue, you have no assurance that task will actually finish in "expected" time, anything from huge log file to random deadlock will trigger this issue again... Also this is possible DoS for installations using default settings... filling a mail.log with random crap is not a hard thing to do.
