### ISSUE TITLE
CSS and JS not found

### ISSUE THREAD

**Issue by danyob** [modoboa/modoboa#2759]
So after my third attempt, i got modoboa up and running, with one isssue, theres no css or js getting pulled into the front end. Here is a console output:

`font-awesome.min.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap.min.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap-datetimepicker.min.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
selectize.bootstrap3.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
userprefs.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
custom.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.min.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap.min.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
moment.min.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap-datetimepicker.min.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
selectize.min.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
global.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
csrf.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
confirmation.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
notify.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
poller.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
top_notifications.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
history.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
listing.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
twocols_nav.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
ckeditor.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
(index):304 Uncaught ReferenceError: set_static_url is not defined
    at (index):304:7
(index):335 Uncaught ReferenceError: $ is not defined
    at (index):335:1
custom.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
selectize.bootstrap3.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap.min.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap-datetimepicker.min.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
font-awesome.min.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
userprefs.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)`

any ideas what this could be? Down to file permissions or owner?

**Comment by Spitfireap** [comment]
Hi, have you used the installer ?

**Comment by danyob** [comment]
> Hi, have you used the installer ?

yes i used the installer, following this guide: https://www.linuxbabe.com/mail-server/email-server-centos-7-modoboa

**Comment by Spitfireap** [comment]
ok, so are you using Centos7 ?

**Comment by danyob** [comment]
> ok, so are you using Centos7 ?

correct :)

**Comment by Spitfireap** [comment]
nice, so what is the output of `ls -la /srv/modoboa/instance/` ?

**Comment by danyob** [comment]
> ls -la /srv/modoboa/instance/


total 8
drwxrwxr-x.  5 modoboa modoboa   70 Jan 23 17:19 .
drwxr-xr-x.  7 modoboa modoboa  172 Jan 23 17:19 ..
drwxrwxr-x.  3 modoboa modoboa   93 Jan 23 17:19 instance
-rwxrwxr-x.  1 modoboa modoboa  628 Jan 23 17:19 manage.py
drwxrwxr-x.  3 modoboa modoboa   21 Jan 23 17:19 media
drwxrwxr-x. 28 modoboa modoboa 4096 Jan 23 17:19 sitestatic

**Comment by Spitfireap** [comment]
Can you try this :
`sudo -u modoboa -i bash`
`/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py collectstatic`

if it doesn't work, can you check in your nginx (should be /etc/nginx/conf.d/*hostname*.conf that this type of line :  
```
location /sitestatic/ {
        try_files $uri $uri/ =404;
    }
```

**Comment by danyob** [comment]
When i run that i get the following:

/srv/modoboa/env/bin/python: /srv/modoboa/env/bin/python: cannot execute binary file

i have also checked the .conf and that section exists.

**Comment by danyob** [comment]
> Can you try this : `sudo -u modoboa -i bash` `/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py collectstatic`
> 
> if it doesn't work, can you check in your nginx (should be /etc/nginx/conf.d/_hostname_.conf that this type of line :
> 
> ```
> location /sitestatic/ {
>         try_files $uri $uri/ =404;
>     }
> ```

I managed to run this is the end, but now on every page i get a message saying "sorry, an internal error occured"

**Comment by Spitfireap** [comment]
Do you have SE Linux enabled perhaps ?
