### ISSUE TITLE
OpenDkim Add Two DKIM keys when External Client is used E.g. Outlook

### ISSUE THREAD

**Issue by shabs76** [modoboa/modoboa#2781]
# Impacted versions

* OS Type: Debian/Ubuntu
* OS Version: 20.04.5 LTS (GNU/Linux 5.15.0-1028-aws x86_64)
* Database Type: PostgreSQL
* Database version: X.y
* Modoboa: 2.0.3
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
I could not connect with external clients like Outlook. So I changed the postfix configuration to:-
`
smtp      inet  n       -       y       -       1       postscreen
smtpd     pass  -       -       y       -       -       smtpd
dnsblog   unix  -       -       y       -       0       dnsblog
tlsproxy  unix  -       -       y       -       0       tlsproxy
pickup     unix  n       -       n       60      1       pickup
    -o content_filter=smtp-amavis:[127.0.0.1]:10026
cleanup    unix  n       -       n       -       0       cleanup
qmgr       unix  n       -       n       300     1       qmgr
tlsmgr     unix  -       -       n       1000?   1       tlsmgr
rewrite    unix  -       -       n       -       -       trivial-rewrite
bounce     unix  -       -       n       -       0       bounce
defer      unix  -       -       n       -       0       bounce
trace      unix  -       -       n       -       0       bounce
verify     unix  -       -       n       -       1       verify
flush      unix  n       -       n       1000?   0       flush
proxymap   unix  -       -       n       -       -       proxymap
proxywrite unix  -       -       n       -       1       proxymap
smtp       unix  -       -       n       -       -       smtp
relay      unix  -       -       n       -       -       smtp
    -o syslog_name=postfix/$service_name
showq      unix  n       -       n       -       -       showq
error      unix  -       -       n       -       -       error
retry      unix  -       -       n       -       -       error
discard    unix  -       -       n       -       -       discard
local      unix  -       n       n       -       -       local
virtual    unix  -       n       n       -       -       virtual
lmtp       unix  -       -       n       -       -       lmtp
anvil      unix  -       -       n       -       1       anvil
scache     unix  -       -       n       -       1       scache

postlog    unix-dgram n  -       n       -       1       postlogd

maildrop   unix  -       n       n       -       -       pipe flags=DRhu
    user=vmail argv=/usr/bin/maildrop -d ${recipient}

uucp       unix  -       n       n       -       -       pipe flags=Fqhu
    user=uucp argv=uux -r -n -z -a$sender - $nexthop!rmail ($recipient)
ifmail     unix  -       n       n       -       -       pipe flags=F user=ftn
    argv=/usr/lib/ifmail/ifmail -r $nexthop ($recipient)
bsmtp      unix  -       n       n       -       -       pipe flags=Fq.
    user=bsmtp argv=/usr/lib/bsmtp/bsmtp -t$nexthop -f$sender $recipient
scalemail-backend unix - n       n       -       2       pipe flags=R
    user=scalemail argv=/usr/lib/scalemail/bin/scalemail-store ${nexthop}
    ${user} ${extension}

mailman    unix  -       n       n       -       -       pipe flags=FR
    user=list argv=/usr/lib/mailman/bin/postfix-to-mailman.py ${nexthop}
    ${user}

submission inet n       -       n       -       -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level=encrypt
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o content_filter=smtp-amavis:[127.0.0.1]:10026

465 inet  n       -       n       -       -       smtpd
  -o syslog_name=postfix/smtps
  -o smtpd_tls_wrappermode=yes
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o content_filter=smtp-amavis:[127.0.0.1]:10026

dovecot unix    -       n       n       -       -      pipe
    flags=DRh user=vmail:vmail argv=/usr/lib/dovecot/deliver -f ${sender} -d ${user}@${domain} -m ${extension}

mlmmj   unix  -       n       n       -       -       pipe
    flags=ORhu user=mlmmj:mlmmj argv=/usr/bin/mlmmj-amime-receive -L /var/vmail/mlmmj/${nexthop}

# Amavisd integration.
smtp-amavis unix -  -   n   -   4  smtp
    -o syslog_name=postfix/amavis
    -o smtp_data_done_timeout=1200
    -o smtp_send_xforward_command=yes
    -o disable_dns_lookups=yes
    -o max_use=20

127.0.0.1:10025 inet n  -   n   -   -  smtpd
    -o syslog_name=postfix/10025
    -o content_filter=
    -o mynetworks_style=host
    -o mynetworks=127.0.0.0/8
    -o local_recipient_maps=
    -o relay_recipient_maps=
    -o strict_rfc821_envelopes=yes
    -o smtp_tls_security_level=none
    -o smtpd_tls_security_level=none
    -o smtpd_restriction_classes=
    -o smtpd_delay_reject=no
    -o smtpd_client_restrictions=permit_mynetworks,reject
    -o smtpd_helo_restrictions=
    -o smtpd_sender_restrictions=
    -o smtpd_recipient_restrictions=permit_mynetworks,reject
    -o smtpd_end_of_data_restrictions=
    -o smtpd_error_sleep_time=0
    -o smtpd_soft_error_limit=1001
    -o smtpd_hard_error_limit=1000
    -o smtpd_client_connection_count_limit=0
    -o smtpd_client_connection_rate_limit=0
    -o receive_override_options=no_header_body_checks,no_unknown_recipient_checks,no_address_mappings

127.0.0.1:10028 inet n  -   n   -   -  smtpd
    -o syslog_name=postfix/10028
    -o content_filter=
    -o mynetworks_style=host
    -o mynetworks=127.0.0.0/8
    -o local_recipient_maps=
    -o relay_recipient_maps=
    -o strict_rfc821_envelopes=yes
    -o smtp_tls_security_level=none
    -o smtpd_tls_security_level=none
    -o smtpd_restriction_classes=
    -o smtpd_delay_reject=no
    -o smtpd_client_restrictions=permit_mynetworks,reject
    -o smtpd_helo_restrictions=
    -o smtpd_sender_restrictions=
    -o smtpd_recipient_restrictions=permit_mynetworks,reject
    -o smtpd_end_of_data_restrictions=
    -o smtpd_error_sleep_time=0
    -o smtpd_soft_error_limit=1001
    -o smtpd_hard_error_limit=1000
    -o smtpd_client_connection_count_limit=0
    -o smtpd_client_connection_rate_limit=0
    -o receive_override_options=no_header_body_checks,no_unknown_recipient_checks

smtp-amavis unix -  -   -   -   4  smtp
    -o smtp_data_done_timeout=1200
    -o smtp_send_xforward_command=yes
    -o disable_dns_lookups=yes
    -o max_use=20
    -o smtp_tls_security_level=none
`

After the change, I could connect with Outlook and other clients, but the webmail could still send emails and receive them to the receiver.
# Current behavior

The problem now is,  every time an email is sent from Outlook or other clients **Two DKIM keys are added**. Below are logs from mail.log file

```
Feb 12 12:21:13 mail postfix/smtps/smtpd[1138940]: Anonymous TLS connection established from unknown[197.250.227.1]: TLSv1.3 with cipher TLS_AES_128_GCM_SHA256 (128/128 bits) key-exchange ECDHE (P-256) server-signature RSA-PSS (2048 bits)
Feb 12 12:21:15 mail postfix/smtps/smtpd[1138940]: 04FC887821: client=unknown[197.250.227.1], sasl_method=PLAIN, sasl_username=user@example.com
Feb 12 12:21:15 mail postfix/cleanup[1139518]: 04FC887821: message-id=<>
Feb 12 12:21:15 mail opendkim[24456]: 04FC887821: DKIM-Signature field added (s=modoboa, d=example.com)
Feb 12 12:21:15 mail postfix/qmgr[1117942]: 04FC887821: from=<user@example.com>, size=1986, nrcpt=1 (queue active)
Feb 12 12:21:16 mail postfix/10025/smtpd[1139555]: connect from localhost[127.0.0.1]
Feb 12 12:21:16 mail postfix/10025/smtpd[1139555]: 2C0DB8782C: client=localhost[127.0.0.1]
Feb 12 12:21:16 mail postfix/cleanup[1139518]: 2C0DB8782C: message-id=<20230212122116.2C0DB8782C@mail.example.com>
Feb 12 12:21:16 mail opendkim[24456]: 2C0DB8782C: DKIM-Signature field added (s=modoboa, d=example.com)
Feb 12 12:21:16 mail postfix/qmgr[1117942]: 2C0DB8782C: from=<user@example.com>, size=3076, nrcpt=1 (queue active)
Feb 12 12:21:16 mail postfix/10025/smtpd[1139555]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Feb 12 12:21:16 mail amavis[18779]: (18779-08) Passed CLEAN {RelayedOutbound}, ORIGINATING LOCAL [197.250.227.1]:1267 [197.250.227.1] <user@example.com> -> <user@gmail.com>, Queue-ID: 04FC887821, mail_id: F3AmxR1BDGqS, Hits: -0.056, size: 2505, queued_as: 2C0DB8782C, dkim_sd=modoboa:example.com, 475 ms
Feb 12 12:21:16 mail postfix/smtp[1139550]: 04FC887821: to=<user@gmail.com>, relay=127.0.0.1[127.0.0.1]:10026, delay=1.5, delays=0.99/0.01/0/0.48, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 2C0DB8782C)
Feb 12 12:21:16 mail postfix/qmgr[1117942]: 04FC887821: removed
Feb 12 12:21:16 mail postfix/smtp[1139556]: Trusted TLS connection established to email-smtp.us-east-1.amazonaws.com[34.201.230.25]:587: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Feb 12 12:21:16 mail postfix/smtp[1139556]: 2C0DB8782C: to=<user@gmail.com>, relay=email-smtp.us-east-1.amazonaws.com[34.201.230.25]:587, delay=0.32, delays=0.1/0.02/0.17/0.03, dsn=5.0.0, status=bounced (host email-smtp.us-east-1.amazonaws.com[34.201.230.25] said: 554 Transaction failed: Duplicate header 'DKIM-Signature'. (in reply to end of DATA command))
```

# Expected behavior

I expected emails to be forwarded to AWS SES with one DKIM key either added before forward to localhost or after the message has been forwarded.

Is there a way to prevent this from happening?
Thank you in advance.
I hope I will be able to get assistance on this. Is there anything I should add in the postfix conf file to make it work?

**Comment by tonioo** [comment]
@shabs76 Could you highlight the modifications you made to postfix config please?
