### ISSUE TITLE
Aliases creation on new admin

### ISSUE THREAD

**Issue by FullGreenGN** [modoboa/modoboa#2886]
Hi,
I want to create catch all mail (no-reply@domain.ltd) but when i create the alias I got this error in my web console

POST https://mail.domain.ltd/api/v2/aliases/
Uncaught (in promise) Error: Request failed with status code 404

**Comment by Spitfireap** [comment]
Hi ! Can you check the actual response from the api ? Also, does your recipient(s) exist ?
