### ISSUE TITLE
New Admin: DKIM bind says _domain_key instead of _domainkey

### ISSUE THREAD

**Issue by fmp777** [modoboa/modoboa#2931]
Just a typo in the new UI.  The old UI displays _domainkey correctly.
![image](https://user-images.githubusercontent.com/2659615/227589093-cf9964e6-2a25-4f79-886b-7863bffb1349.png)

**Comment by Spitfireap** [comment]
Hi, this was fixed with #2630 released with 2.0.3. Please make sure your modoboa instance is up-to-date. Also, please follow the [new-admin upgrade instructions](https://modoboa.readthedocs.io/en/latest/upgrade.html#new-admin-interface) ;)
