### ISSUE TITLE
installer: Failed to find amavis database schema error 

### ISSUE THREAD

**Issue by Jarrodsz** [modoboa/modoboa#2941]
# Impacted versions

* OS Type: CentOS
* OS Version: 9
* Database Type: installer based
* installer: yes

# Steps to reproduce
1. clone repro like instructions
2. run install like instructions

# Current behavior
```
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Generating new self-signed certificate
Installing amavis
Failed to find amavis database schema
```

# Expected behavior

Install the mailserver without errors.

Is there a fix for this please? I evaluated lots of mailservers and this project is nice and lean but unable to install it.

**Comment by Spitfireap** [comment]
For now, the installer only supports centos 7. You can use the `centos9-support` of [modoba-installer](https://github.com/modoboa/modoboa-installer/tree/centos9-support), but this is a work in progress. @tomas-kucera wanted to finish the support integration, but he doesn't have time for now, I guess. It *should* work, but it requires you to disable SE-Linux. 

I'm closing the issue, if you find any bug please continue the discussion [here](https://github.com/modoboa/modoboa/discussions/2721) ;)
