### ISSUE TITLE
Domain DNS status 403 forbidden for reseller.

### ISSUE THREAD

**Issue by k-hristov** [modoboa/modoboa#2945]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 22.04 LTS
* Database Type: PostgreSQL
* Database version: 14.7
* Modoboa: 2.0.5
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Run simple modoboa-installer with letsencrypt certificate.

# Current behavior
Logged in as admin:
Domains list page
I can see the domains i've added. I can also see the DNS checks row. On each "label" MX SPF DMARC DKIM and etc. when i click on them modal shows up with proper content.

Logged in as reseller.
I can see the domains i've added. I can also see the DNS checks row. Labels MX and DNSBL show up modals. All others give Alert with content "Internal error". In the browser with the inspector -> Network tab the AJAX error is 403 Forbidden. I can see the same error in /var/log/uwsgi/app/modoboa_instance.log. Same goes for domain details page.
`[HOSTNAME] [pid: 391931|app: 1|req: 123/525] [MY_IP] () {56 vars in 1093 bytes} [Tue Apr  4 15:00:38 2023] GET /dnstools/dnsrecords/3/ => generated 135 bytes in 157 msecs (HTTP/1.1 403) 5 headers in 154 bytes (1 switches on core 0)`

# Expected behavior
I believe that reseller should be able to see contents of all these "Labels". Reseller is basically owner of these domains.

**Comment by tonioo** [comment]
@k-hristov In the new or the old UI ?
