### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by lmfrazao** [modoboa/modoboa#2966]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 20.04
* Database Type: MySQL
* Modoboa: 2.1.1
* installer used: Yes ?
* Webserver: Nginx

# Steps to reproduce

after upgrading from 2.1.0 I am having errors when editing domains and users, it just won't open.

with debug enabled, same thing.

only can see 405 Method Not Allowed on browser error

[HTTP/2XHRGET
...admin/accounts/2/edit/?active_tab=mail
405 Method Not Allowed

**Comment by lmfrazao** [comment]
update:

aliases open ok

listing quotas from users, if you try to open a user from that list, same error.

**Comment by Spitfireap** [comment]
Hi, thanks for the report. @tonioo it seems to come from [this](https://github.com/modoboa/modoboa/commit/5d886f3d06373d2c3292911bac0772bcd5102343), domain/X/edit requires a get a load it seems.

**Comment by tonioo** [comment]
@lmfrazao Have you run the collectstatic command during the upgrade? Make sure to also clear your cache.

**Comment by lmfrazao** [comment]
I did ran collectstatic

cache, you mean from the browser, correct ? that I did.

**Comment by lmfrazao** [comment]
working fine now.

thank you!
