### ISSUE TITLE
Unable to create calendar

### ISSUE THREAD

**Issue by NiccyB** [modoboa/modoboa#2990]
# Impacted versions

* OS Type: Debian
* OS Version: 11
* Database Type: As per installer
* Database version: As per installer
* Modoboa: As per installer
* installer used: Yes
* Webserver: As per installer

# Steps to reproduce

Create simple user. Log in as user. Click 'Calendars' from top bar. Click '+ New calendar'. Enter details and click 'Create'. 

# Current behaviour

New calendar dialog box stays open and calendar is not created. No error messages are given.

# Expected behaviour

Dialogue box closes and calendar is created.

**Comment by Spitfireap** [comment]
Hi, do you have a self-signed cert or a let's encrypt one ?

**Comment by NiccyB** [comment]
Self-signed on the modoboa box itself, but accessed through a nginx reverse proxy with a LE cert.

**Comment by Spitfireap** [comment]
Okay, could you please try to modify this file : `/srv/modoboa/env/lib/pythonX.X/site-packages/modoboa_radicale/backends/caldav_.py `
Then find this : 
```
self.client = caldav.DAVClient(
            server_url,
            username=username, password=password)
```
And add `ssl_verify_cert=False`. So it should be : 

```
self.client = caldav.DAVClient(
            server_url,
            username=username, password=password,
            ssl_verify_cert=False)
```

Then restart uwsgi service and retry to create a calendar.

**Comment by NiccyB** [comment]
Tried that and it did not resolve the issue.
Rebooted and cleared browser cache just in case and still not resolved.

**Comment by Spitfireap** [comment]
Ok, do you have any error in the browser console ?

**Comment by NiccyB** [comment]
Ah. Yes.
![image](https://user-images.githubusercontent.com/31012803/235626110-6b3274e1-09a8-45bf-a311-33aec01b5c66.png)

**Comment by Spitfireap** [comment]
Nice, so can you edit `/srv/modoboa/instance/instance/settings.py` and set `DEBUG` to True ? and restart uwsgi. 
Then post what shows in the browser console when creating a calendar

**Comment by NiccyB** [comment]
Ah, yes.
![image](https://user-images.githubusercontent.com/31012803/235626380-4f6baad1-06b0-4247-9523-896b567aebff.png)

**Comment by NiccyB** [comment]
With DEBUG=True I get no more information in the console than that above.

**Comment by Spitfireap** [comment]
You need to go to `Network` tab and check for the 'Response' of the request

**Comment by NiccyB** [comment]
"Failed to load response data: Request content was evicted from inspector cache"

**Comment by Spitfireap** [comment]
Is it for the `api/v1/user-calendars` request ? Can you try to create a calendar on the old interface ?

**Comment by NiccyB** [comment]
I'm just logged in as a simple user using the default interface (as per the install script). I can't see anywhere to change to any other interface.

**Comment by Spitfireap** [comment]
So you are on the old. 
Regarding the response, are you sure it is on user-calendars request (filter the results with `XHR/Fetch` option

**Comment by NiccyB** [comment]
![image](https://user-images.githubusercontent.com/31012803/235638555-752b22ad-c4a0-4d1f-9d64-ce0c4efbd424.png)

**Comment by aaalkhonji73** [comment]
XHR/Fetch

**Comment by Spitfireap** [comment]
> ![image](https://user-images.githubusercontent.com/31012803/235638555-752b22ad-c4a0-4d1f-9d64-ce0c4efbd424.png)

![Screenshot_20230502_132645](https://user-images.githubusercontent.com/45575529/235653825-0de52376-919b-4960-8584-0160a08e6b1e.png)

Just before creating the calendar, clear the history on the Network tab and uncheck `Preserve log` if checked. Then look again at the response of user-calendars.

**Comment by NiccyB** [comment]
OK. Switched to Firefox which just worked, of course. Shouldn't have been in Chrome in the first place.

"maximum recursion depth exceeded while calling a Python object"

Redacted raw reponse attached.

[modoboa_create_calendar_debug.txt](https://github.com/modoboa/modoboa/files/11373329/modoboa_create_calendar_debug.txt)

**Comment by Spitfireap** [comment]
Thanks. Can you share the output of `pip list` with your venv activated plz?

**Comment by NiccyB** [comment]
Package            Version
------------------ --------------
appdirs            1.4.4
bottle             0.12.19
brz-etckeeper      0.0.0
certifi            2020.6.20
chardet            4.0.0
distlib            0.3.1
fail2ban           0.11.2
filelock           3.0.12
idna               2.10
importlib-metadata 1.6.0
inithooks          1.0.3
more-itertools     4.2.0
pip                20.3.4
pycurl             7.43.0.6
pycurl-wrapper     2.0-2-g027c28a
Pygments           2.7.1
pythondialog       3.5.1
PyYAML             5.3.1
pyzor              1.0.0
requests           2.25.1
setuptools         52.0.0
six                1.16.0
supervisor         4.2.2
turnkey-conffile   1.0
turnkey-netinfo    1.0
turnkey-sysinfo    1.1
turnkey-version    1.1
TurnkeyLazyClass   1.0
urllib3            1.26.5
virtualenv         20.4.0+ds
wheel              0.34.2
zipp               1.0.0

**Comment by Spitfireap** [comment]
seems to be on global here : `/srv/modoboa/env/bin/pip list` perhaps ?

**Comment by Spitfireap** [comment]
No worries. I can't reproduce the issue so I'm just rubber ducking here ;).

Can you check if there is a log corresponding to radicale here : `/var/log/supervisor` ?

Also can you try to run this : 
```
/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py generate_rights --force
```
and try again ?

**Comment by NiccyB** [comment]
Yes, there's a file at /var/log/supervisor/radicale-stdout---supervisor-do_a027l.log but it is empty.

/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py generate_rights --force and then restart doesn't solve the problem.

/etc/radicale/config is as follows:
```
# This file was automatically installed on 2023-05-02T09:23:21.009445
# -*- mode: conf -*-
# vim:ft=cfg

# Config file for Radicale - A simple calendar server
#
# Place it into /etc/radicale/config (global)
# or ~/.config/radicale/config (user)
#
# The current values are the default ones


[server]

# CalDAV server hostnames separated by a comma
# IPv4 syntax: address:port
# IPv6 syntax: [address]:port
# For example: 0.0.0.0:9999, [::]:9999
#hosts = 127.0.0.1:5232

# Daemon flag
#daemon = False

# File storing the PID in daemon mode
#pid =

# Max parallel connections
#max_connections = 20

# Max size of request body (bytes)
#max_content_length = 10000000

# Socket timeout (seconds)
#timeout = 10

# SSL flag, enable HTTPS protocol
#ssl = False

# SSL certificate path
#certificate = /etc/ssl/radicale.cert.pem

# SSL private key
#key = /etc/ssl/radicale.key.pem

# CA certificate for validating clients. This can be used to secure
# TCP traffic between Radicale and a reverse proxy
#certificate_authority =

# SSL Protocol used. See python's ssl module for available values
#protocol = PROTOCOL_TLSv1_2

# Available ciphers. See python's ssl module for available ciphers
#ciphers =

# Reverse DNS to resolve client address in logs
#dns_lookup = True

# Message displayed in the client when a password is needed
#realm = Radicale - Password Required


[encoding]

# Encoding for responding requests
#request = utf-8

# Encoding for storing local collections
#stock = utf-8


[auth]

# Authentication method
# Value: none | htpasswd | remote_user | http_x_remote_user
type = radicale_dovecot_auth 

# Htpasswd filename
# htpasswd_filename = users

# Htpasswd encryption method
# Value: plain | sha1 | ssha | crypt | bcrypt | md5
# Only bcrypt can be considered secure.
# bcrypt and md5 require the passlib library to be installed.
# htpasswd_encryption = plain 

# Incorrect authentication delay (seconds)
#delay = 1

auth_socket = /var/run/dovecot/auth-radicale


[rights]

# Rights backend
# Value: none | authenticated | owner_only | owner_write | from_file
type = from_file 

# File for rights management from_file
file = /etc/radicale/rights


[storage]

# Storage backend
# Value: multifilesystem
type = radicale_storage_by_index
radicale_storage_by_index_fields = dtstart, dtend, uid, summary

# Folder for storing local collections, created if not present
filesystem_folder = /srv/radicale/collections

# Lock the storage. Never start multiple instances of Radicale or edit the
# storage externally while Radicale is running if disabled.
#filesystem_locking = True

# Sync all changes to disk during requests. (This can impair performance.)
# Disabling it increases the risk of data loss, when the system crashes or
# power fails!
#filesystem_fsync = True

# Delete sync token that are older (seconds)
#max_sync_token_age = 2592000

# Close the lock file when no more clients are waiting.
# This option is not very useful in general, but on Windows files that are
# opened cannot be deleted.
#filesystem_close_lock_file = False

# Command that is run after changes to storage
# Example: ([ -d .git ] || git init) && git add -A && (git diff --cached --quiet || git commit -m "Changes by "%(user)s)
#hook =


[web]

# Web interface backend
# Value: none | internal
type = none 


[logging]

# Logging configuration file
# If no config is given, simple information is printed on the standard output
# For more information about the syntax of the configuration file, see:
# http://docs.python.org/library/logging.config.html
#config = /etc/radicale/logging

# Store all environment variables (including those set in the shell)
#full_environment = False

# Don't include passwords in logs
#mask_passwords = True


[headers]

# Additional HTTP headers
#Access-Control-Allow-Origin = *
```

**Comment by NiccyB** [comment]
Exactly the same problem running as a VM. I'll try stock Debian next rather than Turnkey Core.

**Comment by NiccyB** [comment]
Hmm. Stock Debian doesn't work at all. I just get this at the home page:

![image](https://user-images.githubusercontent.com/31012803/235725921-56cd296d-1737-4a88-915e-2995dd3fa4f5.png)

**Comment by NiccyB** [comment]
After a glitch (I just got a server error at the home page) and a re-install of Stock Debian 11, I still get exactly the same error trying to create a user's calendar.

**Comment by Spitfireap** [comment]
Does your VM run behind a reverse proxy as well ?

**Comment by Spitfireap** [comment]
I think you simply need to add this ` proxy_pass_header Authorization;` to your nginx reverse proxy for modoboa proxy

**Comment by NiccyB** [comment]
Yay, we're there!! Thank you.

OK. So the "ssl_verify_cert=False" line in /srv/modoboa/env/lib/pythonX.X/site-packages/modoboa_radicale/backends/caldav_.py definitely needs to be added (took it out and got an SSL error). And then "proxy_pass_header Authorization;" needs to be added to the nginx configuration.

Thank you for working through this with me.
