### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by metaldigger** [modoboa/modoboa#2994]
# Impacted versions

* OS Type: Debian/Ubuntu
* OS Version: 22.04
* Database Type: MySQL
* Modoboa: 2.1.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
launch the installation with ./run.py 

# Current behavior
The installer stops during modoboa installation, after "installing modoboa" appears 'b' and return to the shell.

**Comment by ruslaan7** [comment]
I have the same problem. I ran the installation with the --debug option and installed the missing packages pkg-config and libcairo2-dev. It worked for me.

**Comment by metaldigger** [comment]
It worked also for me. Thanks @ruslaan7
