### ISSUE TITLE
watchout

### ISSUE THREAD

**Issue by peterpt** [modoboa/modoboa#3010]
just a few advises : 
- manual install to launch run.py does not exist , update install instructions

- python does not exist anymore of a fresh debian installation , only python3 , i would be interesting if you guys try to test your code on a recent and fresh installed system before releasing the code , my guess is that you are testing this code on a machine that came from a previous version of debian or whatever and where python (as python only binary) still exists .

Too much trouble then drop a message here on github page saying "not maintained anymore"

**Comment by Toniob** [comment]
Hi. Can you please try and install the package named python-is-python3 . My guess is that you didn't know it existed.

**Comment by phpony** [comment]
Also if you're here not for a childish rant but for actual improvement - you're in a wrong repo. Modoboa is a family of products under the hood of https://github.com/modoboa/modoboa-installer. So your complaints about installer should go there, not here.

**Comment by Spitfireap** [comment]
It is an open source project actively developed, and you are free to propose edition to the documentation at your will. 
Steps are:
- Fork the project
- Edit the documentation
- Open a pull request

If you want someone else to do it, then more politeness would probably help. 

Feel free to open a new issue when you've met one of the two solutions proposed above :)
