### ISSUE TITLE
Failure after upgrade

### ISSUE THREAD

**Issue by sven-borkert** [modoboa/modoboa#3057]
# Impacted versions

* OS Type: Ubuntu 
* OS Version: 22.04
* Database Type: PostgreSQL
* Database version: 14.9-0ubuntu0.22.04.1
* Modoboa: 2.2.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

I read the upgrade documentation, it says:

`If you use the installer to perform the upgrade, you NEED to update it. See above for instructions. After updating the installer and modoboa with it, you only need to edit urls.py and settings.py`

So I updated the installer like described in the documentation and ran the installer in upgrade mode, which completed without complaints.

I then checked the urls.py and settings.py, but found the metioned changes are already present:

- /srv/modoboa/instance/instance/urls.py contains "from django.urls import include, path"
- /srv/modoboa/instance/instance/settings.py contains django_rq in INSTALLES_APPS and the RQ_QUEUES section futher down in the file.

So to my understanding, the upgrade should be complete.

# Current behavior

I sent a mail to the system, it does not get delivered, I see the following errors in the system log:

```
Sep  2 13:20:44 mail amavis[1568]: (01568-01) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
Sep  2 13:20:45 mail amavis[1568]: (01568-01) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
Sep  2 13:20:45 mail amavis[1568]: (01568-01) (!)ClamAV-clamd: All attempts (1) failed connecting to /var/run/clamav/clamd.ctl, retrying (2)
Sep  2 13:20:51 mail amavis[1568]: (01568-01) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
Sep  2 13:20:51 mail amavis[1568]: (01568-01) (!)ClamAV-clamd av-scanner FAILED: run_av error: Too many retries to talk to /var/run/clamav/clamd.ctl (All attempts (1) failed connecting to /var/run/clamav/clamd.ctl) at (eval 128) line 659.\n
Sep  2 13:20:51 mail amavis[1568]: (01568-01) (!)WARN: all primary virus scanners failed, considering backups
Sep  2 13:21:20 mail amavis[1568]: (01568-01) (!)TempDir removal: tempdir is to be PRESERVED: /var/lib/amavis/tmp/amavis-20230902T132044-01568-PqC3kRg5
Sep  2 13:21:20 mail postfix/smtpd[8492]: warning: lost connection with proxy inet:[127.0.0.1]:10024
Sep  2 13:21:20 mail postfix/smtpd[8492]: proxy-reject: END-OF-MESSAGE: 451 4.3.0 Error: queue file write error; from=<xxxxxx@gmail.com> to=<admin@xxxxxxx> proto=ESMTP helo=<mail-yb1-xb36.google.com>
Sep  2 13:21:20 mail postfix/cleanup[8504]: 74011204CA: message-id=<20230902132120.74011204CA@xxxxxx>

```

# Expected behavior

Have the mail delivered.

The system is a fully default installation that I installed with the Modoboa installer for testing, and now tried to update from 2.1.2 to 2.2.0.

**Comment by tonioo** [comment]
@sven-borkert Looks like clam daemon is not running. Can you try to restart it?

**Comment by sven-borkert** [comment]
@tonioo Oh yes, you're right. The clamav-daemon failed because of an OOM kill. I had sized down my test system to the minimum requirements of 2GB RAM, that does not seem to be enough. With 4GB of RAM it runs fine, never mind.
