### ISSUE TITLE
Unable to connect using any Android email client

### ISSUE THREAD

**Issue by qumberrizvi** [modoboa/modoboa#3066]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 22.04 LTS
* Database Type: PostgreSQL
* Database version: 14.9
* Modoboa: 2.2.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
- Install Modoboa using the install script.
- Configure DNS, etc.
- Generate certificates for mail.yourdomain.com and autoconfig.yourdomain.com using Certbot.
- Once webmail is working perfectly, connect using any email client on Android or Thunderbird
-  Use third party SMTP as relay through postfix (SendInBlue / Brevo)
- Ensure all incoming ports are open (25, 587, 443, 143, 465, 993)
- Enable all outgoing ports are open (except 25 - blocked by AWS; hence the Brevo SMTP relay)
- IMAP connection never succeeds (Unable to connect to server)

# Current behavior

Unable to connect using any client. Fails on "Checking incoming server settings" with "couldn't connect to server message".

# Expected behavior

Should connect to the server using email clients.

# Video/Screenshot link

https://photos.app.goo.gl/9QA6QcsFYZpTFBrr7

Please let me know if you need any info / logs etc.

**Comment by Spitfireap** [comment]
Can you try to connect and share the relevant connection attempt in `/var/log/mail.log` ?

**Comment by qumberrizvi** [comment]
> Can you try to connect and share the relevant connection attempt in `/var/log/mail.log` ? 

Sorry but I terminated the instance and am now using a managed service. So I can't provide that log anymore.

**Comment by Spitfireap** [comment]
OK, thank you :)
