### ISSUE TITLE
Receiving Empty Mail Body from Figma

### ISSUE THREAD

**Issue by mughal41** [modoboa/modoboa#3069]
# Impacted versions

* OS Type: Debian/Ubuntu
* OS Version: 22.04
* Database Type: PostgreSQL 
* Database version: 14.9
* Modoboa: 2.1.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
When receiving an account confirmation email from Figma, the email received is blank with no body, whereas same mail received on google has complete body attached.
# Current behavior

When receiving an email particularly from Figma for account confirmation / verification the mail body is empty. I cross checked vmail directory in /srv/vmail/[domain_name] but the file is blank as well  with no html.

# Expected behavior

# Video/Screenshot link (optional)

**Comment by osamamumtaz** [comment]
I'm also facing the exactly same issue.
I'm trying to create account on figma, I receive empty body on email from Figma.

Following for updates regarding this issue.

**Comment by Spitfireap** [comment]
Hi,

Just to be clear, you checked with a separate mail client or simply with the webmail ? Can you check `/var/log/mail.log` when receiving the email ?

**Comment by mughal41** [comment]
@Spitfireap yes i checked `/var/log/mail.log` but no logs were generated, i also checked the **maildir** directory where all the received mails for a user are stored and sadly it was empty as well.

**Comment by mughal41** [comment]
@Spitfireap sure i tested it out again with a new test account attaching the results

**Comment by tonioo** [comment]
@mughal41 What client do you use to check that email body is empty?
