### ISSUE TITLE
High Cpu Usage after new installation during this week

### ISSUE THREAD

**Issue by samuraikid0** [modoboa/modoboa#3072]
# Impacted versions

* OS Type: Debian
* OS Version: Bullseye
* Database Type: PostgreSQL
* Database version: 13
* Modoboa: Last
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Complete a fresh installation and look at task manager you see amavis foreground process run 99% all the time.

# Current behavior

# Expected behavior
System don't run at 100%

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@samuraikid0 Have you tried to restart this process?

**Comment by Relic180** [comment]
I'm experience this as well, with a fairly similar build to OP:

- OS Type: Ubuntu
- OS Version: 24.04 (Noble Numbat)
- Database Type: PostgreSQL
- Database version: 17
- Modoboa: Last (Oct 7th)
- installer used: Yes
- Webserver: nginx (1.24)

Immediately after the install completed, my CPU usage shows up consistently around 80%. Prior to install, it had been between 5-15%.

I installed it yesterday originally. Overnight my VPS host capped me and sent a bunch of notifications / warnings for running at full-tilt for over 12 hours straight. Everything got stuck and unresponsive, I had to get uncapped just so I could restore from a backup image.

Trying to install again, and looks like I'm seeing the exact same thing. Restarted a couple times to be sure. CPU always hovering between 75-85%. Most terminal commands take far longer to execute than normal, etc...

**Comment by tonioo** [comment]
Can you check which process is consuming your CPU(s) ?

**Comment by cyberarm** [comment]
Have you checked that you're not using port 9000?
IIRC, I had a high cpu issue due to using that port and the modoboa worker attempting to bind to it, failing, and getting stuck in a loop.

**Comment by Relic180** [comment]
Although what ultimately kicked-off the behavior was the Modoboa installation, the issue was actually with pm2.

Not entirely sure what happened, but after the install pm2 went and fetched an outdated ecosystem config that had some no-longer-valid paths in it. So as soon as the install finished, pm2 started throwing massive errors and devouring my CPU.

Once I found it and fixed the paths, everything went back to normal. Sorry about the false alarm.
