### ISSUE TITLE
Upgrade Issue 2.2.0

### ISSUE THREAD

**Issue by ecolipain** [modoboa/modoboa#3088]
### Discussed in https://github.com/modoboa/modoboa/discussions/3083

<div type='discussions-op-text'>

<sup>Originally posted by **ecolipain** October  4, 2023</sup>
- Ubuntu 20.04.1
- Postgres 12.6
- Python 3.8
- psycopg 3.1
- Manual install
- Upgrade 2.1.2 ---> 2.2.0

Attempting to upgrade to 2.2.0. url.py modified per upgrade instructions ( Modified to:  from django.urls import include, path ).

**> url.py**         

> from django.urls import include, path
urlpatterns = [
url(r'', include('modoboa.urls')),
]

Receiving error upon migrate command.      
 _NameError: name 'url' is not defined._ 
Full output of migrate command attached.
[migrate.txt](https://github.com/modoboa/modoboa/files/12807190/migrate.txt)
</div>
[migrate.txt](https://github.com/modoboa/modoboa/files/12859074/migrate.txt)

**Comment by Spitfireap** [comment]
Hi, it seems you missed the line bellow :
``And replace url with path in the file.`` 
Can you try that ? :)

We might need to make it clearer indeed.

**Comment by ecolipain** [comment]
Thanks. It jogged my brain.

Altered to:
> urls.py

    from django.urls import include, path
    urlpatterns = [
    path(r'',_ include('modoboa.urls')),
    ]

**Comment by ecolipain** [comment]
Issue Closed
