### ISSUE TITLE
Postfix relay ti modoboa cannot received email Another user same domain

### ISSUE THREAD

**Issue by antoweb** [modoboa/modoboa#3103]
# Impacted versions

* OS Type: Debian
* OS Version: Number or Name
* Database Type: PostgreSQL / MySQL
* Database version: X.y
* Modoboa: X.X.x
* installer used: Yes/No ?
* Webserver: Nginx/Apache

# Steps to reproduce
- Configure modoboa server as relay in a postfix to Another server
- send an email to any mailbox ok
- send mail to Another mailbox same domain modoboa
- postfix log says mail senti
- mail message not arrived on destination mailbox
# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by Spitfireap** [comment]
Hi, 
Can you explain what you mean exactly by : 
```
send an email to any mailbox ok
send mail to Another mailbox same domain modoboa
```

**Comment by antoweb** [comment]
Sorry was my problem.closing it
