### ISSUE TITLE
DKIM keys not generated automatically after installing modoboa using installer

### ISSUE THREAD

**Issue by mjarvisal** [modoboa/modoboa#3104]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 22.04
* Database Type: PostgreSQL
* Database version: 14.9
* Modoboa: 2.2.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Install modoboa using installer
Setup new domain with DKIM enabled

# Current behavior
DKIM keys not generated

# Expected behavior
openDKIM should automatically generate DKIM key for the domain.

# Fix
Needed to edit the modoboa crontab and uncomment Generate DKIM keys job

**Comment by Spitfireap** [comment]
Hi, this is not how modoboa should generate the key. Can you check the output of:

``` cat /var/log/supervisor/modoboa-dkim-worker*```

**Comment by mjarvisal** [comment]
10:14:58 Worker rq:worker:26ce74e3931d481081759f49b26b6584 started with PID 1523, version 1.15.1
10:14:58 Subscribing to channel rq:pubsub:26ce74e3931d481081759f49b26b6584
10:14:58 *** Listening on dkim...
10:28:28 Cleaning registries for queue: dkim
10:55:28 Cleaning registries for queue: dkim
11:22:28 Cleaning registries for queue: dkim
...
10:46:41 Cleaning registries for queue: dkim
10:48:31 dkim: django.core.management.call_command('modo', 'manage_dkim_keys', '--domain=example.com') (ef6e9dda-f96d-4b00-9e93-0afc9f2af655)
10:48:32 dkim: Job OK (ef6e9dda-f96d-4b00-9e93-0afc9f2af655)
10:48:32 Result is kept for 500 seconds
11:02:02 Cleaning registries for queue: dkim
11:29:02 Cleaning registries for queue: dkim

**Comment by Spitfireap** [comment]
So it seems it did work. Can you try again by commenting the cron job and generate a set of keys? You may check on `/var/lib/dkim/` if you kept the default installation folder. The creation should be almost instantaneous.

**Comment by mjarvisal** [comment]
After uncommenting the cron job and creating a test domain for each dkim key length, it looks to be working. Don't know why it didn't work for the first time. I waited for over an hour for the key be generated and then noticed the crontab. I think maybe I should have restarted crond after commenting the job because now it created those keys two times but looks to be working!

16:17:16 dkim: django.core.management.call_command('modo', 'manage_dkim_keys', '--domain=dkimtest1024.com') (a0e0d484-8580-4178-8407-5159f047e250)
16:17:17 dkim: Job OK (a0e0d484-8580-4178-8407-5159f047e250)
16:17:17 Result is kept for 500 seconds
16:17:17 dkim: django.core.management.call_command('modo', 'manage_dkim_keys', '--domain=dkimtest1024.com') (d947e045-d40c-4b6c-b0b9-62daa88f489b)
16:17:17 dkim: Job OK (d947e045-d40c-4b6c-b0b9-62daa88f489b)
16:17:17 Result is kept for 500 seconds
16:17:51 dkim: django.core.management.call_command('modo', 'manage_dkim_keys', '--domain=dkimtest2048.com') (c2073bb3-80e6-4f47-abba-afd0a334aea7)
16:17:51 dkim: Job OK (c2073bb3-80e6-4f47-abba-afd0a334aea7)
16:17:51 Result is kept for 500 seconds
16:17:51 dkim: django.core.management.call_command('modo', 'manage_dkim_keys', '--domain=dkimtest2048.com') (155ecdcc-c135-4313-b7cb-e26d3b7ae02f)
16:17:52 dkim: Job OK (155ecdcc-c135-4313-b7cb-e26d3b7ae02f)
16:17:52 Result is kept for 500 seconds
16:18:22 dkim: django.core.management.call_command('modo', 'manage_dkim_keys', '--domain=dkimtest4096.com') (ea667bd8-832c-4466-9364-e3dabf52d2b3)
16:18:24 dkim: Job OK (ea667bd8-832c-4466-9364-e3dabf52d2b3)
16:18:24 Result is kept for 500 seconds
16:18:24 dkim: django.core.management.call_command('modo', 'manage_dkim_keys', '--domain=dkimtest4096.com') (65efc90b-b32d-469d-b713-efc24318e800)
16:18:24 dkim: Job OK (65efc90b-b32d-469d-b713-efc24318e800)
16:18:24 Result is kept for 500 seconds
~$ sudo ls /var/lib/dkim/
dkimtest1024.com.pem  dkimtest2048.com.pem  dkimtest4096.com.pem  example.com.pem

**Comment by Spitfireap** [comment]
Thank you. I'm closing the issue. The running twice is expected behavior for now and will be addressed in a future released.
Be sure to **comment out** the dkim line in the crontab as the dkim job is handled by RQ now and is started asynchronously as soon as you request a new key.

**Comment by movahhedi** [comment]
After hours it still says "not generated". Where is the said cron job?

**Comment by movahhedi** [comment]
After 12 hours it didn't generate automatically. So I ran this (with SUDO):
```
sudo /srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py modo manage_dkim_keys
```
Got it from [the cronjobs` docs](https://modoboa.readthedocs.io/en/latest/manual_installation/modoboa.html#cron-jobs)

**Comment by juliuskiura** [comment]
> After 12 hours it didn't generate automatically. So I ran this (with SUDO) and it worked:
> 
> ```
> sudo /srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py modo manage_dkim_keys
> ```
> 
> Got it from [the cronjobs` docs](https://modoboa.readthedocs.io/en/latest/manual_installation/modoboa.html#cron-jobs)

This has worked for me

**Comment by faisalr3za** [comment]
i've got this response

sudo /srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py modo manage_dkim_keys
System check identified some issues:

WARNINGS:
?: (ckeditor.W001) django-ckeditor bundles CKEditor 4.22.1 which isn't supported anmyore and which does have unfixed security issues, see for example https://ckeditor.com/cke4/release/CKEditor-4.24.0-LTS . You should consider strongly switching to a different editor (maybe CKEditor 5 respectively django-ckeditor-5 after checking whether the CKEditor 5 license terms work for you) or switch to the non-free CKEditor 4 LTS package. See https://ckeditor.com/ckeditor-4-support/ for more on this. (Note! This notice has been added by the django-ckeditor developers and we are not affiliated with CKSource and were not involved in the licensing change, so please refrain from complaining to us. Thanks.)
