### ISSUE TITLE
Unable to delete Identity

### ISSUE THREAD

**Issue by Quiver92** [modoboa/modoboa#3105]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 22.04
* Database Type: PostgreSQL
* Database version: 14
* Modoboa: 2.1.2
* installer used: Yes
* Webserver: Nginx

# Steps To Reproduce
1. From GUI try to delete Identity

# Current behavior
I've got "Internal error" message in GUI
and Error messages in postgresql log:
```
modoboa@modoboa ERROR:  relation "modoboa_migration" does not exist at character 172
modoboa@modoboa STATEMENT:  SELECT "modoboa_migration"."id", "modoboa_migration"."provider_id", "modoboa_migration"."mailbox_id", "modoboa_migration"."username", "modoboa_migration"."_password" FROM "modoboa_migration" WHERE "modoboa_migration"."mailbox_id" IN (182)
```

# Expected behavior
Identety succesfully deleted

# Video/Screenshot link (optional)
![obraz](https://github.com/modoboa/modoboa/assets/13777007/144693c0-f43f-4441-9271-382e47b4490a)

**Comment by tonioo** [comment]
@Quiver92 Looks like you forgot to run migrations
