### ISSUE TITLE
Error: Group matching query does not exist. when i try to create new mailbox simple user

### ISSUE THREAD

**Issue by sherz12r** [modoboa/modoboa#3122]
# Impacted versions

* OS Type: Debian/Ubuntu, Centos/Redhat, Arch, Gentoo, Slack, ...
* OS Version: Number or Name
* Database Type: PostgreSQL / MySQL
* Database version: X.y
* Modoboa: X.X.x
* installer used: Yes/No ?
* Webserver: Nginx/Apache

# Steps to reproduce

# Current behavior

Request Method: | POST
-- | --
https://mail.mydomain.com/admin/accounts/new/
4.2.6
DoesNotExist at /admin/accounts/new/

Group matching query does not exist.
/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/query.py, line 637, in get
modoboa.admin.views.identity.newaccount
/usr/bin/uwsgi-core
3.8.10

</body>
</html>

</body>
</html>
# Expected behavior

# Video/Screenshot link (optional)
![Capture](https://github.com/modoboa/modoboa/assets/46225971/5e976bdd-9398-4837-bf71-fb61bb83a915)

**Comment by tonioo** [comment]
@sherz12r How did you install modoboa?

**Comment by sherz12r** [comment]
@tonioo https://www.linuxbabe.com/mail-server/modoboa-email-server-ubuntu-20-04
i followed these steps if there is issue please guide i stuck in this

**Comment by sherz12r** [comment]
> @sherz12r How did you install modoboa?

please reply

**Comment by tonioo** [comment]
@sherz12r Something went wrong during the install. Can you try to run the installer once again using the --debug option?

**Comment by sherz12r** [comment]
> @sherz12r Something went wrong during the install. Can you try to run the installer once again using the --debug option?

thanks i resolved by reinstalling and writing correct values in installer.cfg

**Comment by meh4i** [comment]
@sherz12r I have the same problem could you help me with correct values in installer.cfg?
at first login i got error which fixed by running `python manage.py migrate` and then create django super user then i could login but i can not create new user because of the same error as you.
