### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by adrians75** [modoboa/modoboa#3124]
Hello, 
I have a fresh install, on a server with Ubuntu 22 I installed Cloudpanel and Modoboa. I followed this tutorial for installation https://www.linuxbabe.com/mail-server/email-server-ubuntu-22-04-modoboa

After completing the installation of Modoboa I received the message "You can enjoy Modoboa at .." but when accessing the link I receive the error "Internal Server Error" on the web page.

I found the following post also on Gihub

_Same problem again, i think some package that it needs is not available since i am installing it inside a lxd container. You should put here instructions how people can debug and restart uwsgi whatever that is.
Hi. Just installed modoboa for the first time and faced this error. Temporary fixed this with setting USE_TZ to False in /srv/modoboa/instance/instance/settings.py file and /etc/init.d/uwsgi restart._

I made the respective setting, restarted, but the problem still hasn't been solved.

What else could I check?
Thank you!

**Comment by NeitsabTeguom** [comment]
Same problem, Internal Server Error (500)
And the fix [adrians75] say, effectively not working.
Some solutions ?

**Comment by redalert99** [comment]
same problem here. after install can't access the webpage due to the "internal server error"....

**Comment by NeitsabTeguom** [comment]
Back to previous 2.1.0 temporarily : sudo ./run.py --version=2.1.0 mydomain.com

**Comment by Spitfireap** [comment]
Hi @NeitsabTeguom,
It seems you are trying to perform an upgrade. [Could you please check that you applied the specific upgrade instructions after your upgrade](https://modoboa.readthedocs.io/en/latest/upgrade.html#specific-instructions) ? 

As for @adrians75 and @redalert99 if it is indeed a fresh install : can you go to the modoboa-installer directory, type this command : `git rev-parse HEAD` and post the result ? Also can you go to `/srv/modoboa/instance/instance/settings.py`, set DEBUG to `True` then restart uwsgi (`systemctl restart uwsgi`) and reload the page ?

**Comment by NeitsabTeguom** [comment]
I do it but not work

**Comment by Spitfireap** [comment]
`modoboa_pdfcredentials` shows up in your log. Please apply the specific instruction for 2.1.0.

**Comment by NeitsabTeguom** [comment]
Traceback (most recent call last):
  File "./instance/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Wed Dec 13 22:08:18 2023 - unable to load app 0 (mountpoint='mail.example.com|') (callable not found or import error)
Wed Dec 13 22:08:18 2023 - --- no python application found, check your startup logs for errors ---
mail.example.com [pid: 1316687|app: -1|req: -1/5] 109.221.81.79 () {54 vars in 1008 bytes} [Wed Dec 13 22:08:18 2023] GET /core/ => generated 21 bytes in 3 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)

**Comment by porrascarlos802018** [comment]
Having same problem here :

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'mail.domainwashere.com',
]
CSRF_TRUSTED_ORIGINS = ['https://*.domainwashere']


what logs file should be checked?

**Comment by lorenzocomotti** [comment]
Having same problem, In my case uwsgi didn't restart.
To solve the problem, I have run `systemctl restart uwsgi.service`

**Comment by cantrust-hosting-cooperative** [comment]
If you are hitting this problem and you are doing an upgrade, you need to make certain you haven't missed any of the [Upgrade Specific Instructions](https://modoboa.readthedocs.io/en/latest/upgrade.html#specific-instructions) between your old version and the new. 

Pay special attention to removing old extensions that have been moved into core.   I had to remove _modoboa_pdf_credentials_ and _modoboa_stats_ from MODOBOA_APPS, because these are both replaced with new core versions.  Once  I did both of them the 500 errors went away.

You will have a _much_ easier time finding the error if you enable debug mode (but do NOT leave it on in production):
```
cd /srv/modoboa/instance
cp settings.py settings.bak.py
sed -i -e 's/DEBUG = False/DEBUG = True/' settings.py
systemctl restart uwsgi
```
Then if you trigger the error you should get some clues about what is wrong, or at least which extension is responsible. 
 The old extensions are not compatible with the rest of the newer code, which causes the 500 errors.

Don't forget to turn off debug mode afterwards!

```
cd /srv/modoboa/instance
sed -i -e 's/DEBUG = True/DEBUG = False/' settings.py
systemctl restart uwsgi
```
