### ISSUE TITLE
Cannot enable DKIM on new domains.

### ISSUE THREAD

**Issue by stutteringp0et** [modoboa/modoboa#3130]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 22.04.3 LTS
* Database Type: MySQL
* Database version: mariadb  Ver 15.1
* Modoboa: 2.2.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Upgraded a while back, attempted to add a new domain - but I cannot enable DKIM.  I found that I can create them if DKIM is disabled, but when I edit the domain to enable it - I get a 500 server error on the post.

# Current behavior

Can't enable DKIM at creation of domain, or editing an existing domain

# Expected behavior

it works

# Video/Screenshot link (optional)

<img width="531" alt="image" src="https://github.com/modoboa/modoboa/assets/310899/958a3810-3cc0-4fe3-a044-66afb60e8f28">

**Comment by tonioo** [comment]
@stutteringp0et Could you enable debug traces and provide more information? (set DEBUG to True inside settings.py and reload uwsgi)

**Comment by stutteringp0et** [comment]
I found the problem - I was missing all of the RQ configurations in settings.py

After reviewing the documentation, I was able to insert the necessary entries to enable DKIM.

Thanks for your attention.

This ticket may be closed.
