### ISSUE TITLE
[Bug] Two-Factor authentication Not working

### ISSUE THREAD

**Issue by imbraintl** [modoboa/modoboa#3150]
Hello, please help, I've been using Modoboa for 1 year now, and from nowhere it shows a screen on login for a Two-Factor authentication code. I went and checked as admin and no Two Factor was active, as a gentleman I did activate Two-Factor authentication. But when I enter the code from my auth app or recovery code I can't bypass the Two-Factor authentication code screen. This is happening to all users, and then recently it is applied to the admin account. Is there a way I can remove Two-Factor authentication? As I don't want it.

**Comment by tonioo** [comment]
@imbraintl Have you updated something before it happens?

**Comment by imbraintl** [comment]
No I have not it was working well. I have not done any updates
