### ISSUE TITLE
Can not access inbox

### ISSUE THREAD

**Issue by camden-git** [modoboa/modoboa#3180]
# Impacted versions

Debian 11
PostgreSQL
Modoboa 2.2.4
installer used: Yes
Nginx

# Steps to reproduce

Fresh install using script, new simple user account, going to the inbox page does not work and causes an error. 

# Current behavior

Causes an error. 
![image](https://github.com/modoboa/modoboa/assets/64759244/4c462fcc-0b60-4ae0-81a6-d592d1424a70)

# Expected behavior

Shows inbox

**Comment by tonioo** [comment]
@camden-git Have you tried to logout/login again ?
