### ISSUE TITLE
DJango and deprecated functions

### ISSUE THREAD

**Issue by arreehm** [modoboa/modoboa#3202]
There's a lot of Django v4 deprecation related bugs. I suggest to limit DJango version.

**Comment by tonioo** [comment]
@arreehm Can you provide more detail please?

**Comment by arreehm** [comment]
If I add all extensions, there are extensions that are non-necessary, because they are now in base, but they use ugettext in django, and it's deprecated. Therefore you cannot use extensions-all in installer.
