### ISSUE TITLE
latest installer didnt install v env for auto mx 

### ISSUE THREAD

**Issue by Sn0wer-alu** [modoboa/modoboa#3208]
latest installer on my debian12 didn't create v env for automx, i manually install 
python3 -m venv /srv/automx/env/
and
@pip3 install future lxml "sqlalchemy<2.0" python-memcached python-dateutil configparser psycopg2-binary@ 
# Impacted versions

* OS Type: Debian  * OS Version: 12
* Database Type: PostgreSQL 
* Database version: 
* Modoboa: latest
* installer used: Yes with --upgrade
* Webserver: Nginx

# Steps to reproduce
just  install

**Comment by tonioo** [comment]
@Sn0wer-alu Do you have logs to provide?

**Comment by Sn0wer-alu** [comment]
how are you can reproduce to log?

**Comment by tonioo** [comment]
@Sn0wer-alu Run the installer once again using the --debug option
