### ISSUE TITLE
After 30 domains I can't access domains at the bottom of the page

### ISSUE THREAD

**Issue by wyliebsd1** [modoboa/modoboa#3212]
# Impacted versions

* OS Type: Debian
* OS Version: 11 Bullseye
* Database Type: PostgreSQL / MySQL
* Database version: X.y
* Modoboa: 2.2.0
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce

I have added a lot of domains to my server around 30.  I added a new domain that started with a W, and could not see it in the list or access it.  The only way i was able to access it was by deleting one of the other domains in order to bring it back into view.  

You could probably just add random named domains to a new instance without any real records or services just to reproduce this in the interface. 

# Current behavior
Cannot see domains at the bottom after 30 domains added. 

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
Is the new or the old UI?

**Comment by Toniob** [comment]
Hi,

Increase the elements per page at the bottom of the preferences page : https://yourdomain/core/#parameters/ . And it’s ok after that.

**Comment by wyliebsd1** [comment]
Aw thanks very much Toniob!  That fixed it right up.

**Comment by wyliebsd1** [comment]
Closing.
