### ISSUE TITLE
password_scheme	[ '"sha512crypt" is not a valid choice.' ]

### ISSUE THREAD

**Issue by usernamehyphen** [modoboa/modoboa#3234]
# Impacted versions

* OS Type: 			Debian
* OS Version: 		12
* Database Type: 	postgres
* Database version:	15.6
* Modoboa:  		2.2.4
* installer used: 		yes
* Webserver: 		nginx
# Steps to reproduce

1. login into a new-admin
2. go to /new-admin/parameters/core (go to settings > general)
3. ctrl+shift+k (open debug console in your browser)
4. no need to change anything, just click on the green floppy disk icon in bottom right corner and then see response from the server indicating failure

# Current behavior
this was installed yesterday, almost everything is in default settings (except maybe for importing users and domains CSVs)
I believe that this might be caused by the users csv import, but i tried to remove those.

## Response
```XHRPUT
XHRPUT
https://mail.<blablabla>/api/v2/parameters/core/
[HTTP/2 400  112ms]

	
password_scheme	[ '"sha512crypt" is not a valid choice.' ]
```

# Expected behavior
status 200
# Video/Screenshot link (optional)
![Screenshot_20240411_133221](https://github.com/modoboa/modoboa/assets/120217643/547de2c7-8cf0-4780-8677-ba744f72d584)

**Comment by tonioo** [comment]
Are you migrating from an old modoboa instance? Is your dovecot server on the same host than the web interface?

**Comment by tonioo** [comment]
Does the CSV file for users include passwords? Are they plain text or not?
And can you check the list of available password schemes from the web interface?

**Comment by usernamehyphen** [comment]
i give up, re-installing now.
