### ISSUE TITLE
dkim_keys_storage_dir	[ "Directory non-writable" ]

### ISSUE THREAD

**Issue by usernamehyphen** [modoboa/modoboa#3235]
# Impacted versions

* OS Type: 			Debian
* OS Version: 		12
* Database Type: 	postgres
* Database version:	15.6
* Modoboa:  		2.2.4
* installer used: 		yes
* Webserver: 		nginx
# Steps to reproduce

1. install this, don't change anything from default.
2. login into a new-admin
3. go to /new-admin/parameters/admin (go to settings > administration)
4. ctrl+shift+k (open debug console in your browser)
5. no need to change anything, just click on the green floppy disk icon in bottom right corner and then see response from the server indicating failure

# Current behavior
this was installed yesterday (found after #3234), nothing was changed in filesystem - everything is either default debian or was changed by installation script.

## Response
```XHRPUT
XHRPUT
https://mail.perfugium.net/api/v2/parameters/admin/
[HTTP/2 400  109ms]

	
dkim_keys_storage_dir	[ "Directory non-writable" ]
0	"Directory non-writable"
```
this can be fixed by a chmod/chown command, but maybe should be set properly? (which user should have write access to this directory apart from the opendkim guy?)
```bash
ls -l /var/lib/dkim
total 8
drwxr-xr-x  2 opendkim opendkim 4096 Apr 10 11:34 .
drwxr-xr-x 36 root     root     4096 Apr 10 11:41 ..
```
# Expected behavior
status 200
# Video/Screenshot link (optional)

![Screenshot_20240411_142447](https://github.com/modoboa/modoboa/assets/120217643/5613c22a-55f3-431f-ae89-c9b1819240c2)

**Comment by tonioo** [comment]
@usernamehyphen This folder should belong to opendkim:opendkim after a successful installation. (see https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/scripts/opendkim.py#L35)
Did you notice anything else?
