### ISSUE TITLE
Mail traffic suddenly is empty, no refreshed statistics 

### ISSUE THREAD

**Issue by blu-IT** [modoboa/modoboa#3243]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 18.04.6 LTS
* Database Type: PostgreSQL
* Database version: 10
* Modoboa: 1.17.0
* installer used: Yes
* Webserver: nginx

# Steps to reproduce

Log into Modoboa and click on statistics.

# Current behavior

Mailtraffic statistis remain empty since 30.04.2024 2 AM, but mails are still send and receivied.

I tried manually 
`/srv/modoboa/env/bin/python /srv/modoboa/manage.py logparser && /srv/modoboa/env/bin/python /srv/modoboa/manage.py update_statistics` 
but get this error 
` /srv/modoboa/env/bin/python: can't open file '/srv/modoboa/manage.py': [Errno 2] No such file or directory
`

Controlled parameter settings for mail.log: /var/mail.log -> these are correct and haven't been changed.
Controlled /srv/modoboa/rrdfiles:

 
![Modoboa](https://github.com/modoboa/modoboa/assets/13665806/10de14fb-abda-4383-a747-fb9381d64f07)

# Expected behavior

Actual statistics are displayed.

Any idea?

**Comment by Spitfireap** [comment]
> I tried manually
> `/srv/modoboa/env/bin/python /srv/modoboa/manage.py logparser && /srv/modoboa/env/bin/python /srv/modoboa/manage.py update_statistics`

The complete path is `/srv/modoboa/instance/manage.py`. You forgot `instance`. Can you try again with this ?

**Comment by blu-IT** [comment]
> > I tried manually
> > `/srv/modoboa/env/bin/python /srv/modoboa/manage.py logparser && /srv/modoboa/env/bin/python /srv/modoboa/manage.py update_statistics`
> 
> The complete path is `/srv/modoboa/instance/manage.py`. You forgot `instance`. Can you try again with this ?

@Spitfireap Thanks for the hint!

Today I checked the statistics again and before I could try the correct command as you send, I saw that since last night they work again - without touching anything! They stopped for nearly 4 days and now they work again. Very strange!

I'll close this issue and if it happens again, I'll report.

Thanks again!
