### ISSUE TITLE
Logging: ERROR modoboa.admin No AAAA record for mail.<domain> but server is smtp.<domain>

### ISSUE THREAD

**Issue by thomas2108** [modoboa/modoboa#3246]
My mail server is not named mail.domain.com but its name is smtp.domain.com. 
Everything according to ipv6 is setup correctly and operates normal.
The only thing is, that modoboa logs 
ERROR modoboa.admin No AAAA record for mail.domain.com
It seems, that the name mail. is incorrectly expected somewhere.

**Comment by Spitfireap** [comment]
Hi,

How modoboa has been installed? Which distro are you running it with? Is it an old install or a new one ? Which domains are in settings.py ALLOWED_HOSTS ?

**Comment by thomas2108** [comment]
Don't know exactly, how it was installed. The person is no longer in our organization. But it's version 2.2.2 and should not be older than 3 month. It's running on Debian 12 - all up to date.
settings.py has just the local servername which is 'mailserver'. No domain at all:
ALLOWED_HOSTS = [
    'mailserver',
]

Because i did not find the name mail.domain.com in any config file I now checked the database. There i found an entry at the admin_mxrecord table which matches. the smtp.domain.com entries are also present

4732	smtp.domain.com	xx.xxx.xxx.xx	0	2024-05-03 15:30:09.616	6
4733	smtp.domain.com	xxxx:xxx:xxx:xxxx::xx	0	2024-05-03 15:30:09.616	6
4734	smtp.domain.com	xx.xxx.xxx.xx	0	2024-05-03 16:30:05.179	4
4735	smtp.domain.com	xxxx:xxx:xxx:xxxx::xx	0	2024-05-03 16:30:05.179	4
4736	mail.domain.com	xx.xxx.xxx.xx	0	2024-05-03 17:00:04.243	5

So the smtp.domain.com entries are each present twice for ipv4 and ipv6 and apparently mail.domain.com is definitely false.

Can I savely delete the last row? Is it correct, that there are duplicate entries ? Where can I find references to the first Id-Column ?

Thanks for your help!

**Comment by thomas2108** [comment]
problem solved
