### ISSUE TITLE
deploy  segmentation fault

### ISSUE THREAD

**Issue by BUPT-wxq** [modoboa/modoboa#3257]
# Impacted versions

* OS Type: Ubuntu
* OS Version: Number or Name
* Database Type:   MySQL
# Steps to reproduce

# Current behavior

I want to deploy an instance for development without docker.
I run next command 
modoboa-admin.py deploy --dburl default:mysql://modoboa:Passw0rd~@127.0.0.1:3306/modoboa --domain localhost --devel instance
I try default:mysql://modoboa:Passw0rd~@127.0.0.1:3306/modoboa
mysql://modoboa:Passw0rd~@127.0.0.1:3306/modoboa
mysql://modoboa:Passw0rd~@localhost:3306/modoboa
but got error  [1]    877 segmentation fault  modoboa-admin.py deploy --dburl  --domain localhost --devel instance
May be my --dburl incorrect

# Expected behavior
how to deploy an instance in virtual environment and access Modoboa at http://localhost:8000
# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@BUPT-wxq I don't think this segmentation fault comes from Modoboa. On which system are you trying to install it?

**Comment by BUPT-wxq** [comment]
> @BUPT-wxq I don't think this segmentation fault comes from Modoboa. On which system are you trying to install it?
May be I deploy locally. Which ubuntu version support modoboa
