### ISSUE TITLE
Incorrect DNS status for subdomains

### ISSUE THREAD

**Issue by hugohamelcom** [modoboa/modoboa#3263]
OS: Debian 12
Modoboa: 2.2.4
Installer used: Yes
Webserver: Nginx
Database: MySQL

I configured a subdomain in Modoboa, and all the records are correct in Cloudflare, and emails are sending and receiving. The issue is with the DNS status in Modoboa, it shows "Domain has no MX record" ("No MX record found for this domain."), DNSBL shows "No information available for this domain.", and SPF shows "No record found".

Interestingly, the DKIM, DMARC and autoconfig are showing "green".

My Cloudflare records are:
- A: mail.sub (points to the IP)
- CNAME: autoconfig.sub
- CNAME: autodiscover.sub
- MX: sub (points to: mail.sub.domain.com)
- TXT: _dmarc.sub (with DMARC configuration)
- TXT: sub (with SPF configuration)
- TXT: modoboa._domainkey.sub (with DKIM)

**Comment by Spitfireap** [comment]
Hi, Is it on new-admin interface or the legacy one ? Can you provide some screenshots of both ?

**Comment by hugohamelcom** [comment]
It is in both.
![image](https://github.com/user-attachments/assets/5f1bfcb1-d350-4fbc-a74e-72384ca49655)
![image](https://github.com/user-attachments/assets/0ca1bdee-f1c7-457f-9ebd-855e0b4ba71a)

**Comment by hugohamelcom** [comment]
It says: `/srv/modoboa/env/bin/python: can't open file '/home/username/manage.py': [Errno 2] No such file or directory`

**Comment by Spitfireap** [comment]
Sorry, didn't give you the full path : `/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py modo check_mx

**Comment by Spitfireap** [comment]
:(. 

Can you try changing the DNS server ? 
![image](https://github.com/user-attachments/assets/282e57ba-e51e-4f10-8aee-5b2d77aa47d1)

**Comment by hugohamelcom** [comment]
Interestingly, it seems one of the directory doesn't have the right permission.
I check the permissions and it returned: `drwxr-xr-x 2 opendkim opendkim 4096 Jun  7 17:28 /var/lib/dkim`
![image](https://github.com/user-attachments/assets/a29a9697-4844-4ad8-a356-1441e05a06c1)

**Comment by Spitfireap** [comment]
Can you give the write permission to the group and try again ? When did you install modo ?

**Comment by hugohamelcom** [comment]
I was installed at the beginning of June 2024. I still get the "Directory non-writable" error even if /var/lib/dkim have the right permission: drwxrwxr-x 2 opendkim opendkim

**Comment by Spitfireap** [comment]
What is the output of `groups modoboa` ?

**Comment by hugohamelcom** [comment]
It returns: `modoboa : modoboa`

**Comment by Spitfireap** [comment]
So can you add `opendkim` ? `usermod -a -G opendkim modoboa`, restart uwsgi (`systemctl restart uwsgi`), and try again :)

**Comment by hugohamelcom** [comment]
Perfect, it worked! I just re-ran `/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py modo check_mx` and now it shows the DNS correctly in both interface.
![image](https://github.com/user-attachments/assets/553b307a-573c-413f-896c-a244f8353001)
![image](https://github.com/user-attachments/assets/a805e261-53e7-460b-b6ce-c733d2ec8a3b)

**Comment by Spitfireap** [comment]
After changing your DNS ?

**Comment by hugohamelcom** [comment]
I changed the DNS to 1.1.1.1 and was able to save it with the changes. I just tested without the custom DNS (reran the MX command) and it is still working. So, my understanding is that the custom DNS was not necessarily the issue, but mostly the group and directory permission.

**Comment by Spitfireap** [comment]
Nice !
