### ISSUE TITLE
An internal error occured - KeyError at /webmail/ 'password'

### ISSUE THREAD

**Issue by TSKNF** [modoboa/modoboa#3299]
# Impacted versions

* OS Type: Proxmox 8.2.1
* OS Version: Debian 12
* Database Type: PostgreSQL
* Database version: 16+261.pgdg120+1
* Modoboa: 2.3.0
* installer used: Yes
* Webserver: Nginx
# Steps to reproduce
Step 1: Create a Debian 12 LXC container in Proxmox 8.2.1.
Step 2: Install Modoboa according to the instructions
Step 3: Create a simple user
# Current behavior
If you now log in with this user everything seems to work but if you click on webmail you get this error message: 

![modoboa 5](https://github.com/user-attachments/assets/e17fbc4f-76bb-47d6-a1da-11bea0dc0d99)
"Sorry An internal error occured."

An image of the error message with Debug True:

![modoboa 3](https://github.com/user-attachments/assets/1d620122-449a-40a3-82a5-e568d5a212e0)
"KeyError at /webmail/          'password'"

This message appears during setup: 

![modoboa 1](https://github.com/user-attachments/assets/ca02f5b1-088e-419d-b7e4-0a61d9a3932e)
"User dovocot already exists, skipping creation but please make sure the /srv/vmail directory exists."

When I try to delete a user, I get this error message:

![modoboa 4](https://github.com/user-attachments/assets/01f28f13-897a-4ae0-a6a2-9af6085731fd)

# Expected behavior
The webmail interface should work without errors.
Deleting accounts should also work without errors.
There should not already be a user with the name dovocot.

**Comment by VladislavGatsenko** [comment]
same error

**Comment by nadihighlander** [comment]
Hi
debian 11 , clean install (postwhite is not installed)
same error 
calendar and contacts works

**Comment by donholloway** [comment]
Getting similar error.  Install seems OK.  After creating a domain and user in admin, when switching to added user, the webmail errors - first with a generic problem.  I switched into debug and got this.  I had read something a while back about no default session variable being set, but it was from 2015.  

<html><body>
<h1>KeyError
       at /webmail/</h1>
  <pre class="exception_value">'password'</pre>
  
Request Method: | GET
-- | --
https://mail.manysparrows.io/webmail/
4.2.15
KeyError
'password'
/srv/modoboa/env/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py, line 53, in __getitem__
modoboa_webmail.views.index
/usr/bin/uwsgi-core
3.10.12
['.',  '',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/srv/modoboa/env/lib/python3.10/site-packages',  '/srv/modoboa/env/lib/python3.10/site-packages/setuptools/_vendor']
Tue, 13 Aug 2024 16:28:25 -0400


</body>
</html>

**Comment by theitmachine** [comment]
Same error

**Comment by TSKNF** [comment]
That makes me confident that we can solve the problem.

The message in the setup that a Dovecot user already exists is irrelevant. I named the user differently in the setup. The message did not appear but the result was the same.

Whether MariaDB or Postresql is used makes no difference.

Can someone tell me if modoboa supports ipv6 only?

**Comment by VladislavGatsenko** [comment]
By the way, connecting external clients doesn't work either. Who has the same thing?

And file2ban service starts with an error

**Comment by Spitfireap** [comment]
The password thing on the webmail is logic, we need to push an update for webmail since we've added oauth2 login.
@VladislavGatsenko the external client should work though. Can you add detail on this error ?

**Comment by donholloway** [comment]
Excellent news.  Is there a way that I can update the webmail code once it is finished?  (or can I be a tester?)

**Comment by Spitfireap** [comment]
The update will be fairly easy to apply.
I think that the hotfix will consist in asking the user password the first time you open the webmail for the session before we've got time to fully implement oauth2 flow (unless @tonioo gets more time to work on that :D ). I'll have to work on this hotfix this weekend.

**Comment by Spitfireap** [comment]
Ok can those affected by the issue try this : 
 - make sur you have modoboa 2.3.0 fully updated and working
 - `sudo -u modoboa -i bash`
 - `/srv/modoboa/env/bin/pip install modoboa-webmail==1.9.1b1`
 - as root : `systemctl restart uwsgi`

To revert do all the steps but instead of 1.9.1b1 put 1.9.0 :)

**Comment by ultr41337h4xor** [comment]
Same issue here I believe. I am also on Debian 12, used the run.py --upgrade script to update my installation. After the upgrade, I've noticed the new interface is used as default, however I can't log in (Internal Server Error when I enter my login data). Also can't send any emails from an external client.

![image](https://github.com/user-attachments/assets/95961d09-a17d-450a-8898-4210aca40d61)

![image](https://github.com/user-attachments/assets/e0903699-6526-48e4-8657-86ff4285ccf0)


> Ok can those affected by the issue try this :
> 
>     * make sure you have modoboa 2.3.0 fully updated and working
> 
>     * `sudo -u modoboa -i bash`
> 
>     * `/srv/modoboa/env/bin/pip install modoboa-webmail==1.9.1b1`
> 
>     * as root : `systemctl restart uwsgi`
> 
> 
> To revert do all the steps but instead of 1.9.1b1 put 1.9.0 :)

Tried it, didn't help, unfortunately.

**Comment by Spitfireap** [comment]
This is not the same issue. This issue is about strictly the webmail. 
[Please check the specific upgrade instructions for 2.3.0](https://modoboa.readthedocs.io/en/latest/upgrade.html#version-2-3-0)

**Comment by donholloway** [comment]
> Ok can those affected by the issue try this :
> 
>     * make sure you have modoboa 2.3.0 fully updated and working
> 
>     * `sudo -u modoboa -i bash`
> 
>     * `/srv/modoboa/env/bin/pip install modoboa-webmail==1.9.1b1`
> 
>     * as root : `systemctl restart uwsgi`
> 
> 
> To revert do all the steps but instead of 1.9.1b1 put 1.9.0 :)

Tried it, went into webmail and now got a screen asking for password, so progress, then got "authentication error".

**Comment by jrosier** [comment]
> Ok can those affected by the issue try this :
> 
>     * make sure you have modoboa 2.3.0 fully updated and working
> 
>     * `sudo -u modoboa -i bash`
> 
>     * `/srv/modoboa/env/bin/pip install modoboa-webmail==1.9.1b1`
> 
>     * as root : `systemctl restart uwsgi`
> 
> 
> To revert do all the steps but instead of 1.9.1b1 put 1.9.0 :)

Works for me!
