### ISSUE TITLE
django-ckeditor bundles CKEditor 4.22.1 isn't supported anymore

### ISSUE THREAD

**Issue by bosgold** [modoboa/modoboa#3316]
# Impacted versions

* OS Version: Ubuntu 18.04
* Database Type: MySQL
* Database version: MariaDB 10.6.15
* Modoboa: 2.2.4
* Webserver: Nginx
* Pyhton: 3.8.16
* pip: 24.1.1

# Steps to reproduce

Starting the upgrade procedure to Modoboa 2.3.1.
Including the by pip desired upgrade of pip during this procedure.

# Current behavior

Upgrade as such was successfull. But all cronjobs " $PYTHON $INSTANCE/manage.py ..." throw out a warning message

> System check identified some issues:
> 
> WARNINGS:
> ?: (ckeditor.W001) django-ckeditor bundles CKEditor 4.22.1 which isn't supported anmyore and which does have unfixed security issues, see for example https://ckeditor.com/cke4/release/CKEditor-4.24.0-LTS . You should consider strongly switching to a different editor (maybe CKEditor 5 respectively django-ckeditor-5 after checking whether the CKEditor 5 license terms work for you) or switch to the non-free CKEditor 4 LTS package. See https://ckeditor.com/ckeditor-4-support/ for more on this. (Note! This notice has been added by the django-ckeditor developers and we are not affiliated with CKSource and were not involved in the licensing change, so please refrain from complaining to us. Thanks.)

# Expected behavior

No such warnings.
Besides redirecting the cronjob warnings/errors to /dev/null. Don't think this is a good idea.

**Comment by belzebub40k** [comment]
Seems to be a known upstream issue with no real fix but you can silence the warning via `SILENCED_SYSTEM_CHECKS`.

https://github.com/django-ckeditor/django-ckeditor/issues/764

```
SILENCED_SYSTEM_CHECKS = [
    ...
    "ckeditor.W001",  # CKEditor 4.22.1 warning
]
```

**Comment by VladlenO** [comment]
> Seems to be a known upstream issue with no real fix but you can silence the warning via `SILENCED_SYSTEM_CHECKS` in _settings.py_.
> 
> [django-ckeditor/django-ckeditor#764](https://github.com/django-ckeditor/django-ckeditor/issues/764)
> 
> ```
> SILENCED_SYSTEM_CHECKS = [
>     ...
>     "ckeditor.W001",  # CKEditor 4.22.1 warning
> ]
> ```

In which file exactly should I specify the prohibition on updating? Thanks.

**Comment by belzebub40k** [comment]
@VladlenO in the **settings.py** of your modoboa instance. There should already be a section SILENCED_SYSTEM_CHECKS.

**Comment by renarios** [comment]
Is it possible to just install django-ckeditor-5, or does the configuration of modoboa have to be changed for that?

**Comment by bosgold** [comment]
Replacing CKEditor 4 by django-ckeditor 5 does not work.
Some of the things I already tried.
