### ISSUE TITLE
problem coonetion modboa

### ISSUE THREAD

**Issue by draconMo** [modoboa/modoboa#3323]
Hello

OS Type: Debian12

Installation settings are default

installation went without problems

ports are open on the firewall 25,143,587
I'm trying to connect to the post server by using Mozilla Thunderbird
I get an error when connecting

dovecot log 

Oct 15 12:47:39 andreydracon.ru dovecot[222958]: auth: Panic: file http-client.c: line 646 (http_client_context_close): assertion failed: (cctx->clients_list == NULL)
Oct 15 12:47:39 andreydracon.ru dovecot[222958]: auth: Error: Raw backtrace: #0 t_askpass[0x7f952e67abe0] -> #1 backtrace_append[0x7f952e67ae50] -> #2 backtrace_get[0x7f952e67afe0] -> #3 execvp_const[0x7f952e6861d0] -> #4 i_syslog_fatal_handler[0x7f952e686b40] -> #5 i_panic[0x7f952e5dc0d4] -> #6 [unw_get_proc_name() failed: -10] -> #7 io_loop_set_current[0x7f952e69cc00] -> #8 [unw_get_proc_name() failed: -10] -> #9 [unw_get_proc_name() failed: -10] -> #10 io_loop_call_io[0x7f952e69deb0] -> #11 io_loop_handler_run_internal[0x7f952e69fbb0] -> #12 io_loop_handler_run[0x7f952e69fd40] -> #13 io_loop_run[0x7f952e69ff10] -> #14 [unw_get_proc_name() failed: -10] -> #15 [unw_get_proc_name() failed: -10] -> #16 passdb_cache_deinit[0x55bfeb19f190] -> #17 auths_init[0x55bfeb181300] -> #18 main[0x55bfeb17f920] -> #19 __libc_init_first[0x7f952e31b1d0] -> #20 __libc_start_main[0x7f952e31b280] -> #21 _start[0x55bfeb17fea0]
Oct 15 12:47:39 andreydracon.ru dovecot[222955]: master: Error: service(auth): command startup failed, throttling for 60.000 secs
Oct 15 12:47:39 andreydracon.ru dovecot[222958]: auth: Fatal: master: service(auth): child 226133 killed with signal 6 (core dumps disabled - https://dovecot.org/bugreport.html#coredumps)
Oct 15 12:47:39 andreydracon.ru dovecot[222958]: imap-login: Disconnected: Auth process broken (disconnected before auth was ready, waited 0 secs): user=<>, rip=5.167.55.204, lip=193.233.20.149, session=

For the sake of experimentation, I installed everything the same on  Ubuntu serber 22.04 and everything works

Is debian 12 supported? Or is it worth using Debian 11, Ubuntu 22.04 ?

**Comment by tonioo** [comment]
@draconMo Debian 12 is supported. I've pushed a fix to the installer this morning, could you try again?

**Comment by tonioo** [comment]
Can you run using the --debug option please?

**Comment by draconMo** [comment]
Installing dovecot
Reading package lists...
Building dependency tree...
Reading state information...
postgresql is already the newest version (15+248).
postgresql-server-dev-all is already the newest version (248).
The following package was automatically installed and is no longer required:
  libgnutls-dane0
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Synchronizing state of postgresql.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable postgresql
● postgresql.service - PostgreSQL RDBMS
     Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; preset: enabled)
     Active: active (exited) since Wed 2024-10-16 17:00:14 MSK; 1min 46s ago
   Main PID: 41755 (code=exited, status=0/SUCCESS)
        CPU: 1ms

Oct 16 17:00:14 andreydracon.ru systemd[1]: Starting postgresql.service - PostgreSQL RDBMS...
Oct 16 17:00:14 andreydracon.ru systemd[1]: Finished postgresql.service - PostgreSQL RDBMS.
Reading package lists...
Building dependency tree...
Reading state information...
Package dovecot-imapd is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  dovecot-sieve

Package dovecot-lmtpd is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package dovecot-managesieved is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package dovecot-pgsql is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package dovecot-sieve is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Release 'bookworm-backports' for 'dovecot-pgsql' was not found
E: Release 'bookworm-backports' for 'dovecot-imapd' was not found
E: Release 'bookworm-backports' for 'dovecot-lmtpd' was not found
E: Release 'bookworm-backports' for 'dovecot-managesieved' was not found
E: Release 'bookworm-backports' for 'dovecot-sieve' was not found

**Comment by tonioo** [comment]
Can you check which files are present in the /etc/apt/sources.list.d folder please?

**Comment by draconMo** [comment]
root@andreydracon:/etc/apt/sources.list.d# cat backports.list
deb http://deb.debian.org/debian bookworm-backports main

root@andreydracon:/etc/apt/sources.list.d#

**Comment by tonioo** [comment]
Strange, then dovecot packages should install properly...
Could you try to manually run this:
> sudo apt update
> sudo apt install dovecot-imapd/bookworm-updates

**Comment by draconMo** [comment]
root@andreydracon:~# apt update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:4 http://deb.debian.org/debian bookworm-backports InRelease [59.0 kB]
Get:5 http://deb.debian.org/debian bookworm-backports/main amd64 Packages [252 kB]
Get:6 http://deb.debian.org/debian bookworm-backports/main Translation-en [211 kB]
Fetched 625 kB in 1s (734 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
root@andreydracon:~# apt install dovecot-imapd/bookworm-updates
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package dovecot-imapd is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  dovecot-sieve

E: Release 'bookworm-updates' for 'dovecot-imapd' was not found

**Comment by tonioo** [comment]
I meant :
> sudo apt install dovecot-imapd/bookworm-backports

Sorry

**Comment by draconMo** [comment]
The installation was completed, please tell me if I need to do anything after installation dovecot for it to work correctly modboa

**Comment by tonioo** [comment]
If the initial problem you reported has disappeared, then you're good to go

**Comment by draconMo** [comment]
Mozilla Thunderbird 
does not connect to the mailbox, I can see it in the log
not work  (journalctl --since today | grep dovecot)

Oct 17 12:19:02 andreydracon.ru dovecot[499]: imap-login: Disconnected: Aborted login by logging out (no auth attempts in 0 secs): user=<>, rip=5.167.55.204, lip=193.233.20.149, session=<3Mdnragk7MMFpzfM

**Comment by tonioo** [comment]
What are your settings?

**Comment by draconMo** [comment]
![1](https://github.com/user-attachments/assets/72ab528e-6d27-435f-a70c-28848bf6c6f1)

**Comment by draconMo** [comment]
firewall 
root@andreydracon:~# nft list ruleset
table ip FirewallIPV4 {
        chain input {
                type filter hook input priority filter; policy drop;
                iifname "lo" accept
                ct state established,related accept
                ip saddr 192.168.250.0/24 icmp type { destination-unreachable, echo-request, parameter-problem } accept
                ip saddr { 5.167.55.204, 5.180.240.78, 87.241.229.112, 94.180.57.68, 109.107.170.153 } tcp dport 22 accept
                ip saddr { 5.167.55.204, 5.180.240.78, 87.241.229.112, 94.180.57.68, 109.107.170.153 } tcp dport 443 accept
                tcp dport { 25, 143 } accept
        }

        chain forward {
                type filter hook forward priority filter; policy drop;
        }

        chain output {
                type filter hook output priority filter; policy accept;
        }
}
table ip6 FirewallIPV6 {
        chain input {
                type filter hook input priority filter; policy drop;
                iifname "lo" accept
        }

        chain forward {
                type filter hook forward priority filter; policy drop;
        }

        chain output {
                type filter hook output priority filter; policy accept;
        }
}

**Comment by tonioo** [comment]
The IMAP part should work. You can also try with port 993 and TLS mode

**Comment by draconMo** [comment]
993 tcp
Oct 17 13:48:23 andreydracon.ru dovecot[540]: imap-login: Disconnected: Connection closed: SSL_accept() failed: error:0A000412:SSL routines::sslv3 alert bad certificate: SSL alert number 42 (no auth atte mpts in 0 secs): user=<>, rip=5.167.55.204, lip=193.233.20.149, TLS handshaking: SSL_accept() failed: error:0A000412:SSL routines::sslv3 alert bad certificate: SSL alert number 42, session=<V2Ht7Kkkq90Fp zfM>
143 tcp
Oct 17 13:48:30 andreydracon.ru dovecot[540]: imap-login: Disconnected: Aborted login by logging out (no auth attempts in 0 secs): user=<>, rip=5.167.55.204, lip=193.233.20.149, session=<WoRW7akksd0FpzfM

**Comment by draconMo** [comment]
postfix 

Oct 17 13:55:20 andreydracon.ru postfix/postscreen[1912]: CONNECT from [5.167.55.204]:59950 to [193.233.20.149]:25
Oct 17 13:55:20 andreydracon.ru postfix/dnsblog[1913]: addr 5.167.55.204 listed by domain zen.spamhaus.org as 127.255.255.254
Oct 17 13:55:20 andreydracon.ru postfix/postscreen[1912]: PASS OLD [5.167.55.204]:59950
Oct 17 13:55:21 andreydracon.ru postfix/smtpd[1915]: warning: hostname 5x167x55x204.static-business.rostov.ertelecom.ru does not resolve to address 5.167.55.204: Name or service not known
Oct 17 13:55:21 andreydracon.ru postfix/smtpd[1915]: connect from unknown[5.167.55.204]
Oct 17 13:55:21 andreydracon.ru postfix/smtpd[1915]: warning: SASL: Connect to Dovecot auth socket 'private/auth' failed: No such file or directory
Oct 17 13:55:21 andreydracon.ru postfix/smtpd[1915]: fatal: no SASL authentication mechanisms
Oct 17 13:55:22 andreydracon.ru postfix/master[980]: warning: process /usr/lib/postfix/sbin/smtpd pid 1915 exit status 1
Oct 17 13:55:22 andreydracon.ru postfix/master[980]: warning: /usr/lib/postfix/sbin/smtpd: bad command startup -- throttling
racon.ru postfix/master[980]: warning: /usr/lib/postfix/sbin/smtpd: bad command startup -- throttling

**Comment by tonioo** [comment]
What kind of certificate did you generate?

**Comment by draconMo** [comment]
The certificate was created during the modoboa installation, all settings are default.

**Comment by tonioo** [comment]
Then it's probably a self-signed one. Can you try with a LE one? (you need to update the config file and rerun the isntaller)

**Comment by draconMo** [comment]
Don't quite understand what needs to be done?

**Comment by tonioo** [comment]
You need a valid certificate (a LetsEncrypt one), that's something the installer can generate for you but you need to update the config file

**Comment by draconMo** [comment]
Looks like a problem looks like the problem is dovecot 

# 2.3.21.1 (d492236fa0): /etc/dovecot/dovecot.conf
# Pigeonhole version 0.5.21.1 (49005e73)
# OS: Linux 6.1.0-26-amd64 x86_64 Debian 12.7
# Hostname: andreydracon.ru
mail_location = mbox:~/mail:INBOX=/var/mail/%u
mail_privileged_group = mail
namespace inbox {
  inbox = yes
  location =
  mailbox Drafts {
    special_use = \Drafts
  }
  mailbox Junk {
    special_use = \Junk
  }
  mailbox Sent {
    special_use = \Sent
  }
  mailbox "Sent Messages" {
    special_use = \Sent
  }
  mailbox Trash {
    special_use = \Trash
  }
  prefix =
}
passdb {
  driver = pam
}
protocols = " imap"
ssl_cert = </etc/dovecot/private/dovecot.pem
ssl_client_ca_dir = /etc/ssl/certs
ssl_dh = # hidden, use -P to show it
ssl_key = # hidden, use -P to show it
userdb {
  driver = passwd
}

# 2.3.21.1 (d492236fa0): /etc/dovecot/dovecot.conf
# Pigeonhole version 0.5.21.1 (49005e73)
# OS: Linux 6.1.0-26-amd64 x86_64 Debian 12.7
# Hostname: andreydracon.ru
mail_location = mbox:~/mail:INBOX=/var/mail/%u
mail_privileged_group = mail
namespace inbox {
  inbox = yes
  location =
  mailbox Drafts {
    special_use = \Drafts
  }
  mailbox Junk {
    special_use = \Junk
  }
  mailbox Sent {
    special_use = \Sent
  }
  mailbox "Sent Messages" {
    special_use = \Sent
  }
  mailbox Trash {
    special_use = \Trash
  }
  prefix =
}
passdb {
  driver = pam
}
protocols = " imap"
ssl_cert = </etc/dovecot/private/dovecot.pem
ssl_client_ca_dir = /etc/ssl/certs
ssl_dh = # hidden, use -P to show it
ssl_key = # hidden, use -P to show it
userdb {
  driver = passwd
}

if corrected 10-master.conf

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0666
  }
    authorization starts working


It looks like the dovecote configuration files remained original

**Comment by tonioo** [comment]
Did you complete the installation using the installer or manually?

**Comment by draconMo** [comment]
Did the following
root@andreydracon:/etc/modoboa-installer# python3 run.py and******.ru
Welcome to Modoboa installer!

Checking the installer...
Installer seems up to date!
Checks complete

Configuration file installer.cfg not found, creating new one.
Notice:
It is recommanded to run this installer on a FRESHLY installed server.
(ie. with nothing special already installed on it)

Warning:
Before you start the installation, please make sure the following DNS records exist for domain 'andreydracon.ru':
mail IN A
@ IN MX mail.andrey******.ru.

Your mail server will be installed with the following components:
fail2ban modoboa automx amavis clamav dovecot nginx razor postfix postwhite spamassassin uwsgi radicale opendkim
Do you confirm? (Y/n) y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Generating new self-signed certificate
Installing amavis
Installing spamassassin
Installing razor
Installing clamav
Installing fail2ban
Installing modoboa
Installing automx
Installing radicale
Installing uwsgi
Installing nginx
Installing opendkim
Installing postfix
Installing postwhite
Installing dovecot
Failed to install dependencies

had a dream
E: Release 'bookworm-backports' for 'dovecot-pgsql' was not found
E: Release 'bookworm-backports' for 'dovecot-imapd' was not found
E: Release 'bookworm-backports' for 'dovecot-lmtpd' was not found
E: Release 'bookworm-backports' for 'dovecot-managesieved' was not found
E: Release 'bookworm-backports' for 'dovecot-sieve' was not found


then executed

apt install dovecot-imapd/bookworm-backports

**Comment by tonioo** [comment]
Ok, then indeed the installation is not complete. Can you run the installer again to see if it completes now?

**Comment by draconMo** [comment]
Hello and thanks for your help!

The path to success - 
I ran the installation script again (I didn’t recreate the certificate, I agreed with everything else).
