### ISSUE TITLE
modoboa 2.3.2 missing sieve filters configuration menu

### ISSUE THREAD

**Issue by zottimusprime** [modoboa/modoboa#3361]
# Impacted versions

* OS Type: Debian 12
* OS Version:  12.8
* Database Type: PostgreSQL 
* Database version: 15.10
* Modoboa: 2.3.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
* Run installer with:  ./run.py --stop-after-configfile-check <your domain>
* modify hostname parameter in installer.cfg (eg: change the default one which is set to "mail" )
* run the real setup with:  ./run.py <your domain>
* create a domain
* create at least 1 mail user

# Current behavior
Log in webmail interface with a simple email user (not the admin!) : no more sieve filters configuration menu: only "Settings" and "Logout" options are available

# Expected behavior
filters configuration option should be listed on menu by clicking on username at the top right corner of webmail screen, between  "Settings" and "Logout".

**Comment by tonioo** [comment]
@zottimusprime Sieve filters are now available in the new UI

**Comment by zottimusprime** [comment]
Many sorries for bothering you again, but I can't find where to configure per user sieve filter in my webmail under modoboa 2.3.2. Webmail interface is the same as previous versions. Could you  please point me where is the new interface you mentioned?
Best regards

**Comment by tonioo** [comment]
You won't find the feature in the webmail but in the the User Interface (the one you can find under /new-admin)

**Comment by zottimusprime** [comment]
Found it! Thanks for support, sir!
Best regards
