### ISSUE TITLE
Catchall does not work for domain-alias

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa#466]
**Originally created by C B on 2013-10-10T10:29:19Z**

In my postfix-dovecot setup with modoboa 1.0.1 is a domain example.com with an alias of example.alias configurated. The postfix accepts mail for the configured alias username@example.{com,alias} -> external@domain.tld, and the catchall configured for example.com does work as expected. Contrary to the expectation the catchall does not work for the domain-alias example.alias.
A catchall for the domain-alias example.alias cannot be configured in the webinterface, as the domain is unknown.

**Comment by fompi** [comment]
A workaround is not a solution. In the meantime, I've used this query to solve this problem:

```
(SELECT mb.address || '@' || dom.name FROM admin_mailbox mb INNER JOIN admin_domain dom ON mb.domain_id=dom.id WHERE mb.id IN (SELECT al_mb.mailbox_id FROM admin_alias al INNER JOIN admin_domain dom ON al.domain_id=dom.id INNER JOIN admin_alias_mboxes al_mb ON al.id=al_mb.alias_id WHERE al.enabled AND al.address='*' AND (dom.name='%d' OR dom.name=(SELECT dom.name FROM admin_domain dom INNER JOIN admin_domainalias domal ON dom.id=domal.target_id WHERE domal.name='%d' AND domal.enabled AND dom.enabled)) AND dom.enabled)) UNION (SELECT al.extmboxes FROM admin_alias al INNER JOIN admin_domain dom ON al.domain_id=dom.id WHERE al.enabled AND al.extmboxes<>'' AND al.address='*' AND (dom.name='%d' OR dom.name=(SELECT dom.name FROM admin_domain dom INNER JOIN admin_domainalias domal ON dom.id=domal.target_id WHERE domal.name='%d' AND domal.enabled AND dom.enabled)) AND dom.enabled)
```

But I assume it should be worked on. Why won't create vies to clarify the map files?

**Comment by tonioo** [comment]
Yes, it could be useful. But I must admit my knowledge about views is pretty limited. Do you have any example ?
