### ISSUE TITLE
LDAP Sync

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa#482]
**Originally created by Gérald Colangelo on 2012-04-26T13:10:01Z**

Modoboa is able to use a LDAP directory to log user in and would create automatically mailboxes if don't exist.
This can be consider as a "basic" LDAP synchronization processus.
The only problem is that user must first login to modoboa to get his mailbox created.

A periodical check against the LDAP directory to create new mailboxes may be useful and may make Modoboa a choice for "Active directory powered companies"...

**Comment by almereyda** [comment]
@pierreozoux In https://github.com/tonioo/modoboa/issues/821#issuecomment-247705224 you mentioned we would need Modoboa to be a read/write LDAP editor. It shouldn't be too hard to reconfigure Postfix and Dovecot to directly authenticate against such a service, if available. Deployment and configuration of an LDAP service and a separate LDAP management plugin can be managed with the `-installer`, then. The syncing idea appears a little clumsy, to be frank.

**Comment by tonioo** [comment]
@almereyda What would you do instead? Modoboa will never be able to use an LDAP directory as storage backend since Django can't do it...
