### ISSUE TITLE
Add reply-to tag for distribution lists

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa#485]
**Originally created by Dalnix AB on 2013-05-15T11:51:45Z**

Distribution lists in modoboa is awesome! Hurray!

Only thing i miss is when i send an email to a list, people answer to me in person instead of to the list. 

I would like to have (maybe optional) modoboa add a reply-to header when sent to distrubution lists so that when people hit reply it goes back to the list.

**Comment by ebrahim** [comment]
A mailing list server usually sets the "Sender" address of outgoing emails to address of the sending mailing list.

**Comment by patrickbenkoetter** [comment]
* Ebrahim Mohammadi <reply@reply.github.com>:
> A mailing list server usually sets the "Sender" address of outgoing emails to address of the sending mailing list.

This should be optional as there usually are fierce battles whether it right
[tm] or not to set Reply-to:-headers.

p@rick

-- 
[*] sys4 AG
 
https://sys4.de, +49 (89) 30 90 46 64
Franziskanerstraße 15, 81669 München
 
Sitz der Gesellschaft: München, Amtsgericht München: HRB 199263
Vorstand: Patrick Ben Koetter, Marc Schiffbauer
Aufsichtsratsvorsitzender: Florian Kirstein

**Comment by tonioo** [comment]
What's the best way to add a header to an outgoing message? Use smtpd_sender_restrictions with a check_sender_access (PREPEND)?
@patrickbenkoetter ?

**Comment by piwats** [comment]
Careful here: mailing list as per RFC must have the obvious list-post, list-id, list-subscribe,lists unsubscribe and the precedence header, or else the emails will be treated as spam by various spam filters.

Also there are some caveats to take care of, as f.i. dkim signing and dmarc policies ( which if the headers are modified, will break the mailing list)

**Comment by tonioo** [comment]
I think @piwats is right, Modoboa is not a mailing list manager like Mailman. Would it be complicated to build a "simple" plugin for that ? (I mean create a simple ML manager)

**Comment by Avalarion** [comment]
You have to handle a lot of stuff for a Mailinglist Tool, I would drop this feature and perhaps implement something like mailman integration ( perhaps take a look how proprietary solutions work here... )
