### ISSUE TITLE
Add Cluebringer/policyd Support

### ISSUE THREAD

**Issue by SomeGeek** [modoboa/modoboa#575]
We should integrate Postfix [Cluebringer](https://www.policyd.org) support. It's nearly essential when it comes to mail security. Plays nice with amavisd-new as well.

**Comment by almereyda** [comment]
Is this discussion still about `policyd`, else it could be renamed or closed.
People seem to like Modoboa for using `postscreen` instead: https://twitter.com/TwizzyDizzy/status/732204315511783425

**Comment by hadifarnoud** [comment]
I was looking for policyD integration as well. My issue is some users on my server send bulk emails and that puts everyone's emails in spam. it is very hard to find the responsible account manually.

so, I understand policyD or postfwd will give me ability to limit send per account/domain.

is there a way I can set it up right now? do you have any ETA?

**Comment by tonioo** [comment]
@hadifarnoud No ETA for this but if your need is just about limiting the sending rate, you can already do it using postfix (example: https://wiki.deimos.fr/Postfix:_limit_outgoing_mail_throttling.html).

**Comment by hadifarnoud** [comment]
@tonioo I want to set limit per sending account/domain. that does the opposite.
