### ISSUE TITLE
[Feature Request] ACL/Shared Mailboxes

### ISSUE THREAD

**Issue by piwats** [modoboa/modoboa#580]
Hello Antoine,

having the ability to control the acl/shared mailboxes of dovecot also from modoboa could be very useful in many use cases:

http://wiki2.dovecot.org/SharedMailboxes/Shared
http://wiki2.dovecot.org/ACL

-Paul

**Comment by tonioo** [comment]
@piwats Hi Paul, I know it's been a while but is this a feature you'd offer only to administrators or to everyone?

**Comment by JayBeRayBearGun** [comment]
I am missing this feaure as well. Coming from an exim/cyrus combo this was really easy to set up with the cyradm cli (inlcuding acls). I see two main scenario:

1) a user makes one of his mailbox/folders available to one or more other users (typically office or family situation)_
2) administrator does the the same as above for a number of users (ie. on behalf of) This could be the case when sharing control is turned off for regular users.

**Comment by tonioo** [comment]
dovecot provides the same kind of command line utility: `doveadm`. There is a subcommand to manage ACLs (http://wiki2.dovecot.org/Tools/Doveadm/ACL).
Regarding the integration to Modoboa, I'm still wondering what would be the best place to add this feature into the GUI... The admin case is pretty easy to solve but  the user one is a bit more tricky unless we say it is associated to the webmail... Do you know how Roundcube manages this?

**Comment by JayBeRayBearGun** [comment]
Ah great I'll investigate it,... I have only a fleeting acquaintance with roundcube so can't be of much help there (just looked for it). In my opinion the most logical location in the webmail iterface would be in the little gear icon/button on the bottom left of the folder view. Adding a folder share option there would seem like a good place. The admin case should be somewhere in the setting & parameter panel perhaps. I am not yet familiar enough with modoboa to give good feedback here.

**Comment by JayBeRayBearGun** [comment]
When I user doveadm to lookup mailboxes I only get the standard set and not the actual folders. Besides I can't seem to specify the user. Could this be because this is handled through postgresql?

**Comment by JayBeRayBearGun** [comment]
OK I found out how roundcube does it. I'll email you two screenshots (couldnt find a way to upload/include it here).

**Comment by tuxis-ie** [comment]
We'd like to see this as well. I'd say this is a per-domain setting, where the domainadmin can enable/disable for the whole domain and a user can decide with whom they'd want to share.

**Comment by JayBeRayBearGun** [comment]
+1 @tuxis-ie

**Comment by tonioo** [comment]
@JayBeRayBearGun Thank you :)
