### ISSUE TITLE
Restrict Admin-panel access for admins

### ISSUE THREAD

**Issue by SomeGeek** [modoboa/modoboa#617]
Restrict the ability for administrators to logon everywhere.
- Use ACL's to limit administrator logons
- Enforce 2-factor authentication
- Use brute-force protection for the login-field

**Comment by web-refinery** [comment]
2-factor authentication seems like a good idea - but it should be opt-in.

**Comment by tonioo** [comment]
Something like oAuth ?

**Comment by mundschenk-at** [comment]
I'd be interested as well. oAuth is used to authenticate with a different service, though, no?

**Comment by tonioo** [comment]
@mundschenk-at What do you propose?

**Comment by mundschenk-at** [comment]
An extension that implements TOTP for admins (and optionally users). Other schemes (Yubi keys) could follow, but TOTP is more widespread.

**Comment by floreal797** [comment]
+1 I would be very interested by this feature
