### ISSUE TITLE
Support One-Time passwords also for users

### ISSUE THREAD

**Issue by SomeGeek** [modoboa/modoboa#618]
Passwords are becoming more aged these days. Many services are integrating two-factor authentication, which is also great for Modoboa. There are many apps (Android/iOS/WinPhone) acting as a token. Adding it is as easy as scanning a QR-code.

We should make Postfix/Dovecot support two-factor authitencation for 'unknown' places. It wouldn't make sense to enter your password everytime receiving your mail in your desktop mail client, for example.

**Comment by tonioo** [comment]
What do you mean by "one-time password" ? Do you have a use case ?

**Comment by mundschenk-at** [comment]
I assume he means 2-factor authentication with TOTP ([time-based one-time passwords](https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm)).

**Comment by tonioo** [comment]
Maybe. Do you know any django implementation?.

**Comment by mundschenk-at** [comment]
There is one on https://github.com/mtigas/django-twofactor, but it's unmaintained. I'm pretty sure there are others though.

**Comment by florealcab** [comment]
This feature (TOTP) is very important to improve security of mails. I'm really awaiting it. I see it's plan for the 2.0 version. This version will be release in next months? Next years? Couple of years? Any idea? Thank you for making modoboa, it's a very nice software!

**Comment by tonioo** [comment]
@florealcab No release date yet. Depends on the time we can invest on Modoboa...

**Comment by tonioo** [comment]
FYI, you can sponsor this feature: https://modoboa.org/en/projects/10/.
