### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by patrickbenkoetter** [modoboa/modoboa#634]
Modo should have a password generator, that generates and sets passwords on request.
- The password generator should be configurable and allow to set a password policy for passwords of specific complexity
- It should be possible to create new passwords
- It should be possible to create AND set passwords to make sure users really use the password.
- Maybe the password generator could/should be used in combinatation with a password reset service

**Comment by eberkund** [comment]
Should this be done in the front end with JavaScript or backend with Python?

**Comment by tonioo** [comment]
If we implement a password reset service, it means the generation must be done on the backend. What do you think ?

**Comment by eberkund** [comment]
Yeah for a password reset that would be what makes sense. I was thinking of other ways sites allow passwords to be reset but now that I've thought about it, emailing out a pregenerated random password is the simplest way, and just as effective. When someone is creating a new account we could have a JS call to fetch new random passwords from the backend, which could tie into the REST API you mentioned on the other thread.
