### ISSUE TITLE
Can't save settings

### ISSUE THREAD

**Issue by ddt-consult** [modoboa/modoboa#793]
when I click "Save" on the administration tab of the modoboa parameters,
nothing happens. Turning on DEBUG and going to
http://server/vmailadmin/core/parameters/save/
shows this:

> Environment:
> 
> Request Method: GET
> Request URL: http://localhost:9980/vmailadmin/core/parameters/save/
> 
> Django Version: 1.7.10
> Python Version: 2.7.9
> Installed Applications:
> ('django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.sites',
>  'django.contrib.staticfiles',
>  'reversion',
>  'modoboa',
>  'modoboa.core',
>  'modoboa.lib',
>  'modoboa_admin_limits',
>  'modoboa_admin_relaydomains',
>  'modoboa_stats',
>  'modoboa_radicale',
>  'modoboa_webmail',
>  'modoboa_admin',
>  'modoboa_sievefilters',
>  'modoboa_imap_migration')
> Installed Middleware:
> ('x_forwarded_for.middleware.XForwardedForMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.locale.LocaleMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware',
>  'modoboa.lib.middleware.AjaxLoginRedirect',
>  'modoboa.lib.middleware.CommonExceptionCatcher',
>  'modoboa.lib.middleware.RequestCatcherMiddleware')
> 
> Traceback:
> File "/usr/local/share/python-venv/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
> 1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
>    File "/usr/local/share/python-venv/lib/python2.7/site-packages/django/db/transaction.py" in inner
> 2.                 return func(_args, *_kwargs)
>    File "/usr/local/share/python-venv/lib/python2.7/site-packages/django/db/transaction.py" in inner
> 3.                 return func(_args, *_kwargs)
>    File "/usr/local/share/python-venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
> 4.                 return view_func(request, _args, *_kwargs)
>    File "/usr/local/share/python-venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
> 5.                 return view_func(request, _args, *_kwargs)
>    File "/usr/local/share/python-venv/lib/python2.7/site-packages/modoboa/core/views/admin.py" in saveparameters
> 6.         if form.is_valid():
>    File "/usr/local/share/python-venv/lib/python2.7/site-packages/django/forms/forms.py" in is_valid
> 7.         return self.is_bound and not bool(self.errors)
>    File "/usr/local/share/python-venv/lib/python2.7/site-packages/django/forms/forms.py" in errors
> 8.             self.full_clean()
>    File "/usr/local/share/python-venv/lib/python2.7/site-packages/django/forms/forms.py" in full_clean
> 9.         self._clean_form()
>    File "/usr/local/share/python-venv/lib/python2.7/site-packages/django/forms/forms.py" in _clean_form
> 10.             cleaned_data = self.clean()
>     File "/usr/local/share/python-venv/lib/python2.7/site-packages/modoboa/core/app_settings.py" in clean
> 11.         if cleaned_data["authentication_type"] != "ldap":
> 
> Exception Type: KeyError at /core/parameters/save/
> Exception Value: 'authentication_type'

**Comment by tonioo** [comment]
Hi,
can you tell me which versions you are using please ?

**Comment by ddt-consult** [comment]
I'm using what was current two days ago when I installed this server:

> (python-venv)root@mail:~# pip freeze
> Django==1.7.10
> LEPL==5.1.3
> MySQL-python==1.2.5
> Pillow==3.0.0
> argparse==1.2.1
> chardet==2.3.0
> dj-database-url==0.3.0
> django-passwords==0.3.4
> django-reversion==1.8.5
> django-versionfield2==0.4.0
> django-xforwardedfor-middleware==1.0
> factory-boy==2.6.0
> fake-factory==0.5.3
> future==0.15.2
> lockfile==0.8
> lxml==3.5.0
> modoboa==1.3.5
> modoboa-admin==1.1.2
> modoboa-admin-limits==1.0.2
> modoboa-admin-relaydomains==1.1.0
> modoboa-amavis==1.0.3
> modoboa-imap-migration==1.0.3
> modoboa-pdfcredentials==1.0.1
> modoboa-postfix-autoreply==1.1.1
> modoboa-radicale==1.0.3
> modoboa-sievefilters==1.0.3
> modoboa-stats==1.0.2
> modoboa-webmail==1.0.2
> passlib==1.6.5
> progressbar==2.3
> py-rrdtool==0.2.2
> pycrypto==2.6.1
> pytz==2015.7
> reportlab==3.2.0
> requests==2.8.1
> rfc6266==0.0.4
> sievelib==0.9.2
> six==1.10.0
> virtualenv==1.11.6
> wsgiref==0.1.2

**Comment by tonioo** [comment]
Do you have any special configuration ? (did you change something to online parameters)

I don't reproduce your issue on the official demo...

**Comment by ddt-consult** [comment]
No, there's no special configuration. I simply installed modoboa according to the user guide into a virtualenv, created a new SuperAdmin and deleted the default one, added a domain and 10 users. That's all. Then I wanted to set "administer mailboxes on the file-system" (my translation from German) to True but saving didn't work.

BTW: what are those online parameters I might have changed?

**Comment by tonioo** [comment]
Have you used the installer ?

**Comment by ddt-consult** [comment]
No. I installed modoboa according to the user guide.

BTW: I just noticed that saving works when I comment the radicale extension in settings.py.

**Comment by tonioo** [comment]
That's strange. Do you still encounter the issue if you activate the radicale extension ?

**Comment by ddt-consult** [comment]
Yes:
radicale active -> saving fails
radicale inactive -> saving works

**Comment by tonioo** [comment]
Still with the same stacktrace ?

Do you see any error into the Radicale tab ?

**Comment by ddt-consult** [comment]
Yes, with the same stacktrace.

No errors in the Radicale tab.
Now, after I set the Radicale "Server URL" parameter to some value and clicked "Save", saving on the Administration tab does work too.

**Comment by tonioo** [comment]
Ok I understand now. I really need to improve the way online settings are managed.

**Comment by tonioo** [comment]
Fixed by #951

**Comment by stooj** [comment]
I am experiencing the same issue with 1.9.0 - the modoboa parameters form was unresponsive until I disabled the `modoboa_radicale` app in settings.py.

Turning on DEBUG in settings.py did not seem to make a difference (the save button is just unresponsive). Is there some other way to get a decent trace that I am missing? I'm new to modoboa.

**Comment by tonioo** [comment]
This can happen when a mandatory parameter is not filled. You should be redirected to the tab where the error lives... Maybe a javascript cache issue?
