### ISSUE TITLE
dedicated, password change-only page

### ISSUE THREAD

**Issue by cptMikky** [modoboa/modoboa#892]
It would be great to have a URL dedicated to password changes/resets only, mostly for scenarios where Modoboa serves as a configuration and management backend and users don't interface with Modoboa directly.

A (preferably skinable) simple web page with a simple form: login, old password, new password, repeat password and perhaps a reset password button sending new password to secondary e-mail (does Modoboa have this? Didn't find this option).

The idea is to isolate users from Modoboa in scenarios where they do not come to contact with it in any use cases and having them log in to an unknown environment might be confusing.

Please note that API is not the same as this feature and writing own service to change passwords via API is not viable as it would have to hold a full-access API key which is a security risk. This should be operable by user without any privileges.

**Comment by almereyda** [comment]
It seems Modoboa identities contain a secondary email field already.

Password-reset pages are also a high demand from our communities.

**Comment by tonioo** [comment]
A password reset service is available since 1.9.0.
