### ISSUE TITLE
Can't Add user

### ISSUE THREAD

**Issue by scrolls-mckenzie** [modoboa/modoboa#955]
I'm recently having issues adding new users. Receiving this response

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
.parseJSON()
jquery.min.js:3
Cwizard.prototype.post/<()
creation_wizard.js:61
.proxy/i()
jquery.min.js:3
b.Callbacks/c()
jquery.min.js:3
b.Callbacks/p.fireWith()
jquery.min.js:3
k()
jquery.min.js:5
.send/r()

**Comment by tonioo** [comment]
Can you set DEBUG to True inside settings.py and then reload uwsgi ?

Then, open a javascript debugger and look at the console tab, you should see more information.

**Comment by tonioo** [comment]
@scrolls-mckenzie ping

**Comment by scrolls-mckenzie** [comment]
Hello toonio,

 Apologies for late response.

 I have turned on debugging in the settings.py 
`DEBUG = True`

I also set the loggers to error level

```
    'loggers': {
        'modoboa.auth': {
            'handlers': ['syslog-auth', 'modoboa'],
            'level': 'ERROR',
            'propagate': True
        },
```
and restarted uwsgi
`service uwsgi reload`

I am using firefox with the debugger opened and i do not receive any more error messages than normal and what i previously posted is what i am getting. Should this also be logging to a file?

**Comment by tonioo** [comment]
This part uses AJAX calls so you won't see the real error unless you open a debugger and look at the console tab. You should see all requests made sent to the server, just open the one returning a 500 error and check the response.

**Comment by scrolls-mckenzie** [comment]
i am receiving a massive response starting with

POST 
XHR 
https://mail.eviport.com/admin/accounts/new/ [HTTP/1.1 500 Internal Server Error 459ms]
Headers
POST
Response
Cookies
ProgrammingError at /admin/accounts/new/
(1146, "Table 'modoboa.limits_userobjectlimit' doesn't exist")

do you need more info?

**Comment by tonioo** [comment]
Looks like you did not run the migrate command... Have you enabled the limits plugin recently?
Can you try the following command:
`> python manage.py migrate`

**Comment by tonioo** [comment]
@scrolls-mckenzie ping

**Comment by scrolls-mckenzie** [comment]
I have tried to run python manage.py migrate 


Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/modoboa/instance/instance/settings.py", line 242, in <module>
    from modoboa_amavis.settings import *
ImportError: No module named modoboa_amavis.settings



       Joel Garvey

      0410 577 272
 joelgarvey@me.com

**Comment by tonioo** [comment]
If you don't want to use the amavis extension, edit your settings.py
file and comment the line at the end (which tries to import amavis
settings).

**Comment by scrolls-mckenzie** [comment]
Why would i not want to use amavis? I am forwarding you the console output from the command you asked me to run. Disabling a module doesn't seem like a good fix.

**Comment by tonioo** [comment]
The output you pasted only says the amavis extension is not installed. To fix this, make sure the `modoboa-amavis` package is installed within your environment and that `modoboa_amavis` is listed inside `MODOBOA_APPS` (settings.py file).

**Comment by scrolls-mckenzie** [comment]
I have still been trying to run the command

`python manage.py migrate`

but every time I get another error that a module is not installed. This seems odd as i am currently running a version and have not uninstalled anything

the latest error

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named modoboa_webmail


I have had the same errors for amavis, pdfccedentials, stats and now webmail. I have been re-installing each module but find the whole process very odd. 
Why would all these modules say they don't exist if they are currently running.

**Comment by tonioo** [comment]
Have you mixed different virtualenv? Are you sure a virtualenv was loaded every time you made a modification? You may have installed packages in the default system path instead of your virtualenv?

**Comment by scrolls-mckenzie** [comment]
Can you specify what command to run the virtualenv. There is a reference to dependencies in the documentation but nothing about the actual activation of the virtualenv.

**Comment by scrolls-mckenzie** [comment]
So i activated the virtualenv via 
`virtualenv env`
`source env/bin/activate`

I then ran 

`python manage.py migrate`

Still getting errors.

`Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management`

 Would you recommend at this stage that a re-install is in order?

**Comment by tonioo** [comment]
Looks like django is not installed... Can you run this please (with virtualenv loaded):
$ pip install -U pip
$ pip list
You should get the list of all installed packages.

**Comment by scrolls-mckenzie** [comment]
I have cd to the modaboa/instance location
I activated the virtualenv and ran the commands you asked
My output is this 

`Package    Version`
---------- -------
`pip        9.0.1`
`setuptools 2.2`

**Comment by tonioo** [comment]
This is what I thought, it is empty. It means this virtualenv was never used to install packages before. How did you install modoboa?

**Comment by tonioo** [comment]
@scrolls-mckenzie ping

**Comment by AienTech** [comment]
I did as you told. Everything seems to be fine, but after creating 51 users, it suddenly appeared that I can't create a user anymore. I turned the `DEBUG` on and it shows me nothing. Is there anything i can do to fix it?

**Comment by AienTech** [comment]
all I'm getting is
```
POST https://mail.swwwan.com/admin/accounts/new/ 500 (Internal Server Error)
send @ jquery.min.js:5
ajax @ jquery.min.js:5
post @ creation_wizard.js:41
submit @ creation_wizard.js:105
i @ jquery.min.js:3
dispatch @ jquery.min.js:3
v.handle @ jquery.min.js:3
```

**Comment by tonioo** [comment]
@AienTech Click on the request that fails (network tab) and look at the response.

**Comment by AienTech** [comment]
Fixed it, it was an issue of my db configs

**Comment by malteneu** [comment]
Hi, I also cannot add users. Same errors and I tried to run manage.py but it didn't execute: 

`File "manage.py", line 16
     ) from exc
           ^`

Tried to find the orginal file in your repository, but didn't find it.
