### ISSUE TITLE
Automx

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa#967]
As Modoboa is approaching a more fine-grained control of mail domain's associated DNS records, this would also enable for an integration of https://github.com/sys4/automx / https://automx.org/en/ ( known from https://wiki.uberspace.de/mail:automx )

Additionally, proposing SRV records for `_imaps._tcp.` and `_submission._tcp.` (as seen at OVH) may additionally happen in the installation documentation or by the webinterface (think of the DNS check view of Mailinabox).

**Comment by almereyda** [comment]
Sys4 have been in touch before already at https://github.com/tonioo/modoboa/issues/575#issuecomment-48869053

**Comment by tonioo** [comment]
Yes, I already know Modoboa integrates well with automx (I did a few setups in the past). This is more an installer feature from my point of view.
SRV records generation (and others) is something I plan to add in the future.

**Comment by tonioo** [comment]
See https://github.com/modoboa/modoboa-installer/issues/98
