### ISSUE TITLE
Check DNS for autoconfig

### ISSUE THREAD

**Issue by neutrinus** [modoboa/modoboa#979]
Many email-clients use some kind of autoconfiguration to help users:
* thunderbird: https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration
* outlook: https://technet.microsoft.com/en-us/library/cc511507.aspx

It would be nice if modoboa beside checking rbls would also check if required dns records are set and if the autoconfig xml is reachable.

**Comment by almereyda** [comment]
This could probably lead to an integration with #967.

**Comment by tonioo** [comment]
IMO, we're talking about two different features:
1. make the installer deploy automx
2. Provide a tool within the UI to generate DNS records and to check if they are properly configured
