### ISSUE TITLE
Account creation with aliases from different domain fails

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa#980]
If I intend to create a `postmaster@somethi.ng` and want to set aliases like `postmaster@somethingel.se`, `hostmaster@somethingel.se` or `hostmaster@somethi.ng`, it only works if the additional domain aliases are removed.

**Comment by tonioo** [comment]
Can you explain your use case a bit more please?

**Comment by almereyda** [comment]
I wanted to create a general host-/postmaster mailbox which would take multiple aliases for different domains. Creation failed if I wanted to use multiple domains within the aliases; when the aliases came from the same domain, the command passed.

**Comment by tonioo** [comment]
Just to make sure I understand your use case, you try to create
something like this (in one step):

Account: test@domain.tld

Alias : alias@domain1.tld

Alias : alias@domain2.tld

And it fails?

The aliases you're using already exist or not?

**Comment by almereyda** [comment]
Yes, I am trying to create

Account: test@domain1.tld

Alias: alias1@domain1.tld
Alias: alias2@domain1.tld

Alias: alias1@domain2.tld
Alias: alias2@domain2.tld

The aliases don't exist yet, and creation fails if more than domain1.tld is
involved.

**Comment by tonioo** [comment]
I fail to reproduce your issue. I've just tried on the official demo and it works. What kind of account are you creating?

**Comment by tonioo** [comment]
@almereyda ping

**Comment by tonioo** [comment]
@almereyda Could you please give me more information ?

**Comment by Amzani** [comment]
Hello @tonioo 

Not sure if it's the same issue, but registering an external forward doesn't work in admin interface (when adding/editing accounts) /admin/identities

**How to reproduce :** 

```
1. Login with admin
2. Create an account like : foo@domain.com
3. Create a forward like : bar@gmail.com 
4. Send an email to foo@domain.com
```

**Expected**
Receive an email at bar@gmail.com

GET to /api/v1/aliases/ doesn't show the registered Alias/Forward.
  
But when i login with foo@domain.com to the admin panel, go to (/user/#forward/) and register the forward everything is fine.
 
Some Infos : 
- Modoboa version : 1.6.2 installed on ubuntu 14.04

**Comment by tonioo** [comment]
@Amzani I can't reproduce your issue. Can you tell we how you created this forward? (exactly)

**Comment by Amzani** [comment]
@tonioo this is some screenshot 
![step1](https://i.imgsafe.org/d52e496158.png)
![step2](https://i.imgsafe.org/d52e3c159f.png)

1. Forward to gmail dosn't work
2. my forward is not listed with GET to https://mydomain:443/api/v1/aliases/

**Comment by tonioo** [comment]
@Amzani Actually, you haven't created a forward but you have added an extra sender address for this account, ie. you're allowing your user to send messages using toto@gmail.com as sender. Just move your gmail address to the "Alias" field and it should work ;)

**Comment by tonioo** [comment]
@almereyda Are you talking about a creation from the web UI or from the API?

**Comment by Amzani** [comment]
@tonioo hmm i tried to add a @gmail.com adresse in the Alias section but i got this error message : 
"Ce domain local n'existe pas", maybe i'm missing something.
![image](https://i.imgsafe.org/8a7e974d6e.png)

I'm using the Admin UI https://mydomain/admin/identities/
Thanks

**Comment by tonioo** [comment]
@Amzani oups... Looks like forward creation is not allowed from this form. I'll fix that asap. As a workaround, just create the forward using the "New alias" button.

**Comment by tonioo** [comment]
@Amzani I realize my answer was wrong. When you create a new account, the alias section allows you to define one or more alias pointing to this account so they must be local. For example, you can't set a gmail.com address because you don't own the gmail.com domain. There is no bug here.
