### ISSUE TITLE
Can't populate if email longer than 30 caracters

### ISSUE THREAD

**Issue by tmartinfr** [modoboa/modoboa#993]
I'm storing my accounts using LDAP.
During first login to modoboa, the account is populated into the DB.
Email field is 254 caracters long, but the `last_name` is only 30 (https://github.com/modoboa/modoboa/blob/master/modoboa/core/models.py#L53).
But during populate, Modoboa store the email into the `last_name` field :

```
<django.db.backends.utils.CursorDebugWrapper object at 0x7f15f36df650> 	

(False,
 u'veryveryveryveryverylongemailaddress@example.com',
 u'',
 u'veryveryveryveryverylongemailaddress@example.com',
 u'',
 False,
 True,
 datetime.datetime(2016, 12, 23, 5, 46, 13, 912041, tzinfo=<UTC>),
 False,
 False,
 u'XXX',
 'en',
 96)

sql 	

u'UPDATE "core_user" SET "is_superuser" = %s, "username" = %s, "first_name" = %s, "last_name" = %s, "email" = %s, "is_staff" = %s, "is_active" = %s, "date_joined" = %s, "is_local" = %s, "master_user" = %s, "password" = %s, "last_login" = NULL, "language" = %s, "phone_number" = NULL, "secondary_email" = NULL WHERE "core_user"."id" = %s'
```

So using an email address more than 30 caracters fails.

**Comment by tonioo** [comment]
@tmartinfr That's strange. I might be related to the way your LDAP directory is configured. What kind of directory do you use? What schemas are you using?

**Comment by tmartinfr** [comment]
@tonioo I use OpenLDAP with very standard configuration. I'm not sure it's related. Just that the `last_name` field in the modoboa schema is limited to 30 caracters.

**Comment by tonioo** [comment]
The email value should not be used to fill in last name...

**Comment by tonioo** [comment]
By default, modoboa uses the `sn` ldap attribute to fill the last name. Can you check your directory?

**Comment by tmartinfr** [comment]
@tonioo Ok, so that's the reason! After checking, my directory's `sn` contains user email due to historical reasons. I'm going to change that. Thanks.
