### ISSUE TITLE
should ask to replace aliases after domain edition

### ISSUE THREAD

**Issue by Toniob** [modoboa/modoboa#996]
Hi,

It is currently possible to edit a domain and change its name. After such a modification, Modoboa should ask the user if he wants to update the aliases pointing to the old name and replace it with the new one.

Thanks

**Comment by tonioo** [comment]
This is also true for regular email addresses... I don't think it is the best option, maybe we could propose to create a domain alias using the old name?

**Comment by Toniob** [comment]
I don't think it's a good idea. What if you make a typo while editing the name ? You're going to keep the mistaken name in the list ? And I know how the sysadmins are (because I am one). In 6 months, we'll forget why there is an alias, delete it and so, brake the email aliases.

**Comment by tonioo** [comment]
Actually, it is not possible to rename a domain without renaming associated mailboxes. It could be possible with aliases but I don't like the idea to introduce a non consistent behaviour. I'm also wondering what would be the interest in renaming the domain without renaming aliases and mailboxes too. Can you explain your use case a bit more please?

**Comment by Toniob** [comment]
You can try this :
- create a domain test.example
- add an alias test@test.example to one of your identities
- rename the domain from test.example to test2.example
- check the aliases of your identity, test@test.example is not renamed
You can't even edit your identity anymore because one alias is wrong.

**Comment by tonioo** [comment]
Ok I understand, it is a bug :p
