### ISSUE TITLE
email takes (too) long to arrive in mailbox

### ISSUE THREAD

**Issue by JayBeRayBearGun** [modoboa/modoboa#997]
Modoboa noob here (i come from cyrus and exim environment)

Installation took some time but seems to work as intended.

For some reason it takes quite a long time for mail to appear in the users mailbox. It easily takes more than an hour or so. What could be wrong? How could I debug this?

**Comment by tonioo** [comment]
This delay is introduced by postscreen. (http://www.postfix.org/POSTSCREEN_README.html)
I suggest you check your logs (/var/log/mail.log) but, depending on the sender IP, delivery can take a long time...

**Comment by JayBeRayBearGun** [comment]
came across this line:
Jan  5 02:48:44 mail postfix/postscreen[20940]: close database /var/lib/postfix/postscreen_cache.db: No such file or directory (possible Berkeley 
DB bug)

could this cause the excessive delay?

**Comment by tonioo** [comment]
No, this is a know issue when running postfix in a chrooted env.
Do you see messages like this: "450 4.3.2 Service currently unavailable" in you logs?

**Comment by JayBeRayBearGun** [comment]
Yes! Quite a few even. With some different numeral prefixed though. Some related to legitimate email as far as I can see.

**Comment by tuxis-ie** [comment]
Outlook.com by any chance? They requeue messages from different machines, killing greylisting...

**Comment by JayBeRayBearGun** [comment]
@tuxis-ie no not that I can see,... some email is by myself send as tests

**Comment by tonioo** [comment]
Do you use an external address for your tests?

**Comment by JayBeRayBearGun** [comment]
Yes only external addresses,...

Okay here is a bit more extensive report. I looked at
/var/log/mail.log and /var/log/syslog

Most "unavailable" messages appear in mail.log and a few in syslog.

The "currently unavailable" messages are preceeded by numerals and
triplets. These vary between 450 4.3.2 and 550 5.7.1.

The latter definitely is spam and is blocked by
bl.spameatingmonkey.net (according to the log).

The "unavailable" messages preceded by 450 are either test messages
sent by me from my gmail account (or other) and some non-spam but
commercially tinted messages.

It should perhaps be noted that there currently is not a great deal of
regular email aimed at this domain.

**Comment by JayBeRayBearGun** [comment]
I just sent a test message with some actuall text from my personal account (non-gmail) which came through in record time :) Didn't check but it must have been within minutes.

**Comment by JayBeRayBearGun** [comment]
The messages that are preceded by 450 in the logs, get through with some delay it seems. As mentioned before these are commercial but non-spam (and a few test messages). I can't figure are what the actual delay is. My guess is in the order of hour(s).

**Comment by tonioo** [comment]
That's not an issue for new message/sender. Once a sender has been seen one time and has passed test, it is maintained in a temporary whitelist so next messages coming from him will pass without delay. The delay depends on which tests fail for a given sender.

**Comment by JayBeRayBearGun** [comment]
Ok then,... so you're basically saying it is functioning as it is supposed to be right?  

If so.,. YEAH! :)

PS: thanks for your handywork and patience.

**Comment by tonioo** [comment]
Yes, it is. This said, you're free to fine tune postscreen configuration
according to your needs ;)

**Comment by CyberfoxDK** [comment]
Tonioo   -   can you help with the whitelist location ?
Cant seem to find it.

**Comment by csmk** [comment]
> can you help with the whitelist location ?

🔗  http://www.postfix.org/POSTSCREEN_README.html#temp_white

**Comment by CyberfoxDK** [comment]
thanks, went through that already, so it seems like i may have missed somthing.
Will read it more thoroughly this time...

**Comment by JayBeRayBearGun** [comment]
OK, closing this issue as for me it seems to work. Thanks
